### PR TITLE
Vue3 ( fix ) implement reactive args + fix many vue app creation issue 

### LINKED ISSUE #13913: Addon-controls/Vue3: Control update causes full page re-render
**Describe the bug**
When toggling a control value the whole html get's replaced which in turn causes no animations to occur when switching a value of a prop.

If only the value of the prop updated, the component would show the animation correctly.

**Expected behavior**
Only props to update

**Screenshots**
https://user-images.githubusercontent.com/1305015/107917053-9b22dd00-6f67-11eb-8aaa-538f07da3ced.mp4

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
Environment Info:

  System:
    OS: Linux 5.8 Ubuntu 20.10 (Groovy Gorilla)
    CPU: (24) x64 AMD Ryzen 9 3900 12-Core Processor
  Binaries:
    Node: 12.16.1 - /tmp/fnm-shell-8506636/bin/node
    Yarn: 1.22.10 - /tmp/fnm-shell-8506636/bin/yarn
    npm: 6.14.8 - /tmp/fnm-shell-8506636/bin/npm
  Browsers:
    Chrome: 88.0.4324.150
    Firefox: 85.0.1
  npmPackages:
    @storybook/addon-actions: ^6.2.0-alpha.28 => 6.2.0-alpha.28 
    @storybook/addon-essentials: ^6.2.0-alpha.28 => 6.2.0-alpha.28 
    @storybook/addon-links: ^6.2.0-alpha.28 => 6.2.0-alpha.28 
    @storybook/vue3: ^6.2.0-alpha.28 => 6.2.0-alpha.28

### LINKED ISSUE #15567: Controls Addon - Vue - Update property without re-rendering story
**Describe the bug**
When updating vue props thorugh Controls the component remount (mounted lifecycle method relaunched)

**To Reproduce**
https://github.com/rtrap-rsi/vue-storybook-remount-issue

### PR DESCRIPTION
**Pull request by chakAs3**
Fixes #15567 fixes #13913

issue is not noticed but there is a risk of memory leak and performance issue as the vue component are growing and reactivity is complex 
## What I did 
use reactive args and update them inside of re-creating the whole component and story again and again when the user is interacting 

## How to test

1. Run a sandbox for template, e.g. `yarn task --task sandbox --start-from auto --template vue3-vite/default-ts`
2. Open Storybook in your browser
3. Use Vue devTools to inspect the reactivity and the number of Vue apps created  each you navigate the Tree
 
image

## Checklist

- [x] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)  yes
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [x] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Review by JReinhold — CHANGES_REQUESTED** [review]
The code looks clean! I haven't had a time to try it out yet, I'll do that next week.

Could you add a story that ensures the reactivity works? We can do that by having a stateful story that tests that changing args keeps the state.

So something like a button that increments a counter, and a play function that:

1. resets args (so the play function can be run again and again)
2. clicks button to increment counter
3. asserts counter is incremented
4. changes args by emitting an event
5. asserts that args have changed, eg. the label on the button has changed
6. asserts that the counter is still incremented - thus the state is still there and the component didn't remount.

All the necessary pieces for the above can be seen in [this play function](https://github.com/storybookjs/storybook/blob/next/code/ui/blocks/src/components/Story.stories.tsx#L75-L95), but I'm happy to be more specific if you need me to.

If you add the story to `code/renderers/vue3/template/stories` it will be picked up by CI.

**Comment by chakAs3** [comment]
Yeah good idea let me try  that I will come back to you @JReinhold if I have some questions

**Comment by chakAs3** [comment]
Hi, @JReinhold Let's start the week I hope you had a great weekend. I have done what you asked I think it needs some approval on chromatic since there are some new UIs, can you review it and let me know if it is OK for you?

File: code/renderers/vue3/src/render.ts [hunk 1]
```diff
@@ -50,15 +52,38 @@ export function renderToCanvas(
       Use "() => ({ template: '<my-comp></my-comp>' })" or "() => ({ components: MyComp, template: '<my-comp></my-comp>' })" when defining the story.
       `,
     });
-    return;
+    return () => {};
   }
 
-  showMain();
+  const storyArgs = element.props || (element as any).render?.().props || storyContext.args || {};
```
Comment (JReinhold) [inline code/renderers/vue3/src/render.ts:58]: Is it safe to call `render()` here? Or can it have side-effects, that would be triggered multiple times by this call? I'm no Vue expert

File: code/renderers/vue3/template/stories/ReactiveArgs.stories.js [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+    await updatedPromise;
+    await expect(canvas.getByRole('button')).toHaveTextContent('updated 1');
+
+    await userEvent.click(reactiveButton); // click to update the label to increment the count + 1
+    await expect(reactiveButton).toHaveTextContent('updated 2');
+
+    await channel.emit(RESET_STORY_ARGS, { storyId: id });
+    await new Promise((resolve) => {
+      channel.once(STORY_ARGS_UPDATED, resolve);
+    });
```
Comment (JReinhold) [inline code/renderers/vue3/template/stories/ReactiveArgs.stories.js:45]: I think you should move this to the beginning of the play function.
I was confused that the result was "Button 2", because I thought it meant the args had never updated, but then I realised it was because they were reset. if you reset at the beginning that confusion won't be a problem

File: code/renderers/vue3/src/render.ts [hunk 3]
```diff
@@ -73,3 +98,25 @@ function getSlots(props: Args, context: StoryContext<VueRenderer, Args>) {
...
+  Object.assign(reactiveArgs, nextArgs);
+}
+
+function teardown(
+  storybookApp: ReturnType<typeof createApp>,
+  canvasElement: VueRenderer['canvasElement']
+) {
+  storybookApp?.unmount();
+  if (map.has(canvasElement)) map.delete(canvasElement);
+}
```
Comment (JReinhold) [inline code/renderers/vue3/src/render.ts:122]: [The Chromatic tests](https://www.chromatic.com/test?appId=630513346a8e284ae244d415&id=63cda8c7ca2f3db4f73babaf) shows that force re-rendering doesn't work anymore. The story focuses the button, emits a "force re-render" event and expects the button to loose focus, but it doesn't.

I wonder if that is a bug in this code here. I _think_ that it could be fixed if you unmounted the `storybookApp` from the `map` instead of from the parameter. So something like this (untested):
```suggestion
function teardown(
  canvasElement: VueRenderer['canvasElement']
) {
  if(!map.has(canvasElement)){
    return;
  }
  const { vueApp } = map.get(canvasElement);
  vueApp.unmount();
  map.delete(canvasElement);
}
```

**Review by JReinhold — CHANGES_REQUESTED** [review]
great improvements! I have a few suggestions though.

File: code/renderers/vue3/src/render.ts (hunk 1 above)
Comment (chakAs3) [reply code/renderers/vue3/src/render.ts:58]: well anyway in Vue 3 render function arguments consistent in stateful and functional components, using h().
so if i want to render any component  i will have to 
  ```
  const FunctionalComp = props => h('button', `I'm functional ${props.label}`)
  const render = () =>  h(FunctionalComp, { label: 'Hello Story' }, [])
  const { type , props, children, key } = render()
  // pure  
  const pureRenderFn = props => h(MyButton,props)
  const { type : t , props : p, children : c , key:k } = pureRenderFn({label:'Im pure '})
```
i wrote this code [LINK](https://sfc.vuejs.org/#eNqlVF1r2zAU/SsXM1ACjv2yJ+MUtkFZB/tgfawLdRw5dmtLQrrOFoz/+64kK3Fa2EsxxpZ0dO45V/dqjD4plRwHHmVRIXJT6VYhGI6Dgq4Uh20RoSmim0IA2LftldQIIzQxaF5W2B45TFBr2QMjGrYAfT99HhClmFeTNEzYeA5o30oKg3A7COKSouy+yF7BFpSWysD2BpoV27ldLIanO9ZDfYbCh9HBkq7c8W56WheiQOIs0JNqLvZcE9lqbZmI6jpMTD7c1gzYV951Eu5R6hODKYaHR2IL6kbAk+IQe1UxVE3b7Yk9hhd+IvvbOdTK7UlTUIPmC3d2+NshbsW1t5CS2M29DZkBhrD0T4pDaBpVtELxsxenYBljNXpb7K73UtjkqOmEU3/EdKA58l51JXJ3uHnz0X1hcRRgkyQFF5g5M3k6g3Kl/a4gbBzh2/3PH4lB3YpDW59W3g9Mk4U5K1Ug83g7J2u/5FF5GmgvYn5Z9e+RESRcos95Hceg4Dp6ni7yYp8ojnxBb/pSJc9GCuqV0aVzXqAGIT4vuIiouO24iBpEZbI0NXVlK/7ZJFIfUvpL9CCw7XnCTb/ZafnHcE3ERRQvOFKaPHK98ZXF9f84X0Hf8FpaMjmRlWUPko/Q8a7XGRrmTF+6/FVvF4L/dUt7XpdDR5Bz+rMH5oqOPToX7grxVWDbzHQS6adE1PThfYswrUPOqGE0wbUAbHjo2tDmHjKv+0aet51nl1fE4kJwJe+Me/dW/rn+o+kfuwuvEw==) to illustrate what I'm saying 
in either case, they should return  type , props, children  

and storyFn()  returns  render function all time, the reason why i put   element.props  because the type definition is FunctionComponent normally i should be getting props from storyFn()  i have no club why they sending it as a Wrapper with render function inside

File: code/renderers/vue3/template/stories/ReactiveArgs.stories.js (hunk 2 above)
Comment (chakAs3) [reply code/renderers/vue3/template/stories/ReactiveArgs.stories.js:45]: yes you are better in the beginning.

File: code/renderers/vue3/src/render.ts (hunk 1 above)
Comment (JReinhold) [reply code/renderers/vue3/src/render.ts:58]: sounds good to me!

File: code/renderers/vue3/src/render.ts (hunk 3 above)
Comment (chakAs3) [reply code/renderers/vue3/src/render.ts:122]: > [The Chromatic tests](https://www.chromatic.com/test?appId=630513346a8e284ae244d415&id=63cda8c7ca2f3db4f73babaf) shows that force re-rendering doesn't work anymore. The story focuses the button, emits a "force re-render" event and expects the button to loose focus, but it doesn't.
> 
> I wonder if that is a bug in this code here. I _think_ that it could be fixed if you unmounted the `storybookApp` from the `map` instead of from the parameter. So something like this (untested):

I don't think that is the issue, cause that is the exact reference I'm passing can't fail should be removed.

File: code/renderers/vue3/src/render.ts (hunk 1 above)
Comment (chakAs3) [reply code/renderers/vue3/src/render.ts:58]: render() it is not rendering anything it returns a vnode,  virtual dom presentation of the component.

File: code/renderers/vue3/src/render.ts (hunk 3 above)
Comment (JReinhold) [reply code/renderers/vue3/src/render.ts:122]: you're right, it looks like there's actually something wrong with that story, that is unrelated to the work you're doing here. thanks for bringing it to my attention, I'm investigating if it is a regression.

**Review by JReinhold — APPROVED** [review]
Fantastic! 💪

File: code/lib/store/template/stories/rendering.stories.ts [hunk 4]
```diff
@@ -9,14 +9,14 @@ export default {
...
-
+// this is the story should be remove it will always fail, because forceReRender Api is removed in V7
 export const ForceReRender = {
   play: async ({ canvasElement }: PlayFunctionContext<any>) => {
     const channel = globalThis.__STORYBOOK_ADDONS_CHANNEL__;
     const button = await within(canvasElement).findByRole('button');
     await button.focus();
     await expect(button).toHaveFocus();
-
+    //  forceRender is not called in V7
```
Comment (tmeasday) [inline code/lib/store/template/stories/rendering.stories.ts:19]: Actually this test was a 🤦 . It should be emitting `FORCE_REMOUNT`. But the bigger issue is making sure it actual fails (chromatic & the test runner) when the assertion fails like this.

Comment (chakAs3) [reply code/lib/store/template/stories/rendering.stories.ts:19]: I have tested it is not trigging RORCE_RMOUNT,  renderToCanvas is not called at all

**Comment by iamandrewluca** [comment]
When passing some component through args, and that component is rendered using `<component/>` a warning will be in the console. Maybe instead of using `reactive`, better to use the [shallowReactive](https://vuejs.org/api/reactivity-advanced.html#shallowreactive) version or maybe even better `shallowRef`

```
vue received a component which was made a reactive object
```

**Comment by chakAs3** [comment]
> When passing some component through args, and that component is rendered using `<component/>` a warning will be in the console. Maybe instead of using `reactive`, better to use the [shallowReactive](https://vuejs.org/api/reactivity-advanced.html#shallowreactive) version or maybe even better [shallowRef](https://vuejs.org/api/reactivity-advanced.html#shallowref) 🤔
> 
> ```
> vue received a component which was made a reactive object
> ```

Oh yeah, passing a component as prop may cause some issues, as it should be serializable i hope it is a simple functional component, You are right in using shallowReactive to be safe, but we had some issues in case of altering the args with nested object that should be reactive in this case,  anyway i will give it another try and see what we can do here to avoid this 

Thanks for the advice
