### PR TITLE
CLI: Don't install addon-onboarding during minimal installs

### LINKED ISSUE #31459: [Bug]: Minimal install still installs addon-onboarding
### Describe the bug

We shouldn't install `addon-onboarding` when the user has opted out.

### Reproduction link

N/A

### Reproduction steps

1. Install Storybook with the minimal option
2. Inspect `package.json` and observe the onboarding addon

### System

```bash
Any
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ghengeveld**
Closes #31459

## What I did

Introduced a new `onboarding` feature which is only added for full, interactive installs (not "minimal" or in CI). Removed the addon from generators and instead added a list of supported project types to ensure addon-onboarding is only added for those project types.

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

## Greptile Summary

Makes the onboarding addon installation conditional, avoiding unnecessary dependencies in minimal Storybook installs.

- Added `skipInstall` flag in `code/lib/cli-storybook/src/add.ts` to control dependency installation during addon setup
- Improved test configuration handling in Vitest plugin with path normalization via `pathe.normalize()`
- Added documentation for preview-only builds with `--preview-only` flag in CLI options
- Aligned version numbers across packages from 9.1.0-alpha.1 to 9.1.0-alpha.2
- Enhanced documentation with comprehensive framework compatibility requirements in `docs/get-started/install.mdx`

### CODE REVIEW

File: code/lib/create-storybook/src/initiate.ts [hunk 1]
```diff
@@ -439,13 +450,15 @@ export async function doInitiate(options: CommandOptions): Promise<
     selectedFeatures.add('docs');
     if (isInteractive) {
       selectedFeatures.add('test');
+      selectedFeatures.add('onboarding');
```
Comment (yannbf) [inline code/lib/create-storybook/src/initiate.ts:453]: is this feature shown in the user prompts when running sb init?

Comment (yannbf) [reply code/lib/create-storybook/src/initiate.ts:453]: will it respect the global config when users decide not to use onboarding anymore in their machines?

File: code/lib/create-storybook/src/initiate.ts [hunk 2]
```diff
@@ -577,6 +590,10 @@ export async function doInitiate(options: CommandOptions): Promise<
     }
   }
 
+  if (selectedFeatures.has('onboarding') && !ONBOARDING_PROJECT_TYPES.includes(projectType)) {
+    selectedFeatures.delete('onboarding');
```
[the remark this answers is not in the document]
Comment (ghengeveld) [reply code/lib/create-storybook/src/initiate.ts:594]: `selectedFeatures` will get the `onboarding` value if the "recommended" setup is selected (the default). If it turns out that the project type doesn't support the onboarding flow, it's removed here.

File: code/lib/create-storybook/src/initiate.ts (hunk 1 above)
Comment (shilman) [reply code/lib/create-storybook/src/initiate.ts:455]: Yeah that makes sense to me. We might want to change it in the future if we provide some kind of onboarding for new users who did not set up the project. But we can cross that bridge when we come to it.

File: code/lib/create-storybook/src/initiate.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (shilman) [reply code/lib/create-storybook/src/initiate.ts:596]: Sorry somehow missed the second part of that if clause when reviewing on my phone. 🤦

File: code/lib/create-storybook/src/initiate.ts (hunk 1 above)
Comment (ghengeveld) [reply code/lib/create-storybook/src/initiate.ts:455]: Done. I disabled addon-onboarding for users who skipped the onboarding (either interactively, or through their global storybook settings file).

**Review by shilman — APPROVED** [review]
