### PR TITLE
Addon Docs: Skip `!autodocs` stories when computing primary story

### LINKED ISSUE #32683: [Bug]: !autodocs does not hide the preview of the story in the documentation if it is the first story
### Describe the bug

The `!autodocs` tag still displays the story as a **preview** of the component if it is the first story in the file. If the story is moved after the first one, it is completely hidden as expected.

Expected behavior: The `!autodocs` tag should hide the story completely from the documentation, regardless of its location within the file.

Image

[Reproduction Repo](https://github.com/Evi-2003/storybook-autodocs-issue)

### Reproduction link

https://68e7c3607e6dc5d3051d143e-zfywlhkgqk.chromatic.com/?path=/docs/example-button--docs

### Reproduction steps

1. Add `tag: [!autodocs]` to the first story in the code.  
2. In the component documentation, the preview of the component is the story to which we just added `!autodocs`.

### System

```bash
➜  storybook-docs-issue git:(main) ✗ npx storybook@latest info

Storybook Environment Info:

  System:
    OS: macOS 26.0
    CPU: (8) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.20.0 - ~/.nvm/versions/node/v22.20.0/bin/node
    npm: 10.9.3 - ~/.nvm/versions/node/v22.20.0/bin/npm <----- active
    pnpm: 10.17.1 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 141.0.7390.56
    Safari: 26.0
  npmPackages:
    @storybook/addon-docs: ^9.1.10 => 9.1.10
    @storybook/preset-create-react-app: ^9.1.10 => 9.1.10
    @storybook/react-webpack5: ^9.1.10 => 9.1.10
    eslint-plugin-storybook: ^9.1.10 => 9.1.10
    storybook: ^9.1.10 => 9.1.10
```

### Additional context

The story will be hidden under "STORIES" in the docs, but it is still shown as a preview if it's the first story in the file.

### PR DESCRIPTION
**Pull request by ia319**
Closes #32683

## What I did

Added usePrimaryStory hook to centralize primary story selection.

Refactored Primary.tsx to use usePrimaryStory instead of selecting stories[0].

Refactored Controls.tsx to call usePrimaryStory when no specific story is provided via of.

#### The changes in this PR are covered in the following automated tests:

- [x] stories
- [x] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing
**Translation:**

**Before modification:**

Write a sample sandbox:

```tsx
const meta = preview.meta({
  title: 'Example/Button',
  component: Button,
  parameters: {
    layout: 'centered',
  },
  tags: ['autodocs'], // **whether this line exists or not makes no difference**
  argTypes: {
    backgroundColor: { control: 'color' },
  },
  args: { onClick: fn() },
});

export const Primary = meta.story({
  args: {
    primary: true,
    label: 'utton',
  },
  tags: ["!autodocs"]
});

export const Secondary = meta.story({
  args: {
    label: 'Bllutton',
    size: 'medium',
  },
  tags: ["autodocs"] // **It works the same even without this line.**
});
```
Screenshot 2025-10-12 011351

From the logs, we can see that the handling of `tags` in
`code/core/src/preview-api/modules/store/csf/prepareStory.ts` is correct.
The issue lies in
`code/addons/docs/src/blocks/blocks/Primary.tsx`,
where `const primaryStory = context.componentStoriesFromCSFFile(csfFile)[0];`
always selects the **first** story directly.

**After modification:**
Screenshot 2025-10-12 014005
`Primary.tsx` and `Controls.tsx` now correctly retrieve the stories with the `autodocs` tag.

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [x] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [x] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/publish.yml) or locally with `gh workflow run --repo storybookjs/storybook publish.yml --field pr=<PR_NUMBER>`_

## Summary by CodeRabbit

* **Refactor**
  * Improved primary story selection logic to use tag-based detection for more reliable story resolution.
  * Simplified component architecture by removing prop-based configuration.

* **Tests**
  * Added comprehensive test coverage for story tag-based selection scenarios.

* **New Features**
  * Added example stories showcasing different autodocs tag configurations.

### CODE REVIEW

**Comment by ia319** [comment]
After pull from upstream and rebase, I ran `yarn test` and `yarn vitest run addons/vitest/src/node/test-manager.test.ts` locally. The tests passed, and I did not encounter this error. I don’t know how to proceed.

File: code/addons/docs/src/blocks/blocks/usePrimaryStory.ts
Comment (Sidnioulz) [inline code/addons/docs/src/blocks/blocks/usePrimaryStory.ts:1]: Open question: I think this could go into `code/core/src/preview-api/modules/addons/hooks.ts`. @JReinhold any thoughts on that? Would you also ever want to get the primary story for a component in e.g. a MCP server rather than the docs addon?

File: code/addons/docs/src/blocks/blocks/usePrimaryStory.ts [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+
+/**
+ * A hook to get the primary story for the current component It filters out stories with the
+ * '!autodocs' tag.
+ */
+export const usePrimaryStory = (): PreparedStory | undefined => {
+  const context = useContext(DocsContext);
+  const stories = context.componentStories();
+  return stories.find((story) => story.tags.includes('autodocs'));
+};
```
[the remark this answers is not in the document]
Comment (Sidnioulz) [reply code/addons/docs/src/blocks/blocks/usePrimaryStory.ts:15]: @ia319 hooks usually have their own test file. You should be able to mock the DocsContext and build tests that show
* The hook ignores `!autodocs` stories
* It takes the first story with `autodocs`

**Review by Sidnioulz — CHANGES_REQUESTED** [review]
LGTM, we're only missing a few tests and must check where to position the new hook in the codebase.

**Comment by Sidnioulz** [comment]
> After pull from upstream and rebase, I ran `yarn test` and `yarn vitest run addons/vitest/src/node/test-manager.test.ts` locally. The tests passed, and I did not encounter this error. I don’t know how to proceed.

Some tests are flaky :) If you suspect a flaky test, feel free to ask us on `#addons` to rerun the test jobs. If you ever have failing tests in `e2e-tests`, we can teach you how to run them!

**Review by Sidnioulz — APPROVED** [review]

File: code/addons/docs/src/blocks/blocks/usePrimaryStory.ts
Comment (Sidnioulz) [reply code/addons/docs/src/blocks/blocks/usePrimaryStory.ts:1]: After due consideration, this is the right location for the hook. Thanks @ia319! We'll take it from there!

**Review by Sidnioulz — CHANGES_REQUESTED** [review]
Hi @ia319,

We have one last change request for you. The Chromatic CI job shows that the `Primary` docs block now correctly filters out stories where `autodocs` is not set, but all the examples without toolbar are gone, because they all use `code/addons/docs/src/blocks/examples/StoriesParameters.stories.tsx` which does not have `autodocs`.

Could you please add `autodocs` to that example (as it's supposed to be used for toolbar testing), and add a few stories using `code/addons/docs/src/blocks/examples/ButtonNoAutodocs.stories.tsx` and `code/addons/docs/src/blocks/examples/ButtonSomeAutodocs.stories.tsx` to validate how the primary story loads?

The files to modify are
* `code/addons/docs/src/blocks/examples/StoriesParameters.stories.tsx`: add autodocs
* `code/addons/docs/src/blocks/blocks/Primary.stories.tsx`: add stories using the examples above

Thanks!

**Review by Sidnioulz — APPROVED** [review]
Thank you @ia319!
