### PR TITLE
Vite: Fix HMR issue for Storybook preview files

### LINKED ISSUE #26881: [Bug]: HMR of `preview.tsx` is not working
### Describe the bug

After upgrading to v8, HMR no longer works for `preview.tsx`.

### To Reproduce

preview.tsx

```tsx
import React from "react"
import { Decorator, Parameters } from "@storybook/react"
import { themes } from "@storybook/theming"
import { UITheme } from "./theme"
import { StoryProvider, DocsContainer } from "./components"

export const parameters: Parameters = {
  darkMode: {
    light: { ...themes.light, ...UITheme.light },
    dark: { ...themes.dark, ...UITheme.dark },
  },
  options: {
    storySort: {
      order: ["Documents", ["Welcome", "*"], "Components", "Hooks", "System"],
    },
  },
  a11y: {
    config: {
      rules: [
        { id: "color-contrast", enabled: false },
        { id: "landmark-unique", enabled: false },
      ],
    },
  },
  backgrounds: { disable: true },
  controls: { expanded: true },
  docs: { container: DocsContainer },
  layout: "fullscreen",
}

export const decorators: Decorator[] = [
  (Story) => {
    return (
      <StoryProvider>
        <Story />
      </StoryProvider>
    )
  },
]
```

components.tsx

```
import React, { FC, ReactNode, useEffect } from "react"
import { useDarkMode } from "storybook-dark-mode"
import {
  Container,
  ContainerProps,
  UIProvider,
  useColorMode,
} from "@yamada-ui/react"
import {
  DocsContainer as StorybookDocsContainer,
  DocsContainerProps,
} from "@storybook/blocks"
import { themes } from "@storybook/theming"

export const StoryProvider: FC<{ children: ReactNode }> = ({ children }) => {
  return (
    <UIProvider>
      <App p="md">{children}</App>
    </UIProvider>
  )
}

const App: FC<ContainerProps> = ({ p, children }) => {
  const { changeColorMode } = useColorMode()

  const colorMode = useDarkMode() ? "dark" : "light"

  useEffect(() => {
    changeColorMode(colorMode)
  }, [colorMode])

  return (
    <Container p={p} gap="md" alignItems="flex-start">
      {children}
    </Container>
  )
}

export const DocsContainer: FC<
  DocsContainerProps & { children: ReactNode }
> = ({ children, theme, ...rest }) => {
  const dark = useDarkMode()

  theme = dark ? themes.dark : themes.light

  return (
    <StorybookDocsContainer theme={theme} {...rest}>
      {children}
    </StorybookDocsContainer>
  )
}
```

Until v7, updating the `StoryProvider` in the `decorators`, i.e. `UIProvider`, made HMR work.

### System

```bash
System:
    OS: macOS 14.4.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nodenv/versions/20.11.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 10.2.4 - ~/.nodenv/versions/20.11.0/bin/npm
    pnpm: 8.13.1 - /usr/local/bin/pnpm <----- active
  npmPackages:
    @storybook/addon-a11y: ^8.0.8 => 8.0.8 
    @storybook/addon-backgrounds: ^8.0.8 => 8.0.8 
    @storybook/addon-docs: ^8.0.8 => 8.0.8 
    @storybook/addon-measure: ^8.0.8 => 8.0.8 
    @storybook/addon-storysource: ^8.0.8 => 8.0.8 
    @storybook/addon-viewport: ^8.0.8 => 8.0.8 
    @storybook/blocks: ^8.0.8 => 8.0.8 
    @storybook/cli: ^8.0.8 => 8.0.8 
    @storybook/manager-api: ^8.0.8 => 8.0.8 
    @storybook/react: ^8.0.8 => 8.0.8 
    @storybook/react-vite: ^8.0.8 => 8.0.8 
    @storybook/theming: ^8.0.8 => 8.0.8 
    storybook: ^8.0.8 => 8.0.8 
    storybook-dark-mode: ^4.0.1 => 4.0.1
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by valentinpalkovic**
Closes https://github.com/storybookjs/storybook/issues/26881

## What I did

Changes in `.storybook/preview.<ts|js>` files were not updated after an HMR event. A full browser reload was necessary. The issue was that even though the HMR event was sent successfully to the browser, the old preview annotation files were loaded.

**before**
```
1. `.storybook/preview.js` changes
2. HMR event sent to the browser
3. Preview annotations for `./.storybook/preview.js` loaded -> Since this was already imported once, the browser will return the cached version of the module and will not request it again
```

**after**
```
1. `.storybook/preview.js` changes
2. HMR event sent to the browser
3. Preview annotations for `./storybook/preview.js?t=<hash>` loaded -> This contains the latest changes
```

I have adjusted the logic to always consider the updated annotation files instead of a previous cached version.

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Review by tmeasday — APPROVED** [review]
This change makes sense to me!

File: code/builders/builder-vite/src/codegen-modern-iframe-script.ts [hunk 1]
```diff
@@ -21,9 +21,12 @@ export async function generateModernIframeScriptCode(options: Options, projectRo
   // and the HMR handler.  We don't use the hot.accept callback params because only the changed
   // modules are provided, the rest are null.  We can just re-import everything again in that case.
   const getPreviewAnnotationsFunction = `
-  const getProjectAnnotations = async () => {
+  const getProjectAnnotations = async (hmrPreviewAnnotationModules = []) => {
     const configs = await Promise.all([${previewAnnotationURLs
-      .map((previewAnnotation) => `import('${previewAnnotation}')`)
+      .map(
+        (previewAnnotation, index) =>
+          `hmrPreviewAnnotationModules.at(${index}) ?? import('${previewAnnotation}')`
```
Comment (IanVS) [inline code/builders/builder-vite/src/codegen-modern-iframe-script.ts:28]: This is a little hard to grok without the benefit of the explanation in your PR description, I wonder if it would be helpful to have a brief comment describing why this is necessary.
