### PR TITLE
Core: Remove maximum-scale=1 from viewport meta tag

### LINKED ISSUE #31272: [Bug]: Accessibility issue: maximum-scale=1 added to viewport meta tag in the `<head>` prevents zooming
### Describe the bug

Storybook adds `maximum-scale=1` to the viewport meta tag in the HTML head of the documentation pages, which disables zooming functionality. This creates a critical accessibility issue as users with visual impairments who need to zoom cannot do so.
This prevents compliance with **WCAG 2.1 Success Criterion 1.4.4 (Resize text)**, which requires that text can be resized without assistive technology up to 200 percent without loss of content or functionality.

Image

### Reproduction link

https://temporary-design-system-post.netlify.app/?path=/docs/introduction--docs

### Reproduction steps

1. Go to https://temporary-design-system-post.netlify.app/?path=/docs/introduction--docs
2. Right-click and inspect the page, then look at the <head> section
3. Check the meta tag: `<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">` inside `<head>`

### System

```bash
Storybook version 8.2.7
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yatishgoel**
Closes #31272

## What I did

Removed `maximum-scale=1` from the viewport meta tag in the Storybook manager UI. This property was originally introduced to prevent mobile browsers from zooming in onto a focused input field, specifically the search field. To remedy the original issue, the font size for the search input was bumped to 16px on mobile, and element padding/sizing for mobile has been updated accordingly.

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

## Greptile Summary

Removed 'maximum-scale=1' from the viewport meta tag in the HTML template to improve accessibility, allowing users to zoom content up to 200% as per WCAG 2.1 Success Criterion 1.4.4.

- Modified `code/core/assets/server/template.ejs` to remove maximum-scale restriction, enabling zoom functionality for users with visual impairments
- Change ensures compliance with WCAG accessibility standards for text resizing

### CODE REVIEW

**Review by Sidnioulz — COMMENTED** [review]
See https://github.com/storybookjs/storybook/issues/31272#issuecomment-2844680484. We'll need to check that the original bug no longer exists.

File: code/core/src/manager/components/sidebar/Search.tsx [hunk 1]
```diff
@@ -90,14 +90,14 @@ const IconWrapper = styled.div(({ theme, onClick }) => ({
...
-const Input = styled.input(({ theme }) => ({
+const Input = styled.input<{ isMobile: boolean }>(({ theme, isMobile }) => ({
   appearance: 'none',
   height: 28,
   width: '100%',
   padding: 0,
   border: 0,
   background: 'transparent',
-  fontSize: `${theme.typography.size.s1 + 1}px`,
+  fontSize: isMobile ? '16px' : `${theme.typography.size.s1 + 1}px`,
```
Comment (Sidnioulz) [inline code/core/src/manager/components/sidebar/Search.tsx:100]: `1rem` would be even better to correctly account for user zoom preferences, thought that might be better done globally throughout the app in a separate issue.

Comment (ghengeveld) [reply code/core/src/manager/components/sidebar/Search.tsx:100]: I don't know for sure whether 1rem would satisfy the requirement for the 16px font size behavior, and we also don't use relative font sizes anywhere else. Maybe we'll revisit this at some point but it would be a larger overhaul of the UI.

**Review by ghengeveld — APPROVED** [review]

File: code/core/src/manager/components/sidebar/Search.tsx (hunk 1 above)
Comment (Sidnioulz) [reply code/core/src/manager/components/sidebar/Search.tsx:100]: I'm fairly confident it would as we had the same exact a11y violation at Back Market and we switched offending inputs to `1rem` to fix it. I hadn't initially recognised it was the Safari input zoom bug until you commented.

But as you said, `rem` is in use nowhere in the UI so that should be addressed separately.
