### PR TITLE
CPC: Fix type generation

### LINKED ISSUE #28500: [Bug]: Type error in @storybook/react 8.2.0
### Describe the bug

Distribtued file `@storybook/react/dist/index.d.ts` contains on line 6

```ts
import * as core_dist_types from 'core/dist/types';
```

which cannot be resolved - this is presumably an issue in compilation, but it is causing type errors.

### Reproduction link

https://new-storybook.netlify.app/

### Reproduction steps

_No response_

### System

```bash
Storybook Environment Info:

  System:
    OS: Windows 10 10.0.19045
    CPU: (24) x64 Intel(R) Core(TM) i9-10920X CPU @ 3.50GHz
  Binaries:
    Node: 20.13.1 - 
    Yarn: 4.3.1 -  <----- active
    npm: 10.5.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (126.0.2592.87)
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ndelangen**
Closes https://github.com/storybookjs/storybook/issues/28500

## What I did

I ensured the problematic `.d.ts` output import paths no longer happen, by searching for the broken pattern and replacing it with the correct path, in the script generating these files.

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Review by valentinpalkovic — APPROVED** [review]

File: scripts/prepare/addon-bundle.ts [hunk 1]
```diff
@@ -190,6 +192,17 @@ const run = async ({ cwd, flags }: { cwd: string; flags: string[] }) => {
 
   await Promise.all(tasks);
 
+  const dtsFiles = await glob(outDir + '/**/*.d.ts');
```
Comment (yannbf) [inline scripts/prepare/addon-bundle.ts:195]: Can this be moved to a utility function, given that it's the same in these two scripts? And can you add a comment explaining why this is needed (can be done in the function)

**Review by yannbf — CHANGES_REQUESTED** [review]

**Review by yannbf — APPROVED** [review]
