### PR TITLE
A11y: Ensure popover dialogs have an ARIA label

### LINKED ISSUE #33494: [A11y]: Ensure all popovers have a dialog role and an aria-label
### Describe the bug

PopoverProvider doesn't force users to pass a dialog role popover and doesn't force them to pass an `ariaLabel` either. Let's fix that.

### Reproduction link

ø

### Reproduction steps

_No response_

### System

```bash
ø
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by gayanMatch**
Closes #33494

  ## What I did

  Added accessibility improvements to `PopoverProvider` component:

  - Added `ariaLabel` prop that provides an accessible label for the popover dialog, announced by screen readers when the popover opens
  - Added deprecation warning when `ariaLabel` is not provided (will become mandatory in Storybook 11)
  - Automatically injects `aria-haspopup="dialog"` to trigger elements, informing assistive technology that the button opens a dialog
  - Updated all existing `PopoverProvider` usages in the codebase with appropriate aria labels
  - Updated MIGRATION.md with documentation for the new prop and behavior

  ## Checklist for Contributors

  ### Testing

  #### The changes in this PR are covered in the following automated tests:

  - [x] stories
  - [ ] unit tests
  - [ ] integration tests
  - [ ] end-to-end tests

  #### Manual testing

  1. Run `yarn storybook:ui` in the `code` directory
  2. Navigate to **Overlay/PopoverProvider** stories
  3. Open browser DevTools and inspect a trigger button
  4. Verify `aria-haspopup="dialog"` is present on the trigger
  5. Click the trigger to open the popover
  6. Verify `aria-expanded="true"` appears on the trigger when open
  7. Inspect the popover element and verify `aria-label` is set

  ### Documentation

  - [ ] Add or update documentation reflecting your changes
  - [x] If you are deprecating/removing a feature, make sure to update
        [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

  ## Checklist for Maintainers

  - [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
  - [ ] Make sure this PR contains **one** of the labels below:
     <details>
       <summary>Available labels</summary>

    - `bug`: Internal changes that fixes incorrect behavior.
    - `maintenance`: User-facing maintenance tasks.
    - `dependencies`: Upgrading (sometimes downgrading) dependencies.
    - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
    - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
    - `documentation`: Documentation **only** changes. Will not show up in release changelog.
    - `feature request`: Introducing a new feature.
    - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
    - `other`: Changes that don't fit in the above categories.

     </details>
     
     

## Summary by CodeRabbit

* **New Features**
  * Popovers now support an ariaLabel for improved accessibility; many popovers and stories include example labels.
  * Tooltip system reimplemented as TooltipProvider with a new triggerOnFocusOnly option and defaultVisible control.

* **Breaking Changes**
  * WithTooltip public API simplified: removed trigger, interactive, followCursor, closeOnOutsideClick, closeOnTriggerHidden, withArrows, strategy, mutationObserverOptions, hasChrome.

Contribution by Gittensor, see my contribution statistics at https://gittensor.io/miners/details?githubId=132382032

### CODE REVIEW

File: code/addons/docs/src/blocks/components/ArgsTable/ArgValue.tsx [hunk 1]
```diff
@@ -203,6 +203,7 @@ const ArgSummary: FC<ArgSummaryProps> = ({ value, initialExpandedArgs }) => {
 
   return (
     <PopoverProvider
+      ariaLabel="Argument value details"
```
Comment (Sidnioulz) [inline code/addons/docs/src/blocks/components/ArgsTable/ArgValue.tsx]:
```suggestion
      ariaLabel="Arg value details"
```

We use the 'arg' wording in the documentation and product throughout.

File: code/core/src/components/components/Popover/PopoverProvider.tsx [hunk 2]
```diff
@@ -86,8 +102,19 @@ export const PopoverProvider = ({
...
       {...props}
     >
-      <Pressable>{children}</Pressable>
-      <PopoverUpstream placement={placement} offset={offset} style={{ outline: 'none' }}>
+      <Pressable>
+        {
+          cloneElement(children, {
+            'aria-haspopup': 'dialog',
+          } as DOMAttributes<Element>) as ReactElement<DOMAttributes<FocusableElement>, string>
+        }
```
Comment (Sidnioulz) [inline code/core/src/components/components/Popover/PopoverProvider.tsx:112]: ### Comment

Let's add a comment above the cloneElement to explain why we do this:
> `React-aria does not inject aria-haspopup="dialog" to support legacy screen readers, so we do it ourselves.`

## Type casting
I'd like to use as little type casting as possible.

Here in particular, `Pressable` has the following signature for `children`: `ReactElement<DOMAttributes, string>` so no need to cast to a more specific type.

The core problem is that `Pressable` uses `DOMAttributes` instead of `HTMLAttributes` (which includes the `AriaAttributes` interface). I'll report the issue upstream.

In the meantime, could you please use a `@ts-expect-error` decorator explaining that react-aria doesn't allow passing valid ARIA attributes to `Pressable` children?

File: code/core/src/components/components/Tabs/Tabs.hooks.tsx [hunk 3]
```diff
@@ -69,6 +69,7 @@ export function useList(list: ChildrenListComplete) {
       return (
         <>
           <PopoverProvider
+            ariaLabel="More tabs"
```
Comment (Sidnioulz) [inline code/core/src/components/components/Tabs/Tabs.hooks.tsx]:
```suggestion
            ariaLabel="Additional tabs"
```

File: code/core/src/manager/components/sidebar/ChecklistWidget.tsx
Comment (Sidnioulz) [inline code/core/src/manager/components/sidebar/ChecklistWidget.tsx]: @ghengeveld @MichaelArestad here I'm noticing we use `onboarding checking` in ARIA label but `guide` in the menu button.

Do you have preferences on how to harmonise?

File: code/core/src/manager/components/sidebar/ChecklistWidget.tsx [hunk 4]
```diff
@@ -255,6 +255,7 @@ export const ChecklistWidget = () => {
                   </CollapseToggle>
                   {loaded && (
                     <PopoverProvider
+                      ariaLabel="Checklist options"
```
Comment (Sidnioulz) [inline code/core/src/manager/components/sidebar/ChecklistWidget.tsx]: This should be `Onboarding guide menu` or `Onboarding checklist menu`. Let's wait for feedback from the team if possible. If you don't hear back from us within a few days, please use the first option.

File: code/core/src/manager/components/sidebar/ContextMenu.tsx [hunk 5]
```diff
@@ -196,6 +196,7 @@ export const useContextMenu = (context: API_HashEntry, links: Link[], api: API)
       onMouseEnter: handlers.onMouseEnter,
       node: shouldRender ? (
         <PopoverProvider
+          ariaLabel="Story actions"
```
Comment (Sidnioulz) [inline code/core/src/manager/components/sidebar/ContextMenu.tsx]:
```suggestion
          ariaLabel="Context menu"
```

We'll figure out a better name when we rewrite the sidebar. This menu is also used by components and docs so it can't mention stories.

File: code/core/src/manager/components/sidebar/RefIndicator.tsx [hunk 6]
```diff
@@ -155,6 +155,7 @@ export const RefIndicator = React.memo(
       return (
         <IndicatorPlacement ref={forwardedRef}>
           <PopoverProvider
+            ariaLabel="Storybook status"
```
Comment (Sidnioulz) [inline code/core/src/manager/components/sidebar/RefIndicator.tsx]:
```suggestion
            ariaLabel="Composed Storybook status"
```

File: MIGRATION.md [hunk 7]
```diff
@@ -627,6 +627,20 @@ The PopoverProvider component acts as a counterpoint to WithTooltip. When you wa
 
 PopoverProvider is based on react-aria. It must have a single child that acts as a trigger. This child must have a pressable role (can be clicked or pressed) and must be able to receive React refs. Wrap your trigger component in `forwardRef` if you notice placement issues for your popover.
 
+##### Added: ariaLabel
+
+The `ariaLabel` prop was added to provide an accessible label for the popover dialog. This label is announced by screen readers when the popover opens. **This prop will become mandatory in Storybook 11.** Provide a concise description of the popover's purpose.
```
Comment (Sidnioulz) [inline MIGRATION.md]:
```suggestion
The `ariaLabel` prop was added in Storybook 10.2 to provide an accessible label for the popover dialog. This label is announced by screen readers when the popover opens. `ariaLabel` will become mandatory in Storybook 11.
```

**Review by Sidnioulz — COMMENTED** [review]
LGTM overall, only minor edits needed. Thanks for giving this a go, @gayanMatch! Please re-request a review once you've addressed the comments!

File: MIGRATION.md [hunk 8]
```diff
@@ -627,6 +627,20 @@ The PopoverProvider component acts as a counterpoint to WithTooltip. When you wa
...
+```tsx
+<PopoverProvider ariaLabel="Share options" popover={<ShareMenu />}>
+  <Button ariaLabel="Share">Share</Button>
+</PopoverProvider>
+```
+
+##### Automatic aria-haspopup
+
+PopoverProvider now automatically sets `aria-haspopup="dialog"` on the trigger element. You no longer need to manually add this attribute to your trigger buttons.
+
```
Comment (Sidnioulz) [inline MIGRATION.md]:
```suggestion

```

This part is not relevant, we only document breaking changes.

File: code/core/src/manager/components/sidebar/ChecklistWidget.tsx (hunk 4 above)
Comment (gayanMatch) [reply code/core/src/manager/components/sidebar/ChecklistWidget.tsx]: I used `Onboarding guide menu` for now

**Review by Sidnioulz — APPROVED** [review]
Thanks @gayanMatch 🙇

File: MIGRATION.md [hunk 9]
```diff
@@ -627,6 +627,16 @@ The PopoverProvider component acts as a counterpoint to WithTooltip. When you wa
 
 PopoverProvider is based on react-aria. It must have a single child that acts as a trigger. This child must have a pressable role (can be clicked or pressed) and must be able to receive React refs. Wrap your trigger component in `forwardRef` if you notice placement issues for your popover.
 
+##### Added: ariaLabel
+
+The `ariaLabel` prop was added in Storybook 10.2 to provide an accessible label for the popover dialog. This label is announced by screen readers when the popover opens. `ariaLabel` will become mandatory in Storybook 11.
```
Comment (Sidnioulz) [inline MIGRATION.md]:
```suggestion
The `ariaLabel` prop was added in Storybook 10.3 to provide an accessible label for the popover dialog. This label is announced by screen readers when the popover opens. `ariaLabel` will become mandatory in Storybook 11.
```
