### PR TITLE
Builder-Webpack5: Fix @vitest/mocker resolution issue

### LINKED ISSUE #33306: [Bug]: Build fails with "@vitest/mocker" resolution error in Docker when Vitest is not used
### Describe the bug

When building a Next.js application with Storybook 10.1.4 in a Docker environment, the build process fails with module resolution errors for @vitest/mocker and @vitest/mocker/browser. This occurs even though:
- Vitest is not installed or used in the project
- No test-related Storybook addons are configured
- The mocker runtime functionality is not needed

This is how my `main.ts` looks like:
```
// .storybook/main.ts
import type { StorybookConfig } from 'storybook/internal/types';

const config: StorybookConfig = {
  stories: ['../src/__stories__/**/*.stories.tsx'],
  addons: ['@storybook/addon-a11y', '@storybook/addon-docs'],
  framework: '@storybook/nextjs',
};

module.exports = config;
```
This is the error I am encountering when I try to build storybook in docker: 
```
✘ [ERROR] Could not resolve "@vitest/mocker"

    node_modules/storybook/assets/server/mocker-runtime.template.js:1:31:
      1 │ import { MockerRegistry } from '@vitest/mocker';
        ╵                                ~~~~~~~~~~~~~~~~

  You can mark the path "@vitest/mocker" as external to exclude it from the bundle, 
  which will remove this error and leave the unresolved path in the bundle.

✘ [ERROR] Could not resolve "@vitest/mocker/browser"

    node_modules/storybook/assets/server/mocker-runtime.template.js:2:50:
      2 │ ... ModuleMocker, createCompilerHints } from '@vitest/mocker/browser';
        ╵                                              ~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@vitest/mocker/browser" as external to exclude it from the bundle, 
  which will remove this error and leave the unresolved path in the bundle.
```
The build error shows that node_modules/storybook/assets/server/mocker-runtime.template.js is being processed during the build, causing it to attempt to resolve Vitest dependencies that don't exist.

My current workaround is to install `@vitest/mocker` and `vite`, but ideally I would not need to install these since I'm not testing my storybook components. 

### Reproduction link

No link for this.

### Reproduction steps

1. Create a Next.js project with Storybook 10.1.4
2. Configure Storybook with basic addons (no test addons)
3. Build the application in a Docker container
4. Observe the build failure

### System

```bash
│  Storybook Environment Info:
│

│  System:
│  OS: macOS 26.1
│  CPU: (12) arm64 Apple M2 Pro
│  Shell: 5.9 - /bin/zsh
│  Binaries:
│  Node: 22.18.0 
│  Yarn: 1.22.22
│  npm: 10.9.3 
│  pnpm: 8.15.2 - /opt/homebrew/bin/pnpm
│  Browsers:
│  Chrome: 143.0.7499.41
│  Safari: 26.1
│  npmPackages:
│  @storybook/addon-a11y: 10.1.4 => 10.1.4
│  @storybook/addon-docs: 10.1.4 => 10.1.4
│  @storybook/nextjs: 10.1.4 => 10.1.4
│  storybook: 10.1.4 => 10.1.4
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by valentinpalkovic**
Closes https://github.com/storybookjs/storybook/issues/33306

## What I did

Storybook core now generates the runtime during build time, so @vitest/mocker and @vitest/mocker/browser are no longer resolved during a consumer’s app build.

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This pull request has been released as version `0.0.0-pr-33315-sha-a17762c8`. Try it out in a new sandbox by running `npx storybook@0.0.0-pr-33315-sha-a17762c8 sandbox` or in an existing project with `npx storybook@0.0.0-pr-33315-sha-a17762c8 upgrade`.
<details>
<summary>More information</summary>

| | |
| --- | --- |
| **Published version** | [`0.0.0-pr-33315-sha-a17762c8`](https://npmjs.com/package/storybook/v/0.0.0-pr-33315-sha-a17762c8) |
| **Triggered by** | @valentinpalkovic |
| **Repository** | [storybookjs/storybook](https://github.com/storybookjs/storybook) |
| **Branch** | [`valentin/fix-vitest-mocker-resolution`](https://github.com/storybookjs/storybook/tree/valentin/fix-vitest-mocker-resolution) |
| **Commit** | [`a17762c8`](https://github.com/storybookjs/storybook/commit/a17762c8ce9c6dcc9a4b3131aa7f464ce9a98b53) |
| **Datetime** | Thu Dec 11 18:25:44 UTC 2025 (`1765477544`) |
| **Workflow run** | [20143262351](https://github.com/storybookjs/storybook/actions/runs/20143262351) |

To request a new release of this pull request, mention the `@storybookjs/core` team.

_core team members can create a new canary release [here](https://github.com/storybookjs/storybook/actions/workflows/publish.yml) or locally with `gh workflow run --repo storybookjs/storybook publish.yml --field pr=33315`_
</details>

## Summary by CodeRabbit

* **Refactor**
  * Simplified mocking runtime delivery to use a static runtime file, streamlining runtime injection and module resolution.
  * Centralized mocking utilities into the core package and re-exported redirect helpers for easier use by builders.
  * Updated dev tooling plugins to inject the mocker runtime earlier and resolve its path more reliably.

* **Chores**
  * Removed builder-level dependency on an external mocker package; added it as a core dev dependency.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: code/core/scripts/generate-source-files.ts [hunk 1]
```diff
@@ -196,4 +196,16 @@ async function generateExportsFile(prettierConfig: prettier.Options | null): Pro
...
+
+  // Import and run the prebuild script
+  await import(pathToFileURL(scriptPath).href);
+}
+
+// Run both prebuild tasks
+Promise.all([generateSourceFiles(), prebuildMockerRuntime()]).catch((error) => {
+  console.error('Error during prebuild:', error);
+  process.exit(1);
+});
```
Comment (JReinhold) [inline code/core/scripts/generate-source-files.ts]: would it be simpler if that prebuild file just exported a function that was regularly imported and then called here, instead of this roundabout using dynamic import of the file path and such?

**Comment by MarcusUMN** [comment]
@valentinpalkovic is there any timeline when you think this would be able to be merged for general consumption? Thank you!

**Comment by valentinpalkovic** [comment]
This solution has to be reworked after internal review. This will very likely happen in about two weeks.

**Comment by domarmstrong** [comment]
Any further update around this? It would be great if it could be looked at because the version that introduced this issue also introduced a bug fix for a security vulnerability. So this is actually blocking us being able to get the security fix in as it totally breaks storybook for us.

> On December 11th, the Storybook team received a responsible disclosure alerting them to a potential vulnerability in certain built and published Storybooks.
The vulnerability is a bug in how Storybook handles environment variables defined in a .env file, which could, in specific circumstances, lead to those variables being unexpectedly bundled into the artifacts created by the storybook build command. When a built Storybook is published to the web, the bundle’s source is viewable, thus potentially exposing those variables to anyone with access. If those variables contained secrets, they should be considered compromised.

**Comment by valentinpalkovic** [comment]
I will try to get this resolved by the beginning of next week!

File: code/builders/builder-vite/src/plugins/vite-inject-mocker/plugin.ts [hunk 2]
```diff
@@ -1,58 +1,37 @@
...
       if (viteConfig.command === 'build') {
         this.emitFile({
           type: 'chunk',
-          id: join(
-            resolvePackageDir('storybook'),
-            'assets',
-            'server',
-            'mocker-runtime.template.js'
-          ),
+          id: join(resolvePackageDir('storybook'), 'dist', 'mocking-utils', 'mocker-runtime.js'),
```
Comment (JReinhold) [inline code/builders/builder-vite/src/plugins/vite-inject-mocker/plugin.ts]: duplicate of `mockerRuntimePath` above

File: code/builders/builder-vite/src/plugins/vite-inject-mocker/plugin.ts [hunk 3]
```diff
@@ -1,58 +1,37 @@
...
 export const viteInjectMockerRuntime = (options: {
   previewConfigPath?: string | null;
 }): import('vite').Plugin => {
+  // Get the actual file path so Vite can resolve relative imports
+  const mockerRuntimePath = join(
+    resolvePackageDir('storybook'),
+    'dist',
+    'mocking-utils',
+    'mocker-runtime.js'
+  );
```
Comment (JReinhold) [inline code/builders/builder-vite/src/plugins/vite-inject-mocker/plugin.ts:13]: I think it's safer to rely on `storybook`'s exports instead of digging directly into the `dist`. You should be able to do that with:

`fileURLToPath(import.meta.resolve('storybook/internal/mocking-utils/mocker-runtime'))`

File: code/builders/builder-vite/src/plugins/vite-inject-mocker/plugin.ts [hunk 4]
```diff
@@ -1,58 +1,37 @@
...
-import { fileURLToPath } from 'node:url';
-
 import { resolvePackageDir } from 'storybook/internal/common';
 
-import { exactRegex } from '@rolldown/pluginutils';
-import { dedent } from 'ts-dedent';
+import { join } from 'pathe';
 import type { ResolvedConfig, ViteDevServer } from 'vite';
 
 const entryPath = '/vite-inject-mocker-entry.js';
```
Comment (JReinhold) [inline code/builders/builder-vite/src/plugins/vite-inject-mocker/plugin.ts]: nit


```suggestion
const ENTRY_PATH = '/vite-inject-mocker-entry.js';
```

File: code/builders/builder-vite/src/plugins/vite-inject-mocker/plugin.ts [hunk 5]
```diff
@@ -1,58 +1,37 @@
...
 
-const entryCode = dedent`
-    <script type="module" src=".${entryPath}"></script>
-  `;
-
 let server: ViteDevServer;
```
Comment (JReinhold) [inline code/builders/builder-vite/src/plugins/vite-inject-mocker/plugin.ts]: I think this variable is unnecessary now.

File: code/core/scripts/generate-source-files.ts [hunk 6]
```diff
@@ -196,4 +196,7 @@ async function generateExportsFile(prettierConfig: prettier.Options | null): Pro
   );
 }
 
-generateSourceFiles();
+generateSourceFiles().catch((error) => {
+  console.error('Error during prebuild:', error);
+  process.exit(1);
+});
```
Comment (JReinhold) [inline code/core/scripts/generate-source-files.ts]: this swallows the stack trace, as a thrown error will provide more information than just `console.error(error)` does, so I think this should be reverted.

File: code/core/src/mocking-utils/runtime.ts [hunk 7]
```diff
@@ -1,28 +1,16 @@
...
-  const runtimeScriptContent = bundleResult.outputFiles[0].text;
-
-  return runtimeScriptContent;
+/**
+ * Returns the bundled mocker runtime script content. This is used by builders (webpack5, vite,
+ * etc.) to inject the mocker runtime into the preview iframe.
+ */
+export function getMockerRuntime(): string {
+  return readFileSync(
+    join(resolvePackageDir('storybook'), 'dist', 'mocking-utils', 'mocker-runtime.js'),
```
Comment (JReinhold) [inline code/core/src/mocking-utils/runtime.ts]: same comment about using `import.meta.resolve` here instead.

File: code/core/src/mocking-utils/runtime.ts [hunk 8]
```diff
@@ -1,28 +1,16 @@
...
-  });
-
-  const runtimeScriptContent = bundleResult.outputFiles[0].text;
-
-  return runtimeScriptContent;
+/**
+ * Returns the bundled mocker runtime script content. This is used by builders (webpack5, vite,
+ * etc.) to inject the mocker runtime into the preview iframe.
+ */
+export function getMockerRuntime(): string {
```
Comment (JReinhold) [inline code/core/src/mocking-utils/runtime.ts:8]: where is this function being used now?

File: scripts/build/utils/generate-bundle.ts [hunk 9]
```diff
@@ -124,7 +124,10 @@ export async function generateBundle({
     target: BROWSER_TARGETS,
     supported: SUPPORTED_FEATURES,
     splitting: false,
-    external: [], // don't externalize anything, we're using aliases to bundle everything into the runtimes
+    external: [
+      'msw/browser', 
+      'msw/core/http',
```
Comment (JReinhold) [inline scripts/build/utils/generate-bundle.ts:132]: can you add a comment for these two lines, which package/feature requires them?

**Review by JReinhold — CHANGES_REQUESTED** [review]

File: code/core/src/mocking-utils/runtime.ts (hunk 8 above)
Comment (valentinpalkovic) [reply code/core/src/mocking-utils/runtime.ts:8]: builder-webpack5 and in the rspack-based builder

**Review by JReinhold — APPROVED** [review]
Great work!
