### PR TITLE
A11y: Underline MDX links for WCAG SC 1.4.1 compliance

### LINKED ISSUE #33017: [Bug]: Links in MDX should have an underline styling by default
### Describe the bug

See https://www.chromatic.com/test?appId=635781f3500dd2c49e189caf&id=6913769e99ba81e2674e55f8

https://dequeuniversity.com/rules/axe/4.10/link-in-text-block?application=axeAPI

### Reproduction link

https://635781f3500dd2c49e189caf-siuwlkquds.chromatic.com/?path=/story/components-typography-documentwrapper--with-dom

### Reproduction steps

Go to repro link

### System

```bash
N/A
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by NikhilChowdhury27**
Closes #33017

## What I did

Added `textDecoration: 'underline'` to links in MDX/docs for WCAG 2.1 Level A accessibility compliance (Success Criterion 1.4.1 - Use of Color).

**Files changed:**
- `code/addons/docs/src/blocks/components/DocsPage.tsx` - Added underline to links in docs pages (`.sbdocs-content`)
- `code/core/src/components/components/typography/DocumentWrapper.tsx` - Added underline to links in MDX wrapper
- `code/core/src/components/components/typography/elements/A.tsx` - Added underline to anchor elements

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [x] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

**Tested:**
- ✅ Unit tests passing (7 tests in 2 files: `DocsPage.test.tsx`, `DocumentWrapper.test.tsx`)
- ✅ Visual verification at `http://localhost:6006`
- ✅ Links underlined in light and dark themes
- ✅ Anchor links (`.anchor`) correctly remain without underlines

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

**Note:** No documentation updates needed - visual accessibility enhancement only.

---

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`

- [ ] Make sure this PR contains **one** of the labels below:

    Available labels
    - **bug**: Internal changes that fixes incorrect behavior.
    - **maintenance**: User-facing maintenance tasks.
    - **dependencies**: Upgrading (sometimes downgrading) dependencies.
    - **build**: Internal-facing build tooling & test updates. Will not show up in release changelog.
    - **cleanup**: Minor cleanup style change. Will not show up in release changelog.
    - **documentation**: Documentation only changes. Will not show up in release changelog.
    - **feature request**: Introducing a new feature.
    - **BREAKING CHANGE**: Changes that break compatibility in some way with current major version.
    - **other**: Changes that don't fit in the above categories.

---

## 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/publish.yml) or locally with `gh workflow run --repo storybookjs/storybook publish.yml --field pr=<PR_NUMBER>`_

---

## Visual Verification

**All links now have underlines in both light and dark themes:**

![Links with underlines - light theme]
Screenshot 2025-11-24 at 7 31 25 PM

![Links with underlines - dark theme]
Screenshot 2025-11-24 at 7 31 15 PM

**References:**
- [WCAG 2.1 - Use of Color (Level A)](https://www.w3.org/WAI/WCAG21/Understanding/use-of-color.html)
- [Deque AXE Rule: link-in-text-block](https://dequeuniversity.com/rules/axe/4.10/link-in-text-block)

## Summary by CodeRabbit

* **Style**
  * Links in docs and typography now render underlined by default with improved thickness and offset for better visibility and WCAG alignment; decorative anchor markers remain ununderlined. Button-styled links and icon decorations remain non-underlined.

* **Tests**
  * Added accessibility tests verifying underline styling in light and dark themes, across multiple-link content, and confirming anchor markers and button-style links are not underlined.

### CODE REVIEW

**Review by Sidnioulz — CHANGES_REQUESTED** [review]
Thanks for giving this a go, @NikhilChowdhury27 

Please, when using AI, perform your own manual review before requesting a review from maintainers; there are many PRs and issues to review and the maintainers shouldn't need to delay other PRs to catch obvious issues with AI-generated code.

On the screenshots you provided, we can see links that are _not_ underlined. Therefore, some CSS changes are missing. Dosubot suggested that `sbdocs` classes [need to be updated](https://github.com/storybookjs/storybook/issues/33017#issuecomment-3521286051) and this is probably what's missing.

**Comment by Sidnioulz** [comment]
Also, please make sure your AI does _not_ remove any section from the PR template. We need the maintainer checklist and canary section preserved.

**Comment by NikhilChowdhury27** [comment]
@Sidnioulz 
 Hey! Really sorry about the mess in my initial submission - you were absolutely right about the missing CSS for `.sbdocs` classes and the PR template issue. 
 
 This is my first time contributing to Storybook and I definitely made some rookie mistakes with the screenshots. I've cleaned everything up now with all 3 CSS changes, proper tests. I really appreciate your patience and detailed feedback - once this gets merged I'll have way better context on how things work here and I promise I won't make the same mistakes again. 
 
 Thanks for taking the time to guide me through this! 🙏

**Comment by MichaelArestad** [comment]
Howdy! I appreciate the PR. We are still defining link styles and trying to find out exactly what is needed. I do expect to add underlines to link styles in MDX, but those underlines probably shouldn't be applied in instances where there an icon accompanying the link text. Conversely, we could remove the chevron from the Configure page.

As far as the link styles, I am leaning toward something like this:
```css
text-decoration-thickness: 0.5px; /* may also want relative */
  text-underline-offset: 0.11em;
```

**Comment by NikhilChowdhury27** [comment]
Hey Michael!
Thanks for the feedback! Before implementing the refined styling (text-decoration-thickness: 0.5px; text-underline-offset: 0.11em), I have a concern:
If we exclude underlines for every link with an icon, we'll need ongoing manual exclusions across the codebase as new components are added.

Alternative approach:
Target contextual text links specifically instead:

```
.sbdocs-content p a,
.sbdocs-content li a,
.sbdocs-content td a {
  text-decoration: underline;
  text-decoration-thickness: 0.5px;
  text-underline-offset: 0.11em;
}
```

**Comment by MichaelArestad** [comment]
>  Target contextual text links specifically instead:

@NikhilChowdhury27 This is a great call and will also reduce conflicts with buttons as it is in unlikely they are in those contexts. Let's try this!

**Comment by NikhilChowdhury27** [comment]
Hey @MichaelArestad ,

Thanks for the feedback! I've updated the implementation based on your suggestions.

**What changed:**
- Applied `text-decoration: underline` (0.5px thickness, 0.11em offset) to all text links across docs content and UI
- Button-styled links (like GitHub, Documentation buttons) correctly don't have underlines since they're visually buttons, not text links
- Footer text links (Chromatic, Storybook Community) have underlines as expected

**Technical approach:**
- Updated `DocsPage.tsx`, `DocumentWrapper.tsx`, `A.tsx`, and `link/link.tsx` to apply underlines globally
- Added specific exclusion for `.anchor` position markers
- Button component keeps `textDecoration: 'none'` since mixing button styling with underlines would be confusing UX

**Note:** The "What's new?" page loads content from an external iframe (`storybook.js.org`), so we can't control link styling there. Those links would need to be updated on the blog side.

I'll add two screenshots showing the fixed About page for reference. All tests pass ✅

Let me know if you'd like any adjustments!
Screenshot 2025-11-25 at 8 49 32 PM
Screenshot 2025-11-25 at 8 49 48 PM

File: code/core/src/components/components/typography/link/link.tsx [hunk 1]
```diff
@@ -67,7 +67,10 @@ const A = styled.a<LinkStylesProps>(
   ({ theme }) => ({
     display: 'inline-block',
     transition: 'all 150ms ease-out',
-    textDecoration: 'none',
+    // Add underlines to all links for WCAG 2.1 Level A compliance (SC 1.4.1)
+    textDecoration: 'underline',
+    textDecorationThickness: '0.5px',
+    textUnderlineOffset: '0.11em',
```
[the remark this answers is not in the document]
Comment (NikhilChowdhury27) [reply code/core/src/components/components/typography/link/link.tsx]: @coderabbitai 
Fixed in commit 5c715366722. Added `textDecoration: 'none'` to the `isButton` variant to prevent button-styled links from having underlines.

File: code/addons/docs/src/blocks/components/DocsPage.tsx [hunk 2]
```diff
@@ -114,7 +114,10 @@ export const DocsContent = styled.div(({ theme }) => {
       lineHeight: '24px',
 
       color: theme.color.secondary,
-      textDecoration: 'none',
+      // Add underlines to all links for WCAG 2.1 Level A compliance (SC 1.4.1)
```
Comment (Sidnioulz) [inline code/addons/docs/src/blocks/components/DocsPage.tsx]:
```suggestion
      // Ensure WCAG Level A compliance (SC 1.4.1), see https://www.w3.org/WAI/WCAG22/Techniques/failures/F73
```

Let's cite the example of failure that actually matched our situation.

File: code/addons/docs/src/blocks/components/DocsPage.tsx [hunk 3]
```diff
@@ -127,6 +130,8 @@ export const DocsContent = styled.div(({ theme }) => {
         top: 0,
         left: 0,
         bottom: 0,
+        // Anchor links are position markers and should not have underlines
```
Comment (Sidnioulz) [inline code/addons/docs/src/blocks/components/DocsPage.tsx]:
```suggestion
```
At the end of the day, this is a styling choice. I don't think we need to try and justify it other than "we think it looks okay".

More specifically, those links should be styled as buttons with a hover and focus state to pass WCAG, as they are buttons.

File: code/core/src/components/components/Button/Button.tsx [hunk 4]
```diff
@@ -320,6 +319,9 @@ const StyledButton = styled('button', {
       animation:
         animating && animation !== 'none' ? `${theme.animation[animation]} 1000ms ease-out` : '',
     },
+
+    // Button-styled links should not have underlines - they're visually buttons, not text links
+    textDecoration: 'none',
```
Comment (Sidnioulz) [inline code/core/src/components/components/Button/Button.tsx]:
```suggestion
    textDecoration: 'none',
```

This is obvious enough.

File: code/addons/docs/src/blocks/components/DocsPage.test.tsx [hunk 5]
```diff
@@ -0,0 +1,102 @@
...
+            </a>
+          </h2>
+        </ThemedDocsContent>
+      );
+
+      const anchor = container.querySelector('a.anchor');
+      expect(anchor).toBeTruthy();
+
+      const styles = window.getComputedStyle(anchor!);
+      // Anchor links should not have underline by default as per DocsPage.tsx styling
```
Comment (Sidnioulz) [inline code/addons/docs/src/blocks/components/DocsPage.test.tsx]:
```suggestion
```

File: code/core/src/components/components/typography/elements/A.tsx [hunk 6]
```diff
@@ -8,7 +8,10 @@ export const A = styled(Link)(withReset, ({ theme }) => ({
   lineHeight: '24px',
 
   color: theme.color.secondary,
-  textDecoration: 'none',
+  // Add underlines to all links for WCAG 2.1 Level A compliance (SC 1.4.1)
```
Comment (Sidnioulz) [inline code/core/src/components/components/typography/elements/A.tsx]:
```suggestion
  // Ensure WCAG Level A compliance (SC 1.4.1), see https://www.w3.org/WAI/WCAG22/Techniques/failures/F73
```

File: code/core/src/components/components/typography/elements/A.tsx [hunk 7]
```diff
@@ -21,5 +24,7 @@ export const A = styled(Link)(withReset, ({ theme }) => ({
     top: 0,
     left: 0,
     bottom: 0,
+    // Anchor links are position markers and should not have underlines
```
Comment (Sidnioulz) [inline code/core/src/components/components/typography/elements/A.tsx]:
```suggestionunderlines
```

File: code/core/src/components/components/typography/link/link.tsx [hunk 8]
```diff
@@ -67,7 +67,10 @@ const A = styled.a<LinkStylesProps>(
   ({ theme }) => ({
     display: 'inline-block',
     transition: 'all 150ms ease-out',
-    textDecoration: 'none',
+    // Add underlines to all links for WCAG 2.1 Level A compliance (SC 1.4.1)
```
Comment (Sidnioulz) [inline code/core/src/components/components/typography/link/link.tsx]:
```suggestion
    // Ensure WCAG Level A compliance (SC 1.4.1), see https://www.w3.org/WAI/WCAG22/Techniques/failures/F73
```

File: code/core/src/components/components/typography/link/link.tsx [hunk 9]
```diff
@@ -173,6 +176,8 @@ const A = styled.a<LinkStylesProps>(
           background: 'none',
           padding: 0,
           fontSize: 'inherit',
+          // Button-styled links should not have underlines
```
Comment (Sidnioulz) [inline code/core/src/components/components/typography/link/link.tsx]:
```suggestion
```

File: code/core/src/components/components/typography/DocumentWrapper.tsx [hunk 10]
```diff
@@ -78,6 +81,8 @@ export const DocumentWrapper = styled.div(({ theme }) => ({
     top: 0,
     left: 0,
     bottom: 0,
+    // Anchor links are position markers and should not have underlines
```
Comment (Sidnioulz) [inline code/core/src/components/components/typography/DocumentWrapper.tsx]:
```suggestion
```

File: code/core/src/components/components/typography/DocumentWrapper.tsx [hunk 11]
```diff
@@ -64,7 +64,10 @@ export const DocumentWrapper = styled.div(({ theme }) => ({
   },
   a: {
     color: theme.color.secondary,
-    textDecoration: 'none',
+    // Add underlines to all links for WCAG 2.1 Level A compliance (SC 1.4.1)
```
Comment (Sidnioulz) [inline code/core/src/components/components/typography/DocumentWrapper.tsx]:
```suggestion
    // Ensure WCAG Level A compliance (SC 1.4.1), see https://www.w3.org/WAI/WCAG22/Techniques/failures/F73
```

**Review by Sidnioulz — APPROVED** [review]
Code LGTM. Let's clean up comments before merging though.

**Comment by NikhilChowdhury27** [comment]
@Sidnioulz  Thanks for your feedbacks, I have resolved, please see if we can merge this pr.

Also going forward I will keep in mind all the comments you have given

File: code/core/src/components/components/typography/DocumentWrapper.tsx [hunk 12]
```diff
@@ -64,7 +64,10 @@ export const DocumentWrapper = styled.div(({ theme }) => ({
   },
   a: {
     color: theme.color.secondary,
-    textDecoration: 'none',
+    // Ensure WCAG Level A compliance (SC 1.4.1), see https://www.w3.org/WAI/WCAG22/Techniques/failures/F73
+    textDecoration: 'underline',
+    textDecorationThickness: '0.5px',
+    textUnderlineOffset: '0.11em',
```
Comment (MichaelArestad) [inline code/core/src/components/components/typography/DocumentWrapper.tsx:70]: After testing in a browser, this feels a bit better:

```suggestion
    textUnderlineOffset: '0.2em',
```

File: code/core/src/components/components/typography/elements/A.tsx [hunk 13]
```diff
@@ -8,7 +8,10 @@ export const A = styled(Link)(withReset, ({ theme }) => ({
   lineHeight: '24px',
 
   color: theme.color.secondary,
-  textDecoration: 'none',
+  // Ensure WCAG Level A compliance (SC 1.4.1), see https://www.w3.org/WAI/WCAG22/Techniques/failures/F73
+  textDecoration: 'underline',
+  textDecorationThickness: '0.5px',
+  textUnderlineOffset: '0.11em',
```
Comment (MichaelArestad) [inline code/core/src/components/components/typography/elements/A.tsx:14]: After testing in a browser, this feels a bit better:

```suggestion
    textUnderlineOffset: '0.2em',
```

File: code/core/src/components/components/typography/link/link.tsx [hunk 14]
```diff
@@ -67,7 +67,10 @@ const A = styled.a<LinkStylesProps>(
   ({ theme }) => ({
     display: 'inline-block',
     transition: 'all 150ms ease-out',
-    textDecoration: 'none',
+    // Ensure WCAG Level A compliance (SC 1.4.1), see https://www.w3.org/WAI/WCAG22/Techniques/failures/F73
+    textDecoration: 'underline',
+    textDecorationThickness: '0.5px',
+    textUnderlineOffset: '0.11em',
```
Comment (MichaelArestad) [inline code/core/src/components/components/typography/link/link.tsx]: After testing in a browser, this feels a bit better:

```suggestion
    textUnderlineOffset: '0.2em',
```

File: code/addons/docs/src/blocks/components/DocsPage.tsx [hunk 15]
```diff
@@ -114,7 +114,10 @@ export const DocsContent = styled.div(({ theme }) => {
       lineHeight: '24px',
 
       color: theme.color.secondary,
-      textDecoration: 'none',
+      // Ensure WCAG Level A compliance (SC 1.4.1), see https://www.w3.org/WAI/WCAG22/Techniques/failures/F73
+      textDecoration: 'underline',
+      textDecorationThickness: '0.5px',
+      textUnderlineOffset: '0.11em',
```
Comment (MichaelArestad) [inline code/addons/docs/src/blocks/components/DocsPage.tsx:120]: After testing in a browser, this feels a bit better:

```suggestion
    textUnderlineOffset: '0.2em',
```

**Review by MichaelArestad — DISMISSED** [review]
I am running this by the team from a design standpoint.

In the meantime, we shouldn't underline links that contain an SVG or are paired with an SVG. We can use the `:has()` psuedo selector in CSS to do this sort of reliably. [See this demo.](https://codepen.io/MichaelArestad/pen/QwNaxOV/373658673ea0798dd8f473f337a2268a)

**Comment by domyen** [comment]
Pretty much agree with @MichaelArestad. I'd like to limit the blast radius of this PR to only focus on one type of changes. It currently touches a bunch of different places in the app.

In general:
- I'm OK for links inside text blocks to have underlines so long as they're in the docs/mdx template (aka rendered in our docs mode)
- I don't think underlines should apply to links in these cases:
  - Links that have an icon accompaniment
  - Links **outside** of the docs/mdx template. So all of [these diffs](https://www.chromatic.com/test?appId=635781f3500dd2c49e189caf&id=692d9a6a9f9ec402ead4058a) are no-gos:
		image

Once we get that figured out and merged, I'm happy to expand the scope to more types of links (in separate PRs).

**Comment by NikhilChowdhury27** [comment]
Hi @MichaelArestad  and @domyen,

Thanks for the feedback! To make sure I scope this correctly, I have a few quick questions:

1. **Scope**: Should I only modify `DocsPage.tsx` and `DocumentWrapper.tsx`, or also `A.tsx` in `typography/elements/`? (Want to confirm `A.tsx` is docs-specific)

2. **SVG detection**: For the `:has(svg)` rule, should I handle:
   - Links that contain SVG (e.g., `<a><svg>...</svg>Text</a>`)
   - Links adjacent to SVG (e.g., `<svg/><a>Text</a>`)
   - Or both?

3. **Browser support**: Is modern browser support for `:has()` sufficient, or should I add a fallback?

Once confirmed, I'll update the PR to only touch docs/MDX template links with the SVG exclusion rule.

Thanks!

**Comment by NikhilChowdhury27** [comment]
Hey guys, Just pinging for an update

**Comment by Sidnioulz** [comment]
> **SVG detection**: For the `:has(svg)` rule, should I handle:
> 
> * Links that contain SVG (e.g., `<a><svg>...</svg>Text</a>`)
> * Links adjacent to SVG (e.g., `<svg/><a>Text</a>`)
> * Or both?

1. Modify all components
2. Inside the link only so we don't catch adjacent decorations, e.g. the code/core/src/components/components/typography/elements/A.tsx component has a `containsIcon` prop; use the prop if it exists, else use CSS `has` selectors. If you ever need to do this in JS with a query of children content, report back to us without submitting new code
3. We already use `:has` in the codebase

**Review by Sidnioulz — APPROVED** [review]
@MichaelArestad @domyen I've adjusted the underline decoration to use what Michael requested.

I've also ensured Manager UI components don't underline (this actually removes underlines in a link in the interactions addon panel), so the new style is only applied to docs content.

I continue to think we should underline _all_ links in the Manager UI but we can discuss that separately. Right now my concern is making sure user content is accessible by default and that this old PR gets merged.
