### PR TITLE
Bug: fix an issue where port can be NaN

### LINKED ISSUE #21553: [Bug]: Storybook 7 migration fails with main.cjs
### Describe the bug

I have a monorepo with packages that are `type: module` and contain storybooks. The config file has to be `main.cjs`, and so that main.cjs can import from src it sits in the src folder.

i.e. the config file is at `libs/my-lib/src/.storybook/main.cjs`

When running `npx storybook@next upgrade --prerelease --config-dir src/.storybook/` from `libs/my-lib`, I get the following error:

```console
╭ Migration check ran with failures 
│                                                
│         Successful migrations:
│                                           
│    eslintPlugin                   
│                                           
│           Failed migrations:  
│                                           
│       nodejs-requirement: 
│       Unable to find or evaluate src/.storybook/main.cjs: Cannot find module '✂️/libs/my-lib/src/.storybook/main'   │
│       Require stack:                                                                        
│       - ✂️/node_modules/@storybook/core-common/dist/index.js
│       - ✂️/node_modules/@storybook/telemetry/dist/index.js
│       - ✂️/node_modules/@storybook/cli/dist/generate.js
│       - ✂️/node_modules/@storybook/cli/bin/index.js  
```

### To Reproduce

_No response_

### System

_No response_

### Additional context

This isn't an issue for me as I can do the upgrade without the migration, but raising as perhaps you want to fix :)

Also this can be worked around by renaming main.cjs to main.js, running the migration and then naming back again.

### PR DESCRIPTION
**Pull request by ndelangen**
Closes https://github.com/storybookjs/storybook/issues/21553

## What I did

I found that if options.port is not set, it can cause a warning:

```
✔ Port NaN is not available. Would you like to run Storybook on port 51224 instead? … yes
```

### CODE REVIEW

File: code/lib/cli/src/generate.ts [hunk 1]
```diff
@@ -226,8 +226,10 @@ command('dev')
       ci: 'CI',
     });
 
-    // eslint-disable-next-line no-param-reassign
-    options.port = parseInt(`${options.port}`, 10);
+    if (parseInt(`${options.port}`, 10)) {
```
Comment (valentinpalkovic) [inline code/lib/cli/src/generate.ts:229]: Is port=0 a legit port?

Comment (ndelangen) [reply code/lib/cli/src/generate.ts:229]: no it isn't

**Review by valentinpalkovic — APPROVED** [review]
