### PR TITLE
Core: Improve framework field validation

### LINKED ISSUE #20651: Ensure users have a main.js framework field as part of the boot-up experience
### Describe the bug

SB7 requires that the user have a valid framework defined in their `.storybook/main.js` config. We have automigrations to address this, but apparently users are still getting caught without it, either due to problems with the automigration or users skipping the automigrations entirely.

When you have an invalid string as your `framework`, e.g. `foo`, it will throw the following error:

```
TypeError: Cannot destructure property 'renderer' of '(intermediate value)' as it is undefined.
    at buildDevStandalone ($SNIP/node_modules/@storybook/core-server/dist/index.js:33:1795)
    at async withTelemetry ($SNIP/node_modules/@storybook/core-server/dist/index.js:33:5533)
    at async dev ($SNIP/node_modules/@storybook/cli/dist/generate.js:441:440)
```

For reference, when you start Storybook with NO framework it reports the following: 

```
shilman@MBP14 react-vite-default-ts % yst
@storybook/cli v7.0.0-beta.29

WARN you have not specified a framework in your /Users/shilman/projects/storybookjs/storybook/sandbox/react-vite-default-ts/.storybook/main.js
✖ Would you like to send crash reports to Storybook? … yes
```

And when you have a renderer set as your framework `@storybook/react` it throws the following error:

```
ERR! Error: Invalid value of @storybook/react in the 'framework' field of Storybook config.
ERR! 
ERR! Please run 'npx sb@next automigrate'
...
```

### To Reproduce

```shell
Edit your `main.js` to set `framework` to `foo` and run `yarn storybook`
```

### System

_No response_

### Additional context

Suggested fixes:
- [x] Add old-style frameworks (`react`/`vue`/`vue3`/etc. to the list of known renderers)
- [x] Add check for invalid frameworks like "foo" and report the same error message as known renderers
- [x] Add the check for no framework & report the same error message as known renderers

### PR DESCRIPTION
**Pull request by yannbf**
Closes #20651

## What I did

The `framework` field is not validated in three different steps:

1. Is there no framework field? -> throw error, tell user to run automigrate
2. Is it a renderer package? -> throw error, tell user to run automigrate
3. Is it a known framework package? -> all good
4. Is it neither of the above? Does the package at least get resolved? else throw error

## How to test

1. Run a sandbox for template, e.g. `yarn task --task sandbox --start-from auto --template react-vite/default-ts`
2. Change the framework field to:
scenario 1: remove framework field
scenario 2: framework field value: `@storybook/react-vite`
scenario 3: framework field value: `react`
scenario 4: framework field value: `foo`

## Checklist

- [x] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [x] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

File: code/lib/core-common/src/utils/validate-config.ts [hunk 1]
```diff
@@ -1,19 +1,47 @@
...
+  }
+
+  // If we know about the framework, we don't need to validate it
+  if (Object.keys(frameworkPackages).includes(frameworkName)) {
+    return;
+  }
+
+  // If it's not a known framework, we need to validate that it's a valid package at least
+  try {
+    require.resolve(frameworkName);
```
Comment (shilman) [inline code/lib/core-common/src/utils/validate-config.ts:40]: How about this instead which is more specific, since we're using `frameworkName/preset` below in the code

```
require.resolve(join(frameworkName, 'preset'))
```

@ndelangen points out that this could be problematic in PnP mode, but I think it's OK because the `frameworkName` should be an absolute path in PnP mode anyway. WDYT?

File: code/lib/core-server/src/build-dev.ts [hunk 2]
```diff
@@ -19,7 +19,6 @@ import { global } from '@storybook/global';
 import { telemetry } from '@storybook/telemetry';
 
 import { join, resolve } from 'path';
-import { logger } from '@storybook/node-logger';
```
Comment (shilman) [inline code/lib/core-server/src/build-dev.ts:22]: Causing a failure in some CI tests

**Review by shilman — CHANGES_REQUESTED** [review]
Generally looks good. Have a couple suggested improvements

File: code/lib/core-common/src/utils/validate-config.ts (hunk 1 above)
Comment (yannbf) [reply code/lib/core-common/src/utils/validate-config.ts:40]: Not sure, I’ll wait for Norbert’s response!

Comment (shilman) [reply code/lib/core-common/src/utils/validate-config.ts:40]: he agrees with me, we discussed

**Review by shilman — APPROVED** [review]

File: code/lib/core-common/src/utils/validate-config.ts [hunk 3]
```diff
@@ -1,19 +1,48 @@
...
-// Checks that the framework name is not a renderer
-export function validateFrameworkName(frameworkName: string) {
+export function validateFrameworkName(frameworkName: string | undefined) {
+  const automigrateMessage = `Please run 'npx storybook@next automigrate' to automatically fix your config.
+
+  See the migration guide for more information: 
+  https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#new-framework-api\n`;
+
+  // Throw error if there is no framework field
+  // TODO: maybe this error should not be thrown if we allow empty Storybooks that only use "refs" for composition
```
Comment (ndelangen) [inline code/lib/core-common/src/utils/validate-config.ts:16]: AFAIK this is not something we allow/support.
The UI will show you a "empty storybook" warning if you'd do that.
