### PR TITLE
Automigration: Fail with non-zero exit code on migration failure

### LINKED ISSUE #31919: [Bug]: automigrate exits with 0 code even when migrations fail
### Describe the bug

I'm trying to add a post-dependabot script to my workflows to run storybook migrations:

```
      - name: Storybook migrations
        if: ${{ contains(github.event.pull_request.title, 'storybook') }}
        run: |
          yarn storybook automigrate -y && yarn fix &&\
          git add . &&\
          git commit -m "[dependabot skip] migrate" || true
```

On the first attempt at running this the `addon-a11y-addon-test` migration failed owing to a missing `vitest.setup.ts` file (issue to follow).

However, `automigrate`'s exit code appears to be solely based on what doctor says; it drops the results of migrations on the floor. As a result, all the above script did was check in an error log :(

### Reproduction link

-

### Reproduction steps

_No response_

### System

```bash
Storybook Environment Info:

  System:
    OS: Linux 6.6 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
    CPU: (24) x64 Intel(R) Core(TM) i9-10920X CPU @ 3.50GHz
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 22.15.1 - ~/.nvm/versions/node/v22.15.1/bin/node
    Yarn: 4.9.2 - /mnt/c/Program Files/nodejs/yarn <----- active
    npm: 10.9.2 - ~/.nvm/versions/node/v22.15.1/bin/npm
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mrginglymus**
Closes #31919

## What I did

Added a `--fail` option to the `automigrate` command indicating that any failed migrations should cause a non-zero exit code.

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This pull request has been released as version `0.0.0-pr-31923-sha-c04cd64d`. Try it out in a new sandbox by running `npx storybook@0.0.0-pr-31923-sha-c04cd64d sandbox` or in an existing project with `npx storybook@0.0.0-pr-31923-sha-c04cd64d upgrade`.
<details>
<summary>More information</summary>

| | |
| --- | --- |
| **Published version** | [`0.0.0-pr-31923-sha-c04cd64d`](https://npmjs.com/package/storybook/v/0.0.0-pr-31923-sha-c04cd64d) |
| **Triggered by** | @valentinpalkovic |
| **Repository** | [mrginglymus/storybook](https://github.com/mrginglymus/storybook) |
| **Branch** | [`fail-on-failed-migrations`](https://github.com/mrginglymus/storybook/tree/fail-on-failed-migrations) |
| **Commit** | [`c04cd64d`](https://github.com/mrginglymus/storybook/commit/c04cd64dc19a53d3ca71beaf8bc34e49660025eb) |
| **Datetime** | Mon Jul  7 10:58:08 UTC 2025 (`1751885888`) |
| **Workflow run** | [16115065163](https://github.com/storybookjs/storybook/actions/runs/16115065163) |

To request a new release of this pull request, mention the `@storybookjs/core` team.

_core team members can create a new canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=31923`_
</details>

## Greptile Summary

Added a new `--fail` flag to the Storybook CLI's automigrate command that causes non-zero exit codes when migrations fail, enhancing CI/CD pipeline capabilities.

- Added `fail` boolean option to `AutofixOptionsFromCLI` interface in `code/lib/cli-storybook/src/automigrate/types.ts`
- Implemented error throwing logic in `code/lib/cli-storybook/src/automigrate/index.ts` when migrations fail and fail flag is enabled
- Added new test cases in `code/lib/cli-storybook/src/automigrate/index.test.ts` to verify both soft and hard failure modes
- Added `--fail` (-f) option to CLI interface in `code/lib/cli-storybook/src/bin/index.ts`

### CODE REVIEW

**Comment by valentinpalkovic** [comment]
Hi @mrginglymus 

Thank you for your contribution! 

For me it makes a ton of sense to return with a non-zero exit code if automigrations are failing while running the `automigrate` command. Would you agree that when running `npx storybook automigrate`, the script should return a non-zero exit code by default, and adding a flag isn't strictly necessary?

**Comment by mrginglymus** [comment]
That would be my preference, I was just worried about changing default behaviours.

Presumably no escape-hatch flag needed, unless applied as a general purpose flag to `handleCommandFailure`

File: code/lib/cli-storybook/src/automigrate/index.ts [hunk 1]
```diff
@@ -191,6 +191,10 @@ export const automigrate = async ({
     logger.log('');
   }
 
+  if (hasFailures) {
+    throw new Error('Some migrations failed');
+  }
```
Comment (valentinpalkovic) [inline code/lib/cli-storybook/src/automigrate/index.ts]: Let's throw the error at the end of the `doAutomigrate` function instead, so that the dependencies can still be installed and the doctor command can run. If one automigration fails, it should not necessarily block others. Additionally, the `automigrate` function can be called programmatically, and it should return the result of each automigration as it does so far. So by moving this piece of code to `doAutomigrate`, we just influence how the `automigrate` cli command behaves in the case of an automigration error.

**Review by valentinpalkovic — APPROVED** [review]
LGTM!
