### PR TITLE
Telemetry: Ensure we report errors even when unexpected things happen

### LINKED ISSUE #21318: [Bug]: Thrown errors unreported
### Describe the bug

The following errors are not reported to telemetry even when crash reporting is enabled
- [x] Preview.js syntax errors in builder-webpack 
- [ ] Inside webpackFinal
- [x] Top level of main.js in builder-vite

### To Reproduce

_No response_

### System

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tmeasday**
Closes #21318

## What I did

- Pass empty string if `error.message` is undefined (this happens with compilation errors):
Pasted Graphic 1

- `try/catch` getting error level (this throws if `main.js` has syntax errors):

Pasted Graphic

## How to test

1. Run a sandbox for template, e.g. `yarn task --task sandbox --start-from auto --template react-vite/default-ts`
2. Add syntax error to `preview.js`
3. Run with `STORYBOOK_TELEMETRY_DEBUG=1 yarn storybook`

Also try - 2. add syntax error to `main.js`

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [x] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

File: code/lib/core-server/src/withTelemetry.ts [hunk 1]
```diff
@@ -64,7 +64,12 @@ export async function sendTelemetryError(
   options: TelemetryOptions
 ) {
   try {
-    const errorLevel = await getErrorLevel(options);
+    let errorLevel = 'error';
+    try {
+      errorLevel = await getErrorLevel(options);
+    } catch (err) {
+      // If this throws, eg. due to main.js breaking, we fall back to 'full'
```
Comment (shilman) [inline code/lib/core-server/src/withTelemetry.ts:71]:
```suggestion
      // If this throws, eg. due to main.js breaking, we fall back to 'error'
```

**Review by shilman — APPROVED** [review]
