### PR TITLE
CSF-Tools: Add support for existing node imports and improve import handling

### LINKED ISSUE #31477: [Bug]: `wrap-require` automigration doesn't account for existing imports
### Describe the bug

The `wrap-require` automigration needs to check whether the imports it tries to add already exist in both formats: `xyz` and `node:xyz`.

Currently, it ends up generating code like this:
Image

Which causes the rest of the automigrations to fail:
Image

### PR DESCRIPTION
**Pull request by valentinpalkovic**
Closes https://github.com/storybookjs/storybook/issues/31477

## What I did

When setting imports for node namespaced modules, like `node:path`, setting these imports will check whether node packages without the `node:` namespace are available and will then add the import specifier to the existing import instead.

**Before:**

```tsx
// file
import { dirname } from 'path';

const config: StorybookConfig = { };
export default config;

// automigration
config.setImport(['dirname, join'], 'node:path');

// file after transformation
import { dirname, join } from 'node:path';
import { dirname } from 'path'; // dirname already exists

const config: StorybookConfig = { };
export default config;
```

**After:**

```tsx
// file
import { dirname } from 'path';

const config: StorybookConfig = { };
export default config;

// automigration
config.setImport(['dirname, join'], 'node:path');

// file after transformation
import { dirname, join } from 'path';

const config: StorybookConfig = { };
export default config;
```

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

File: code/core/src/csf-tools/ConfigFile.ts [hunk 1]
```diff
@@ -736,17 +736,24 @@ export class ConfigFile {
...
         t.isVariableDeclarator(node.declarations[0]) &&
         t.isCallExpression(node.declarations[0].init) &&
         t.isIdentifier(node.declarations[0].init.callee) &&
         node.declarations[0].init.callee.name === 'require' &&
         t.isStringLiteral(node.declarations[0].init.arguments[0]) &&
-        node.declarations[0].init.arguments[0].value === fromImport
-    ) as t.VariableDeclaration | undefined;
+        (node.declarations[0].init.arguments[0].value === fromImport ||
+          node.declarations[0].init.arguments[0].value === fromImport.split('node:')[1]);
+      if (hasDeclaration) {
```
Comment (yannbf) [inline code/core/src/csf-tools/ConfigFile.ts:750]: If you do it like this in the require logic, perhaps do the same in the import logic, then remove lines 868-873 and alter lines 921-923 to be:
```ts
const importDeclaration = this._ast.program.body.find(
  (node) => {
    const hasDeclaration = t.isImportDeclaration(node) && (node.source.value === fromImport || node.source.value === fromImport.split('node:')[1])

    if (hasDeclaration) {
      fromImport = node.source.value;
    }

    return hasDeclaration;
  }
) as t.ImportDeclaration | undefined;
```

In that part, I see that this code is the first one that refers to the `fromImport` variable so it should be safe

**Review by yannbf — APPROVED** [review]
