### PR TITLE
ReactDocgen: Try using the latest version of the original

### LINKED ISSUE #33158: [Bug]: @storybook/react-docgen-typescript-plugin uses deprecated version of rimraf
### Describe the bug

I am trying to remove all deprecations from my npm installed libraries and the only one left is caused by `@storybook/react-docgen-typescript-plugin`. 

Here are the deprecated modules:
```
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
```

An `npm list @inflight@1.0.6` shows this hierarchy:

```
npm list inflight@1.0.6
MY REPO
└─┬ @storybook/nextjs@10.0.8
  └─┬ @storybook/preset-react-webpack@10.0.8
    └─┬ @storybook/react-docgen-typescript-plugin@1.0.6--canary.9.0c3f3b7.0
      └─┬ flat-cache@3.2.0
        └─┬ rimraf@3.0.2
          └─┬ glob@7.2.3
            └── inflight@1.0.6
```

### Reproduction link

N/a

### Reproduction steps

Even running `npx storybook@latest info` highlights the issue:
```
npx storybook@latest info
Need to install the following packages:
storybook@10.0.8
Ok to proceed? (y) y

npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated rimraf@2.6.3: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
```

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 26.1
    CPU: (12) arm64 Apple M2 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.21.0 - MY USER/.nvm/versions/node/v22.21.0/bin/node
    npm: 10.9.4 - MY USER/.nvm/versions/node/v22.21.0/bin/npm <----- active
    pnpm: 10.1.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 142.0.7444.60
    Safari: 26.1
  npmPackages:
    @storybook/addon-a11y: 10.0.8 => 10.0.7 
    @storybook/addon-docs: 10.0.8 => 10.0.7 
    @storybook/nextjs: 10.0.8 => 10.0.7 
    storybook: 10.0.8 => 10.0.7
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ndelangen**
Closes https://github.com/storybookjs/storybook/issues/33158

## What I did

I'm researching what the best approach is to solve the above issue.

I decided the first thing I'd try was this, the most radical approach: replacing the forked with the updated original.

I assumed that this would fail in some way, but would yield insights on the differences between the fork and upstream.

The updated original seems to work, however, so that's what this PR is.

I'm hoping this means we can drop the  special fork/canary version of `@storybook/react-docgen-typescript-plugin`.

We need to do QA on this.

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [x] integration tests
- [ ] end-to-end tests

#### Manual testing

I added a modification in one of the sandboxes to force it to use this option.
That sandbox is being run in this PR, and showing no changes in it's visual regression test.
Also manually verified if the docgen types are present (controls showing up)

I'm releasing a Canary of this to verify locally some more.

I've manually verified using the canary that the docgen works as expected.
I've added a few more abstractions so test, and the `react-docgen-typescript` was definitely used and produced slightly more descriptive docgen:
Screenshot 2026-01-06 at 12 34 59
Screenshot 2026-01-06 at 12 35 04
Screenshot 2026-01-06 at 12 35 19
Screenshot 2026-01-06 at 12 35 39

There are also these changes detected which indicate that the sandbox-template change was done, and applied:
https://www.chromatic.com/test?appId=633c394125f29c2cbb5a4cac&id=695cfda7154daeda3a0cd6cd

### 🦋 Canary release

This pull request has been released as version `0.0.0-pr-33454-sha-b7cb6649`. Try it out in a new sandbox by running `npx storybook@0.0.0-pr-33454-sha-b7cb6649 sandbox` or in an existing project with `npx storybook@0.0.0-pr-33454-sha-b7cb6649 upgrade`.
<details>
<summary>More information</summary>

| | |
| --- | --- |
| **Published version** | [`0.0.0-pr-33454-sha-b7cb6649`](https://npmjs.com/package/storybook/v/0.0.0-pr-33454-sha-b7cb6649) |
| **Triggered by** | @ndelangen |
| **Repository** | [storybookjs/storybook](https://github.com/storybookjs/storybook) |
| **Branch** | [`norbert/investigate-react-docgen-typescript-plugin`](https://github.com/storybookjs/storybook/tree/norbert/investigate-react-docgen-typescript-plugin) |
| **Commit** | [`b7cb6649`](https://github.com/storybookjs/storybook/commit/b7cb66498b00076015dabfbcd08224584572cbd3) |
| **Datetime** | Mon Jan  5 12:11:58 UTC 2026 (`1767615118`) |
| **Workflow run** | [20714993527](https://github.com/storybookjs/storybook/actions/runs/20714993527) |

To request a new release of this pull request, mention the `@storybookjs/core` team.

_core team members can create a new canary release [here](https://github.com/storybookjs/storybook/actions/workflows/publish.yml) or locally with `gh workflow run --repo storybookjs/storybook publish.yml --field pr=33454`_
</details>

## Summary by CodeRabbit

* **Chores**
  * Updated TypeScript documentation generation configuration across React-based presets.
  * Migrated to a standalone TypeScript documentation plugin package for improved stability.
  * Added TypeScript-specific documentation options to Create React App template configuration.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: code/lib/cli-storybook/src/sandbox-templates.ts [hunk 1]
```diff
@@ -428,6 +428,9 @@ export const baseTemplates = {
         features: {
           experimentalTestSyntax: true,
         },
+        typescript: {
+          reactDocgen: 'react-docgen-typescript',
+        } as any, // the generic type does not contain the reactDocgen property
```
Comment (valentinpalkovic) [inline code/lib/cli-storybook/src/sandbox-templates.ts:433]: (unrelated to this PR):
Does it make sense to also test a Vite-based sandbox? @shilman, what are your thoughts on this? The main reason this PR introduces `react-docgen-typescript` is to see whether the non-fork version regresses in any areas. Testing showed that it does not. Still, apart from having tested it manually, do we want to have one webpack and one Vite sandbox checking `react-docgen-typescript` usage? I think we should, especially after the recent discussions we had about adoption.

**Review by valentinpalkovic — APPROVED** [review]

File: code/lib/cli-storybook/src/sandbox-templates.ts (hunk 1 above)
Comment (shilman) [reply code/lib/cli-storybook/src/sandbox-templates.ts:433]: 100% would be great to have `react-docgen-typescript` in CI for both Webpack and Vite.

Comment (ndelangen) [reply code/lib/cli-storybook/src/sandbox-templates.ts:433]: @valentinpalkovic AFAICS, this is not something users can even opt into with vite builder.

Notice how the size reporting only shows webpack package changes.
