### PR TITLE
Svelte: remount when resetting args in controls

### LINKED ISSUE #21470: [Bug]: The reset controls button appears to be resetting the value back to undefined
### Describe the bug

Hello, I'm currently using Storybook `7.0.0-beta.62` with SvelteKit and I'm running into this problem again: https://github.com/storybookjs/storybook/issues/11976. Which occasionally leads to this error in the console: `A component is changing a controlled input to be uncontrolled. This is likely caused by the value changing from a defined to undefined`. Instead of going back to `undefined`, the value should go back to the default specified in `args` or by the `props`.

### To Reproduce

A short example to help illustrate the issue:

### test.svelte
```svelte
<script lang="ts">
	export let prop = 'prop';
</script>

<p>{prop}</p>
```

### test.stories.ts
```ts
import type { Meta, StoryObj } from '@storybook/svelte';

import Test from './test.svelte';

const meta = {
	title: 'Effects/Test',
	tags: [
		'autodocs',
	],

	component: Test,

} satisfies Meta<Test>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
};
```

### System

```shell
System:
  OS: macOS 12.6
  CPU: (10) arm64 Apple M1 Max
Binaries:
  Node: 18.14.1 - ~/.nvm/versions/node/v18.14.1/bin/node
  Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.1/bin/yarn
  npm: 9.6.0 - ~/.nvm/versions/node/v18.14.1/bin/npm
Browsers:
  Chrome: 110.0.5481.177
  Firefox: 110.0.1
  Safari: 16.0
npmPackages:
  @storybook/addon-a11y: ^7.0.0-beta.62 => 7.0.0-beta.62
  @storybook/addon-essentials: ^7.0.0-beta.62 => 7.0.0-beta.62
  @storybook/addon-interactions: ^7.0.0-beta.62 => 7.0.0-beta.62
  @storybook/addon-links: ^7.0.0-beta.62 => 7.0.0-beta.62
  @storybook/blocks: ^7.0.0-alpha.8 => 7.0.0-beta.62
  @storybook/manager-api: ^7.0.0-beta.62 => 7.0.0-beta.62
  @storybook/svelte: ^7.0.0-beta.62 => 7.0.0-beta.62
  @storybook/sveltekit: ^7.0.0-beta.62 => 7.0.0-beta.62
  @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
  @storybook/theming: ^7.0.0-beta.62 => 7.0.0-beta.62
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JReinhold**
Closes #21470

## What I did

This PR makes the Svelte renderer force remount the story when a user resets all args in the controls panel.

It does this by listening for the `RESET_STORY_ARGS` event, saves the information that a story is being reset, and uses that information in `renderToCanvas` to remount instead of just updating props.

There's a possible race condition here, because the `RESET_STORY_ARGS` event will both trigger this custom listener and also trigger `renderToCanvas`. If for some reason `renderToCanvas` reacts to the event **before** the custom listener, then it won't know that it should remount, and it will most likely remount on the following render, eg. triggered by a regular arg change.
I've been unable to produce this out-of-order triggering so for now it's purely theoretical.

There's still an issue here though, that when any singular control gets unset, that will not cause a full remount and the component will not revert to default but rather act as if the value was `undefined`. From a purely Svelte-rendering perspective this is expected, the same thing happens if your Svelte components do that (set a prop to something and then sets it to `undefined`). But maybe from a Storybook user perspective this is unexpected, at least I would expect it to go back to the default.
This scenario is only valid for the color control as it is the only control that can be unset. But I suspect we'll make this a universal feature in the future.

## How to test

1. See new test story being successful: https://630873996e4e3557791c069c-eagyhguotu.chromatic.com/?path=/story/stories-renderers-svelte-args--remount-on-reset-story-args
2. Try it out with [the default Button story](https://630873996e4e3557791c069c-eagyhguotu.chromatic.com/?path=/story/example-button--primary):
    1. Open the Button story in a Svelte project
    2. Change the "size" control to "large"
    3. Reset args
    4. See that it goes back to the default
    5. Do the same thing but [on the `next` branch](https://630873996e4e3557791c069c-ucioaavosy.chromatic.com/?path=/story/example-button--primary) and see that the button loses its size completely because `size` becomes `undefined`. 

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

File: code/renderers/svelte/src/render.ts [hunk 1]
```diff
@@ -24,6 +26,20 @@ function teardown(canvasElement: SvelteRenderer['canvasElement']) {
...
+/**
+ * This is a workaround for the issue that when resetting args,
+ * the story needs to be remounted completely to revert to the component's default props.
+ * This is because Svelte does not itself revert to defaults when a prop is undefined.
+ * See https://github.com/storybookjs/storybook/issues/21470#issuecomment-1467056479
+ *
+ * We listen for the RESET_STORY_ARGS event and store the storyId to be reset
+ * We then use this in the renderToCanvas function to force remount the story
+ */
+const storyIdsToRemountFromResetArgsEvent = new Set<string>();
```
Comment (JReinhold) [inline code/renderers/svelte/src/render.ts:38]: I'm unsure if this Set would ever have more than one entry at a time. It would only occur if `RESET_STORY_ARGS` were sent for multiple stories at the same time, and their `renderToCanvas` were all called after them (because `renderToCanvas` immediately removes the story id from the Set again).

I can't think of a scenario where that would happen - in that sense this could be simplified to be a single string instead of a Set.

However this feels more bulletproof in a way.

File: code/lib/store/template/stories/rendering.stories.ts [hunk 2]
```diff
@@ -65,7 +65,5 @@ export const ChangeArgs = {
 
     await within(canvasElement).findByText(/New Text/);
     await expect(button).toHaveFocus();
-
-    await channel.emit(RESET_STORY_ARGS, { storyId: id });
```
Comment (JReinhold) [inline code/lib/store/template/stories/rendering.stories.ts:69]: resetting args at the end of this test is unnecessary, because we recently reset args at the beginning instead - both as a way to ensure that the story is in a clean state before executing.

File: code/renderers/svelte/src/render.ts (hunk 1 above)
Comment (tmeasday) [reply code/renderers/svelte/src/render.ts:38]: Yeah I agree with all that 💯

**Review by tmeasday — APPROVED** [review]
LGTM @JReinhold 👏 

In 7.1 we should probably add information about whether this is a "reset" to the `renderToCanvas` call (IIRC that's the plan right?)

Do you have thoughts about the individual arg reset issue? Is this something that can realistically happen to a component? If not, should we just be resetting in the same way?

**Comment by JReinhold** [comment]
> In 7.1 we should probably add information about whether this is a "reset" to the `renderToCanvas` call (IIRC that's the plan right?)

Yes, tracking in https://github.com/storybookjs/storybook/issues/21706

> Do you have thoughts about the individual arg reset issue? Is this something that can realistically happen to a component? If not, should we just be resetting in the same way?

I actually think we should keep it as-is for now. Reseting an individual arg is synonymous with changing the prop to `undefined` (if the default is `undefined` for the story, ofc), and I think we should show the user what happens in reality when they do that. If we start remounting we're basically telling the user "if you change this prop to undefined it will go back to the default prop of the component", which it won't in their application, so this would be misleading.
I feel this is different from reseting all Controls to `undefined`, because that seems more like a Storybook scenario where you just want to go back to the initial state.
