### PR TITLE
Vite: Use posix paths for glob

### LINKED ISSUE #554: [Bug] importers[path] is not a function
### What version of `vite` are you using?

4.0.0

### System info and storybook versions

System:
OS: Win11x64
 node: 16.18.1

### Describe the Bug

blank vite typescript project them:

> pnpx storybook@7.0.0-beta.43 init --type html --builder=vite

starting storybook:

```importers[path] is not a function
TypeError: importers[path] is not a function
    at importFn (http://localhost:6006/virtual:/@storybook/builder-vite/storybook-stories.js:6:31)
    at StoryStore.loadEntry (http://localhost:6006/sb-preview/runtime.mjs:40:10578)
    at async MdxDocsRender.prepare (http://localhost:6006/sb-preview/runtime.mjs:74:6539)
    at async PreviewWeb.renderSelection (http://localhost:6006/sb-preview/runtime.mjs:83:3054)
```

### Link to Minimal Reproducible Example

_No response_

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by IanVS**
Closes https://github.com/storybookjs/builder-vite/issues/554

## What I did

New vite projects are failing in Windows because of a change in an updated `glob` package which enforces forward-slashes for glob paths.

So, we'll use `path.posix` to join paths in the vite builder for globs.

## How to test

I don't have access to a windows box, so I'm not able to test.  And we don't test Windows in CI.  I'm hoping that maybe @joshwooding or someone else can help test this out.

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [X] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

File: code/lib/builder-vite/src/list-stories.ts [hunk 1]
```diff
@@ -1,4 +1,4 @@
-import * as path from 'path';
+import * as posixPath from 'node:path/posix'; // Glob requires forward-slashes
```
Comment (shilman) [inline code/lib/builder-vite/src/list-stories.ts:1]: `import { join } from 'node:path/posix';`? not sure if it makes a difference in node

Comment (IanVS) [reply code/lib/builder-vite/src/list-stories.ts:1]: Do you prefer the destructured version?  I slightly prefer the namespaced version, just because it's clear when it's being used where it's coming from.  `posixPath.join()` vs just `join()`.  But I don't feel strongly about it and happy to change if you'd like.

Comment (shilman) [reply code/lib/builder-vite/src/list-stories.ts:1]: Don't feel strongly. I think @ndelangen was making a push towards the namespaced version (but maybe only in browser code, for tree shaking?), so maybe he can comment here.

**Review by shilman — APPROVED** [review]
