### PR TITLE
CSF-Tools: Remove prettier from printConfig

### LINKED ISSUE #23748: [Bug]: UI performance regression
### Describe the bug

We are seeing a performance regression in Storybook's startup time, possibly due to the new "experimental" components

Here is the time to first render for the React-Vite project over time:

image

Drilling in, it appears to have been introduced around [this commit](https://github.com/storybookjs/storybook/commit/1b6eb11551ddf8ad95aa9c5dcba6d6f7799db6f4), potentially somehow due to the new icons? (Pink column is time to preview responsive)

image

Another clue is that the build size (purple column above) also increased around the same time:

image

### To Reproduce

https://lookerstudio.google.com/u/0/reporting/6a438ac0-fe04-490c-ba91-f12a5bb6e917/page/p_54yskb3a7c

### System

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kasperpeulen**
Should fix #23748

## What I did

Remove prettier dep from csf-tools to fix perf regression

## How to test

Ask MIchael for perf insights :) 

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "build", "documentation", "maintenance", "dependencies", "other"]`

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

File: code/lib/csf-tools/src/ConfigFile.ts [hunk 1]
```diff
@@ -718,27 +716,11 @@ export const loadConfig = (code: string, fileName?: string) => {
...
-  const result = recast.print(config._ast, options);
-  const prettierConfig = prettier.resolveConfig.sync('.');
-
-  if (prettierConfig) {
-    let pretty: string;
-    try {
-      pretty = prettier.format(result.code, {
-        ...prettierConfig,
-        filepath: config.fileName ?? 'main.ts',
-      });
```
Comment (ndelangen) [inline code/lib/csf-tools/src/ConfigFile.ts:735]: @kasperpeulen can we detect the existence of `node_modules/.bin/prettier` and call it with the right arguments if it exists in a child_process?

That way we get the best of both worlds!?

**Review by ndelangen — APPROVED** [review]
