### PR TITLE
Addon-docs: Fix un-prefixed path links

### LINKED ISSUE #13630: Relative links in md files are broken in v6.1.12
Hi guys,

We are using md files to display component's documentation under Docs, some of those files have relative links to other stories. 
For example:

```
[web](/docs/components-navigation-navigation-framework--default) 
```

which should navigate to http ://localhost:6006/?path=/docs/components-navigation-navigation-framework--default, but after updating SB from v6.1.11 to 6.1.12 it goes to http: //localhost:6006/iframe.html?path=/docs/components-navigation-navigation-framework--default. 
As you can see, "**iframe.html?**" is being added to the url, as the result page cannot be found.

@shilman, @ndelangen, I took a look at [the change log ](https://github.com/storybookjs/storybook/blob/next/CHANGELOG.md) and it seems that it was broken here: 
Addon-docs: Fix link not working cross origin ([#13022](https://github.com/storybookjs/storybook/pull/13022))

**System**
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-4940MX CPU @ 3.10GHz
  Binaries:
    Node: 14.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 87.0.4280.141
    Edge: Spartan (44.19041.423.0), Chromium (87.0.664.75)
  npmPackages:
    @storybook/addon-a11y: ^6.1.12 => 6.1.14
    @storybook/addon-actions: ^6.1.12 => 6.1.14
    @storybook/addon-docs: ^6.1.12 => 6.1.14
    @storybook/addon-knobs: ^6.1.12 => 6.1.14
    @storybook/addon-links: ^6.1.12 => 6.1.14
    @storybook/addon-storysource: ^6.1.12 => 6.1.14
    @storybook/addon-viewport: ^6.1.12 => 6.1.14
    @storybook/addons: ^6.1.12 => 6.1.14
    @storybook/angular: ^6.1.12 => 6.1.14
    @storybook/source-loader: ^6.1.12 => 6.1.14

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199622255231368/1200109632960423) by [Unito](https://www.unito.io/learn-more)

### PR DESCRIPTION
**Pull request by ndelangen**
Issue: https://github.com/storybookjs/storybook/issues/13630

## What I did

- The href attribute (prop) was being modified (prefixed) by the Link component, but the click-handler didn't read this modification.

It seems the logical place to change/prefix the href would be in the`addons/docs/src/blocks/mdx.tsx` code itself, but this is a fine solution that backwards compatible for now.

### CODE REVIEW

File: addons/docs/src/blocks/mdx.tsx [hunk 1]
```diff
@@ -95,7 +95,7 @@ export const AnchorMdx: FC<AnchorMdxProps> = (props) => {
           href={href}
           onClick={(event: SyntheticEvent) => {
             event.preventDefault();
-            navigate(href);
+            navigate(event.currentTarget.getAttribute('href'));
```
Comment (shilman) [inline addons/docs/src/blocks/mdx.tsx:98]:
```suggestion
            // use the A element's href, which has been modified for
            // local paths without a `?path=` query param prefix
            navigate(event.currentTarget.getAttribute('href'));
```

**Review by shilman — APPROVED** [review]
LGTM!

**Comment by mgameover** [comment]
Hi @shilman, 
Unfortunately, it doesn't solve the issue [#13630](https://github.com/storybookjs/storybook/issues/13630)
I added some comments to it, please take a look.
Thanks!
