### PR TITLE
Manager: Add reactivity to useParameter

### LINKED ISSUE #28592: [Bug]: `useParameter` API is not working on initial load.
### Describe the bug

The `useParameter` API is not working on initial load.

I'm implementing and managing a `storybook-addon-cookie`.
My addon uses `useParameter` to read the cookie values entered by the user inside the story and display them in the panel.

However, since migrating to storybook version 8, when I access the parameter via `useParameter`, I get an empty value on initial load.
When I use `console.log` to `preview` and `Panel`, it appears to be getting an empty value until `preview` is called.

Is there any way to ensure that `preview.js` is called before `manager.js`?

```tsx
// Panel
export const PanelContent: React.FC = () => {
  const { path } = useStorybookState();
  const defaultCookie = useParameter<Cookie>(PARAM_KEY, {}); // TODO: Doesn't work on initial load

  const [story, setStory] = useState<string>();
  const [value, setValue] = useState<Cookie>();
  const [globals, updateGlobals] = useGlobals();

  const initCookie = () => {
    setStory(path);
    setValue(defaultCookie);
    clearCookies();
    setCookies(defaultCookie, encoding);
  };

  useEffect(() => {
    console.log('defaultCookie', defaultCookie);
    if (story !== path) {
      initCookie();
    }
  }, [defaultCookie, path, story]);
 //...
}
```
```ts
// preview
export const cookieDecorator = (
  storyFn: StoryFunction<Renderer>,
  { parameters }: DecoratorContext,
) => {
  const [flag, setFlag] = useState<boolean>(true);

  if (flag) {
    setFlag(false);
    if (!parameters) return storyFn();

    if (parameters[PARAM_PRESERVE_KEY] !== true) {
      clearCookies();
    }

    if (parameters[PARAM_KEY]) {
      console.log(parameters[PARAM_KEY]);
      setCookies(parameters.cookie, parameters.cookieEncoding);
    }
  }

  return storyFn();
};
```
스크린샷 2024-07-14 오후 5 41 57

### Reproduction link

https://github.com/hwookim/storybook-addon-cookie

### Reproduction steps

_No response_

### System

The package pretty much follows the settings in [addon-kit](https://github.com/storybookjs/addon-kit/blob/main/package.json).

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by valentinpalkovic**
Closes https://github.com/storybookjs/storybook/issues/28592

## What I did

I have added reactivity to `useParameters`, which wasn't consistently returning a prepared story's parameters.

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This pull request has been released as version `0.0.0-pr-31579-sha-cf05dec5`. Try it out in a new sandbox by running `npx storybook@0.0.0-pr-31579-sha-cf05dec5 sandbox` or in an existing project with `npx storybook@0.0.0-pr-31579-sha-cf05dec5 upgrade`.
<details>
<summary>More information</summary>

| | |
| --- | --- |
| **Published version** | [`0.0.0-pr-31579-sha-cf05dec5`](https://npmjs.com/package/storybook/v/0.0.0-pr-31579-sha-cf05dec5) |
| **Triggered by** | @valentinpalkovic |
| **Repository** | [storybookjs/storybook](https://github.com/storybookjs/storybook) |
| **Branch** | [`valentin/add-reactivity-to-use-parameter`](https://github.com/storybookjs/storybook/tree/valentin/add-reactivity-to-use-parameter) |
| **Commit** | [`cf05dec5`](https://github.com/storybookjs/storybook/commit/cf05dec5aa05eea5d4b194f2ff6844cfa8a97b9d) |
| **Datetime** | Tue May 27 10:56:13 UTC 2025 (`1748343373`) |
| **Workflow run** | [15273427125](https://github.com/storybookjs/storybook/actions/runs/15273427125) |

To request a new release of this pull request, mention the `@storybookjs/core` team.

_core team members can create a new canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=31579`_
</details>

## Greptile Summary

Added reactivity to the `useParameter` hook in Storybook's manager API, enabling automatic parameter updates when story changes occur.

- Modified `code/core/src/manager-api/root.tsx` to add state management for parameter values
- Added `useChannel` hook to listen for `STORY_PREPARED` events and update parameters
- Implemented change detection to prevent unnecessary re-renders
- Maintained backwards compatibility while adding reactive functionality

### CODE REVIEW

File: code/core/src/manager-api/root.tsx [hunk 1]
```diff
@@ -337,9 +340,24 @@ export function useStoryPrepared(storyId?: StoryId) {
...
   const api = useStorybookApi();
+  const [parameter, setParameter] = useState(api.getCurrentParameter<S>(parameterKey));
 
-  const result = api.getCurrentParameter<S>(parameterKey);
-  return orDefault<S>(result, defaultValue!);
+  const handleParameterChange = useCallback(() => {
+    const newParameter = api.getCurrentParameter<S>(parameterKey);
+    if (newParameter !== parameter) {
+      setParameter(newParameter);
+    }
```
Comment (ghengeveld) [inline code/core/src/manager-api/root.tsx:349]: I think the inequality check is unecessary because `useState` setters already optimize for this by not rerendering when the new value is equal to the old.

**Review by ghengeveld — APPROVED** [review]
