### PR TITLE
Core: Fix highlight conflicts

### LINKED ISSUE #31208: [Bug]: Issue with exported types from Highlight
### Describe the bug

Related to #30894

When a user attempts to configure the highlight module that was recently moved into core using the new API that's available, the `REMOVE_HIGHLIGHT` option is not recognized. This is causing the highlight module to not function as expected.

Below is a recording of the issue:

https://github.com/user-attachments/assets/b78ddcf7-cac5-405a-9497-acdbcc1256b1

cc @ghengeveld @valentinpalkovic 

### Reproduction link

https://new-storybook.netlify.app/

### Reproduction steps

1. Create a new project
2. Run `npx storybook@next init` to install the latest beta version of Storybook
3. Open a story file (i.e.,`Page.stories.tsx`) and attempt to configure it
4. Observe the issue

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 15.0.1
    CPU: (8) arm64 Apple M3
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
    Yarn: 1.22.21 - /usr/local/bin/yarn
    npm: 10.5.2 - ~/.nvm/versions/node/v20.13.1/bin/npm <----- active
    pnpm: 9.12.2 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 135.0.7049.96
    Edge: 135.0.3179.85
    Safari: 18.0.1
  npmPackages:
    @storybook/addon-docs: ^9.0.0-beta.1 => 9.0.0-beta.1
    @storybook/addon-onboarding: ^9.0.0-beta.1 => 9.0.0-beta.1
    @storybook/addon-vitest: ^9.0.0-beta.1 => 9.0.0-beta.1
    @storybook/react-vite: ^9.0.0-beta.1 => 9.0.0-beta.1
    eslint-plugin-storybook: ^9.0.0-beta.1 => 9.0.0-beta.1
    storybook: ^9.0.0-beta.1 => 9.0.0-beta.1
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ghengeveld**
Fixes #31208, #31210

## What I did

The A11y addon was overriding highlights created by others (e.g. from a decorator). I updated its logic to only clear out its own highlights. I also fixed the situation of creating two highlights with the same ID, those will now overwrite their previous value.

The highlighting logic was being instantiated twice and the cleanup/teardown logic of the first instance was conflicting with the second instance. Rather than trying to fix that complicated piece of code, I replaced it with a simple "first instance wins" behavior, eliminating the possibility of a 2nd instance messing things up.

I also made `styles` optional (providing a default) because they always have been, and removed `selectable` because it was confusing and superfluous (same can be achieved with an empty `menu` array).

#### The changes in this PR are covered in the following automated tests:

- [x] stories
- [x] unit tests
- [ ] integration tests
- [x] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

## Greptile Summary

Implemented significant improvements to Storybook's highlight system to prevent conflicts between the A11y addon and other decorators, while simplifying the initialization logic with a singleton pattern.

- Added `__STORYBOOK_HIGHLIGHT_INITIALIZED` global flag in `code/core/src/highlight/typings.d.ts` to enforce singleton pattern
- Modified `code/addons/a11y/src/components/A11yContext.tsx` to use targeted `REMOVE_HIGHLIGHT` calls instead of `RESET_HIGHLIGHT`
- Updated `code/core/src/highlight/useHighlights.ts` to handle duplicate highlight IDs by filtering previous highlights
- Added default outline styles in `code/core/src/highlight/utils.ts` for when no styles are specified
- Made `styles` property optional in `code/core/src/highlight/types.ts` with sensible defaults

### CODE REVIEW

File: code/addons/a11y/src/components/A11yContext.tsx [hunk 1]
```diff
@@ -276,7 +284,9 @@ export const A11yContextProvider: FC<PropsWithChildren> = (props) => {
   }, [getInitialStatus, manual]);
 
   useEffect(() => {
-    emit(RESET_HIGHLIGHT);
+    emit(REMOVE_HIGHLIGHT, `${ADDON_ID}/selected`);
+    emit(REMOVE_HIGHLIGHT, `${ADDON_ID}/others`);
```
Comment (ndelangen) [inline code/addons/a11y/src/components/A11yContext.tsx:288]: This feels a bit sub-optimal. Could/should it receive an array?

File: code/addons/a11y/src/components/A11yContext.tsx [hunk 2]
```diff
@@ -317,8 +328,9 @@ export const A11yContextProvider: FC<PropsWithChildren> = (props) => {
 
     const others = results?.[tab as RuleType]
       .flatMap((r) => r.nodes.flatMap((n) => n.target).map(String))
-      .filter((e) => !selected.includes(e));
+      .filter((e) => !['html', 'body', 'main', ...selected].includes(e));
```
Comment (ndelangen) [inline code/addons/a11y/src/components/A11yContext.tsx:331]: Should we have a comment explaining this special case?

File: code/addons/a11y/src/components/A11yContext.tsx [hunk 3]
```diff
@@ -317,8 +328,9 @@ export const A11yContextProvider: FC<PropsWithChildren> = (props) => {
...
     emit(HIGHLIGHT, {
+      id: `${ADDON_ID}/others`,
       selectors: others,
       styles: {
         outline: `1px solid color-mix(in srgb, ${colorsByType[tab]}, transparent 30%)`,
```
Comment (ndelangen) [inline code/addons/a11y/src/components/A11yContext.tsx:336]: I'm wondering why we want to allow custom styling.

The addon probably already did support it, so we might just be keeping it for the sake of not changing, but I do want to raise the question if it's fundamentally a good idea.

For UI consistency reasons we might not want this.. @MichaelArestad 

But also if these styles are going to be directly injected.. that might raise security concerns? @shilman

File: code/core/src/highlight/useHighlights.ts [hunk 4]
```diff
@@ -582,37 +593,11 @@ export const useHighlights = ({
...
-  };
-
-  (globalThis as any).__STORYBOOK_HIGHLIGHT_TEARDOWN = teardown;
-
-  return teardown;
+  channel.on(STORY_RENDER_PHASE_CHANGED, ({ newPhase }: { newPhase: string }) => {
+    if (newPhase === 'loading') {
+      resetState();
+    }
+  });
```
Comment (ndelangen) [inline code/core/src/highlight/useHighlights.ts:602]: out of scope for this PR, but I wanted to raise it anyway:
I pretty sure all of this code would become unnecessary if we gave this addon some more attention and turned it into a decorator.

There's quite a bit of code here, for the sake of synchronizing with storybook's rendering lifecycle, which is something that's near automatic in decorators as they are a part of said lifecycle.

File: code/core/src/highlight/useHighlights.stories.tsx [hunk 5]
```diff
@@ -1,16 +1,55 @@
-import React, { useEffect, useState } from 'react';
+import React from 'react';
 
-import { mockChannel } from 'storybook/internal/preview-api';
+import { useChannel } from 'storybook/internal/preview-api';
```
Comment (ndelangen) [inline code/core/src/highlight/useHighlights.stories.tsx:3]: Very impressive how you got this in a story, and truly can show of the functionality working.

The highlighting, uses the real highlighting code, via the real addon, but then the click handlers used addon actions, that did confuse me. I'd expect the click functionality to also be "real" then.

File: code/core/src/highlight/useHighlights.stories.tsx [hunk 6]
```diff
@@ -1,16 +1,55 @@
...
+        backgroundColor: 'transparent',
+      },
+      ...options,
+    });
+    return () => emit(REMOVE_HIGHLIGHT, id);
+    // eslint-disable-next-line react-hooks/exhaustive-deps
+  }, [emit]);
+};
 
 const Content = ({ dynamic, withPopover }: { dynamic: boolean; withPopover: boolean }) => {
```
Comment (ndelangen) [inline code/core/src/highlight/useHighlights.stories.tsx:50]: Extracting this dummy component into it's own file, seems a good step to me.

File: code/core/src/highlight/useHighlights.ts [hunk 7]
```diff
@@ -63,9 +63,11 @@ export const useHighlights = ({
   rootId?: string;
   storybookRootId?: string;
 }) => {
-  // Clean up any existing instance of useHighlights
+  if (globalThis.__STORYBOOK_HIGHLIGHT_INITIALIZED) {
+    return;
+  }
 
-  (globalThis as any).__STORYBOOK_HIGHLIGHT_TEARDOWN?.();
+  globalThis.__STORYBOOK_HIGHLIGHT_INITIALIZED = true;
```
Comment (ndelangen) [inline code/core/src/highlight/useHighlights.ts:70]: From what you told me, this is only needed because of our stories testing this functionality, correct?

I'm wondering if this could be avoided somehow, or at least have a comment explaining what this global variable is for.

File: code/addons/a11y/src/components/A11yContext.tsx (hunk 3 above)
Comment (ghengeveld) [reply code/addons/a11y/src/components/A11yContext.tsx:336]: I'm not sure what your security concerns are here. A malicious addon can already do pretty bad things without going through a highlight...

File: code/core/src/highlight/useHighlights.ts (hunk 4 above)
Comment (ghengeveld) [reply code/core/src/highlight/useHighlights.ts:602]: It would probably make sense for this to be a (global) decorator rather than a stand-alone script in the preview. Definitely not something to address right now though.

File: code/core/src/highlight/useHighlights.ts (hunk 7 above)
Comment (ghengeveld) [reply code/core/src/highlight/useHighlights.ts:70]: I think this happens either way. In our own Storybook I've seen preview.js and runtime.js both execute `useHighlights`, and they also do it twice. That might be a bug in Storybook or be specific to our own Storybook, but either way I feel safer knowing we can only ever have one instance. Of course refactoring to a decorator might be the real answer here.

File: code/core/src/highlight/useHighlights.stories.tsx (hunk 5 above)
Comment (ghengeveld) [reply code/core/src/highlight/useHighlights.stories.tsx:3]: That would assume addon-a11y is around, which I don't love. Right now it asserts all of the functional surface area, including the fact that this clickEvent is emitted and can be listened to on the (real) channel.

I'll update the event name but leave the rest as-is.

File: code/addons/a11y/src/components/A11yContext.tsx (hunk 3 above)
Comment (MichaelArestad) [reply code/addons/a11y/src/components/A11yContext.tsx:335]: Some folks might want custom styling if our highlight colors are close to their brand colors. I don't think it's a bad idea. I also don't think many folks will opt to customize it.

**Review by ndelangen — APPROVED** [review]
