### PR TITLE
CLI: Improve CLI upgrade for `@latest` and `@next`

### LINKED ISSUE #31314: [Bug]: Storybook 9 - Improvements for Storybook upgrade and upgradeStorybookRelatedDependencies automigration
### Describe the bug

Currently, the upgrade experience is great for `@latest` but not so much for `@next`.
When running upgrade for beta, for instance, the `upgradeStorybookRelatedDependencies` is never triggered (on purpose, for now) and therefore users still have broken Storybooks because some addons might depend on Storybook 8.

Here are the changes to improve the experience:
1. "Core satellite packages" should be upgraded directly, without prompt, on the upgrade command. By core satellite packages I mean addons maintained by the Storybook team which are outside of the monorepo: [addon-designs](https://github.com/storybookjs/addon-designs), [addon-coverage](https://github.com/storybookjs/addon-coverage), [test-runner](https://github.com/storybookjs/test-runner), [addon-svelte-csf](https://github.com/storybookjs/addon-svelte-csf), [addon-webpack5-compiler-babel](https://github.com/storybookjs/addon-webpack5-compiler-babel), [addon-webpack5-compiler-swc](https://github.com/storybookjs/addon-webpack5-compiler-swc), [@chromatic-com/storybook](https://github.com/chromaui/addon-visual-tests). On `@latest upgrade`, it fetches the latest version on npm, and on `@next upgrade`, it fetches the prerelease version on npm.
2. The `upgradeStorybookRelatedDependencies` should always be triggered. Because we don't control the release cycle of external addons, the automigration should display the publish date alongside the packages so the user can judge whether it makes sense to upgrade.

### Reproduction link

-

### Reproduction steps

_No response_

### System

```bash
-
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yannbf**
Closes #31314

## What I did

- Introduced a new module for managing Storybook satellite addons.
- Updated CLI utility functions to include checks for satellite addons.
- Enhanced the upgrade process to handle satellite dependencies, ensuring they are upgraded alongside core Storybook packages (but only when it's an exact match for @latest or @next, as users could be downgrading or installing specific versions which might be tricky).
- Improved messaging in the upgrade prompts to inform users about community-maintained packages.

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This pull request has been released as version `0.0.0-pr-31356-sha-36d464a6`. Try it out in a new sandbox by running `npx storybook@0.0.0-pr-31356-sha-36d464a6 sandbox` or in an existing project with `npx storybook@0.0.0-pr-31356-sha-36d464a6 upgrade`.
<details>
<summary>More information</summary>

| | |
| --- | --- |
| **Published version** | [`0.0.0-pr-31356-sha-36d464a6`](https://npmjs.com/package/storybook/v/0.0.0-pr-31356-sha-36d464a6) |
| **Triggered by** | @yannbf |
| **Repository** | [storybookjs/storybook](https://github.com/storybookjs/storybook) |
| **Branch** | [`yann/improve-upgrade-command`](https://github.com/storybookjs/storybook/tree/yann/improve-upgrade-command) |
| **Commit** | [`36d464a6`](https://github.com/storybookjs/storybook/commit/36d464a66a9e8ebad331e5e1a0ed906eba297a9b) |
| **Datetime** | Fri May  2 13:42:33 UTC 2025 (`1746193353`) |
| **Workflow run** | [14796402208](https://github.com/storybookjs/storybook/actions/runs/14796402208) |

To request a new release of this pull request, mention the `@storybookjs/core` team.

_core team members can create a new canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=31356`_
</details>

## Greptile Summary

Enhances Storybook's upgrade process by introducing automatic handling of satellite addons and improving user messaging during package upgrades for @latest and @next versions.

- Added new `code/core/src/common/satellite-addons.ts` to manage Storybook-maintained packages outside the monorepo
- Enhanced `code/lib/cli-storybook/src/upgrade.ts` to automatically upgrade satellite addons for @latest/@next versions
- Updated `code/lib/cli-storybook/src/automigrate/fixes/upgrade-storybook-related-dependencies.ts` with clearer messaging about community package compatibility
- Added `isSatelliteAddon` utility in `code/core/src/common/utils/cli.ts` to identify satellite addons during upgrades

### CODE REVIEW

File: code/core/src/common/utils/cli.ts [hunk 1]
```diff
@@ -156,4 +157,5 @@ export const createLogStream = async (
   });
 };
 
-export const isCorePackage = (pkg: string) => Object.keys(versions).includes(pkg);
+export const isCorePackage = (pkg: string) => Object.keys(storybookPackagesVersions).includes(pkg);
```
Comment (ndelangen) [inline code/core/src/common/utils/cli.ts:160]:
```suggestion
export const isCorePackage = (pkg: string) => !!(storybookPackagesVersions[pkg]);
```

This should be slightly faster, and maybe simpler?

**Review by ndelangen — APPROVED** [review]
