### PR TITLE
Vue: Replace vue-docgen-api with Volar vue-component-meta

### LINKED ISSUE #22090: [Bug]: vue-docgen-plugin cannot parse functional component
### Describe the bug

I get an error when add a story for my functional component. The component written in Vue SFC and export a render function.

```
No suitable component definition found on "D:/Coding/JavaScript/vue3-vite/default-js/src/stories/Button.vue"
18:23:08 [vite] Internal server error: No suitable component definition found on "D:/Coding/JavaScript/vue3-vite/default-js/src/stories/Button.vue"
  Plugin: storybook:vue-docgen-plugin
  File: D:/Coding/JavaScript/vue3-vite/default-js/src/stories/Button.vue
      at <anonymous> (d:\Coding\JavaScript\vue3-vite\default-js\node_modules\.pnpm\vue-docgen-api@4.64.1_vue@3.2.47\node_modules\vue-docgen-api\dist\parse-script.js:67:23)
      at Generator.next (<anonymous>)
      at fulfilled (d:\Coding\JavaScript\vue3-vite\default-js\node_modules\.pnpm\vue-docgen-api@4.64.1_vue@3.2.47\node_modules\vue-docgen-api\dist\parse-script.js:28:58)
```

```vue
<!-- Button.vue -->
<script>
import { h } from "vue";

export default function Button() {
    return h("button");
}
</script>

<style>/* ... */</style>
```

```javascript
// Button.stories.js
import Button from './Button.vue';

export default { component: Button };

export const Primary = {};
```

### To Reproduce

https://github.com/Kaciras/sb-issue

### System

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 5625U with Radeon Graphics
  Binaries:
    Node: 19.7.0 - D:\Program Files\NodeJS\node.EXE
    npm: 9.5.0 - D:\Program Files\NodeJS\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1555.0), Chromium (109.0.1518.78)
  npmPackages:
    @storybook/addon-essentials: ^7.0.4 => 7.0.4
    @storybook/addon-interactions: ^7.0.4 => 7.0.4
    @storybook/addon-links: ^7.0.4 => 7.0.4
    @storybook/blocks: ^7.0.4 => 7.0.4
    @storybook/testing-library: ^0.0.14-next.2 => 0.0.14-next.2
    @storybook/vue3: ^7.0.4 => 7.0.4
    @storybook/vue3-vite: ^7.0.4 => 7.0.4
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by chakAs3**
Closes #22090 #21606 #23313 #25582 #25305 #24621 #22209 #21684 #19233 #16301

and other issues

### Current PR status / open points
Status from: 18 February 2024
- waiting for https://github.com/vuejs/language-tools/issues/3896. Alternatively we have to implement a temporary workaround because currently projects that use references in their tsconfig will miss all component docs in Storybook
- Performance issues need testing if they still exists. If they exist, we might need to only include .vue files by default and add a framework option to also include ts,js,jsx and tsx files

Volar can be enabled with:

```ts
// .storybook/main.ts
import type { StorybookConfig } from '@storybook/vue3-vite';

const config: StorybookConfig = {
  framework: {
    name: '@storybook/vue3-vite',
    options: {
      docgen: "vue-component-meta"
    },
  },
};

export default config;
```

## What I did

replace **vue-docgen-api** with official vue language tools by Volar ( **vue-meta-component** ) with a better type definition, more features, and regular updates by @johnsoncodehk.

### Added Props type definition extraction

- String (e.g. 'Foo')
- Array of strings (e.g. ['Baz', 'Bar', 'Foo'])
- Number (e.g. 1)
- Union types with optional values (e.g. 'Foo' | undefined)
- Union types (e.g. 'Foo' | 'Baz')
- Object with inline properties (e.g. { foo: 'Foo' })
- Object with nested properties (e.g. { nestedProp: 'Nested Prop' })
- Object with intersection types (e.g. { nestedProp: 'Nested Prop', additionalProp: 'Additional Prop' })
- Array of objects with properties (e.g. [{ foo: 'Foo' }])
- Literal types (e.g. ['Uncategorized', 'Display', 'Addons'])
- Enum types (e.g. MyEnum.Small)
- Recursive object types (e.g. { recursive: { recursive: { recursive: 'recursive' } } })

image

### Added props description and tag annotation support :

This PR adds the ability to include descriptions and tag annotations for props in Vue components. The following examples demonstrate how to use this new feature:

**Props Description**

To provide a description for a prop, add a description property to the prop object. Here is an example:

```ts
interface MyComponentProps {
  /**
   * The name of the user
   */
  name: string;
  /**
   * The category of the component
   * @required
   * @default 'Uncategorized'
   */
  category: string;
}

export default {
  name: "MyComponent",
  props: {
    name: {
      type: String,
      required: true,
      description: "The name of the user",
    },
    category: {
      type: String,
      default: "Uncategorized",
      tags: ["required", "default: Uncategorized"],
    },
  },
  // rest of the component's logic
};
```

**Props Tag Annotation**

To add a tag annotation to a prop, add a tags property to the prop object. This can be useful for documenting things like default values or required props. Here is an example:

```ts
props: {
  // @required
  // @default 'Uncategorized'
  category: {
    type: String,
    tags: ['required', 'default: Uncategorized']
  }
}
```

These new features can make documentation more organized and useful for other developers, so be sure to take advantage of them in your Vue components.

### Added support control generation

- Ability to generate Storybook controls based on Vue component's props type definitions

This new feature enables developers to generate Storybook controls for their Vue components, using simple props type definitions as a guide. Here's an example of how it might look like:

```vue
<script>
enum MyEnum {
	Small,
	Medium,
	Large,
}

const categories = [
	'Uncategorized',
	'Content',
	'Interaction',
	'Display',
	'Forms',
	'Addons',
] as const;

type MyCategories = typeof categories[number];

type MyProps = {
  /**
	 * description enum value
	 */
	enumValue: MyEnum,
	/**
	 * description literal type alias that require context
	 */
	literalFromContext: MyCategories,
}

withDefaults(defineProps<MyProps>(), {
	bar: 1,
	baz: () => ['foo', 'bar'],
});
</script>
```

### Events types extraction

**Note**:
Due to technical limitations of Volar / vue language features, JSDoc / descriptions for emits can not be extracted.

```vue
<script setup lang="ts">
type MyFooEvent = "foo";

interface MyEvents {
  (event: MyFooEvent, data?: { foo: string }): void;
  (event: "bar", value: { year: number; title?: any }): void;
  (e: "baz"): void;
}

const emit = defineEmits<MyEvents>();
</script>
```

image

### Added slots types definition extraction

we can get slots type definition from Vue component and display them on the component docs table

```vue
<template>
  <slot name="no-bind"></slot>
  <br />
  <slot :num="123"></slot>
  <br />
  <slot name="named" str="str"></slot>
  <br />
  <slot name="vbind" v-bind="{ num: 123, str: 'str' }"></slot>
</template>

<script setup lang="ts"></script>
```

image

### Added "Exposed" methods and properties types definition extraction

With the release of Vue 3.2 a new composition tool was made available for us, called expose.
to make methods and properties available to the parent. and made the type available #3399

Now we can extract these exposed and display them on docs table in section called exposed

```vue
<script setup lang="ts">
import { ref } from "vue";

const label = ref("Button");
const count = ref(100);

defineExpose({
  /**
   * a label string
   */
  label,
  /**
   * a count number
   */
  count,
});
</script>
```

image

In addition to generating Storybook controls for Vue components based on their props, events, slots and exposed type definitions, the new feature also allows this meta extraction from all types of Vue components, including functional, composition / options API components, and from both `.vue` or `.ts` files. This makes it easier for developers to test their components and ensure that they are working as intended.

Here's an example of a TypeScript Vue component:

```ts
//  .ts-component.ts
export default defineComponent({
  props: {
    /**
     * string foo
     */
    foo: {
      type: String,
      required: true,
    },
    /**
     * optional number bar
     */
    bar: {
      type: Number,
    },
  },
  setup(props) {
    return () => h("pre", JSON.stringify(props, null, 2));
  },
});
```

## Support for Named Export Component

The PR introduces support for named export components in Vue. With this enhancement, you can now have multiple components exported from a single file using named exports. This provides greater flexibility and organization in structuring your Vue components.

You can do something like this

```ts
// ./component.ts
export const ComponentA = defineComponent({
  name: "MyCompo1",
  props: {
    /**
     * This is a description of the prop
     * @values 'small', 'medium', 'large'
     * @defaultValue 'medium'
     * @control select
     * @group Size
     * */
    size: {
      type: String as PropType<"small" | "medium" | "large">,
      default: "medium",
    },
    /**
     * This is a description of the prop
     * @defaultValue false
     * @control color
     * @group Style
     * */
    backgroundColor: {
      type: String,
      default: "red",
    },
  },
  setup(props: any) {
    return () => h("pre", JSON.stringify(props, null, 2));
  },
});

export const ComponentB = defineComponent(
  (props: MyProps) => () => h("Pre", `${JSON.stringify(props)}`),
  { props: ["foo", "bar"] }
);
```

## Component Meta Extraction from Various File Types

The PR extends the component meta extraction functionality to support multiple file types, including .vue, .js, .ts, .tsx, and .jsx. Regardless of the file extension, you can now extract component metadata seamlessly. This improvement enables a unified approach to extracting component meta across different file formats, ensuring consistent and efficient development workflows.

so you can have something like :

```ts
// ./components.tsx
export const JSXComponent = defineComponent({
  props: {
    /**
     * label for the JSXComponent
     */
    label: String,
    /**
     * counter for the JSXComponent
     * @default 0
     * @type Number
     * @example 1
     */
    counter: Number,
  },
  name: "JSXComponent",
  setup(props, { emit }) {
    return () => (
      <>
        <h4>JSX Component</h4>
      </>
    );
  },
});
```

By incorporating these new features, we aim to enhance the flexibility and extensibility of Vue components, making it easier to manage and extract metadata across various file types and export configurations.

Please review this PR and provide your feedback. Your contributions and suggestions are highly appreciated.

Thank you!

## How to test

1. Run a sandbox for template, e.g. `yarn task --task sandbox --start-from auto --template vue3-vite/default-ts`
2. Open Storybook in your browser

-->

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

This pull request has been released as version `0.0.0-pr-22285-sha-f910dccb`. Try it out in a new sandbox by running `npx storybook@0.0.0-pr-22285-sha-f910dccb sandbox` or in an existing project with `npx storybook@0.0.0-pr-22285-sha-f910dccb upgrade`.
<details>
<summary>More information</summary>

| | |
| --- | --- |
| **Published version** | [`0.0.0-pr-22285-sha-f910dccb`](https://npmjs.com/package/@storybook/cli/v/0.0.0-pr-22285-sha-f910dccb) |
| **Triggered by** | @kasperpeulen |
| **Repository** | [storybookjs/storybook](https://github.com/storybookjs/storybook) |
| **Branch** | [`chaks/vue-component-meta`](https://github.com/storybookjs/storybook/tree/chaks/vue-component-meta) |
| **Commit** | [`f910dccb`](https://github.com/storybookjs/storybook/commit/f910dccb3d4064771821effdb5d15ecb9df10e80) |
| **Datetime** | Fri Feb 23 15:33:14 UTC 2024 (`1708702394`) |
| **Workflow run** | [8021473651](https://github.com/storybookjs/storybook/actions/runs/8021473651) |

To request a new release of this pull request, mention the `@storybookjs/core` team.

_core team members can create a new canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=22285`_
</details>

### CODE REVIEW

**Comment by Jansschen** [comment]
This is a good idea❤️
when i can use this？

**Comment by chakAs3** [comment]
> @SocketSecurity ignore-all

**Comment by chakAs3** [comment]
> **🚨 Potential security issues detected.** Learn more about [Socket for GitHub ↗︎](https://socket.dev?utm_medium=gh)
> 
> To accept the risk, merge this PR and you will not be notified again.
> 
> Issue	Package	Version	Note	Source
> [ Network access ](https://socket.dev/npm/package/@volar/typescript/issues/1.7.6?issue=networkAccess)	[ @volar/typescript ](https://socket.dev/npm/package/@volar/typescript/overview/1.7.6)	[ 1.7.6 ](https://socket.dev/npm/package/@volar/typescript/files/1.7.6)	
> * **Module:** globalThis["fetch"]
> * **Location:** [out/dtsHost.js](https://socket.dev/npm/package/@volar/typescript/files/1.7.6/out/dtsHost.js#T5586-5591)
> 
> [`code/frameworks/vue-vite/package.json`](https://github.com/storybookjs/storybook/pull/22285/files#diff-b4ec5cab4f01abf53e9b31a3ad17b7f8be70a4dc6fd450dedf4cf1bbd1b0eae9) via [vue-component-meta@1.7.14](https://socket.dev/npm/package/vue-component-meta/overview/1.7.14), [`code/frameworks/vue3-vite/package.json`](https://github.com/storybookjs/storybook/pull/22285/files#diff-bdf82c9bc70c4c8065b5dc20a3451fc254f8680179e63487f5999ce000797878) via [vue-component-meta@1.7.14](https://socket.dev/npm/package/vue-component-meta/overview/1.7.14)
> ### Next steps
> ** What is network access? **
> This module accesses the network.
> 
> Packages should remove all network access that isn't functionally unnecessary. Consumers should audit network access to ensure legitimate use.
> 
> ** Take a deeper look at the dependency **
> ** Remove the package **
> **Mark a package as acceptable risk**
> To ignore an alert, reply with a comment starting with `@SocketSecurity ignore` followed by a space separated list of `package-name@version` specifiers. e.g. `@SocketSecurity ignore foo@1.0.0 bar@*` or ignore all packages with `@SocketSecurity ignore-all`
> 
> * `@SocketSecurity ignore @volar/typescript@1.7.6`

@SocketSecurity ignore @volar/typescript@1.7.6

**Comment by ndelangen** [comment]
I think this looks very promising, exciting stuff @chakAs3 !

**Comment by chakAs3** [comment]
> I think this looks very promising, exciting stuff @chakAs3 !

thanks @ndelangen,  yeah after I finished it I was really happy with the outcome, which inspired me, the Union Type Control, and what excited me more it took me 5 min to implement it because of the amazing code written in the controls. if you look at the PR it feels like the feature was already there we just did not want it 😆 . #22912  if you can review it and I would like @kylegach to have his input with the design team

**Comment by chakAs3** [comment]
> But FYI, I'm on the learning (i.e. docs) team (along with `@jonniebigodes`), not the design team. For a design review,

Thanks @kylegach I'm aware of that. I have already tagged @MichaelArestad in Your PR addressing ArgTypes documentation.

**Comment by chakAs3** [comment]
@kasperpeulen is all green, we need to merge these first #23180 #23179

**Comment by chakAs3** [comment]
Hi @kasperpeulen  @shilman  this is ready and closes also https://github.com/storybookjs/storybook/issues/23313

**Comment by floroz** [comment]
Thank you so much for working on this @chakAs3 , my team migrated to `script setup` and we had to resort to copy/paste types to have them appear in Storybook auto-docs.

This feature would unlock a lot of improvements.  Once merged would it be already available on the `@next` tag?

**Comment by chakAs3** [comment]
> This feature would unlock a lot of improvements. Once merged would it be already available on the `@next` tag?

Hi @floroz, really glad to hear that, yes it will be available on next once it is merged.  

Meanwhile, you can use my fork if you use `pnpm` check this repo https://github.com/chakAs3/vue3-storybook-custom-render which shows you how you can do that.

Please let me know if that works for you, or else i can assist you

**Comment by floroz** [comment]
> > This feature would unlock a lot of improvements. Once merged would it be already available on the `@next` tag?
> 
> Hi @floroz, really glad to hear that, yes it will be available on next once it is merged.
> 
> Meanwhile, you can use my fork if you use `pnpm` check this repo https://github.com/chakAs3/vue3-storybook-custom-render which shows you how you can do that.
> 
> Please let me know if that works for you, or else i can assist you

Thank you @chakAs3. I can see your repo explain how to use the different renderers in Vue, in my case the issue to solve is, given a component with the following interface

```ts
// Component.vue
defineProps<Props & { b: string }>();
```
```ts
// types.ts
type Props = { 
/*
* I am JSDoc annotation
*/
a: string 
}
```

to have the `auto-docs` analysing `Props` types and output in the Args table the name, type and description (from JSDoc).

Would you be able to point me towards how to achieve that following some example from your repo? 

The only way I could do that is to directly use `vue-component-meta` and maintain some complex script on our side (and still, the integration with Storybook would be quite clanky with that custom solution).

**Comment by chakAs3** [comment]
@floroz  I have added  an example  for you, please check it out   https://stackblitz.com/~/github.com/chakAs3/vue3-storybook-custom-render/pull/2

**Comment by kasperpeulen** [comment]
@chakAs3 Code looks good, will do some QA tomorrow and then try to get it in!

**Comment by chakAs3** [comment]
> @chakAs3 Code looks good, will do some QA tomorrow and then try to get it in!

Perfect let me know 👍   I will be available tomorrow if there is any requested changes

**Comment by kasperpeulen** [comment]
@chakAs3 Testing out our new canary releases:
image

**Comment by floroz** [comment]
@kasperpeulen @chakAs3 thanks for your work on this, is there any way to access this canary release via npm? 

I thought there was a `pnpm dlx storybook@latest upgrade --canary` but it just works for `--prerelease`.

If not, where can I find the release id so I manually update the dependencies in my package.json?

**Comment by kasperpeulen** [comment]
@floroz You have to manually change all storybook packages to the canary version for now in your package.json!

Will be better once this lands:
https://github.com/storybookjs/storybook/discussions/23590

**Comment by kasperpeulen** [comment]
@chakAs3 At some places you are specifying a package as both peerDep and normal dep, is that intentional? To provide a default when the user doesn't install a package or something?

**Comment by floroz** [comment]
> @floroz You have to manually change all storybook packages to the canary version for now in your package.json!
> 
> Will be better once this lands: #23590

Thanks @kasperpeulen . Since you posted the screenshot, where I can find the canary version to copy/paste?

**Comment by chakAs3** [comment]
> @chakAs3 At some places you are specifying a package as both peerDep and normal dep, is that intentional? To provide a default when the user doesn't install a package or something?

yes in some cases i need to have them in direct deps, it fails if I don't for this case

**Comment by kasperpeulen** [comment]
> > @chakAs3 At some places you are specifying a package as both peerDep and normal dep, is that intentional? To provide a default when the user doesn't install a package or something?
> 
> yes in some cases i need to have them in direct deps, it fails if the user not providing

cc @ndelangen

**Comment by ndelangen** [comment]
AFAIK specifying a package as a regular dependency AND as a peerDependency is very confusing.

It's signalling that you want the requester to have have/provide this package and simultaneously signalling you'll take care of supplying the package yourself.

A devDependency + peerDependency makes sense, because during development there's no requester, thus the package needs to be supplied.

A dependency + peerDependency doesn't make sense? because either your supply it yourself, OR it's supplied via the requester.

> yes in some cases i need to have them in direct deps, it fails if the user not providing

I'm hoping I understand correctly. So it's not really an optional peerDependency then?

**Comment by floroz** [comment]
Screenshot 2023-07-27 at 08 43 08

I upgraded our project to test this canary version and I found the following:

- the startup time for a story to first load has increased substantially (perceived ~5 seconds more?)


And I found this bug:
Screenshot 2023-07-27 at 08 52 36

So I removed all usages of `use-safe-attrs`

Screenshot 2023-07-27 at 08 51 55

Now it's throwing the same error in `color.ts`


As dug further, it seems that it throws this `ReferenceError: defineComponent is not defined` whenever a Vue component is imported from a file that is not a Vue component.

**Comment by chakAs3** [comment]
> I'm hoping I understand correctly. So it's not really an optional peerDependency then?

Yes @ndelangen  it is not optional,  and agree with you we should not have direct deps and peerDeps, however here we have a constraint   `vue-vite` requires `typescript` cause it uses tsChecker to get component meta, and i don't want to force the  user to install it so I will rather go for direct deps and remove is from peerDeps

**Comment by kasperpeulen** [comment]
@chakAs3 Could you have a look at the performance regression and bug from @floroz 
Do you notice something similar in your own Vue projects?

> Yes @ndelangen it is not optional, and agree with you we should not have direct deps and peerDeps, however here we have a constraint vue-vite requires typescript cause it uses tsChecker to get component meta, and i don't want to force the user to install it so I will rather go for direct deps and remove is from peerDeps

I see what you mean, it is hard, because if we remove it from peerDeps, we are forcing the user to use our version of TS right?

**Comment by chakAs3** [comment]
> I see what you mean, it is hard, because if we remove it from peerDeps, we are forcing the user to use our version of TS right?

no in this case `vue-vite` use his own typescript in his ts-checker, user still uses his typescript version in devDeps

**Comment by chakAs3** [comment]
> Could you have a look at the performance regression

yes, I notice this performance degradation but this is only at the start when we run static code analysis I will check it out.

**Comment by ndelangen** [comment]
So whatever it is that is needing `typescript`... could that package be a optional peerDependency for us then?
And so if users don't add this dependency, we fallback to something else, or skip?

That way `typescript` doesn't become a peerDependency?

**Comment by floroz** [comment]
> > Could you have a look at the performance regression
> 
> yes, I notice this performance degradation but this is only at the start when we run static code analysis I will check it out.

@chakAs3 do you know if this PR would also solve this issue with static analysis for docs generation? https://github.com/storybookjs/storybook/issues/23437#issuecomment-1650016298 ?

**Comment by Dschungelabenteuer** [comment]
Hey @chakAs3! Once again thank you so much for all these efforts you put in Storybook's Vue renderer! 

We have upgraded Vue to 3.3 and refactored our components (especially props with imported types) to reduce code duplication, and as we would expect it broke our Storybook because of `vue-docgen-api` :-) That's why I've been anticipating this change a lot, great work, there! 

I gave the `0.0.0-pr-22285-sha-d07bfc52` release a try and ran into some issues which can be observed in a [simple repro](https://github.com/Dschungelabenteuer/storybook-vue33):

- Whenever one of my components [imports a `.ts` file](https://github.com/Dschungelabenteuer/storybook-vue33/blob/main/src/stories/Button.vue#L10) with a [default export](https://github.com/Dschungelabenteuer/storybook-vue33/blob/main/src/stories/useSomething.ts#L16), I get an error
- If I change the mentioned default export into a [named export](https://github.com/Dschungelabenteuer/storybook-vue33/blob/named-export-composable/src/stories/useSomething.ts#L36), I get the same error as @floroz
- [Aliases](https://github.com/Dschungelabenteuer/storybook-vue33/tree/with-aliases) don't seem to be picked and resolved by [`@volar/typescript`](https://github.com/vuejs/language-tools/blob/master/packages/vue-component-meta/src/index.ts#L224) during static analysis.

I might have some misconception about what's going on and how component meta is actually resolved, but I feel like something may be off about [these lines](https://github.com/storybookjs/storybook/pull/22285/files#diff-e8cc604f67f49484b1513c410951436fed4e9d07198da3a0c257d8d176f42295R65-R76). Unlike the [`vue-vite` version](https://github.com/storybookjs/storybook/pull/22285/files#diff-2ee2ca494a969cacc82abf2c9944d5923b43ccb933c0133a0645e62e149d1f1eR10), the [`vue3-vite`](https://github.com/storybookjs/storybook/pull/22285/files#diff-e8cc604f67f49484b1513c410951436fed4e9d07198da3a0c257d8d176f42295R19) filter also includes `ts(x)` and `js(x)` files. My understanding is that it is done to provide support for components created through `defineComponent`?

If that's the case, is there any reason not to filter out all `js(x)` and `ts(x)` files that do not import `defineComponent` from `vue`? Isn't `vue-component-meta` supposed to recursively extract components meta on its own? I'm wondering because when I take a look at the output `__docgenInfo` of non-component files (e.g. my repro's `useSomething` composable), it doesn't seem like it provides any valuable data?

Regarding the alias not being resolved, I have to admit I don't really understand the rationale behind [these lines](https://github.com/storybookjs/storybook/pull/22285/files#diff-e8cc604f67f49484b1513c410951436fed4e9d07198da3a0c257d8d176f42295R28-R35). Shouldn't the component meta checker use the end-user's `(j|t)sconfig.json` compiler options? I tried to change these lines to the following:
```ts
  const checker = createComponentMetaChecker(
    path.resolve(getProjectRoot().absolutePathToProjectRoot, 'tsconfig.json'), // (or jsconfig.json)
    checkerOptions
  );
```
And assuming the first two issues were previously fixed, it seems to work fine and be able to correctly extract component meta even when using aliases. Am I missing something obvious?

Unfortunately, I also noticed the performance issue both when booting up Storybook and first loading a Story. Especially on large codebases with a lot of exports (e.g. with barrel files). Although the slowdown is quite negligible in my repro, things have gone quite off the charts in my team's Storybook: some stories could take up to 50s to load, and a few components even seemed to be doomed in some infinite analysis loop (although I could not 100% confirm that because my log files blow up pretty fast). This is especially annoying since a simple hover in Storybook's sidebar triggers the preload of the hovered target story/page, which easily turns into quite a bottleneck! I can't solely blame the PR because I'm well aware of the trade-offs implied by `@vue/compiler-sfc`'s static analysis of imported types that was introduced with Vue 3.3, and I know we may have some unconventional setup that deserves a bit of cleanup. But I couldn't resist investigating further:

I've logged all of the calls to `vue-component-meta`'s `getComponentMeta` method and surprisingly it looks like some files are analyzed multiple times (without triggering any HMR):

```
Getting component meta for {dir}/src/stories/Button.stories.ts
Getting component meta for {dir}/src/stories/Button.stories.ts
Getting component meta for {dir}/src/stories/Button.stories.ts
Getting component meta for {dir}/src/stories/Button.stories.ts
Getting component meta for {dir}/src/stories/Button.stories.ts
Getting component meta for {dir}/src/stories/Button.vue
Getting component meta for {dir}/jsconfig.json.global.vue
Getting component meta for {dir}/src/stories/useSomething.ts
```

This is probably caused by [those lines](https://github.com/storybookjs/storybook/pull/22285/files#diff-e8cc604f67f49484b1513c410951436fed4e9d07198da3a0c257d8d176f42295R44-R45). Since `*.stories.ts` are not filtered out of the plugin, every single export/story results in a `getComponentMeta` call. Applying my above suggestions & considerations helped me get rid of the infinite loops and get these ~50s down to ~6s, which is still not ideal but way more acceptable. So where are those six remaining seconds coming from? Well I did not dig much further, but it looks like getting rid of [this call to `getExportNames`](https://github.com/storybookjs/storybook/pull/22285/files#diff-e8cc604f67f49484b1513c410951436fed4e9d07198da3a0c257d8d176f42295R44) made things pretty fast again! There still is a bit more latency than before, but that's to be expected because of the static analysis and definitely not a a big deal).

Please let me know if I can be of any help, or if I'm missing the point completely 😅 

And once again, thank's for the hard work!

**Comment by chakAs3** [comment]
> Please let me know if I can be of any help, or if I'm missing the point completely 😅

You have been already helpfull by your investigation, i noticed also some performance issue and now i got some ideas thanks to you analytics let me check it out, i was a bit busy with Nuxt integration, i'm almost done i will look back to this.

Really glad after this comment i will get in touch with you, sure i will help me go faster. ❤️

**Comment by Dschungelabenteuer** [comment]
@chakAs3 it's worth noting that latest version of [`vue-component-meta` has an issue](https://github.com/vuejs/language-tools/issues/3566). 

Also, [here](https://github.com/Dschungelabenteuer/storybook/tree/n028/vue334) is a branch which illustrates a working example based on my previous feedback. However:
- I only picked your changes on vue3 (no vue, examples and other things)
- I completely filtered out `ts(x)` files for illustration purposes (so my branch probably wouldn't work with `defineComponent`s)
- I had to rollback vue-component-meta to `1.8.8` due to the issue I mentioned

I'm using this branch's `@storybook/vue3-vite` and `@storybook/vue3` builds as pnpm patches on my large codebase and this seems to be working pretty fine :-)

**Comment by chakAs3** [comment]
> @chakAs3 it's worth noting that latest version of [`vue-component-meta` has an issue](https://github.com/vuejs/language-tools/issues/3566).
> 
> Also, [here](https://github.com/Dschungelabenteuer/storybook/tree/n028/vue334) is a branch which illustrates a working example based on my previous feedback. However:
> 
> * I only picked your changes on vue3 (no vue, examples and other things)
> * I completely filtered out `ts(x)` files for illustration purposes (so my branch probably wouldn't work with `defineComponent`s)
> * I had to rollback vue-component-meta to `1.8.8` due to the issue I mentioned
> 
> I'm using this branch's `@storybook/vue3-vite` and `@storybook/vue3` builds as pnpm patches on my large codebase and this seems to be working pretty fine :-)

I'm aware of the issue i already reported to johnson the maintainer i'm not getting in response it is quite strange that breaks like this

**Comment by so1ve** [comment]
Update: the issue has been fixed now!

**Comment by chakAs3** [comment]
> Update: the issue has been fixed now!

thanks for the update

**Comment by elevatebart** [comment]
@chakAs3 I absolutely love this PR! Great job! I only have a concern about performance. 

Did you test if the same code base would take shorter time to generate or longer?

Anyway short or long it's still progress. We can optimize later.

**Comment by chakAs3** [comment]
> @chakAs3 I absolutely love this PR! Great job! I only have a concern about performance.
> 
> Did you test if the same code base would take shorter time to generate or longer?
> 
> Anyway short or long it's still progress. We can optimize later.

Hi @elevatebart  thanks for the support, yes that was a performance issue i reduce it by excluding stories and config files, but i can think of explicit set the components folder or something of this sort.  do you think `vue-component-meta` less performant for some reason ?

**Comment by rmerk** [comment]
@chakAs3 is this close to getting merged?

**Comment by Dschungelabenteuer** [comment]
Oops my bad, @chakAs3! Took some time off and I've just noticed your comment thanks to yesterday's notification :') Do you want me to test anything specific? I've got both a minimal and a rather large codebase I could test any change against! 

FWIW, Unsurprisingly, I do get (s)lower performances when only filtering out story files (_vs._ filtering out all `js/ts(x)` files), but yeah, we both know we can't ignore those. Still, ignoring story files is better than nothing and definitely takes a weight off Vue's type resolving steps.

I like this idea of a framework-level configuration, fine-grained control is great for more experienced users, but we should still make sure to provide the most versatile defaults, and there's basically a trade off between "covering most cases by default" and "be as fast as possible by default". I guess this is rather a governance-related matter.

**Comment by chakAs3** [comment]
> @chakAs3 is this close to getting merged?

I will have to check with team to get it merged.

**Comment by chakAs3** [comment]
> Oops my bad, @chakAs3! Took some time off and I've just noticed your comment thanks to yesterday's notification :') Do you want me to test anything specific? I've got both a minimal and a rather large codebase I could test any change against!
> 
> FWIW, unsurprisingly, I do get (s)lower performances when only filtering out story files (_vs._ filtering out all `js/ts(x)` files), but yeah, we both know we can't ignore those. Still, ignoring story files is better than nothing and definitely takes a weight off Vue's type resolving steps.
> 
> I like this idea of a framework-level configuration, fine-grained control is great for more experienced users, but we should still make sure to provide the most versatile defaults, and there's basically a trade off between "covering most cases by default" and "be as fast as possible by default". I guess this is rather a governance-related matter.

Hi i'm kind of sharing the same take, let me see what we can do to accelerate this.

**Comment by jnarowski** [comment]
+1 to wanting this merged asap. I am about to push Storybook to my whole team and would need argTypes and TypeScript to play better together. Without this docs get out of sync and it's very hard to maintain. 

Anything I can do to help?

**Comment by chakAs3** [comment]
@jnarowski  glad to hear that, i will get back to this PR,  after Paris Meetup tomorrow https://twitter.com/storybookjs/status/1721557650477850694, you can watch online if you any question or request

**Comment by mokone91** [comment]
+1, this is very important pr, wanting this merged!

**Comment by chakAs3** [comment]
> +1, this is very important pr, wanting this merged!

sorry i was bit busy these days, i have an idea of how you can get this feature immediately in your project, especially if you use Nuxt

**Comment by pgalhardo** [comment]
What do you think is the milestone for this one—7.X or 8?

**Comment by kasperpeulen** [comment]
Would love to include this in 8.0. 
We are thinking about releasing 8.0 somewhere in Q1 of 2024, do you think that is feasible @chakAs3?

**Comment by chakAs3** [comment]
> Would love to include this in 8.0. We are thinking about releasing 8.0 somewhere in Q1 of 2024, do you think that is feasible @chakAs3?

Yes i think so i will allow sometime for this

**Comment by thomasaull** [comment]
@chakAs3 Is there any way we could use this already? If so, can you give me a high level overview how to do it?

**Comment by chakAs3** [comment]
> @chakAs3 Is there any way we could use this already? If so, can you give me a high level overview how to do it?

Yes  i can release it in separate package kind of a fork until been reviewed by the team to be included in Storybook 8.

**Comment by thomasaull** [comment]
> Yes i can release it in separate package kind of a fork until been reviewed by the team to be included in Storybook 8.

@chakAs3 This would be awesome!

**Comment by kasperpeulen** [comment]
We can release this as a canary as well. I can put some work into it.
What is the current state of this PR @chakAs3 ?

**Comment by chakAs3** [comment]
> We can release this as a canary as well. I can put some work into it. What is the current state of this PR @chakAs3 ?

I have checked it, it looks fine for me. a canary release will be great for better test, let me know what i can do, there is some weird issue with e2e test for lit sandbox can you check that as well ?

**Comment by kasperpeulen** [comment]
@chakAs3 Yeah e2e tests are flaky, @yannbf is looking at it.
I will make a canary!

**Comment by kasperpeulen** [comment]
Released!
image

**Comment by elevatebart** [comment]
> Released! image

As seen at the bottom of the description of the PR, if anyone come here looking to test it.

Thank you again @chakAs3

**Comment by Clarkkkk** [comment]
Thank you all for your work. I can't wait to try it out at once. And I have this error:
```
ReferenceError: defineComponent is not defined
    at http://localhost:6006/src/utils/createContext.ts:10:26
```
Here is the reproduction [repo](https://github.com/Clarkkkk/Netease-Music-App), and the error occurs in `ContextMenu.stories.ts`.  Can you please check it?

**Comment by seanogdev** [comment]
Is this a candidate for V8?

**Comment by kasperpeulen** [comment]
@seanogdev It can be merged at any time, when the CI is green and the reported bugs and performant issues are fixed.
Feel free to try out the canary in the meantime.

cc @chakAs3 Do you think you have time the coming months to finalize this PR?

**Comment by chakAs3** [comment]
> cc @chakAs3 Do you think you have time the coming months to finalize this PR?

I'm ready to dedicate time to finalize this PR, but it needs a thorough review first. I believe it's almost ready, and I've even added some additional unit tests.

**Comment by larsrickert** [comment]
@chakAs3 Amazing work! Thanks for your work. Love to see that advanced property types are supported now and event parameters are extracted.

Is there anything I can help to speed up the completion of this PR?
@kasperpeulen Would it be possible to release this change already as version 8 beta so we don't have to wait for the final 8.0.0 for this great feature?

**Comment by larsrickert** [comment]
@chakAs3 I did some tests and found some minor bugs. You can check them out live on Stackblitz (you need to reload the Storybook in the Stackblitz browser after it started, idk why): https://stackblitz.com/~/github.com/larsrickert/storybook-bug-reproduction-22285

image

1. Descriptions are missing for events
2. Exposed contains some unintended entries:
     - `$slots`
     - `on[eventName]` entry for every event, e.g. `onUpdate:modelValue` for event called `update:modelValue`
 3. Nice to have (optional):
    - Might be a general Storybook issue but the default value "red" is not checked initially in the controls 
    - For properties with union types like the `color` property, in my opinion it would be nicer if the control would show a dropdown/select instead of radio buttons by default. Otherwise the radio control can get very long if the union type contains many types 
image


The remaining features of your PR work fine for my testings. Great job 👍

**Comment by kasperpeulen** [comment]
> Is there anything I can help to speed up the completion of this PR?

I think testing mostly. So thanks for that!

If you know more about Volar and have ideas how to solve the raised bugs and performance issues, I can make you storybook maintainer, so you can pair with @chakAs3 on this PR :)

**Comment by larsrickert** [comment]
> > Is there anything I can help to speed up the completion of this PR?
> 
> I think testing mostly. So thanks for that!
> 
> If you know more about Volar and have ideas how to solve the raised bugs and performance issues, I can make you storybook maintainer, so you can pair with @chakAs3 on this PR :)

Yeah if its fine for @chakAs3 I can support finishing this PR :)

**Comment by chakAs3** [comment]
> Yeah if its fine for @chakAs3 I can support finishing this PR :)

ofcourse i will be thankful if you can help. you are welcome

**Comment by chakAs3** [comment]
> > Yeah if its fine for @chakAs3 I can support finishing this PR :)
> 
> ofcourse i will be thankful if you can help. you are welcome but for the bugs have nothing to do with Volar, it is more on the Story controls
> 
> and for `namedSlot` i can see it is of type `namedSlot(args:{value:string})` so you need to pass the props, it seems normal to break otherwise.Also bear with us for the controls are basic for now, some major work needed to be done as slots in Vue are very different than React or other frameworks

**Comment by larsrickert** [comment]
Somes updates:

- "defineComponent" error is fixed
- Redundant entries under "Exposed" are removed
- Seems like event descriptions can not be supported by `vue-component-meta`, see [this Volor issue](https://github.com/vuejs/language-tools/issues/1894#issuecomment-1281648320). I am not sure how to handle this missing feature tho
- Regarding the performance issues:
    - I guess the main issue is that .ts/.js files are included by default (esspecially because larger project may have lots of regular .ts files)
    - imho, exported components from .ts/.js files are very rare (most projects probably use regular .vue components)
    - What do you think of excluding .ts/.js files by default and add a framework option to opt-in? Like this we have better performance by default while still supporting .ts/.js files

**Comment by seanogdev** [comment]
Could we [switch out the checker](https://github.com/msokk/volar/blob/7ef30c2d1c2dc94c83c3f4e6da514e74d338765f/packages/vue-component-meta/src/index.ts#L61) based on if we find a tsconfig ?

**Comment by larsrickert** [comment]
> Could we [switch out the checker](https://github.com/msokk/volar/blob/7ef30c2d1c2dc94c83c3f4e6da514e74d338765f/packages/vue-component-meta/src/index.ts#L61) based on if we find a tsconfig ?

You're right some projects might not have a tsconfig.json file...I updated it to use a fallback checker if no tsconfig.json exists

**Comment by larsrickert** [comment]
@kasperpeulen Is it possible to create a new canary release so we can try out the fixed issues? The known bugs should mostly be fixed now. Open points are:

- Event descriptions are missing. This is a current Volar limitation, I added a [feature request](https://github.com/vuejs/language-tools/issues/3893) for it
- Performance issue: My sugeestion would be to only include .vue by default and add a framework option to allow jsx,tsx,js and ts files. However, it would be great if someone could provide a repo with a large reproduction example so we can actually test this out

**Comment by larsrickert** [comment]
@chakAs3 I added a temporary workaround for the missing event description from Volar until [the Volar feature request is implemented](https://github.com/vuejs/language-tools/issues/3893) that uses the previous "vue-docgen-api". What do you think about it?: https://github.com/storybookjs/storybook/pull/22285/files#diff-e8cc604f67f49484b1513c410951436fed4e9d07198da3a0c257d8d176f42295R184

**Comment by kasperpeulen** [comment]
@larsrickert Canary release is running!

**Comment by kasperpeulen** [comment]
> Performance issue: My sugeestion would be to only include .vue by default and add a framework option to allow jsx,tsx,js and ts files. However, it would be great if someone could provide a repo with a large reproduction example so we can actually test this out

This sounds good to me. WDYT @chakAs3 ?

File: code/frameworks/vue3-vite/src/plugins/vue-component-meta.ts [hunk 1]
```diff
@@ -0,0 +1,228 @@
...
+    // find a temp workaround for this
+    // see: https://github.com/vuejs/language-tools/issues/3896
+
+    // prefer the tsconfig.json file of the project to support alias resolution etc.
+    return createComponentMetaChecker(projectTsConfigPath, checkerOptions);
+  }
+
+  return createComponentMetaCheckerByJsonConfig(
+    projectRoot,
+    { include: ['src/**/*'] },
```
Comment (seanogdev) [inline code/frameworks/vue3-vite/src/plugins/vue-component-meta.ts:146]:
```suggestion
    { include: ['**/*'] },
```

We probably cant be 100% sure users place their files in the src dir.

**Review by seanogdev — COMMENTED** [review]
Thank you for the work on this @larsrickert !

**Comment by chakAs3** [comment]
> > Performance issue: My sugeestion would be to only include .vue by default and add a framework option to allow jsx,tsx,js and ts files. However, it would be great if someone could provide a repo with a large reproduction example so we can actually test this out
> 
> This sounds good to me. WDYT @chakAs3 ?

I like the framework option i have already thought about it. for now most people use .vue file, but they should not be limited to that us js component are very useful, we have even created PR on Volar vue-component-meta addressing  detecting if js/ts file is component with it is type but this won't present processing the file which impact the performance

this proposed solution will reduce the number of file processed but not solve the real issue which is performance will occur with large component number project, what i did is the exclude the *.stories.js.   and already suggestion an explicit framework option but i did not get time to work on it

**Comment by chakAs3** [comment]
> @chakAs3 I added a temporary workaround for the missing event description from Volar until [the Volar feature request is implemented](https://github.com/vuejs/language-tools/issues/3893) that uses the previous "vue-docgen-api". What do you think about it?: https://github.com/storybookjs/storybook/pull/22285/files#diff-e8cc604f67f49484b1513c410951436fed4e9d07198da3a0c257d8d176f42295R184

i don't see the workaround is necessary for this, unless it is tested and not asking any extra work from the user end, then after the official fix by volar we will have to depreciate the workaround  WDYT.  @kasperpeulen ?

**Comment by larsrickert** [comment]
> > @chakAs3 I added a temporary workaround for the missing event description from Volar until [the Volar feature request is implemented](https://github.com/vuejs/language-tools/issues/3893) that uses the previous "vue-docgen-api". What do you think about it?: https://github.com/storybookjs/storybook/pull/22285/files#diff-e8cc604f67f49484b1513c410951436fed4e9d07198da3a0c257d8d176f42295R184
> 
> i don't see the workaround is necessary for this, unless it is tested and not asking any extra work from the user end, then after the official fix by volar we will have to depreciate the workaround WDYT. @kasperpeulen ?

We don't need to deprecate the workaround. Since it is just internal implementation, we can just remove the workaround and update "vue-component-meta" once it is supported there. Nothing will change for the end user :)

**Comment by chakAs3** [comment]
@larsrickert @kasperpeulen it looks good for me, i have approved the baseline change, and tested visually everything looks great, event description are showing, thanks to @larsrickert. Bravo.

All green 🚀 🟢  @kasperpeulen

**Comment by larsrickert** [comment]
> @larsrickert @kasperpeulen it looks good for me, i have approved the baseline change, and tested visually everything looks great, event description are showing, thanks to @larsrickert. Bravo.
> 
> All green 🚀 🟢 @kasperpeulen

Thanks :) @kasperpeulen Please do **not** merge this PR yet due to the open points (see PR description). Esspecially the tsconfig issue will break many projects if not fixed (I can probably work on this tomorrow)

**Comment by chakAs3** [comment]
> tsconfig issue will break many projects if not fixed

tsconfig is not required you can apply No Ts config based checker,  i remember testing it in no typescript project. did you face an issue in here?

**Comment by larsrickert** [comment]
> > tsconfig issue will break many projects if not fixed
> 
> tsconfig is not required you can apply No Ts config based checker, i remember testing it in no typescript project. did you face an issue in here?

Yes I faced an issue because aliases are not resolved for imports so if the project e.g. has an alias "@" for "./src" (which is the default for the Vue starter projects), all imports and therefore types/docs that use this alias are not resolved.

Therefore we should use the tsconfig file of the project if possible. Maybe using the non-tsconfig checker is a temporary workaround/limitation but I'd like to use the tsconfig version.

**Comment by chakAs3** [comment]
> the default for the Vue starter projects), all imports and therefore types/docs that use this alias are not resolved.

you should extend the noTsConfigChecker with tsconfig you can use the same as vue-component-meta's tsconfig 

```ts
{
		"extends": "../tsconfig.json",
		"include": [
			"**/*",
		],
	},
```

File: code/frameworks/vue3-vite/src/plugins/vue-component-meta.ts [hunk 2]
```diff
@@ -0,0 +1,224 @@
...
+  const checkerOptions: MetaCheckerOptions = {
+    forceUseTs: true,
+    noDeclarations: true,
+    printer: { newLine: 1 },
+  };
+
+  const projectRoot = getProjectRoot();
+  const projectTsConfigPath = path.join(projectRoot, 'tsconfig.json');
+
+  if (await fileExists(projectTsConfigPath)) {
```
Comment (chakAs3) [inline code/frameworks/vue3-vite/src/plugins/vue-component-meta.ts:135]: @larsrickert this should do the job to detect if the project has tsconfig

File: code/frameworks/vue3-vite/src/plugins/vue-component-meta.ts [hunk 3]
```diff
@@ -0,0 +1,224 @@
...
+    // TODO: tsconfig that uses references is currently not supported by vue-component-meta
+    // find a temp workaround for this
+    // see: https://github.com/vuejs/language-tools/issues/3896
+
+    // prefer the tsconfig.json file of the project to support alias resolution etc.
+    return createComponentMetaChecker(projectTsConfigPath, checkerOptions);
+  }
+
+  return createComponentMetaCheckerByJsonConfig(projectRoot, { include: ['**/*'] }, checkerOptions);
```
Comment (chakAs3) [inline code/frameworks/vue3-vite/src/plugins/vue-component-meta.ts:144]: you can pass extend this with the package tsconfig like this 
```
{
		"extends": "../tsconfig.json",
		"include": [
			"**/*",
		],
	},
	```

Comment (chakAs3) [reply code/frameworks/vue3-vite/src/plugins/vue-component-meta.ts:144]: you can use the standard one used in vue language tools https://github.com/vuejs/language-tools/blob/master/packages/component-meta/tsconfig.json

Comment (larsrickert) [reply code/frameworks/vue3-vite/src/plugins/vue-component-meta.ts]: > you can extend this with the package tsconfig like this

We can not use any arbitrary tsconfig, it has to be exactly the tsconfig of the project. See this example which is taken from a new Vue starter application:
```json
// tsconfig.json
{
  "files": [],
  "references": [
    { "path": "./tsconfig.node.json" }, // not relevant for this example
    { "path": "./tsconfig.app.json" },
    { "path": "./tsconfig.vitest.json" } // not relevant for this example
  ]
}
```

```json
// tsconfig.app.json
{
  "extends": "@vue/tsconfig/tsconfig.dom.json",
  "include": ["env.d.ts", "src/**/*"],
  "compilerOptions": {
    // ...
    "paths": {
      "@/*": ["./src/*"]
    }
  }
}
```

And now you have a component in your project that uses `@/` for imports:
```vue
<script lang="ts" setup>
import type { MyProps } from "@/types";

const props = defineProps<MyProps>();
</script>
```

`vue-component-meta` can not resolve the type/docs correctly so they will not show up in Storybook. Therefore we should prefer the actual tsconfig of the project over the non-tsconfig checker.

**Comment by kasperpeulen** [comment]
@chakAs3 @larsrickert
Should we do any documentation changes if we merge this PR?

**Comment by larsrickert** [comment]
> @chakAs3 @larsrickert Should we do any documentation changes if we merge this PR?

Yes I think it would be good to document that we switched the doc plugin and that the project should check if everything still works fine for them. Where should I add such documentation?

I will watch the open Volar issues and update Storybook / remove the current workarounds. I'd say we can do this in a follow up PR so this one is not blocked.

So basically the only thing left are the performance issues:
- The largest project that I have access to has 78 vue components and 205 .ts files. The build step and serving the static build output had fine performance for me. Only the initial loading time when starting up the dev server (`storybook dev -p 6006`) until a story is shown in the browser took a lot longer (see table below)
- only including .vue files only provided a very small performance improvement in my tests so I am not sure how we could improve it. Maybe the `vue-component-meta` has some initial warp up time? Would appreciate any ideas on this. @kasperpeulen Would this be a blocker to merge this PR in your opinion?

| Storybook version           | Time (dev server start to first story visible) | Notes                      |
| --------------------------- | ---------------------------------------------- | ------------------------- |
| 0.0.0-pr-22285-sha-21557c1b | ~13 seconds                                    |                           |
| 0.0.0-pr-22285-sha-21557c1b | ~11.5 seconds                                  | Only include `.vue` files |
| 8.0.0-beta.3                | ~5 seconds                                     |                           |

_Benchmarked on M1 Max Macbook Pro_

**Comment by kasperpeulen** [comment]
> Yes I think it would be good to document that we switched the doc plugin and that the project should check if everything still works fine for them. Where should I add such documentation?

It can be added here!
https://github.com/storybookjs/storybook/blob/next/MIGRATION.md

Are you available on Discord @larsrickert for a quick call how to release this?

**Comment by larsrickert** [comment]
> Are you available on Discord @larsrickert for a quick call how to release this?

Sure you can add me: https://discord.com/users/251414332955557889

**Comment by kasperpeulen** [comment]
Thank you so much @larsrickert and @chakAs3 for making this PR stable again.

I am discussing with @shilman how to release this.

We think the best way to release this would be to make the "docgen" for vue still switchable in 8.x defaulting to `vue-docgen-api` in 8.0 but can be overriden to this `volar` implementation.

We can then default to `volar` in 8.x or 9.0 once we have enough feedback.

In this way, we are also able to improve the performance in the meantime without blocking this PR. 
Maybe @IanVS @ndelangen or @joshwooding have some tips how they did this with react-docgen-typescript. 
I guess we might somehow be able to scan lazy load one component at a time? Instead of all at startup.

We have framework options. So I guess the api should be:

```ts
// main.ts
const config: StorybookConfig = {
  framework: {
    name: '@storybook/vue3-vite',
    options: {
      docgen: 'volar', // defaults to vue-docgen-api
    },
  },
};

export default config;
```

**Comment by kasperpeulen** [comment]
@larsrickert Somehow I can not add you, but we could talk in this channel:
https://discord.gg/75Q7DPtS

**Comment by seanogdev** [comment]
Just to add a personal anecdote, I'm using component-meta in our product to help generate docs for our design system, the forceTs option was prohibitively slow for us. For 125 components that went from ~15s to just under ~4s

**Comment by thomasaull** [comment]
Regarding performance: Maybe the Volar extension for VS Code does caching of some sort — it doesn't feel particularly slow even in large projects

**Comment by larsrickert** [comment]
> Just to add a personal anecdote, I'm using component-meta in our product to help generate docs for our design system, the forceTs option was prohibitively slow for us. For 125 components that went from ~15s to just under ~4s

Unfortunately this didn't improve performance in my tests :/

**Comment by larsrickert** [comment]
@kasperpeulen As discussed:

- framework option is added and defaults to "vue-docgen-api"
- only thing left to do is to document the change so people are aware of the new feature :) Is the `MIGRATION.md` the right place for this? Seems like only breaking changes are added there, not new features.

**Comment by kasperpeulen** [comment]
Right, as it is not breaking anymore it doesn't have to be added to MIGRATION.md.
We will update the documentation cc @kylegach and probably do 8.0 feature post about it cc @joevaugh4n

**Comment by chakAs3** [comment]
> Right, as it is not breaking anymore it doesn't have to be added to MIGRATION.md. We will update the documentation cc @kylegach and probably do 8.0 feature post about it cc @joevaugh4n

It's fantastic to see this PR evolving nicely! Huge thanks to everyone involved for their contributions. While the documentation may need some refinement with @kylegach to fit into the official docs, I'm eager to assist with that. Additionally, I'm keen to collaborate on the blog post with @joevaugh4n. Big kudos to @kasperpeulen & @larsrickert for their efforts! 👍 🚀

**Comment by chakAs3** [comment]
i rather suggest to call it `vue-component-meta` (the package namee) to be more specific as Volar is the larger it includes all vue language tools
```ts
const config: StorybookConfig = {
  framework: {
    name: '@storybook/vue3-vite',
    options: {
      docgen: 'vue-component-meta', // defaults to vue-docgen-api
    },
  },
};

**Comment by chakAs3** [comment]
> In this way, we are also able to improve the performance in the meantime without blocking this PR.
> Maybe @IanVS @ndelangen or @joshwooding have some tips how they did this with react-docgen-typescript.
> I guess we might somehow be able to scan lazy load one component at a time? Instead of all at startup.

i think the actual problem with performance is due to files `transform`, Volar is so fast because it does extract meta via static code analysis.
Maybe generating  virtual component meta files in build time will eliminate completely this issue.

**Review by kasperpeulen — APPROVED** [review]
Thanks so much @chakAs3 and @larsrickert

**Review by larsrickert — APPROVED** [review]
