### PR TITLE
Core: Fix indexing for non-prefixed `stories.*` stories

### LINKED ISSUE #23923: [Bug]: I cannot name stories `stories.tsx`
### Describe the bug

When naming stories like this: `stories.tsx`, I get this error:
```
 Error: Invariant failed: No matching indexer found for /Users/user/server/app/components/Link/stories.tsx
    at invariant (/Users/user/server/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:14:11)
    at StoryIndexGenerator.extractStories (/Users/user/server/node_modules/@storybook/core-server/dist/index.js:60:4143)
    at /Users/user/server/node_modules/@storybook/core-server/dist/index.js:60:2601
    at /Users/user/server/node_modules/@storybook/core-server/dist/index.js:60:2058
    at Array.map (<anonymous>)
    at /Users/user/server/node_modules/@storybook/core-server/dist/index.js:60:1965
    at Array.map (<anonymous>)
    at StoryIndexGenerator.updateExtracted (/Users/user/server/node_modules/@storybook/core-server/dist/index.js:60:1718)
    at StoryIndexGenerator.ensureExtracted (/Users/user/server/node_modules/@storybook/core-server/dist/index.js:60:2517)
    at StoryIndexGenerator.initialize (/Users/user/server/node_modules/@storybook/core-server/dist/index.js:60:1622)
```

This on the other hand works:
```
Something.stories.tsx
```

### To Reproduce

_No response_

### System

```shell
Environment Info:

  System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
  Browsers:
    Chrome: 116.0.5845.110
    Safari: 16.5.2
  npmPackages:
    @storybook/addon-essentials: 7.3.2 => 7.3.2 
    @storybook/addon-interactions: 7.3.2 => 7.3.2 
    @storybook/addon-links: 7.3.2 => 7.3.2 
    @storybook/addon-onboarding: 1.0.8 => 1.0.8 
    @storybook/addon-styling: 1.3.6 => 1.3.6 
    @storybook/blocks: 7.3.2 => 7.3.2 
    @storybook/react: 7.3.2 => 7.3.2 
    @storybook/react-vite: 7.3.2 => 7.3.2 
    @storybook/testing-library: 0.2.0 => 0.2.0
```

### Additional context

main.ts file:

```ts
import type { StorybookConfig } from "@storybook/react-vite";

const config: StorybookConfig = {
  stories: [
    "../app/components/**/stories.tsx",
    "../app/components/**/*.stories.@(ts|tsx)",
    "../app/utils/styles/**/*.stories.@(ts|tsx)",
  ],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-onboarding",
    "@storybook/addon-interactions",
    {
      name: "@storybook/addon-styling",
      options: {},
    },
  ],
  framework: {
    name: "@storybook/react-vite",
    options: {},
  },
  docs: {
    autodocs: "tag",
  },
};
export default config;
```

### PR DESCRIPTION
**Pull request by shilman**
Closes #23923

## What I did

Add support for `(stories|story)\.*` files

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [x] integration tests
- [ ] end-to-end tests

#### Manual testing

Add a `stories.ts` file to a sandbox

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

File: code/lib/core-server/src/presets/common-preset.ts [hunk 1]
```diff
@@ -196,7 +196,7 @@ export const features = async (
 });
 
 export const csfIndexer: Indexer = {
-  test: /\.(stories|story)\.(m?js|ts)x?$/,
+  test: /(stories|story)\.(m?js|ts)x?$/,
```
Comment (Hypnosphi) [inline code/lib/core-server/src/presets/common-preset.ts:199]: we use `.examples.tsx` naming convention in our project. Can we somehow override this regexp in our config?

Comment (shilman) [reply code/lib/core-server/src/presets/common-preset.ts:199]: No. There's been talk about using the stories glob directly, but that's not implemented. Easiest thing is to use .stories.x per the documentation

Comment (shilman) [reply code/lib/core-server/src/presets/common-preset.ts:199]: You could also add a custom indexer yourself. @JReinhold  and @kylegach are working on docs for that

Comment (antrianis) [reply code/lib/core-server/src/presets/common-preset.ts:199]: Did we get documentation on this?

Comment (JReinhold) [reply code/lib/core-server/src/presets/common-preset.ts:199]: yes @antrianis! The docs won't be published until the next minor version, but you can see it here: https://github.com/storybookjs/storybook/blob/next/docs/api/main-config-indexers.md
