### PR TITLE
Core: Disable interactions debugger on composed stories to avoid cross-origin error

### LINKED ISSUE #31650: [Bug]: Interactions broken in composed storybook instances
### Describe the bug

When using [Storybook Composition](https://storybook.js.org/docs/sharing/storybook-composition) in v9, the "Interactions" tab of stories is blank and a security error is logged in the console:

```
SecurityError: Failed to read a named property '__STORYBOOK_ADDON_INTERACTIONS_INSTRUMENTER_STATE_' from 'Window': Blocked a frame with origin "http://localhost:6007" from accessing a cross-origin frame.
  at instrument (runtime.js:24150:5)
  at runtime.js:24175:20
```

If you open the child composed storybook instance directly, the Interactions panel behaves as expected.

Image

Image

Parent: https://stackblitz.com/edit/github-zxyr5zjk?file=.storybook/main.ts
Child: https://stackblitz.com/edit/github-zxyr5zjk-e5173fnk?file=src/stories/Button.stories.ts

### Reproduction link

https://stackblitz.com/edit/github-zxyr5zjk

### Reproduction steps

1. Open and run parent instance: https://stackblitz.com/edit/github-zxyr5zjk?file=.storybook/main.ts
1. Open and run child instance: https://stackblitz.com/edit/github-zxyr5zjk-e5173fnk?file=src/stories/Button.stories.ts
1. Observe button/primary story of the child Storybook instance when viewed from the parent Storybook instance has passing interactions, but no details: https://githubzxyr5zjk-iwaw--6006--55edb8f4.local-credentialless.webcontainer.io/?path=/story/child_example-button--primary
1. See error in console
1. Observe button/primary story in child Storybook instance with working interactions and details: https://githubzxyr5zjke5173fnk-zvhh--6006--55edb8f4.local-credentialless.webcontainer.io/?path=/story/example-button--primary
1. No errors in console

### System

```bash
Command not working in StackBlitz.
```

### Additional context

Seems like a CORS issue.

### PR DESCRIPTION
**Pull request by ghengeveld**
Closes #31650

## What I did

Gracefully handle cross-origin errors when accessing a composed Storybook with interactions, by catching the error and disabling debugger controls.

Screenshot 2025-06-06 at 14 25 27

The instrumenter attempts to retain its state when reloading the preview iframe by storing its state on the parent window. This is not allowed on composed Storybooks due to the same-origin policy. In most cases this is not a problem because the iframe will only be reloaded if the story can't be remounted within 3 'ticks' (see `StoryRender.teardown()`). If this scenario does happen, the instrumenter will lose its state. This is an edge case we can't easily resolve, because the state we're trying to preserve relies on object references and therefore can't be serialized (e.g. for sessionStorage or postMessage/channel).

Because we cannot predict when the iframe needs a full reload, I've decided to assume the worst and disable the debugger controls for composed Storybooks altogether.

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

## Greptile Summary

Fixes cross-origin security issues in Storybook's interactions panel when accessing composed stories by gracefully handling parent window state access restrictions.

- Added safe window state access methods in `code/core/src/instrumenter/instrumenter.ts` to handle cross-origin limitations
- Modified `Window` interface in `code/core/src/instrumenter/typings.d.ts` to properly declare global state variables
- Implements fallback to local-only state when cross-origin access fails, maintaining forward-only debugging capability
- Gracefully handles cases where iframe reloads occur in composed stories
- Preserves interaction functionality while limiting some debugging features (like backwards stepping) in cross-origin scenarios

### CODE REVIEW

**Comment by shannonmoeller** [comment]
Why disable it instead of fixing it? The data could be passed from the child to the parent with `window.postMessage(message, '*')`. Storybook could even be extended to allow configuration of the parent/child origin relationships to make it more secure than just `'*'`.

https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage

File: code/core/src/instrumenter/instrumenter.ts [hunk 1]
```diff
@@ -263,6 +255,24 @@ export class Instrumenter {
     }
   }
 
+  loadParentWindowState = () => {
+    try {
+      this.state = global.window?.parent?.__STORYBOOK_ADDON_INTERACTIONS_INSTRUMENTER_STATE__ || {};
```
Comment (shannonmoeller) [inline code/core/src/instrumenter/instrumenter.ts:260]: This should be changed to use `window.postMessage()` to enable safe cross-origin communication.

**Comment by shannonmoeller** [comment]
I have done similar things to fix issues syncing toolbar state across composed storybook instances. I have this in the preview.tsx file of the parent instance of my component library:

```ts
// Propagates global updates to composed storybook instances
window.addEventListener('message', (event)  => {
  const message = JSON.parse(event.data?.trim?.() || '{}');

  if (message.key !== 'storybook-channel') return;
  if (message.event?.type !== 'updateGlobals') return;

  window.top?.document.querySelectorAll('iframe').forEach((iframe) => {
    if (iframe.contentWindow === window) return;

    iframe.contentWindow?.postMessage(event.data, '*');
  });
});
```

**Comment by ghengeveld** [comment]
@shannonmoeller Unfortunately we can't use postMessage because as far as I know, its serialization method will lose object references. Instrumenter state contains a property `callRefsByResult` which is a `Map<any, CallRef>` where the key is the return value of an instrumented function call. This can be anything, including a DOM node reference or other non-serializable data. If this data would get serialized, we'd lose the reference to the original object (e.g. DOM node). `callRefsByResult` is required in order to track values back to their originating call. We might be able to work around it by rearchitecting how retained state works (i.e. the rows that you see below the current "breakpoint" line when debugging), but that's a much bigger lift.

File: code/core/src/instrumenter/instrumenter.test.ts [hunk 2]
```diff
@@ -712,6 +730,40 @@ describe('Instrumenter', () => {
...
   });
 
+  describe('while detached from parent window', () => {
+    beforeEach(() => {
+      global.window.parent = {
+        ...global.window.parent,
+        get __STORYBOOK_ADDON_INTERACTIONS_INSTRUMENTER_STATE__() {
+          throw new Error('Blocked');
+        },
+        set __STORYBOOK_ADDON_INTERACTIONS_INSTRUMENTER_STATE__(_: unknown) {},
```
Comment (ndelangen) [inline code/core/src/instrumenter/instrumenter.test.ts:740]: Long term, would be great to stop having to do this somehow.

Accessing `global.window.parent` should never be done.
Surely this can be done using the channel?

Till then this looks like an improvement to me.

**Review by ndelangen — APPROVED** [review]
