### PR TITLE
Svelte: Fixes component name in docgen-loader

### LINKED ISSUE #13742: Unable to import Svelte files that doesn't start with capital letter
**Describe the bug**
Unable to import Svelte files that doesn't start with capital letter, e.g. `header.svelte`, `_header.svelte`. Webpack compiles fine, but in the browser console, it reports `Unexpected error while loading ./stories/Header.stories.js: ReferenceError: _header is not defined`.

**To Reproduce**
Repo: https://github.com/bluwy/storybook-svelte-import-repro

1. Clone repo
2. `npm install`
3. `npm run storybook`
4. Go to http://localhost:6006 (Storybook page) and open devtools console

**Expected behavior**
Able to import Svelte files regardless of casing.

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
```
Environment Info:

  System:
    OS: Linux 5.8 Ubuntu 20.10 (Groovy Gorilla)
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Node: 12.19.0 - ~/.nvm/versions/node/v12.19.0/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.19.0/bin/npm
  Browsers:
    Firefox: 84.0.2
  npmPackages:
    @storybook/addon-actions: ^6.1.15 => 6.1.15 
    @storybook/addon-essentials: ^6.1.15 => 6.1.15 
    @storybook/addon-links: ^6.1.15 => 6.1.15 
    @storybook/svelte: ^6.1.15 => 6.1.15 
```

**Additional context**
This works in v6.1.12, and but fails in v6.1.14 onwards (repo is using v6.1.15 but I've also tested in v6.1.14). 
https://github.com/storybookjs/storybook/pull/13466 seems to be causing the issue since it's introduced in v6.1.14.

### PR DESCRIPTION
**Pull request by j3rem1e**
Issue: #13742

## What I did

The Svelte component name was not correctly guessed for unusual files names.
I use now the function from svelte/compiler which generates the component name.
However, this function is not exported by Svelte, so I had to duplicate it in the loader.

## How to test

- Is this testable with Jest or Chromatic screenshots? No
- Does this need a new example in the kitchen sink apps? No
- Does this need an update to the documentation? No

### CODE REVIEW

File: addons/docs/src/frameworks/svelte/svelte-docgen-loader.ts [hunk 1]
```diff
@@ -1,7 +1,36 @@
 import svelteDoc from 'sveltedoc-parser';
-
 import * as path from 'path';
 
+// From svelte/compiler/compile/utils but not exported
```
Comment (phated) [inline addons/docs/src/frameworks/svelte/svelte-docgen-loader.ts:4]: Let's do this:
```suggestion
// From https://github.com/sveltejs/svelte/blob/8db3e8d0297e052556f0b6dde310ef6e197b8d18/src/compiler/compile/utils/get_name_from_filename.ts
// Copied because it is not exported from the compiler
```

File: addons/docs/src/frameworks/svelte/svelte-docgen-loader.ts [hunk 2]
```diff
@@ -26,11 +55,10 @@ export default async function svelteDocgen(source: string) {
     // populate filename in docgen
     componentDoc.name = path.basename(file);
 
-    const componentName = path.parse(resource).name;
-
+    const componentName = get_name_from_filename(resource);
     docgen = `
-    ${componentName}.__docgen = ${JSON.stringify(componentDoc)};
-  `;
+${componentName}.__docgen = ${JSON.stringify(componentDoc)};
```
Comment (phated) [inline addons/docs/src/frameworks/svelte/svelte-docgen-loader.ts:60]: Maybe use `ts-dedent` here if the indentation matters instead of manually dedenting in this code.

File: addons/docs/src/frameworks/svelte/svelte-docgen-loader.ts [hunk 3]
```diff
@@ -1,7 +1,36 @@
 import svelteDoc from 'sveltedoc-parser';
-
 import * as path from 'path';
 
+// From svelte/compiler/compile/utils but not exported
+function get_name_from_filename(filename: string) {
```
Comment (phated) [inline addons/docs/src/frameworks/svelte/svelte-docgen-loader.ts:5]: Can you change this to Storybook's camelCase pattern?

**Review by phated — CHANGES_REQUESTED** [review]
Looking good. Just a few things.

**Comment by j3rem1e** [comment]
@phated I have updated my PR with your remarks, thanks !

**Review by phated — APPROVED** [review]
Awesome! Thanks!

**Review by shilman — APPROVED** [review]
😻
