### PR TITLE
Indexer: Do not create autodocs entries unless addon-docs installed

### LINKED ISSUE #31326: [Bug]: minimal storybook install broken with autodocs
### Describe the bug

When I install storybook without docs, It still adds the `autodocs` tag to the button story. This causes the docs entry to render in the sidebar (which is not the case in 8.6!) And then when I navigate to the docs page, it crashes with an error in the browser console. 

```sh
Uncaught (in promise) TypeError: i.renderer is not a function
```

### Reproduction link

n/a

### Reproduction steps

_No response_

### System

```bash
any
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ndelangen**
Closes https://github.com/storybookjs/storybook/issues/31326

## What I did

This pull request includes updates to streamline the handling of documentation options and improve type definitions in the codebase. The most significant changes involve refactoring the `docs` preset logic, enhancing type safety, and adding conditional checks for autodocs.

### Improvements to documentation handling:

* Refactored the `docs` preset in `code/addons/docs/src/preset.ts` to use the `PresetProperty<'docs'>` type and added support for passing `docsMode` from `CLIOptions`. This ensures better type safety and flexibility in handling documentation options.
* Removed the redundant `docs` export from `code/core/src/core-server/presets/common-preset.ts`, consolidating the logic into the updated implementation in `preset.ts`.

### Type definition enhancements:

* Updated imports in `code/addons/docs/src/preset.ts` to include additional types like `CLIOptions` and `StorybookConfigRaw`, ensuring more precise type usage throughout the file.

### Conditional autodocs generation:

* Modified the `StoryIndexGenerator` in `code/core/src/core-server/utils/StoryIndexGenerator.ts` to only create documentation entries when autodocs are enabled and the `docs` option is defined. This adds a safeguard against unintended behavior.

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This pull request has been released as version `0.0.0-pr-31331-sha-87ed948b`. Try it out in a new sandbox by running `npx storybook@0.0.0-pr-31331-sha-87ed948b sandbox` or in an existing project with `npx storybook@0.0.0-pr-31331-sha-87ed948b upgrade`.
<details>
<summary>More information</summary>

| | |
| --- | --- |
| **Published version** | [`0.0.0-pr-31331-sha-87ed948b`](https://npmjs.com/package/storybook/v/0.0.0-pr-31331-sha-87ed948b) |
| **Triggered by** | @shilman |
| **Repository** | [storybookjs/storybook](https://github.com/storybookjs/storybook) |
| **Branch** | [`norbert/docs-preset-property-indexer-fix`](https://github.com/storybookjs/storybook/tree/norbert/docs-preset-property-indexer-fix) |
| **Commit** | [`87ed948b`](https://github.com/storybookjs/storybook/commit/87ed948b6e00bb75f8780bf352d9a449493651ea) |
| **Datetime** | Fri May  2 07:01:25 UTC 2025 (`1746169286`) |
| **Workflow run** | [14790433123](https://github.com/storybookjs/storybook/actions/runs/14790433123) |

To request a new release of this pull request, mention the `@storybookjs/core` team.

_core team members can create a new canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=31331`_
</details>

## Greptile Summary

This PR fixes a bug where Storybook was creating documentation entries even when the addon-docs package wasn't installed, leading to runtime errors.

- Modified `StoryIndexGenerator.ts` to only create docs entries when both autodocs tag and docs option are present
- Removed redundant `docs` export from `common-preset.ts` to consolidate logic in addon-docs package
- Updated `preset.ts` to handle `docsMode` conditionally based on both `docsOptions` and CLI settings
- Fixed issue where minimal Storybook installations were incorrectly showing docs entries in sidebar

### CODE REVIEW

File: code/addons/docs/src/preset.ts [hunk 1]
```diff
@@ -129,12 +134,15 @@ async function webpack(
...
-const docs = (docsOptions: DocsOptions) => {
-  return {
-    ...docsOptions,
+const docs: PresetProperty<'docs'> = (docsOptions, { docs: docsMode }: CLIOptions) => {
+  const result: StorybookConfigRaw['docs'] = {
     defaultName: 'Docs',
-    autodocs: 'tag',
   };
+
+  if (docsOptions && docsMode) {
```
Comment (shilman) [inline code/addons/docs/src/preset.ts:142]: Why do we need this?

**Review by shilman — COMMENTED** [review]
Looks good to me, but I don't understand how docsMode  relates to anything.

File: code/addons/docs/src/preset.ts (hunk 1 above)
Comment (ndelangen) [reply code/addons/docs/src/preset.ts:142]: That was already there, I just refactored it.

The big difference is that now I detect addon-docs, by the presence of options.docs, which used to be set by common-preset.

By moving it to addon-docs itself, now `options.docs` becomes `undefined` when `addon-docs` is NOTv set up.

**Comment by ndelangen** [comment]
I tested this locally, and it works now!
@shilman please review?

**Review by shilman — APPROVED** [review]
