### PR TITLE
Addon-docs: Resolve `mdx-react-shim` & `@storybook/global` correctly

### LINKED ISSUE #23217: [Bug]: Module not found: Error: Can't resolve `@storybook/addon-docs/mdx-react-shim`
### Describe the bug

When processing an `.mdx` file in my repo, storybook produces the following error:

```
ERR! => Failed to build the preview
ERR! Module not found: Error: Can't resolve '@storybook/addon-essentials/docs/mdx-react-shim' in '/tmp/test/packages/a/src/Foo'
ERR! ModuleNotFoundError: Module not found: Error: Can't resolve '@storybook/addon-essentials/docs/mdx-react-shim' in '/tmp/test/packages/a/src/Foo'
```

This is similar to #21716, but the solutions there either do not work or do not seem very satisfactory to me.

### To Reproduce

1. Extract [test.zip](https://github.com/storybookjs/storybook/files/11873776/test.zip)
2. In that repo, using pnpm 8, run `pnpm install && pnpm --dir=packages/storybook run build`

### System

```shell
Environment Info:

  System:
    OS: Linux 6.3 Debian GNU/Linux trixie/sid
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  Binaries:
    Node: 18.13.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.2.0 - /usr/bin/npm

Also of note

    pnpm: 8.6.3 - /usr/local/bin/pnpm
```

### Additional context

The problem in the test repo seems to be at https://github.com/storybookjs/storybook/blob/f57e67f302865930f1bca01a977d0624ea663f19/code/addons/essentials/src/docs/preset.ts#L6 where it assumes that the code passed that option will have `@storybook/addon-essentials` available, which may not be the case in pnpm with hoisting disabled or in yarn when using PnP. Passing it through `require.resolve()` (or something similar to get an absolute path for `@storybook/addon-essentials/docs/mdx-react-shim`) should work there.

If `@storybook/addon-docs` is being used instead, code at https://github.com/storybookjs/storybook/blob/f57e67f302865930f1bca01a977d0624ea663f19/code/addons/docs/src/preset.ts#L59 makes a similar assumption, and a similar solution should work there.

I also see code in `@storybook/builder-vite` at https://github.com/storybookjs/storybook/blob/f57e67f302865930f1bca01a977d0624ea663f19/code/builders/builder-vite/src/plugins/mdx-plugin.ts#L36 that assumes that `@storybook/addon-docs` will be available when the option is being resolved. In this case a simple `require.resolve()` won't always work since there is no dependency or peer dependency of `@storybook/builder-vite` on `@storybook/addon-docs` to make it available to it.

In light of the above, here are some unsatisfactory workarounds for the problem:

* Re-enable pnpm's indirect-dep fallback hoisting, which exists to sometimes work around broken deps like this.
* Add an otherwise-unnecessary dep on `@storybook/addon-essentials` or `@storybook/addon-docs` (depending on what exactly is in `main.cjs`) to either the root `package.json` or to `projects/a/package.json` so the package will be available in the context where the option is being resolved.
* Add the following additional addon in `.storybook/main.cjs` to override the problematic option with a usable value:
   ```
        {
            name: '@storybook/addon-docs',
            options: {
                mdxPluginOptions: {
                    mdxCompileOptions: {
                        providerImportSource: require.resolve( '@storybook/addon-docs/mdx-react-shim' ),
                    },
                },
            },
        },
   ```
* Use `NODE_PATH` when running storybook to have it always search `packages/storybook/node_modules/` for dependencies in addition to the normal locations.

### PR DESCRIPTION
**Pull request by ndelangen**
Closes #23217

## What I did

I added a `require.resolve`, which should cause the issue to no longer happen.

When manually testing I found that it was also failing to load `@storybook/global`.
So I found a solution for that too.

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

1. run `yarn task --task run-registry --no-link`
2. wait for it to have the local registry running successfully
3. unzip the repro
4. navigate to the unzipped directory
5. change the pnpm config to use the local registry by making a change to the `.npmrc`-file: 
    ```diff
    + registry=http://localhost:6001/
    ```
6. prune the pnpm store cache (`pnpm store prune`)
7. remove `node_modules` (there are also 2 in the packages)
8. run the install (`pnpm install`)
9. navigate to the `./packages/storybook` directory
10. Run `yarn build`
11. Expect it to work.

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [x] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [x] Make sure this PR contains **one** of the labels below:

### 🦋 Canary release

This pull request has been released as version [`0.0.0-pr-23941-sha-8f1ed079`](https://npmjs.com/package/@storybook/cli/v/0.0.0-pr-23941-sha-8f1ed079). Install it by pinning all your Storybook dependencies to that version.
<details>
<summary>More information</summary>

| | |
| --- | --- |
| **Published version** | [`0.0.0-pr-23941-sha-8f1ed079`](https://npmjs.com/package/@storybook/cli/v/0.0.0-pr-23941-sha-8f1ed079) |
| **Triggered by** | @ndelangen |
| **Repository** | [storybookjs/storybook](https://github.com/storybookjs/storybook) |
| **Branch** | [`norbert/fix-23217`](https://github.com/storybookjs/storybook/tree/norbert/fix-23217) |
| **Commit** | [`8f1ed079`](https://github.com/storybookjs/storybook/commit/8f1ed079010e8f8a8c7f4b7c088d94e6246ba561) |
| **Datetime** | Fri Aug 25 12:43:08 UTC 2023 (`1692967388`) |
| **Workflow run** | [5976017700](https://github.com/storybookjs/storybook/actions/runs/5976017700) |

To request a new release of this pull request, mention the `@storybookjs/core` team.

_core team members can create a new canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=23941`_
</details>

### CODE REVIEW

**Comment by IanVS** [comment]
Note the user in the issue report is using pnpm.  Could the problem be that we are not exposing the shim correctly?  Also, by using `require.resolve`, does that prevent us from shipping ESM?

**Comment by ndelangen** [comment]
@IanVS that's a great comment, I made a change so it should be able to get the `.mjs`-file.

**Comment by IanVS** [comment]
Oh, I thought I was a core team member, so I tried to build a canary to test this out in my own pnpm project, but I don't have permissions.  @ndelangen maybe you can trigger a canary?

File: code/addons/essentials/src/docs/preset.ts [hunk 1]
```diff
@@ -1,8 +1,13 @@
...
+
+// eslint-disable-next-line import/export
 export * from '@storybook/addon-docs/dist/preset';
 
 export const mdxLoaderOptions = async (config: any) => {
   // eslint-disable-next-line no-param-reassign
-  config.mdxCompileOptions.providerImportSource = '@storybook/addon-essentials/docs/mdx-react-shim';
+  config.mdxCompileOptions.providerImportSource = join(
+    dirname(require.resolve('@storybook/addon-docs/package.json')),
+    '/dist/shims/mdx-react-shim'
```
Comment (IanVS) [inline code/addons/essentials/src/docs/preset.ts:10]: Why do we need to use `/dist/shims` here, when the [exports](https://github.com/storybookjs/storybook/blob/f83212b5ae347caa0893a37e1201c70dcd531387/code/addons/docs/package.json#L62) of `addon-docs` includes `mdx-react-shim` ?  I thought the way we normally handle bundlers that don't support `exports` was by putting a file at the root which re-exported from `dist`.  That feels like a cleaner solution to me, rather than sprinkling `dist` throughout our source.

**Review by IanVS — APPROVED** [review]
Thanks @ndelangen.  I tested out the canary in both my own non-monorepo pnpm react-vite storybook project (which was not failing previously), as well as in the monorepo pnpm react-webpack reproduction provided in the issue, both of which worked fine.  

I think eventually, if we want to support true node.js ESM, we'll need to start using `createRequire`, since our .mjs files that are generated right now will throw errors if `require` is not available, but that can be a matter for another day.

File: code/addons/essentials/src/docs/preset.ts (hunk 1 above)
Comment (ndelangen) [reply code/addons/essentials/src/docs/preset.ts:10]: @IanVS right, I'd definitely not want users to import directly from `dist`, because what's in `dist` is internal for us.
But that's also the reaosn why I think here it's OK to use:
This is all contained in the monorepo, so I'm less afraid this will break.

Sure I could direct to a root file, and then the root file directs to dist.. but I'd rather have less hoops and less files that need to be there for obscure reasons.

If this works, and therefore 1 less reason for having an root files that's 👍 for me.

I'm hoping that long term we won't have any root files anymore.. but that's likely going to be around the same time when:
> we want to support true node.js ESM, we'll need to start using createRequire, since our .mjs files that are generated right now will throw errors if require is not available, but that can be a matter for another day.
