### PR TITLE
Vue3: Add support for  Global Apps install

### LINKED ISSUE #23844: [Bug]: setup function imported from '@storybook/vue3' is not working
### Describe the bug

Given that I have an import statement in the **preview.js** file as follows:

```
import { setup } from '@storybook/vue3';
```

When I call the setup function as follows:
```
setup((app) => {
  console.log('Here comes the app:', app);
});
```

Then nothing happens. Seems like the function given to the setup as an argument is not being executed.

### To Reproduce

_No response_

### System

```shell
Environment Info:

  System:
    OS: macOS 13.4.1
    CPU: (12) x64 Apple M2 Pro
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chrome: 115.0.5790.170
    Edge: 114.0.1823.67
    Firefox: 116.0.2
    Safari: 16.5.2
  npmPackages:
    @storybook/addon-a11y: ^7.3.0 => 7.3.0 
    @storybook/addon-actions: ^7.3.0 => 7.3.0 
    @storybook/addon-console: ^2.0.0 => 2.0.0 
    @storybook/addon-essentials: ^7.3.0 => 7.3.0 
    @storybook/addon-interactions: ^7.3.0 => 7.3.0 
    @storybook/addon-links: ^7.3.0 => 7.3.0 
    @storybook/addon-styling: ^1.3.6 => 1.3.6 
    @storybook/addons: ^7.3.0 => 7.3.0 
    @storybook/blocks: ^7.3.0 => 7.3.0 
    @storybook/mdx1-csf: ^1.0.0 => 1.0.0 
    @storybook/testing-library: ^0.2.0 => 0.2.0 
    @storybook/theming: ^7.3.0 => 7.3.0 
    @storybook/vue3: ^7.3.0 => 7.3.0 
    @storybook/vue3-webpack5: ^7.3.0 => 7.3.0
```

### Additional context

I noticed this today in v7.2.3 and shortly after I saw that v7.3.0 is released. So I updated to it to see if this is fixed, but it's still not working.

### PR DESCRIPTION
**Pull request by chakAs3**
Closes #23844

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "build", "documentation", "maintenance", "dependencies", "other"]`

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

File: code/renderers/vue3/src/globals.ts [hunk 1]
```diff
@@ -3,3 +3,5 @@ import { global } from '@storybook/global';
 const { window: globalWindow } = global;
 
 globalWindow.STORYBOOK_ENV = 'vue3';
+globalWindow.STORYBOOK_VUE_GLOBAL_PLUGINS ||= [];
+globalWindow.STORYBOOK_VUE_GLOBAL_MIXINS ||= [];
```
Comment (kasperpeulen) [inline code/renderers/vue3/src/globals.ts:7]: I don't see those 2 being used anywhere.

File: code/renderers/vue3/src/index.ts [hunk 2]
```diff
@@ -6,4 +6,10 @@ export * from './public-api';
 export * from './public-types';
 
 // optimization: stop HMR propagation in webpack
-if (typeof module !== 'undefined') module?.hot?.decline();
+try {
+  if (module?.hot?.decline) {
+    module.hot.decline();
+  }
+} catch (e) {
+  console.log('  e:', e);
```
Comment (kasperpeulen) [inline code/renderers/vue3/src/index.ts:14]: Do we need to log this?

File: code/renderers/vue3/src/render.ts [hunk 3]
```diff
@@ -145,3 +149,9 @@ function teardown(
   storybookApp?.unmount();
   if (map.has(canvasElement)) map.delete(canvasElement);
 }
+
+async function installGlobalPlugins(app: App<any>, storyContext: StoryContext<VueRenderer>) {
+  if (window.APPLY_PLUGINS_FUNC) {
+    await window.APPLY_PLUGINS_FUNC(app, storyContext);
```
Comment (kasperpeulen) [inline code/renderers/vue3/src/render.ts:155]: What is the difference with the setup function? Should this function be set by the user?

**Review by kasperpeulen — COMMENTED** [review]
Can you fill in "What I did" and "How to test"? @chakAs3

File: code/renderers/vue3/src/globals.ts (hunk 1 above)
Comment (chakAs3) [reply code/renderers/vue3/src/globals.ts:7]: not yet used I planned you used them in the begining but i'm still thinking of the right implementation

File: code/renderers/vue3/src/index.ts (hunk 2 above)
Comment (chakAs3) [reply code/renderers/vue3/src/index.ts:14]: not need to log but we need to wrap it in try catch. , it will break in vite ( it is webpack specific )

File: code/renderers/vue3/src/render.ts (hunk 3 above)
Comment (chakAs3) [reply code/renderers/vue3/src/render.ts:155]: using setup is not safe, in case your package manager allows 2 versions of the same package, @storybook/vue3 can't be a singleton,  so calling setup. seems not working for users 
using window. APPLY_PLUGINS_FUNC  will insure the singleton. 
it should be. awaited as well in case. registering the plugin is async

File: code/renderers/vue3/src/index.ts (hunk 2 above)
Comment (kasperpeulen) [reply code/renderers/vue3/src/index.ts]: Okay, let's remove the console.log then

File: code/renderers/vue3/src/render.ts (hunk 3 above)
Comment (kasperpeulen) [reply code/renderers/vue3/src/render.ts:155]: I think we can also solve this by putting this on the window:
https://github.com/storybookjs/storybook/blob/936602d1bba26788298d3aa839e38ddb248c4fbc/code/renderers/vue3/src/render.ts#L20

I think it is better have one API.

Comment (chakAs3) [reply code/renderers/vue3/src/render.ts:155]: yes exactly i'm working on that idea

File: code/renderers/vue3/src/index.ts [hunk 4]
```diff
@@ -6,4 +6,11 @@ export * from './public-api';
 export * from './public-types';
 
 // optimization: stop HMR propagation in webpack
-if (typeof module !== 'undefined') module?.hot?.decline();
+try {
+  if (module?.hot?.decline) {
+    module.hot.decline();
+  }
```
Comment (kasperpeulen) [inline code/renderers/vue3/src/index.ts:12]: You still need the `typeof module !== 'undefined'` check right?

Maybe:
```ts
if (typeof module !== 'undefined') module?.hot?.decline?.();
```

File: code/renderers/vue3/src/index.ts [hunk 5]
```diff
@@ -6,4 +6,11 @@ export * from './public-api';
...
+} catch (e) {
+  /* do nothing */
+  console.log(e);
```
Comment (kasperpeulen) [inline code/renderers/vue3/src/index.ts:15]: I would ignore it, we only pollute the console for vite users with this.

File: code/renderers/vue3/src/render.ts [hunk 6]
```diff
@@ -16,18 +17,17 @@ export const render: ArgsStoryFn<VueRenderer> = (props, context) => {
...
-const setupFunctions = new Set<(app: App, storyContext?: StoryContext<VueRenderer>) => void>();
-/** add a setup function to set that will be call when story is created a d
- *
- * @param fn
- */
-export const setup = (fn: (app: App, storyContext?: StoryContext<VueRenderer>) => void) => {
-  setupFunctions.add(fn);
+export const setup = (fn: (app: App, storyContext?: StoryContext<VueRenderer>) => unknown) => {
+  globalThis.PLUGINS_SETUP_FUNCTIONS ??= new Set();
+  globalThis.PLUGINS_SETUP_FUNCTIONS.add(fn);
```
Comment (kasperpeulen) [inline code/renderers/vue3/src/render.ts:22]: @ndelangen I thought you mentioned at some point that we prefer `@storybook/global` over `globalThis` but I don't know the reasons anymore.

File: code/renderers/vue3/src/render.ts [hunk 7]
```diff
@@ -16,18 +17,17 @@ export const render: ArgsStoryFn<VueRenderer> = (props, context) => {
...
 };
 
-const runSetupFunctions = (app: App, storyContext: StoryContext<VueRenderer>) => {
-  setupFunctions.forEach((fn) => fn(app, storyContext));
+const runSetupFunctions = async (
+  app: App,
+  storyContext: StoryContext<VueRenderer>
+): Promise<any> => {
+  if (globalThis && globalThis.PLUGINS_SETUP_FUNCTIONS)
+    await Promise.all([...globalThis.PLUGINS_SETUP_FUNCTIONS].map((fn) => fn(app, storyContext)));
```
Comment (kasperpeulen) [inline code/renderers/vue3/src/render.ts:30]: Maybe `Promise.allSettled` as I think we don't want to short-circuit here?

File: code/renderers/vue3/src/render.ts [hunk 8]
```diff
@@ -16,18 +17,17 @@ export const render: ArgsStoryFn<VueRenderer> = (props, context) => {
...
+  globalThis.PLUGINS_SETUP_FUNCTIONS ??= new Set();
+  globalThis.PLUGINS_SETUP_FUNCTIONS.add(fn);
 };
 
-const runSetupFunctions = (app: App, storyContext: StoryContext<VueRenderer>) => {
-  setupFunctions.forEach((fn) => fn(app, storyContext));
+const runSetupFunctions = async (
+  app: App,
+  storyContext: StoryContext<VueRenderer>
+): Promise<any> => {
```
Comment (kasperpeulen) [inline code/renderers/vue3/src/render.ts:28]: `Promise<void>`

**Review by kasperpeulen — CHANGES_REQUESTED** [review]
Looks good! Some small stuff.

File: code/renderers/vue3/src/render.ts (hunk 6 above)
Comment (chakAs3) [reply code/renderers/vue3/src/render.ts:22]: as i know globalThis was introduced to give access to global scope regardless the system Node/Browser,  it is consistency and standard  rather than using window / global

Comment (chakAs3) [reply code/renderers/vue3/src/render.ts:22]: and that  what @storybook/global  provides the global scope so if we do 
`declare var STORYBOOK_ENV:'type'` in `type.d.ts` file
will be safely available on globalThis  as global module

**Review by kasperpeulen — APPROVED** [review]
LGTM!
