### PR TITLE
UI: Fix React error 300 on some addons

### LINKED ISSUE #33352: [Bug]: Storybook 10 broken on reload or direct access to pages with Path parameter
### Describe the bug

Since upgrading from Storybook 9.x to the latest 10.1.18, when I attempt to go directly to a story or reload a page with the path parameter, it fails to load with the following console errors:

2 globals-runtime.js:3326 Error: Minified React error #300; visit https://reactjs.org/docs/error-decoder.html?invariant=300 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Nh (globals-runtime.js:2938:110)
    at cj (globals-runtime.js:3423:48)
    at Vk (globals-runtime.js:5237:97)
    at Uk (globals-runtime.js:4974:16)
    at Tk (globals-runtime.js:4968:28)
    at Ik (globals-runtime.js:4958:11)
    at Nk (globals-runtime.js:4748:87)
    at Gk (globals-runtime.js:4701:65)
    at J (globals-runtime.js:344:22)
    at MessagePort.R2 (globals-runtime.js:369:16)

Li @ globals-runtime.js:3326Understand this error
globals-runtime.js:5035 Uncaught Error: Minified React error #300; visit https://reactjs.org/docs/error-decoder.html?invariant=300 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Nh (globals-runtime.js:2938:110)
    at cj (globals-runtime.js:3423:48)
    at Vk (globals-runtime.js:5237:97)
    at Uk (globals-runtime.js:4974:16)
    at Tk (globals-runtime.js:4968:28)
    at Ik (globals-runtime.js:4958:11)
    at Nk (globals-runtime.js:4748:87)
    at Gk (globals-runtime.js:4701:65)
    at J (globals-runtime.js:344:22)
    at MessagePort.R2 (globals-runtime.js:369:16)Understand this error

globals-runtime.js:5814  manager  received storybook/html/codeUpdate but was unable to determine the source of the event
error @ globals-runtime.js:5814Understand this error

globals-runtime.js:5814  manager  received storybook/instrumenter/sync but was unable to determine the source of the event

You can see this in action on this public Storybook instance: https://us-cbp.github.io/design-system/

It happens on any of the main stories (tsx files), but doesn't happen on my .mdx files like the component API Docs or Specifications or a number at the top of the left nav.

This is the web components/vite framework.

Code can be found here: https://github.com/US-CBP/design-system/tree/develop/packages/web-components

### Reproduction link

https://us-cbp.github.io/design-system/?path=/story/introduction--introduction

### Reproduction steps

Navigate to any story with a "path" URL parameter
Reload the page
It fails - check the browser console for errors.

### System

```bash
Storybook Environment Info:
│

│  System:
│  OS: Windows 11 10.0.26200
│  CPU: (24) x64 13th Gen Intel(R) Core(TM) i7-13700F
│  Binaries:
│  Node: 24.8.0 - C:\Program Files\nodejs\node.EXE
│  npm: 11.6.0 - C:\Program Files\nodejs\npm.CMD <----- active
│  Browsers:
│  Chrome: 143.0.7499.41
│  Edge: Chromium (140.0.3485.54)
│  Firefox: 145.0 - C:\Program Files\Mozilla Firefox\firefox.exe
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Sidnioulz**
Closes #33352

## What I did

Accounted for React elements passed to the `render` prop for addon tools. If the prop is not a function, I'm now using `cloneElement` instead of directly rendering it as a function. This fixes the bug as far as I can tell.

#### The changes in this PR are covered in the following automated tests:

ø

#### Manual testing

> [!CAUTION]
> I could not repro on our own SB instance so I ended up having to code a fix in the built SB manager in the repro repo's `node_modules`.

1. Fork https://github.com/US-CBP/design-system/tree/develop/packages/web-components
2. Run the SB instance in `packages/web-components`
3. Go to any page, press F5 and notice the crash
2. Replace the Storybook instance it contains with the code on this branch
3. Rinse and repeat, it should no longer crash

### Documentation

ø

## Checklist for Maintainers

- [x] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [x] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This pull request has been released as version `0.0.0-pr-33381-sha-f3410369`. Try it out in a new sandbox by running `npx storybook@0.0.0-pr-33381-sha-f3410369 sandbox` or in an existing project with `npx storybook@0.0.0-pr-33381-sha-f3410369 upgrade`.
<details>
<summary>More information</summary>

| | |
| --- | --- |
| **Published version** | [`0.0.0-pr-33381-sha-f3410369`](https://npmjs.com/package/storybook/v/0.0.0-pr-33381-sha-f3410369) |
| **Triggered by** | @yannbf |
| **Repository** | [storybookjs/storybook](https://github.com/storybookjs/storybook) |
| **Branch** | [`sidnioulz/issue-33352`](https://github.com/storybookjs/storybook/tree/sidnioulz/issue-33352) |
| **Commit** | [`f3410369`](https://github.com/storybookjs/storybook/commit/f3410369066852d20a86d93248b750544c9dea62) |
| **Datetime** | Wed Dec 17 11:48:20 UTC 2025 (`1765972100`) |
| **Workflow run** | [20301772924](https://github.com/storybookjs/storybook/actions/runs/20301772924) |

To request a new release of this pull request, mention the `@storybookjs/core` team.

_core team members can create a new canary release [here](https://github.com/storybookjs/storybook/actions/workflows/publish.yml) or locally with `gh workflow run --repo storybookjs/storybook publish.yml --field pr=33381`_
</details>

## Summary by CodeRabbit

* **Bug Fixes**
  * Fixed panel addon rendering so the active state is applied consistently across different render types.
  * Improved addon rendering support to handle both element and function renderers reliably, preventing potential hook-related issues.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Review by ghengeveld — APPROVED** [review]
I would've used a ternary return statement, but generally LGTM.

**Comment by Sidnioulz** [comment]
> I would've used a ternary return statement, but generally LGTM.

Generally agreed. Here, this allowed me to scope down the ts-expect-error to the exact problematic code, so I don't risk shadowing future errors elsewhere.

**Comment by Sidnioulz** [comment]
> I would've used a ternary return statement, but generally LGTM.

Feel free to merge this whenever you like, @ghengeveld  :)

File: code/core/src/manager/components/panel/Panel.tsx [hunk 1]
```diff
@@ -67,11 +67,22 @@ const Section = styled.section({
   flexDirection: 'column',
 });
 
+// Ensures we don't cause difficult-to-debug hooks violations
+// when addon authors pass a React element type instead of a function.
+function renderChild(renderProp: Addon_BaseType['render']) {
+  if (isValidElement(renderProp)) {
```
Comment (mrginglymus) [inline code/core/src/manager/components/panel/Panel.tsx]: Is this code path even possible? The types certainly seem to forbid it...

File: code/core/src/manager/components/panel/Panel.tsx [hunk 2]
```diff
@@ -67,11 +67,22 @@ const Section = styled.section({
...
+    /** @ts-expect-error We must pass `active` in case addon authors use AddonPanel. */
+    return cloneElement(renderProp, { active: true });
+  }
+
+  return createElement(renderProp, { active: true });
```
Comment (mrginglymus) [inline code/core/src/manager/components/panel/Panel.tsx]: Something about explicitly calling `createElement` makes me nervous.

Something like:
```ts
function renderChild(RenderProp...) {
  return <RenderProp active />
}
```

should work out the same, but use whatever `createElement` the build transform wants to use.

File: code/core/src/manager/components/panel/Panel.tsx (hunk 1 above)
Comment (Sidnioulz) [reply code/core/src/manager/components/panel/Panel.tsx]: The type is irrelevant if something else is being passed by callees, isn't it?

Comment (mrginglymus) [reply code/core/src/manager/components/panel/Panel.tsx]: They're supposed to pass a ReactElementConstructor - if they're passing a react element instance, then the exisitng code path would explode already.

Comment (Sidnioulz) [reply code/core/src/manager/components/panel/Panel.tsx]: I thought this could be found (esp. in local addons) so long as you don't use SB hooks, but indeed, it causes other React hook errors even with this patch. So I'm gonna remove that bit.
