### PR TITLE
Next.js: Handle v14 compatibility for draftMode import

### LINKED ISSUE #32950: [Bug]: Getting error building storybook in v10 with nextjs
### Describe the bug

I have a project that explicitly installs `next@14` rather than just implicitly installing it via `@storybook/next`
When I build the storybook I get the following error:

```
=> Failed to build the preview
SB_BUILDER-WEBPACK5_0002 (WebpackInvocationError): Module not found: Error: Can't resolve 'next/dist/server/request/draft-mode' in './node_modules/@storybook/nextjs/dist/export-mocks/headers'
    at file://./node_modules/@storybook/builder-webpack5/dist/index.js:1114:35
    at ./node_modules/webpack/lib/HookWebpackError.js:66:2
    at Hook.eval [as callAsync] (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:31:10), <anonymous>:11:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (./node_modules/tapable/lib/Hook.js:21:14)
    at Cache.shutdown (./node_modules/webpack/lib/Cache.js:157:23)
    at ./node_modules/webpack/lib/Compiler.js:1407:15
    at Hook.eval [as callAsync] (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:31:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (./node_modules/tapable/lib/Hook.js:21:14)
    at Compiler.close (./node_modules/webpack/lib/Compiler.js:1400:23)
    at file://./node_modules/@storybook/builder-webpack5/dist/index.js:1114:18
    at finalCallback (./node_modules/webpack/lib/Compiler.js:519:32)
    at onCompiled (./node_modules/webpack/lib/Compiler.js:533:20)
    at ./node_modules/webpack/lib/Compiler.js:1355:21
    at eval (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:31:10), <anonymous>:32:1)
    at ./node_modules/webpack/lib/EntryPlugin.js:49:5
    at ./node_modules/webpack/lib/Compilation.js:2486:13
    at ./node_modules/webpack/lib/Compilation.js:2371:6
    at ./node_modules/webpack/lib/Compilation.js:2314:13
    at ./node_modules/webpack/lib/util/AsyncQueue.js:390:5
    at Hook.eval [as callAsync] (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:31:10), <anonymous>:15:1)
    at AsyncQueue._handleResult (./node_modules/webpack/lib/util/AsyncQueue.js:360:21)
    at ./node_modules/webpack/lib/util/AsyncQueue.js:343:11
    at onTransitiveTasksFinished (./node_modules/webpack/lib/Compilation.js:1702:20)
    at ./node_modules/webpack/lib/Compilation.js:1688:7
    at ./node_modules/webpack/lib/Compilation.js:2314:13
    at ./node_modules/webpack/lib/util/AsyncQueue.js:390:5
    at Hook.eval [as callAsync] (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:31:10), <anonymous>:15:1)
    at AsyncQueue._handleResult (./node_modules/webpack/lib/util/AsyncQueue.js:360:21)
    at ./node_modules/webpack/lib/util/AsyncQueue.js:343:11
    at onTransitiveTasksFinished (./node_modules/webpack/lib/Compilation.js:1702:20)
    at ./node_modules/webpack/lib/Compilation.js:1688:7
    at ./node_modules/webpack/lib/Compilation.js:2314:13
    at ./node_modules/webpack/lib/util/AsyncQueue.js:390:5
    at Hook.eval [as callAsync] (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:31:10), <anonymous>:15:1)
    at AsyncQueue._handleResult (./node_modules/webpack/lib/util/AsyncQueue.js:360:21)
    at ./node_modules/webpack/lib/util/AsyncQueue.js:343:11
    at onTransitiveTasksFinished (./node_modules/webpack/lib/Compilation.js:1702:20)
    at ./node_modules/webpack/lib/Compilation.js:1688:7
    at ./node_modules/webpack/lib/Compilation.js:2314:13
    at ./node_modules/webpack/lib/util/AsyncQueue.js:390:5
    at Hook.eval [as callAsync] (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:31:10), <anonymous>:15:1)
    at AsyncQueue._handleResult (./node_modules/webpack/lib/util/AsyncQueue.js:360:21)
    at ./node_modules/webpack/lib/util/AsyncQueue.js:343:11
    at onTransitiveTasksFinished (./node_modules/webpack/lib/Compilation.js:1702:20)
    at ./node_modules/webpack/lib/Compilation.js:1688:7
    at ./node_modules/webpack/lib/Compilation.js:2314:13
    at ./node_modules/webpack/lib/util/AsyncQueue.js:382:6
    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)
```

Digging into directory structure I see that there is not a `next/dist/server/request/draft-mode` in the installed `next@14`. According to the next [documentation](https://nextjs.org/docs/app/api-reference/functions/draft-mode) draft mode is in `next/headers`.  This [line](https://github.com/storybookjs/storybook/blob/9d1fc3ebe4665f2b7ff5b30135504282e1296d04/code/frameworks/nextjs/src/export-mocks/headers/index.ts#L1) is importing the offending, non-existant file in my installation:

Not sure why this is happening, but it is preventing my storybook 10 upgrade. 

My `main.ts` looks like:
```
import type { StorybookConfig } from 'storybook/internal/types';

const config: StorybookConfig = {
  stories: ['../src/__stories__/**/*.stories.tsx'],
  addons: ['@storybook/addon-a11y', '@storybook/addon-docs'],
  framework: '@storybook/nextjs',
};

module.exports = config;
```

According to a comment in the original [PR](https://github.com/storybookjs/storybook/commit/59df579fbc5861357b99eae6578c77694b218224), 
```
// This export won't exist in Next.js 14 but it's safe because we ignore it in Webpack when applicable
```
But it seems not to be in my case

### Reproduction link

TBD

### Reproduction steps

_No response_

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 26.0.1
    CPU: (12) arm64 Apple M2 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.21.0 - ~/.nvm/versions/node/v22.21.0/bin/node
    npm: 10.9.4 - ~/.nvm/versions/node/v22.21.0/bin/npm <----- active
    pnpm: 10.1.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 142.0.7444.60
    Safari: 26.0.1
  npmPackages:
    @storybook/addon-a11y: 10.0.4 => 10.0.4 
    @storybook/addon-docs: 10.0.4 => 10.0.4 
    @storybook/nextjs: 10.0.4 => 10.0.4 
    storybook: 10.0.4 => 10.0.4
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tanujbhaud**
## Summary

Fixes #32950 - Build errors when using Storybook v10 with Next.js 14

The issue occurred because `next/dist/server/request/draft-mode` doesn't exist in Next.js 14, causing build failures. While webpack aliases were configured to handle this version difference, the static top-level import was failing before webpack could apply the aliases.

## Changes

- Replaced static import with dynamic `require()` in try-catch block
- Added fallback to Next.js 14 location when the Next.js 15+ path doesn't exist
- Preserved existing webpack alias functionality for proper path resolution

## Technical Details

**Next.js 14**: `draftMode` is exported from `next/dist/client/components/headers`
**Next.js 15+**: `draftMode` is exported from `next/dist/server/request/draft-mode`

The webpack compatibility map already handles this via aliases, but we needed to defer the import to runtime to prevent build-time resolution errors.

## Test plan

- [ ] Verify builds succeed with Next.js 14
- [ ] Verify builds succeed with Next.js 15+
- [ ] Confirm webpack aliases still work correctly
- [ ] Test that draftMode mocking functionality is preserved

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved draft mode initialization to handle varying module locations and enhance compatibility across different environments through better fallback mechanisms.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: code/addons/vitest/src/updateVitestFile.ts [hunk 1]
```diff
@@ -11,7 +12,10 @@ export const loadTemplate = async (name: string, replacements: Record<string, st
     join(resolvePackageDir('@storybook/addon-vitest'), 'templates', name),
     'utf8'
   );
-  Object.entries(replacements).forEach(([key, value]) => (template = template.replace(key, value)));
+  // Normalize Windows paths (backslashes) to forward slashes for JavaScript string compatibility
+  Object.entries(replacements).forEach(
+    ([key, value]) => (template = template.replace(key, slash(value)))
+  );
```
Comment (valentinpalkovic) [inline code/addons/vitest/src/updateVitestFile.ts]: This change doesn't relate to the linked issue. Can you remove it and open a new PR that describes what you want to solve?

**Comment by tanujbhaud** [comment]
Fixed! I've removed the unrelated Windows paths commit and rebased the branch cleanly from `next`. The PR now only contains the Next.js 14 draftMode compatibility fix for issue #32950.

The Windows paths fix will remain in PR #33340 which addresses issue #31768 separately.

**Review by valentinpalkovic — APPROVED** [review]
