### PR TITLE
CLI: Fix add command for non monorepo deps

### LINKED ISSUE #25790: [Bug]: Running `npx storybook@next add package` on non-mono-repo deps fails
### Describe the bug

Running `npx storybook@next add <package>` on non-mono-repo addons fails sometimes, because the wrong version number is taken.

For more context:
https://github.com/storybookjs/storybook/discussions/25692#discussioncomment-8266587

### To Reproduce

https://github.com/storybookjs/storybook/discussions/25692#discussioncomment-8266587

### System

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by valentinpalkovic**
Closes https://github.com/storybookjs/storybook/issues/25790

## What I did

Running `npx storybook@next add <package>` on non-mono-repo addons sometimes failed because the wrong version number was taken. Now, the check to determine whether a package is a mono repo package or not was adjusted to take the `versions.ts` file into account.

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

1. Run a sandbox for template, e.g. `yarn task --task sandbox --start-from auto --template react-vite/default-ts`
2. Run `/path-to-storybook/code/lib/cli/bin/index.js add @storybook/addon-webpack5-compiler-babel`
3. The latest version of the addon should be installed

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This pull request has been released as version `0.0.0-pr-25791-sha-731531eb`. Try it out in a new sandbox by running `npx storybook@0.0.0-pr-25791-sha-731531eb sandbox` or in an existing project with `npx storybook@0.0.0-pr-25791-sha-731531eb upgrade`.
<details>
<summary>More information</summary>

| | |
| --- | --- |
| **Published version** | [`0.0.0-pr-25791-sha-731531eb`](https://npmjs.com/package/@storybook/cli/v/0.0.0-pr-25791-sha-731531eb) |
| **Triggered by** | @yannbf |
| **Repository** | [storybookjs/storybook](https://github.com/storybookjs/storybook) |
| **Branch** | [`valentin/fix-add-command-for-non-monorepo-deps`](https://github.com/storybookjs/storybook/tree/valentin/fix-add-command-for-non-monorepo-deps) |
| **Commit** | [`731531eb`](https://github.com/storybookjs/storybook/commit/731531ebcfe32e9a5a348a7b1ed633ad97a95055) |
| **Datetime** | Tue Jan 30 17:12:51 UTC 2024 (`1706634771`) |
| **Workflow run** | [7714884306](https://github.com/storybookjs/storybook/actions/runs/7714884306) |

To request a new release of this pull request, mention the `@storybookjs/core` team.

_core team members can create a new canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=25791`_
</details>

### CODE REVIEW

**Review by yannbf — APPROVED** [review]
LGTM! I triggered a canary, I think we should test it properly before merging

File: code/lib/core-common/src/js-package-manager/JsPackageManager.ts [hunk 1]
```diff
@@ -55,7 +55,10 @@ export abstract class JsPackageManager {
     basePath?: string
   ): Promise<PackageJson | null>;
 
-  public abstract getPackageVersion(packageName: string, basePath?: string): Promise<string | null>;
+  async getPackageVersion(packageName: string, basePath = this.cwd): Promise<string | null> {
```
Comment (valentinpalkovic) [inline code/lib/core-common/src/js-package-manager/JsPackageManager.ts:58]: @yannbf This function was indeed just used by the `add` command. I looked it up wrongly previously.

**Review by yannbf — APPROVED** [review]
