### PR TITLE
CLI: Fix open storybook in default browser

### LINKED ISSUE #15316: Storybook does not open in default browser
**Describe the bug**
My default browser is Firefox (if I type `open https://storybook.js.org/` in my console then it opens in Firefox. However when I run `npm run storybook` it opens in another browser I happen to have installed on my computer, called Google Chrome.

**To Reproduce**
Set Firefox as default Browser. In a Story book project, run `npm run storybook`

**System**
Environment Info:

  System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    npm: 6.14.11 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Edge: 91.0.864.54
    Firefox: 89.0.1
    Safari: 14.1.1

### PR DESCRIPTION
**Pull request by richorrichard**
Issue: #15316 

## What I did
Updated `open-in-browser.ts` to find the user's default browser, and attempt to honor that default browser (when default is Firefox or Safari) instead of automatically opening in a Chromium-based browser.  
- Included 2 new npm packages:
  - `x-default-browser` to detect the user's system default browser
  - `open` to handle cross-platform versions of Firefox

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

File: lib/core-server/src/utils/open-in-browser.ts [hunk 1]
```diff
@@ -1,15 +1,45 @@
...
+    if (res.isFirefox) {
+      // Handle firefox cross-browser using open's system-specific binary utility.
+      // See https://github.com/sindresorhus/open#openapps for more information.
+      try {
+        await open(address, {
+          app: {
+            name: 'firefox',
+          },
+        });
+      } catch (error) {
```
Comment (shilman) [inline lib/core-server/src/utils/open-in-browser.ts:18]: can we move the `try/catch` around the whole thing to remove duplicate code?

File: lib/core-server/src/utils/open-in-browser.ts [hunk 2]
```diff
@@ -1,15 +1,45 @@
...
+        logger.error(dedent`
+          Could not open ${address} inside a browser. If you're running this command inside a
+          docker container or on a CI, you need to pass the '--ci' flag to prevent opening a
+          browser by default.
+        `);
+      }
+    } else {
```
Comment (shilman) [inline lib/core-server/src/utils/open-in-browser.ts:25]: shouldn't the logic be switched here where we use `betterOpn` for chrome/chromium only, and then use `open` for everything else? my understanding of the original issue is that `betterOpn` always prefers chrome if it's available and that's what was annoying users.

**Review by shilman — COMMENTED** [review]
@richorrichard Thanks so much for taking this on! 🙏  A couple comments/questions:

File: lib/core-server/src/utils/open-in-browser.ts (hunk 1 above)
Comment (richorrichard) [reply lib/core-server/src/utils/open-in-browser.ts]: Good call - I adjusted in the following commit.

File: lib/core-server/src/utils/open-in-browser.ts (hunk 2 above)
Comment (richorrichard) [reply lib/core-server/src/utils/open-in-browser.ts]: This is also much simpler. I was originally turned off to this idea because of the way betterOpn triages versions of chrome. I updated to test for Chrome and checked it against every browser I could get my hands on for Mac and this approach works wonderfully, and it's much simpler to read. Thanks for the feedback and review!

**Review by shilman — APPROVED** [review]
Awesome -- thanks so much for the follow-up, this turned out great!

**Comment by richorrichard** [comment]
You're very welcome! I'm looking forward to moving on to my next contribution :) 

Last question - I see there are non-required failed checks. Is that something I should dig into and try to fix? Let me know if there's anything else I need to do to prepare it for merge.

**Comment by yannbf** [comment]
Hey @richorrichard nice contribution! I originally swapped `opn` with `better-opn` because it reuses browser tabs rather than always opening a new one (if you kill storybook and run the command again). Do you know if that is still the case? If so, even though the browser will be better respected, it will still be quite annoying.

**Comment by shilman** [comment]
@yannbf doesn't it reuse tabs if your browser is set the chrome? and respect your setting if your browser is not set to chrome? i haven't tested the branch but assuming that's the behavior i would consider that a fix not a regression

**Comment by richorrichard** [comment]
@yannbf and @shilman I agree that using `better-opn` by itself would be an ideal end state, but it would take more work than I think is reasonable for a small issue like this, and I believe the `better-opn` strategy would be more fragile than using it only for the chrome case. 

My reasoning is that `open` handles the logic of opening any given browser _cross-platform_ better than `better-opn`. `better-opn` CAN open other explicitly desired browsers, but it requires passing in that browser's binary as an environment variable, and that variable is platform-specific. So, I believe using `open` is less fragile to use as our base case gracefully handle non-chrome browsers, and use `better-opn` to handle chrome-based browsers because it does a better job of targeting the active window/tab in Chrome.

**Comment by shilman** [comment]
Well said @richorrichard ... works for me! 🙏
