### PR TITLE
Fix to css Zoom not working in safari

### LINKED ISSUE #20888: [Bug]: Zoom in Safari is not working as expected
### Describe the bug

The CSS `zoom` is not working correctly in Safari if rem values are used. See a minimal reproduction here:
https://codepen.io/spielboerg/pen/GRBPRRE

Here is the comparison between Safari & Google Chrome:
Safari Bug

I have already filed a bug report with Apple about this. Until this bug is fixed, it might be better if the zoom was done with `transform: scale()` like for Firefox.

### To Reproduce

1. Open the official Storybook: https://storybookjs.netlify.app/official-storybook/?path=/story/addons-actions--arg-types-example
2. Change the padding of the button in the devTools to `1rem`
3. Increase the zoom in Storybook via SCR-20230202-g58 (not the native browser zoom via CMD/Ctrl + +/-)
4. See that the button is not scaled properly (top: normal zoom, bottom: zoomed in):
    Storybook

### System

```shell
Environment Info:

  System:
    OS: macOS 13.2
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.18.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 109.0
    Safari: 16.3
  npmPackages:
    @storybook/addon-docs: ^6.5.10 => 6.5.16 
    @storybook/addon-essentials: ^6.5.16 => 6.5.16 
    @storybook/addon-links: ^6.5.16 => 6.5.16 
    @storybook/addons: ^6.5.10 => 6.5.16 
    @storybook/builder-webpack5: ^6.5.16 => 6.5.16 
    @storybook/manager-webpack5: ^6.5.16 => 6.5.16 
    @storybook/preset-create-react-app: ^4.1.2 => 4.1.2 
    @storybook/react: ^6.5.16 => 6.5.16 
    @storybook/testing-library: ^0.0.13 => 0.0.13 
    @storybook/theming: ^6.5.10 => 6.5.16
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by FlynnFc**
Closes #20888 

## What I did

Implemented a test for safari. Excludes Chrome, Edge, and all Android browsers.

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [x] Make sure this PR contains **one** of the labels below.

`["bug","ui", "other"]`

### CODE REVIEW

File: code/ui/components/src/Zoom/browserSupportsCssZoom.ts [hunk 1]
```diff
@@ -2,8 +2,12 @@ import { global } from '@storybook/global';
 
 export function browserSupportsCssZoom(): boolean {
   try {
-    // @ts-expect-error (we're testing for browser support)
-    return global.document.implementation.createHTMLDocument('').body.style.zoom !== undefined;
+    const isSafari = /^((?!chrome|android).)*safari/i.test(navigator.userAgent);
```
Comment (ndelangen) [inline code/ui/components/src/Zoom/browserSupportsCssZoom.ts:5]: I think a code-comment here would be great explaining why this odd code is here, and when it'd be safe to remove, assuming the big will eventually be fixed in safari?

Can we have a link to the issue in the safari bugtracker?

This Regex mentions chrome and android, why?

**Review by ndelangen — CHANGES_REQUESTED** [review]

**Comment by ndelangen** [comment]
Thank you for your first PR to storybook ❤️ much appreciated, I've left a review requesting some changes, but they are pretty small ones, I think. 

Let me know if you need any assistance, should be good to merge afterwards.

File: code/ui/components/src/Zoom/browserSupportsCssZoom.ts [hunk 2]
```diff
@@ -2,12 +2,11 @@ import { global } from '@storybook/global';
...
   try {
-    const isSafari = /^((?!chrome|android).)*safari/i.test(navigator.userAgent);
-    if (!isSafari) {
-      // @ts-expect-error (we're testing for browser support)
-      return global.document.implementation.createHTMLDocument('').body.style.zoom !== undefined;
-    }
-    return false;
+    // Checks if safari or firefox is being used.
+    // This check can be removed when zoom becomes standard css. Currently firefox does not support it and there is a bug in safari see here:  https://developer.mozilla.org/en-US/docs/Web/CSS/zoom#browser_compatibility
+    // regex checks if there are other bronwers because "safari" is also present when using chrome or an andriod browser whilst on mac/iphone see more here : https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent#which_part_of_the_user_agent_contains_the_information_you_are_looking_for
```
Comment (ndelangen) [inline code/ui/components/src/Zoom/browserSupportsCssZoom.ts:5]:
```suggestion
    // regex checks if there are other browsers because "safari" is also present when using chrome or an android browser whilst on mac/iPhone see more here : https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent#which_part_of_the_user_agent_contains_the_information_you_are_looking_for
```

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
Great! looking forward to your next PR @FlynnFc ! 🙏

**Comment by valentinpalkovic** [comment]
Causing unexpected behaviors in the following Github Issues:
- https://github.com/storybookjs/storybook/issues/23586
- https://github.com/storybookjs/storybook/issues/16774
