### PR TITLE
Maintenance: Fix broken and outdated documentation links

### LINKED ISSUE #29352: [Bug]: Link to Storybook docs from composition menu fails
### Describe the bug

Currently, when you click on the button labelled "read composition docs", which is shown by the menu when hovering the icon of a composed story, a page opens to the url [https://storybook.js.org/docs/react/sharing/storybook-composition](https://storybook.js.org/docs/react/sharing/storybook-composition), which should be updated to [https://storybook.js.org/docs/sharing/storybook-composition](https://storybook.js.org/docs/sharing/storybook-composition)

### Reproduction link

http://localhost:6006

### Reproduction steps

1. create a storybook with a composed story.
2. hover the icon of the composed story.
3. click on the button labelled "read composition docs" from the composed story menu, 

### System

Storybook Environment Info:

  System:
    OS: Linux 6.8 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) arm64 unknown
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 22.9.0 - /usr/local/share/nvm/versions/node/v22.9.0/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 10.8.3 - /usr/local/share/nvm/versions/node/v22.9.0/bin/npm <----- active
    pnpm: 9.12.1 - /usr/local/share/nvm/versions/node/v22.9.0/bin/pnpm
  npmPackages:
    @storybook/addon-a11y: ^8.3.5 => 8.3.5 
    @storybook/addon-essentials: ^8.3.5 => 8.3.5 
    @storybook/addon-interactions: ^8.3.5 => 8.3.5 
    @storybook/addon-links: ^8.3.5 => 8.3.5 
    @storybook/blocks: ^8.3.5 => 8.3.5 
    @storybook/react: ^8.3.5 => 8.3.5 
    @storybook/react-vite: ^8.3.5 => 8.3.5 
    @storybook/test: ^8.3.5 => 8.3.5 
    @storybook/test-runner: ^0.19.1 => 0.19.1 
    eslint-plugin-storybook: ^0.9.0 => 0.9.0 
    storybook: ^8.3.5 => 8.3.5 
    storybook-dark-mode: ^4.0.2 => 4.0.2 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jonniebigodes**
Closes #29352

With this pull request, the links included in the monorepo were updated to address the recent updates to the documentation, preventing them from generating errors (e.g., 404 and 500).

What was done:
- Updated the links where possible to match the current state of the documentation

This body of work may require patching back to the `main` branch and released as a patch version. I would leave it up to the rest of the maintainers to address how best to proceed.

## Greptile Summary

Updated documentation links across multiple files in the Storybook codebase to fix broken and outdated references.

- Removed '/react' and version-specific segments from URLs to make them framework-agnostic
- Updated links in error messages, comments, and test files to reflect current documentation structure
- Modified prompt messages in migration scripts to use correct, up-to-date documentation links
- Added TODO comments for temporary fixes related to preventing 500 errors during migrations
- Ensured consistency in link updates across various renderer files (HTML, Preact, React, Server, Svelte, Vue3, Web Components)

### CODE REVIEW

**Review by kasperpeulen — APPROVED** [review]

**Review by kylegach — APPROVED** [review]
Wow, great clean up work!! ❤️ 

I left one comment to be addressed, but will go ahead and approve to unblock you.

File: code/core/src/server-errors.ts [hunk 1]
```diff
@@ -217,7 +217,7 @@ export class MissingAngularJsonError extends StorybookError {
     super({
       category: Category.CLI_INIT,
       code: 2,
-      documentation: 'https://storybook.js.org/docs/angular/faq#error-no-angularjson-file-found',
+      documentation: 'https://storybook.js.org/docs/faq#error-no-angularjson-file-found',
```
[the remark this answers is not in the document]
Comment (jonniebigodes) [reply code/core/src/server-errors.ts:220]: I'm aware of it and it's used extensively in other places, however in this case it doesn't add anything as the FAQ is not framework specific, adding that would only add a bit of noise to it.

File: code/lib/cli-storybook/src/automigrate/fixes/remove-legacymdx1.ts [hunk 2]
```diff
@@ -31,11 +31,12 @@ export const removeLegacyMDX1: Fix<RemoveLegacyMDX1Options> = {
     return null;
   },
 
+  // TODO: This is a temporary fix to prevent a 500 error when running the migration and the user clicks the link in the prompt to preview the docs. We'll probably need to account for future releases.
   prompt({}) {
     return dedent`
       You have features.legacyMdx1 in your Storybook main config file. This feature has been removed. Shall we remove it from your Storybook main config file?
 
-      Link: https://storybook.js.org/docs/8.0/migration-guide
+      Link: https://storybook.js.org/docs/migration-guide
```
Comment (kylegach) [inline code/lib/cli-storybook/src/automigrate/fixes/remove-legacymdx1.ts:39]: FYI, I've fixed the bug that broke some redirects, including this one.

Proof: https://storybook.js.org/docs/8.0/migration-guide

Because this link is specific to the 7→8 migration guide, it's best that the version remains so that it points to the correct place when SB 9 is released.

```suggestion
      Link: https://storybook.js.org/docs/8.0/migration-guide
```

File: code/lib/cli-storybook/src/automigrate/fixes/vite-config-file.ts [hunk 3]
```diff
@@ -108,7 +109,7 @@ export const viteConfigFile = {
         If you already have these plugins, you can ignore this message.
 
         You can find more information on how to do this here:
-        https://storybook.js.org/docs/8.0/migration-guide/#missing-viteconfigjs-file
+        https://storybook.js.org/docs/migration-guide#missing-viteconfigjs-file
```
Comment (kylegach) [inline code/lib/cli-storybook/src/automigrate/fixes/vite-config-file.ts:112]: See prior comment

```suggestion
        https://storybook.js.org/docs/8.0/migration-guide#missing-viteconfigjs-file
```

File: code/lib/cli-storybook/src/automigrate/fixes/vite-config-file.ts [hunk 4]
```diff
@@ -118,7 +119,7 @@ export const viteConfigFile = {
       Please add a vite.config.js file to your project root.
 
       You can find more information on how to do this here:
-      https://storybook.js.org/docs/8.0/migration-guide/#missing-viteconfigjs-file
+      https://storybook.js.org/docs/migration-guide#missing-viteconfigjs-file
```
Comment (kylegach) [inline code/lib/cli-storybook/src/automigrate/fixes/vite-config-file.ts:122]: See prior comment

```suggestion
      https://storybook.js.org/docs/8.0/migration-guide#missing-viteconfigjs-file
```

**Review by kylegach — COMMENTED** [review]
I fixed the underlying bug that was breaking a bunch of redirects. It's definitely better to have the canonical URLs being used everywhere, though, so this PR is still great.

The one exception is that some of the migration guide links pertain specifically to SB 8 features, so those should retain the version in the URL. I've left comments calling each of those out.
