### PR TITLE
React: Improve error handling of component manifest generation

### LINKED ISSUE #32848: [Bug]: Manifest error handling
### Describe the bug

Currently:
1. When a componentPath does not successfully resolve, the manifest generation skips generating data for that component
2. When a story source snippet does not successfully render, the manifest generation falls back to `() => <Component />`

In both cases, this obscures the underlying problem, which could be a bug in the manifest generation or the user using an unsupported construct. Instead of hiding the error, the manifest generator should report it cleanly with the line number and context, so that the user can debug.

### Reproduction link

n/a

### Reproduction steps

_No response_

### System

```bash
any
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kasperpeulen**
Closes #32848

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This pull request has been released as version `0.0.0-pr-32855-sha-350cba2a`. Try it out in a new sandbox by running `npx storybook@0.0.0-pr-32855-sha-350cba2a sandbox` or in an existing project with `npx storybook@0.0.0-pr-32855-sha-350cba2a upgrade`.
<details>
<summary>More information</summary>

| | |
| --- | --- |
| **Published version** | [`0.0.0-pr-32855-sha-350cba2a`](https://npmjs.com/package/storybook/v/0.0.0-pr-32855-sha-350cba2a) |
| **Triggered by** | @kasperpeulen |
| **Repository** | [storybookjs/storybook](https://github.com/storybookjs/storybook) |
| **Branch** | [`kasper/error-manifest`](https://github.com/storybookjs/storybook/tree/kasper/error-manifest) |
| **Commit** | [`350cba2a`](https://github.com/storybookjs/storybook/commit/350cba2ab9f42ce66963bb1f75b882fe53f73ce8) |
| **Datetime** | Tue Oct 28 14:14:32 UTC 2025 (`1761660872`) |
| **Workflow run** | [18877200892](https://github.com/storybookjs/storybook/actions/runs/18877200892) |

To request a new release of this pull request, mention the `@storybookjs/core` team.

_core team members can create a new canary release [here](https://github.com/storybookjs/storybook/actions/workflows/publish.yml) or locally with `gh workflow run --repo storybookjs/storybook publish.yml --field pr=32855`_
</details>

## Summary by CodeRabbit

* **New Features**
  * Manifests now include component file path; examples may have optional snippets and per-entry/top-level error info.
  * Snippet generation accepts story identifiers and can emit either function- or variable-style snippets; improved code-location utilities and path helpers.
  * Added a runtime assertion helper.

* **Bug Fixes**
  * Improved metadata synchronization and more robust, error-captured snippet generation and parsing.

* **Tests**
  * Updated tests for manifest shape, error paths, meta-level and top-level export scenarios.

* **Chores**
  * Added .junie to .gitignore.

### CODE REVIEW

File: code/renderers/react/src/componentManifest/utils.ts [hunk 1]
```diff
@@ -10,3 +10,10 @@ export const groupBy = <K extends PropertyKey, T>(
     return acc;
   }, {});
 };
+
+export function invariant(condition: any, message?: string | (() => string)): asserts condition {
+  if (condition) {
+    return;
+  }
+  throw new Error((typeof message === 'function' ? message() : message) ?? 'Invariant failed');
+}
```
Comment (JReinhold) [inline code/renderers/react/src/componentManifest/utils.ts]: how is this better than what we have from `tiny-invariant`? is it because that gets worse in production mode?

File: code/renderers/react/src/enrichCsf.ts [hunk 2]
```diff
@@ -18,17 +18,21 @@ export const enrichCsf: PresetPropertyFn<'experimental_enrichCsf'> = async (inpu
         return;
       }
       const { format } = await getPrettier();
+      let node;
+      try {
+        node = getCodeSnippet(storyExport, csfSource._metaNode, csfSource._meta?.component);
+      } catch (e) {
+        // don't bother the user if we can't generate a snippet
```
Comment (JReinhold) [inline code/renderers/react/src/enrichCsf.ts]: maybe use `logger.debug` here from `storybook/internal/node-logger` so it's at least easy to get this information if we need to?

**Review by JReinhold — APPROVED** [review]
LGTM apart from a few comments.

I'll let @shilman judge the AST stuff, I don't know enough about it to approve it.

File: code/core/src/types/modules/core-common.ts [hunk 3]
```diff
@@ -347,12 +347,14 @@ export type TagsOptions = Record<Tag, Partial<TagOptions>>;
 
 export interface ComponentManifest {
   id: string;
-  name: string;
+  path: string;
+  name?: string;
```
Comment (kasperpeulen) [inline code/core/src/types/modules/core-common.ts]: Make a fallback using the filename

File: code/renderers/react/src/componentManifest/generator.test.ts [hunk 4]
```diff
@@ -412,3 +414,209 @@ test('componentManifestGenerator generates correct id, name, description and exa
...
+test('no component field', async () => {
+  const code = dedent`
+    import type { Meta } from '@storybook/react';
+    import { Button } from './Button';
+
+    export default {
+      args: { onClick: fn() },
+    };
+    
+    export const Primary = {};
```
Comment (kasperpeulen) [inline code/renderers/react/src/componentManifest/generator.test.ts]: make this CSF1

File: code/renderers/react/src/componentManifest/generator.ts [hunk 5]
```diff
@@ -23,42 +23,83 @@ export const componentManifestGenerator = async () => {
...
     );
     const singleEntryPerComponent = Object.values(groupByComponentId).flatMap((group) =>
       group && group?.length > 0 ? [group[0]] : []
     );
     const components = await Promise.all(
-      singleEntryPerComponent.flatMap(async (entry) => {
+      singleEntryPerComponent.flatMap(async (entry): Promise<ReactComponentManifest> => {
         const storyFile = await readFile(path.join(process.cwd(), entry.importPath), 'utf-8');
         const csf = loadCsf(storyFile, { makeTitle: (title) => title ?? 'No title' }).parse();
         const componentName = csf._meta?.component;
```
Comment (kasperpeulen) [inline code/renderers/react/src/componentManifest/generator.ts]: make a fallback

File: code/renderers/react/src/componentManifest/generator.test.ts [hunk 6]
```diff
@@ -412,3 +414,209 @@ test('componentManifestGenerator generates correct id, name, description and exa
...
+              "name": "boolean",
+            },
+          },
+        },
+      },
+      "summary": undefined,
+    }
+  `);
+});
+
```
Comment (kasperpeulen) [inline code/renderers/react/src/componentManifest/generator.test.ts:586]: Test for extracting meta.render

File: code/renderers/react/src/componentManifest/utils.ts [hunk 7]
```diff
@@ -10,3 +10,10 @@ export const groupBy = <K extends PropertyKey, T>(
     return acc;
   }, {});
 };
+
```
Comment (kasperpeulen) [inline code/renderers/react/src/componentManifest/utils.ts:13]: explain why this is needed

File: code/renderers/react/src/enrichCsf.ts [hunk 8]
```diff
@@ -13,46 +13,32 @@ export const enrichCsf: PresetPropertyFn<'experimental_enrichCsf'> = async (inpu
...
       try {
-        const code = recast.print(
-          getCodeSnippet(storyExport, csfSource._metaNode, csfSource._meta?.component)
-        ).code;
-
-        // TODO read the user config
-        snippet = await format(code, { filepath: join(process.cwd(), 'component.tsx') });
+        node = getCodeSnippet(csfSource, key);
       } catch (e) {
         // don't bother the user if we can't generate a snippet
```
Comment (kasperpeulen) [inline code/renderers/react/src/enrichCsf.ts]: put the error in the source
