### PR TITLE
CLI: Add Yarn workspaces support for init command

### LINKED ISSUE #9045: Installation on a Yarn workspace falls back on npm while Yarn is installed
**Describe the bug**
The packages that are set up using `sb init` are being installed via npm despite Yarn presence.

**To Reproduce**
1. Install Yarn via Chocolatey
2. Install `@storybook/cli` globally via Yarn
3. Run `sb init` on an applicable project
4. Observe installation

**Expected behavior**
Yarn could have installed the packages instead of npm.

**System:**
```
  System:
    OS: Windows 10 10.0.17134
    CPU: (4) x64 Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz
  Binaries:
    Node: 12.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
```

**Additional Context:**

Chocolatey version is *0.10.15* (output of `choco --version`)

The sample project had Lerna and Yarn workspaces integrated. The command was run in a Yarn workspaces.

### PR DESCRIPTION
**Pull request by pocka**
Issue: close #9045 

## What I did

Add support Yarn workspaces support for init command.

I changed `@storybook/cli init` command to lookup `yarn.lock` in ancestor directories, in addition to the current directory.

```
# Run `@storybook/cli init` on subdir

## use npm
.
├── package.json
├── package-lock.json
└── subdir/

.
├── package.json
├── package-lock.json
└── subdir/
    ├── package.json
    └── package-lock.json

.
├── package.json
├── yarn.lock
└── subdir/
    ├── package.json
    └── package-lock.json

## use yarn
.
├── package.json
├── yarn.lock
└── subdir/

.
├── package.json
├── package-lock.json
└── subdir/
    ├── package.json
    └── yarn.lock.json
```

I believe this commit doesn't break normal use-cases, but it surely adds complexity.
Should I implement `--use-yarn` flag instead?

## How to test

- Is this testable with Jest or Chromatic screenshots? ... no
- Does this need a new example in the kitchen sink apps? ... no
- Does this need an update to the documentation? ... Updated README

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

File: lib/cli/lib/has_yarn.js [hunk 1]
```diff
@@ -1,13 +1,40 @@
...
   }
   return false;
 }
+
+/**
+ * Lookup yarn.lock in the current directory and its ancestor directories,
+ * return true if it exists.
+ */
+function hasLockFile() {
+  const f = finder();
```
Comment (ndelangen) [inline lib/cli/lib/has_yarn.js]: we could use `find-up` here?

Comment (pocka) [reply lib/cli/lib/has_yarn.js]: Thanks for your advice!

**Review by shilman — APPROVED** [review]
LGTM!!
