### PR TITLE
Core / Addon A11y: Emit `STORY_HOT_UPDATED` and rerun A11y tests on HMR

### LINKED ISSUE #31412: [Bug]: A11y addon panel does not update with new Storybook Test results
### Describe the bug

After running component tests via the testing widget, I would expect the a11y addon panel to update its results. Currently, it only updates after either manually triggering a rerun in the panel or navigating to a different story and back.

The most ideal fix would somehow update the panel automatically. Perhaps by listening to a "tests finished" event and re-running the checks?

### Reproduction link

https://github.com/yannbf/mealdrop/compare/main...retreat-demo

### Reproduction steps

1. Checkout reproduction branch
2. `yarn`
3. `yarn storybook`
4. Have a11y errors
5. Click on a11y error in a story's menu
6. A11y panel correctly shows violation
7. Navigate to different addon panel
8. Fix a11y error and rerun test
9. Click on a11y status in same story's menu
10. A11y panel still shows violation

### System

```bash
System:
    OS: macOS 15.3.2
    CPU: (8) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.16.0 - /private/var/folders/q7/9dmtlkxs0lxfv6nr64f86pth0000gn/T/xfs-787b3a4d/node
    Yarn: 4.2.1 - /private/var/folders/q7/9dmtlkxs0lxfv6nr64f86pth0000gn/T/xfs-787b3a4d/yarn <----- active
    npm: 10.9.2 - ~/projects/mealdrop/node_modules/.bin/npm
  Browsers:
    Chrome: 135.0.7049.117
    Safari: 18.3.1
  npmPackages:
    @storybook/addon-a11y: 9.0.0-beta.11 => 9.0.0-beta.11
    @storybook/addon-designs: 9.0.0-next.3 => 9.0.0-next.3
    @storybook/addon-docs: 9.0.0-beta.11 => 9.0.0-beta.11
    @storybook/addon-themes: 9.0.0-beta.11 => 9.0.0-beta.11
    @storybook/addon-vitest: 9.0.0-beta.11 => 9.0.0-beta.11
    @storybook/react-vite: 9.0.0-beta.11 => 9.0.0-beta.11
    @storybook/test-runner: 0.23.0-next.1 => 0.23.0-next.1
    chromatic: ^11.26.1 => 11.28.2
    eslint-plugin-storybook: 9.0.0-beta.11 => 9.0.0-beta.11
    msw-storybook-addon: ^2.0.4 => 2.0.4
    storybook: 9.0.0-beta.11 => 9.0.0-beta.11
    storybook-addon-test-codegen: patch:storybook-addon-test-codegen@npm%3A1.2.0#~/.yarn/patches/storybook-addon-test-codegen-npm-1.2.0-9550d5ad4c.patch => 1.2.0
```

### Additional context

I tried to use `storybook.new` to create a full reproduction, but ran into two issues:

1. `npx storybook add @storybook/addon-a11y` installed the package but the postinstall script either did not run or did nothing (nothing added to either `main.js` or `preview.js`
2. `npx storybook add @storybook/addon-vitest` errored when trying to install the browser

### PR DESCRIPTION
**Pull request by ghengeveld**
Closes #31412

## What I did

- Added hot module reloading listeners for Vite and Webpack, emitting a new `STORY_HOT_UPDATED` event when this happens.
- Updated the A11y addon to listen for `STORY_HOT_UPDATED` and trigger a "manual" test run when this happens.
- Updated the A11y addon to `waitForAnimations` when doing a manual test run.

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

## Greptile Summary

Based on the provided information, I'll create a concise summary of the pull request changes:

Added hot module reloading (HMR) support to the A11y addon, enabling automatic re-running of accessibility tests when stories are updated during development.

- Added new `STORY_HOT_UPDATED` event to core events for signaling HMR updates in both Vite and Webpack builders
- Implemented `waitForAnimations` utility in a11yRunner to ensure animations complete before running accessibility tests
- Updated A11yContext to listen for HMR updates and trigger accessibility test reruns automatically
- Added animation utilities (`pauseAnimations`, `waitForAnimations`) to handle animation states during testing
- Increased animation check delay from 50ms to 100ms for more reliable test execution

The changes improve the developer experience by automatically updating accessibility test results when code changes occur, addressing issue #31412 where the A11y panel wasn't updating after test runs.

### CODE REVIEW

**Review by valentinpalkovic — APPROVED** [review]

File: code/builders/builder-vite/src/codegen-modern-iframe-script.ts [hunk 1]
```diff
@@ -90,6 +91,10 @@ export async function generateModernIframeScriptCodeFromPreviews(options: {
 
     return dedent`
     if (import.meta.hot) {
+      import.meta.hot.on('vite:afterUpdate', () => {
+        window.__STORYBOOK_PREVIEW__.channel.emit('${STORY_HOT_UPDATED}');
+      });
```
Comment (ndelangen) [inline code/builders/builder-vite/src/codegen-modern-iframe-script.ts:96]: Have we tested this with react fast refresh?
Because fast refresh catches the HMR event and does not let it propagate further.

Comment (ghengeveld) [reply code/builders/builder-vite/src/codegen-modern-iframe-script.ts:96]: @ndelangen How would I do that? Do you have a suggestion on how to detect fast refresh?
