### PR TITLE
UI: Make preview Toolbar and core Bar implement the toolbar role

### LINKED ISSUE #25918: [Bug]: Top toolbar lacking semantics
### Describe the bug

The HTML markup for the top toolbar needs semantics. The buttons should be marked up as an unordered list to indicate the number of items clearly, and ideally, this would be grouped into a labeled `<section>`. 
bug1

### To Reproduce

Inspect top toolbar elements.

### System

_No response_

### Additional context

_No response_

### LINKED ISSUE #26674: Screen reader is not announcing the selection state of the "Violations"/"Passes"/"Incomplete" tab items in Accessibility Tab.
### Describe the bug

OS: Windows 11
OS version: 23H2 (OS Build 22631.3296)
Edge Version: 122.0.2365.80 (Official build) (64-bit)

### To Reproduce

1.Open the URL " [Overview - Docs ⋅ Storybook (windows.net)](https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2fvivacommonstorybooktest.blob.core.windows.net%2f%24web%2findex.html?path%3D%2fdocs%2foverview--docs&data=05%7c02%7cv-subaku%40microsoft.com%7c1d03a870859b492ba99f08dbf6498987%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c638374567927399114%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000%7c%7c%7c&sdata=924Ca%2B3zJMJHXpDXaCwWOTu%2fHX1W%2fJ2TKRp6YoSBli8%3D&reserved=0)".
2.Navigate to the "Tab list" in the left pane and expand it.
3.Navigate to "default" and invoke it.
4.Navigate to "Accessibility" tab item and invoke it.
5.Navigate to the " violations, passes, incomplete tab items.
6.Observe the narrator announcement.

[b12dd9a1-4c07-4f73-8204-4a056297188d.webm](https://github.com/storybookjs/storybook/assets/93735775/32c849c4-9520-4964-89ac-16ac90928e5f)

### System

```bash
Actual Results: 

While navigating to the " violations, passes, incomplete tab items, narrator is not announcing the selected/unselected state.

Expected Results: 

While navigating to the " violations, passes, incomplete” tab items, narrator should announce the selected/unselected state.
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Sidnioulz**
Closes #25918
Closes #32235
Closes #26674

### AriaToolbar

We needed a bar that has the proper toolbar role and implements the toolbar navigation.

* Has built-in kb navigation
* Bundled inside a Bar component

### AbstractAriaToolbar

* Has an absolutely awful name
* Not bundled inside a Bar component, made for custom layout use cases

### AriaTabs

We needed the proper tablist-tabpanel implementation with
* Keyboard navigation (left-right in the list, tab/shift+tab to switch between list and panel)
* The list and panel directly adjacent in tabbing order

* Integrates all below components and hooks into a preconfigured tabpanel
* Forces a layout where the tablist and tabpanel are huddled together, with the tablist in a Bar and optional tools on the side
* Provides access to AriaTabPanel props to limit need to detach
* Allows passing a style object and bg color to the Bar, also to limit need to detach
* Has empty state support like old Tabs
* Can receive tools like old Tabs (but places them before the ariatabs in the tabbing order for WCAG compliance)

### AriaTabList

* Consumes the shared state object
* Shows the list of buttons that control the panel
* Has built-in kb navigation
* Tab items can be disabled, selected (current tab), pressed (being pressed/activated), focused
* Tab items have a title (can be string or ReactNode)

### AriaTabPanel

* Consumes the shared state object
* Shows only the current tab by default
* Has option to render other tabs in the background with a forced `hidden` attr, for React context preservation in existing addon panels
* Has built-in ScrollArea that can be disabled for advanced layouts

### useAriaTabListState

* Generates a shared state from a declarative list of tabs
* The shared state helps tablist and tabpanel share DOM ids, aria attributes, etc.
* Each tab has an id, a title (string|ReactNode), children (string|ReactNode) and aria-label

#### Changes made

* Removed ScrollArea in favour of the CSS scrollbar that was effectively in use everywhere
* Added an inner div to the Bar to preserve height when it scrolls without having to hardcode Bar implementation details in callee code
* Added an `innerStyle` prop to help handling recurring layout customisation needs (padding, gap, flex direction) without having to fork Bar or rely on internal DOM structure

#### Changes not made

* Did not fix the logical coupling between `border` and `backgroundColor` as it was not relevant to what I was fixing, though I'd be happy to smooth that out too to group up component API changes in a single major

#### Rationale

Bar's primary issues are:
* ScrollArea would have side effects in how flex positioning is applied to Bar, because it div layers between the Bar and its callee; this is an issue I ran into during this PR
* Likely erroneous of default values for the `scrollable` prop resulting in three variants: `true` uses ScrollArea, `undefined` uses CSS scrollbars, `false` is non-scrollable; knowing that no code inside Storybook uses `true`
* Bar's handling of height forces callees who want a scrollable Bar to have an extra div layer between the Bar and its children that hardcodes the Bar height, to preserve content height when the scrollbar is drawn

#### Changes made

* Added a `deprecate` notice

#### Rationale

FlexBar is a layout specialisation of Bar, but it turned out that we had places in the code where we needed exactly that layout, but still used Bar. That's because FlexBar made it harder to apply paddings and gaps between items. The component likely was written for a specific use case and existing use cases likely didn't get refactored in time.

Given that the bulk of FlexBar's value can be achieved with a few CSS properties, and that using FlexBar requires writing as much CSS to override its opinionated padding, I prefer removing it entirely.

#### Changes made

* Added a `deprecate` notice
* Removed unused `useResizeDetector` dependency
* Moved `TabButton` subcomponent from the `bar` folder to the `tabs/` folder because it belongs to Tabs

#### Rationale

Tabs suffers a few issues:
* A11y: it hardcodes IDs which results in duplicate-ID WCAG violations
* A11y: it doesn't provide a tabpanel role for the active panel
* A11y: it doesn't implement the required keyboard navigation panel (<- ->)
* A11y: it doesn't attempt to ensure the tablist and tabpanel immediately follow each other in keyboard tab order
* A11y: it doesn't mark the currently selected item in the tablist with `aria-selected`
* A11y: its focus state is not distinguishable from its selected state
* Quality: the existing API has a fair share of presentational props (border, background colour, absolute positioning) that feel like they should be grouped and presented via Emotion CSS objects if relevant, or simply left to callees to handle via Emotion
* Quality: it contains a fair share of addon panel specific code, violating separation of concerns
* Perf: it forces us to render every child instead of just the selected one, even when unnecessary

Fixing those issues requires a near total rewrite of the component's logic, especially because we have patterns where we need the tablist and tabpanel to be rendered separately, and their shared state to be maintained upstream. It also requires adding props for an opaque state object that can contain all the relevant shared state without forcing callees to be aware of implementation details.

It was significantly easier to create a new component than to ensure that both new and existing components are API-compatible.

### AddonPanel (@storybook/components)

* Forced a height of 100% by default, as this is almost always necessary in the addon panel; it helps with vertical centering and scrollbar behaviour
* Added a `hasScrollbar` prop to pre-integrate the scrollbar for addons that don't need a more advanced layout; can be disabled easily enough

#### Rationale

This component is used internally for many of our 'simpler' addon layouts, but also exposed to addon authors. Therefore, it makes sense for the component to provide the best defaults out of the box for addon panel positioning (aka. take all the space and have a scrollbar).

### Toolbar (@storybook/addon-docs/blocks)

* Switched from FlexBar to AriaToolbar, because this is a toolbar and it did not need the FlexBar layout specialisation
* Replaced wrapper div with CSS properties to simplify DOM and code

### SubNav -> Toolbar (component-testing module)

* Renamed component because it is not a nav, and that had caused confusion in the past when refactoring nav ARIA attributes
* Made component use AriaToolbar instead of Bar, as this is a toolbar :)
* Improved aria-label to explain the types of tools found instead of repeating "toolbar" (SRs will already announce that this is a toolbar)
* Simplified layout, favouring padding and gap instead of side margins on children where possible

### Addon panel

* Ported to use AriaTabList and AriaTabPanel
* Moved ErrorBoundary code specific to this panel back from the shared Bars component into the panel source
* Added heading and DOM/ARIA markup for the toolbar to become a landmark

### Addon-controls panel

* Save Story: Adjusted positioning and dimensions of the bar as it was cropped a little
* Adjusted layout to handle changes to AddonPanel container

### Toolbar

* Temporarily migrated the canvas/docs/addon tabs to AriaTabs, without wrapping the preview in a tabpanel, just to fix kb nav behaviour and avoid regressions
* Made minor change to display logic for the canvas wrapper: ensured that if the tabId is set to `canvas`, it also shows (and not just when undefined, for compat with components setting `tabId`)
* Added mention of goal to remove tabs for SB 11, as per RFC: https://github.com/storybookjs/storybook/discussions/32273
* Ported the actual toolbar section to use AbstractAriaToolbar (to avoid compat issues with the tabs section, can be made to use a real AriaToolbar in SB 11)
* Added heading and DOM/ARIA markup for the toolbar to become a landmark

### Settings page

* Switched to new AriaTabs for kb nav
* Simplified code a bit to limit Location context consumers

 
### Solve the overflow menu dilemma
With this PR, we lose the overflow menu that shows when scrollbars with a TabList have too little space. We're considering options:
* sacrifice usability and unmake some of this PR's changes to preserve the overflow button temporarily
* make the entire tablist become a vertical tablist on a menu button as soon as there's an overflow
* permanently replace the tablist with a menu, and add a title for the current addon
* accept the scrollbar and the loss of the overflow menu for now

* [x] @MichaelArestad to try out options in Figma and make a recommendation
* [x] Implementation of the recommended solution

####  Implement CSS changes

* [x] @MichaelArestad to review CSS states from the written stories and provide mockups
* [x] Implement provided mockups

### Finalise naming and deprecation decisions

~Please provide async comments on your preferences. Now that I know SB 10 is here, my recommendation is to entirely remove Tabs and to remove Aria prefixes from the new components' names.~

* [x] **We want to minimize breaking changes, so we want to keep existing names and deprecate rather than remove Tabs / Bar / FlexBar**

* [x] Double check source code in Tabs and Bar to make sure what's deprecated is marked as such and to delete what we choose to remove in SB 10
* [x] Ensure deprecation / removal notices are well written
* [x] TabList: mention that the new AriaTabList does not support mixed link/tab content (tabs only)

### Finish integration of new components
* [x] Use new AriaTabs in TabbedArgsTable (forgotten use case)

### Doc changes
* [x] Write behaviour changes to MIGRATION.md
* [x] Add deprecation notices to MIGRATION.md
 
### Fix E2E tests
* [x] Fix broken locators in Playwright E2E tests

#### The changes in this PR are covered in the following automated tests:

- [x] stories
- [ ] unit tests
- [ ] integration tests
- [x] end-to-end tests

#### Manual testing

1. Run SB
2. Check out the new keyboard behaviour on all affected components: now using Left+Right to navigate as expected

### Documentation

N/A, only MIGRATION.md changes AFAIK

## Checklist for Maintainers

- [x] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [x] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

## Summary by CodeRabbit

- **New Features**
  - Added accessible AriaTabs and AriaToolbar components and a new component-testing Toolbar (status, navigation, rerun).

- **Improvements**
  - Improved keyboard/ARIA support; panels and controls get configurable, consistent scrolling and layout tweaks.

- **Deprecations / Removals**
  - Removed legacy Tabs, TabsState, FlexBar and related helpers; Bar API updated.

- **Documentation**
  - Migration guide updated with API/component notes and a minor typo fix.

- **Chores**
  - Added react-aria/react-stately and updated package metadata.

### CODE REVIEW

File: code/core/src/manager/components/preview/Toolbar.tsx [hunk 1]
```diff
@@ -137,19 +138,24 @@ export const ToolbarComp = React.memo<ToolData>(function ToolbarComp({
...
       data-test-id="sb-preview-toolbar"
-      aria-labelledby={id}
+      aria-labelledby={headingId}
     >
-      <span className="sb-sr-only" id={id}>
+      <h2 id={headingId} className="sb-sr-only">
         Toolbar
-      </span>
-      <ToolbarInner>
+      </h2>
```
[the remark this answers is not in the document]
Comment (Sidnioulz) [reply code/core/src/manager/components/preview/Toolbar.tsx:97]: Will handle through https://github.com/storybookjs/storybook/issues/32271.

File: code/core/src/components/components/Tabs/TabList.stories.tsx [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+  { id: 'tab2', title: 'Tab 2', children: () => <div>Content for Tab 2</div> },
+  { id: 'tab3', title: 'Tab 3', children: () => <div>Content for Tab 3</div> },
+];
+
+const meta = preview.meta({
+  title: 'AriaTabList',
+  component: AriaTabList,
+  args: {
+    tabs: DEFAULT_TABS,
+    state: undefined,
```
Comment (Sidnioulz) [inline code/core/src/components/components/Tabs/TabList.stories.tsx:45]: Getting TS errors on this because tabs aren't an arg. I need help to figure out how to pass that data around and customise it per story (globals?).

Comment (chakAs3) [reply code/core/src/components/components/Tabs/TabList.stories.tsx:45]: what about parameters ?

Comment (Sidnioulz) [reply code/core/src/components/components/Tabs/TabList.stories.tsx:45]: Good call, thanks!

File: code/core/src/components/components/tabs/tabs.tsx [hunk 3]
```diff
@@ -184,6 +185,8 @@ export const Tabs: FC<TabsProps> = memo(
     emptyState,
     showToolsWhenEmpty,
   }) => {
+    deprecate('The `Tabs` component is deprecated. Use `AriaTabs` instead.');
```
Comment (Sidnioulz) [inline code/core/src/components/components/tabs/tabs.tsx]: Must be revisited based on target removal date/version for Tabs and on final name for AriaTabs.

File: code/core/src/components/components/bar/bar.tsx [hunk 4]
```diff
@@ -89,12 +114,13 @@ const BarInner = styled.div<BarInnerProps>(({ bgColor }) => ({
...
 }));
 
-export interface FlexBarProps extends ComponentProps<typeof Bar> {
+export interface FlexBarProps extends BarProps {
   border?: boolean;
   backgroundColor?: string;
 }
 
 export const FlexBar = ({ children, backgroundColor, className, ...rest }: FlexBarProps) => {
+  deprecate('FlexBar is deprecated. Use Bar with justifyContent: "space-between" instead.');
```
Comment (Sidnioulz) [inline code/core/src/components/components/bar/bar.tsx:124]: TODO: clarify date/version of removal.

File: code/core/src/components/components/AriaTabs/AriaTabs.tsx
Comment (Sidnioulz) [inline code/core/src/components/components/AriaTabs/AriaTabs.tsx:1]: Spoken with @ghengeveld and we could reintroduce the overflow button specifically for tabs (not for toolbars) by having the entire tablist collapse at once into a vertical tablist. This would mean that we don't mix up horizontal and vertical kb navigation.

@MichaelArestad WDYT?

File: code/.storybook/manager.tsx [hunk 5]
```diff
@@ -1,8 +1,18 @@
...
   },
 });
+
+addons.register('storybook/internal/manager', (api) => {
+  addons.add('DEBUG-A11y', {
+    type: types.TAB,
+    title: 'DEBUG A11y',
+    render: () => <div>Keep this tab until you're done debugging.</div>,
+  });
+});
```
Comment (Sidnioulz) [inline code/.storybook/manager.tsx]: Remove this. Was added for testing.

File: test-storybooks/portable-stories-kitchen-sink/react/e2e-tests/save-from-controls.spec.ts [hunk 6]
```diff
@@ -30,6 +30,19 @@ test.describe("save-from-controls", () => {
...
+
+
+    // console.log(
+    //   'tabpanel',
+    //   this.page.locator('#storybook-panel-root #panel-tab-content').elementHandle()
+    // );
+    // console.log(
+    //   'all divs',
+    //   this.page.locator('#storybook-panel-root #panel-tab-content > div').elementHandle()
+    // );
```
Comment (Sidnioulz) [inline test-storybooks/portable-stories-kitchen-sink/react/e2e-tests/save-from-controls.spec.ts]: TODO: clean this up

I was debugging playwright behaviour. Could use a hand to run this locally in browser like I'd do with Cypress, to be honest.

**Comment by ghengeveld** [comment]
I added `ci: do not merge` because we want to wrap up our supercycle (2 weeks remaining) before merging this PR, due to it being potentially disruptive. The label may be removed after September 15.

File: code/core/src/components/components/AriaTabs/AriaTabs.tsx
Comment (MichaelArestad) [reply code/core/src/components/components/AriaTabs/AriaTabs.tsx:1]: I'm still hesitant about collapsing everything into the overflow list. I'm okay with trying it to see how it feels.

Comment (Sidnioulz) [reply code/core/src/components/components/AriaTabs/AriaTabs.tsx:1]: Yeah that was a comment before we last spoke. I'll get round to building your mockups at some point. Definitely wanna try the chevrons for fast scrolling like in Firefox!

**Comment by Sidnioulz** [comment]
@coderabbit resolve

**Comment by Sidnioulz** [comment]
@coderabbitai full review

File: code/core/src/components/components/Tabs/TabPanel.tsx [hunk 7]
```diff
@@ -0,0 +1,64 @@
...
+   * Whether to render only the active tab's content, or all tabs. When true, non-selected tabs are
+   * rendered with the hidden attribute and do not affect the accessibility object model.
+   */
+  renderAllChildren?: boolean;
+}
+
+const Panel = styled.div({
+  overflowY: 'hidden',
+  height: '100%',
+});
```
[the remark this answers is not in the document]
Comment (Sidnioulz) [reply code/core/src/components/components/Tabs/TabPanel.tsx:33]: Good call but this is intended. `hasScrollbar` is set to false so that callees build their own scrolling inside the panel.

File: code/core/src/components/components/Tabs/StatelessTabsView.tsx [hunk 8]
```diff
@@ -0,0 +1,91 @@
...
+  // tabListChild,
+  ...props
+}) => {
+  const EmptyContent = emptyState ?? <EmptyTabContent title="Nothing found" />;
+  const [tabListChild, ...tabPanelChildren] = React.Children.toArray(children);
+  if (!showToolsWhenEmpty && tabPanelChildren?.length === 0) {
+    return EmptyContent;
+  }
+
+  // const tabPanelChildren = children;
```
Comment (Sidnioulz) [inline code/core/src/components/components/Tabs/StatelessTabsView.tsx]: @Sidnioulz

**Review by ghengeveld — APPROVED** [review]

File: code/core/src/components/index.ts [hunk 9]
```diff
@@ -68,13 +68,29 @@ export {
...
+export type { TabProps, TabsViewProps } from './components/Tabs/TabsView';
+
+export { StatelessTabList } from './components/Tabs/StatelessTabList';
+export type { StatelessTabListProps } from './components/Tabs/StatelessTabList';
+export { StatelessTabPanel } from './components/Tabs/StatelessTabPanel';
+export type { StatelessTabPanelProps } from './components/Tabs/StatelessTabPanel';
+export { StatelessTabsView } from './components/Tabs/StatelessTabsView';
+export type { StatelessTabsViewProps } from './components/Tabs/StatelessTabsView';
+export { StatelessTab } from './components/Tabs/StatelessTab';
+export type { StatelessTabProps } from './components/Tabs/StatelessTab';
```
Comment (Sidnioulz) [inline code/core/src/components/index.ts:109]: @Sidnioulz check that import paths are well capitalised. Grep `/tabs/` and `/Tabs/`
