### PR TITLE
Core: Fix cyclical dependency in core addons

### LINKED ISSUE #31573: [Bug]: v9 cyclic dependency in storybook/preview causes metro to crash when react compiler is enabled
### Describe the bug

the addon imports in `src/shared/preview/core-annotations.ts` result in a cyclic dependency after bundled since we end up with

`storybook/preview-api -> storybook/measure -> storybook/preview-api`

normally this wouldn't be an issue but there is currently a bug with metro which can cause crashes with cyclic dependencies.

so this is kinda a long winded issue but it would still be good to remove cyclic dependencies if possible

### Reproduction link

https://github.com/dannyhw/repro-compiler

### Reproduction steps

1. clone the project
2. bun install
3. bun run storybook:ios

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 15.5
    CPU: (10) arm64 Apple M1 Max
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.14.0 - /usr/local/bin/node
    Yarn: 1.22.22 - ~/Library/pnpm/yarn
    npm: 10.9.2 - /usr/local/bin/npm
    pnpm: 10.4.0 - ~/Library/pnpm/pnpm
  npmPackages:
    @storybook/addon-docs: 9.0.0-rc.4 => 9.0.0-rc.4 
    @storybook/addon-ondevice-actions: 9.0.0-rc.4 => 9.0.0-rc.4 
    @storybook/addon-ondevice-backgrounds: 9.0.0-rc.4 => 9.0.0-rc.4 
    @storybook/addon-ondevice-controls: 9.0.0-rc.4 => 9.0.0-rc.4 
    @storybook/addon-ondevice-notes: 9.0.0-rc.4 => 9.0.0-rc.4 
    @storybook/react: 9.0.0-rc.4 => 9.0.0-rc.4 
    @storybook/react-native: 9.0.0-rc.4 => 9.0.0-rc.4 
    @storybook/react-native-web-vite: 9.0.0-rc.4 => 9.0.0-rc.4 
    storybook: 9.0.0-rc.4 => 9.0.0-rc.4
```

### Additional context

only happens if the react compiler is enabled for react native projects

heres the issue on react native storybook
https://github.com/storybookjs/react-native/issues/732

a workaround is comment out these lines in `node_modules/storybook/dist/preview-api/index.js` for example with a package patch

```
// src/shared/preview/core-annotations.ts
// import ao from "storybook/internal/component-testing/preview";
// import lo from "storybook/actions/preview";
// import co from "storybook/backgrounds/preview";
// import po from "storybook/highlight/preview";
// import uo from "storybook/measure/preview";
// import fo from "storybook/outline/preview";
// import yo from "storybook/test/preview";
// import mo from "storybook/viewport/preview";
function Ie() {
  return [
    // @ts-expect-error CJS fallback
    // (uo.default ?? uo)(),
    // // @ts-expect-error CJS fallback
    // (co.default ?? co)(),
    // // @ts-expect-error CJS fallback
    // (po.default ?? po)(),
    // // @ts-expect-error CJS fallback
    // (fo.default ?? fo)(),
    // // @ts-expect-error CJS fallback
    // (mo.default ?? mo)(),
    // // @ts-expect-error CJS fallback
    // (lo.default ?? lo)(),
    // // @ts-expect-error CJS fallback
    // (ao.default ?? ao)(),
    // // @ts-expect-error CJS fallback
    // (yo.default ?? yo)(),
  ];
}
```

### PR DESCRIPTION
**Pull request by JReinhold**
Closes https://github.com/storybookjs/storybook/issues/31573

## What I did

- Changed core addons to be imported relatively instead of via an entry point. that way, they become part of the `preview-api` bundle instead of a separate thing. the separate entry point was causing a cyclical dependency, `storybook/preview-api` -> `storybook/highlight/preview` -> `storybook/preview-api`
- Stopped producing these `/preview` entry points, as they weren't actually useful for anything. They are automatically applied in the Storybook runtime as well as in portable stories, implicitly via `setProjectAnnotations()`.

As discussed with @kasperpeulen, @yannbf, @ndelangen.

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [x] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This pull request has been released as version `0.0.0-pr-31750-sha-3896d4de`. Try it out in a new sandbox by running `npx storybook@0.0.0-pr-31750-sha-3896d4de sandbox` or in an existing project with `npx storybook@0.0.0-pr-31750-sha-3896d4de upgrade`.
<details>
<summary>More information</summary>

| | |
| --- | --- |
| **Published version** | [`0.0.0-pr-31750-sha-3896d4de`](https://npmjs.com/package/storybook/v/0.0.0-pr-31750-sha-3896d4de) |
| **Triggered by** | @JReinhold |
| **Repository** | [storybookjs/storybook](https://github.com/storybookjs/storybook) |
| **Branch** | [`jeppe/fix-preview-api-bicycle`](https://github.com/storybookjs/storybook/tree/jeppe/fix-preview-api-bicycle) |
| **Commit** | [`3896d4de`](https://github.com/storybookjs/storybook/commit/3896d4dee486ba8e0c32bf488198222217c89111) |
| **Datetime** | Wed Jun 11 13:52:41 UTC 2025 (`1749649961`) |
| **Workflow run** | [15586796328](https://github.com/storybookjs/storybook/actions/runs/15586796328) |

To request a new release of this pull request, mention the `@storybookjs/core` team.

_core team members can create a new canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=31750`_
</details>

## Greptile Summary

Resolves critical cyclical dependency issue in Storybook's core addons by restructuring how preview APIs are bundled and imported.

- Changed addon imports to use relative paths instead of entry points in `code/core/src/csf/core-annotations.ts`
- Removed separate `/preview` entry points from `code/core/package.json` for various addons (backgrounds, measure, outline, etc.)
- Removed empty index files from multiple addons in `code/core/src/` (backgrounds, outline, measure, component-testing)
- Modified `code/core/scripts/entries.ts` and `dts.ts` to remove preview entries from external dependencies
- Functionality now handled implicitly via `setProjectAnnotations()`, fixing Metro bundler crashes in React Native

### CODE REVIEW

**Comment by JReinhold** [comment]
@dannyhw can you check if this canary fixes the cyclical issue?
If so, I'll try to patch this back to 9.0.

File: code/core/scripts/dts.ts [hunk 1]
```diff
@@ -24,35 +24,19 @@ async function run() {
...
     'storybook/measure',
-    'storybook/measure/preview',
-
     'storybook/highlight',
-    'storybook/highlight/preview',
-
     'storybook/outline',
-    'storybook/outline/preview',
-
     'storybook/backgrounds',
```
Comment (kasperpeulen) [inline code/core/scripts/dts.ts]: can be removed

File: code/core/scripts/dts.ts [hunk 2]
```diff
@@ -24,35 +24,19 @@ async function run() {
     'storybook/theming',
 
     'storybook/test',
-    'storybook/test/preview',
-
     'storybook/measure',
```
Comment (kasperpeulen) [inline code/core/scripts/dts.ts]: can be removed

**Review by ndelangen — APPROVED** [review]

**Comment by dannyhw** [comment]
Hey @JReinhold  Sorry I couldn't test the other day had a lot going on. Unfortunately react native actions was actually using the actions/preview entrypoint to setup actions, maybe there is a way around this but I would need some help to figure that out. 

edit:

still looking into this, the main thing currently is it just breaking the build but I need to see if I can just remove that part

Regarding the react compiler, it is still erroring and I still need to comment out the core annotations to get things to work, one thing I noticed though is that if I just comment out the core annotations in the list even without removing the import it works.

~Yeah right now I can't seem to get the react native actions addon to work :/~ my workaround now is to just duplicate the actions annotations code to react native
