### PR TITLE
Addon-Test: Fix config and watch mode inconsistencies

### LINKED ISSUE #30201: [Tracking]: Universal State Primitive 📡
## 🧑‍🤝‍🧑 Who: @JReinhold and @valentinpalkovic

This is a tracking issue for a project centered around creating a primitive that makes it easier to have state that is synced between some or all "environments".

# ⚠️ Problem

Storybook consists of multiple "environments" that tie the experience together:

- The dev server
- One or multiple places in the the manager UI (eg. an addon panel and toolbar dropdown)
- The preview UI (ie. in stories)

The Channel API can be used to communicate between these environments, but it only solves the _communication_ part, and leaves it up to the consumer to figure out how to keep state in sync between the environments, which is not straight forward. A few use cases that are harder to implement than they should be today are:

1. Sharing state between the dev server and the manager UI. The (experimental) Test addon does this a lot, sharing information between the Vitest instance on the server with the sidebar UI.
2. Sharing state between multiple "slots" in the manager UI, ie. an addon panel that shares information with a toolbar tool. This is hard today because the two components are registered separately without any possibility to instantiate a React context provider or similar way to share information.
3. Sharing state between the preview and the manager UI, ie. an addon panel that needs to show different information based on some logic it is injecting into stories.

The most immediate problem we're facing _today_ is inconsistent state in the Test Module. It can quickly get out of sync if the dev server restarts, if the manager has stale state in session storage, or if other tabs changes the state of the server.

# 🏁 Goals

The high-level goals of this project is to:

1. Construct a low-level primitive API that makes it easier to share state across multiple environments. It must be use-case agnostic, not focusing on any specific environments, eg. it shouldn't _need_ to sync to the server, if the use case is only to sync between manager UI slots. It's still TBD whether or not that API will be a public, non-experimental at the end of the project or not, it might be beneficial to keep it internal/experimental for a period of time before we commit to stabilising it for public use.
2. Use the new API to revamp the state management in the testing addon, eliminating state inconsistencies where possible. There's a high chance this supersedes the current (experimental) testing module API, still TBD.

# 📚 Research

@JReinhold has done an initial POC on a "UniversalState" API, that can serve as an inspiration or starting point for discussions and initial implementation. The final API might not look like this at all, or it might be a slight modification of this, we'll see. 🤷 The POC is implemented in the [`jeppe/universal-state`](https://github.com/storybookjs/storybook/commit/7bca712b843d2af0e8c374563bb2f3fec816ee66) branch.

(note the following videos where originally intended for the Storybook Core team eyes only, so it might require contextual knowledge that you don't have)

<details><summary>Demonstration of UniversalState POC from the consumer perspective</summary>

https://github.com/user-attachments/assets/34991255-1750-48a6-9563-7da6c2aef28d

https://github.com/user-attachments/assets/ac090169-c522-40cb-8866-1f53865d2ec2

</details> 

<details><summary>Demonstration of how the UniversalState POC is implemented</summary>

https://github.com/user-attachments/assets/e39b5fd5-13e6-4b83-b243-78ccf86ff99c

</details> 

The `@chromatic-com/storybook` addon also has a concept of [`SharedState`](https://github.com/chromaui/addon-visual-tests/blob/main/src/utils/SharedState.ts) that is very similar to the UniversalState POC as it needs to solve the same underlying pain-points.

# 🚩 Milestones

The base idea is currently to create a minimal, low-level abstraction on top of the existing Channel API that handles the syncing of the state - the Channel API already handled _communication_ between the environments, but it doesn't handle anything regarding keeping state in sync.

## Primitive API

```[tasklist]
### Tasks
- [x] Discuss confict handling scenarios
- [ ] Revive UniversalState POC within `@storybook/core`
- [ ] Support a Selector-pattern when subscribing to the state
- [ ] Add React-hook in manager UI that handles re-rendering on state change
- [ ] Handle conflict resolution when multiple state instances modify state simultaneously
- [ ] Handle conflicts when multiple state instances are instantiated simultaneously
- [ ] Add persistence hooks for consumers to read/write persisted state
```

## Use API in testing addon

```[tasklist]
### Tasks
- [ ] Use UniversalStore to sync configs (a11y, coverage)
- [ ] Use UniversalStore to sync watch mode
- [ ] Use UniversalStore to sync running state and triggering runs
```

### PR DESCRIPTION
**Pull request by JReinhold**
Closes #30201

## What I did

Changed the flow for Testing Providers, to move config and watch handling to be an internal thing, completely opaque to Storybook core. This means that addon-test now handles all of that internally, using the new UniversalStore API instead.

User facing changes:
- watch mode, coverage and a11y is now controlled by the server. No more inconsistent checkboxes when restarting the server and the UI still says they are enabled. Nothing is persisted to session storage.
- This also means that multiple open tabs will sync their state immediately.
- No more "Settings updated" message and green glow.

*Breaking* API changes to the *experimental* Test provider API:
- `watching`, `watchable` and changing config is now not part of the API anymore. None of these were used by VTA, the only other known user of the API.

- Updated telemetry to include data on coverage and a11y state.

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [x] unit tests
- [ ] integration tests
- [x] end-to-end tests

#### Manual testing

1. Start any Storybook, the UI, a sandbox or the Portable Stories kitchen sink we use to E2E test Testing Module
2. Enable watch mode, you should see Vitest start up in the terminal
3. Make changes to stories and ensure it triggers Vitest
4. Disable watch mode
5. Enable coverage and a11y
6. Run a full test, you should get coverage and a11y results
7. Open a second tab and expand the testing module.
8. Change coverage and a11y, you should see the changes immediately in the other tab
9. Restart the dev sever and reload the browser, you should see that coverage, a11y and watch has been disabled again in the UI

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

| name | before | after | diff | z | % |
| ---- | ------ | ----- | ---- | - | - |
| createSize |  0 B | 0 B | 0 B | - | - |
| generateSize |  80.5 MB | 80.5 MB | 0 B | 0.68 | 0% |
| initSize |  80.5 MB | 80.5 MB | 0 B | -0.3 | 0% |
| diffSize |  97 B | 97 B | 0 B | -0.33 | 0% |
| buildSize |  7.24 MB | 7.28 MB | 32.8 kB | **3.32** | 0.5% |
| buildSbAddonsSize |  1.87 MB | 1.89 MB | 22.1 kB | **20.63** | 1.2% |
| buildSbCommonSize |  195 kB | 195 kB | 0 B | - | 0% |
| buildSbManagerSize |  1.88 MB | 1.88 MB | 355 B | -0.66 | 0% |
| buildSbPreviewSize |  0 B | 0 B | 0 B | - | - |
| buildStaticSize |  0 B | 0 B | 0 B | - | - |
| buildPrebuildSize |  3.94 MB | 3.96 MB | 22.5 kB | **8.3** | 0.6% |
| buildPreviewSize |  3.3 MB | 3.31 MB | 10.3 kB | **1.4** | 0.3% |
| testBuildSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbAddonsSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbCommonSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbManagerSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbPreviewSize |  0 B | 0 B | 0 B | - | - |
| testBuildStaticSize |  0 B | 0 B | 0 B | - | - |
| testBuildPrebuildSize |  0 B | 0 B | 0 B | - | - |
| testBuildPreviewSize |  0 B | 0 B | 0 B | - | - |

| name | before | after | diff | z | % |
| ---- | ------ | ----- | ---- | - | - |
| createTime |  14.3s | 27.2s | 12.8s | 0.7 | 47.1% |
| generateTime |  20.8s | 21.5s | 700ms | **2.12** | 3.2% |
| initTime |  4.9s | 4.5s | -428ms | -0.38 | -9.4% |
| buildTime |  9.9s | 8.2s | -1s -655ms | -1.02 | -20.1% |
| testBuildTime |  0ms | 0ms | 0ms | - | - |
| devPreviewResponsive |  5.4s | 4.8s | -624ms | -1.08 | -12.9% |
| devManagerResponsive |  4.3s | 3.8s | -499ms | -0.65 | -13.1% |
| devManagerHeaderVisible |  1s | 651ms | -423ms | -1.22 | -65% |
| devManagerIndexVisible |  1.1s | 704ms | -452ms | -1.06 | -64.2% |
| devStoryVisibleUncached |  2.9s | 2.3s | -599ms | **-1.93** | 🔰-25% |
| devStoryVisible |  1.1s | 705ms | -481ms | -1.13 | -68.2% |
| devAutodocsVisible |  868ms | 611ms | -257ms | **-1.31** | 🔰-42.1% |
| devMDXVisible |  831ms | 670ms | -161ms | -0.89 | -24% |
| buildManagerHeaderVisible |  796ms | 771ms | -25ms | -0.34 | -3.2% |
| buildManagerIndexVisible |  895ms | 914ms | 19ms | -0.28 | 2.1% |
| buildStoryVisible |  710ms | 751ms | 41ms | -0.25 | 5.5% |
| buildAutodocsVisible |  720ms | 709ms | -11ms | -0.21 | -1.6% |
| buildMDXVisible |  575ms | 600ms | 25ms | -0.45 | 4.2% |

## Greptile Summary

This PR refactors the addon-test module to internalize configuration and watch mode handling using the new UniversalStore API, improving state synchronization across tabs and removing session storage persistence.

- Removed `watching`, `watchable`, and config properties from the experimental Test Provider API, making these features internal to the addon
- Added UniversalStore implementation for state management with proper environment handling and type safety
- Added telemetry reporting for coverage and accessibility states with error sanitization
- Improved test reliability by adding proper setup/cleanup in e2e tests and removing redundant checks
- Added MockUniversalStore for testing with proper state isolation and reset capabilities

### CODE REVIEW

File: code/addons/test/src/components/TestProviderRender.tsx [hunk 1]
```diff
@@ -191,13 +163,13 @@ export const TestProviderRender: FC<TestProviderRenderProps> = ({
...
-  const a11yNotPassedAmount = state.config?.a11y
+  const a11yNotPassedAmount = config?.a11y
     ? a11yResults?.filter((result) => result?.status === 'failed' || result?.status === 'warning')
         .length
     : undefined;
 
   const a11ySkippedAmount =
-    state.running || !state?.details.config?.a11y || !state.config?.a11y
+    state.running || !config?.a11y || !config?.a11y
       ? null
```
[the remark this answers is not in the document]
Comment (valentinpalkovic) [reply code/addons/test/src/components/TestProviderRender.tsx:173]: ☝️

File: code/addons/test/src/preset.ts [hunk 2]
```diff
@@ -102,6 +116,65 @@ export const experimental_serverChannel = async (channel: Channel, options: Opti
...
+
+    channel.on(
+      TESTING_MODULE_PROGRESS_REPORT,
+      async (payload: TestingModuleProgressReportPayload) => {
+        if (payload.providerId !== TEST_PROVIDER_ID) {
+          return;
+        }
+        const status = 'status' in payload ? payload.status : undefined;
+        const progress = 'progress' in payload ? payload.progress : undefined;
+        const error = 'error' in payload ? payload.error : undefined;
```
Comment (valentinpalkovic) [inline code/addons/test/src/preset.ts:137]: Oh TypeScript...

File: code/addons/test/src/preset.ts [hunk 3]
```diff
@@ -102,6 +116,65 @@ export const experimental_serverChannel = async (channel: Channel, options: Opti
...
+          provider: TEST_PROVIDER_ID,
+          watchMode: state.watching,
+        });
+      }
+    });
+
+    channel.on(
+      TESTING_MODULE_PROGRESS_REPORT,
+      async (payload: TestingModuleProgressReportPayload) => {
+        if (payload.providerId !== TEST_PROVIDER_ID) {
```
Comment (valentinpalkovic) [inline code/addons/test/src/preset.ts:132]: Can you elaborate why a separate telemetry handling is necessary for addon test?

Comment (JReinhold) [reply code/addons/test/src/preset.ts:132]: Because we want telemetry to include the information of whether or not coverage/a11y was enabled for the run. And that information is now completely opaque to SB core, so the default core telemetry can't include that information.

File: code/addons/test/src/node/reporter.ts [hunk 4]
```diff
@@ -182,7 +182,6 @@ export class StorybookReporter implements Reporter {
       } as TestingModuleProgressReportProgress,
       details: {
         testResults,
-        config: this.testManager.config,
```
Comment (valentinpalkovic) [inline code/addons/test/src/node/reporter.ts:185]: This change will very likely cause behavioural changes in the frontend. Each run request sent information of how the run should be executed (e.g. a11y=true|false). When sending progress back to the frontend, we take the initial config and send it back. The reason is, that certain states in the sidebar require information of how and whether a particular StatusAPI status should be shown. When receiving the progress report and the user afterwards changes settings, like activating/deactivating a11y, certain statuses might be shown wrongly in the Sidebar. The changes made [here](https://github.com/storybookjs/storybook/pull/30491/files#diff-a1140218b853d9f385690bbcc3904eec72d1edb8c8db8dc3fd907c3333da8d1eR171-R172) are therefore very likely wrong, because they only take the current state into account and not the state from the former test run


Context: https://github.com/storybookjs/storybook/pull/30077/files

Comment (valentinpalkovic) [reply code/addons/test/src/node/reporter.ts:185]: Additionally, if you keep this setting, you don't have to move 6486affcb7da068fbd090cbda9aaa869f30cc71454f328405bb51df993f9ead7R128 telemetry section to addon-test, but rather it can remain as it was in core-presets, because the progress contains the configuration information with which the run was triggered.

File: code/addons/test/src/preset.ts [hunk 5]
```diff
@@ -102,6 +115,65 @@ export const experimental_serverChannel = async (channel: Channel, options: Opti
         addonVersion,
       });
     });
+
+    store.onStateChange(async (state, previous) => {
+      if (state.watching && !previous.watching) {
+        await telemetry('testing-module-watch-mode', {
+          provider: TEST_PROVIDER_ID,
+          watchMode: state.watching,
```
[the remark this answers is not in the document]
Comment (JReinhold) [reply code/addons/test/src/preset.ts:123]: This PR undoes what you state. Watching is now no longer a functionality baked into the Testing module, because it is not relevant to the Testing module (except for telemetry, but that shouldn't drive our API decisions).

See PR description:
> Breaking API changes to the experimental Test provider API:
>
> - watching, watchable and changing config is now not part of the API anymore. None of these were used by VTA, the only other known user of the API.

[the remark this answers is not in the document]
Comment (valentinpalkovic) [reply code/addons/test/src/preset.ts:123]: Hmm. I don't necessarily agree with this change because consequently we would have to change how the testing module in general looks and how the watch button is shown. Currently, it is shown universally in the header section of the testing module. It's technically not part of addon-test. If we ever want to make the Testing Module's API public, it would be odd refering the watch button's functionality exclusively to addon-test.

[the remark this answers is not in the document]
Comment (valentinpalkovic) [reply code/addons/test/src/preset.ts:123]: EDIT: Nevermind. I had the old implementation in mind. You're right with what you said

**Review by valentinpalkovic — APPROVED** [review]
