### PR TITLE
UI: Make TagsFilter state persistent

### LINKED ISSUE #32986: [Bug]: TagsFilter UI resets on every nav open in mobile layout
### Describe the bug

When using the mobile layout, the whole sidebar is hidden behind a menu button. This means the UI is re-rendered, and its state lost, every time the menu is closed and reopened.

We'd need to move the UI state inside TagsFilter into a context stored in the manager Layout. This would have the added benefit of preserving state when switching between mobile and desktop layouts. Using a React Context  would still make it manageable to test TagsFilter.

### Reproduction link

http://localhost:6006/

### Reproduction steps

1. Resize window to be on mobile layout
2. Open sidebar
3. Set a tag filter of your choice
4. Close sidebar
5. Reopen sidebar, tag filter is gone

### System

```bash
Storybook 10.0.6 and/or `next`
Node 24, Linux
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Sidnioulz**
Closes #32986

## What I did

* Moved TagsFilter state for currently selected filters from the TagsFilter & Sidebar components into the `layout` module
* Made that state persistent
* Moved UI-related state (filter count, grouping of filters) to TagsFilterPanel where it is actually consumed
* Mockied the `layout` module for TagsFilter* stories

#### The changes in this PR are covered in the following automated tests:

- [x] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

* Run the local Storybook
* Apply a tag filter of your choice
* Reload the tab and notice the tag filter is maintained
* Close and reopen your browser and notice the tag filter is maintained
* Add default tag filters in your Storybook config, clear your browser cache in DevTools and reload Storybook and your tab to ensure they are applied
* Check that the tag reset button appears upon loading Storybook with active tag filters, but not when loading it with default, config-driven filters

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/publish.yml) or locally with `gh workflow run --repo storybookjs/storybook publish.yml --field pr=<PR_NUMBER>`_

## Summary by CodeRabbit

* **New Features**
  * Dynamic, persistent tag-filter system with built-in and user tag filters and updated default layout sizes.

* **Refactor**
  * Sidebar tag UI and panel reworked to use centralized API-driven filters for simpler state, counts, and accessibility.

* **Tests**
  * Expanded stories with a mock API wrapper and many story variants; added a non-persistent testing store factory.

* **Chores**
  * Storybook global mock added for more stable story rendering.

### CODE REVIEW

**Comment by Sidnioulz** [comment]
@JReinhold @ghengeveld I'd love some feedback from you guys on the approach and how far you think I should take module mocking in the short term. The first few stories in TagsFilter.stories.ts use the mocked module, though with limitations (see https://github.com/storybookjs/storybook/issues/32986#issuecomment-3664521247)

**Comment by ndelangen** [comment]
@Sidnioulz can you resolve the merge conflicts? 🙏

File: code/core/src/manager-api/store.ts [hunk 1]
```diff
@@ -120,3 +122,38 @@ export default class Store {
...
+        callback(internalState);
+      }
+      if (onChange) {
+        onChange(internalState);
+      }
+    },
+  };
+
+  return new Store(upstream);
+}
```
[the remark this answers is not in the document]
Comment (Sidnioulz) [reply code/core/src/manager-api/store.ts]: @ghengeveld this is why you were seeing your localStorage persisted state pollute a sessionStorage setting (sidebar width). We'd need some declarative way to list the state contained in a store (alongside its persistence setting) so we can properly initialise stores without bundling in all of `localStorage`. Not a trivial task :/

File: code/core/src/manager/components/sidebar/TagsFilterPanel.tsx [hunk 2]
```diff
@@ -40,61 +49,131 @@ const MutedText = styled.span(({ theme }) => ({
...
+      }
+    },
+    [api]
+  );
+
+  const setAllFilters = useCallback(
+    (selected: boolean) => {
+      api.setAllTagFilters(selected ? Object.keys(filtersById) : [], []);
+    },
+    [api, filtersById]
```
[the remark this answers is not in the document]
Comment (Sidnioulz) [reply code/core/src/manager/components/sidebar/TagsFilterPanel.tsx:161]: This appears to be the same logic as before.

**Comment by Sidnioulz** [comment]
@ndelangen branch is updated and CI green, it should be good to review

File: code/core/src/manager-api/store.ts [hunk 3]
```diff
@@ -120,3 +122,49 @@ export default class Store {
...
+        callback(internalState);
+      }
+      if (onChange) {
+        onChange(internalState);
+      }
+    },
+  };
+
+  return new InMemoryStore(upstream);
+}
```
Comment (ghengeveld) [inline code/core/src/manager-api/store.ts]: If this is for testing purposes, shouldn't this be in a tests file?

**Review by ghengeveld — APPROVED** [review]

File: code/core/src/manager-api/store.ts (hunk 3 above)
Comment (Sidnioulz) [reply code/core/src/manager-api/store.ts]: I'll isolate it in a `manager-api/test-utils/store.ts` file to make it clearer. I don't think we have an existing pattern for such files, do we?

File: code/core/src/manager-api/modules/layout.ts [hunk 4]
```diff
@@ -504,8 +728,15 @@ export const init: ModuleFn<SubAPI, SubState> = ({ store, provider, singleStory
     api.setOptions(merge(api.getInitialOptions(), persisted));
   });
 
+  provider.channel?.on(STORY_INDEX_INVALIDATED, () => {
+    recomputeFilters(fullAPI, store);
+  });
```
Comment (ndelangen) [inline code/core/src/manager-api/modules/layout.ts]: Could you explain why this change was needed?

File: code/core/src/manager-api/modules/layout.ts [hunk 5]
```diff
@@ -504,8 +728,15 @@ export const init: ModuleFn<SubAPI, SubState> = ({ store, provider, singleStory
...
+
   return {
     api,
     state: merge(api.getInitialOptions(), persisted),
+    init: () => {
+      recomputeFilters(fullAPI, store);
```
Comment (ndelangen) [inline code/core/src/manager-api/modules/layout.ts]: I'm curious why the initial state couldn't be correct to start.

The `init` method is really meant to set up listeners, not immediately change the initial state.

File: code/core/src/manager-api/store.ts [hunk 6]
```diff
@@ -28,6 +28,7 @@ type GetState = () => State;
 type SetState = (a: any, b: any) => any;
 
 interface Upstream {
+  allowPersistence?: boolean;
```
Comment (ndelangen) [inline code/core/src/manager-api/store.ts:35]: Let's add a JSdoc to explain what turning this on/off will do/allow.

File: code/core/src/manager-api/store.ts [hunk 7]
```diff
@@ -108,7 +110,7 @@ export default class Store {
       });
     });
 
-    if (persistence !== 'none') {
+    if (persistence !== 'none' && this.upstreamPersistence) {
```
Comment (ndelangen) [inline code/core/src/manager-api/store.ts:117]: Is this purely added for testing?

File: code/core/src/manager/components/sidebar/TagsFilter.tsx [hunk 8]
```diff
@@ -60,147 +41,14 @@ const TagSelected = styled(Badge)(({ theme }) => ({
...
-          acc.defaultExcluded.add(tag);
-        }
-        return acc;
-      },
-      { defaultIncluded: new Set<string>(), defaultExcluded: new Set<string>() }
-    );
-  }, [tagPresets]);
+export const TagsFilter = ({ api, indexJson }: TagsFilterProps) => {
+  const includedFilters = api.getIncludedTagFilters();
+  const excludedFilters = api.getExcludedTagFilters();
```
Comment (ndelangen) [inline code/core/src/manager/components/sidebar/TagsFilter.tsx]: I suggest we add the data to the state and pass it down from a container component instead of adding a new getter method.

That way, the UI is responsive to the state changes.

As implemented, if this component is memoized, it will not re-render unless either changes: 
- `api` (will never change)
- `indexJson` (will likely change as a result of the filters-change) 

My advice is to avoid using/creating state-getter functions, as we will end up depending on accidental re-render.
And thus introduce state bugs when we fix those accidental re-renders.

File: code/core/src/manager-api/modules/layout.ts (hunk 5 above)
Comment (Sidnioulz) [reply code/core/src/manager-api/modules/layout.ts]: Excellent call. Removing this solved a state corruption problem harming the other tag filter function sources.

File: code/core/src/manager-api/store.ts (hunk 7 above)
Comment (Sidnioulz) [reply code/core/src/manager-api/store.ts:117]: Yes, this is how we can spawn a store in a story context without polluting external storage.

File: code/core/src/manager-api/modules/layout.ts (hunk 4 above)
Comment (Sidnioulz) [reply code/core/src/manager-api/modules/layout.ts]: This was removed, I could not find an explanation why it was needed.

File: code/core/src/manager/components/sidebar/TagsFilter.tsx (hunk 8 above)
Comment (Sidnioulz) [reply code/core/src/manager/components/sidebar/TagsFilter.tsx]: So, rather than call the API, wrap into a ManagerContext consumer or prop-drill all the way from Sidebar?

I don't like the level of prop drilling currently present in the sidebar code because it makes it really hard to test individual component logic in isolation, and so we have code where we only test display concerns and don't cover logic bugs.

I'd be happy to refactor to using a consumer. Though, is it blocking for feature freeze from your POV?

Comment (Sidnioulz) [reply code/core/src/manager/components/sidebar/TagsFilter.tsx]: @ndelangen I've pushed changes that should entirely remove the getters that return stateful content. LMK if that's better :)
