### PR TITLE
UI: Improve contrast ratio between focus / hover

### LINKED ISSUE #24162: [Bug]: Luminosity contrast ratio of keyboard focus indicator on 'Left navigation' controls is 2.604:1 which is less than 3:1
### Describe the bug

Luminosity contrast ratio of keyboard focus indicator on 'Left navigation' controls is 2.604:1 which is less than 3:1 

**Actual Result:**
The color contrast ratio of the keyboard focus indicator for the 'Left navigation' controls is 1.252:1 which is less than 3:1 

**Expected Result:**
The color contrast ratio of the keyboard focus indicator on the 'Left navigation controls' should be greater than or equal to 3:1. 

### To Reproduce

1. Open the URL- [Samples / General - Localization ⋅ Storybook (mgt.dev)](https://mgt.dev/next/v3/?path=/story/samples-general--localization)
2. 'Microsoft Graph Toolkit Playground' Overview page will get displayed. 
3. Navigate to the 'Left rail navigation' region using tab key. 
4. Navigate on the controls using tab key. 
5. Run AI tool and observe the issue. 

Attachments:
ScreenShot

### System

```bash
OS Build: Windows 11 
Version: 22H2 (OS Build 22621.2134) 
Browser: Edge dev 
Browser Version 116.0.1938.76 (Official build) (64-bit)
```

### Additional context

Same issue is repro on Components / mgt-agenda / Properties - Preferred Timezone ⋅ Storybook

### PR DESCRIPTION
**Pull request by chocoscoding**
hover and focus states to meet the minimum requirement of 3:1

Closes #24162 

## What I did

Adjusted the contrast ratio for focus and hover on <BranchNode /> and <LeafNodeStyleWrapper/> to pass 3:1 minimum contrast ratio requirements

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

File: code/ui/manager/src/components/sidebar/Tree.tsx [hunk 1]
```diff
@@ -133,6 +133,7 @@ export const LeafNodeStyleWrapper = styled.div(({ theme }) => ({
   '&:hover, &:focus': {
     outline: 'none',
     background: theme.background.hoverable,
+    color: theme.color.lighter,
```
Comment (cdedreuille) [inline code/ui/manager/src/components/sidebar/Tree.tsx:136]: Thanks a lot for your changes. I checked the branch locally and the result doesn't seem to work properly. When I hover a story the text is becoming white because you set the hover to use `color: theme.color.lighter`.
What was your intent by doing that?

CleanShot 2023-09-19 at 09 39 32

File: code/ui/manager/src/components/sidebar/TreeNode.tsx [hunk 2]
```diff
@@ -73,6 +73,7 @@ const BranchNode = styled.button<{
   background: 'transparent',
   '&:hover, &:focus': {
     background: theme.background.hoverable,
+    color: theme.color.lighter,
```
Comment (cdedreuille) [inline code/ui/manager/src/components/sidebar/TreeNode.tsx:76]: Same here. Why did you choose to set it to use `color.lighter` ? These colors are set and would be the same if you are using dark and light mode.

**Review by cdedreuille — CHANGES_REQUESTED** [review]

File: code/ui/manager/src/components/sidebar/Tree.tsx (hunk 1 above)
Comment (chocoscoding) [reply code/ui/manager/src/components/sidebar/Tree.tsx:136]: Oh, Pardon me. I didn't test for the light mode to see this.
In dark mode, the color of the text on hover and focus was lighter. Which made it pop and more noticable.
Which gave a good contrast ratio score as well.

However, it wasn't so complete

**Comment by chocoscoding** [comment]
I would love to get your opinion on this though,
If i was to archive the text popping on focus and hover effect on both light mode and dark mode.

I did ` color: theme.base === 'light' ? theme.color.darkest : theme.color.lighter` and it works well. 

Do you think its too much or you would like to see it

**Comment by cdedreuille** [comment]
Yes the code you shared depending on the them could work. We are working on a new way to set colours in Storybook that will make working with light and dark mode much easier. But for now this solution could work well.

**Comment by chocoscoding** [comment]
Oh, noted.
Would love to see how you handle the theme. 
Also I have made the contrast ratio good without any highlighting of the color attribute

**Review by cdedreuille — APPROVED** [review]

**Comment by cdedreuille** [comment]
Even better. Then I think it's ok to merge

**Comment by msftedad** [comment]
Hi Team, As issue is still repro. Could you please provide update if there is any?
