### PR TITLE
Addon Test: Prompt switch to `experimental-nextjs-vite`

### LINKED ISSUE #29796: [Bug]: Test addon init should update framework in Next projects
### Describe the bug

```sh
mkdir nextjs-test
cd nextjs-test
npx storybook@next init
npx storybook add @storybook/experimental-addon-test
```

The installer should prompt me about switching my framework to `@storybook/experimental-nextjs-vite`. Otherwise the CT UI won't show up in the testing module

### Reproduction link

N/A

### Reproduction steps

_No response_

### System

```bash
any
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ndelangen**
Closes #29796

## What I did

When the postinstall runs of `experimental-addon-test` and the user is using framework `nextjs` prompt them to change to `experimental-nexjs-vite` framework.

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [x] end-to-end tests

#### Manual testing

This `postinstall` is ran with `yes=true` in our CI.
It's used to "migrate" the `experimental-nextjs-vite-default-ts` sandbox already.

I've manually run the same on my machine locally, and verified the steps are executed, and the sandbox's `main.ts` file and `package.json` files are modified correctly.

QA should include generating a nextjs sandbox WITHOUT the test addon, then adding the test addon to it.
It should ask you to migrate to the experimental framework nextjs vite.

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

| name | before | after | diff | z | % |
| ---- | ------ | ----- | ---- | - | - |
| createSize |  0 B | 0 B | 0 B | - | - |
| generateSize |  77.7 MB | 77.7 MB | 0 B | -0.23 | 0% |
| initSize |  133 MB | 133 MB | -7.15 kB | **2.36** | 0% |
| diffSize |  55.1 MB | 55.1 MB | -7.15 kB | **2.35** | 0% |
| buildSize |  6.87 MB | 6.87 MB | -3.78 kB | 1.05 | -0.1% |
| buildSbAddonsSize |  1.51 MB | 1.51 MB | -219 B | **2.29** | 0% |
| buildSbCommonSize |  195 kB | 195 kB | 0 B | - | 0% |
| buildSbManagerSize |  1.86 MB | 1.86 MB | -2.31 kB | 0.46 | -0.1% |
| buildSbPreviewSize |  0 B | 0 B | 0 B | - | - |
| buildStaticSize |  0 B | 0 B | 0 B | - | - |
| buildPrebuildSize |  3.57 MB | 3.57 MB | -2.52 kB | **1.61** | -0.1% |
| buildPreviewSize |  3.3 MB | 3.3 MB | -1.25 kB | 1.02 | 0% |
| testBuildSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbAddonsSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbCommonSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbManagerSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbPreviewSize |  0 B | 0 B | 0 B | - | - |
| testBuildStaticSize |  0 B | 0 B | 0 B | - | - |
| testBuildPrebuildSize |  0 B | 0 B | 0 B | - | - |
| testBuildPreviewSize |  0 B | 0 B | 0 B | - | - |

| name | before | after | diff | z | % |
| ---- | ------ | ----- | ---- | - | - |
| createTime |  7.9s | 6.8s | -1s -19ms | -0.54 | -14.8% |
| generateTime |  25s | 19.8s | -5s -174ms | -0.44 | -26% |
| initTime |  19s | 13.8s | -5s -258ms | -0.04 | -38.1% |
| buildTime |  9s | 8.9s | -74ms | 0.23 | -0.8% |
| testBuildTime |  0ms | 0ms | 0ms | - | - |
| devPreviewResponsive |  5.2s | 4.5s | -719ms | -0.96 | -15.7% |
| devManagerResponsive |  4s | 3.4s | -652ms | -0.98 | -19.2% |
| devManagerHeaderVisible |  627ms | 599ms | -28ms | 0.32 | -4.7% |
| devManagerIndexVisible |  667ms | 612ms | -55ms | -0.47 | -9% |
| devStoryVisibleUncached |  1.9s | 1.7s | -217ms | 0.04 | -12.2% |
| devStoryVisible |  666ms | 635ms | -31ms | -0.05 | -4.9% |
| devAutodocsVisible |  505ms | 500ms | -5ms | -0.44 | -1% |
| devMDXVisible |  571ms | 590ms | 19ms | 1 | 3.2% |
| buildManagerHeaderVisible |  635ms | 608ms | -27ms | 0.16 | -4.4% |
| buildManagerIndexVisible |  746ms | 704ms | -42ms | 0.28 | -6% |
| buildStoryVisible |  580ms | 566ms | -14ms | 0.37 | -2.5% |
| buildAutodocsVisible |  462ms | 419ms | -43ms | -0.58 | -10.3% |
| buildMDXVisible |  445ms | 437ms | -8ms | -0.16 | -1.8% |

## Greptile Summary

This PR adds functionality to prompt users to migrate from @storybook/nextjs to @storybook/experimental-nextjs-vite during the experimental-addon-test installation process, ensuring proper test addon functionality.

- Added prompt in `postinstall.ts` to switch frameworks when Next.js is detected
- Handles migration by installing `@storybook/experimental-nextjs-vite` and removing `@storybook/next`
- Updates main config file's framework field to use experimental framework
- Configures Vitest setup with appropriate framework plugin imports and settings
- Maintains backward compatibility by preserving existing test configurations

### CODE REVIEW

File: code/addons/test/src/postinstall.ts [hunk 1]
```diff
@@ -53,6 +55,34 @@ export default async function postInstall(options: PostinstallOptions) {
...
+      ]);
+
+      await packageManager.removeDependencies({}, ['@storybook/next']);
+
+      // update the storybook main.ts config file
+      const mainJsPath = serverResolve(resolve(options.configDir, 'main')) as string;
+
+      const config = await readConfig(mainJsPath);
+
+      config.setFieldValue(['framework'], '@storybook/experimental-nextjs-vite');
```
Comment (yannbf) [inline code/addons/test/src/postinstall.ts:78]: If users have a monorepo-shenanigan like the it has to be respected as well e.g.:

```ts
const getAbsolutePath = (packageName) =>
  path.dirname(require.resolve(path.join(packageName, 'package.json')));

export default {
  framework: {
    name: getAbsolutePath('@storybook/react'),
    options: {},
  },
}
```

File: code/addons/test/src/postinstall.ts [hunk 2]
```diff
@@ -53,6 +55,34 @@ export default async function postInstall(options: PostinstallOptions) {
   // if Vitest is installed, we use the same version to keep consistency across Vitest packages
   const vitestVersionToInstall = vitestVersionSpecifier ?? 'latest';
 
+  if (info.frameworkPackageName === '@storybook/nextjs') {
+    const out = await prompts({
+      type: 'confirm',
+      name: 'migrateToExperimentalNextjsVite',
+      message: `To use this addon, you should migrate to use @storybook/experimental-nextjs-vite, do you want to migrate?`,
```
Comment (yannbf) [inline code/addons/test/src/postinstall.ts:62]: You should check this part of the code below which already handles installing the package:
https://github.com/storybookjs/storybook/blob/13e54a028b9a4005142b113693e839218ca9c612/code/addons/test/src/postinstall.ts#L205

You should also check about the messaging, making it clear to the user why and provide a link to the docs (like the code I referred)

File: code/addons/test/src/postinstall.ts [hunk 3]
```diff
@@ -53,6 +55,34 @@ export default async function postInstall(options: PostinstallOptions) {
...
+      await packageManager.addDependencies({ installAsDevDependencies: true }, [
+        '@storybook/experimental-nextjs-vite',
+      ]);
+
+      await packageManager.removeDependencies({}, ['@storybook/next']);
+
+      // update the storybook main.ts config file
+      const mainJsPath = serverResolve(resolve(options.configDir, 'main')) as string;
+
+      const config = await readConfig(mainJsPath);
```
Comment (yannbf) [inline code/addons/test/src/postinstall.ts:76]: We must do something here in case people have a webpack/webpackFinal property in their main.js. They have to know that they need to do something, else that bit of code will be ignored and won't be applied when they are running tests

File: code/addons/test/src/postinstall.ts (hunk 1 above)
Comment (ndelangen) [reply code/addons/test/src/postinstall.ts:78]: got it, I think I have a solution for this.

File: code/addons/test/src/postinstall.ts (hunk 3 above)
Comment (ndelangen) [reply code/addons/test/src/postinstall.ts:86]: I added a prerequisiteCheck, is that correct, do you think?

File: code/addons/test/src/postinstall.ts (hunk 2 above)
Comment (ndelangen) [reply code/addons/test/src/postinstall.ts]: Okay, I tried to improve the messaging. What do you think?

File: code/addons/test/src/postinstall.ts [hunk 4]
```diff
@@ -53,6 +57,56 @@ export default async function postInstall(options: PostinstallOptions) {
...
+      `,
+          initial: true,
+        });
+
+    if (out.migrateToExperimentalNextjsVite) {
+      await packageManager.addDependencies({ installAsDevDependencies: true }, [
+        '@storybook/experimental-nextjs-vite',
+      ]);
+
+      await packageManager.removeDependencies({}, ['@storybook/next']);
```
Comment (ndelangen) [inline code/addons/test/src/postinstall.ts:87]:
```suggestion
      await packageManager.removeDependencies({}, ['@storybook/nextjs']);
```

File: code/addons/test/src/postinstall.ts [hunk 5]
```diff
@@ -53,6 +57,56 @@ export default async function postInstall(options: PostinstallOptions) {
...
+
+      const mainJsPath = serverResolve(resolve(options.configDir, 'main')) as string;
+      const config = await readConfig(mainJsPath);
+
+      const node = config.getFieldNode(['framework']);
+
+      traverse(node, {
+        StringLiteral(path) {
+          if (path.node.value === '@storybook/next') {
```
Comment (ndelangen) [inline code/addons/test/src/postinstall.ts:96]:
```suggestion
          if (path.node.value === '@storybook/nextjs') {
```

File: code/addons/test/src/postinstall.ts [hunk 6]
```diff
@@ -57,6 +61,52 @@ export default async function postInstall(options: PostinstallOptions) {
...
+            The addon requires the use of @storybook/experimental-nextjs-vite to work with Next.js.
+            https://storybook.js.org/docs/writing-tests/test-addon#install-and-set-up
+
+            Do you want to migrate?
+          `,
+          initial: true,
+        });
+
+    if (out.migrateToExperimentalNextjsVite) {
+      console.log('running migrateToExperimentalNextjsVite');
```
Comment (valentinpalkovic) [inline code/addons/test/src/postinstall.ts:87]: Do you want to keep the console.log?

File: code/addons/test/src/postinstall.ts [hunk 7]
```diff
@@ -57,6 +61,52 @@ export default async function postInstall(options: PostinstallOptions) {
...
+      await packageManager.addDependencies({ installAsDevDependencies: true }, [
+        '@storybook/experimental-nextjs-vite',
```
Comment (valentinpalkovic) [inline code/addons/test/src/postinstall.ts:89]: Which version of `@storybook/experimental-nextjs-vite` will be added? Always the latest?

Comment (ndelangen) [reply code/addons/test/src/postinstall.ts:89]: hmm fair enough, should be the same as the current CLI version.

File: code/addons/test/src/postinstall.ts (hunk 6 above)
Comment (ndelangen) [reply code/addons/test/src/postinstall.ts:87]: nope 🙈

**Review by valentinpalkovic — APPROVED** [review]
