### PR TITLE
NextJS: Aliases `react` and `react-dom` like `next.js` does

### LINKED ISSUE #23661: [Bug]: Using appDirectory in preview.ts causes reactdom.preload error with Next.js framework
### Describe the bug

When using the image component from `next/image`, adding the `priority` flag will cause storybook stories to fail to render if the following conditions are met:

- Storybook is using the `@storybook/nextjs` framework
- Storybook's `preview.ts` is setup to support nextjs routing as per guide here: https://storybook.js.org/recipes/next#configuring-nextnavigation

Drilling down further, it seems that it is the addition of `appDirectory: true` that is causing the failure:

Screenshot 2023-07-31 at 10 46 23

If I remove the `appDirectory: true` setting, then all is good:

Screenshot 2023-07-31 at 10 50 32

### To Reproduce

A simple GitHub repo to reproduce this issue is available here: https://github.com/terrymun/storybook-nextjs-image-with-priority

An alternative way to reproduce this is to add the following lines to the `preview.js` (or `preview.ts`) file on a Storybook that is configured to work with Next.js:

```ts
export const parameters = {
  // ... your other parameters config

  nextjs: {
    // WARNING: This will cause the storybook to throw an error
    appDirectory: true,
  },
}
```

### System

```shell
Environment Info:

  System:
    OS: macOS 13.4.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 115.0.5790.114
    Edge: 115.0.1901.188
    Safari: 16.5.2
  npmPackages:
    @storybook/addon-essentials: ^7.2.0-rc.0 => 7.2.0-rc.0 
    @storybook/addon-interactions: ^7.2.0-rc.0 => 7.2.0-rc.0 
    @storybook/addon-links: ^7.2.0-rc.0 => 7.2.0-rc.0 
    @storybook/addon-onboarding: ^1.0.8 => 1.0.8 
    @storybook/blocks: ^7.2.0-rc.0 => 7.2.0-rc.0 
    @storybook/nextjs: ^7.2.0-rc.0 => 7.2.0-rc.0 
    @storybook/react: ^7.2.0-rc.0 => 7.2.0-rc.0 
    @storybook/testing-library: ^0.2.0 => 0.2.0
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sookmax**
Closes #23661

**Warning**: This PR seems to break the rendering of `<InlineStory />` in docs pages. Please **do not** accept this PR until the issue related to the rendering of `<InlineStory />` is resolved.

## What I did

While I was investigating #23661, I noticed `next`'s webpack resolves `react` and `react-dom` differently. Specifically, it resolves them to the pre-compiled versions that reside in `next/dist/compiled/react` and `next/dist/compiled/react-dom` respectively: https://github.com/vercel/next.js/blob/ff5338ce03a3240a97a5c84f5ad5c31c0f53a6ce/packages/next/src/build/webpack-config.ts#L1370-L1379.

I speculate these pre-compiled `react` and `react-dom` are from [Canary channel](https://react.dev/community/versioning-policy#canary-channel) of React, which contains some undocumented / experimental APIs that are not available in [Latest channel](https://react.dev/community/versioning-policy#latest-channel).

`next` uses these experimental versions of `react` and `react-dom` because some of their components (e.g., `next/image`) depends on the APIs provided by them.

To be more specific, the root cause of #23661 is the introduction of a new dependency in `next/image` (https://github.com/vercel/next.js/pull/52425) that is not available in `react-dom@latest`: https://github.com/vercel/next.js/blob/7d57784fc0585cb9e5394b982761a840a6554515/packages/next/src/client/image-component.tsx#L13. (i.e., `ReactDOM.preload()`).

So I added the same aliases to `@Storybook/nextjs` so that `next/image` doesn't break in the storybook webpack server.

Unfortunately, this introduces a new bug where the `<Canvas />` (or more specifically `<InlineStory />` in the Canvas) doesn't render the story component properly:

Screenshot 2023-08-01 at 10 49 42 PM

---

React _does_ throw an error that says `Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.` when I leave the docs page and enter a story page, but other than that I'm pretty much clueless why the change I made affects the rendering of `<InlineStory />` 😅.

So, it would be much appreciated if the core team members shed some lights in this issue so that eventually we can resolve #23661.

Thanks!

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "build", "documentation", "maintenance", "dependencies", "other"]`

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

File: code/ui/blocks/src/components/Story.tsx [hunk 1]
```diff
@@ -83,13 +80,7 @@ const InlineStory: FunctionComponent<InlineStoryProps> = (props) => {
         )} { min-height: ${height}; transform: translateZ(0); overflow: auto }`}</style>
       ) : null}
       {showLoader && <StorySkeleton />}
-      <div
-        ref={storyRef}
-        id={`${storyBlockIdFromId(props)}-inner`}
-        data-name={story.name}
-        // eslint-disable-next-line react/no-danger
-        dangerouslySetInnerHTML={{ __html: htmlContents }}
-      />
```
Comment (valentinpalkovic) [inline code/ui/blocks/src/components/Story.tsx:92]: @tmeasday This seemed to be an issue. Can you take a look at this? Maybe you remember why the dangerouslySetInnerHTML was necessary at all.

Comment (tmeasday) [reply code/ui/blocks/src/components/Story.tsx:92]: @valentinpalkovic I think it is explained by the comment above:

> We do this so React doesn't complain when we replace the span in a secondary render

IIRC, if you render (in an "outer" react context [the docs page in this case]):

```
<div><span /></div>
```

And then later use a second "inner" react context [the react renderer in this case] to overwrite the `span` (`ReactDOM.render(<something />, theSpan`), then React helpfully warns you that you are overwritting one render tree with another. This was a trick to avoid that.

It may longer be an issue or there may be a better way. I am not sure.

Comment (ndelangen) [reply code/ui/blocks/src/components/Story.tsx:92]: Possibly the canary version of react changes this behavior. and we can no longer depend on this trick @tmeasday.

Comment (tmeasday) [reply code/ui/blocks/src/components/Story.tsx:92]: If so great!

**Comment by yannbf** [comment]
@tmeasday @valentinpalkovic @ndelangen what are the next steps for this PR?

**Review by ndelangen — APPROVED** [review]

**Comment by tmeasday** [comment]
@ndelangen it looks like there is an unresolved problem on this PR?

**Comment by ndelangen** [comment]
DangerJS seems to fail over some auth token problem @tmeasday
