### PR TITLE
Bug: ensure src of iframe for a ref stays the same, unless the version changes

### LINKED ISSUE #21499: [Bug]: Composition - switching stories within a composed storybook shows spinners and reloads
### Describe the bug

Issue extracted from: https://github.com/storybookjs/storybook/issues/21352

@yannbf reported some of these in QA as well.

When visiting composed stories, the preview completely reloads after a second. 
This is composing the SB Design system.

Here's another example showing the difference between a composed storybook and the uncomposed:

---

Changing controls to a composed Storybook seems to reload the entire preview.

### To Reproduce

- Add a ref to the `code/ui/.storybook/main.ts` file.
  ```js
  refs: {
    'design-system': {
      title: 'Design System',
      url: 'https://master--5ccbc373887ca40020446347.chromatic.com/',
    },
  },
  ```
- start the storybook
- switch stories

### System

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ndelangen**
Closes https://github.com/storybookjs/storybook/issues/21499

## What I did

I ensured that when rendering iframes we don't change the src attribute of the iframe unless the base-url changes (the version changed)

## How to test

1. Add a ref
2. Start and load storybook
3. Go to the composed storybook
4. Switch between stories

Expect no loaders/spinner and no refreshes

### CODE REVIEW

File: code/ui/manager/src/components/preview/FramesRenderer.tsx [hunk 1]
```diff
@@ -51,6 +51,8 @@ export const FramesRenderer: FC<FramesRendererProps> = ({
   storyId = '*',
 }) => {
   const version = refs[refId]?.version;
+  const storyIdRef = useRef(storyId);
+  const viewModeRef = useRef(viewMode);
```
Comment (tmeasday) [inline code/ui/manager/src/components/preview/FramesRenderer.tsx:55]: Can you explain why these refs are needed?

File: code/ui/manager/src/components/preview/FramesRenderer.tsx [hunk 2]
```diff
@@ -95,12 +97,12 @@ export const FramesRenderer: FC<FramesRendererProps> = ({
...
         return {
           ...acc,
-          [`storybook-ref-${r.id}`]: `${r.url}/iframe.html?id=${storyId}&viewMode=${viewMode}&refId=${r.id}${stringifiedQueryParams}`,
+          [`storybook-ref-${r.id}`]: `${r.url}/iframe.html?id=${storyIdRef}&viewMode=${viewModeRef}&refId=${r.id}${stringifiedQueryParams}`,
         };
       }, frames);
 
     setFrames(newFrames);
-  }, [storyId, entry, refs]);
+  }, [entry, ...Object.values(refs).map((r) => r.id)]);
```
Comment (tmeasday) [inline code/ui/manager/src/components/preview/FramesRenderer.tsx:105]: 1. If we pass `entry` here, doesn't it rerun everytime you change story (and thus the entry changes)?
2. Do the internals of the refs ever change? I was thinking if we do the filtering outside of the `useEffect` and key on the list of filtered ref ids, we could be resilient to that.

File: code/ui/manager/src/components/preview/FramesRenderer.tsx [hunk 3]
```diff
@@ -117,19 +119,22 @@ export const FramesRenderer: FC<FramesRendererProps> = ({
...
-            id={id}
-            title={id}
-            src={src}
-            allowFullScreen
-            scale={scale}
-          />
-        </Fragment>
-      ))}
+      {Object.entries(frames).map(([id, src]) => {
+        const [key] = refs[id] ? refs[id].url.split('?') : [id];
```
Comment (tmeasday) [inline code/ui/manager/src/components/preview/FramesRenderer.tsx:123]: FTR the `id` here doesn't match the `ref` id ("id = `storybook-ref-${r.id}`") so this line of code is actually pointless/broken.

**Review by tmeasday — CHANGES_REQUESTED** [review]

File: code/ui/manager/src/components/preview/FramesRenderer.tsx (hunk 1 above)
Comment (ndelangen) [reply code/ui/manager/src/components/preview/FramesRenderer.tsx:55]: The idea is to lock the values, so they won't change, thus won't trigger updates.
But I'll refactor this to have the same effect.

Comment (tmeasday) [reply code/ui/manager/src/components/preview/FramesRenderer.tsx]: @ndelangen as long as you don't depend on them in the dependencies array to `useEffect`, it doesn't matter.

**Review by tmeasday — COMMENTED** [review]
I like this as it is more consistent with what we do for the main frame (set it once when we first boot and then never again).

However I'm wondering about losing this logic:
image

If I understand the old code directly, it's saying we need to add iframes for `auto-inject` refs even before they are selected. Is this the type of ref where we don't have an `index.json` (ie SSv6) so we need to wait for the `SET_STORIES` (now `SET_INDEX`) event in order to render the sidebar?

If so, we'll have a chicken and egg situation if we don't show the frame before the ref is selected (it won't be possible to select the ref because we haven't rendered it yet).

File: code/ui/manager/src/components/preview/FramesRenderer.tsx [hunk 4]
```diff
@@ -57,50 +65,42 @@ export const FramesRenderer: FC<FramesRendererProps> = ({
...
+      ? {
+          [`storybook-ref-${selectedRef.id}`]: `${selectedRef.url}/iframe.html?id=${storyId}&viewMode=${viewMode}&refId=${selectedRef.id}${stringifiedQueryParams}`,
+        }
+      : {}),
+    ...autoInjectedRefs.reduce((acc, ref) => {
+      return {
+        ...acc,
+        [`storybook-ref-${ref.id}`]: `${ref.url}/iframe.html?id=${storyId}&viewMode=${viewMode}&refId=${ref.id}${stringifiedQueryParams}`,
+      };
+    }, {}),
```
Comment (tmeasday) [inline code/ui/manager/src/components/preview/FramesRenderer.tsx:89]: Can we combine this to one array to avoid duplication? `[...autoInjectedRefs, selectedRef]`

**Review by tmeasday — APPROVED** [review]
Yes! I love it @ndelangen -- much cleaner now.
