### PR TITLE
Addon-docs: Fix Table of Contents heading leak

### LINKED ISSUE #23541: [Bug]: 7.1 Stories are leaking headers into table of contents
### Describe the bug

When I enable the table of contents the headers from within stories are displayed in the TOC. I would expect that stories are isolated from the rest of the storybook.

Screenshot 2023-07-20 at 16 25 36

### To Reproduce

1. Enable TOC
2. Create a story and use `h3` tag (depends on configuration) in the story

### System

```shell
Environment Info:

  System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 3.5.0 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.14.0 - ~/Projects/design-system-v2/node_modules/.bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5.1
  npmPackages:
    @storybook/addon-a11y: ^7.1.0 => 7.1.0 
    @storybook/addon-actions: ^7.1.0 => 7.1.0 
    @storybook/addon-designs: ^7.0.1 => 7.0.1 
    @storybook/addon-docs: ^7.1.0 => 7.1.0 
    @storybook/addon-essentials: ^7.1.0 => 7.1.0 
    @storybook/addon-interactions: ^7.1.0 => 7.1.0 
    @storybook/blocks: ^7.1.0 => 7.1.0 
    @storybook/components: ^7.1.0 => 7.1.0 
    @storybook/jest: ^0.1.0 => 0.1.0 
    @storybook/react: ^7.1.0 => 7.1.0 
    @storybook/react-vite: ^7.1.0 => 7.1.0 
    @storybook/test-runner: ^0.11.0 => 0.11.0 
    @storybook/testing-library: ^0.2.0 => 0.2.0
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by vmizg**
Closes #23541

## What I did

Exclude all content from Story blocks from being indexed by the Table of Contents (TOC) component by default. The user can still override the `ignoreSelector` to adjust this behaviour.

> IMO, the default headingSelector should be `h2, h3` instead of just `h3`, but this is not in the scope of this fix. Worth considering?

## How to test

1. Set up the following TOC config in the `sandbox/.storybook/preview.ts` file:
    ```ts
    import type { Preview } from '@storybook/react';
    
    const preview: Preview = {
      parameters: {
        ...
        docs: {
          toc: {
            disable: false,
            headingSelector: 'h1, h2, h3',
          },
        },
      },
    };
    
    export default preview;
    ```
2. Run the default sandbox, `yarn start`
3. Open Storybook in your browser
4. Go to the Header `Docs` page
5. See that the `Acme` headings from the sample component do not bleed into the generated Table of Contents

To test the previous behaviour, do the same thing and note the difference in Table of Contents.

## Checklist

- [x] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [x] Make sure to add/update documentation regarding your changes
- [x] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md) (N/A)

#### Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "build", "documentation", "maintenance", "dependencies", "other"]`

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

File: code/ui/blocks/src/components/TableOfContents.tsx [hunk 1]
```diff
@@ -139,14 +139,13 @@ export const TableOfContents = ({
...
       headingSelector: headingSelector ?? 'h3',
-      ignoreSelector: ignoreSelector ?? '.skip-toc',
-      headingsOffset: 40,
-      scrollSmoothOffset: -40,
       /**
        * Ignore headings that did not
        * come from the main markdown code.
        */
-      // ignoreSelector: ':not(.sbdocs), .hide-from-toc',
+      ignoreSelector: ignoreSelector ?? '.docs-story *, .skip-toc',
```
Comment (kylegach) [inline code/ui/blocks/src/components/TableOfContents.tsx:146]: @shilman — This approach seems sound to me, but you're the one who left the commented-out version to seemingly accomplish the same thing, so thought you'd like to chime in.

**Review by JReinhold — APPROVED** [review]
Looks great, thanks!

**Comment by cdedreuille** [comment]
What's the status on this one @JReinhold? Any reason why this is not merged?

**Review by shilman — APPROVED** [review]
