### PR TITLE
CLI: Fix throwing in readonly environments

### LINKED ISSUE #31709: [Bug]: SB_CORE-SERVER_0001 on read-only file system
### Describe the bug

To avoid impurities, we run our CI systems in a mostly read-only environment. `storybook build --disable-telemetry` fails to run with

```
Error loading global settings SB_CORE-SERVER_0001 (SavingGlobalSettingsFileError): Unable to save global settings file to $HOME/.storybook/settings.json
Reason: Error: EACCES: permission denied, open '$HOME/.storybook/settings.json'
```

This happens in 8.6.14 as well as 9.0.6. `storybook dev` also shows the error but continues to startup fine.

It seems build fails due to project json creation loading the global settings too and there's no CLI flag to turn it off. IIUC, this is also telemetry related. Maybe it should also respect `STORYBOOK_DISABLE_TELEMETRY`?

As a workaround, specifying `disableProjectJson` via the config file does work though. Though it would be nice to have this kind of thing be optional and not write to the home directory.

### Reproduction link

n/a

### Reproduction steps

1. `git clone https://github.com/storybookjs/sandboxes.git --depth=1
2. `cd sandboxes/react-webpack/18-ts/after-storybook`
3. `npm install` 
4. `mkdir -p $HOME/.storybook`
5. `chmod -w $HOME/.storybook`
6. `npm run storybook-build`

### System

```bash
Storybook Environment Info:

  System:
    OS: Linux 6.11 Fedora Linux 41 (Forty One)
    CPU: (4) arm64 unknown
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.11.0 - /usr/bin/node
    npm: 10.9.0 - /usr/bin/npm <----- active
  npmPackages:
    @storybook/addon-docs: ^9.1.0-alpha.3 => 9.1.0-alpha.3
    @storybook/addon-onboarding: ^9.1.0-alpha.3 => 9.1.0-alpha.3
    @storybook/addon-webpack5-compiler-swc: ^3.0.0 => 3.0.0
    @storybook/react-webpack5: ^9.1.0-alpha.3 => 9.1.0-alpha.3
    storybook: ^9.1.0-alpha.3 => 9.1.0-alpha.3
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JReinhold**
Closes #31709

## What I did

1. Changed the global settings logic to only log a warning if it can't save the file, instead of throwing an error
2. Don't run global settings logic in CI
3. Added a utility to more resiliently check for optional, boolean environment variables, and a shortcut `isCI` that uses that.

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [x] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

## Greptile Summary

Improves error handling in read-only environments by replacing error throwing with warning logs and adding robust environment variable handling utilities.

- Added new utilities `isCI` and `optionalEnvToBoolean` in `code/core/src/common/utils/envs.ts` for consistent environment detection
- Modified `code/core/src/telemetry/storybook-metadata.ts` to skip global settings in CI environments
- Updated `code/lib/cli-storybook/src/bin/index.ts` to use warning logs instead of throwing errors when saving fails
- Fixed boolean logic in sandbox initiation to correctly disable dev mode in CI environments

### CODE REVIEW

File: code/core/src/telemetry/storybook-metadata.ts [hunk 1]
```diff
@@ -57,10 +57,10 @@ export const computeStorybookMetadata = async ({
   mainConfig?: StorybookConfig & Record<string, any>;
   configDir: string;
 }): Promise<StorybookMetadata> => {
-  const settings = await globalSettings();
+  const settings = process.env.CI === 'true' ? undefined : await globalSettings();
```
Comment (shilman) [inline code/core/src/telemetry/storybook-metadata.ts]: Seeing several different usages of `process.env.CI` in the codebase. This one seems like the safest to me:

https://github.com/storybookjs/storybook/blob/2155bb89597d0238c31b02b74937ae158dd8aaf8/code/core/src/telemetry/telemetry.ts#L48

**Review by shilman — APPROVED** [review]
Looks good with one minor nit

File: code/core/src/telemetry/storybook-metadata.ts (hunk 1 above)
Comment (JReinhold) [reply code/core/src/telemetry/storybook-metadata.ts]: `Boolean('false')` returns `true`, seems pretty bad to me.

Ie. `CI=false storybook dev` would make that thing become `true`.

Although `process.env.CI === 'true'` wouldn't support `CI=1`, but I'm not sure how many use that.

Comment (tmeasday) [reply code/core/src/telemetry/storybook-metadata.ts]: Should we use this https://github.com/storybookjs/storybook/blob/c2d246ce49e181fef17a86b2248f3ae538e5fb70/code/core/src/core-server/presets/common-preset.ts#L173-L188

Comment (shilman) [reply code/core/src/telemetry/storybook-metadata.ts]: Slight detour but can we also fix that across the codebase? If `Boolean('false')` returns `true` that's a bug. And there's a ton of other places that just refer to `process.env.CI` directly.

Comment (JReinhold) [reply code/core/src/telemetry/storybook-metadata.ts]: alright, I refactored it to export a utility from `storybook/internal/common` and used that everywhere we were reading a boolean env. please re-review @shilman or @tmeasday.

File: code/core/src/common/utils/envs.ts [hunk 2]
```diff
@@ -67,3 +67,24 @@ export const stringifyProcessEnvs = (raw: Record<string, string>): Record<string
...
+export const optionalEnvToBoolean = (input: string | undefined): boolean | undefined => {
+  if (input === undefined) {
+    return undefined;
+  }
+  if (input.toUpperCase() === 'FALSE' || input === '0') {
+    return false;
+  }
+  if (input.toUpperCase() === 'TRUE' || input === '1') {
+    return true;
+  }
```
Comment (tmeasday) [inline code/core/src/common/utils/envs.ts:79]: This is redundant right.. do we think it's better for brevity? Should this function be unit tested?

File: code/core/src/common/utils/envs.ts [hunk 3]
```diff
@@ -67,3 +67,24 @@ export const stringifyProcessEnvs = (raw: Record<string, string>): Record<string
...
+  return Boolean(input);
+};
+
+/**
+ * Consistently determine if we are in a CI environment
+ *
+ * Doing Boolean(process.env.CI) or !process.env.CI is not enough, because users might set CI=false
+ * or CI=0, which would be truthy, and thus return true in those cases.
+ */
+export const isCI = optionalEnvToBoolean(process.env.CI);
```
Comment (tmeasday) [inline code/core/src/common/utils/envs.ts]: Is it OK for this file to read `process.env`? It's never used in a scenario where one of those might be undefined?

**Review by tmeasday — APPROVED** [review]
I have a couple questions but looks good otherwise, good improvement.

File: code/core/src/common/utils/envs.ts (hunk 3 above)
Comment (JReinhold) [reply code/core/src/common/utils/envs.ts]: No the `storybook/internal/common` entrypoint is only usable in Node, not in the browser.

File: code/core/src/common/utils/envs.ts (hunk 2 above)
Comment (JReinhold) [reply code/core/src/common/utils/envs.ts:79]: Hmm you mean that the strings `'TRUE'` and `'1'` are truthy anyways, so `Boolean(input)` would return `true` anyway? I hadn't thought of that. I should remove it, that should also make it more obvious that `'blah'` also makes it `true`.

I can add tests.

**Comment by diagramatics** [comment]
👋 Just wanna bring this back since it was automatically closed. We do need this fix for our CI use case same as #31709 and it would be nice to have this also released to v8 as well since `globalSettings` was introduced in `v8.6.14`.

**Comment by valentinpalkovic** [comment]
@JReinhold Can you take another look and maybe resolve the conflicts?
