### PR TITLE
Bug: version switcher of compositions

### LINKED ISSUE #21505: [Bug]: Composition - version switcher doesn't close, no visual feedback
Related: https://github.com/storybookjs/storybook/issues/21534
Related: https://github.com/storybookjs/storybook/issues/5593

### Describe the bug

The version picker works, but is slow. it does not give feedback, it doesn't close

### To Reproduce

- Add the design system as a ref to `code/ui/.storybook/main.ts`
- Switch to a different version using the dropdown

### System

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ndelangen**
Closes https://github.com/storybookjs/storybook/issues/21505

## What I did

- I ensured the version switcher closes when you click outside
- I ensure the version switcher closes when you click another version
- I ensured the ref enters a loading state when a new version is being requested

## How to test

- add a ref

```
  refs: {
    'design-system': {
      title: 'Design System',
      url: 'https://master--5ccbc373887ca40020446347.chromatic.com',
    },
  },
```

... to `code/ui/.storybook/main.ts`

- start the ui storybook
- open the browser
- go to the ref
- change version

Expect that the version switcher closes
Expect that the ref enters the loading state
Expect that after some time, the ref shows again, and the same story is still selected. (assuming the same sotry existed in the other version)

### CODE REVIEW

File: code/lib/manager-api/src/lib/stories.ts [hunk 1]
```diff
@@ -146,13 +146,18 @@ export const transformStoryIndexToStoriesHash = (
...
+  }
+
+  let v4Index = index;
+
+  v4Index = v4Index.v === 2 ? transformStoryIndexV2toV3(v4Index as any) : v4Index;
+  v4Index = v4Index.v === 3 ? transformStoryIndexV3toV4(v4Index as any) : v4Index;
 
-  v4Index = index.v === 2 ? transformStoryIndexV2toV3(index as any) : index;
-  v4Index = index.v === 3 ? transformStoryIndexV3toV4(index as any) : index;
+  const finalIndex = v4Index as API_PreparedStoryIndex;
```
Comment (tmeasday) [inline code/lib/manager-api/src/lib/stories.ts:158]: Can we change these to be more sensibly named? It seems weird we have these any objects that really v2/3 indexes called `v4Index`? Don't we have types for the other indexes?

**Review by tmeasday — APPROVED** [review]
LGTM @ndelangen! I noticed that the ref still starts off in the error state before it loads the first time. I'm not sure if that was something this PR was targetting as well, but I thought I'd mention it.

File: code/lib/manager-api/src/lib/stories.ts (hunk 1 above)
Comment (ndelangen) [reply code/lib/manager-api/src/lib/stories.ts]: We do have types for them (I added the v2 type as best as I could, it wasn't very different from v3).

I could cast the the exact right type, but that didn't seem important, because casting doesn't add any type safety anyway.

**Comment by ndelangen** [comment]
> I noticed that the ref still starts off in the error state before it loads the first time. I'm not sure if that was something this PR was targeting as well, but I thought I'd mention it.

Will try to fix that in another PR.

**Review by Alexstriker360 — APPROVED** [review]
