### PR TITLE
Core: Honor BROWSER shell scripts before xdg-open

### LINKED ISSUE #32949: [Bug]: v10 new crash if `$BROWSER` points to `.sh` script (e.g. Codespaces)
### Describe the bug

Since upgrading to v10, Storybook is crashing on startup:

```
node:events:486
      throw er; // Unhandled 'error' event
      ^

Error: spawn xdg-open ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn xdg-open',
  path: 'xdg-open',
  spawnargs: [ 'http://localhost:6022/' ]
```

I can work around it with `--no-open`, but ideally that wouldn't be necessary.

What I've managed to work out so far:

- My `$BROWSER` value points to a shell script (ends with `.sh`), so `$BROWSER http://localhost:6022/` opens the local browser.
- `xdg-open` is not available in default container images. I could install it in our images, but that's a lot of bloat just to open a browser.
- v10 did change the browser opening code. It looks like the value of `$BROWSER` is ignored unless it ends with `.js`, which ours does not.
- When I compared this to the Vite browser opening code, which works fine for us, I found it also has a `.js` extension check. So I can't actually explain the difference in behaviour.

### Reproduction link

Just use storybook.new, then open in Codespaces (or any environment with `$BROWSER` pointing to a shell script and `xdg-open` not installed).

### Reproduction steps

_No response_

### System

```bash
System:
    OS: Linux 6.8 Ubuntu 24.04.3 LTS 24.04.3 LTS (Noble Numbat)
    CPU: (4) x64 AMD EPYC 7763 64-Core Processor
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 24.11.0 - ~/.volta/tools/image/node/24.11.0/bin/node
    Yarn: 4.9.4 - ~/.volta/tools/image/yarn/4.9.4/bin/yarn
    npm: 11.6.1 - ~/.volta/tools/image/node/24.11.0/bin/npm
    pnpm: 10.20.0 - ~/.volta/tools/image/pnpm/10.20.0/bin/pnpm <----- active
  npmPackages:
    @storybook/addon-a11y: catalog: => 10.0.2 
    @storybook/addon-docs: catalog: => 10.0.2 
    @storybook/addon-vitest: catalog: => 10.0.2 
    @storybook/react-vite: catalog: => 10.0.2 
    storybook: catalog: => 10.0.2
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by robbchar**
Closes #32949

## What I did

Modified the code to allow for more script types other than just .js. (As a disclaimer I can't test this in a reproduction in my current environment, Windows Home...)

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [x] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

As I said previously I can't test this in my local environment, Windows Home... I used Github Codespaces to repro the bug I just can't easily run against a fix.

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/publish.yml) or locally with `gh workflow run --repo storybookjs/storybook publish.yml --field pr=<PR_NUMBER>`_

## Summary by CodeRabbit

* **New Features**
  * Added shell-script support and broader script recognition for launching browsers (.sh, .js, .ts, .mjs, .cjs).
  * Exposed a new environment error type for clearer failure reporting.

* **Bug Fixes / Reliability**
  * Improved environment detection, unified execution flow, and consistent logging for script/browser launch failures; preserved existing platform-specific fallbacks.

* **Tests**
  * Added unit tests validating launch behavior across platforms and script vs. browser scenarios.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: code/core/src/core-server/utils/open-browser/opener.ts [hunk 1]
```diff
@@ -32,10 +32,15 @@ function getBrowserEnv() {
...
-    action = Actions.SCRIPT;
   } else if (value.toLowerCase() === 'none') {
     action = Actions.NONE;
+  } else if (
+    value.toLowerCase().endsWith('.js') ||
+    value.toLowerCase().endsWith('.mjs') ||
+    value.toLowerCase().endsWith('.cjs') ||
+    value.toLowerCase().endsWith('.sh')
+  ) {
+    action = Actions.SCRIPT;
```
Comment (Sidnioulz) [inline code/core/src/core-server/utils/open-browser/opener.ts]: Attn: this will cause a shell script to be passed on to a Node runtime. It will most likely cause bugs for other users.

**Review by Sidnioulz — CHANGES_REQUESTED** [review]

File: code/core/src/core-server/utils/open-browser/opener.ts (hunk 1 above)
Comment (robbchar) [reply code/core/src/core-server/utils/open-browser/opener.ts]: Yes, definitely, that was the bug though, right? https://github.com/storybookjs/storybook/issues/32949 My thought was that the reporter has that setup intentionally so that something happens in addition to the browser running.

Comment (Sidnioulz) [reply code/core/src/core-server/utils/open-browser/opener.ts]: They want it to be called, but probably not by a Node runtime. Rather, by a Shell runtime. `xdg-open` will not run in Node.

I believe the way to handle this would be to add an `Actions` type for shell and to spawn a shell interpreter. Which leads to the question: what operating systems are expected to have .sh? Should POSIX be assumed? Should the presence of `bash` be assumed?

Comment (robbchar) [reply code/core/src/core-server/utils/open-browser/opener.ts]: Good questions. They weren't specific with the use-case, I was thinking the user would deal with the actual running of the script and the things within the script. I _bet_ storybook doesn't really want to be in the business of figuring out OS's/shells that kind of thing. 

If we do want to go down that route then I feel like we could decide things like what's assumed, Though actually spawning off a node script, or trying to, seems like pretty good 'best effort' for something that is not the main purpose of storybook.

Comment (robbchar) [reply code/core/src/core-server/utils/open-browser/opener.ts]: Agree that passing .sh to Node would be wrong; we either need a shell branch or drop .sh from this path. Since Storybook likely doesn’t want to manage cross-platform shell execution, I propose we support Node-run scripts only and remove .sh here.

Comment (Sidnioulz) [reply code/core/src/core-server/utils/open-browser/opener.ts]: If the goal of the issue is to support xdg-open users, who rely on FreeDesktop.org standards (including most Linux and some BSD users), then surely it's fine to restrict `.sh` execution to POSIX compliant systems e.g. Linux, BSD, Mac and WSL. We can just call bash like we call node (even though users could prefer another JS interpreter).

**Comment by robbchar** [comment]
In addition to the CR changes I also moved the test file to be collocated with it's test file to be consistent with other test files.

File: code/core/src/core-server/utils/open-browser/opener.ts (hunk 1 above)
Comment (robbchar) [reply code/core/src/core-server/utils/open-browser/opener.ts]: Oh wait, so I said 'thumbs up' but I thought of something else. This is for what I would call 'xdg-open'-like users in that they don't have xdg-open but rather some script, that presumably acts in the same way. I'm still going to implement it to work POSIX systems.

File: code/core/src/core-server/utils/open-browser/opener.ts [hunk 2]
```diff
@@ -20,8 +21,28 @@ const Actions = Object.freeze({
...
+    return true;
+  }
+
+  try {
+    const version = require('fs').readFileSync('/proc/version', 'utf8').toLowerCase();
+    return version.includes('microsoft');
+  } catch {
+    return false;
+  }
+}
```
[the remark this answers is not in the document]
Comment (robbchar) [reply code/core/src/core-server/utils/open-browser/opener.ts]: I'm not in WSL, just straight bash, so I can't test this. That _seems_ like the right logic though but I don't want to make the change without being able to see if it works.

File: code/core/src/core-server/utils/open-browser/opener.test.ts [hunk 3]
```diff
@@ -0,0 +1,117 @@
...
+  });
+
+  afterEach(() => {
+    vi.restoreAllMocks();
+    process.env = originalEnv;
+    process.argv = originalArgv;
+  });
+
+  it('executes a node script when BROWSER points to a JS file', () => {
+    process.env.BROWSER = '/tmp/browser.js';
```
Comment (Sidnioulz) [inline code/core/src/core-server/utils/open-browser/opener.test.ts:38]: @ndelangen do we have an env mocking library already? I've used `mockedEnv` in the past. I'm concerned we're not cleaning up `env` here so this could lead to future tests on the same runner behaving differently.

File: code/core/src/core-server/utils/open-browser/opener.ts [hunk 4]
```diff
@@ -32,30 +37,59 @@ function getBrowserEnv() {
...
-      console.log();
-      return;
-    }
+  attachCloseHandler(child, scriptPath);
+  return true;
+}
+
+function executeShellScript(scriptPath: string, url: string) {
+  const extraArgs = process.argv.slice(2);
+  const child = spawn('/bin/sh', [scriptPath, ...extraArgs, url], {
```
Comment (Sidnioulz) [inline code/core/src/core-server/utils/open-browser/opener.ts]:
```suggestion
  const child = spawn('sh', [scriptPath, ...extraArgs, url], {
```

POSIX does not mandate use of `/bin/`, but Node.js spawn should lookup commands through `$PATH`, ensuring that `sh` is found regardless of install location.

File: code/core/src/core-server/utils/open-browser/opener.ts [hunk 5]
```diff
@@ -32,30 +37,59 @@ function getBrowserEnv() {
...
     // Default.
     action = Actions.BROWSER;
-  } else if (value.toLowerCase().endsWith('.js')) {
-    action = Actions.SCRIPT;
   } else if (value.toLowerCase() === 'none') {
     action = Actions.NONE;
+  } else if (
+    value.toLowerCase().endsWith('.js') ||
+    value.toLowerCase().endsWith('.mjs') ||
+    value.toLowerCase().endsWith('.cjs')
```
Comment (Sidnioulz) [inline code/core/src/core-server/utils/open-browser/opener.ts]: This is good and should be kept. We could even extend to `.ts` for Node 24+.

File: code/core/src/core-server/utils/open-browser/opener.ts [hunk 6]
```diff
@@ -149,22 +183,34 @@ function startBrowserProcess(
...
     }
+    case Actions.SHELL_SCRIPT: {
+      if (!value) {
+        throw new BrowserEnvError('BROWSER environment variable is not set.');
+      }
+      if (canRunShell) {
+        return executeShellScript(value, url);
+      }
+      return startBrowserProcess(browserTarget, url, args);
+    }
```
Comment (Sidnioulz) [inline code/core/src/core-server/utils/open-browser/opener.ts:231]: If I understand correctly what was going on with the reported bug, `xdg-open` used to gracefully handle Shell scripts (likely via the shebang), which is why we didn't need that.

I don't mind more explicit shell script handling but I don't know if we still need it. Another approach would be to rename Actions.BROWSER to Actions.OPEN and keep the code paths joined as they used to be before 10.0.

@ndelangen WDYT?

**Review by Sidnioulz — COMMENTED** [review]
Thanks @robbchar! Even though we were all looking at the wrong thing initially, there are a bunch of improvements in your PR that I'd definitely like to see merged.

See my comments on the issue and my other PR for full context :) I think we can focus your PR on adding tests and making JS handling more robust, and let the other one handle `xdg-open` and shell scripting.

**Comment by Sidnioulz** [comment]
Hey @robbchar!

Now that https://github.com/storybookjs/storybook/pull/33325 is merged, could you please rebase your PR and refactor it to focus on detection Nodejs scripts and calling the Node runtime for them?

Thanks :pray:

**Comment by robbchar** [comment]
@Sidnioulz I'm sorry but I'm a bit confused should I be doing something like this:

```typescript
if (hasNodeShebang(file)) {
  spawn(process.execPath, [file])
} else {
  open(file)
}
```

?

thanks

**Comment by Sidnioulz** [comment]
> @Sidnioulz I'm sorry but I'm a bit confused should I be doing something like this:
> 
> ```ts
> if (hasNodeShebang(file)) {
>   spawn(process.execPath, [file])
> } else {
>   open(file)
> }
> ```
> 
> ?
> 
> thanks

I think you can skip that, as `xdg-open` is able to do it and we now know for sure that xdg-open is called by the package on all platforms :)

**Review by Sidnioulz — APPROVED** [review]
We've done some testing with @mrginglymus (thanks!) for Windows support of `sh`. Spawning works only on WSL, which returns a `linux` `process.platform`, so the condition used in the code is good.

Rather than call a browser and fail, I've taken the liberty to add a commit to your code to explicitly fail when running Shell on Windows. Specifically, I tell users to use WSL so they have a workaround available.

I've changed types a little bit too so we can avoid adding `if`'s just to make TypeScript happy.

**Comment by robbchar** [comment]
@Sidnioulz Those changes are fine, thanks :) So, is there anything else that I should do? Sorry, I 'looked away' for a bit but I'm back now so more available. I know you approved but if there _is_ something I should do please let me know. thanks again

**Comment by Sidnioulz** [comment]
> @Sidnioulz Those changes are fine, thanks :) So, is there anything else that I should do? Sorry, I 'looked away' for a bit but I'm back now so more available. I know you approved but if there _is_ something I should do please let me know. thanks again

You have done everything you needed to! Thanks again for your contribution! I'm waiting on core team members to be back from vacation to merge the PR.

File: code/core/src/core-server/utils/open-browser/opener.test.ts (hunk 3 above)
Comment (ndelangen) [reply code/core/src/core-server/utils/open-browser/opener.test.ts:38]: No We do not have a unique library for that as far as I am aware, but you should be able to import `process` from `node:process` and mock it that way, like any other module.

If the code is local, that is...

**Comment by ndelangen** [comment]
@robbchar Thank you for this PR, I think we're close to merging, but there a request I have.

Could you share as much details as possible on the steps to manually reproduce?
I understand you cannot run it locally, but you mention you did something on codespaces? Can you describe that procedure so we can later verify this fix?

**Comment by robbchar** [comment]
Hello,

Sorry for the delayed reply,

The original repro was done in GitHub Codespaces via an “Open in Codespaces” flow from storybook.new, which no longer exists, so it’s no longer a one-click setup. I was able to recreate the environment manually, and here’s the process I used.

Codespaces repro steps

1. Create a Codespace from the storybookjs/storybook repo.
2. Switch to Node 18+ and enable Yarn 4:
```bash
nvm install 20
nvm use 20
corepack enable
corepack prepare yarn@4.10.3 --activate
```

3. Create a sandbox using Storybook’s internal task generator:
```bash
sandbox --template react-vite/default-ts
(I ran this interactively; there may be a more direct non-interactive invocation, but this matches what I did.)
4. Set $BROWSER to a script and ensure xdg-open is not present (in the default Codespaces image it isn’t):
```bash
#!/usr/bin/env bash
echo "invoked: $@" >> /tmp/browser-invocations.log
```
Then
```bash
chmod +x /path/to/script
export BROWSER=/path/to/script
```
5. Run Storybook from the generated sandbox:
```bash
cd ../storybook-sandboxes/react-vite-default-ts
yarn storybook
```
7. It currently works for me, but the comment above says it will so I'm not surprised :)

Happy to provide more details or try additional variations if that helps.

Thanks!
