### PR TITLE
Core: Add error categorization framework

### LINKED ISSUE #23511: Create error categorization framework
There will be categories of errors (which will grow over time) and a base error class, which will hold metadata such as category, code and message. This will be useful when going through these errors in telemetry:

```tsx
enum Category {
  INIT = 'I',
  RUNTIME = 'R',
  COMPILE = 'C',
  // ... and many more
}

// StorybookError, to keep metadata in its object which can be 
class StorybookError extends Error {
  constructor(public category: Category, public code: string, message: string) {
    super(message);
  }
}
```

Errors would all be objects created via a factory function, which could take care of message formatting, would provide a flag to send telemetry, a flag for documentation, and could be used to display warnings without having to instantiate errors:

```tsx
function create<T, C extends string>({
  category,
  code,
  template,
  documentation,
  telemetry,
}: {
  category: Category;
  code: C;
  template(data: T): string;
  // either true or a link to a specific documentation
  documentation?: boolean | string;
  telemetry?: boolean;
}): {
  code: C;
  error: (data: T) => StorybookError;
  message: (data: T) => string;
} {
  const page =
    documentation === true
      ? `https://storybook.js.org/error/${code}`
      : typeof documentation === 'string'
      ? documentation
      : undefined;
  const message = documentation
    ? (data: T) =>
        `SB_${category}_${code} - ${template(data)}\n\nMore info: ${page}`
    : (data: T) => `SB_${category}_${code} - ${template(data)}`

  const error = (data: T) => {
    // telemetry would be injected globally and accessed to send errors if needed
    if (telemetry && globalThis.telemetry) {
      globalThis.telemetry({ code, category, data, message: message(data) });
    }
    return new StorybookError(category, code, message(data));
  };
  return { code, error, message };
}
```

Example of the creation of errors:

```tsx
// --- definition --- //

export const INSTALL_FAILURE = create({
  category: Category.INIT,
  code: '0001',
  // if linked is true, append code in sb errors page
  linked: true,
  template: ({ reason }: { reason: string }) =>
    `Failed to install: ${reason}`,
});

export const MISSING_MAIN_JS = create({
  category: Category.COMPILE,
  code: '0001',
  // if linked is a string, use it instead of the default /error/<code> url
  linked: 'https://storybook.js.org/docs/faq#common-issue-and-how-to-solve-it',
  template: ({ location }: { location: string }) =>
    `Missing main.js file at ${location}`,
});
```

Example of usage:

```tsx
// --- usage --- //

if ('we detected a problem, ow no!') {
  // can be used in warning messages without having to instantiate the error
  const foo = INSTALL_FAILURE.error({ reason: 'Unsupported Vite version.' });

  // Failed to install: Unsupported Vite version. More info https://storybook.js.org/error/I0001
  console.warn(foo.message);
}

if ('we detected a problem, ow no!') {
  // Missing main.js file at xyz. More info https://storybook.js.org/docs/faq#common-issue-and-how-to-solve-it
  throw MISSING_MAIN_JS.error({
    location: 'main.js',
  });
}
```

[Prototype](https://stackblitz.com/edit/vitejs-vite-m5ynr7?file=src/main.ts)

### PR DESCRIPTION
**Pull request by yannbf**
Closes #23511 

## What I did

This PR proposes a new way to write and throw errors in Storybook.

For more details, please check [the README included in this PR](https://github.com/storybookjs/storybook/blob/yann/error-categorization-framework/code/lib/core-events/src/errors/README.md).

## Checklist

- [x] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [x] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [x] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [x] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "build", "documentation", "maintenance", "dependencies", "other"]`

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

File: code/lib/core-server/src/presets/common-preset.ts [hunk 1]
```diff
@@ -335,5 +336,22 @@ export const experimental_serverChannel = async (
     }
   );
 
+  channel.on(SEND_TELEMETRY_EVENT, async ({ payload, isError }) => {
```
Comment (yannbf) [inline code/lib/core-server/src/presets/common-preset.ts:339]: SEND_TELEMETRY_ERROR instead.

File: code/lib/core-events/src/errors/preview-errors.ts [hunk 2]
```diff
@@ -0,0 +1,22 @@
+import dedent from 'ts-dedent';
+import { defineError } from './define-error';
+
+export enum Category {
+  PREVIEW_API = 'PREVIEW_API',
+}
+
+export const MISSING_STORY_AFTER_HMR = defineError({
```
Comment (yannbf) [inline code/lib/core-events/src/errors/preview-errors.ts:8]: CLIENT + SERVER errors instead

File: code/lib/core-events/src/errors/README.md [hunk 3]
```diff
@@ -0,0 +1,147 @@
...
+
+### Return Value
+
+The function returns an object containing the following properties:
+
+| Name           | Type                                | Description                                                                                    |
+| -------------- | ----------------------------------- | ---------------------------------------------------------------------------------------------- |
+| code           | `number`                            | The numeric code for the defined error.                                                        |
+| category       | `Category`                          | The category of the defined error.                                                             |
+| error          | `(...data: Data) => StorybookError` | A function that generates the error message based on the provided template and data arguments. |
```
Comment (kylegach) [inline code/lib/core-events/src/errors/README.md:57]: Unless you think the bold formatting in some of the table descriptions is super key to understanding, I would argue that the parameters and return value tables' information would be better learned as JSDoc comments in the signature type:

```suggestion
### API

```typescript
export function defineError<Template extends string | ((...data: any[]) => string)>({
  /** The category to which the error belongs. */
  category: Category;
  /** The numeric code for the error. */
  code: number;
  /** A properly written error message or a function that takes data arguments and returns an error, for dynamic messages message. */
  template: Template;
  /** Optional. Should be set to `true` **if the error is documented on the Storybook website**. If defined as string, it should be a custom documentation link. */
  documentation?: boolean | string;
  /** Optional. If set to `true`, telemetry will be used to send errors. **Only for client based errors**. */
  telemetry?: boolean;
}): {
  /** The numeric code for the defined error. */
  code: number;
  /** The category of the defined error. */
  category: Category;
  /** A function that generates the error message based on the provided template and data arguments. */
  error: (...data: Data) => StorybookError;
}
```
```

File: code/lib/core-events/src/errors/README.md [hunk 4]
```diff
@@ -0,0 +1,147 @@
...
+  code: 2,
+  template: (fieldName: string) => `Invalid value provided for ${fieldName}.`,
+  documentation: 'https://some-custom-documentation.com/validation-errors',
+});
+
+// "[SB_Generic_0001] Something went wrong. Please try again later.
+throw simpleError.error();
+
+// "[SB_Validation_0002] Invalid value provided for username. More info: https://some-custom-documentation.com/validation-errors"
+throw dataError.error('username');
```
Comment (kylegach) [inline code/lib/core-events/src/errors/README.md:83]: Nit: Usually comments illustrating output come _after_ the code that produces them:

```suggestion
throw simpleError.error();
// "[SB_Generic_0001] Something went wrong. Please try again later.

throw dataError.error('username');
// "[SB_Validation_0002] Invalid value provided for username. More info: https://some-custom-documentation.com/validation-errors"
```

File: code/lib/core-events/src/errors/README.md [hunk 5]
```diff
@@ -0,0 +1,147 @@
...
+```
+
+## How to write a proper error message
+
+Writing clear and informative error messages is crucial for effective debugging and troubleshooting. A well-crafted error message can save developers and users valuable time. Consider the following guidelines:
+
+- **Be clear and specific:** Provide straightforward error messages that precisely describe the issue.
+- **Include relevant context:** Add details about the error's origin and relevant context to aid troubleshooting.
```
Comment (kylegach) [inline code/lib/core-events/src/errors/README.md:91]: Should we expand this one to recommend including context specific to a user's setup? e.g. the Long example below could be even more helpful as:

```
Couldn't find story matching 'xyz' after HMR.
  - Did you just rename a story?
  - Did you remove it from your CSF file, `Card.stories.ts`?
  - Are you sure a story with the id `component--xyz` exists?
  - Please check the stories field of your main.js config. Will `'../src/**/*.stories.@(js|jsx|mjs|ts|tsx)'` match your CSF file?
  - Also check the browser console and terminal for potential error messages.
```

File: code/lib/core-events/src/errors/README.md [hunk 6]
```diff
@@ -0,0 +1,147 @@
...
+```
+
+Short:
+```
+Failed to initialize Storybook.
+
+Do you have an error in your \`preview.js\`? Check your Storybook's browser console for errors.
+```
+
+❌ Here are a few unrecommended examples:
```
Comment (kylegach) [inline code/lib/core-events/src/errors/README.md:125]: Anti-examples are just as useful as good ones! ❤️

**Review by kylegach — COMMENTED** [review]
I only reviewed the README, but I'm loving this work! Great job, Yann! 👏

File: code/lib/core-events/src/errors/README.md (hunk 4 above)
Comment (yannbf) [reply code/lib/core-events/src/errors/README.md]: thanks!

File: code/lib/core-events/src/errors/README.md (hunk 3 above)
Comment (yannbf) [reply code/lib/core-events/src/errors/README.md]: Hey @kylegach I have reworked this PR quite a bit and this documentation part has changed (though similar in concept). Could you please recheck?

File: code/lib/core-events/src/errors/README.md (hunk 5 above)
Comment (yannbf) [reply code/lib/core-events/src/errors/README.md:120]: Great point! I updated the example with a more realistic scenario, and also improved the actual error message based on this feedback!

File: scripts/eslint-plugin-local-rules/no-duplicated-error-codes.js [hunk 7]
```diff
@@ -0,0 +1,50 @@
+module.exports = {
+  meta: {
+    type: 'problem',
+    docs: {
+      description: 'Ensure unique error codes per category in the same file',
+      category: 'Best Practices',
+      recommended: true,
+      url: 'https://example.com/rules/unique-error-codes',
```
Comment (yannbf) [inline scripts/eslint-plugin-local-rules/no-duplicated-error-codes.js:8]:
```suggestion
```

File: code/lib/core-server/src/presets/common-preset.ts [hunk 8]
```diff
@@ -329,5 +330,17 @@ export const experimental_serverChannel = async (
     }
   );
 
+  channel.on(SEND_TELEMETRY_ERROR, async (error) => {
```
Comment (yannbf) [inline code/lib/core-server/src/presets/common-preset.ts:333]:
```suggestion
  channel.on(TELEMETRY_ERROR, async (error) => {
```

File: code/lib/core-events/src/errors/server-errors.ts [hunk 9]
```diff
@@ -0,0 +1,45 @@
...
+  NODE_LOGGER = 'NODE-LOGGER',
+  TELEMETRY = 'TELEMETRY',
+  BUILDER_MANAGER = 'BUILDER-MANAGER',
+  BUILDER_VITE = 'BUILDER-VITE',
+  BUILDER_WEBPACK5 = 'BUILDER-WEBPACK5',
+  SOURCE_LOADER = 'SOURCE-LOADER',
+  POSTINSTALL = 'POSTINSTALL',
+  DOCS_TOOLS = 'DOCS-TOOLS',
+  CORE_WEBPACK = 'CORE-WEBPACK',
+}
```
Comment (kasperpeulen) [inline code/lib/core-events/src/errors/server-errors.ts:30]: I'm thinking that this `category` should not be a field of `StorybookError`, but should be should be passed to telemetry at the point where the error is caught.

For example, a function such as `readConfig` from `@storybook/csf-tools` will throw all kind of errors, but we likely want to know in telemetry more about the context where this function is called. As it can be called in `codemods`, the `eslint-plugin`, `build`, `init`, `dev` etc.

Also, I'm kind of thinking that the boolean `telemetry` should not be part of the `StorybookError` class, but is something that is also `context` dependent. As for example, I don't think we might not want to send telemetry for the eslint plugin, as it can be used independent of storybook (for other integrations)?

Maybe we should just maintain a list of `code`'s that we want telemetry for? 

I guess you could say that `telemetry` is just a different concern all together than throwing errors. For example, when `composeStories` outside of storybook, or by other integrators, it is kind of weird that the `Error` that we throw contains a `telemetry` boolean.

File: code/lib/core-events/src/errors/storybook-error.ts [hunk 10]
```diff
@@ -0,0 +1,71 @@
...
+    this.fullCode = this.name;
+  }
+
+  get paddedCode() {
+    return this.code.toString().padStart(4, '0');
+  }
+
+  /**
+   * Overrides the default `Error.name` property in the format: SB_<CATEGORY>_<CODE>.
+   * @returns {string} Full error name.
```
Comment (kasperpeulen) [inline code/lib/core-events/src/errors/storybook-error.ts:50]: I think you might want to remove that, as it might override the actual return type which is a template string:
`SB_${this['category']}_${this['code']}`

File: code/ui/manager/src/runtime.ts [hunk 11]
```diff
@@ -55,12 +58,40 @@ class ReactProvider extends Provider {
...
+    error.name = originalError.name || error.name;
+  }
+  error.category = error.category || 'UNCATEGORIZED';
+
+  return error;
+}
+
+// handle all uncaught errors at the root of the application and log to telemetry
+globalThis.addEventListener('error', (args) => {
+  const error = preprocessError(args.error || args);
```
Comment (yannbf) [inline code/ui/manager/src/runtime.ts:87]: @ndelangen @shilman please check. I decided to filter errors in preview by the `fromStorybook` property, as the error handler will include user code errors, but for this manager runtime, I thought we should send all errors, as, supposedly, they are happening from the Storybook app. If there is no category in the error object, `UNCATEGORIZED` will be added

File: code/lib/core-server/src/withTelemetry.ts [hunk 12]
```diff
@@ -85,13 +85,31 @@ export async function sendTelemetryError(
         error instanceof Error,
         'The error passed to sendTelemetryError was not an Error, please only send Errors'
       );
+
+      let storybookErrorProperties = {};
```
Comment (yannbf) [inline code/lib/core-server/src/withTelemetry.ts:89]: @ndelangen @shilman please check

File: code/ui/manager/src/runtime.ts [hunk 13]
```diff
@@ -55,12 +58,40 @@ class ReactProvider extends Provider {
...
 Object.keys(Keys).forEach((key: keyof typeof Keys) => {
   global[Keys[key]] = values[key];
 });
+
+globalThis.sendTelemetryError = (error) => {
+  const channel = globalThis.__STORYBOOK_ADDONS_CHANNEL__;
+  channel.emit(TELEMETRY_ERROR, error);
+};
+
+function preprocessError(originalError: Error) {
```
Comment (shilman) [inline code/ui/manager/src/runtime.ts:71]: Do we need to do this in another places?

Comment (yannbf) [reply code/ui/manager/src/runtime.ts:71]: no, basically just in `manager` because we assume that every error that occurs there is related to Storybook, but as we are catching all errors (instead of only the ones with error.fromStorybook), we should be mindful of many error shapes which involve circular references to the window object

File: code/ui/manager/src/runtime.ts [hunk 14]
```diff
@@ -63,16 +64,28 @@ Object.keys(Keys).forEach((key: keyof typeof Keys) => {
...
+  }
+) {
+  let error = originalError;
+
+  if (!originalError.fromStorybook) {
+    error = new UncaughtManagerError(originalError);
+  }
+
   // DOM manipulation errors and other similar errors are not serializable as they contain
   // circular references to the window object. If that's the case, we make a simplified copy
```
[the remark this answers is not in the document]
Comment (yannbf) [reply code/ui/manager/src/runtime.ts:83]: it was not a problem when stringifying, but it was a problem when parsing it back

**Review by ndelangen — APPROVED** [review]
