### PR TITLE
CLI: Upgrade non-core storybook packages better

### LINKED ISSUE #21287: CLI: upgrade command does not upgrade addon-coverage
### Describe the bug

From all my Storybook dependencies, the npx sb@next upgrade command did not detect nor upgrade @storybook/addon-coverage, which caused the following issue as the current installed version did not support Storybook 7:

```
WARN Failed to load preset: {"type":"presets","name":"/Users/yannbraga/Dev/mealdrop/node_modules/@storybook/addon-coverage/preset.js"} on level 1
ERR! ReferenceError: regeneratorRuntime is not defined
ERR! at <anonymous> (/Users/yannbraga/Dev/mealdrop/node_modules/@storybook/addon-coverage/dist/cjs/preset.js:33:46)
```

### To Reproduce

https://github.com/yannbf/mealdrop

### System

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by shilman**
Closes #21287 

## What I did

Storybook packages outside the monorepo were not getting upgraded properly with the `--prerelease` flag.

This PR changes the upgrade process to:
- [x] Don't hardcode the monorepo packages, use `versions.ts` instead
- [x] Upgrade storybook-related packages even if they don't have a `@next` dist tag, but filter out canary versions

## How to test

- [ ] See attached unit tests
- [ ] Using the the CLI from this branch, `upgrade --prerelease` a project that contains older versions of non-monorepo packages that contain the string `storybook`, e.g. `storybook-addon-designs`, `@storybook/addon-coverage`, etc.

### CODE REVIEW

File: code/lib/cli/src/upgrade.ts [hunk 1]
```diff
@@ -25,32 +26,8 @@ export const getStorybookVersion = (line: string) => {
...
-  '@storybook/storybook-deployer',
-  '@storybook/test-runner',
-  '@storybook/testing-library',
-  '@storybook/testing-react',
-];
 export const isCorePackage = (pkg: string) =>
-  pkg.startsWith('@storybook/') &&
-  !pkg.startsWith('@storybook/preset-') &&
-  !excludeList.includes(pkg);
+  coreVersions[pkg as keyof typeof coreVersions] !== undefined;
```
Comment (yannbf) [inline code/lib/cli/src/upgrade.ts:30]: good one! you could do `Object.keys(coreVersions).includes(pkg)` as well

**Review by yannbf — APPROVED** [review]
LGTM!!

**Comment by yannbf** [comment]
FYI tests are failing on Windows:

```
  ● getProjectRoot › should return the root directory containing a .yarn directory if there is no .git or .svn directory

    expect(received).toBe(expected) // Object.is equality

    Expected: "/path/to"
    Received: "\\path\\to"

      66 |     );
      67 |
    > 68 |     expect(getProjectRoot()).toBe('/path/to');
         |                              ^
      69 |   });
      70 | });
      71 |

      at Object.toBe (src/utils/__tests__/paths.test.ts:68:30)
```
