### PR TITLE
Addon Vitest: Fix broken docs links

### LINKED ISSUE #31441: [Bug]: Test addon - Broken links
### Describe the bug

Related to #31197 

When users attempt to run the Storybook test add-on, they encounter broken links in the documentation. Specifically, if they encounter a bug in their tests and try to navigate to the documentation for the test addon, they are redirected to a 404 page. This critical issue prevents users from accessing the documentation and understanding how to use the test addon effectively.
See the following recording showcasing the issue:

https://github.com/user-attachments/assets/7cbc306a-4bf5-484c-add1-87e89e213a3e

### Reproduction link

https://new-storybook.netlify.app/

### Reproduction steps

1. Create a new project
2. Run `npx storybook@next init` to install the latest beta version of Storybook
3. When prompted select the following option
    - Recommended: Component dev, docs, test
4. Add a component that could potentially break tests
5. Run tests via the widget
6. Observe that the links in the documentation are broken and redirect to a 404 page

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 15.0.1
    CPU: (8) arm64 Apple M3
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
    Yarn: 4.9.1 - /usr/local/bin/yarn <----- active
    npm: 10.5.2 - ~/.nvm/versions/node/v20.13.1/bin/npm
  Browsers:
    Chrome: 136.0.7103.93
    Edge: 136.0.3240.64
    Safari: 18.0.1
  npmPackages:
    @storybook/addon-a11y: ^9.0.0-beta.11 => 9.0.0-beta.11
    @storybook/addon-docs: 9.0.0-beta.11 => 9.0.0-beta.11
    @storybook/addon-svelte-csf: ^5.0.0 => 5.0.0
    @storybook/addon-vitest: ^9.0.0-beta.11 => 9.0.0-beta.11
    @storybook/svelte-vite: 9.0.0-beta.11 => 9.0.0-beta.11
    msw-storybook-addon: ^2.0.3 => 2.0.4
    storybook: 9.0.0-beta.11 => 9.0.0-beta.11
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kylegach**
Closes #31441

## What I did

- Change `writing-tests/test-addon` to `writing-tests/vitest-addon`
- Add `next` version specifier to docs URLs, to ensure it always points at most up-to-date docs
    - In latest docs, the page is still `test-addon`

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [x] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [x] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [x] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

## Greptile Summary

This PR updates documentation links in the Vitest addon to fix broken URLs and ensure they point to the correct documentation pages.

- Updates all documentation paths from `writing-tests/test-addon` to `writing-tests/vitest-addon` across multiple files
- Adds `next` version specifier to documentation URLs to ensure they point to latest docs
- Updates `DOCUMENTATION_LINK` constant in `constants.ts` for consistent URL references
- Modifies postinstall script to use updated documentation links
- Updates test files and templates to reflect new documentation paths

The changes are straightforward and focused on fixing the broken documentation links reported in issue #31441, where users encountered 404 errors when trying to access the test addon documentation.

### CODE REVIEW

File: code/addons/vitest/src/postinstall.ts [hunk 1]
```diff
@@ -80,7 +80,7 @@ export default async function postInstall(options: PostinstallOptions) {
             name: 'migrateToNextjsVite',
             message: dedent`
             The addon requires the use of @storybook/nextjs-vite to work with Next.js.
-            https://storybook.js.org/docs/writing-tests/test-addon#install-and-set-up
+            https://storybook.js.org/docs/next/${DOCUMENTATION_LINK}#install-and-set-up
```
Comment (kylegach) [inline code/addons/vitest/src/postinstall.ts:83]: Should this use `api.getDocsUrl` (as done [here](https://github.com/storybookjs/storybook/blob/next/code/addons/vitest/src/components/GlobalErrorModal.tsx#L82-L86))?

**Comment by kylegach** [comment]
The CI failures seem unrelated?

File: code/addons/vitest/src/postinstall.ts (hunk 1 above)
Comment (yannbf) [reply code/addons/vitest/src/postinstall.ts:83]: this is a node file and can't use the storybook API unfortunately

**Review by jonniebigodes — APPROVED** [review]
Left one item for you to look into when you can. Approving to unblock

File: code/addons/vitest/src/constants.ts [hunk 2]
```diff
@@ -13,7 +13,7 @@ export const TEST_PROVIDER_ID = `${ADDON_ID}/test-provider`;
 export const STORYBOOK_ADDON_TEST_CHANNEL = 'STORYBOOK_ADDON_TEST_CHANNEL';
 
 export const TUTORIAL_VIDEO_LINK = 'https://youtu.be/Waht9qq7AoA';
-export const DOCUMENTATION_LINK = 'writing-tests/test-addon';
+export const DOCUMENTATION_LINK = 'writing-tests/vitest-addon';
```
[the remark this answers is not in the document]
Comment (kylegach) [reply code/addons/vitest/src/constants.ts:16]: Good catch.

I'll merge this first. Then update these links again in #31172.
