### PR TITLE
UI: Update deprecated Icons with the new @storybook/icons in addons

### LINKED ISSUE #25760: [Bug]: deprecation warnings when older icons are being used
### Describe the bug

**Project:** MealDrop
**Version:** 8.0.0-alpha.14
**Bug/feedback:**

It seems that not all parts of Storybook are using the new icons, so the browser console gets many deprecation warnings when older icons are being used such as:

```js
Use of deprecated props in the button component detected, see the migration notes at https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#new-ui-and-props-for-button-and-iconbutton-components

Use of the deprecated Icons (check) component detected. Please use the @storybook/icons component directly. For more informations, see the migration notes at https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#icons-is-deprecated

Use of the deprecated Icons (play) component detected. Please use the @storybook/icons component directly. For more informations, see the migration notes at https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#icons-is-deprecated
```

**Scenario 1:**

When using addon-interactions and accessing a story that contains a play function. The addon interactions panel seems to be using old icons (check, play).

**Scenario 2:**

When creating your own toolbar ([from official docs](https://storybook.js.org/docs/essentials/toolbars-and-globals#global-types-and-the-toolbar-annotation)), you can define icons via their name like so:

```ts
const preview = {
  //... other properties,
  globalTypes: {
    theme: {
      name: 'Theme',
      description: 'Theme for the components',
      defaultValue: 'light',
      toolbar: {
        icon: 'circlehollow',
        items: [
          { value: 'light', icon: 'circlehollow', title: 'light' },
          { value: 'dark', icon: 'circle', title: 'dark' },
          { value: 'side-by-side', icon: 'sidebar', title: 'side by side' },
        ],
      },
    },
  },
};

export default preview;
```

When clicking on the newly created toolbar button, you will get as many warnings as the amount of icons you create:
image

### To Reproduce

1. Go to https://stackblitz.com/edit/github-csg7tu
2.1 Open the `Page - Logged In` story
2.2 Click on the circle toolbar
3. See the warnings

### System

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cdedreuille**
Closes https://github.com/storybookjs/storybook/issues/25760

## What I did

As part of Storybook 8 we are transitioning to a new package for icons. In this PR we are transforming the `<Icons />` component into the new icons from `@storybook/icons`.

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

File: code/addons/interactions/src/components/StatusIcon.tsx [hunk 1]
```diff
@@ -1,51 +1,35 @@
...
+      {status === CallStates.DONE && <CheckIcon color={theme.color.positive} />}
+      {status === CallStates.ERROR && <StopAltIcon color={theme.color.negative} />}
+      {status === CallStates.ACTIVE && <PlayIcon color={theme.color.secondary} />}
+      {status === CallStates.WAITING && (
+        <WarningContainer>
+          <CircleIcon color={transparentize(0.5, '#CCCCCC')} size={6} />
+        </WarningContainer>
+      )}
+    </>
   );
```
Comment (JReinhold) [inline code/addons/interactions/src/components/StatusIcon.tsx:34]: I feel like this would be much cleaner with a switch statement, something like

```suggestion
  switch (status) {
	  case CallStates.DONE: {
	    return <CheckIcon color={theme.color.positive} />;
	  }
	  case CallStates.ERROR: {
	    return <StopAltIcon color={theme.color.negative} />;
	  }
	  case CallStates.ACTIVE: {
	    return <PlayIcon color={theme.color.secondary} />;
	  }
	  case CallStates.WAITING: {
	    return (
	      <WarningContainer>
	        <CircleIcon color={transparentize(0.5, '#CCCCCC')} size={6} />
	      </WarningContainer>
	    );
	  }
	  default: {
	    return null; //log warning?
	  }
  }

```

File: code/addons/jest/package.json [hunk 2]
```diff
@@ -54,6 +54,7 @@
   },
   "dependencies": {
     "@storybook/global": "^5.0.0",
+    "@storybook/icons": "^1.2.3",
```
Comment (JReinhold) [inline code/addons/jest/package.json:57]: needs to be in `devDependencies`

File: code/ui/components/src/components/icon/icon.tsx [hunk 3]
```diff
@@ -24,18 +24,27 @@ export interface IconsProps extends ComponentProps<typeof Svg> {
...
-export const Icons = ({ icon, useSymbol, ...props }: IconsProps) => {
-  deprecate(
-    `Use of the deprecated Icons ${
-      `(${icon})` || ''
-    } component detected. Please use the @storybook/icons component directly. For more informations, see the migration notes at https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#icons-is-deprecated`
-  );
+export const Icons = ({
+  icon,
+  useSymbol,
+  removeDeprecateWarning = false,
```
Comment (JReinhold) [inline code/ui/components/src/components/icon/icon.tsx:37]: I'd suggest `__suppressDeprecationWarning` instead.

1. the `__` prefix highlights that this is a prop only intended for internal use
2. `remove` is a destructive action, we're not really removing it everywhere, we're just suppressing it here.

File: docs/addons/writing-addons.md [hunk 4]
```diff
@@ -98,10 +98,11 @@ Going through the code blocks in sequence:
...
 
-import { Icons, IconButton } from '@storybook/components';
+import { IconButton } from '@storybook/components';
+import { LightningIcon } from '@storybook/icons';
 ```
 
-The [`useGlobals`](./addons-api.md#useglobals) and [`useStorybookApi`](./addons-api.md#usestorybookapi) hooks from the `manager-api` package are used to access the Storybook's APIs, allowing users to interact with the addon, such as enabling or disabling it. The `Icons` and `IconButtons` components from the [`@storybook/components`](https://www.npmjs.com/package/@storybook/components) package render the icons and buttons in the toolbar.
+The [`useGlobals`](./addons-api.md#useglobals) and [`useStorybookApi`](./addons-api.md#usestorybookapi) hooks from the `manager-api` package are used to access the Storybook's APIs, allowing users to interact with the addon, such as enabling or disabling it. The `IconButton` component from the [`@storybook/components`](https://www.npmjs.com/package/@storybook/components) package render the buttons in the toolbar. Any icon from the [`@storybook/icons`](https://storybook.js.org/docs/react/api/icons) package can be used.
```
Comment (JReinhold) [inline docs/addons/writing-addons.md:105]: @kylegach input here?

**Review by JReinhold — COMMENTED** [review]
code looks great! 🔥 I haven't tested the functionality yet though, I will soon.

File: code/addons/interactions/src/components/StatusIcon.tsx (hunk 1 above)
Comment (cdedreuille) [reply code/addons/interactions/src/components/StatusIcon.tsx:34]: Thanks @JReinhold. Much cleaner indeed

File: code/addons/jest/package.json (hunk 2 above)
Comment (cdedreuille) [reply code/addons/jest/package.json:57]: Done

File: code/ui/components/src/components/icon/icon.tsx (hunk 3 above)
Comment (cdedreuille) [reply code/ui/components/src/components/icon/icon.tsx]: Done

File: docs/addons/writing-addons.md (hunk 4 above)
Comment (kylegach) [reply docs/addons/writing-addons.md:105]: There's significant changes needed here. I'll push a commit in a bit.

File: docs/addons/writing-addons.md [hunk 5]
```diff
@@ -97,11 +97,13 @@ Going through the code blocks in sequence:
...
 
 import { useGlobals, useStorybookApi } from '@storybook/manager-api';
-
-import { Icons, IconButton } from '@storybook/components';
+import { IconButton } from '@storybook/components';
+import { LightningIcon } from '@storybook/icons';
 ```
 
-The [`useGlobals`](./addons-api.md#useglobals) and [`useStorybookApi`](./addons-api.md#usestorybookapi) hooks from the `manager-api` package are used to access the Storybook's APIs, allowing users to interact with the addon, such as enabling or disabling it. The `Icons` and `IconButtons` components from the [`@storybook/components`](https://www.npmjs.com/package/@storybook/components) package render the icons and buttons in the toolbar.
+The [`useGlobals`](./addons-api.md#useglobals) and [`useStorybookApi`](./addons-api.md#usestorybookapi) hooks from the `manager-api` package are used to access the Storybook's APIs, allowing users to interact with the addon, such as enabling or disabling it.
```
Comment (kylegach) [inline docs/addons/writing-addons.md:104]: @cdedreuille — I pushed [the commit](https://github.com/storybookjs/storybook/pull/25822/commits/997fe1161a19b6bececf4b4b2a2caa86fffd32ed) with further updates.

File: docs/addons/writing-addons.md (hunk 4 above)
Comment (kylegach) [reply docs/addons/writing-addons.md]: @cdedreuille — I pushed [the commit](https://github.com/storybookjs/storybook/pull/25822/commits/997fe1161a19b6bececf4b4b2a2caa86fffd32ed) with further updates.

Comment (cdedreuille) [reply docs/addons/writing-addons.md]: Thanks Kyle. Looks great!

**Review by JReinhold — APPROVED** [review]
