### PR TITLE
Vue: Fix out of memory error when using vue-component-meta

### LINKED ISSUE #26647: [Bug]: Javascript heap out of memory when doing build-storybook when using docgen: 'vue-component-meta'
### Describe the bug

Hi folks - Storybook is amazing and I ❤️ it - and I'm very happy that 'vue-component-meta' was added in Storybook 8.

I migrated my component library to Storybook 8 recently and although the development build (`storybook dev -p 6006 --no-open`) works without issue - the build (`npx storybook build`) fails locally and in CI due to running out of memory (see below).

Removing `docgen: 'vue-component-meta'` from the Storybook configuration resolves the issue - but this docgen is the main reason I've migrated across.

It fails while transforming the .ts & .vue files - so I'm wondering if it's doing something while bundling (which isn't necessary) that isn't happening when running in the dev build which would be fine to just have built instead.

The component library I'm building has ~75 Vue3 components and in Storybook 8 without vue-component-meta it would use ~1.7GB.

I've tried going up to as far with max_old_space_size as 16GB to even get it to build locally but to no avail. My CI provider allows up to 4GB so that would be the goal.

main.ts
```ts
import type { StorybookConfig } from '@storybook/vue3-vite';
import pkg from '../package.json';

// Don't include the '/' in the package name as otherwise storybook interprets as a hierarchy hint.
export const titlePrefix = `${pkg.name.split('/').at(-1)}@${pkg.version}`;

export default {
  stories: [
    {
      titlePrefix,
      directory: '../src/components/',
      files: '**/*.stories.@(js|jsx|ts|tsx)'
    }
  ],
  staticDirs: ['../public'],
  framework: { name: '@storybook/vue3-vite', options: { docgen: 'vue-component-meta' } },
  core: { builder: '@storybook/builder-vite' }
};
```

Trace just before crash:

```
> components@3.8.1 build-storybook
> npx --max_old_space_size=16384 storybook build

@storybook/cli v8.0.4

info => Cleaning outputDir: storybook-static
info => Loading presets
info => Building manager..
info => Manager built (88 ms)
info => Building preview..
info => Copying static files: public at storybook-static

[vite:dts] You are building a library that may not need to generate declaration files.

vite v4.4.9 building for production...

./sb-common-assets/fonts.css doesn't exist at build time, it will remain unchanged to be resolved at runtime
transforming (141) src/components/tabs/TabButtons/TabButtons.stories.ts
```

Trace after crash (running with --max_old_space_size=16384 to try to saturate my RAM):
```
> components@3.8.1 build-storybook
> npx --max_old_space_size=16384 storybook build

@storybook/cli v8.0.4

info => Cleaning outputDir: storybook-static
info => Loading presets
info => Building manager..
info => Manager built (96 ms)
info => Building preview..
info => Copying static files: public at storybook-static

[vite:dts] You are building a library that may not need to generate declaration files.

vite v4.4.9 building for production...

./sb-common-assets/fonts.css doesn't exist at build time, it will remain unchanged to be resolved at runtime
transforming (161) node_modules/@mdx-js/react/index.js
<--- Last few GCs --->

[64674:0x120040000]    72249 ms: Mark-sweep 4022.0 (4136.7) -> 4007.9 (4138.5) MB, 1221.8 / 0.0 ms  (average mu = 0.113, current mu = 0.007) allocation failure; scavenge might not succeed
[64674:0x120040000]    73475 ms: Mark-sweep 4023.7 (4138.5) -> 4009.8 (4140.5) MB, 1216.9 / 0.0 ms  (average mu = 0.063, current mu = 0.008) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10444a6e4 node::Abort() [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
 2: 0x10444a8c8 node::ModifyCodeGenerationFromStrings(v8::Local<v8::Context>, v8::Local<v8::Value>, bool) [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
 3: 0x1045a160c v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
 4: 0x10474bec4 v8::internal::EmbedderStackStateScope::EmbedderStackStateScope(v8::internal::Heap*, v8::internal::EmbedderStackStateScope::Origin, cppgc::EmbedderStackState) [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
 5: 0x10474fab0 v8::internal::Heap::CollectSharedGarbage(v8::internal::GarbageCollectionReason) [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
 6: 0x10474cac4 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::internal::GarbageCollectionReason, char const*, v8::GCCallbackFlags) [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
 7: 0x104749dc4 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
 8: 0x10473e900 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
 9: 0x10473f144 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
10: 0x1047250c4 v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
11: 0x104ac56c0 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
12: 0x104e1504c Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
13: 0x10b03916c 
14: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
15: 0x10b7538ec 
16: 0x10c72bbfc 
17: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
18: 0x10c2d4d54 
19: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
20: 0x10c2d4a14 
21: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
22: 0x10b753c10 
23: 0x10c72bbfc 
24: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
25: 0x10b0390d4 
26: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
27: 0x10b7538ec 
28: 0x10c72bbfc 
29: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
30: 0x10c2d4d54 
31: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
32: 0x10c2d4a14 
33: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
34: 0x10b753c10 
35: 0x10c72bbfc 
36: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
37: 0x10b0390d4 
38: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
39: 0x10b7538ec 
40: 0x10c72bbfc 
41: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
42: 0x10c2d4d54 
43: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
44: 0x10c2d4a14 
45: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
46: 0x10b753c10 
47: 0x10c72bbfc 
48: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
49: 0x10b0390d4 
50: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
51: 0x10b7538ec 
52: 0x10c72bbfc 
53: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
54: 0x10c2d4d54 
55: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
56: 0x10c2d4a14 
57: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
58: 0x10b753c10 
59: 0x10c72bbfc 
60: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
61: 0x10b0390d4 
62: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
63: 0x10b7538ec 
64: 0x10c72bbfc 
65: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
66: 0x10c2d4d54 
67: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
68: 0x10c2d4a14 
69: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
70: 0x10b753c10 
71: 0x10c72bbfc 
72: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
73: 0x10b0390d4 
74: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
75: 0x10b7538ec 
76: 0x10c72bbfc 
77: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
78: 0x10c2d4d54 
79: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
80: 0x10c2d4a14 
81: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
82: 0x10b753c10 
83: 0x10c72bbfc 
84: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
85: 0x10b0390d4 
86: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
87: 0x10b7538ec 
88: 0x10c72bbfc 
89: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
90: 0x10c2d4d54 
91: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
92: 0x10c2d4a14 
93: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
94: 0x10b753c10 
95: 0x10c72bbfc 
96: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
97: 0x10b0390d4 
98: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
99: 0x10b7538ec 
100: 0x10c72bbfc 
101: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
102: 0x10c2d4d54 
103: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
104: 0x10c2d4a14 
105: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
106: 0x10b753c10 
107: 0x10c72bbfc 
108: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
109: 0x10b0390d4 
110: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
111: 0x10b7538ec 
112: 0x10c72bbfc 
113: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
114: 0x10c2d4d54 
115: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
116: 0x10c2d4a14 
117: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
118: 0x10b753c10 
119: 0x10c72bbfc 
120: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
121: 0x10b0390d4 
122: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
123: 0x10b7538ec 
124: 0x10c72bbfc 
125: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
126: 0x10c2d4d54 
127: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
128: 0x10c2d4a14 
129: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
130: 0x10b753c10 
131: 0x10c72bbfc 
132: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
133: 0x10b0390d4 
134: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
135: 0x10b7538ec 
136: 0x10c72bbfc 
137: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
138: 0x10c2d4d54 
139: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
140: 0x10c2d4a14 
141: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
142: 0x10b753c10 
143: 0x10c72bbfc 
144: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
145: 0x10b0390d4 
146: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
147: 0x10b753c10 
148: 0x10c72bbfc 
149: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
150: 0x10bf52034 
151: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
152: 0x10b7538ec 
153: 0x10c72bbfc 
154: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
155: 0x10c2d4d54 
156: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
157: 0x10c2d4a14 
158: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
159: 0x10b753c10 
160: 0x10c72bbfc 
161: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
162: 0x10b0390d4 
163: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
164: 0x10b7538ec 
165: 0x10c72bbfc 
166: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
167: 0x10c2d4d54 
168: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
169: 0x10c2d4a14 
170: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
171: 0x10b753c10 
172: 0x10c72bbfc 
173: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
174: 0x10b0390d4 
175: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
176: 0x10b7538ec 
177: 0x10c72bbfc 
178: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
179: 0x10c2d4d54 
180: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
181: 0x10c2d4a14 
182: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
183: 0x10b753c10 
184: 0x10c72bbfc 
185: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
186: 0x10b0390d4 
187: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
188: 0x10b7538ec 
189: 0x10c72bbfc 
190: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
191: 0x10c2d4d54 
192: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
193: 0x10c2d4a14 
194: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
195: 0x10b753c10 
196: 0x10c72bbfc 
197: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
198: 0x10b0390d4 
199: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
200: 0x10b7538ec 
201: 0x10c72bbfc 
202: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
203: 0x10c2d4d54 
204: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
205: 0x10c2d4a14 
206: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
207: 0x10b753c10 
208: 0x10c72bbfc 
209: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
210: 0x10b0390d4 
211: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
212: 0x10b7538ec 
213: 0x10c72bbfc 
214: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
215: 0x10c2d4d54 
216: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
217: 0x10c2d4a14 
218: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
219: 0x10b753c10 
220: 0x10c72bbfc 
221: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
222: 0x10b0390d4 
223: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
224: 0x10b7538ec 
225: 0x10c72bbfc 
226: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
227: 0x10c2d4d54 
228: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
229: 0x10c2d4a14 
230: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
231: 0x10b753c10 
232: 0x10c72bbfc 
233: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
234: 0x10b0390d4 
235: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
236: 0x10b753c10 
237: 0x10c72bbfc 
238: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
239: 0x10bf52034 
240: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
241: 0x10b7538ec 
242: 0x10c72bbfc 
243: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
244: 0x10c2d4d54 
245: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
246: 0x10c2d4a14 
247: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
248: 0x10b753c10 
249: 0x10c72bbfc 
250: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
251: 0x10b0390d4 
252: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
253: 0x10b7538ec 
254: 0x10c72bbfc 
255: 0x104d9d700 construct_stub_create_deopt_addr [/Users/lee/.nvm/versions/node/v18.17.0/bin/node]
[1]    64627 abort      npm run build-storybook
```

### To Reproduce

See bug description

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm <----- active
    pnpm: 8.9.2 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 123.0.6312.59
    Safari: 17.2.1
  npmPackages:
    @storybook/addon-essentials: ^8.0.4 => 8.0.4 
    @storybook/addon-interactions: ^8.0.4 => 8.0.4 
    @storybook/addon-links: ^8.0.4 => 8.0.4 
    @storybook/blocks: ^8.0.4 => 8.0.4 
    @storybook/vue3: ^8.0.4 => 8.0.4 
    @storybook/vue3-vite: ^8.0.4 => 8.0.4 
    chromatic: ^11.0.0 => 11.0.0 
    storybook: ^8.0.4 => 8.0.4
```

### Additional context

_No response_

### LINKED ISSUE #26935: [Bug]: Storybook and Radix-vue memory leak
### Describe the bug

Started a vue app from scratch and added strybook 8.0.9 and Radix-vue with shadcn-vue. When I try to render a component into a story `DropdownMenuContent` and open storybook with `npm run storybook`, it fails to render and it freezes the browser. It crashes the app after 30s-1min with a `FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory` error.

What I tried:
 - bumped the space size for NODE using `--max-old-space-size=32768`
 - duplicated vite.config.js into storybook, then pointed via main.ts to the colocated one, just to exclude random configurations from there
 - sourceMap: false from viteFinal within main.ts in .storybook

Apologies if this isn't really a storybook issue, but it happens only in storybook context. 

### To Reproduce

1. Scaffold new vue 3 app with vite
2. Add radix-vue with shadcn-vue
3. Initialize storybook
4. Try to render the `DropdownMenuContent`

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm <----- active
    pnpm: 8.15.4 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 124.0.6367.62
    Safari: 17.4.1
  npmPackages:
    @storybook/addon-essentials: ^8.0.9 => 8.0.9 
    @storybook/addon-interactions: ^8.0.9 => 8.0.9 
    @storybook/addon-links: ^8.0.9 => 8.0.9 
    @storybook/blocks: ^8.0.9 => 8.0.9 
    @storybook/test: ^8.0.9 => 8.0.9 
    @storybook/vue3: ^8.0.9 => 8.0.9 
    @storybook/vue3-vite: ^8.0.9 => 8.0.9 
    eslint-plugin-storybook: ^0.8.0 => 0.8.0 
    storybook: ^8.0.9 => 8.0.9
```

### Additional context

I suspect this is an issue with typescript. I localised the issue and it happens when I import a type within DropdownMenuContent.
image

### PR DESCRIPTION
**Pull request by larsrickert**
Closes #26647 
Closes #26935
Based on discussions on #28462

## What I did

This PR fixes the "out of memory" issue when running `storybook build` when using complex property types like `HTMLElement` with the `vue-component-meta` docgen plugin.

The root cause is that `vue-component-meta` includes all recursive schemas for object types which can be very complex and large (e.g. HTMLElement). Since the nested schema is not needed inside Storybok because we don't generate UI controls for object properties, we should be able to safely omitting them without any side effects.

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

1. Run a sandbox for template, e.g. `yarn task --task sandbox --start-from auto --template vue3-vite/default-ts`
2. In .storybook/main.ts, set the `framework.options.docgen` option to `vue-component-meta`
3. Add new property `test?: HTMLElement` to any Vue component
4. Run `build-storybook`

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

| name | before | after | diff | z | % |
| ---- | ------ | ----- | ---- | - | - |
| createSize |  0 B | 0 B | 0 B | - | - |
| generateSize |  76.5 MB | 76.5 MB | 1.99 kB | **1.83** | 0% |
| initSize |  198 MB | 198 MB | 3.45 kB | -0.78 | 0% |
| diffSize |  121 MB | 121 MB | 1.46 kB | -0.8 | 0% |
| buildSize |  7.59 MB | 7.59 MB | 1 B | **4.54** | 0% |
| buildSbAddonsSize |  1.63 MB | 1.63 MB | 0 B | **4.36** | 0% |
| buildSbCommonSize |  195 kB | 195 kB | 0 B | - | 0% |
| buildSbManagerSize |  2.3 MB | 2.3 MB | 1 B | **Infinity** | 0% |
| buildSbPreviewSize |  349 kB | 349 kB | 0 B | - | 0% |
| buildStaticSize |  0 B | 0 B | 0 B | - | - |
| buildPrebuildSize |  4.47 MB | 4.47 MB | 1 B | **4.54** | 0% |
| buildPreviewSize |  3.12 MB | 3.12 MB | 0 B | - | 0% |
| testBuildSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbAddonsSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbCommonSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbManagerSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbPreviewSize |  0 B | 0 B | 0 B | - | - |
| testBuildStaticSize |  0 B | 0 B | 0 B | - | - |
| testBuildPrebuildSize |  0 B | 0 B | 0 B | - | - |
| testBuildPreviewSize |  0 B | 0 B | 0 B | - | - |

| name | before | after | diff | z | % |
| ---- | ------ | ----- | ---- | - | - |
| createTime |  25.5s | 23.7s | -1s -764ms | **1.41** | 🔰-7.4% |
| generateTime |  20s | 24.9s | 4.8s | 1.22 | 19.5% |
| initTime |  20.6s | 23.7s | 3s | 0.23 | 13% |
| buildTime |  13.9s | 15.6s | 1.7s | 1.11 | 11% |
| testBuildTime |  0ms | 0ms | 0ms | - | - |
| devPreviewResponsive |  8.2s | 10.2s | 1.9s | **1.96** | 🔺18.8% |
| devManagerResponsive |  5.6s | 6.2s | 629ms | **1.51** | 🔺10.1% |
| devManagerHeaderVisible |  799ms | 1s | 259ms | **4.73** | 🔺24.5% |
| devManagerIndexVisible |  828ms | 1s | 271ms | **4.9** | 🔺24.7% |
| devStoryVisibleUncached |  1.2s | 1.8s | 595ms | **2.5** | 🔺31.8% |
| devStoryVisible |  860ms | 1.1s | 263ms | **4.8** | 🔺23.4% |
| devAutodocsVisible |  715ms | 847ms | 132ms | **2.22** | 🔺15.6% |
| devMDXVisible |  696ms | 943ms | 247ms | **3.46** | 🔺26.2% |
| buildManagerHeaderVisible |  782ms | 956ms | 174ms | **1.94** | 🔺18.2% |
| buildManagerIndexVisible |  784ms | 961ms | 177ms | **1.87** | 🔺18.4% |
| buildStoryVisible |  852ms | 1s | 153ms | **1.86** | 🔺15.2% |
| buildAutodocsVisible |  697ms | 842ms | 145ms | **1.39** | 🔺17.2% |
| buildMDXVisible |  700ms | 825ms | 125ms | **3.36** | 🔺15.2% |

### CODE REVIEW

**Comment by et84121** [comment]
@larsrickert, I want to express my sincere gratitude for your thorough investigation and solution to this issue. Your approach of addressing the problem within Storybook's processing, rather than limiting vue-component-meta's capabilities, is indeed a much better solution than what I initially proposed.

Your work here not only solves the immediate problem but also maintains the full functionality of vue-component-meta, which is crucial for many projects. This fix will be incredibly helpful for teams like mine who are looking to adopt or continue using Storybook for component documentation.

Thank you for your dedication to improving Storybook and for fostering such a collaborative environment for problem-solving. Your efforts are truly appreciated!

File: code/renderers/vue3/src/docs/extractArgTypes.ts [hunk 1]
```diff
@@ -283,17 +283,11 @@ export const convertVueComponentMetaProp = (
...
       return {
         name: 'object',
-        value: Object.entries(schema.schema ?? {}).reduce<Record<string, SBType>>(
-          (obj, [propName, propSchema]) => {
-            obj[propName] = convertVueComponentMetaProp(propSchema);
-            return obj;
-          },
-          {}
-        ),
+        // Storybook does not generate controls for object properties so we don't need to recursively map the object schema here
```
Comment (chakAs3) [inline code/renderers/vue3/src/docs/extractArgTypes.ts:289]: I'm not entirely sure what you mean here. While it's true that complex objects won't have proper controls, Storybook does generate controls for simple objects (JSON object controls). However, it doesn't require or use nested schemas. I think you meant controls for the properties of objects rather than props of the object type.

Comment (larsrickert) [reply code/renderers/vue3/src/docs/extractArgTypes.ts]: Yes exactly, I updated the comment so I hope its clearer now :)

**Review by kasperpeulen — APPROVED** [review]
LGTM, thanks!

**Comment by kasperpeulen** [comment]
Could you check the CI failures @larsrickert

**Comment by MathiasCiarlo** [comment]
Thank you so much @larsrickert! We are waiting eagerly for this release. It will make our static bundle go frow 84 to 4 MB, greatly reducing build time 🥳

**Comment by Adamlb** [comment]
I have tried the new alpha.2 release that included this PR but I am still experiencing the memory issues. Has this solved it for others? I'm wondering if I have something else going on.

**Comment by ericvel** [comment]
@Adamlb Sadly still experiencing the same issue 😢

**Comment by larsrickert** [comment]
@Adamlb @ericvel I updated `@storybook/vue3` and `@storybook/vue3-vite` to version `8.3.0-alpha.2` and it worked perfectly fine in my tests.

Could you share a reproduction example?

**Comment by ericvel** [comment]
@larsrickert It does in fact seem to have fixed the issue in places where I use the `HTMLElement `and `InputHTMLAttributes` types.

The only type still causing memory issues for me now is `MouseEvent`. See example:

```
const onClick = (event: MouseEvent) => {
  // do something
};
```

In any case, thank you for the quick alpha release! 🙏 Let me know if you need more details.

**Comment by Adamlb** [comment]
@larsrickert We don't specifically pull in the types in our components yet but we are using shadcn and radix-vue which does.

If I give the build 8gb of ram, it does complete, and the most egregious file is full of repeated documentation around event things, so its likely the same thing as ericvel.

I will try and determine something more specific, but may not be able to get to it until this evening.

**Comment by Walnussbaer** [comment]
Is there a working workaround for this problem? Since our upgrade to storybook 8.2.9 and using vue-component-meta, we cannot build storybook for production anymore. 

I tried using storybook `8.3.0-alpha.8`, but npm install reports conflicting peer dependencies (although I upgraded every storybook dependency we use to 8.3.0-alpha.8 - I guess that's why it's called alpha ^^)

**Comment by larsrickert** [comment]
> Is there a working workaround for this problem? 
@Walnussbaer Hey, the issue should be fixed now. Can you try out the latest version 8.3.0-beta.5?

**Comment by Walnussbaer** [comment]
@larsrickert I just upgraded to the final release yesterday (8.3.0) and everything worked like a charm. We also had a bug in 8.3.0-alpha.8  that the controls for argTypes weren't created automatically, but this was also fixed with 8.3.0. So far, really good work. Thank you very much!
