### PR TITLE
Angular: Include object configured styles

### LINKED ISSUE #17711: Angular storybook does not read the global styles when bundlename is specified in the angular json
**Describe the bug**
When using angular builder for storybook, the Global styles are only applied when I specified in the styles like below
"styles": ["src/styles.scss"]
But if I specific the styles with an object like using input and bundleName, will not work.

**To Reproduce**
Please use the below repo to reproduce the issue.
https://github.com/SunilManthenaG01/storybook-inline-scss-angular-
I added the body css style in styles.scss file. When you run the storybook using **npm run storybook** click on the app component story and you can see the global styles which are in styles.scss are not applied.
If you change like below, it works fine.
image

**System**
Environment Info:
Browsers:
Edge: Spartan (44.19041.1266.0), Chromium (98.0.1108.62)
npmPackages:
@storybook/addon-actions: ^6.4.19 => 6.4.19
@storybook/addon-essentials: ^6.4.19 => 6.4.19
@storybook/addon-interactions: ^6.4.19 => 6.4.19
@storybook/addon-links: ^6.4.19 => 6.4.19
@storybook/angular: ^6.4.19 => 6.4.19
@storybook/builder-webpack5: ^6.4.19 => 6.4.19
@storybook/manager-webpack5: ^6.4.19 => 6.4.19
@storybook/testing-library: ^0.0.9 => 0.0.9
npmGlobalPackages:
@storybook/cli: 6.4.19

### LINKED ISSUE #24683: [Bug]: storybook/angular is not using all styles from angular.json
### Describe the bug

Storybook is not including all styles, if the styles are defined as an object.

See https://angular.io/guide/workspace-config#styles-and-scripts-configuration

In my case i used: 

```json
// project.json / angular.json
[
         {
            "input": "dist/theme/design.token.css",
            "inject": true,
            "bundleName": "design-tokens"
          },
          "app/src/styles.scss",
]
```

In this case the design tokens are not contained. 
Only the `styles.scss` gets applied.

### To Reproduce

https://stackblitz.com/edit/github-e8jowf-rywx3a?file=angular.json

the button should be pink (`--button-background-color: #ff02b3;`) if the css (`src/design.tokens.css`) would have been loaded correctly.

Only the `src/styles.scss` is applied as expected.

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.1
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    pnpm: 8.10.0 - ~/.nvm/versions/node/v18.18.2/bin/pnpm <----- active
  Browsers:
    Chrome: 118.0.5993.117
    Edge: 118.0.2088.76
    Safari: 17.1
  npmPackages:
    @storybook/addon-designs: ^7.0.5 => 7.0.5 
    @storybook/addon-essentials: 7.5.2 => 7.5.2 
    @storybook/addon-interactions: ^7.5.1 => 7.5.2 
    @storybook/angular: 7.5.2 => 7.5.2 
    @storybook/core-server: 7.5.2 => 7.5.2 
    @storybook/jest: ~0.1.0 => 0.1.0 
    @storybook/manager-api: ^7.5.1 => 7.5.2 
    @storybook/test-runner: ^0.13.0 => 0.13.0 
    @storybook/testing-library: ~0.2.0 => 0.2.2 
    @storybook/theming: ^7.5.1 => 7.5.2 
    storybook-addon-pseudo-states: ^2.1.2 => 2.1.2
```

### Additional context

I used NX (`"@nx/storybook": "17.0.2"`)

### PR DESCRIPTION
**Pull request by valentinpalkovic**
Closes https://github.com/storybookjs/storybook/issues/24683
Closes https://github.com/storybookjs/storybook/issues/17711

## What I did

Support styles, which are configured as an object

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

1. Clone https://stackblitz.com/edit/github-e8jowf-rywx3a?file=angular.json
2. Build `@storybook/angular` and replace `node_modules/@storybook/angular/dist` with build output
3. Verify, that the button should be pink (--button-background-color: #ff02b3;)

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Review by yannbf — APPROVED** [review]
LGTM!!

File: code/frameworks/angular/src/server/angular-cli-webpack.js [hunk 1]
```diff
@@ -66,6 +66,9 @@ exports.getWebpackConfig = async (baseConfig, { builderOptions, builderContext }
 
       // Options provided by user
       ...builderOptions,
+      styles: builderOptions.styles
+        ?.map((style) => (typeof style === 'string' ? style : style.input))
```
Comment (andriy-statsenko-lightit) [inline code/frameworks/angular/src/server/angular-cli-webpack.js:70]: @valentinpalkovic hi. I think there is a slight mistake here since first you use `map` to take the string, but the `filter` will always have a string. Now objects with `"inject": false` will not be created as separate files

Comment (valentinpalkovic) [reply code/frameworks/angular/src/server/angular-cli-webpack.js:70]: Hi @andriy-statsenko-lightit

Thank you for pointing this out. You're right! Fix incoming: https://github.com/storybookjs/storybook/pull/27108

Comment (andriy-statsenko-lightit) [reply code/frameworks/angular/src/server/angular-cli-webpack.js:70]: @valentinpalkovic Thanks for the answer. It’s also worth noting that even if you swap the `filter` and `map`, files with `“inject”: false` will not be included in the final build. 🤔

Comment (valentinpalkovic) [reply code/frameworks/angular/src/server/angular-cli-webpack.js:70]: Maybe I misunderstood the `inject` property in the past. Are you saying we shouldn't filter at all, but `inject` only means whether the CSS is bundled in or outputted as a separate file?

Comment (andriy-statsenko-lightit) [reply code/frameworks/angular/src/server/angular-cli-webpack.js:70]: Ok so `inject: false` just excludes the bundle from the injection to `index.html` file, but the file will remain in the folder. `inject: true` includes the file to `index.html`. Example:
image
As I understand it, the problem was that files with `inject: true` were not included in the` index.html `file or were not included in the `main.css `file (not knowing exactly how the storybook builder works). After this fix, they will now be in the `main.css` file, but files with `inject: false` will not be created at all in the build (`dist`) folder.

Comment (valentinpalkovic) [reply code/frameworks/angular/src/server/angular-cli-webpack.js:70]: Ok, so do I understand you correctly?:

- If inject: true is set, the CSS file is compiled/transpiled AND should be part of the main bundle
- If inject: false is set, the CSS file is compiled/transpiled but is NOT part of the main bundle. In this case you have to import it somewhere manually? Can you name some examples where this is relevant?

Comment (andriy-statsenko-lightit) [reply code/frameworks/angular/src/server/angular-cli-webpack.js:70]: Yeah, exactly. So in my case, I use those `inject-false` files in `manager-head/preview-head.html` and import them like CSS or JS files.

Comment (valentinpalkovic) [reply code/frameworks/angular/src/server/angular-cli-webpack.js:70]: And did the fix in this PR break this behavior? Or was it never working?

Comment (andriy-statsenko-lightit) [reply code/frameworks/angular/src/server/angular-cli-webpack.js:70]: Yes, this fix simply filters out files with `inject: false`. As a result, the `main.css` file contains only files that are either files with `inject: true` or with no `inject` (it is `true` by default).
But there is an interesting point - if you comment out this fix, it also does not always work normally. For example, this config creates separate files:
```
"styles": [
               {
                 "input": ".storybook/styles/ui-manager-overrides.scss",
                 "inject": false,
                 "bundleName": "ui-manager-overrides"
               },
               {
                 "input": ".storybook/styles/ui-preview-overrides.scss",
                 "inject": false,
                 "bundleName": "ui-preview-overrides"
               }
             ]
```
image

But if you add `"src/styles/main.scss"`, then only the `main.css` file is created, and files with `"inject": false `are simply not created in the dist folder. This problem only occurs with Storybook Builder; there is no such problem with Angular Builder.
```
"styles": [
              "src/styles/main.scss",
              {
                "input": ".storybook/styles/ui-manager-overrides.scss",
                "inject": false,
                "bundleName": "ui-manager-overrides"
              },
              {
                "input": ".storybook/styles/ui-preview-overrides.scss",
                "inject": false,
                "bundleName": "ui-preview-overrides"
              }
            ]
```
image

Comment (valentinpalkovic) [reply code/frameworks/angular/src/server/angular-cli-webpack.js:70]: That's interesting! Does it work if you define `src/styles/main.scss` in the object notation alongside with the other two scss files, like:

```
"styles": [
              {
                "input": "src/styles/main.scss",
                "bundleName": "main.scss",
                "inject": true
              },
              {
                "input": ".storybook/styles/ui-manager-overrides.scss",
                "inject": false,
                "bundleName": "ui-manager-overrides"
              },
              {
                "input": ".storybook/styles/ui-preview-overrides.scss",
                "inject": false,
                "bundleName": "ui-preview-overrides"
              }
            ]
```

Comment (andriy-statsenko-lightit) [reply code/frameworks/angular/src/server/angular-cli-webpack.js:70]: Yeah, if there is an object, it works ok, but if there is a path as a string, then files with `“inject”: false` simply do not appear in `dist` folder. This is interesting
image

With string path:
image

Comment (valentinpalkovic) [reply code/frameworks/angular/src/server/angular-cli-webpack.js:70]: But that's great. Then I can kind of revert the work of this PR and do an internal mapping of styles defined as strings to the object notation. For the user, nothing changes, but things seem to work then!

Comment (andriy-statsenko-lightit) [reply code/frameworks/angular/src/server/angular-cli-webpack.js:70]: Yeah, it sounds like a great idea 🙂

Comment (valentinpalkovic) [reply code/frameworks/angular/src/server/angular-cli-webpack.js:70]: I've put together a fix here: https://github.com/storybookjs/storybook/pull/27108

@andriy-statsenko-lightit Would you mind to test the following canary release and give me some feedback? `0.0.0-pr-27108-sha-2470133a`

Comment (andriy-statsenko-lightit) [reply code/frameworks/angular/src/server/angular-cli-webpack.js:70]: @valentinpalkovic yeah, it works fine with different `styles` arrays: string only, string + objects, and objects only. Thanks!
