### PR TITLE
Core: Improve globbing using dynamic CWD

### LINKED ISSUE #32835: [Bug]: Stories glob should exclude node_modules
### Describe the bug

Encountered the following bug upgrading HeroUI from SB8 to SB9.

The following line:

https://github.com/shilman/heroui/blob/328c57d8ea4d27306a7001bb702a1c018953ed0c/packages/storybook/.storybook/main.ts#L8

Had to be modified to:

https://github.com/shilman/heroui/blob/07928b4669e39b270d4a694684aee7c3b5f5e52b/packages/storybook/.storybook/main.ts#L8

Because SB9 was picking up stories from `node_modules`. This is a common pattern and an unintentional breaking change in SB9.

### Reproduction link

https://github.com/shilman/heroui/

### Reproduction steps

First:

```
pnpm install
pnpm run sb
```

Then revert the change to `main.ts` and

```
pnpm run sb
```

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 15.7.1
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.20.0 - /usr/local/bin/node
    npm: 10.9.3 - /usr/local/bin/npm
    pnpm: 10.6.2 - ~/Library/pnpm/.tools/pnpm/10.6.2/bin/pnpm <----- active
  Browsers:
    Chrome: 141.0.7390.123
    Safari: 26.0.1
  npmPackages:
    @storybook/addon-a11y: ^9.1.15 => 9.1.15 
    @storybook/addon-docs: ^9.1.15 => 9.1.15 
    @storybook/addon-links: ^9.1.15 => 9.1.15 
    @storybook/cli: ^9.1.15 => 9.1.15 
    @storybook/react-vite: ^9.1.15 => 9.1.15 
    storybook: ^9.1.15 => 9.1.15
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ia319**
Closes #32835

## What I did

- calculate dynamic CWD for each story specifier
- ensure globby correctly excludes `node_modules` when glob pattern references parent directories

#### The changes in this PR are covered in the following automated tests:

- [x] stories
- [x] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

After the change, the repository mentioned in the issue runs normally, and no errors were found.

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/publish.yml) or locally with `gh workflow run --repo storybookjs/storybook publish.yml --field pr=<PR_NUMBER>`_

## Summary by CodeRabbit

* **Refactor**
  * Improved file-pattern matching and per-pattern directory resolution so file discovery handles patterns that reference locations outside the current working directory more reliably, reducing missed or mis-resolved files during searches. No public APIs or exported interfaces were changed.

### CODE REVIEW

File: code/core/src/core-server/utils/StoryIndexGenerator.ts [hunk 1]
```diff
@@ -160,16 +160,19 @@ export class StoryIndexGenerator {
...
 
-    const files = await globby(fullGlob, {
+    // Execute globby within the new CWD to ensure `ignore` patterns work correctly.
+    const files = await globby(globPattern, {
       absolute: true,
-      cwd: workingDir,
-      ...commonGlobOptions(fullGlob),
+      cwd: globCwd,
+      ...commonGlobOptions(globPattern),
     });
```
Comment (ndelangen) [inline code/core/src/core-server/utils/StoryIndexGenerator.ts:176]: We were using `slash` before; likely for Windows support / path-conversions?
Do we still need something for this?

**Review by ndelangen — CHANGES_REQUESTED** [review]

File: code/core/src/core-server/utils/StoryIndexGenerator.ts (hunk 1 above)
Comment (ia319) [reply code/core/src/core-server/utils/StoryIndexGenerator.ts:176]: Yes, I've added slash to handle that.

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
@ia319 I'm reverting this PR, it seems it caused issues with some negated globs, see this issue:
https://github.com/storybookjs/storybook/issues/33197

I'd welcome this being fixed still, are you open to work on this still, but in such a way negated globs do not break? 🙏

**Comment by ia319** [comment]
> I'd welcome this being fixed still, are you open to work on this still, but in such a way negated globs do not break? 🙏

I have some guesses, and I want to wait for his reply at "https://github.com/storybookjs/storybook/issues/33197#issuecomment-3584992611".
