### PR TITLE
UI: Fix sidebar top and bottom addon slots

### LINKED ISSUE #25404: [Bug]: Visual Test addon does not show test/filter buttons in 8.0-alpha
### Describe the bug

In the monorepo, run `yarn storybook:ui`. The visual test addon is missing its test and filter buttons from the sidebar.

Removing `useMemo` from these lines fixes it, but it might not be the right fix:

https://github.com/storybookjs/storybook/blob/next/code/ui/manager/src/container/Sidebar.tsx#L45-L46

Need:
- [ ] A proper fix
- [ ] Tests to ensure it does not regress

### To Reproduce

_No response_

### System

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ndelangen**
Closes #25404

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

File: code/ui/manager/src/container/Sidebar.tsx [hunk 1]
```diff
@@ -41,9 +42,12 @@ const Sidebar = React.memo(function Sideber({ onMenuClick }: SidebarProps) {
     const whatsNewNotificationsEnabled =
       state.whatsNewData?.status === 'SUCCESS' && !state.disableWhatsNewNotifications;
 
-    const items = api.getElements(types.experimental_SIDEBAR_BOTTOM);
-    const bottom = useMemo(() => Object.values(items), [items]);
-    const top = useMemo(() => Object.values(api.getElements(types.experimental_SIDEBAR_TOP)), []);
+    const bottomItems = api.getElements(Addon_TypesEnum.experimental_SIDEBAR_BOTTOM);
+    const topItems = api.getElements(Addon_TypesEnum.experimental_SIDEBAR_TOP);
+    // eslint-disable-next-line react-hooks/exhaustive-deps
+    const bottom = useMemo(() => Object.values(bottomItems), [...Object.values(bottomItems)]);
```
Comment (shilman) [inline code/ui/manager/src/container/Sidebar.tsx:48]: What is the point of this kind of memoization???

Comment (ndelangen) [reply code/ui/manager/src/container/Sidebar.tsx:48]: You get the same array every time, unless `bottomItems` has new properties/values.

Comment (shilman) [reply code/ui/manager/src/container/Sidebar.tsx:48]: Ok, so it's about preserving instance equality of the array so that the consuming UI does not re-render unnecessarily?

**Review by shilman — APPROVED** [review]
