### PR TITLE
Globals: Repair dynamicTitle: false for user-defined tools

### LINKED ISSUE #33281: [Bug]: Setting dynamicTitle to false in globals has no effect
### Describe the bug

When configuring globals with dynamicTitle: false, the expectation is that the toolbar title remains fixed regardless of global option changes. However, selecting an option from the toolbar's global select causes the toolbar title to update to that option's title.

### Reproduction link

https://stackblitz.com/edit/github-w91nbsqm-9jyxfq2t?file=.storybook%2Fpreview.ts

### Reproduction steps

1. Go to above link.
2. Select an option (e.g., "example1") from the global select toolbar.

### System

```bash
Storybook Environment Info:
│

│  System:
│  OS: macOS 26.1
│  CPU: (8) arm64 Apple M1 Pro
│  Shell: 5.9 - /bin/zsh
│  Binaries:
│  Node: 22.19.0 
│  npm: 8.19.4 
│  pnpm: 9.15.3 - /opt/homebrew/bin/pnpm <----- active
│  Browsers:
│  Chrome: 142.0.7444.176
│  Edge: 142.0.3595.94
│  Firefox: 143.0.3
│  Safari: 26.1
│  npmPackages:
│  @storybook/addon-a11y: 10.1.2 => 10.1.2
│  @storybook/addon-docs: 10.1.2 => 10.1.2
│  @storybook/addon-links: 10.1.2 => 10.1.2
│  @storybook/angular: 10.1.2 => 10.1.2
│  @storybook/test-runner: 0.24.2 => 0.24.2
│  eslint-plugin-storybook: 10.1.2 => 10.1.2
│  storybook: 10.1.2 => 10.1.2
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ia319**
Closes #33281

## What I did

* Add `showSelectedLabel` prop to `Select` (default `true`).
* Only show the selected label when this prop is enabled.
* Set `showSelectedLabel={false}` in `ToolbarMenuSelect`.

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/publish.yml) or locally with `gh workflow run --repo storybookjs/storybook publish.yml --field pr=<PR_NUMBER>`_

## Summary by CodeRabbit

* **New Features**
  * Added a configurable option to control whether selected option titles are displayed in select dropdowns. Default behavior is maintained for backward compatibility, automatically applying across single and multi-select variants.

### CODE REVIEW

File: code/core/src/toolbar/components/ToolbarMenuSelect.tsx [hunk 1]
```diff
@@ -101,6 +101,7 @@ export const ToolbarMenuSelect: FC<ToolbarMenuSelectProps> = withKeyboardCycle(
         onReset={() => updateGlobals({ [id]: '_reset' })}
         onSelect={(selected) => updateGlobals({ [id]: selected })}
         icon={icon && <Icons icon={icon} __suppressDeprecationWarning={true} />}
+        showSelectedLabel={false}
```
Comment (mrginglymus) [inline code/core/src/toolbar/components/ToolbarMenuSelect.tsx]:
```suggestion
        showSelectedLabel={dynamicTitle}
```

otherwise it'll _never_ update

File: code/core/src/toolbar/components/ToolbarMenuSelect.tsx
Comment (mrginglymus) [inline code/core/src/toolbar/components/ToolbarMenuSelect.tsx]: If we pass dynamicTitle through, then we can remove this logic and pass title through directly

Comment (ia319) [reply code/core/src/toolbar/components/ToolbarMenuSelect.tsx]: Thanks for pointing that out — updated accordingly.

File: code/core/src/components/components/Select/Select.tsx [hunk 2]
```diff
@@ -76,6 +76,11 @@ export interface SelectProps
   onSelect?: (option: Value) => void;
   onDeselect?: (option: Value) => void;
   onChange?: (selected: Value[]) => void;
+  /**
+   * Whether to show the selected option's title in place of the children when an option is
+   * selected. Defaults to true.
+   */
+  showSelectedLabel?: boolean;
```
Comment (Sidnioulz) [inline code/core/src/components/components/Select/Select.tsx]:
```suggestion
  /**
   * Legacy option for ToolbarMenuSelect. Do not set this prop in new Storybook code. Whether to show the selected option's title or to preserve the Select's title when a selection is made.
   * @default true
   */
  showSelectedOptionTitle?: boolean;
```

Two comments here:
* I truly do not want people to start using this prop because we made an explicit UX choice with @MichaelArestad to always show the selected item; it aligns the component's behaviour more closely with native HTML `select`
* Let's name it `showSelectedOptionTitle` because it controls showing the selected option's title; this will help us understand our code better :)

File: code/core/src/components/components/Select/Select.tsx
Comment (Sidnioulz) [inline code/core/src/components/components/Select/Select.tsx:1]: We'll need new stories showing how labels behave on `!multiSelect` and on `multiSelect` Selects, when a selection is made, and the option is on or off (so, 4 stories with `defaultOptions` and a `play` function validating the HTML output).

File: code/core/src/toolbar/components/ToolbarMenuSelect.tsx
Comment (Sidnioulz) [inline code/core/src/toolbar/components/ToolbarMenuSelect.tsx]: Could you please make `dynamicTitle` `true` by default here?

File: code/core/src/toolbar/components/ToolbarMenuSelect.tsx [hunk 3]
```diff
@@ -40,16 +40,12 @@ export const ToolbarMenuSelect: FC<ToolbarMenuSelectProps> = withKeyboardCycle(
     const currentValue = globals[id];
     const isOverridden = id in storyGlobals;
     let icon = _icon;
-    let title = _title;
+    const title = _title;
```
Comment (Sidnioulz) [inline code/core/src/toolbar/components/ToolbarMenuSelect.tsx]: You no longer need to rename the `title` prop to `_title` and then create a new `title`. Could you please tidy that up?

File: code/core/src/toolbar/components/ToolbarMenuSelect.tsx
Comment (Sidnioulz) [inline code/core/src/toolbar/components/ToolbarMenuSelect.tsx:1]: Bunch more things to tidy up:

* [ ] In [docs/_snippets/storybook-preview-configure-globaltypes.md](https://github.com/storybookjs/storybook/blob/next/docs/_snippets/storybook-preview-configure-globaltypes.md), could you please replace the 4 occurences of `// Change title based on selected value` to `// Change title based on selected value (recommended for consistency with the Storybook UI)`
* [ ] Remove `getSelectedTitle`'s source code as it is no longer needed

**Review by Sidnioulz — CHANGES_REQUESTED** [review]
Thanks for tackling this @ia319! This is a bit of a sensitive one as we wanted to enforce dynamic titles on all Selects (and yes, I did forget to handle that old option in ToolbarMenuSelect 😬).

File: code/core/src/components/components/Select/Select.stories.tsx [hunk 4]
```diff
@@ -1372,3 +1372,61 @@ export const ResetWithUndefinedOption = meta.story({
...
+    showSelectedOptionTitle: false,
+    multiSelect: true,
+    defaultOptions: ['frog', 'tadpole'],
+  },
+  play: async ({ canvas, step }) => {
+    await step('Verify default title is shown for multi-select', async () => {
+      const selectButton = await canvas.findByRole('button');
+      expect(selectButton).toHaveTextContent('Animal');
+    });
+  },
```
Comment (Sidnioulz) [inline code/core/src/components/components/Select/Select.stories.tsx:1523]: Could you also check that `1` does not appear? If we want to ensure `showSelectedOpenTitle=false` perfectly matches `dynamicTitle=false`, we don't want to show the multiSelect pill here. So we should check that it's hidden in our test.

**Review by Sidnioulz — COMMENTED** [review]
Kudos @ia319, there's just one tiny thing to do with Select multiSelect and we can merge this. Thanks for your contribution ❤️

File: code/core/src/components/components/Select/Select.stories.tsx (hunk 4 above)
Comment (ia319) [reply code/core/src/components/components/Select/Select.stories.tsx:1523]: I can add an assertion like:

  expect(selectButton).not.toHaveTextContent('1');

However, I noticed that in the current implementation, multiSelect always shows the selected count once there is a selection, even when showSelectedOptionTitle is false. Could you confirm if the expected behavior is to hide the multi-select count pill entirely in this case?

Comment (Sidnioulz) [reply code/core/src/components/components/Select/Select.stories.tsx:1523]: You're right, it doesn't matter.

**Review by Sidnioulz — APPROVED** [review]
Thanks @ia319!

**Comment by valentinpalkovic** [comment]
Hi @ia319 

Thank you for putting together this PR!

This PR has some merge conflicts. Would you be able to take a look?

**Comment by ia319** [comment]
@valentinpalkovic Conflicts resolved. Verified that yarn test and yarn lint passed without any related issues.
