### PR TITLE
Svelte: Fix events not being logged in Actions when a story has decorators

### LINKED ISSUE #20690: [Bug]: Decorators in Svelte causes dispatched events to not be logged in Actions
### Describe the bug

Usually, any globally dispatched events in a Svelte component automatically gets inferred and attached to actions.

This works fine for basic components, but as soon as a decorator is decorating a story, it stops attaching any events to actions. Even when manually specifying the argType it still doesn't get logged in the actions panel.

### To Reproduce

```shell
The default stories from a fresh Svelte project works fine.

Adding a decorator breaks it:


export const Secondary = {
  args: {
    label: 'Button',
  },
  argTypes: {
    // onClick: { action: 'clicked' }, // manually doing it should also work in theory
  },
  decorators: [() => BorderDecoratorRed ]
};
```

### System

_No response_

### Additional context

This is likely a regression introduced in https://github.com/storybookjs/storybook/pull/19987

### PR DESCRIPTION
**Pull request by JReinhold**
Closes #20690

## What I did

- Calculated Svelte v4/v5 directly in the `SlotDecorator` component instead of passing it down via props. As https://github.com/storybookjs/storybook/issues/20690#issuecomment-2163891389 correctly points out, `SlotDecorator` didn't correctly pass that prop down to nested `SlotDecorator`'s. Avoiding prop drilling was just easier
- Moved the conversion of action argTypes to event listeners from the root `PreviewRender` component down to the inner-most `SlotDecorator`. Only that last `SlotDecorator` can actually attach the event listeners to the original story. `PreviewRender` now passes `argTypes` down via a context.

Note that there's a weird bug where actions are logged correctly, until you navigate to a _story of another component_, then all actions will be logged twice, once as `click` and then as `event_click`. I have no idea why this happens, I tried to figure it out but couldn't, and it happened before this PR as well, so at least it's not a regression because of this.

#### The changes in this PR are covered in the following automated tests:
- [x] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

1. In a Svelte sandbox, open the story at `/?path=/story/stories-renderers-svelte-slot-decorators--with-default-red-border` (this story has decorators)
2. Click the button
3. See actions logged in the panel.
4. See the currently deployed `next` sandbox does _not_ log actions, even though it should. https://6308736456ad2046275c0ae7-bczjhlhvbw.chromatic.com/?path=/story/stories-renderers-svelte-slot-decorators--with-default-red-border

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This pull request has been released as version `0.0.0-pr-28247-sha-834d31db`. Try it out in a new sandbox by running `npx storybook@0.0.0-pr-28247-sha-834d31db sandbox` or in an existing project with `npx storybook@0.0.0-pr-28247-sha-834d31db upgrade`.
<details>
<summary>More information</summary>

| | |
| --- | --- |
| **Published version** | [`0.0.0-pr-28247-sha-834d31db`](https://npmjs.com/package/@storybook/cli/v/0.0.0-pr-28247-sha-834d31db) |
| **Triggered by** | @JReinhold |
| **Repository** | [storybookjs/storybook](https://github.com/storybookjs/storybook) |
| **Branch** | [`jeppe/fix-svelte-decorator-actions`](https://github.com/storybookjs/storybook/tree/jeppe/fix-svelte-decorator-actions) |
| **Commit** | [`834d31db`](https://github.com/storybookjs/storybook/commit/834d31dbad87f8e9889faea8f58dd0540706d8af) |
| **Datetime** | Fri Jun 14 22:34:12 UTC 2024 (`1718404452`) |
| **Workflow run** | [9523147162](https://github.com/storybookjs/storybook/actions/runs/9523147162) |

To request a new release of this pull request, mention the `@storybookjs/core` team.

_core team members can create a new canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=28247`_
</details>

### CODE REVIEW

File: code/renderers/svelte/src/components/SlotDecorator.svelte [hunk 1]
```diff
@@ -1,32 +1,52 @@
...
-  export let svelteVersion;
   export let decorator = undefined;
   export let Component;
   export let props = {};
   export let on = undefined;
-  
+  export let isOriginalStory = false;
+
   let instance;
   let decoratorInstance;
```
Comment (kasperpeulen) [inline code/renderers/svelte/src/components/SlotDecorator.svelte:13]: What are those 2 variables doing? I don't see them anywhere set in the codebase.

File: code/renderers/svelte/src/components/PreviewRender.svelte [hunk 2]
```diff
@@ -30,19 +36,17 @@
...
   // reactive, re-render on storyFn change
-  $: ({ Component, props = {}, on } = getStoryFnValue(storyFn));
+  $: ({ Component, props = {}, on, isOriginalStory } = getStoryFnValue(storyFn));
 
-  const eventsFromArgTypes = Object.fromEntries(
-    Object.entries(storyContext.argTypes)
-      .filter(([k, v]) => v.action && props[k] != null)
-      .map(([k, v]) => [v.action, props[k]])
-  );
+  // set the argTypes context, read by the last SlotDecorator that renders the original story
```
Comment (kasperpeulen) [inline code/renderers/svelte/src/components/PreviewRender.svelte:48]: Why do you need this to be context? The SlotDecorator could get the argTypes just in decorators.ts right? As an extra prop to SlotDecorator

File: code/renderers/svelte/src/components/SlotDecorator.svelte (hunk 1 above)
Comment (JReinhold) [reply code/renderers/svelte/src/components/SlotDecorator.svelte:13]: They are set in the markup below in the file, and read on line 39.
They are used to listen to events from the instances.

File: code/renderers/svelte/src/components/PreviewRender.svelte [hunk 3]
```diff
@@ -16,6 +20,8 @@
     props = {},
     /** @type {{[string]: () => {}}} Attach svelte event handlers */
     on,
+    /** @type {boolean} whether this level of the decorator chain is the last, ie. the actual story */
+    isOriginalStory,
```
Comment (kasperpeulen) [inline code/renderers/svelte/src/components/PreviewRender.svelte:24]: But this storyFn is always the complete decorated one gotten from either:
https://github.com/storybookjs/storybook/blob/595a08c44141eeadf4768ae7b54a68cd1e56c304/code/renderers/svelte/src/render.ts#L154-L157
or
https://github.com/storybookjs/storybook/blob/595a08c44141eeadf4768ae7b54a68cd1e56c304/code/renderers/svelte/src/render.ts#L77-L87

So it would always be false I guess?

File: code/renderers/svelte/src/components/PreviewRender.svelte [hunk 4]
```diff
@@ -56,4 +60,4 @@
   }
 </script>
 
-<SlotDecorator {svelteVersion} {Component} {props} on={{ ...eventsFromArgTypes, ...on }} />
+<SlotDecorator {Component} {props} {on} {isOriginalStory} />
```
Comment (kasperpeulen) [inline code/renderers/svelte/src/components/PreviewRender.svelte:63]: I think you can just set isOriginalStory={false} here

File: code/renderers/svelte/src/components/PreviewRender.svelte (hunk 3 above)
Comment (kasperpeulen) [reply code/renderers/svelte/src/components/PreviewRender.svelte:24]: Or maybe this is for the case there are no decorators?

File: code/renderers/svelte/src/components/SlotDecorator.svelte (hunk 1 above)
Comment (kasperpeulen) [reply code/renderers/svelte/src/components/SlotDecorator.svelte:13]: ah, I see, it is like a react ref?

Comment (JReinhold) [reply code/renderers/svelte/src/components/SlotDecorator.svelte:13]: Maybe you're confusing them for props? They aren't exported so they aren't props, they are just regular variables.

**Comment by kasperpeulen** [comment]
Looking more into the svelte code.

Shouldn't this line be in the SlotDecorator instead?
https://github.com/storybookjs/storybook/blob/595a08c44141eeadf4768ae7b54a68cd1e56c304/code/renderers/svelte/src/components/PreviewRender.svelte#L47-L56

Normally the component here is the `SlotDecorator` itself. The error should be there if the user forgets the Component right in a custom render function right?

File: code/renderers/svelte/src/components/PreviewRender.svelte (hunk 2 above)
Comment (kasperpeulen) [reply code/renderers/svelte/src/components/PreviewRender.svelte:48]: https://github.com/storybookjs/storybook/blob/1b17dfee562a85be19013071f1d7703b945d9b2a/code/renderers/svelte/src/decorators.ts#L62-L69

File: code/renderers/svelte/src/components/SlotDecorator.svelte [hunk 5]
```diff
@@ -1,32 +1,52 @@
...
+        .filter(([key, value]) => value.action && props[key] != null)
+        .map(([key, value]) => [value.action, props[key]])
+    );
     // Attach Svelte event listeners in Svelte v4
     // In Svelte v5 this is not possible anymore as instances are no longer classes with $on() properties, so it will be a no-op
     onMount(() => {
-      Object.entries(on).forEach(([eventName, eventCallback]) => {
-        // instance can be undefined if a decorator doesn't have <slot/>
+      Object.entries({ ...eventsFromArgTypes, ...on }).forEach(([eventName, eventCallback]) => {
+        // instance can be undefined if a decorator doesn't have a <slot/>
```
Comment (kasperpeulen) [inline code/renderers/svelte/src/components/SlotDecorator.svelte:38]: shouldn't that be an error though?

File: code/renderers/svelte/src/components/SlotDecorator.svelte (hunk 1 above)
Comment (kasperpeulen) [reply code/renderers/svelte/src/components/SlotDecorator.svelte:13]: I mean it is like:
```tsx
const instance = useRef();

<div ref={instance} />
```
In react?

File: code/renderers/svelte/src/components/SlotDecorator.svelte (hunk 5 above)
Comment (kasperpeulen) [inline code/renderers/svelte/src/components/SlotDecorator.svelte:38]: >  // instance can be undefined if a decorator doesn't have a <slot/>

shouldn't that be an error though?

File: code/renderers/svelte/src/components/PreviewRender.svelte (hunk 3 above)
Comment (JReinhold) [reply code/renderers/svelte/src/components/PreviewRender.svelte:24]: Exactly, undecorated.

File: code/renderers/svelte/src/components/SlotDecorator.svelte (hunk 1 above)
Comment (JReinhold) [reply code/renderers/svelte/src/components/SlotDecorator.svelte:13]: yes you could compare it to a ref, it's just a regular long-living variable.

(my previous message wasn't a response to your react message, we basically posted them at the same time)

File: code/renderers/svelte/src/components/SlotDecorator.svelte (hunk 5 above)
Comment (JReinhold) [reply code/renderers/svelte/src/components/SlotDecorator.svelte:38]: That's debatable, I guess it's similar to not calling `storyFn()` in a React decorator. Would that be invalid? 🤷

File: code/renderers/svelte/src/components/PreviewRender.svelte (hunk 2 above)
Comment (JReinhold) [reply code/renderers/svelte/src/components/PreviewRender.svelte:43]: good call. fixed!

**Comment by JReinhold** [comment]
> Shouldn't this line be in the SlotDecorator instead? ... Normally the component here is the SlotDecorator itself. The error should be there if the user forgets the Component right in a custom render function right?

@kasperpeulen 

You are right! I tried that, but it's not as easy as I thought with our current data structure. Only the `PreviewRender` gets the `showError`-function, and passing that down through all `SlotDecorator`s wasn't as easy as it sounds, because the children could be either `SlotDecorator`s or users' components.

In fact it's also guarding against a very rare case, because we're setting `Component` in almost all cases here:

https://github.com/storybookjs/storybook/blob/6dea5b0ee8f3a08a13d8366ae8283d7e9a0c6297/code/renderers/svelte/src/decorators.ts#L44-L58

The only way I could reach the error was by not setting `component` on meta + not returning anything from `render()`, which seems very unlikely to me.

I vote leave as-is, the trade off is not there right now.

File: code/renderers/svelte/src/components/PreviewRender.svelte [hunk 6]
```diff
@@ -15,6 +15,8 @@
     props = {},
     /** @type {{[string]: () => {}}} Attach svelte event handlers */
     on,
+    /** @type {any} whether this level of the decorator chain is the last, ie. the actual story */
```
Comment (kasperpeulen) [inline code/renderers/svelte/src/components/PreviewRender.svelte:18]: This comment seems incorrect.

**Review by kasperpeulen — APPROVED** [review]
LGTM
