### PR TITLE
MDX: Replace remark by rehype plugins

### LINKED ISSUE #21838: Upgrade `remark-slug` and `remark-external-links` are deprecated
### Describe the bug

We use two remark plugins to support our MDX functionality in `addon-docs` and `builder-vite`:

1. [`remark-slug`](https://github.com/remarkjs/remark-slug)
2. [`remark-external-links`](https://github.com/remarkjs/remark-external-links)

Both of these plugins are marked as deprecated and the maintainer (who also maintains MDX) advices to switch to their rehype equivalent instead, [`rehype-slug`](https://github.com/rehypejs/rehype-slug) and [`rehype-external-links`](https://github.com/rehypejs/rehype-external-links). 

If it doesn't produce any breaking changes, we should switch them over.

### To Reproduce

_No response_

### System

_No response_

### Additional context

`remark-slug` is used to automaticall add `id` to headings, which will create the link functionality to headings. That functionality should be preserved.

`remark-external-links` adds `target="_blank"` to all external links.

### PR DESCRIPTION
**Pull request by valentinpalkovic**
Closes https://github.com/storybookjs/storybook/issues/21838

## What I did

Replaced deprecated remark plugins by their rehype equivalents.

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

File: code/addons/docs/src/preset.ts [hunk 1]
```diff
@@ -1,6 +1,6 @@
 import { dirname, join } from 'path';
-import remarkSlug from 'remark-slug';
-import remarkExternalLinks from 'remark-external-links';
+import remarkSlug from 'rehype-slug';
+import remarkExternalLinks from 'rehype-external-links';
```
Comment (JReinhold) [inline code/addons/docs/src/preset.ts:3]:
```suggestion
import rehypeSlug from 'rehype-slug';
import rehypeExternalLinks from 'rehype-external-links';
```

File: code/addons/docs/src/plugins/mdx-plugin.ts [hunk 2]
```diff
@@ -34,9 +34,11 @@ export async function mdxPlugin(options: Options): Promise<Plugin> {
             '/dist/shims/mdx-react-shim'
           ),
           ...mdxPluginOptions?.mdxCompileOptions,
-          remarkPlugins: [remarkSlug, remarkExternalLinks].concat(
-            mdxPluginOptions?.mdxCompileOptions?.remarkPlugins ?? []
-          ),
+          remarkPlugins: [
+            ...(mdxPluginOptions?.mdxCompileOptions?.remarkPlugins ?? []),
```
Comment (JReinhold) [inline code/addons/docs/src/plugins/mdx-plugin.ts:38]:
```suggestion
          rehypePlugins: [
            ...(mdxPluginOptions?.mdxCompileOptions?.rehypePlugins ?? []),
```

I don't think this even works in the current state.

File: code/addons/docs/src/preset.ts [hunk 3]
```diff
@@ -48,9 +48,11 @@ async function webpack(
         '/dist/shims/mdx-react-shim'
       ),
       ...mdxPluginOptions.mdxCompileOptions,
-      remarkPlugins: [remarkSlug, remarkExternalLinks].concat(
-        mdxPluginOptions?.mdxCompileOptions?.remarkPlugins ?? []
-      ),
+      rehypePlugins: [
+        ...(mdxPluginOptions?.mdxCompileOptions?.rehypePlugins ?? []),
+        remarkSlug,
+        remarkExternalLinks,
```
Comment (JReinhold) [inline code/addons/docs/src/preset.ts:54]:
```suggestion
        rehypeSlug,
        rehypeExternalLinks,
```

**Review by JReinhold — CHANGES_REQUESTED** [review]

**Review by JReinhold — APPROVED** [review]
