### PR TITLE
Vitest addon: Handle Playwright installation errors gracefully

### LINKED ISSUE #32117: [Bug]: Storybook cannot be installed in a Stackblitz or Bolt.new environment
### Describe the bug

When attempting to install Storybook, `@storybook/addon-vitest` tries to install playwright, which hangs with the following error message:

```
› Configuring Playwright with Chromium (this might take some time):
  npx playwright install chromium --with-deps
Error running postinstall script for @storybook/addon-vitest
Error: Command failed with exit code 1: npx playwright install chromium --with-deps
BEWARE: your OS is not officially supported by Playwright; installing dependencies for ubuntu20.04-x64 as a fallback.
Installing dependencies...
Switching to root user to install dependencies...
Failed to install browsers
Error: spawn su ENOENT
    at makeError (/home/projects/vitejs-vite-9hr4xbcr/node_modules/storybook/dist/common/index.cjs:24517:67)
    at handlePromise (/home/projects/vitejs-vite-9hr4xbcr/node_modules/storybook/dist/common/index.cjs:25135:15)
    at async postInstall (/home/projects/vitejs-vite-9hr4xbcr/node_modules/@storybook/addon-vitest/dist/postinstall.js:94:896)
    at async postinstallAddon (/home/.npm/_npx/e735b42ccbe56908/node_modules/@storybook/cli/dist/bin/index.cjs:83:873)
    at async add (/home/.npm/_npx/e735b42ccbe56908/node_modules/@storybook/cli/dist/bin/index.cjs:85:2082) {
  shortMessage: 'Command failed with exit code 1: npx playwright install chromium --with-deps',
  command: 'npx playwright install chromium --with-deps',
  escapedCommand: '"npx playwright install chromium --with-deps"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: 'Installing dependencies...\n' +
    'Switching to root user to install dependencies...\n' +
    'Failed to install browsers\n' +
    'Error: spawn su ENOENT',
  stderr: 'BEWARE: your OS is not officially supported by Playwright; installing dependencies for ubuntu20.04-x64 as a fallback.',
  cwd: '/home/projects/vitejs-vite-9hr4xbcr',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

### Reproduction link

https://stackblitz.com/edit/vitejs-vite-9hr4xbcr

### Reproduction steps

1. Go to https://stackblitz.com/ and create a new React project
2. Init Storybook via `npx storybook@latest init --yes`

### System

```bash
-
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ndelangen**
Closes https://github.com/storybookjs/storybook/issues/32117

## What I did

I changed the postinstall to continue (with a warning) when the install of playwright failed

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

## Greptile Summary

This PR adds graceful error handling to the Playwright installation step in the `@storybook/addon-vitest` postinstall process. The change wraps the `npx playwright install chromium --with-deps` command in a try-catch block, allowing the addon installation to continue even when Playwright installation fails.

The modification is minimal and targeted - it only affects the Playwright configuration section of the `postInstall` function in `code/addons/vitest/src/postinstall.ts`. When Playwright installation fails (which commonly occurs in restricted environments like StackBlitz or Bolt.new), the error is caught and a user-friendly message is displayed advising manual installation, but the rest of the addon setup process continues normally.

This change fits well within the broader postinstall architecture, which already handles various installation scenarios and user prompts. The postinstall function is responsible for setting up multiple components including Vitest dependencies, configuration files, and optional features like the accessibility addon. By making Playwright installation non-blocking, the PR ensures that users can still benefit from the core Vitest addon functionality even in environments where Playwright cannot be automatically installed.

## Confidence score: 4/5

- This PR is safe to merge with minimal risk as it only adds error handling without changing core functionality
- Score reflects the simple, targeted nature of the change that improves user experience in edge cases
- Pay close attention to the error handling implementation to ensure proper logging occurs

### CODE REVIEW

File: code/addons/vitest/src/postinstall.ts [hunk 1]
```diff
@@ -309,10 +309,14 @@ export default async function postInstall(options: PostinstallOptions) {
...
-      command: 'npx',
-      args: ['playwright', 'install', 'chromium', '--with-deps'],
-    });
+    try {
+      await packageManager.executeCommand({
+        command: 'npx',
+        args: ['playwright', 'install', 'chromium', '--with-deps'],
+      });
+    } catch (e) {
+      console.error('Failed to install Playwright. Please install it manually');
```
Comment (shilman) [inline code/addons/vitest/src/postinstall.ts:318]: Don't we have guidelines for how to log errors now (so that we can swap in clack)? cc @yannbf

**Review by shilman — COMMENTED** [review]
@ndelangen do we want to patch this back?
