### PR TITLE
Automigrations: Enhance experience for upgrades from Storybook 6 to 8

### LINKED ISSUE #25975: [Bug]: Upgrade from Storybook 6 to Storybook 8 fails if storybook or @storybook/cli isn't installed
### Describe the bug

The `upgrade` command cannot determine the user's Storybook version if `storybook` or `@storybook/cli` aren't listed in the user's package.json. Additionally, the `automigrate` command isn't doing anything in this case because the actual Storybook version cannot be detected.

### To Reproduce

1. Checkout https://github.com/washingtonpost/wpds-ui-kit
2. Run `npx storybook@next upgrade`
3. The `banner` shows previous version `0.0.0`

Alternatively:

1. Checkout https://github.com/washingtonpost/wpds-ui-kit
2. Run `npx storybook@next automigrate`
3. The automigration says it is unable to determine the Storybook version so the automigrations will be skipped.

### System

_No response_

### Additional context

_No response_

### LINKED ISSUE #25989: [Bug]: Module not found entry-preview-docs
### Describe the bug

I upgrade from 6 to 7 today and have so many issues. This is a react native project. 

I've found some issues have to do with some of the addon-ondevice-* pakages with not being able to find @storybook/global. I removed those dependencies to make this issue maybe a little easier.

I tried to use the upgrade  with `npx storybook@latest upgrade` and that fails with the following

```
Error: Command failed with exit code 1: yarn info --name-only --recursive "storybook" "@storybook/cli" "storybook,@storybook/cli"
Usage Error: No package matched your request

$ yarn info [-A,--all] [-R,--recursive] [-X,--extra #0] [--cache] [--dependents] [--manifest] [--name-only] [--virtuals] [--json] ...
    at makeError (<path>\node_modules\execa\lib\error.js:60:11)
    at handlePromise (<path>\node_modules\execa\index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Yarn2Proxy.executeCommand (<path>\node_modules\@storybook\cli\dist\generate.js:56:1607)
    at async Yarn2Proxy.findInstallations (<path>\node_modules\@storybook\cli\dist\generate.js:60:4629)
    at async getInstalledStorybookVersion (<path>\node_modules\@storybook\cli\dist\generate.js:455:2297)
    at async doUpgrade (<path>\node_modules\@storybook\cli\dist\generate.js:456:4728)
    at async withTelemetry (<path>\node_modules\@storybook\core-server\dist\index.js:65:3948)
    at async upgrade (<path>\node_modules\@storybook\cli\dist\generate.js:463:1752)
```

So I followed the migration guide and after that

package.json dependencies

```
  "dependencies": {
    "@expo/vector-icons": "^13.0.0",
    "@expo/webpack-config": "^19.0.0",
    "@react-native-community/datetimepicker": "7.2.0",
    "@react-native-community/eslint-config": "3.2.0",
    "@react-native-community/slider": "4.4.2",
    "@react-native-masked-view/masked-view": "0.2.9",
    "@react-native-material/core": "1.3.7",
    "@react-navigation/bottom-tabs": "6.4.3",
    "@react-navigation/drawer": "6.6.2",
    "@react-navigation/material-top-tabs": "6.6.2",
    "@react-navigation/native": "6.0.16",
    "@react-navigation/stack": "6.3.10",
    "@sentry/react-native": "5.10.0",
    "axios": "1.3.6",
    "copy-webpack-plugin": "^11.0.0",
    "dotenv": "16.0.3",
    "expo": "^49.0.20",
    "expo-application": "~5.3.0",
    "expo-auth-session": "~5.0.2",
    "expo-build-properties": "~0.8.3",
    "expo-constants": "~14.4.2",
    "expo-dev-client": "~2.4.12",
    "expo-device": "~5.4.0",
    "expo-font": "~11.4.0",
    "expo-linear-gradient": "~12.3.0",
    "expo-localization": "~14.3.0",
    "expo-random": "~13.2.0",
    "expo-splash-screen": "~0.20.5",
    "expo-status-bar": "~1.6.0",
    "expo-updates": "~0.18.17",
    "i18n-js": "4.2.3",
    "jest": "^29.2.1",
    "lodash": "4.17.21",
    "react": "18.2.0",
    "react-devtools-core": "4.28.0",
    "react-dom": "18.2.0",
    "react-hook-form": "7.43.9",
    "react-is": "^18.2.0",
    "react-native": "0.72.6",
    "react-native-calendars": "^1.1293.0",
    "react-native-dropdown-picker": "^5.4.6",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-modal": "^13.0.1",
    "react-native-pager-view": "6.2.0",
    "react-native-reanimated": "~3.3.0",
    "react-native-root-siblings": "4.1.1",
    "react-native-screens": "~3.22.0",
    "react-native-svg": "13.9.0",
    "react-native-tab-view": "3.5.1",
    "react-native-toast-message": "2.1.6",
    "react-native-web": "~0.19.6",
    "react-native-webview": "13.2.2",
    "react-query": "3.39.3",
    "recoil": "0.7.6",
    "sentry-expo": "~7.1.0",
    "victory-native": "36.6.8"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "7.1.6",
    "@react-native-async-storage/async-storage": "1.18.2",
    "@storybook/addon-ondevice-actions": "7.6.15",
    "@storybook/addon-ondevice-controls": "7.6.15",
    "@storybook/react-native": "7.6.15",
    "@svgr/webpack": "^8.1.0",
    "@types/lodash": "4.14.197",
    "@types/react": "~18.2.14",
    "@types/xdate": "^0.8.33",
    "@typescript-eslint/eslint-plugin": "^6.7.0",
    "@typescript-eslint/parser": "^6.7.0",
    "babel-loader": "8.3.0",
    "cross-env": "^7.0.3",
    "eslint": "^8.49.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-import-resolver-typescript": "3.5.2",
    "eslint-plugin-import": "2.26.0",
    "eslint-plugin-jest": "27.1.6",
    "eslint-plugin-prettier": "4.2.1",
    "eslint-plugin-react": "7.31.11",
    "eslint-plugin-sort-keys-fix": "1.1.2",
    "eslint-plugin-typescript-sort-keys": "2.3.0",
    "prettier": "2.8.7",
    "react-native-safe-area-context": "4.6.3",
    "react-native-svg-transformer": "^1.1.0",
    "typescript": "^5.1.3"
  },
}
```

Metro's metro.config.js

```
const path = require('path');

const { generate } = require('@storybook/react-native/scripts/generate');
const { getDefaultConfig } = require('expo/metro-config');

generate({
  configPath: path.resolve(__dirname, './.storybook'),
});

const config = getDefaultConfig(__dirname);

config.transformer.unstable_allowRequireContext = true;

config.transformer.assetPlugins = [
  ...config.transformer.assetPlugins,
  'expo-asset/tools/hashAssetFiles',
];
config.transformer.babelTransformerPath = require.resolve(
  'react-native-svg-transformer',
);

config.resolver.sourceExts = [...config.resolver.sourceExts, 'mjs', 'svg'];

config.resolver.assetExts = config.resolver.assetExts.filter(
  (ext) => ext !== 'svg',
);

module.exports = config;
```

Storybook's index.ts

```
import AsyncStorage from '@react-native-async-storage/async-storage';
import { view } from './storybook.requires';

const StorybookUIRoot = view.getStorybookUI({
  storage: {
    getItem: AsyncStorage.getItem,
    setItem: AsyncStorage.setItem,
  },
});

export default StorybookUIRoot;
```

Storybook's main.ts

```
import { StorybookConfig } from '@storybook/react-native';

const main: StorybookConfig = {
  stories: ['./stories/**/*.stories.?(ts|tsx|js|jsx)'],
  addons: ['@storybook/addon-ondevice-controls', '@storybook/addon-ondevice-actions'],
};

export default main;
```

Storybook's preview.tsx

```
import type { Preview } from '@storybook/react';

const preview: Preview = {
  parameters: {
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/,
      },
    },
  },
};

export default preview;
```

My app's entry point

```
const App: React.FC = () => {
  return (
    ... app view stuff
  );
};

// Default to rendering your app
let AppEntryPoint = App;

// Render Storybook if storybookEnabled is true
if (Constants.expoConfig.extra.storybookEnabled === true) {
  console.warn('Storybook mode enabled');
  AppEntryPoint = require('../.storybook').default;
}

registerRootComponent(AppEntryPoint);
```

When I compile and run I get this in the terminal

```
ERROR in ./node_modules/@storybook/react-native/dist/preview.js:25
Module not found: Package path ./dist/entry-preview-docs is not exported from package <path>\node_modules\@storybook\react (see exports field in <path>\node_modules\@storybook\react\package.json)
  23 | });
  24 | module.exports = __toCommonJS(preview_exports);
> 25 | var import_entry_preview_docs = require("@storybook/react/dist/entry-preview-docs");
  26 | var import_docs_tools = require("@storybook/docs-tools");
  27 | var preview_default = {
  28 |   argTypesEnhancers: [import_docs_tools.enhanceArgTypes],
```

It still attempts to run and I get this in the browser console

```
Uncaught Error: Cannot find module '@storybook/react/dist/entry-preview-docs'
    at webpackMissingModule (preview.js:25:1)
    at ./node_modules/@storybook/react-native/dist/preview.js (preview.js:25:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./.storybook/storybook.requires.ts (storybook.requires.ts:25:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./.storybook/index.ts (.(:31:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/App.tsx (App.tsx:58:1)
    at __webpack_require__ (bootstrap:24:1)
    at startup:6:1
    at startup:6:1
```

### To Reproduce

_No response_

### System

```bash
Storybook Environment Info:

  System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i7-13800H
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.6.2 - C:\Program Files\nodejs\yarn.CMD <----- active
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (121.0.2277.112)
  npmPackages:
    @storybook/react-native: 7.6.15 => 7.6.15
```

### Additional context

_No response_

### LINKED ISSUE #26032: Auto migration: Adjust migrations to run only from one particular version to another
Automigrations and Codemods should run only if they make sense. Sometimes, an auto migration or codemod was written for one particular major version. The following lists will show which automigrations should run in particular scenarios:

## Automigrations needed from `6 to 7/8`:

```
cra5
vue3
webpack5
builderVite
sbScripts
newFrameworks
sbBinary
removedGlobalClientAPIs
mdxgfm
autodocsTrue
angularBuilders
angularBuildersMultiproject
```

## Automigrations needed from `6/7 to 8`:

```
wrapRequire
mdx1to2
eslintPlugin
reactDocgen
removeReactDependency
```

## Automigrations needed from `6 to 7` (remove them in Storybook 8):

```
missingBabelRc
addReact
incompatibleAddons
nodeJsRequirement
// revisit that one
mdx-1-to-2
```

### PR DESCRIPTION
**Pull request by valentinpalkovic**
Closes #26032, closes #25975, closes #25989

## What I did

Added version range checks to all automigrations to ensure that the automigrations only run for particular version upgrades. For example, upgrade from 6 to 8 or 7 to 8. The version check only happens during `npx storybook upgrade` and not during `npx storybook automigrate`.

The following auto migrations were removed in Storybook 8 because they aren't necessary anymore:

- incompatible-addons (Storybook doctor covers this)
- vite-4 (added an autoblocker)

Additionally, I have optimized the logic of how the Storybook version is evaluated so that it is also compatible with Storybook 6.

#### Storybook 6

1. Checkout a Storybook 6 Repository (e.g. https://github.com/RocketCommunicationsInc/astro/tree/main/packages/web-components)
2. Run `npx storybook@0.0.0-pr-26067-sha-1d9e1147 upgrade`

Make sure that only the following automigrations were triggered when applicable:

- angular-builders-multiproject
- angular-builders
- autodocsTrue
- bare-mdx-stories-glob
- builder-vite
- cra5
- eslintPlugin
- mdx1to3
- github-flavored-markdown-mdx
- new-frameworks
- react-docgen
- remove-argtypes-regex
- removedglobalclientapis
- remove-jest-testing-library
- storybook-binary
- sb-scripts
- storyshots-migration
- viteConfigFile
- vue3
- webpack5-compiler-setup
- webpack5
- wrap-require

#### Storybook 7

1. Checkout a Storybook 7 Repository
2. Run `npx storybook@0.0.0-pr-26067-sha-1d9e1147 upgrade`

Make sure that only the following automigrations were triggered when applicable:

- eslintPlugin
- react-docgen
- remove-argtypes-regex
- remove-jest-testing-library
- storyshots-migration
- viteConfigFile
- webpack5-compiler-setup

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [x] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

#### Test Results - Freecodecamp (React - SB6.5.16)

The following automigrations got triggered:

```
new-frameworks, storybook-binary, sb-scripts, github-flavored-markdown-mdx, autodocsTrue, react-docgen
webpack5-compiler-setup, mdx1to3
``` 

**Issues:**
- The user will not get notified, that `@storybook/addon-postcss` doesn't work anymore with Storybook 8
- The `bare-mdx-stories-glob` codemod isn't applied automatically, which it should
- The `@storybook/addons` doesn't exist anymore. This is not caught be automigrations. Manual migration required.
- The mdx1-to-3 automigration doesn't link to a 6-to-8 migration document
- The Introduction.stories.mdx file gets transformed from the `bare-mdx-stories-glob` codemod to this:

```
import Code from './assets/code-brackets.svg';
import Colors from './assets/colors.svg';
import Comments from './assets/comments.svg';
import Direction from './assets/direction.svg';
import Flow from './assets/flow.svg';
import Plugin from './assets/plugin.svg';
import Repo from './assets/repo.svg';
import StackAlt from './assets/stackalt.svg';

export default {
  title: 'Example/Introduction'
};
```

The codemod should actually not create a `stories.ts` file, if there are actually no components.

#### Test Results - Astro UXDS Web Component (Web Components - SB6.4.22)

**Issues:**
- All `stories.mdx` files aren't renamed, because 5 `stories.mdx` files cannot be transformed. Reported here: https://github.com/storybookjs/storybook/issues/26140

#### Test Results - Mealdrop (React SB7.6.0)

The following automigrations got triggered

```
github-flavored-markdown-mdx, remove-argtypes-regex
```

#### Test Results - In General

All major package managers (yarn 1, yarn berry, npm and pnpm) were tested to ensure version detection works.

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This pull request has been released as version `0.0.0-pr-26067-sha-847cb0b0`. Try it out in a new sandbox by running `npx storybook@0.0.0-pr-26067-sha-847cb0b0 sandbox` or in an existing project with `npx storybook@0.0.0-pr-26067-sha-847cb0b0 upgrade`.
<details>
<summary>More information</summary>

| | |
| --- | --- |
| **Published version** | [`0.0.0-pr-26067-sha-847cb0b0`](https://npmjs.com/package/@storybook/cli/v/0.0.0-pr-26067-sha-847cb0b0) |
| **Triggered by** | @valentinpalkovic |
| **Repository** | [storybookjs/storybook](https://github.com/storybookjs/storybook) |
| **Branch** | [`valentin/6-to-8-automigrations`](https://github.com/storybookjs/storybook/tree/valentin/6-to-8-automigrations) |
| **Commit** | [`847cb0b0`](https://github.com/storybookjs/storybook/commit/847cb0b0ea2d07ba5112312b9096cdc079b2639c) |
| **Datetime** | Mon Feb 19 09:46:08 UTC 2024 (`1708335968`) |
| **Workflow run** | [7957547061](https://github.com/storybookjs/storybook/actions/runs/7957547061) |

To request a new release of this pull request, mention the `@storybookjs/core` team.

_core team members can create a new canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=26067`_
</details>

### CODE REVIEW

File: code/lib/cli/src/automigrate/fixes/prompt-remove-react.ts [hunk 1]
```diff
@@ -3,10 +3,15 @@ import semver from 'semver';
...
 import type { Fix } from '../types';
 
+// This fix is only relevant for projects using Storybook 8.0.0-alpha.4 or later
+const minimumStorybookVersion = '8.0.0-alpha.4';
+
 export const removeReactDependency: Fix<{}> = {
   id: 'remove-react-dependency',
   promptOnly: true,
 
+  versionRange: ['>=7 <8.0.0-alpha.4', `>=${minimumStorybookVersion}`],
```
Comment (valentinpalkovic) [inline code/lib/cli/src/automigrate/fixes/prompt-remove-react.ts:13]:
```suggestion
  versionRange: [`>=7 < ${minimumStorybookVersion}`, `>=${minimumStorybookVersion}`],
```

File: code/lib/cli/src/automigrate/fixes/eslint-plugin.ts [hunk 2]
```diff
@@ -26,6 +26,8 @@ interface EslintPluginRunOptions {
 export const eslintPlugin: Fix<EslintPluginRunOptions> = {
   id: 'eslintPlugin',
 
+  versionRange: ['<8', '>=7'],
```
Comment (yannbf) [inline code/lib/cli/src/automigrate/fixes/eslint-plugin.ts:29]:
```suggestion
  versionRange: ['>=7', '<8',],
```

File: code/lib/cli/src/automigrate/fixes/mdx-gfm.ts [hunk 3]
```diff
@@ -83,11 +80,11 @@ export const mdxgfm: Fix<Options> = {
     return dedent`
       In MDX1 you had the option of using GitHub flavored markdown.
 
-      Storybook 8.0 uses MDX3 for compiling MDX, and thus no longer supports GFM out of the box.
+      Storybook >= 8.0 uses MDX3 for compiling MDX, and thus no longer supports GFM out of the box.
       Because of this you need to explicitly add the GFM plugin in the addon-docs options:
       https://storybook.js.org/docs/react/writing-docs/mdx#lack-of-github-flavored-markdown-gfm
 
-      We recommend you follow the guide on the link above, however we can add a temporary storybook addon that helps make this migration easier.
+      We recommend you follow the guide on the link above, however we can add a temporary Storybook addon that helps make this migration easier.
```
Comment (yannbf) [inline code/lib/cli/src/automigrate/fixes/mdx-gfm.ts:87]:
```suggestion
      We recommend that you follow the guide in the link above; however, we can add a temporary Storybook addon to help make this migration easier.
```

File: code/lib/cli/src/automigrate/types.ts [hunk 4]
```diff
@@ -23,13 +23,19 @@ export interface RunOptions<ResultType> {
  * promptType defines how the user will be prompted to apply an automigration fix
  * - auto: the fix will be applied automatically
  * - manual: the user will be prompted to apply the fix
- * - notification: the user will be notified about the some changes. A fix isn't required
+ * - notification: the user will be notified about some changes. A fix isn't required, thought
```
Comment (yannbf) [inline code/lib/cli/src/automigrate/types.ts:26]:
```suggestion
 * - notification: the user will be notified about some changes. A fix isn't required, though
```

**Review by yannbf — APPROVED** [review]
LGTM!

**Review by yannbf — APPROVED** [review]
LGTM!

File: code/lib/core-common/src/js-package-manager/Yarn2Proxy.ts [hunk 5]
```diff
@@ -104,22 +104,17 @@ export class Yarn2Proxy extends JsPackageManager {
   }
 
   public async findInstallations(pattern: string[]) {
+    console.log(['info', '--name-only', '--recursive', ...pattern].join(' '));
```
Comment (valentinpalkovic) [inline code/lib/core-common/src/js-package-manager/Yarn2Proxy.ts:107]:
```suggestion
```
