### PR TITLE
Svelte: Fix docs generating when using `lang="ts"` or optional chaining

### LINKED ISSUE #24008: [Bug]: Elvis (?) is breaking autodocs and 'show source' for Svelte components
### Describe the bug

Under a number of circumstances when an Elvis (?) operator is being used, the "autodocs" function stops working and the jsdoc description does not appear inside the storybook properties documentation. Also, the 'show source' function starts delivering incorrect and confusing code.  

image

### To Reproduce

I used the Button example of a new Svelte based Storybook installation for simplicity:
See line 14 as an example:

https://stackblitz.com/edit/github-tqvcar?file=src%2Fstories%2FButton.svelte

Furthermore, I realized that "?"- operators inside the Svelte components HTML / Svelte code, lead to the same situation. 

Also the description must be before the @type jsdoc command and not after. Otherwise, it does not appear.

### System

```bash
Environment Info:

  System:
    OS: macOS 13.4.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 18.4.0 - ~/.nvm/versions/node/v18.4.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.12.1 - ~/.nvm/versions/node/v18.4.0/bin/npm
  Browsers:
    Chrome: 116.0.5845.110
    Safari: 16.5.2
  npmPackages:
    @storybook/addon-essentials: ^7.4.0 => 7.4.0 
    @storybook/addon-interactions: ^7.4.0 => 7.4.0 
    @storybook/addon-links: ^7.4.0 => 7.4.0 
    @storybook/blocks: ^7.4.0 => 7.4.0 
    @storybook/jest: ^0.2.1 => 0.2.2 
    @storybook/svelte: ^7.4.0 => 7.4.0 
    @storybook/sveltekit: ^7.4.0 => 7.4.0 
    @storybook/test-runner: ^0.13.0 => 0.13.0 
    @storybook/testing-library: ^0.2.0 => 0.2.0
```

### Additional context

- https://github.com/storybookjs/addon-svelte-csf/issues/122
- https://github.com/storybookjs/storybook/issues/23904
- https://github.com/storybookjs/storybook/issues/15891

### PR DESCRIPTION
**Pull request by j3rem1e**
Closes #24008 #24137

## What I did

When sveltedoc-parser fails to parse a Svelte component, Storybook was not injecting the documentation metadata.
This metadata was used to determine the component name. If the information is missing, then we use `component.name`, which is not always good. For example, when using vite and HMR, svelte generate a proxy named `Proxy<Component>` and Storybook was displaying this name instead of the real component name.

This PR always injects documentation metadata, with the real name of the component (build at compile time).

Moreover, sveltedoc-parser is configured to parse ecmascript v9 and fails to parse elvis operator, or "??". This PR also change sveltedoc-parser to enable ecmascript v12. However, the configuration is not officially exposed so I have to patch the lib.. I have proposed a real PR to the author of the library.

#### The changes in this PR are covered in the following automated tests:
- [X] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

1. Generate a svelte-vite sandbox
2. Start the storybook in dev mode
3. Modify "Button.svelte" and add "??" or "?." somewhere
4. The source generated for the stories should be valid. Without this PR, it shows `<Proxy<Button> .../>` instead.

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Comment by j3rem1e** [comment]
Fix #24008

**Comment by j3rem1e** [comment]
@JReinhold The "sveltedoc-parser" plugin is duplicated between svelte and webpack. I tried to mutualise the code, but I didn't know where I can put it. the "@storybook/svelte" is only build for a browser, and can't host code for the server.

**Review by JReinhold — CHANGES_REQUESTED** [review]
Thanks for this! 💪

Could you add an e2e test for this?
Ideally it would be enough with a story to test this, but since this is docs related it's more involved than that, because Chromatic doesn't capture docs.

To do this:

1. Add a stories-file with autodocs to https://github.com/storybookjs/storybook/tree/next/code/renderers/svelte/template/stories that demonstrates this behavior.

2. You can test out the stories you're writing by generating a sandbox with `yarn task --task sandbox --template svelte-vite/default-ts`, it should symlink your stories into the sandbox.
2. Add an e2e test file at `code/e2e-tests/framework-svelte-vite.spec.ts` that visits the docs page and asserts that the source content is correct. You can see how this is done for NextJS here (the important part is to skip if the framework doesn't match). https://github.com/storybookjs/storybook/blob/next/code/e2e-tests/framework-nextjs.spec.ts

Let me know if this guidance isn't enough for you to move forward with it, or if you need me to write a test for this instead.

> The "sveltedoc-parser" plugin is duplicated between vite and webpack

That's okay, that's just how it is structured, I don't think it's a big deal, but thanks for considering it. The best we can do is to link between the two files with a comment, so that if it's updated one place we remember to update it both places.

**Comment by j3rem1e** [comment]
I had to remove the e2e test of the documentation for typescript sandbox.

vite uses esbuild which removes jsdoc from the component - the doc is then not visible by the parser.
And it's not possible today to use `vitePreprocess` without esbuild. The documentation works  when I use the "old" svelte-prepocess instead of `vitePreprocess`.

@benmccann maybe you know a workaround for this ?

**Comment by benmccann** [comment]
Hmm. Maybe we will need to tell people to use `svelte-preprocess` rather than `vitePreprocess` when using Storybook? Unless @dominikg or @bluwy have any other ideas

**Comment by dominikg** [comment]
> Hmm. Maybe we will need to tell people to use `svelte-preprocess` rather than `vitePreprocess` when using Storybook? Unless @dominikg or @bluwy have any other ideas

that would not be good. they don't work the same so output can differ. 

why exactly is the name parsed from a comment in the output at all? 99.9% it's sufficient to derive it from the filename (that's what svelte is doing too).

And for the other 0.1, you could just have an option?

**Comment by j3rem1e** [comment]
The issue is not about the name.

We use jsdoc to extract documentation about the properties, slots, events and the component description. And metadata as @slot and @wrapper.

And esbuild removes all comments.

**Comment by j3rem1e** [comment]
We should maybe only preprocess for typescript with svelte-preprocess in the plugin extracting the documentation.

**Comment by bluwy** [comment]
I'm not familiar with the flow, but why are we extracting the docs after processing? Shouldn't it extract the docs before that as the user authored? For example, if the Svelte component property is typed `export let foo: string`, preprocessing strips the `string` type away. If the `string` type were to be "saved" somewhere, maybe the component name could be placed there too?

**Comment by j3rem1e** [comment]
> I'm not familiar with the flow, but why are we extracting the docs after processing? Shouldn't it extract the docs before that as the user authored? For example, if the Svelte component property is typed `export let foo: string`, preprocessing strips the `string` type away. If the `string` type were to be "saved" somewhere, maybe the component name could be placed there too?

The extraction of the documentation today is not done by Storybook but with another lib which doesn't supports typescript:

- sveltedoc-parser uses espree to parse the script tag, and doesn't supports typescript
- I looked a sveld, which uses the svelte compiler, which doesn't supports typescript either. Sveld have a preprocessing phase with the old "svelte-preprocess". It can see the documentation, the jsdoc @type like sveltedoc-parser, but not the typescript type

Today, there is no easy way to parse a typescript svelte component. Maybe svelte2tsx can be used to, but afaik it's not really documented. To me, extracting the documentation/slots/properties should be part of the official svelte tooling, and not reimplemented by other tools - it depends to much of the internal implementation of Svelte ^^

I think the best we can do today is reusing the sveld strategy by not using the svelte.config.js preprocessor, but instead only a typescript() preprocessor. The parsing of the documentation is done by a special loader which shouldn't interfere with the "real" loader/preprocessor.

A second step is maybe to reuse sveld instead of sveltedoc-parser but today some features are missing, like extracting jsoc keywords and slots documentation by parsing the hml template.

**Comment by j3rem1e** [comment]
I have created #24137 to follow this issue, as it's not directly related to this PR.

**Comment by benmccann** [comment]
@dummdidumm do you have any tips on using svelte2tsx? Should we ask the authors of sveld and sveltedoc-parser to switch to it? Is this something we might be able to improve as part of Svelte 5?

**Comment by bluwy** [comment]
Thanks for the explanation @j3rem1e. Looks like there's a missing piece in the tooling today to make it work nicely. I don't think there's much that can be done from `vite-plugin-svelte`'s `vitePreprocess`. I don't mind changing the recommendation to `svelte-preprocess` if it helps (but still with caveats?),  and follow #24137 for further improvements.

**Comment by dominikg** [comment]
> Thanks for the explanation @j3rem1e. Looks like there's a missing piece in the tooling today to make it work nicely. I don't think there's much that can be done from `vite-plugin-svelte`'s `vitePreprocess`. I don't mind changing the recommendation to `svelte-preprocess` if it helps (but still with caveats?), and follow #24137 for further improvements.

If i understood correctly we don't have to change the recommendation, storybooks internal plugin just has to switch to svelte-preprocess (only using typescript script preprocessor)  instead of reusing the users preprocess config.
Although that could also break if users have markup preprocessors or other preprocessors that change the scripts (eg mdsvex or something that adds imports)

Completely agree that this should be solved with first party tooling in the long run.

**Comment by dummdidumm** [comment]
> @dummdidumm do you have any tips on using svelte2tsx? Should we ask the authors of sveld and sveltedoc-parser to switch to it? Is this something we might be able to improve as part of Svelte 5?

These tools serve different purposes. One is for extracting certain docs in a certain format, the other is for transforming Svelte code into something TypeScript understands. I'm very hesitant to add the burden of a specific document format to svelte2tsx.

**Comment by dominikg** [comment]
> > Although that could also break if users have markup preprocessors or other preprocessors that change the scripts (eg mdsvex or something that adds imports)
> 
> Yeah, that seems pretty error prone, which is why I thought it was better for users to just use `svelte-preprocess`, which should work totally fine

no it won't, at least not in every case. eg alias resolve in css urls or if there is custom config in vite.config.js that influences the output. 
Not to mention very different performance in large projects. 
Storybook using it internally only would ensure that rendered components are built to match prod without compromising it.

**Review by JReinhold — CHANGES_REQUESTED** [review]
Thank you all for chipping in here.

I also don't think we should advice users to use another preprocessing toolchain for Storybook. Based on experience we always recommend users to use the same setup for their application and Storybook, to ensure they output the same, or as close to the same as possible.

From what I can understand from these changes, we're processing with `svelte-preprocess` when extracting docs, but we maintain `vitePreprocess` for rendering the stories, is that correct @j3rem1e?

If so, why is it that this doesn't currently work for TS? Is it because JSDocs have already been extracted before it reaches our plugin? Could we force the order of the processing steps, to put docs extraction first?

**Comment by j3rem1e** [comment]
> I also don't think we should advice users to use another preprocessing toolchain for Storybook. Based on experience we always recommend users to use the same setup for their application and Storybook, to ensure they output the same, or as close to the same as possible.

I agree

> From what I can understand from these changes, we're processing with `svelte-preprocess` when extracting docs, but we maintain `vitePreprocess` for rendering the stories, is that correct @j3rem1e?
> 

Yes, the preprocessor is only used to send a component to sveltedoc-parser. 

> If so, why is it that this doesn't currently work for TS? Is it because JSDocs have already been extracted before it reaches our plugin? Could we force the order of the processing steps, to put docs extraction first?

Storybook registers a plugin to postprocess the compiled component. It's only a postprocessor. The workflow is the following:

* The component is compiled by Svelte normally. It uses the preprocessor configured in `svelte.config.js`. Storybook does nothing at this step, it's the default build process
* The postprocessor then build the documentation for the component, and injects it as a static property on the class (ie `MyComponent.__docgen`)

However, to generate the documentation, we need to have a svelte component, not the compiled javascript. So the postprocessor read the original `.svelte` file, read it, and gives it to sveltedoc-parser

If the component is written in TypeScript, it has to be preprocessed again. Before this PR, it was preprocess with esbuild which removes jsdoc. After this PR, it's preprocessed with svelte-preprocess. It impacts only the documentation.

**Comment by JReinhold** [comment]
> If the component is written in TypeScript, it has to be preprocessed again. Before this PR, it was preprocess with esbuild which removes jsdoc. After this PR, it's preprocessed with svelte-preprocess. It impacts only the documentation.

Right, that sounds great! TS users would still need to add JSDocs because we can't extract TS types, but now at least we extract JSDocs from TS which we didn't do before.

**Comment by benmccann** [comment]
> read the original .svelte file, read it, and gives it to sveltedoc-parser
If the component is written in TypeScript, it has to be preprocessed again. Before this PR, it was preprocess with esbuild which removes jsdoc. After this PR, it's preprocessed with svelte-preprocess. It impacts only the documentation.

This sounds like a reasonable approach to me. I somewhat wonder if we could grab the preprocessors from `svelte.config.js` and use them, but just swap `vitePreprocess` for `svelte-preprocess` if it's found. That way if the user has other preprocessors setup like mdxvex they should hopefully still be included and work

> A second step is maybe to reuse sveld instead of sveltedoc-parser but today some features are missing, like extracting jsoc keywords and slots documentation by parsing the hml template.

sveld looks pretty well maintained. It's possible that @theetrain may be able to help coordinate if you have any trouble getting a review on any PRs to that library because he's a Svelte ambassador working on `carbon-components-svelte` which is in the same GitHub org as sveld

**Comment by j3rem1e** [comment]
> This sounds like a reasonable approach to me. I somewhat wonder if we could grab the preprocessors from `svelte.config.js` and use them, but just swap `vitePreprocess` for `svelte-preprocess` if it's found. That way if the user has other preprocessors setup like mdxvex they should hopefully still be included and work
> 

I don't know if it's easy to autodetect/autoconfigure the preprocessors.. However I have added in the PR a `docPreprocess` options in `svelte.config.js` to configure it.

If a preprocessor is used and `docPreprocess` is not configured, then I use a default configuration.

**Comment by dominikg** [comment]
> I don't know if it's easy to autodetect/autoconfigure the preprocessors.. However I have added in the PR a `docPreprocess` options in `svelte.config.js` to configure it.


is this a typo or are you expanding svelte.config.js with your own keys?

**Comment by j3rem1e** [comment]
> > I don't know if it's easy to autodetect/autoconfigure the preprocessors.. However I have added in the PR a `docPreprocess` options in `svelte.config.js` to configure it.
> 
> is this a typo or are you expanding svelte.config.js with your own keys?

I suppose you ask because I shouldn`t do that ? What the best way to configure this preprocessor ?
Before, the configuration was in storybook/main.js but it has be moved into svelte.config.js

File: code/frameworks/svelte-vite/src/plugins/svelte-docgen.ts [hunk 1]
```diff
@@ -44,10 +61,26 @@ function getNameFromFilename(filename: string) {
...
-  const { preprocess: preprocessOptions, logDocgen = false } = svelteOptions;
+  const { preprocess: preprocessOptions, docPreprocess, logDocgen = false } = svelteOptions;
   const include = /\.(svelte)$/;
   const filter = createFilter(include);
 
+  let docPreprocessOptions = docPreprocess;
+  if (!docPreprocessOptions && preprocessOptions) {
+    /*
+     * We can't use vitePreprocess() for the documentation.
+     * This preprocessor uses esbuild which removes jsdoc.
```
Comment (benmccann) [inline code/frameworks/svelte-vite/src/plugins/svelte-docgen.ts:72]: clarify which one "this preprocessor" refers to
```suggestion
     * We can't use vitePreprocess() for the documentation
     * because it uses esbuild which removes jsdoc.
```

File: code/frameworks/svelte-vite/src/plugins/svelte-docgen.ts [hunk 2]
```diff
@@ -44,10 +61,26 @@ function getNameFromFilename(filename: string) {
...
+     *
+     * By default, only typescript is transpiled, and style tags are removed.
+     * This can be configured with the `docPreprocess` options.
+     *
+     * Note: theses preprocessors are only used to make the component
```
Comment (benmccann) [inline code/frameworks/svelte-vite/src/plugins/svelte-docgen.ts:77]:
```suggestion
     * Note: these preprocessors are only used to make the component
```

**Comment by benmccann** [comment]
Why does the preprocessor even need to be configured? I'd remove the options altogether. `vitePreprocess` really only has options for on or off: https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/preprocess.md#vitepreprocess

**Comment by j3rem1e** [comment]
> Why does the preprocessor even need to be configured? I'd remove the options altogether. `vitePreprocess` really only has options for on or off: https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/preprocess.md#vitepreprocess

I have added a possibility to configure it to handle edge-cases discuted here, like "what if the component is written with mdsvex", but I can remove it.

**Review by JReinhold — APPROVED** [review]
This is great! Thanks for the hard work and the patience! ❤️

(just waiting for the CI to finish)

**Comment by JReinhold** [comment]
@j3rem1e CI shows that this breaks for non-TS projects, because the preprocessor will try to import `typescript` and fail. I did a lot of investigation and solved it in this commit: https://github.com/storybookjs/storybook/commit/270c94da50270ca120fedee3ca207ba685a09c23
could you cherry pick it onto this branch, and see if you're okay with it? `git cherry-pick 270c94da50270ca120fedee3ca207ba685a09c23`

To summarize my findings:

1. Vite failed when trying to run the docgen plugin, with `typescript` missing module.
2. The creation of the plugin didn't fail in our sandboxes, because the dependencies are linked and because `svelte-vite` has a `devDependency` on `typescript`, it would actually be present, but it wouldn't be present to Vite during _transformation_. Therefore I moved the logic down _into_ the plugin, instead of before it (ensuring that it still only runs once)
3. We can use `require.resolve('typescript')`, to check if typescript is present - @benmccann will this be an issue in Vite 5? should it be `import.meta.resolve` instead?
4. The JS sandboxes couldn't render the TypeScript button at all, which makes sense. So instead I reverted the button to be JavaScript, and then added a separate TypeScript button that is only added to the TS sandboxes (`svelte-vite/default-ts` and `svelte-kit/skeleton-ts`) - and updated the E2E tests accordingly.

**Comment by j3rem1e** [comment]
It's look ok to me.

Sorry for that, I though that typescript was a required dependency with storybook, I didn't check more.

**Comment by benmccann** [comment]
> We can use require.resolve('typescript'), to check if typescript is present - @benmccann will this be an issue in Vite 5? should it be import.meta.resolve instead?

probably

**Comment by JReinhold** [comment]
I took a stab at `import.meta.resolve`, but `import.meta` is `undefined`. Maybe this will be fixed in #24395, either way I think `require.resolve` is fine for now.
