### PR TITLE
Addon Vitest: Fix watch mode for new files

### LINKED ISSUE #31100: [Bug]: Storybook 9 - Storybook test does not detect newly added story file
### Describe the bug

**Repo:** [MealDrop](https://github.com/yannbf/mealdrop)
**Branch:** `sb-test-demo`

**Steps:**
- Run Storybook
- Run all tests with code coverage enabled through Storybook's UI
- Notice 95% coverage, check the coverage for the Badge.tsx file
- Click on "create story from component", for the Badge.tsx file
- In the controls panel, toggle "uppercase" and save the controls
- Rerun tests with coverage
- Notice that the Badge test was not run, therefore the coverage was not recalculated

### Reproduction link

-

### Reproduction steps

_No response_

### System

```bash
-
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by valentinpalkovic**
Closes https://github.com/storybookjs/storybook/issues/31100

## What I did

I have fixed watch mode for newly added story files in `@storybook/addon-vitest`

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This pull request has been released as version `0.0.0-pr-31156-sha-db97728a`. Try it out in a new sandbox by running `npx storybook@0.0.0-pr-31156-sha-db97728a sandbox` or in an existing project with `npx storybook@0.0.0-pr-31156-sha-db97728a upgrade`.
<details>
<summary>More information</summary>

| | |
| --- | --- |
| **Published version** | [`0.0.0-pr-31156-sha-db97728a`](https://npmjs.com/package/storybook/v/0.0.0-pr-31156-sha-db97728a) |
| **Triggered by** | @valentinpalkovic |
| **Repository** | [storybookjs/storybook](https://github.com/storybookjs/storybook) |
| **Branch** | [`valentin/fix-watch-mode-for-new-files`](https://github.com/storybookjs/storybook/tree/valentin/fix-watch-mode-for-new-files) |
| **Commit** | [`db97728a`](https://github.com/storybookjs/storybook/commit/db97728a32cebf048f786b0f5b4bcd176c438b34) |
| **Datetime** | Tue May 13 11:04:25 UTC 2025 (`1747134265`) |
| **Workflow run** | [14994980268](https://github.com/storybookjs/storybook/actions/runs/14994980268) |

To request a new release of this pull request, mention the `@storybookjs/core` team.

_core team members can create a new canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=31156`_
</details>

## Greptile Summary

This PR enhances the Vitest addon's file watching capabilities, particularly focusing on detecting and testing newly added story files by improving event handling and pattern matching.

- Modified `code/addons/vitest/src/node/vitest-manager.ts` to properly handle 'add' vs 'change' events for test files
- Replaced tinyglobby with micromatch in `code/addons/vitest/src/vitest-plugin/index.ts` for more reliable file pattern matching
- Added `includeStories` to InternalOptions in `code/addons/vitest/src/vitest-plugin/types.ts` for better story inclusion control
- Exported `DEFAULT_FILES_PATTERN` from `code/core/src/common/utils/normalize-stories.ts` for consistent file matching
- Added environment variable support in `scripts/utils/cli-step.ts` for improved CLI configuration

### CODE REVIEW

File: code/addons/vitest/src/node/vitest-manager.ts [hunk 1]
```diff
@@ -370,8 +368,16 @@ export class VitestManager {
     });
   }
 
-  async runAffectedTestsAfterChange(file: string) {
+  async runAffectedTestsAfterChange(file: string, event: 'add' | 'change') {
     const id = slash(file);
+
+    if (event === 'add') {
+      const project = this.vitest?.projects.find(this.isStorybookProject.bind(this));
+      // This function not onlye test a file matches the test globs, but it also
```
Comment (valentinpalkovic) [inline code/addons/vitest/src/node/vitest-manager.ts:376]:
```suggestion
      // This function not only tests whether a file matches the test globs, but it also
```

**Review by yannbf — APPROVED** [review]

File: code/core/src/common/utils/normalize-stories.ts [hunk 2]
```diff
@@ -11,7 +11,7 @@ import { globToRegexp } from './glob-to-regexp';
 import { normalizeStoryPath } from './paths';
 
 const DEFAULT_TITLE_PREFIX = '';
-const DEFAULT_FILES_PATTERN = '**/*.@(mdx|stories.@(js|jsx|mjs|ts|tsx))';
+export const DEFAULT_FILES_PATTERN = '**/*.@(mdx|stories.@(js|jsx|mjs|ts|tsx))';
```
Comment (yannbf) [inline code/core/src/common/utils/normalize-stories.ts:14]:
```suggestion
export const DEFAULT_FILES_PATTERN = '**/*.@(mdx|stories|story.@(js|jsx|mjs|ts|tsx))';
```

**Review by yannbf — APPROVED** [review]
