### PR TITLE
fix #2384: support string-only component for vue

### LINKED ISSUE #2384: vue storybook install fails
The example yields
```
Failed to execute 'createElement' on 'Document': The tag name provided ('<my-button :rounded="true">story as a function template</my-button>') is not a valid name.
    
      Error: Failed to execute 'createElement' on 'Document': The tag name provided ('<my-button :rounded="true">story as a function template</my-button>') is not a valid name.
```

### PR DESCRIPTION
**Pull request by yaodingyd**
Issue: #2384

## What I did

Add support for string only component

### CODE REVIEW

File: app/vue/src/client/preview/render.js [hunk 1]
```diff
@@ -20,6 +20,10 @@ export default function render({
   Vue.config.errorHandler = showException;
 
   const component = story();
+  
+  if (typeof component === 'string') {
+    component = { template: component };
```
Comment (igor-dv) [inline app/vue/src/client/preview/render.js]: component is a `const`, you can't reassign it, can you please fix it ? 
I think we need an example story as well.

**Review by igor-dv — CHANGES_REQUESTED** [review]

File: app/vue/src/client/preview/render.js (hunk 1 above)
Comment (yaodingyd) [reply app/vue/src/client/preview/render.js]: updated

**Review by igor-dv — APPROVED** [review]
Thanks
