### PR TITLE
Maintenance: Fix `@ts-expect-error` strict types

### LINKED ISSUE #20877: [Bug]: [v7.0.0-beta.38/39] inexplicable error in `csf-tools` with `angular` sandbox
### Describe the bug

Getting inexplicable error in `csf-tools`

### To Reproduce

- clone a clean repo from the next branch
- execute 
```shell
yarn task --task dev --template angular-cli/default-ts --start-from=install
```
- wait for the install > compile > sandbox > dev to finish with error

### System

```shell
Environment Info:

  System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
  Binaries:
    Node: 18.13.0 - /usr/local/bin/node
    Yarn: 3.3.0 - /usr/local/bin/yarn
    npm: 9.3.1 - /usr/local/bin/npm
```

### Additional context

```
Error: ../../code/lib/csf-tools/src/ConfigFile.ts:26:40 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(predicate: (this: void, value: ObjectMethod | ObjectProperty | SpreadElement, index: number, obj: (ObjectMethod | ObjectProperty | SpreadElement)[]) => value is ObjectMethod | ... 1 more ... | SpreadElement, thisArg?: any): ObjectMethod | ... 2 more ... | undefined', gave the following error.
    Argument of type '(p: t.ObjectProperty) => boolean' is not assignable to parameter of type '(this: void, value: ObjectMethod | ObjectProperty | SpreadElement, index: number, obj: (ObjectMethod | ObjectProperty | SpreadElement)[]) => value is ObjectMethod | ... 1 more ... | SpreadElement'.
      Types of parameters 'p' and 'value' are incompatible.
        Type 'ObjectMethod | ObjectProperty | SpreadElement' is not assignable to type 'ObjectProperty'.
          Type 'ObjectMethod' is not assignable to type 'ObjectProperty'.
  Overload 2 of 2, '(predicate: (value: ObjectMethod | ObjectProperty | SpreadElement, index: number, obj: (ObjectMethod | ObjectProperty | SpreadElement)[]) => unknown, thisArg?: any): ObjectMethod | ... 2 more ... | undefined', gave the following error.
    Argument of type '(p: t.ObjectProperty) => boolean' is not assignable to parameter of type '(value: ObjectMethod | ObjectProperty | SpreadElement, index: number, obj: (ObjectMethod | ObjectProperty | SpreadElement)[]) => unknown'.
      Types of parameters 'p' and 'value' are incompatible.
        Type 'ObjectMethod | ObjectProperty | SpreadElement' is not assignable to type 'ObjectProperty'.
          Type 'ObjectMethod' is not assignable to type 'ObjectProperty'.

26     const field = node.properties.find((p: t.ObjectProperty) => propKey(p) === first);
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


    at addError (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:31:27)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:18:9
    at AngularWebpackPlugin.updateJitProgram (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:401:5)
    at AngularWebpackPlugin.setupCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:180:87)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:120:14
    at Hook.eval [as call] (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:14:14), <anonymous>:24:1)
    at Hook.CALL_DELEGATE [as _call] (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/Hook.js:11:15)
    at Compiler.newCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:881:32)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:921:32
    at _next0 (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:41:1)
Error: ../../code/lib/csf-tools/src/ConfigFile.ts:44:40 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(predicate: (this: void, value: ObjectMethod | ObjectProperty | SpreadElement, index: number, obj: (ObjectMethod | ObjectProperty | SpreadElement)[]) => value is ObjectMethod | ... 1 more ... | SpreadElement, thisArg?: any): ObjectMethod | ... 2 more ... | undefined', gave the following error.
    Argument of type '(p: t.ObjectProperty) => boolean' is not assignable to parameter of type '(this: void, value: ObjectMethod | ObjectProperty | SpreadElement, index: number, obj: (ObjectMethod | ObjectProperty | SpreadElement)[]) => value is ObjectMethod | ... 1 more ... | SpreadElement'.
      Types of parameters 'p' and 'value' are incompatible.
        Type 'ObjectMethod | ObjectProperty | SpreadElement' is not assignable to type 'ObjectProperty'.
          Type 'ObjectMethod' is not assignable to type 'ObjectProperty'.
  Overload 2 of 2, '(predicate: (value: ObjectMethod | ObjectProperty | SpreadElement, index: number, obj: (ObjectMethod | ObjectProperty | SpreadElement)[]) => unknown, thisArg?: any): ObjectMethod | ... 2 more ... | undefined', gave the following error.
    Argument of type '(p: t.ObjectProperty) => boolean' is not assignable to parameter of type '(value: ObjectMethod | ObjectProperty | SpreadElement, index: number, obj: (ObjectMethod | ObjectProperty | SpreadElement)[]) => unknown'.
      Types of parameters 'p' and 'value' are incompatible.
        Type 'ObjectMethod | ObjectProperty | SpreadElement' is not assignable to type 'ObjectProperty'.
          Type 'ObjectMethod' is not assignable to type 'ObjectProperty'.

44     const field = node.properties.find((p: t.ObjectProperty) => propKey(p) === first);
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


    at addError (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:31:27)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:18:9
    at AngularWebpackPlugin.updateJitProgram (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:401:5)
    at AngularWebpackPlugin.setupCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:180:87)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:120:14
    at Hook.eval [as call] (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:14:14), <anonymous>:24:1)
    at Hook.CALL_DELEGATE [as _call] (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/Hook.js:11:15)
    at Compiler.newCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:881:32)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:921:32
    at _next0 (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:41:1)
Error: ../../code/lib/csf-tools/src/ConfigFile.ts:96:5 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(predicate: (this: void, value: ObjectMethod | ObjectProperty | SpreadElement, index: number, obj: (ObjectMethod | ObjectProperty | SpreadElement)[]) => value is ObjectProperty, thisArg?: any): ObjectProperty | undefined', gave the following error.
    Argument of type '(p: t.ObjectProperty) => boolean' is not assignable to parameter of type '(this: void, value: ObjectMethod | ObjectProperty | SpreadElement, index: number, obj: (ObjectMethod | ObjectProperty | SpreadElement)[]) => value is ObjectProperty'.
      Types of parameters 'p' and 'value' are incompatible.
        Type 'ObjectMethod | ObjectProperty | SpreadElement' is not assignable to type 'ObjectProperty'.
          Type 'ObjectMethod' is not assignable to type 'ObjectProperty'.
  Overload 2 of 2, '(predicate: (value: ObjectMethod | ObjectProperty | SpreadElement, index: number, obj: (ObjectMethod | ObjectProperty | SpreadElement)[]) => unknown, thisArg?: any): ObjectMethod | ... 2 more ... | undefined', gave the following error.
    Argument of type '(p: t.ObjectProperty) => boolean' is not assignable to parameter of type '(value: ObjectMethod | ObjectProperty | SpreadElement, index: number, obj: (ObjectMethod | ObjectProperty | SpreadElement)[]) => unknown'.
      Types of parameters 'p' and 'value' are incompatible.
        Type 'ObjectMethod | ObjectProperty | SpreadElement' is not assignable to type 'ObjectProperty'.
          Type 'ObjectMethod' is not assignable to type 'ObjectProperty'.

96     (p: t.ObjectProperty) => propKey(p) === first
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


    at addError (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:31:27)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:18:9
    at AngularWebpackPlugin.updateJitProgram (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:401:5)
    at AngularWebpackPlugin.setupCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:180:87)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:120:14
    at Hook.eval [as call] (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:14:14), <anonymous>:24:1)
    at Hook.CALL_DELEGATE [as _call] (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/Hook.js:11:15)
    at Compiler.newCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:881:32)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:921:32
    at _next0 (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:41:1)
Error: ../../code/lib/csf-tools/src/ConfigFile.ts:116:3 - error TS2564: Property '_exportsObject' has no initializer and is not definitely assigned in the constructor.

116   _exportsObject: t.ObjectExpression;
      ~~~~~~~~~~~~~~

    at addError (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:31:27)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:18:9
    at AngularWebpackPlugin.updateJitProgram (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:401:5)
    at AngularWebpackPlugin.setupCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:180:87)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:120:14
    at Hook.eval [as call] (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:14:14), <anonymous>:24:1)
    at Hook.CALL_DELEGATE [as _call] (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/Hook.js:11:15)
    at Compiler.newCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:881:32)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:921:32
    at _next0 (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:41:1)
Error: ../../code/lib/csf-tools/src/ConfigFile.ts:144:37 - error TS2345: Argument of type '(p: t.ObjectProperty) => void' is not assignable to parameter of type '(value: ObjectMethod | ObjectProperty | SpreadElement, index: number, array: (ObjectMethod | ObjectProperty | SpreadElement)[]) => void'.
  Types of parameters 'p' and 'value' are incompatible.
    Type 'ObjectMethod | ObjectProperty | SpreadElement' is not assignable to type 'ObjectProperty'.
      Type 'ObjectMethod' is not assignable to type 'ObjectProperty'.

144             decl.properties.forEach((p: t.ObjectProperty) => {
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~

    at addError (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:31:27)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:18:9
    at AngularWebpackPlugin.updateJitProgram (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:401:5)
    at AngularWebpackPlugin.setupCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:180:87)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:120:14
    at Hook.eval [as call] (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:14:14), <anonymous>:24:1)
    at Hook.CALL_DELEGATE [as _call] (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/Hook.js:11:15)
    at Compiler.newCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:881:32)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:921:32
    at _next0 (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:41:1)
Error: ../../code/lib/csf-tools/src/ConfigFile.ts:149:19 - error TS2322: Type 'null' is not assignable to type 'ArrayExpression | ArrayPattern | ArrowFunctionExpression | AssignmentExpression | AssignmentPattern | ... 49 more ... | YieldExpression'.

149                   exportVal = _findVarInitialization(exportVal.name, parent as t.Program);
                      ~~~~~~~~~

    at addError (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:31:27)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:18:9
    at AngularWebpackPlugin.updateJitProgram (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:401:5)
    at AngularWebpackPlugin.setupCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:180:87)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:120:14
    at Hook.eval [as call] (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:14:14), <anonymous>:24:1)
    at Hook.CALL_DELEGATE [as _call] (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/Hook.js:11:15)
    at Compiler.newCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:881:32)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:921:32
    at _next0 (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:41:1)
Error: ../../code/lib/csf-tools/src/ConfigFile.ts:170:17 - error TS2322: Type 'ArrayExpression | ArrowFunctionExpression | AssignmentExpression | AwaitExpression | ... 47 more ... | undefined' is not assignable to type 'Expression'.
  Type 'undefined' is not assignable to type 'Expression'.

170                 self._exports[exportName] = exportVal;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~

    at addError (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:31:27)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:18:9
    at AngularWebpackPlugin.updateJitProgram (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:401:5)
    at AngularWebpackPlugin.setupCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:180:87)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:120:14
    at Hook.eval [as call] (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:14:14), <anonymous>:24:1)
    at Hook.CALL_DELEGATE [as _call] (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/Hook.js:11:15)
    at Compiler.newCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:881:32)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:921:32
    at _next0 (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:41:1)
Error: ../../code/lib/csf-tools/src/ConfigFile.ts:191:17 - error TS2322: Type 'null' is not assignable to type 'Expression'.

191                 exportObject = _findVarInitialization(right.name, parent as t.Program);
                    ~~~~~~~~~~~~

    at addError (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:31:27)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:18:9
    at AngularWebpackPlugin.updateJitProgram (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:401:5)
    at AngularWebpackPlugin.setupCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:180:87)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:120:14
    at Hook.eval [as call] (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:14:14), <anonymous>:24:1)
    at Hook.CALL_DELEGATE [as _call] (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/Hook.js:11:15)
    at Compiler.newCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:881:32)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:921:32
    at _next0 (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:41:1)
Error: ../../code/lib/csf-tools/src/ConfigFile.ts:195:49 - error TS2345: Argument of type '(p: t.ObjectProperty) => void' is not assignable to parameter of type '(value: ObjectMethod | ObjectProperty | SpreadElement, index: number, array: (ObjectMethod | ObjectProperty | SpreadElement)[]) => void'.
  Types of parameters 'p' and 'value' are incompatible.
    Type 'ObjectMethod | ObjectProperty | SpreadElement' is not assignable to type 'ObjectProperty'.
      Type 'ObjectMethod' is not assignable to type 'ObjectProperty'.

195                 exportObject.properties.forEach((p: t.ObjectProperty) => {
                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~

    at addError (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:31:27)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:18:9
    at AngularWebpackPlugin.updateJitProgram (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:401:5)
    at AngularWebpackPlugin.setupCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:180:87)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:120:14
    at Hook.eval [as call] (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:14:14), <anonymous>:24:1)
    at Hook.CALL_DELEGATE [as _call] (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/Hook.js:11:15)
    at Compiler.newCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:881:32)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:921:32
    at _next0 (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:41:1)
Error: ../../code/lib/csf-tools/src/ConfigFile.ts:200:23 - error TS2322: Type 'null' is not assignable to type 'ArrayExpression | ArrayPattern | ArrowFunctionExpression | AssignmentExpression | AssignmentPattern | ... 49 more ... | YieldExpression'.

200                       exportVal = _findVarInitialization(exportVal.name, parent as t.Program);
                          ~~~~~~~~~

    at addError (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:31:27)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:18:9
    at AngularWebpackPlugin.updateJitProgram (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:401:5)
    at AngularWebpackPlugin.setupCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:180:87)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:120:14
    at Hook.eval [as call] (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:14:14), <anonymous>:24:1)
    at Hook.CALL_DELEGATE [as _call] (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/Hook.js:11:15)
    at Compiler.newCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:881:32)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:921:32
    at _next0 (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:41:1)
Error: ../../code/lib/csf-tools/src/ConfigFile.ts:303:45 - error TS2345: Argument of type 'SpreadElement | Expression | null' is not assignable to parameter of type 'Node'.
  Type 'null' is not assignable to type 'Node'.

303         pathNames.push(this._getPresetValue(element, 'name'));
                                                ~~~~~~~

    at addError (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:31:27)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:18:9
    at AngularWebpackPlugin.updateJitProgram (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:401:5)
    at AngularWebpackPlugin.setupCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:180:87)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:120:14
    at Hook.eval [as call] (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:14:14), <anonymous>:24:1)
    at Hook.CALL_DELEGATE [as _call] (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/Hook.js:11:15)
    at Compiler.newCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:881:32)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:921:32
    at _next0 (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:41:1)
Error: ../../code/lib/csf-tools/src/ConfigFile.ts:406:34 - error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.

406       removeProperty(properties, lastPath);
                                     ~~~~~~~~

    at addError (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:31:27)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:18:9
    at AngularWebpackPlugin.updateJitProgram (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:401:5)
    at AngularWebpackPlugin.setupCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:180:87)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:120:14
    at Hook.eval [as call] (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:14:14), <anonymous>:24:1)
    at Hook.CALL_DELEGATE [as _call] (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/Hook.js:11:15)
    at Compiler.newCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:881:32)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:921:32
    at _next0 (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:41:1)
Error: ../../code/lib/csf-tools/src/CsfFile.ts:43:7 - error TS2322: Type 'null' is not assignable to type 'Expression'.

43   let init: t.Expression = null;
         ~~~~

    at addError (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:31:27)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:18:9
    at AngularWebpackPlugin.updateJitProgram (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:401:5)
    at AngularWebpackPlugin.setupCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:180:87)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:120:14
    at Hook.eval [as call] (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:14:14), <anonymous>:24:1)
    at Hook.CALL_DELEGATE [as _call] (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/Hook.js:11:15)
    at Compiler.newCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:881:32)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:921:32
    at _next0 (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:41:1)
Error: ../../code/lib/csf-tools/src/CsfFile.ts:44:7 - error TS2322: Type 'null' is not assignable to type 'VariableDeclarator[]'.

44   let declarations: t.VariableDeclarator[] = null;
         ~~~~~~~~~~~~

    at addError (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:31:27)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:18:9
    at AngularWebpackPlugin.updateJitProgram (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:401:5)
    at AngularWebpackPlugin.setupCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:180:87)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:120:14
    at Hook.eval [as call] (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:14:14), <anonymous>:24:1)
    at Hook.CALL_DELEGATE [as _call] (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/Hook.js:11:15)
    at Compiler.newCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:881:32)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:921:32
    at _next0 (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:41:1)
Error: ../../code/lib/csf-tools/src/CsfFile.ts:60:11 - error TS2322: Type 'Expression | null | undefined' is not assignable to type 'Expression'.
  Type 'undefined' is not assignable to type 'Expression'.

60           init = decl.init;
             ~~~~

    at addError (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:31:27)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:18:9
    at AngularWebpackPlugin.updateJitProgram (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:401:5)
    at AngularWebpackPlugin.setupCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:180:87)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:120:14
    at Hook.eval [as call] (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:14:14), <anonymous>:24:1)
    at Hook.CALL_DELEGATE [as _call] (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/Hook.js:11:15)
    at Compiler.newCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:881:32)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:921:32
    at _next0 (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:41:1)
Error: ../../code/lib/csf-tools/src/CsfFile.ts:71:28 - error TS18049: 'node.loc' is possibly 'null' or 'undefined'.

71   const { line, column } = node.loc.start;
                              ~~~~~~~~

    at addError (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:31:27)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:18:9
    at AngularWebpackPlugin.updateJitProgram (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:401:5)
    at AngularWebpackPlugin.setupCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:180:87)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:120:14
    at Hook.eval [as call] (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:14:14), <anonymous>:24:1)
    at Hook.CALL_DELEGATE [as _call] (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/Hook.js:11:15)
    at Compiler.newCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:881:32)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:921:32
    at _next0 (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:41:1)
Error: ../../code/lib/csf-tools/src/CsfFile.ts:111:30 - error TS2345: Argument of type '(item: t.Expression) => string' is not assignable to parameter of type '(value: SpreadElement | Expression | null, index: number, array: (SpreadElement | Expression | null)[]) => string'.
  Types of parameters 'item' and 'value' are incompatible.
    Type 'SpreadElement | Expression | null' is not assignable to type 'Expression'.
      Type 'null' is not assignable to type 'Expression'.

111     return init.elements.map((item: t.Expression) => {
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~

    at addError (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:31:27)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:18:9
    at AngularWebpackPlugin.updateJitProgram (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:401:5)
    at AngularWebpackPlugin.setupCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:180:87)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:120:14
    at Hook.eval [as call] (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:14:14), <anonymous>:24:1)
    at Hook.CALL_DELEGATE [as _call] (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/Hook.js:11:15)
    at Compiler.newCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:881:32)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:921:32
    at _next0 (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:41:1)
Error: ../../code/lib/csf-tools/src/CsfFile.ts:188:5 - error TS2322: Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.

188     this._fileName = fileName;
        ~~~~~~~~~~~~~~

    at addError (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:31:27)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:18:9
    at AngularWebpackPlugin.updateJitProgram (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:401:5)
    at AngularWebpackPlugin.setupCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:180:87)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:120:14
    at Hook.eval [as call] (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:14:14), <anonymous>:24:1)
    at Hook.CALL_DELEGATE [as _call] (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/Hook.js:11:15)
    at Compiler.newCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:881:32)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:921:32
    at _next0 (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:41:1)
Error: ../../code/lib/csf-tools/src/CsfFile.ts:207:36 - error TS2345: Argument of type '(p: t.ObjectProperty) => void' is not assignable to parameter of type '(value: ObjectMethod | ObjectProperty | SpreadElement, index: number, array: (ObjectMethod | ObjectProperty | SpreadElement)[]) => void'.
  Types of parameters 'p' and 'value' are incompatible.
    Type 'ObjectMethod | ObjectProperty | SpreadElement' is not assignable to type 'ObjectProperty'.
      Type 'ObjectMethod' is missing the following properties from type 'ObjectProperty': value, shorthand

207     declaration.properties.forEach((p: t.ObjectProperty) => {
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~

    at addError (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:31:27)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:18:9
    at AngularWebpackPlugin.updateJitProgram (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:401:5)
    at AngularWebpackPlugin.setupCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:180:87)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:120:14
    at Hook.eval [as call] (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:14:14), <anonymous>:24:1)
    at Hook.CALL_DELEGATE [as _call] (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/Hook.js:11:15)
    at Compiler.newCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:881:32)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:921:32
    at _next0 (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:41:1)
Error: ../../code/lib/csf-tools/src/CsfFile.ts:239:5 - error TS2322: Type 'AnyTypeAnnotation | ArgumentPlaceholder | ArrayPattern | ArrayTypeAnnotation | AssignmentPattern | ... 198 more ... | undefined' is not assignable to type 'Node'.
  Type 'undefined' is not assignable to type 'Node'.

239     node = t.isVariableDeclarator(node) ? node.init : node;
        ~~~~

    at addError (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:31:27)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:18:9
    at AngularWebpackPlugin.updateJitProgram (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:401:5)
    at AngularWebpackPlugin.setupCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:180:87)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:120:14
    at Hook.eval [as call] (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:14:14), <anonymous>:24:1)
    at Hook.CALL_DELEGATE [as _call] (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/Hook.js:11:15)
    at Compiler.newCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:881:32)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:921:32
    at _next0 (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:41:1)
Error: ../../code/lib/csf-tools/src/CsfFile.ts:280:20 - error TS2532: Object is possibly 'undefined'.

280             decl = (self._metaStatement as t.VariableDeclaration).declarations.find(
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
281               isVariableDeclarator
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
282             ).init;
    ~~~~~~~~~~~~~

    at addError (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:31:27)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:18:9
    at AngularWebpackPlugin.updateJitProgram (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:401:5)
    at AngularWebpackPlugin.setupCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:180:87)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:120:14
    at Hook.eval [as call] (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:14:14), <anonymous>:24:1)
    at Hook.CALL_DELEGATE [as _call] (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/Hook.js:11:15)
    at Compiler.newCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:881:32)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:921:32
    at _next0 (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:41:1)
Error: ../../code/lib/csf-tools/src/CsfFile.ts:299:30 - error TS2454: Variable 'metaNode' is used before being assigned.

299           if (!self._meta && metaNode && t.isProgram(parent)) {
                                 ~~~~~~~~

    at addError (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:31:27)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:18:9
    at AngularWebpackPlugin.updateJitProgram (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:401:5)
    at AngularWebpackPlugin.setupCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:180:87)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:120:14
    at Hook.eval [as call] (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:14:14), <anonymous>:24:1)
    at Hook.CALL_DELEGATE [as _call] (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/Hook.js:11:15)
    at Compiler.newCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:881:32)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:921:32
    at _next0 (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:41:1)
Error: ../../code/lib/csf-tools/src/CsfFile.ts:319:63 - error TS2345: Argument of type 'Expression | null | undefined' is not assignable to parameter of type 'Expression'.

319                   self._namedExportsOrder = parseExportsOrder(decl.init);
                                                                  ~~~~~~~~~

    at addError (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:31:27)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:18:9
    at AngularWebpackPlugin.updateJitProgram (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:401:5)
    at AngularWebpackPlugin.setupCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:180:87)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:120:14
    at Hook.eval [as call] (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:14:14), <anonymous>:24:1)
    at Hook.CALL_DELEGATE [as _call] (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/Hook.js:11:15)
    at Compiler.newCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:881:32)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:921:32
    at _next0 (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:41:1)
Error: ../../code/lib/csf-tools/src/CsfFile.ts:337:48 - error TS2345: Argument of type '(p: t.ObjectProperty) => void' is not assignable to parameter of type '(value: ObjectMethod | ObjectProperty | SpreadElement, index: number, array: (ObjectMethod | ObjectProperty | SpreadElement)[]) => void'.
  Types of parameters 'p' and 'value' are incompatible.
    Type 'ObjectMethod | ObjectProperty | SpreadElement' is not assignable to type 'ObjectProperty'.
      Type 'ObjectMethod' is not assignable to type 'ObjectProperty'.

337                   decl.init.properties.forEach((p: t.ObjectProperty) => {
                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~

    at addError (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:31:27)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:18:9
    at AngularWebpackPlugin.updateJitProgram (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:401:5)
    at AngularWebpackPlugin.setupCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:180:87)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:120:14
    at Hook.eval [as call] (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:14:14), <anonymous>:24:1)
    at Hook.CALL_DELEGATE [as _call] (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/Hook.js:11:15)
    at Compiler.newCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:881:32)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:921:32
    at _next0 (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:41:1)
Error: ../../code/lib/csf-tools/src/CsfFile.ts:357:48 - error TS2345: Argument of type 'FunctionDeclaration | Expression | null | undefined' is not assignable to parameter of type 'Node'.
  Type 'undefined' is not assignable to type 'Node'.

357                     __isArgsStory: isArgsStory(fn, parent, self),
                                                   ~~

    at addError (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:31:27)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:18:9
    at AngularWebpackPlugin.updateJitProgram (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:401:5)
    at AngularWebpackPlugin.setupCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:180:87)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:120:14
    at Hook.eval [as call] (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:14:14), <anonymous>:24:1)
    at Hook.CALL_DELEGATE [as _call] (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/Hook.js:11:15)
    at Compiler.newCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:881:32)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:921:32
    at _next0 (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:41:1)
Error: ../../code/lib/csf-tools/src/CsfFile.ts:389:38 - error TS2454: Variable 'metaNode' is used before being assigned.

389                   if (!self._meta && metaNode && t.isProgram(parent)) {
                                         ~~~~~~~~

    at addError (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:31:27)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:18:9
    at AngularWebpackPlugin.updateJitProgram (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:401:5)
    at AngularWebpackPlugin.setupCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:180:87)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:120:14
    at Hook.eval [as call] (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:14:14), <anonymous>:24:1)
    at Hook.CALL_DELEGATE [as _call] (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/Hook.js:11:15)
    at Compiler.newCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:881:32)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:921:32
    at _next0 (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:41:1)
Error: ../../code/lib/csf-tools/src/CsfFile.ts:421:52 - error TS2345: Argument of type '(prop: t.ObjectProperty) => void' is not assignable to parameter of type '(value: ObjectMethod | ObjectProperty | SpreadElement, index: number, array: (ObjectMethod | ObjectProperty | SpreadElement)[]) => void'.
  Types of parameters 'prop' and 'value' are incompatible.
    Type 'ObjectMethod | ObjectProperty | SpreadElement' is not assignable to type 'ObjectProperty'.
      Type 'ObjectMethod' is not assignable to type 'ObjectProperty'.

421                 annotationValue.properties.forEach((prop: t.ObjectProperty) => {
                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    at addError (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:31:27)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:18:9
    at AngularWebpackPlugin.updateJitProgram (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:401:5)
    at AngularWebpackPlugin.setupCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:180:87)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:120:14
    at Hook.eval [as call] (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:14:14), <anonymous>:24:1)
    at Hook.CALL_DELEGATE [as _call] (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/Hook.js:11:15)
    at Compiler.newCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:881:32)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:921:32
    at _next0 (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:41:1)
Error: ../../code/lib/csf-tools/src/CsfFile.ts:478:40 - error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.

478     self._meta.title = this._makeTitle(self._meta.title);
                                           ~~~~~~~~~~~~~~~~

    at addError (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:31:27)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:18:9
    at AngularWebpackPlugin.updateJitProgram (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:401:5)
    at AngularWebpackPlugin.setupCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:180:87)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:120:14
    at Hook.eval [as call] (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:14:14), <anonymous>:24:1)
    at Hook.CALL_DELEGATE [as _call] (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/Hook.js:11:15)
    at Compiler.newCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:881:32)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:921:32
    at _next0 (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:41:1)
Error: ../../code/lib/csf-tools/src/CsfFile.ts:479:31 - error TS4111: Property 'play' comes from an index signature, so it must be accessed with ['play'].

479     if (self._metaAnnotations.play) {
                                  ~~~~

    at addError (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:31:27)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:18:9
    at AngularWebpackPlugin.updateJitProgram (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:401:5)
    at AngularWebpackPlugin.setupCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:180:87)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:120:14
    at Hook.eval [as call] (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:14:14), <anonymous>:24:1)
    at Hook.CALL_DELEGATE [as _call] (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/Hook.js:11:15)
    at Compiler.newCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:881:32)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:921:32
    at _next0 (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:41:1)
Error: ../../code/lib/csf-tools/src/CsfFile.ts:483:30 - error TS2345: Argument of type 'StaticMeta | undefined' is not assignable to parameter of type 'IncludeExcludeOptions'.
  Type 'undefined' is not assignable to type 'IncludeExcludeOptions'.

483       if (isExportStory(key, self._meta)) {
                                 ~~~~~~~~~~

    at addError (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:31:27)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:18:9
    at AngularWebpackPlugin.updateJitProgram (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:401:5)
    at AngularWebpackPlugin.setupCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:180:87)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:120:14
    at Hook.eval [as call] (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:14:14), <anonymous>:24:1)
    at Hook.CALL_DELEGATE [as _call] (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/Hook.js:11:15)
    at Compiler.newCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:881:32)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:921:32
    at _next0 (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:41:1)
Error: ../../code/lib/csf-tools/src/CsfFile.ts:484:25 - error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.

484         const id = toId(self._meta.id || self._meta.title, storyNameFromExport(key));
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    at addError (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:31:27)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:18:9
    at AngularWebpackPlugin.updateJitProgram (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:401:5)
    at AngularWebpackPlugin.setupCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:180:87)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/@ngtools/webpack/src/ivy/plugin.js:120:14
    at Hook.eval [as call] (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:14:14), <anonymous>:24:1)
    at Hook.CALL_DELEGATE [as _call] (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/Hook.js:11:15)
    at Compiler.newCompilation (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:881:32)
    at /home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/webpack/lib/Compiler.js:921:32
    at _next0 (eval at create (/home/mosherif87/repo/storybook/sandbox/angular-cli-default-ts/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:41:1)
Error: ../../code/lib/csf-tools/src/CsfFile.ts:484:25 - error TS18048: 'self._meta' is possibly 'undefined'.
```

### PR DESCRIPTION
**Pull request by sheriffMoose**
Closes #20877

## What I did

* [x] fixed a few failing types while building sandboxes

## How to test

* [ ] CI Passes

### CODE REVIEW

**Review by valentinpalkovic — APPROVED** [review]

File: code/lib/csf-tools/src/ConfigFile.ts [hunk 1]
```diff
@@ -191,16 +191,19 @@ export class ConfigFile {
...
+                exportObject = _findVarInitialization(right.name, parent as t.Program) as any;
               }
               if (t.isObjectExpression(exportObject)) {
                 self._exportsObject = exportObject;
-                exportObject.properties.forEach((p: t.ObjectProperty) => {
+                (exportObject.properties as t.ObjectProperty[]).forEach((p) => {
                   const exportName = propKey(p);
                   if (exportName) {
-                    let exportVal = p.value;
+                    let exportVal = p.value as t.Expression;
```
Comment (shilman) [inline code/lib/csf-tools/src/ConfigFile.ts:201]: Why do we need all these extra type annotations?

Comment (sheriffMoose) [reply code/lib/csf-tools/src/ConfigFile.ts:201]: Yes, #20877

Comment (sheriffMoose) [reply code/lib/csf-tools/src/ConfigFile.ts:201]: @vatcoop & I are affected, can't do changes without disabling strict mode and do few changes

File: code/lib/csf-tools/src/getStorySortParameter.ts [hunk 2]
```diff
@@ -109,7 +109,7 @@ export const getStorySortParameter = (previewCode: string) => {
 
   if (t.isFunctionExpression(storySort)) {
     const { code: sortCode } = generate.default(storySort, {});
-    const functionName = storySort.id.name;
+    const functionName = storySort.id?.name;
```
Comment (yannbf) [inline code/lib/csf-tools/src/getStorySortParameter.ts:112]: I wonder if we should add a TODO comment here to remind to take a look at this code.
if storySort.id can be undefined, it means that the code right after will generate invalid code, e.g.:

```
return undefined(a, b)
```

**Comment by valentinpalkovic** [comment]
@sheriffMoose Can you merge the latest `next` into your branch? If the pipeline is green. Let's merge this. Please take care of Yanns small comment as well.

File: code/lib/csf-tools/src/getStorySortParameter.ts (hunk 2 above)
Comment (yannbf) [reply code/lib/csf-tools/src/getStorySortParameter.ts:112]: @sheriffMoose @ndelangen seems like this PR got merged but this was taken into account. Do you think this might bite us back if we don't at least add a TODO there?

Comment (ndelangen) [reply code/lib/csf-tools/src/getStorySortParameter.ts:112]: If you feel like there should be a comment, and you have an idea what that comment should look like, sure.
I don't have a recollection of this context anymore.

Comment (yannbf) [reply code/lib/csf-tools/src/getStorySortParameter.ts:112]: The (now merged) code looks like this:

```js
if (t.isFunctionExpression(storySort)) {
    const { code: sortCode } = generate.default(storySort, {});
    const functionName = storySort.id?.name;
    // Wrap the function within an arrow function, call it, and return
    const wrapper = `(a, b) => {
      ${sortCode};
      return ${functionName}(a, b)
    }`;
    // eslint-disable-next-line no-eval
    return (0, eval)(wrapper);
  }
```

so if `storySort.id` is optional, then `storySort.id?.name` could be undefined, right? meaning that `functionName` becomes undefined.

later on, `return ${functionName}(a, b)` will get executed. But then, if `functionName` is undefined, the evaluated code will be `undefined(a,b)`, which will crash.
