### PR TITLE
Automigration: Remove `@storybook/addon-essentials` proper

### LINKED ISSUE #30994: [Bug]: Storybook 9 - Can't migrate from Storybook 8 in npm project
### Describe the bug

**Repo:** [Purchases js](https://github.com/RevenueCat/purchases-js)
**Branch:** `main`

**Steps:**
- Run `npm install`
- Run `npx storybook@next upgrade`
- Notice the error:

```ts
╭───────────────────────────────────────────────────────────────────╮
│                                                                   │
│   Upgrading Storybook from version 8.6.11 to version              │
│   9.0.0-alpha.12..                                                │
│   This is a pre-release version.                                  │
│                                                                   │
╰───────────────────────────────────────────────────────────────────╯
info Checking for upgrade blockers...
No blockers found.

npm error Must provide a package name to remove
npm error A complete log of this run can be found in: /Users/yannbraga/.npm/_logs/2025-03-31T09_07_44_702Z-debug-0.log
An error occurred while removing dependencies.
Error: Command failed with exit code 1: npm uninstall
Error: Error: Command failed with exit code 1: npm uninstall
    at er.removeDependencies (/Users/yannbraga/.npm/_npx/67f5399e6d86bbf6/node_modules/storybook/dist/common/index.cjs:19085:94)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async doUpgrade (/Users/yannbraga/.npm/_npx/67f5399e6d86bbf6/node_modules/@storybook/cli/dist/bin/index.cjs:376:1107)
    at async withTelemetry (/Users/yannbraga/.npm/_npx/67f5399e6d86bbf6/node_modules/storybook/dist/core-server/index.cjs:35863:12)
    at async upgrade (/Users/yannbraga/.npm/_npx/67f5399e6d86bbf6/node_modules/@storybook/cli/dist/bin/index.cjs:376:2640)
```

I debugged and specifically for this project, the removeDependencies function is receiving the following arguments:
`{ { skipInstall: false }, dependencies: [] }`

### Reproduction link

-

### Reproduction steps

_No response_

### System

```bash
-
```

### Additional context

_No response_

### LINKED ISSUE #31004: [Bug]: Storybook 9 - ERESOLVE - Dependency resolution error when running upgrade
### Describe the bug

**Repo:** [purchases-js](https://github.com/RevenueCat/purchases-js)
**Branch:** `main`

**Steps:**
- run `npm install`
- run `npx storybook@next upgrade`
- Notice the following error:

```
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: @revenuecat/purchases-js@1.0.5
npm warn Found: storybook@8.6.4
npm warn node_modules/storybook
npm warn   peer storybook@"^8.6.4" from @storybook/addon-interactions@8.6.4
npm warn   node_modules/@storybook/addon-interactions
npm warn     dev @storybook/addon-interactions@"^8.5.0" from the root project
npm warn   12 more (@storybook/addon-viewport, @storybook/components, ...)
npm warn
npm warn Could not resolve dependency:
npm warn peer storybook@"^8.6.4" from @storybook/addon-interactions@8.6.4
npm warn node_modules/@storybook/addon-interactions
npm warn   dev @storybook/addon-interactions@"^8.5.0" from the root project
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: @revenuecat/purchases-js@1.0.5
npm warn Found: storybook@8.6.4
npm warn node_modules/storybook
npm warn   peer storybook@"^8.6.4" from @storybook/addon-interactions@8.6.4
npm warn   node_modules/@storybook/addon-interactions
npm warn     dev @storybook/addon-interactions@"^8.5.0" from the root project
npm warn   12 more (@storybook/addon-viewport, @storybook/components, ...)
npm warn
npm warn Could not resolve dependency:
npm warn peer storybook@"^8.6.4" from @storybook/addon-viewport@8.6.4
npm warn node_modules/@storybook/addon-viewport
npm warn   dev @storybook/addon-viewport@"^8.5.2" from the root project
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: @revenuecat/purchases-js@1.0.5
npm warn Found: storybook@8.6.4
npm warn node_modules/storybook
npm warn   peer storybook@"^8.6.4" from @storybook/addon-interactions@8.6.4
npm warn   node_modules/@storybook/addon-interactions
npm warn     dev @storybook/addon-interactions@"^8.5.0" from the root project
npm warn   12 more (@storybook/addon-viewport, @storybook/components, ...)
npm warn
npm warn Could not resolve dependency:
npm warn peer storybook@"^8.6.4" from @storybook/svelte@8.6.4
npm warn node_modules/@storybook/svelte
npm warn   peer @storybook/svelte@"^0.0.0-0 || ^8.0.0 || ^9.0.0-0" from @storybook/addon-svelte-csf@5.0.0-next.24
npm warn   node_modules/@storybook/addon-svelte-csf
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: @revenuecat/purchases-js@1.0.5
npm warn Found: storybook@8.6.4
npm warn node_modules/storybook
npm warn   peer storybook@"^8.6.4" from @storybook/addon-interactions@8.6.4
npm warn   node_modules/@storybook/addon-interactions
npm warn     dev @storybook/addon-interactions@"^8.5.0" from the root project
npm warn   12 more (@storybook/addon-viewport, @storybook/components, ...)
npm warn
npm warn Could not resolve dependency:
npm warn peer storybook@"^8.6.4" from @storybook/test@8.6.4
npm warn node_modules/@storybook/test
npm warn   @storybook/test@"8.6.4" from @storybook/addon-interactions@8.6.4
npm warn   node_modules/@storybook/addon-interactions
npm warn   1 more (the root project)
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: @revenuecat/purchases-js@1.0.5
npm warn Found: storybook@8.6.4
npm warn node_modules/storybook
npm warn   peer storybook@"^8.6.4" from @storybook/addon-interactions@8.6.4
npm warn   node_modules/@storybook/addon-interactions
npm warn     dev @storybook/addon-interactions@"^8.5.0" from the root project
npm warn   12 more (@storybook/addon-viewport, @storybook/components, ...)
npm warn
npm warn Could not resolve dependency:
npm warn peer storybook@"^8.2.0" from storybook-addon-pseudo-states@4.0.2
npm warn node_modules/storybook-addon-pseudo-states
npm warn   dev storybook-addon-pseudo-states@"^4.0.2" from the root project
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: @revenuecat/purchases-js@1.0.5
npm error Found: storybook@9.0.0-alpha.12
npm error node_modules/storybook
npm error   dev storybook@"^9.0.0-alpha.12" from the root project
npm error
npm error Could not resolve dependency:
npm error peer storybook@"^8.6.11" from @storybook/test@8.6.11
npm error node_modules/@storybook/test
npm error   dev @storybook/test@"^8.5.0" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /Users/yannbraga/.npm/_logs/2025-04-01T08_54_18_996Z-eresolve-report.txt
npm error A complete log of this run can be found in: /Users/yannbraga/.npm/_logs/2025-04-01T08_54_18_996Z-debug-0.log
```

### Reproduction link

-

### Reproduction steps

_No response_

### System

```bash
-
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ndelangen**
Closes https://github.com/storybookjs/storybook/issues/30994
Closes https://github.com/storybookjs/storybook/issues/31004

## What I did

This pull request includes significant updates to the migration logic for handling the removal of `@storybook/addon-essentials` and its features moving to the core of Storybook. The changes ensure that the configuration and dependencies are correctly updated based on whether the user had the docs feature enabled or disabled.

Key changes include:

### Migration Logic Updates:
* Updated migration description to reflect that `@storybook/addon-essentials` is being removed and its features are moving to the core.
* Modified the prompt messages to provide clearer instructions based on whether the docs feature was enabled or disabled.
* Ensured that the `@storybook/addon-essentials` entry is completely removed from the configuration.
* Added logic to remove the `@storybook/addon-essentials` package and, if necessary, install `@storybook/addon-docs` if the docs feature was enabled and not already installed.

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This pull request has been released as version `0.0.0-pr-31015-sha-a186233f`. Try it out in a new sandbox by running `npx storybook@0.0.0-pr-31015-sha-a186233f sandbox` or in an existing project with `npx storybook@0.0.0-pr-31015-sha-a186233f upgrade`.
<details>
<summary>More information</summary>

| | |
| --- | --- |
| **Published version** | [`0.0.0-pr-31015-sha-a186233f`](https://npmjs.com/package/storybook/v/0.0.0-pr-31015-sha-a186233f) |
| **Triggered by** | @valentinpalkovic |
| **Repository** | [storybookjs/storybook](https://github.com/storybookjs/storybook) |
| **Branch** | [`norbert/improve-cpc-automigrations`](https://github.com/storybookjs/storybook/tree/norbert/improve-cpc-automigrations) |
| **Commit** | [`a186233f`](https://github.com/storybookjs/storybook/commit/a186233f1e58de57bee8c3676c03cd86afc9ac6b) |
| **Datetime** | Wed Apr  2 18:09:24 UTC 2025 (`1743617364`) |
| **Workflow run** | [14226524759](https://github.com/storybookjs/storybook/actions/runs/14226524759) |

To request a new release of this pull request, mention the `@storybookjs/core` team.

_core team members can create a new canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=31015`_
</details>

## Greptile Summary

This PR enhances the automigration process by refining the removal logic for @storybook/addon-essentials and introduces a new migration for @storybook/addon-mdx-gfm. The changes improve configuration cleanup and dependency management based on the docs feature configuration.

- Updated /code/lib/cli-storybook/src/automigrate/fixes/addon-essentials-remove-docs.ts to fully remove addon-essentials and conditionally install addon-docs.
- Revised tests in /code/lib/cli-storybook/src/automigrate/fixes/addon-essentials-remove-docs.test.ts to verify removal and dependency commands.
- Added migration and tests for @storybook/addon-mdx-gfm in /code/lib/cli-storybook/src/automigrate/fixes/addon-mdx-gfm-remove.ts and its test file.
- Integrated the new mdx-gfm migration fix into /code/lib/cli-storybook/src/automigrate/fixes/index.ts.

### CODE REVIEW

File: code/lib/cli-storybook/src/automigrate/fixes/addon-mdx-gfm-remove.ts [hunk 1]
```diff
@@ -0,0 +1,85 @@
...
+      This package has been removed in Storybook 9.0. We'll remove it from your configuration and dependencies.
+    `;
+  },
+
+  async run({ result, dryRun, packageManager, mainConfigPath }) {
+    const { hasMdxGfm } = result;
+
+    if (!hasMdxGfm) {
+      return;
+    }
```
Comment (valentinpalkovic) [inline code/lib/cli-storybook/src/automigrate/fixes/addon-mdx-gfm-remove.ts:60]: In the `run` function `hasMdxGfm` is always true. I think also, that you can adjust the type in line 10 to `hasMdxGfm: true;`. Because if `mdxGfm` cannot be detected, you are returning null;

File: code/lib/cli-storybook/src/automigrate/fixes/addon-mdx-gfm-remove.ts [hunk 2]
```diff
@@ -0,0 +1,85 @@
...
+      if (mdxGfmIndex !== -1) {
+        main.removeField(['addons', mdxGfmIndex]);
+      }
+    });
+
+    if (!dryRun) {
+      // Remove addon-mdx-gfm package
+      await packageManager.removeDependencies({}, ['@storybook/addon-mdx-gfm']);
+    }
+  },
```
Comment (valentinpalkovic) [inline code/lib/cli-storybook/src/automigrate/fixes/addon-mdx-gfm-remove.ts:84]: Isn't it easier to call `npx storybook remove @storybook/addon-mdx-gfm` instead?

**Review by valentinpalkovic — APPROVED** [review]

File: code/lib/cli-storybook/src/automigrate/fixes/addon-mdx-gfm-remove.ts (hunk 2 above)
Comment (ndelangen) [reply code/lib/cli-storybook/src/automigrate/fixes/addon-mdx-gfm-remove.ts]: sure!

File: code/lib/cli-storybook/src/automigrate/fixes/addon-mdx-gfm-remove.ts [hunk 3]
```diff
@@ -0,0 +1,58 @@
...
+      return null;
+    }
+
+    try {
+      let hasMdxGfm = false;
+
+      await updateMainConfig({ mainConfigPath, dryRun: true }, () => {
+        const addonNames = getAddonNames(mainConfig);
+        hasMdxGfm = addonNames.includes('@storybook/addon-mdx-gfm');
+      });
```
Comment (valentinpalkovic) [inline code/lib/cli-storybook/src/automigrate/fixes/addon-mdx-gfm-remove.ts:33]: The `updateMainConfig` wrapper seems to be unnecessary

File: code/lib/cli-storybook/src/automigrate/fixes/addon-mdx-gfm-remove.ts [hunk 4]
```diff
@@ -0,0 +1,58 @@
...
+
+  prompt() {
+    return dedent`
+      We've detected that you have ${picocolors.yellow('@storybook/addon-mdx-gfm')} installed.
+      
+      This package has been removed in Storybook 9.0. We'll remove it from your configuration and dependencies.
+    `;
+  },
+
+  async run({ result, packageManager }) {
```
Comment (valentinpalkovic) [inline code/lib/cli-storybook/src/automigrate/fixes/addon-mdx-gfm-remove.ts:55]: `result` not used

File: code/lib/cli-storybook/src/automigrate/fixes/addon-storysource-remove.ts [hunk 5]
```diff
@@ -0,0 +1,58 @@
...
+    } catch (err) {
+      return null;
+    }
+  },
+
+  prompt() {
+    return dedent`
+      We've detected that you have ${picocolors.yellow('@storybook/addon-storysource')} installed.
+      
+      This package has been removed in Storybook 9.0. We'll remove it from your configuration and dependencies.
```
Comment (valentinpalkovic) [inline code/lib/cli-storybook/src/automigrate/fixes/addon-storysource-remove.ts:51]: You should mention the [migration entry](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#migration-from-storybookaddon-storysource-to-code-panel) for more information
