### PR TITLE
fix: removed opacity from list-item color

### LINKED ISSUE #21990: [Bug]: SB 7 Left/Right in TooltipLinkList are color 0.5 - should be 1.0
### Describe the bug

list-item has the following css:
```css
color: rgba(201,205,207,0.5);
```

This is causing text/emojis in the left/right to be transparent.

Before (SB6):
before

Now (SB7):
after

To fix:
```css
color: rgba(201,205,207);
```

### To Reproduce

_No response_

### System

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by adityaKrModak**
Closes #21990

## What I did
I've updated the color property in the Item styled component which was getting inherited in the Left and Right styled components of ListItem.tsx.

## How to test

Here is the before and after screenshots:

Pasted Graphic

Pasted Graphic 1

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Review by valentinpalkovic — APPROVED** [review]

File: code/ui/components/src/tooltip/ListItem.tsx [hunk 1]
```diff
@@ -126,7 +126,7 @@ const Item = styled.a<ItemProps>(
   ({ theme }) => ({
     fontSize: theme.typography.size.s1,
     transition: 'all 150ms ease-out',
-    color: transparentize(0.5, theme.color.defaultText),
+    color: theme.color.defaultText,
```
Comment (MichaelArestad) [inline code/ui/components/src/tooltip/ListItem.tsx:129]: Thanks for this PR! Can you please change this to `theme.color.dark`. It should resolve the issue and be the color that was originally proposed with the menu update.

**Review by MichaelArestad — CHANGES_REQUESTED** [review]

File: code/ui/components/src/tooltip/ListItem.tsx (hunk 1 above)
Comment (adityaKrModak) [reply code/ui/components/src/tooltip/ListItem.tsx]: done!

**Review by MichaelArestad — APPROVED** [review]
