### PR TITLE
Fix css relative asset urls

### LINKED ISSUE #4645: Relative URLs to assets no longer work in CSS now that CSS no longer gets inlined
**Describe the bug**
I just upgraded to Storybook 4, and I _think_ this issue is caused by that (it required a lot of other moving parts as well).

Basically, in my React component, I `import './Widget.css';`. Then in `Widget.css`, I reference a background image located in the same folder as such: `background-image: url(orcid_16x16.png);`.

With Storybook 3, this just worked even using `build-storybook`: the image URL was updated to `static/media/orcid_16x16.2dddb203.png`, and since the CSS was inline, this path was correct.

Now with Storybook 4, however, the URL is still updated to that value, but because it is now located in a CSS file that itself located in `static/css`, the browser is now trying to find the image at `static/css/static/media/`, and hence cannot find it.

**To Reproduce**
1. Visit my [built Storybook v3](http://plaudit.pub/components/?knob-Endorsements=%7B%22first-orcid%22%3A%7B%22endorserName%22%3A%22Alice%20Doe%22%2C%22robust%22%3Atrue%7D%2C%22second-orcid%22%3A%7B%22endorserName%22%3A%22Bob%20Doe%22%2C%22robust%22%3Atrue%7D%7D&selectedKind=Widget&selectedStory=With%20one%20endorsement&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)
2. Notice that there is a green icon to the left-hand side of Alice Doe
3. Now visit [that same page in Storybook 4](https://35-migrate-client-to-creat-review.plaudit.pub/components/?selectedKind=Widget&selectedStory=With%20one%20endorsement&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)
4. Notice that the image is missing

**Expected behavior**
The image to also be present in Storybook 4 - presumably by making sure that URL imports are rewritten to be relative to the CSS file they are in.

**Screenshots**

In Storybook 3:
image

In Storybook 4:
image

**System:**
 - OS: Ubuntu Linux 18.04
 - Device: Dell XPS 13 9360
 - Browser: Firefox
 - Framework: React
 - Addons: [if relevant]
 - Version: 4.0.0

### PR DESCRIPTION
**Pull request by chadfawcett**
Issue: resolves #4645

## What I did
* Added a react-scripts v2 cli test fixture
* Removed the incorrect file paths for css minification in cra prod webpack config.

## How to test

I tested both by adding a relative asset to the `cra-kitchen-sink` styles and built storybook for prod (yarn build-storybook).

I also cloned @Vinnl's repo and testing the stories there.

### CODE REVIEW

File: app/react/src/server/cra_config.js [hunk 1]
```diff
@@ -64,14 +64,7 @@ export function applyCRAWebpackConfig(baseConfig) {
   //  Add css minification for production
   const plugins = [...baseConfig.plugins];
   if (baseConfig.mode === 'production') {
-    plugins.push(
-      new MiniCssExtractPlugin({
-        // Options similar to the same options in webpackOptions.output
-        // both options are optional
-        filename: 'static/css/[name].[contenthash:8].css',
-        chunkFilename: 'static/css/[name].[contenthash:8].chunk.css',
```
Comment (chadfawcett) [inline app/react/src/server/cra_config.js]: These settings were copied over from cra's webpack config. Since storybook does not have a dynamic `publicPath` like cra, these are not needed. As mentioned in the `storybook` config, relative urls always work.

https://github.com/storybooks/storybook/blob/48b2b51332156d690f49b334ce998ad5c50f0b12/lib/core/src/server/config/webpack.config.prod.js#L28-L33

**Comment by Vinnl** [comment]
I just tested this by [manually applying the same fix](https://gitlab.com/Flockademic/plaudit/commit/cb018e555f3c973ed5e557d26d696ffd4a6214fa) and I confirm that [CSS-imported images are shown now](https://35-migrate-client-to-creat-review.plaudit.pub/components/?selectedKind=Widget&selectedStory=With%20one%20endorsement&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs). Thanks!

**Review by shilman — APPROVED** [review]
Don't understand the change but seems to fix the problem!

**Comment by chadfawcett** [comment]
@shilman In CRA, they have a [dynamic public path](https://github.com/facebook/create-react-app/blob/8a74ac577a9087cbae76bc54682c88bbe5a046f1/packages/react-scripts/config/webpack.config.prod.js#L137) and a check to see if [relative paths should be used](https://github.com/facebook/create-react-app/blob/8a74ac577a9087cbae76bc54682c88bbe5a046f1/packages/react-scripts/config/webpack.config.prod.js#L76).

My original implementation copied over the CSS minification paths that didn't match up with the mini css loader. So this just gets those back in sync.

**Comment by chadfawcett** [comment]
@igor-dv Which test checks the snapshots? Everything either passes locally or fails on the Vue bugs in Master.
