### PR TITLE
ReactVite: Docgen ignore un-parsable files

### LINKED ISSUE #25662: [Bug]: @storybook/react-vite configuration for react-docgen doesn't support components that import postcss modules.
### Describe the bug

Have a component like so

```jsx
import React from "react"
import styles, { stylesheet } from "./Container.module.css"

const Container = ({ children }) => (
  <div>
    {children}
  </div>
)

export default Container;
export stylesheet;
```

And where the css file contains an `@import`

```css
@import url("../../css/variables.css");
```

The babel config passed to `react-docgen` doesn't take into account the .babelrc file and attempts to parse the .css file as JavaScript.

This causes an error like so

```
[vite] Internal server error: /path/to/Container.module.css: Support for the experimental syntax 'decorators' isn't currently enabled (1:1):
```

Is there anyway to configure react-docgen to ignore .css files in this case?
At present have fallen back to disabling it and manually putting `description` properties on argTypes instead of auto-generating them from propType docblocks.

Note we use rollup-plugin-postcss to allow emitting a single inline critical css component with the exported stylesheets.
We have a vite plugin (See the reproduction code) that does the equivalent.

### To Reproduce

https://stackblitz.com/edit/github-cwovgn-yvzreq?file=src%2Fstories%2FButton.jsx

### System

```bash
Storybook Environment Info:

  System:
    OS: Linux 6.5 Ubuntu 23.10 23.10 (Mantic Minotaur)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1195G7 @ 2.90GHz
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 16.20.1 
    Yarn: 1.22.19
    npm: 8.19.4 
  Browsers:
    Chrome: 120.0.6099.216
  npmPackages:
    @storybook/addon-actions: ^7.6.6 => 7.6.7 
    @storybook/addon-docs: ^7.6.6 => 7.6.7 
    @storybook/addon-essentials: ^7.6.6 => 7.6.7 
    @storybook/addon-links: ^7.6.6 => 7.6.7 
    @storybook/addon-styling: ^1.3.7 => 1.3.7 
    @storybook/addon-viewport: ^7.6.6 => 7.6.7 
    @storybook/addons: ^7.6.6 => 7.6.7 
    @storybook/react: ^7.6.6 => 7.6.7 
    @storybook/react-vite: ^7.6.6 => 7.6.7 
    @storybook/theming: ^7.6.6 => 7.6.7 
    eslint-plugin-storybook: ^0.6.15 => 0.6.15 
    storybook: ^7.6.6 => 7.6.7
```

### Additional context

We're exporting the stylesheet so we can get reliable class names from CSS modules and combine them into a single critical CSS file that we inline.

### LINKED ISSUE #26109: [Bug]: Storybook 8: [storybook:react-docgen-plugin] Leading decorators must be attached to a class declaration in scss
### Describe the bug

When I try to build I got:

```
[storybook:react-docgen-plugin] <...>/Some.module.scss: Leading decorators must be attached to a class declaration. (1:5)

> 1 | @use 'themes';
    |      ^
  2 | @use 'colors';
  3 |
  4 | $vertical-padding: 14px;
file: <...>/Some.tsx:1:5
=> Failed to build the preview
SyntaxError: ./<...>/Some.module.scss: Leading decorators must be attached to a class declaration. (1:5)

> 1 | @use 'themes';
    |      ^
  2 | @use 'colors';
  3 |
  4 | $vertical-padding: 14px;
    at constructor (./node_modules/@babel/parser/lib/index.js:356:19)
    at JSXParserMixin.raise (./node_modules/@babel/parser/lib/index.js:3223:19)
    at JSXParserMixin.parseDecorators (./node_modules/@babel/parser/lib/index.js:12790:18)
    at JSXParserMixin.parseStatementLike (./node_modules/@babel/parser/lib/index.js:12586:25)
    at JSXParserMixin.parseModuleItem (./node_modules/@babel/parser/lib/index.js:12565:17)
    at JSXParserMixin.parseBlockOrModuleBlockBody (./node_modules/@babel/parser/lib/index.js:13189:36)
    at JSXParserMixin.parseBlockBody (./node_modules/@babel/parser/lib/index.js:13182:10)
    at JSXParserMixin.parseProgram (./node_modules/@babel/parser/lib/index.js:12464:10)
    at JSXParserMixin.parseTopLevel (./node_modules/@babel/parser/lib/index.js:12454:25)
    at JSXParserMixin.parse (./node_modules/@babel/parser/lib/index.js:14376:10)
    at parse (./node_modules/@babel/parser/lib/index.js:14396:26)
    at parser (./node_modules/@babel/core/lib/parser/index.js:41:34)
    at parser.next (<anonymous>)
    at parse (./node_modules/@babel/core/lib/parse.js:25:37)
    at parse.next (<anonymous>)
    at evaluateSync (./node_modules/gensync/index.js:251:28)
    at sync (./node_modules/gensync/index.js:89:14)
    at stopHiding - secret - don't use this - v1 (./node_modules/@babel/core/lib/errors/rewrite-stack-trace.js:47:12)
    at parseSync (./node_modules/@babel/core/lib/parse.js:40:72)
    at babelParser (./node_modules/react-docgen/dist/babelParser.js:78:41)
    at FileState.parse (./node_modules/react-docgen/dist/FileState.js:101:48)
    at FileState.resolveImportedValue (./node_modules/react-docgen/dist/importer/makeFsImporter.js:119:23)
    at FileState.import (./node_modules/react-docgen/dist/FileState.js:92:67)
    at findScopePath (./node_modules/react-docgen/dist/utils/resolveToValue.js:61:57)
    at resolveToValue (./node_modules/react-docgen/dist/utils/resolveToValue.js:106:24)
    at resolveToValue (./node_modules/react-docgen/dist/utils/resolveToValue.js:123:22)
    at resolveHOC (./node_modules/react-docgen/dist/utils/resolveHOC.js:48:59)
    at findComponentDefinition (./node_modules/react-docgen/dist/utils/findComponentDefinition.js:64:85)
    at ./node_modules/react-docgen/dist/resolver/FindExportedDefinitionsResolver.js:44:67
    at Array.forEach (<anonymous>)
    at Object.exportDeclaration (./node_modules/react-docgen/dist/resolver/FindExportedDefinitionsResolver.js:43:54)
    at NodePath._call (./node_modules/@babel/traverse/lib/path/context.js:46:20)
    at NodePath.call (./node_modules/@babel/traverse/lib/path/context.js:36:17)
    at NodePath.visit (./node_modules/@babel/traverse/lib/path/context.js:82:31)
    at TraversalContext.visitQueue (./node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitMultiple (./node_modules/@babel/traverse/lib/context.js:61:17)
    at TraversalContext.visit (./node_modules/@babel/traverse/lib/context.js:107:19)
    at traverseNode (./node_modules/@babel/traverse/lib/traverse-node.js:22:17)
    at NodePath.visit (./node_modules/@babel/traverse/lib/path/context.js:88:52)
    at TraversalContext.visitQueue (./node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (./node_modules/@babel/traverse/lib/context.js:65:19)
    at TraversalContext.visit (./node_modules/@babel/traverse/lib/context.js:109:19)
    at traverseNode (./node_modules/@babel/traverse/lib/traverse-node.js:22:17)
    at traverse (./node_modules/@babel/traverse/lib/index.js:52:34)
    at FileState.traverse (./node_modules/react-docgen/dist/FileState.js:112:5)
    at FindExportedDefinitionsResolver.resolve (./node_modules/react-docgen/dist/resolver/FindExportedDefinitionsResolver.js:88:10)
    at runResolver (./node_modules/react-docgen/dist/resolver/utils/runResolver.js:30:47)
    at parse (./node_modules/react-docgen/dist/parse.js:57:63)
    at defaultParse (./node_modules/react-docgen/dist/main.js:55:35)
    at Object.transform (./node_modules/@storybook/react-vite/dist/preset.js:1:2727)
```

But `storybook dev` works fine.

### To Reproduce

_No response_

### System

_No response_

### Additional context

SB 8.0.0-beta.3

### PR DESCRIPTION
**Pull request by ndelangen**
Closes: https://github.com/storybookjs/storybook/issues/26109
Closes: https://github.com/storybookjs/storybook/issues/25662

Related: https://github.com/reactjs/react-docgen/issues/892

## What I did

I made a video explaining the process:
[Watch the video](https://www.youtube.com/embed/WoXIkX4VF84)

- I modified the `react-docgen` configuration to override the mechanism used to resolve files.
- When `docgen` tries to resolve a file, that we don't include in the files to transform, the custom resolver will throw an error.
- The error will cause `react-docgen` to skip/ignore the file.
- Unlike the parsing error, which is fatal and bubbles up to here https://github.com/storybookjs/storybook/blob/1d5e9f8d179ef19175d2c2bb6bc3ba8a9d511e35/code/frameworks/react-vite/src/plugins/react-docgen.ts#L75

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

I performed a manual test by copying over `frameworks/react-vite/dist` to a reproduction provided by the user (which I modified to make more informative).

The error went away, and docgen information showed up in the bundled assets's code.

The UI changes detected by chromatic are the proof the fix is working.

I added an explicit test to prevent this regression in the future.

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

File: code/frameworks/react-vite/src/plugins/react-docgen.ts [hunk 1]
```diff
@@ -36,14 +36,21 @@ export function reactDocgen({
...
 
       try {
         const docgenResults = parse(src, {
           resolver: defaultResolver,
           handlers,
-          importer: defaultImporter,
+          importer: makeFsImporter((filename, basedir) => {
+            if (!filter(path.relative(cwd, join(basedir, filename)))) {
+              throw new ReactDocgenResolveError(filename);
+            }
```
Comment (ndelangen) [inline code/frameworks/react-vite/src/plugins/react-docgen.ts:50]: So this filtering might be filtering too much... causing this:
https://www.chromatic.com/test?appId=630511d655df72125520f051&id=65e067dddcd6da9ad2e2657e

Going to investigate this further.

Comment (ndelangen) [reply code/frameworks/react-vite/src/plugins/react-docgen.ts]: So I simplified the filtering, but it's not helping with the regression.
Need to investigate further.

**Comment by ndelangen** [comment]
I'm experimenting with bringing this fix to webpack as well

File: code/renderers/react/template/stories/docgen-components/ts-function-component/input.tsx [hunk 2]
```diff
@@ -1,6 +1,9 @@
 import React from 'react';
 
 import { imported } from '../imported';
+// eslint-disable-next-line @typescript-eslint/ban-ts-comment
+// @ts-ignore (css import not supported in TS)
+import styles from '../imported.module.css';
```
Comment (ndelangen) [inline code/renderers/react/template/stories/docgen-components/ts-function-component/input.tsx:6]: This was causing this issue in the repro.

I had to add the ts-ignore, and couldn't make it a expect-error.
This errors when running the `check` task, but it does not when loaded into storybook, so a expect-error would actually cause issues there.

Comment (ndelangen) [reply code/renderers/react/template/stories/docgen-components/ts-function-component/input.tsx:6]: See:
https://app.circleci.com/pipelines/github/storybookjs/storybook/71811/workflows/33e08595-1907-487c-b454-418ca1f3eeae/jobs/632550

File: code/presets/react-webpack/src/loaders/react-docgen-loader.ts [hunk 3]
```diff
@@ -11,6 +11,11 @@ import type { LoaderContext } from 'webpack';
 import type { Handler, NodePath, babelTypes as t, Documentation } from 'react-docgen';
 import { logger } from '@storybook/node-logger';
 
+import {
+  ReactDocgenResolveError,
+  defaultLookupModule,
+} from '../../../../frameworks/react-vite/src/plugins/docgen-resolver';
```
Comment (shilman) [inline code/presets/react-webpack/src/loaders/react-docgen-loader.ts:17]: Is there anything we can do to clean things up? cc @valentinpalkovic

File: code/frameworks/react-vite/src/plugins/react-docgen.ts [hunk 4]
```diff
@@ -36,14 +36,23 @@ export function reactDocgen({
...
 
       try {
         const docgenResults = parse(src, {
           resolver: defaultResolver,
           handlers,
-          importer: defaultImporter,
+          importer: makeFsImporter((filename, basedir) => {
+            const result = defaultLookupModule(filename, basedir);
+
+            if (!result.match(/\.(mjs|tsx?|jsx?)$/)) {
```
Comment (shilman) [inline code/frameworks/react-vite/src/plugins/react-docgen.ts:50]: Why don't we use the `RESOLVE_EXTENSIONS`?

File: code/presets/react-webpack/src/loaders/react-docgen-loader.ts (hunk 3 above)
Comment (ndelangen) [reply code/presets/react-webpack/src/loaders/react-docgen-loader.ts:17]: I did this on purpose.

The only 2 places in our codebase that currently depend on `react-docgen` are:
Screenshot 2024-02-29 at 17 49 37

So in order to extract this somewhere else, I'd need to introduce this to some library.
I understand this might look a bit weird, but it's bundled correctly.

I'm open to suggestions that do not create a new package.

Alternatively (I'm not a fan of this idea either) we could add this code to docs-tools;
but then docs tools gains a dependency to `react-docgen`, and with it, this:
Screenshot 2024-02-29 at 17 53 04

If you feel like this is so bad we're better off duplicating the code, we could do that?

File: code/frameworks/react-vite/src/plugins/react-docgen.ts (hunk 4 above)
Comment (ndelangen) [reply code/frameworks/react-vite/src/plugins/react-docgen.ts:50]: Because I though this would be more expressive.

File: code/presets/react-webpack/src/loaders/react-docgen-loader.ts (hunk 3 above)
Comment (valentinpalkovic) [reply code/presets/react-webpack/src/loaders/react-docgen-loader.ts:17]: Although this is kind of ugly (requiring files from the `react-vite` framework into the `react-webpack` preset things will compile.

I would rather vote to copy the code from `frameworks/react-vite/src/plugins/docgen-resolver` into a directory that is correctly accessible by both, the framework `react-vite` and the preset `react-webpack`, like in e.g. `@storybook/core-common` 

**or** 

we just duplicate the code in `../../../../frameworks/react-vite/src/plugins/docgen-resolver` which I think is okay if we don't want to move it into a sharable core package.

The third option is that things stay as is, but then `resolve` should be a direct dependency of the `react-webpack` package.

**Review by valentinpalkovic — COMMENTED** [review]
Thanks for the video! It was very helpful!

File: code/frameworks/react-vite/src/plugins/react-docgen.ts (hunk 4 above)
Comment (valentinpalkovic) [reply code/frameworks/react-vite/src/plugins/react-docgen.ts:50]: We can write it out, but we should make sure that all possible extensions which the user might use are supported (optional <c|m> prefix for all <js|ts> files with optional <x> suffix).

File: code/presets/react-webpack/src/loaders/react-docgen-loader.ts (hunk 3 above)
Comment (valentinpalkovic) [reply code/presets/react-webpack/src/loaders/react-docgen-loader.ts:17]: @ndelangen Just to clarify. Are you talking about extracting `code/frameworks/react-vite/src/plugins/docgen-resolver.ts` into a core package? Because this file doesn't have any `react-docgen` dependencies or am i overlooking something?

**Comment by valentinpalkovic** [comment]
Great work! 🥳

File: code/presets/react-webpack/src/loaders/react-docgen-loader.ts (hunk 3 above)
Comment (ndelangen) [reply code/presets/react-webpack/src/loaders/react-docgen-loader.ts:18]: Can you define "correctly accessible by both"? @valentinpalkovic 
Placing the code in a shared package, like I mentioned that that would cause that package to gain dependencies it currently does not have.
You suggest `core-common`, I suggested `docs-tools`.

> Are you talking about extracting `code/frameworks/react-vite/src/plugins/docgen-resolver.ts` into a core package?
Yes we currently do not have a suitable package, hence I decided to just do this which minimizes duplicated code, and optimizes for easy of replaceability because I assume that at some point in the future this code will change upstream and updating it in 2 places going to be fragile, right?

But if you both agree that duplicating the code is better than 1 slightly ugly import, I'll change it.

File: code/frameworks/react-vite/src/plugins/react-docgen.ts (hunk 4 above)
Comment (valentinpalkovic) [reply code/frameworks/react-vite/src/plugins/react-docgen.ts]: Sure!

File: code/frameworks/react-vite/src/plugins/react-docgen.ts [hunk 5]
```diff
@@ -36,14 +40,23 @@ export function reactDocgen({
...
         const docgenResults = parse(src, {
           resolver: defaultResolver,
           handlers,
-          importer: defaultImporter,
+          importer: makeFsImporter((filename, basedir) => {
+            const result = defaultLookupModule(filename, basedir);
+
+            if (RESOLVE_EXTENSIONS.find((ext) => result.endsWith(ext)) === undefined) {
+              return result;
+            }
```
Comment (ndelangen) [inline code/frameworks/react-vite/src/plugins/react-docgen.ts:56]: @shilman here i'm now using the array, do you think this is less confusing code?

File: code/presets/react-webpack/src/loaders/react-docgen-loader.ts (hunk 3 above)
Comment (ndelangen) [reply code/presets/react-webpack/src/loaders/react-docgen-loader.ts:18]: > `resolve` should be a direct dependency of the `react-webpack` package.

Ah, yes that's right. I missed that. 🙏

Comment (ndelangen) [reply code/presets/react-webpack/src/loaders/react-docgen-loader.ts]: I duplicated the code.

File: code/frameworks/react-vite/src/plugins/react-docgen.ts (hunk 4 above)
Comment (ndelangen) [reply code/frameworks/react-vite/src/plugins/react-docgen.ts]: OK.

File: code/frameworks/react-vite/src/plugins/react-docgen.ts (hunk 5 above)
Comment (ndelangen) [reply code/frameworks/react-vite/src/plugins/react-docgen.ts:56]: > I guess we should then also adjust line 29 to support a wider range of file extensions?!

I guess that's done now, but originally I figured we'd keep it the same as the code just slightly above it.
As it made no sense to me to use 2 different patterns.

Check line 33 here (that code has been there like that for 19 months

https://github.com/storybookjs/storybook/blob/899ba75db383b8745d6d5514b1f2226d41614522/code/frameworks/react-vite/src/plugins/react-docgen.ts#L32-L56

So in my defense, I thought that to keep those patterns in sync was pretty reasonable.

Comment (ndelangen) [reply code/frameworks/react-vite/src/plugins/react-docgen.ts:56]: Is the request for me to make a change to the code above (what now line 33)?

**Review by valentinpalkovic — APPROVED** [review]
