### PR TITLE
UI: Expand sidebar for selected story when using composition

### LINKED ISSUE #22878: [Bug]: loading a composition story in a new tab doesn't expand the menu
### Describe the bug

Hi,

When clicking a link to a story in my main Storybook it expands the menu 'til the targeted story. See:
https://dsfr-connect.rame.fr/main/?path=/story/gallery-page-account-recover-1-form--default

But when targeting a story from a composition, it doesn't force expanding the menu:
https://dsfr-connect.rame.fr/main/?path=/story/bootstrap-v5_gallery-examples-buttons--default

Is it something expected?

Thank you,

### To Reproduce

-

### System

```shell
-
```

### Additional context

-

### PR DESCRIPTION
**Pull request by joaonunomota**
Closes #22878

## What I did

- Update the `isExpanded` variable when a `selectedStoryId` is found in the `index` provided to the `Ref`.
- The `Refs` component is expanded when the selected story is inside the Ref and either:
  - storybook is initialized
  - the user switches to a new story
- This follows the current behaviour for automatically expanding nodes in the `Tree` component

### Expanding when opening storybook:

expand-on-refresh

### Expand when switching story using shortcut:

ref-expand-on-next-story

## How to test

1. Create two sandboxes
2. Add the following to main.ts on the first storybook:
```
  refs: {
    other: {
      title: 'other',
      url: 'http://localhost:6007',
      expanded: false
    }
  }
```
3. Run the sandboxes with `yarn storybook` and `yarn storybook --port 6007`
4. Access a story within the composition and refresh the page to see the ref open automatically
4. Navigate between stories within the composition and to see the ref open automatically after being closed

## Checklist

- [x] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [x] Make sure to add/update documentation regarding your changes
- [x] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "build", "documentation", "maintenance", "dependencies", "other"]`

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

File: code/ui/manager/src/components/sidebar/Refs.tsx [hunk 1]
```diff
@@ -131,6 +131,12 @@ export const Ref: FC<RefType & RefProps & { status?: State['status'] }> = React.
   const state = getStateType(isLoading, isAuthRequired, isError, isEmpty);
   const [isExpanded, setExpanded] = useState<boolean>(expanded);
 
+  useEffect(() => {
+    if (index && selectedStoryId && index[selectedStoryId]) {
+      setExpanded(true);
+    }
+  }, [setExpanded, index, selectedStoryId]);
```
Comment (ndelangen) [inline code/ui/manager/src/components/sidebar/Refs.tsx:138]: I'm not sure we really need the useEffect?

Would this work instead:
```
const [isExpanded, setExpanded] = useState<boolean>(expanded || index && (selectedStoryId && index[selectedStoryId]));
```

Comment (joaonunomota) [reply code/ui/manager/src/components/sidebar/Refs.tsx:138]: `useEffect` is needed to expand the Ref when storybook is starting up, since `index` is undefined on the component's first render.

I also used `useEffect` to update `isExpanded` when the user selects a new story using a keyboard shortcut or the shortcuts menu, so that it acts like the `Tree` component used in the sidebar. The `useEffect` also makes it so that `index[selectedStoryId]` is only checked when either `selectedStoryId` or `index` is updated.

p.s. I added some gifs to the PR description to make clearer how the Ref acts now.

**Comment by joaonunomota** [comment]
Let me know if there are any issues with the pull request @yannbf :) Happy to make changes if necessary

**Review by ndelangen — APPROVED** [review]

**Review by cdedreuille — APPROVED** [review]
