### PR TITLE
Addon-docs: Fix `react-dom/server` imports breaking stories and docs

### LINKED ISSUE #26532: [Bug]: 8.0.0-alpha.4 broke stories that use ag-grid-react
### Describe the bug

When loading stories using ag-grid-react you get the following error:

image

### To Reproduce

https://stackblitz.com/edit/github-shgzvb?file=src%2Fstories%2Fdata.ts

### System

```bash
Storybook Environment Info:

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm <----- active
    pnpm: 8.15.3 - /usr/local/bin/pnpm
  npmPackages:
    @storybook/addon-essentials: ^8.1.0-alpha.1 => 8.1.0-alpha.1 
    @storybook/addon-interactions: ^8.1.0-alpha.1 => 8.1.0-alpha.1 
    @storybook/addon-links: ^8.1.0-alpha.1 => 8.1.0-alpha.1 
    @storybook/addon-onboarding: ^8.1.0-alpha.1 => 8.1.0-alpha.1 
    @storybook/blocks: ^8.1.0-alpha.1 => 8.1.0-alpha.1 
    @storybook/react: ^8.1.0-alpha.1 => 8.1.0-alpha.1 
    @storybook/react-vite: ^8.1.0-alpha.1 => 8.1.0-alpha.1 
    @storybook/test: ^8.1.0-alpha.1 => 8.1.0-alpha.1 
    storybook: ^8.1.0-alpha.1 => 8.1.0-alpha.1
```

### Additional context

This is because ag-grid-react uses react-dom/server: https://github.com/ag-grid/ag-grid/blob/efc1ab73566f0e541ce30c44ba3fb1ff1e0ab903/packages/ag-grid-react/src/shared/reactComponent.ts#L6

Which is being resolved to [react-dom-server.node.development.js](https://unpkg.com/browse/react-dom@18.2.0/cjs/react-dom-server-legacy.node.development.js)

```js
var stream = require('stream');
...
function _inheritsLoose(subClass, superClass) {
subClass.prototype = Object.create(superClass.prototype);
subClass.prototype.constructor = subClass;
subClass.__proto__ = superClass;
}

var ReactMarkupReadableStream = /*#__PURE__*/function (_Readable) {
	_inheritsLoose(ReactMarkupReadableStream, _Readable);
```

`_Readable` is `stream.Readable` which is a node API so it undefined in a browser which means `superClass.prototype` throws the error.

react-dom/server is being resolved to the node version because of the vite dedupe plugin https://github.com/storybookjs/storybook/blame/dfa09c483863353212b1125a4091ef4a4878c7df/code/addons/docs/src/preset.ts#L143-L162

I have confirmed this by removing it by adding:

```js
    const fixedConfig = {
      ...config,
      plugins: config.plugins?.filter(
        (plugin) => plugin?.name !== "storybook:package-deduplication"
      ),
    };
```

### PR DESCRIPTION
**Pull request by JReinhold**
Closes https://github.com/storybookjs/storybook/issues/26532

## To do

- [ ] Fix E2E docs tests for resolved react version
- [ ] Add a story showing the resolved react version

## What I did

- Added an explicit alias to `react-dom/server`, so Vite wouldn't resolve that to `PATH/react-dom/server.js` (which just redirects to `server.node.js` but instead `PATH/react-dom/server.browser.js`.
- Improved tests to ensure React is correct in stories and autodocs too, and that they are the same version.

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [X] end-to-end tests

#### Manual testing

1. Create a sandbox
2. At the top of `Button.stories.ts`, add `import * as ReactDomServer from 'react-dom/server';`
3. See that the story still works.

A. Try in a React-based and non-React sandbox
B. ... and try across Yarn, Yarn PnP and pnpm as well

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This pull request has been released as version `0.0.0-pr-26557-sha-7290a2c2`. Try it out in a new sandbox by running `npx storybook@0.0.0-pr-26557-sha-7290a2c2 sandbox` or in an existing project with `npx storybook@0.0.0-pr-26557-sha-7290a2c2 upgrade`.
<details>
<summary>More information</summary>

| | |
| --- | --- |
| **Published version** | [`0.0.0-pr-26557-sha-7290a2c2`](https://npmjs.com/package/@storybook/cli/v/0.0.0-pr-26557-sha-7290a2c2) |
| **Triggered by** | @JReinhold |
| **Repository** | [storybookjs/storybook](https://github.com/storybookjs/storybook) |
| **Branch** | [`jeppe/fix-react-dom-server-resolution`](https://github.com/storybookjs/storybook/tree/jeppe/fix-react-dom-server-resolution) |
| **Commit** | [`7290a2c2`](https://github.com/storybookjs/storybook/commit/7290a2c2d87e92a8be116a4f96ad0eca3c4f41fc) |
| **Datetime** | Mon Mar 18 15:14:28 UTC 2024 (`1710774868`) |
| **Workflow run** | [8329053228](https://github.com/storybookjs/storybook/actions/runs/8329053228) |

To request a new release of this pull request, mention the `@storybookjs/core` team.

_core team members can create a new canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=26557`_
</details>

### CODE REVIEW

File: code/addons/docs/src/preset.ts [hunk 1]
```diff
@@ -147,6 +147,8 @@ export const viteFinal = async (config: any, options: Options) => {
       resolve: {
         alias: {
           react,
+          // Vite doesn't respect export maps when resolving a path, so we need to do that manually here
+          'react-dom/server': `${reactDom}/server.browser.js`,
```
Comment (valentinpalkovic) [inline code/addons/docs/src/preset.ts:151]: Does this entry point exist in React 16?

Comment (JReinhold) [reply code/addons/docs/src/preset.ts:151]: Yes it does, but I'll make sure to test a React 16 sandbox too.

**Review by valentinpalkovic — APPROVED** [review]
