### PR TITLE
Telemetry: Replace isomorphic-unfetch with node-fetch in telemetry

### LINKED ISSUE #21432: [Bug]:  "ExperimentalWarning: The Fetch API is an experimental feature" shown during storybook commands in node v18
### Describe the bug

We use `isomorphic-unfetch` that will use the actual fetch implementation in node 18.
However, this will cause warnings:

image

We should probably move to node-fetch, or conditionally use isomorphic-unfetch only when the environment is node 19, where the fetch impl. is stable.

### To Reproduce

Start storybook v7 in node 18.

### System

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tmeasday**
Closes #21432

## What I did

Switch `node-fetch` in for telemetry. 

## How to test

1. Run `yarn ts-node event-log-collector` from the scripts directory
2. Run a sandbox.
3. Check it works
4. Add `res.status(503)` to the `server.post('/event-log', ...`
5. Check it retries.

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

File: code/lib/telemetry/src/telemetry.ts [hunk 1]
```diff
@@ -55,7 +55,7 @@ export async function sendTelemetry(
     if (options.immediate) {
       await Promise.all(tasks);
     } else {
-      await request;
+      console.log(await request);
```
Comment (shilman) [inline code/lib/telemetry/src/telemetry.ts:58]:
```suggestion
      await request;
```

**Review by shilman — APPROVED** [review]
