### PR TITLE
CircleCI: Dynamic config setup

### LINKED ISSUE #32936: [Tracking]: Overhaul CI setup
# Problem statement

Our CI setup is in need of optimization to save cost and time.

The current setup has many convergent points, which make the runtime long, and cause failures of a part of the system to stop running the remaining tasks for other parts of the system.

## We've identified multiple key issues we want to address:
- When one sandbox fails, it blocks all following steps
    - Pre-release sandboxes (especially Next.js) frequently break CI
    - Unrelated failures block work in other areas
- High flakiness across all test types
- Chromatic UI test issues
    - Changes often merged without accepting/denying them
    - Chromatic checks are yellow, not red (non-blocking)
- Package benchmarking often shows incorrect baseline comparisons
- Sandbox generation challenges
    - 24-hour generation cycle creates lag in detecting upstream issues
    - Generation process takes 30-40 minutes, nearly hitting GitHub timeout limits
- CI split between GitHub Actions and CircleCI creates confusion

## Here is a list of solutions we want to complete:
- Use CircleCI dynamic config generation to create individual jobs per sandbox
    - Prevents one sandbox failure from blocking others
    - Each sandbox would have its own set of steps (unit tests, stories tests, etc.)
- Implement smart change detection
    - Only run affected sandboxes based on changed files
    - Different rules for core changes vs. framework-specific changes
- Disable NX cache in CI (not bulletproof, causing issues)
- Make Chromatic fail on changes (red instead of yellow)
- Fix package size benchmarking

These tasks will be completed in distinct milestones described below

# Milestones

## M1: Introduce a dynamic CI config step
**Owner: @ndelangen**
**Complete by: 2025-11-7**
PR: https://github.com/storybookjs/storybook/pull/32925
- [ ] Add a `setup` workflow
- [ ] Ensure support for existing labels passed to existing workflows

---

## M2: Generate the `config.generated.yml`
**Owner: `@mention`**
**Complete by: `@date`**
- [ ] Generate the existing workflow config using code
- [ ] Delete `.circleci/src`

---

## M3: Generate single workflow
**Owner: `@mention`**
**Complete by: `@date`**
- [ ]  Based on label, a singular-workflow `config.generated.yml` is created
- [ ] The created workflow runs selected sandboxes' pipelines in parallel
- [ ] Delete code for parallelism

---

## M4: Change detection
**Owner: `@mention`**
**Complete by: `@date`**
- [ ] Determine target branch
- [ ] Automatically detect which sandboxes / tasks to run
- [ ] Generate config matching change
- [ ] Remove labels `ci:*`

---

## M5: Use CircleCI App integration
**Owner: `@mention`**
**Complete by: `@date`**
- [ ] Enable the official app
- [ ] Setup github triggers for label changes
- [ ] Setup github triggers for pushes
- [ ] Setup circleci daily schedule running all sandboxes, even if nothing changed

---

## M6: Move sandbox generation to scheduled CircleCI job
**Owner: `@mention`**
**Complete by: `@date`**
- [ ] Make separate repos for sandboxes
- [ ] Adjust sandbox scripts to clone/download correct repo
- [ ] Run schedule task to re-generate all sandboxes, and commit changes to individual repositories

---

## M7: Windows & special cases
**Owner: `@mention`**
**Complete by: `@date`**
- [ ] Test at least 1 sandbox on Windows
- [ ] Test at least 1 sandbox with yarn pnp
- [ ] Test at least 1 sandbox with npm
- [ ] Test at least 1 sandbox with pnpm

---

## M8: Reporting
**Owner: `@mention`**
**Complete by: `@date`**
- [ ] Ensure size-reporting is concise, and accurate
- [ ] Ensure bundle analyzer links are correct

---

## M9: Re-running compat & SSH
**Owner: `@mention`**
**Complete by: `@date`**
- [ ] Ensure re-running tasks can be done from failed
- [ ] Ensure SSH into runner is possible

---

## M10: Simpler monorepo setup
**Owner: `@mention`**
**Complete by: `@date`**
- [ ] Merge `code` and `scripts` into root
- [ ] Re-evaluate NX usage and upgrade

**========= Everything below this line is strictly nice-to-have =========**

## Related issues that may be resolved by this project
- [ ] issue1
- [ ] issue2

### PR DESCRIPTION
**Pull request by ndelangen**
## What I did

Related: https://github.com/storybookjs/storybook/pull/19476
Tracking: https://github.com/storybookjs/storybook/issues/32936

I'm overhauling the CI config.

In this PR I introduce the `scripts/ci` folder, in which a CircleCI config is dynamically generated.

This dynamic generation allows us to check the repo/PR/branch state and read dynamic config files (such as `sandboxes-templates.ts`) to determine what the optimum CI workflow would look like.

Here's is an overview:
Screenshot 2025-12-29 at 13 50 56

Screenshot 2025-12-29 at 13 51 47

The hope is that in the future, we'll be able to do change detection, and instead of adding `ci:*`-labels to PRs, we automatically only run affected sandboxes.

#### The changes in this PR are covered in the following automated tests:

- [x] stories
- [x] unit tests
- [x] integration tests
- [x] end-to-end tests

#### Manual testing

- [x] We should run this PR with each `ci:*`-label at least once, checking if every runs as expected.

## Summary by CodeRabbit

* **Chores**
  * Replaced many legacy CI workflows with a dynamic CI config generator and centralized CI tooling; removed numerous static CI jobs and an unstable sandbox template.
* **Bug Fixes**
  * Improved CLI logging resilience and added an environment guard to optionally skip Playwright installation.
* **Documentation**
  * Expanded CONTRIBUTING with local development and sandbox-filtering guidance.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: code/core/src/node-logger/logger/logger.ts [hunk 1]
```diff
@@ -166,6 +166,9 @@ type BoxOptions = {
 } & clack.BoxOptions;
 
 export const logBox = (message: string, { title, ...options }: BoxOptions = {}) => {
+  if (process.env.CI) {
+    return;
+  }
```
Comment (ndelangen) [inline code/core/src/node-logger/logger/logger.ts]: TODO: figure out why this was needed

Comment (valentinpalkovic) [reply code/core/src/node-logger/logger/logger.ts]: ☝️

File: code/lib/cli-storybook/src/sandbox-templates.ts [hunk 2]
```diff
@@ -728,19 +729,20 @@ export const baseTemplates = {
...
+  //   // TODO: The community template does not provide standard stories, which is required for e2e tests. Reenable once it does.
+  //   inDevelopment: true,
+  //   expected: {
+  //     framework: 'storybook-framework-qwik',
+  //     renderer: 'storybook-framework-qwik',
+  //     builder: 'storybook-framework-qwik',
+  //   },
+  //   // TODO: The community template does not provide standard stories, which is required for e2e tests.
+  //   skipTasks: ['e2e-tests-dev', 'e2e-tests', 'bench', 'vitest-integration', 'chromatic'],
+  // },
```
Comment (valentinpalkovic) [inline code/lib/cli-storybook/src/sandbox-templates.ts:765]: My latest knowledge is that `inDevelopment` sandboxes are now also running on CI.

What is the workflow to add a new sandbox and could you maybe document it somewhere (if not already documented)?

Something like:
1. Add a new sandbox in `sandbox-templates`
2. set `inDevelopment: true`
3. Make the sandbox work on your branch locally as well as on CI
4. Run `generate-sandboxes` GitHub action (just guessing the name here) to make sure the sandbox is published to `storybookjs/sandboxes`
5. Remove the `inDevelopment: true` flag and as soon as CI passes, merge the PR.

File: code/lib/cli-storybook/src/sandbox-templates.ts [hunk 3]
```diff
@@ -1039,3 +1041,6 @@ export const daily: TemplateKey[] = [
 ];
 
 export const templatesByCadence = { normal, merged, daily };
+export type TemplateType = Pick<Template, 'inDevelopment' | 'skipTasks' | 'typeCheck'>;
+export type AllTemplatesKey = keyof typeof allTemplates;
+export type AllTemplatesType = Record<AllTemplatesKey, TemplateType>;
```
Comment (valentinpalkovic) [inline code/lib/cli-storybook/src/sandbox-templates.ts]: Although not a written-down convention, I prefer to have type declarations at the top of the file. I think we usually define types at the top before function/variable declarations.

File: scripts/build/utils/generate-types.ts [hunk 4]
```diff
@@ -83,7 +83,7 @@ export async function generateTypesFiles(cwd: string, data: BuildEntries) {
           processes.forEach((p) => p.kill());
           processes = [];
           process.exit(dtsProcess.exitCode || 1);
-        } else {
+        } else if(!process.env.CI) {
```
Comment (valentinpalkovic) [inline scripts/build/utils/generate-types.ts:86]: Can you elaborate?

File: scripts/ci/utils/constants.ts [hunk 5]
```diff
@@ -0,0 +1,18 @@
...
+ *
+ * @example C:\Users\circleci\project\code
+ *
+ * @example /tmp/storybook-sandboxes
+ *
+ * @example C:\Users\circleci\storybook-sandboxes
+ *
+ * To ensure the correct paths are used across config generation, we use the following constants.
+ */
+export const ROOT_DIR = '/tmp';
```
Comment (valentinpalkovic) [inline scripts/ci/utils/constants.ts]: Shouldn't we define the roots for linux AND windows in this file and rename `ROOT_DIR` to `LINUX_ROOT_DIR`?

File: scripts/ci/utils/executors.ts [hunk 6]
```diff
@@ -0,0 +1,64 @@
+import { ROOT_DIR, WORKING_DIR } from './constants';
+
+export const executors = {
```
Comment (valentinpalkovic) [inline scripts/ci/utils/executors.ts:3]: Should we be crystal clear that these are `linux` executors, since we are referring to the linux root (ROOT_DIR)?

File: scripts/ci/utils/helpers.ts [hunk 7]
```diff
@@ -0,0 +1,274 @@
...
+};
+
+export const workflow = {
+  restore_linux: () => [
+    //
+    git.checkout(),
+    workspace.attach(),
+    cache.attach(CACHE_KEYS()),
+  ],
+  restore_windows: (at = 'C:\\Users\\circleci') => [
```
Comment (valentinpalkovic) [inline scripts/ci/utils/helpers.ts]: Should we move `C:\\Users\\circleci` as a const to `constants.ts`?

File: scripts/ci/utils/parameters.ts [hunk 8]
```diff
@@ -0,0 +1,19 @@
...
+  },
+  ghPrNumber: {
+    default: '',
+    description: 'The PR number',
+    type: 'string',
+  },
+  workflow: {
+    default: 'skipped',
+    description: 'Which workflow to run',
+    enum: ['normal', 'merged', 'daily', 'skipped', 'docs'] as const,
```
Comment (valentinpalkovic) [inline scripts/ci/utils/parameters.ts:16]: Should we move the workflow array into `constants` and reference it everywhere where needed?

File: scripts/ci/utils/types.ts [hunk 9]
```diff
@@ -0,0 +1,138 @@
...
+   *     shell: string,
+   *     env: Record<string, string>,
+   *   },
+   * }
+   * ```
+   *
+   * @todo Make this more type-strict, maybe with a union type of step objects. See the example
+   *   above.
+   */
+  steps: unknown[];
```
Comment (valentinpalkovic) [inline scripts/ci/utils/types.ts:52]: Let's add a link in the JSDOC description above which points to the CircleCI documentation of steps

File: scripts/ci/code.ts [hunk 10]
```diff
@@ -0,0 +1,347 @@
...
+  },
+  [codeHub]
+);
+
+export const knip = defineJob(
+  'Knip validation',
+  {
+    executor: {
+      name: 'sb_node_22_classic',
+      class: 'xlarge',
```
Comment (valentinpalkovic) [inline scripts/ci/code.ts]: Do the knip and eslint jobs really need the resource class `xlarge`? Can you double-check?

File: scripts/ci/code.ts [hunk 11]
```diff
@@ -0,0 +1,347 @@
...
+  },
+  [build_windows]
+);
+
+export const benchmarkPackages = defineJob(
+  'Benchmark packages',
+  {
+    executor: {
+      name: 'sb_node_22_classic',
+      class: 'xlarge',
```
Comment (valentinpalkovic) [inline scripts/ci/code.ts]: In general, would it make sense to go through all resource-class definitions and double check whether these higher resource classes are really necessary?

File: scripts/ci/init-empty.ts [hunk 12]
```diff
@@ -0,0 +1,154 @@
...
+        shell: 'bash.exe',
+      },
+      steps: [
+        ...workflow.restore_windows(),
+        verdaccio.start(),
+        server.wait([...verdaccio.ports]),
+        {
+          run: {
+            name: 'Storybook init from empty directory (Windows NPM)',
+            working_directory: 'C:\\Users\\circleci',
```
Comment (valentinpalkovic) [inline scripts/ci/init-empty.ts]: Use a const instead for the windows working dir. Also, please check the other places.

File: scripts/ci/main.ts [hunk 13]
```diff
@@ -0,0 +1,146 @@
...
+   *
+   * You do not need to consider the `requires` field, as the `ensureRequiredJobs` function will
+   * handle that for you.
+   *
+   * @example
+   *
+   * ```ts
+   * const filteredTodos = todos.filter((job) => !!job.id.includes('qwik'));
+   * ```
+   */
```
Comment (valentinpalkovic) [inline scripts/ci/main.ts:93]: This inline comment is great! Let's also add something similar to our contributions guidelines, mentioning that for temporary, highly iteratative tasks the filter functionality might be benificial (time-wise and cost-wise). Additionally, some job id's are dynamic (especially the ones for the sandboxes and init scripts). It may help to document how the job id's are evaluated so that it is easy to filter for them

File: scripts/ci/sandboxes.ts [hunk 14]
```diff
@@ -0,0 +1,499 @@
...
+        shell: 'bash.exe',
+      },
+      steps: [
+        ...workflow.restore_windows(),
+        verdaccio.start(),
+        server.wait([...verdaccio.ports]),
+        {
+          run: {
+            name: 'Run Install',
+            working_directory: `C:\\Users\\circleci\\storybook-sandboxes\\${sandbox.path}`,
```
Comment (valentinpalkovic) [inline scripts/ci/sandboxes.ts]: Use `WINDOWS_ROOT_DIR` and `SANDBOX_DIR`

File: scripts/tasks/sandbox-parts.ts [hunk 15]
```diff
@@ -889,22 +889,28 @@ export const extendPreview: Task['run'] = async ({ template, sandboxDir }) => {
...
-  ].join('\n');
-
-  // find last import statement and append sb.mock calls
-  config = config.replace(
-    'import { sb } from "storybook/test";',
-    `import { sb } from 'storybook/test';\n\n${mockBlock}`
-  );
+  const isCoreRenderer =
+    template.expected.renderer.startsWith('@storybook/') &&
+    template.expected.renderer !== '@storybook/server';
```
Comment (valentinpalkovic) [inline scripts/tasks/sandbox-parts.ts]: The mocking feature is usually builder-dependent, and is renderer-agnostic. Even if a builder doesn't support mocking (e.g. rspack), the `sb.mock` calls in the preview don't harm, because the `mock` implementation is a `no-op` function at runtime. Can you elaborate why you were forced to add this check?

File: yarn.lock [hunk 16]
```diff
@@ -10915,12 +10915,12 @@ __metadata:
...
-  version: 2.4.27
-  resolution: "@volar/language-core@npm:2.4.27"
+"@volar/language-core@npm:2.4.23":
+  version: 2.4.23
+  resolution: "@volar/language-core@npm:2.4.23"
   dependencies:
-    "@volar/source-map": "npm:2.4.27"
-  checksum: 10c0/8fe021ecb0654dde1e221bba4d456d681454fa06a4aff16d0b027d5a1b0514be72bf899c6a515d8e9254ffbd468690e296ffb4cae7e63f6a4ec359d5e8a718be
+    "@volar/source-map": "npm:2.4.23"
+  checksum: 10c0/1b8d60c7c0faa29ef5ec46dd2b673227592d0697753767e4df088f7c2d93843828116fe59472bb9d604ba653400be32a538e985730844b1af4f42a7075e62049
```
Comment (valentinpalkovic) [inline yarn.lock]: I think the `yarn.lock` changes can be reverted, since you haven't changed any dependencies

**Review by valentinpalkovic — CHANGES_REQUESTED** [review]
Well done!

I support a dynamic CircleCI configuration because it gives us the flexibility to quickly filter out certain jobs, which will be particularly beneficial once change detection is implemented. Furthermore, it will be easier to evaluate regressions caused by upstream changes to determine whether a PR can be merged or not without disrupting the build status of unaffected sandboxes.

As a follow-up task, we still need to consider a process for how to proceed once a sandbox starts to fail due to an upstream change. However, these process discussions are independent of this PR.

File: scripts/build/utils/generate-types.ts (hunk 4 above)
Comment (ndelangen) [reply scripts/build/utils/generate-types.ts:86]: Yeah, NX is already logging the fact the task is being done.

Error in logs should be easy to access/find.

Currently when something fails, you have to scroll past many success messages, since the logs are long, it can be difficult to spot the errors in them.
Making the logs less noisy, and thus less long, will help in getting to the errors in the logs faster/easier.

File: scripts/ci/code.ts (hunk 10 above)
Comment (ndelangen) [reply scripts/ci/code.ts]: knip, no. 

linting.. debatable.. `eslint` is not particularly fast. Getting the feedback earlier helps with dev flow.

File: scripts/ci/code.ts (hunk 11 above)
Comment (ndelangen) [reply scripts/ci/code.ts]: Absolutely.

File: scripts/ci/utils/parameters.ts (hunk 8 above)
Comment (ndelangen) [reply scripts/ci/utils/parameters.ts:16]: I don't think we should, here's why:

I infer a type from this data struct:
https://github.com/storybookjs/storybook/blob/93c72eafce4dc54039b53ed72266adca3cd14348/scripts/ci/utils/types.ts#L107

This data structure is *exactly* what CircleCI config needs to have to accept parameters via API.
So to me it felt like the source of truth *is* here, in this definition;
and the type (referenced in a few places) is the derived value.

The array value is never used anywhere else.
The enum values ARE, but It's all type-safe, no magic strings, you cannot pass non-existing values:
Screenshot 2026-01-02 at 11 31 22

File: scripts/tasks/sandbox-parts.ts (hunk 15 above)
Comment (ndelangen) [reply scripts/tasks/sandbox-parts.ts]: Yeah, I'm sure you're right.

I copied this technique from here:
https://github.com/storybookjs/storybook/blob/08390fffe98737789722ca56595cfd11f353162e/scripts/tasks/sandbox-parts.ts#L645-L652

And the reason I did so because if we do not, then we're adding references to files that do not exists!

I'd suggest keeping the behavior as-is for now, it does seem to be working.
And the code I pint to above has been as-is for a while.

Comment (ndelangen) [reply scripts/tasks/sandbox-parts.ts]: Perhaps I should change it to `isCoreFramework`?

**Review by valentinpalkovic — APPROVED** [review]

File: scripts/tasks/sandbox-parts.ts (hunk 15 above)
Comment (ndelangen) [reply scripts/tasks/sandbox-parts.ts]: We had a talk about this, and decided that this is the correct way.

`isCoreRenderer` is the correct check, because the files are only copied when this condition is true as well.
And that's because those files are renderer-specific.

File: scripts/ci/utils/helpers.ts [hunk 17]
```diff
@@ -0,0 +1,274 @@
...
+        working_directory: `code`,
+        command: 'yarn local-registry --publish',
+      },
+    };
+  },
+  ports: ['6001', '6002'],
+};
+
+export const workflow = {
+  restore_linux: () => [
```
Comment (JReinhold) [inline scripts/ci/utils/helpers.ts]: let's stick to camel case

```suggestion
  restoreLinux: () => [
```

Do't we have a lint rule for this? or maybe it doesn't target these files for some reason?

File: scripts/ci/utils/helpers.ts [hunk 18]
```diff
@@ -0,0 +1,274 @@
...
+    //
+    git.checkout(),
+    workspace.attach(),
+    cache.attach(CACHE_KEYS()),
+  ],
+  restore_windows: (at = WINDOWS_ROOT_DIR) => [
```
Comment (JReinhold) [inline scripts/ci/utils/helpers.ts]:
```suggestion
  restoreWindows: (at = WINDOWS_ROOT_DIR) => [
```

File: scripts/ci/common-jobs.ts [hunk 19]
```diff
@@ -0,0 +1,347 @@
...
+} from './utils/helpers';
+import { defineHub, defineJob } from './utils/types';
+
+const dirname = import.meta.dirname;
+
+export const build_linux = defineJob('Build (linux)', {
+  executor: {
+    name: 'sb_node_22_classic',
+    class: 'xlarge',
+  },
```
Comment (JReinhold) [inline scripts/ci/common-jobs.ts:28]: could this not be imported from `executors.ts` instead?

File: scripts/ci/code.ts [hunk 20]
```diff
@@ -0,0 +1,347 @@
...
+        command: 'yarn task --task compile --start-from=auto --no-link --debug',
+      },
+    },
+    {
+      run: {
+        name: 'Publish to Verdaccio',
+        working_directory: `code`,
+        command: 'yarn local-registry --publish',
+      },
+    },
```
Comment (JReinhold) [inline scripts/ci/code.ts]: is there any reason jobs like these (compile, publish) are not defined in `helpers` like eg. `git.X`? are they unique?

File: scripts/ci/sandboxes.ts [hunk 21]
```diff
@@ -0,0 +1,500 @@
...
+          ? [
+              {
+                run: {
+                  name: 'Run prepare',
+                  working_directory: `${LINUX_ROOT_DIR}/${SANDBOX_DIR}/${id}`,
+                  command: `yarn prepare`,
+                },
+              },
+            ]
+          : []),
```
Comment (JReinhold) [inline scripts/ci/sandboxes.ts:195]: probably a comment on _why_ here would be great.

File: scripts/ci/common-jobs.ts
Comment (JReinhold) [inline scripts/ci/common-jobs.ts:1]: surely there must be a better name for this file than `code.ts`. What does this file contain? what is the commonality between all of the exported variables here? Is it `common-jobs.ts`?

**Review by JReinhold — APPROVED** [review]
Fantastic work! I really love how you've architected the helpers, great for readibility. I also love that this is a drop-in replacement, keeping all the current jobs and structures that we know, so optimizations and improvements can happen later, separately.

Do you have any benchmarks/comparisons between the new and the old config in terms of speed and cost?

I really only have nit comments. There's a lot of underscores sneaking into variable names here, which seems odd to me. Maybe there's a pattern that I just don't see, but I'd prefer to just stick with camelCase everywhere like we've done for ages.

In the bigger picture, I was really confused about the concept of a "Hub" and a "Todo" in this work, and I spent a lot of time figuring out what it was. Now that I think I understand that they are not "official" concepts but something you came up with, I have a suggestion:

1. Rename "hub" to "noOpJob", because that is just what it is. Alternatively it could be an "emptyJob".
2. Rename "todos" to "jobs". It's all jobs all the way, so that's just simpler to grasp IMO.

File: scripts/ci/code.ts (hunk 20 above)
Comment (ndelangen) [reply scripts/ci/code.ts]: publish I missed, there's a helper for that, I am using it now, good eye!

I didn't make a helper for `yarn task ...` steps, because it felt like the `yarn task...` is already an abstraction, and it since this is usually the key important part of any job, it being abstracted away would have made it less obvious.

When looking at a job definition, I want your eye to land on the most important step of the job, and have the setup and cleanup be secondary.

File: scripts/ci/common-jobs.ts (hunk 19 above)
Comment (ndelangen) [reply scripts/ci/common-jobs.ts:28]: Yes, it could indeed, however:
It's currently type-safe, which felt like "enough" to me, to verify no mistakes are made.

As we discussed today, TS makes no difference between an inline string and an string imported "enum".
So there would be nothing preventing someone from writing the value inline later (it would be auto-suggested to inline the string by TS; so it's an easy thing to get wrong).

File: scripts/ci/common-jobs.ts
Comment (ndelangen) [reply scripts/ci/common-jobs.ts:1]: If you look at the graph on CircleCI, you'll see a group of jobs under a hub called `code`.

I interesting detail is that the graph is alphabetically sorted.

I wanted to present the most information at a glance in the CircleCI graph, so the jobs like `lint`, `typecheck` etc, should be near each other at the top; hence I grouped them in a hub.

I named the hub `code` because, well I needed something that was higher in the alphabet and `code` was descriptive enough; it hints at jobs related to the `./code` directory in our monorepo.

I debated the naming a bit with @ghengeveld last week; but I do not have a personal preference, I'll rename the file and hub to `common-jobs`, as you suggest.

**Comment by ndelangen** [comment]
@JReinhold I measure the differences between the previous daily and the new one.

Due to me moving the windows compile & unit test to CircleCI credit usage increased, also due to running inDevelopment sandboxes also.

I'm measuring again without the windows compile+test, but data lags by ~24 hours.

Previous daily measurement:
https://app.circleci.com/insights/github/storybookjs/storybook/workflows/daily-legacy-comparison/overview?branch=b1d8acd4-8701-4c76-8a87-7ff2320aa95f

New daily measurement:
https://app.circleci.com/insights/github/storybookjs/storybook/workflows/daily-generated-comparison/overview?branch=b1d8acd4-8701-4c76-8a87-7ff2320aa95f

I can see that `build--windows` is really expensive, as are `init-empty-windows`, `react-latest--vite---typescript---build-windows`, `react-latest--vite---typescript---dev-windows` 

The windows jobs cumulative cost `4,304 + 1,012 + 4,750 + 5,199 + 1,088 = 16,353` credits (though that's over 3 runs, I think (it's a bit hard to tell in CircleCI's app interface).

Assuming it is, then running all the things on windows we do now, costs `5451` credits per run, which is 30% of the workflow-run cost.

Running a sandbox on windows (as real as possible) was an explicit goal of the project, 
...though maybe now we know how costly it is, we may want to reconsider.

Here are the raw numbers:
I did 2 `ci:daily` runs on the old config: `14696` & `15150` CI credits consumed per run.
I did 2 `ci:daily` runs on the new config (without windows): `12500` & `12098`CI credits consumed per run.

As mentioned above running all windows things bring to total new workflow to `17451` CI credits consumed per run.

**Review by kasperpeulen — COMMENTED** [review]
## Review: CircleCI Dynamic Config Setup

Thanks for the detailed walkthrough in the video! The architecture is clean and the TypeScript approach is much more maintainable than 50+ YAML files.

### Question: Is all old functionality ported?

I noticed two things that appear to be missing from the new implementation:

#### 1. Discord Notifications

**Old** (`.circleci/src/commands/report-workflow-on-failure.yml`):
```yaml
- discord/status:
    only_for_branches: main,next,next-release,latest-release
    fail_only: true
    failure_message: $(yarn get-report-message << pipeline.parameters.workflow >> << parameters.template >>)
```

**New** (`scripts/ci/utils/helpers.ts:207-224`):
```typescript
reportOnFailure: () => {
  return [
    // ...
    {
      run: {
        name: 'Report failure',
        when: 'on_fail',
        command: 'echo "Workflow failed"',  // ← Just echoes to stdout
      },
    },
  ];
},
```

The Discord orb is still defined in `orbs.ts`, but not used. Is this intentional (deferred to M6: Reporting) or should it be restored?

#### 2. Coverage Job

The old `coverage.yml` job with codecov integration appears to be removed entirely. The tracking issue mentions "Code coverage reporting on PR" under M6 - is this intentionally deferred?

---

If these are intentionally deferred to M6, it might be worth adding a comment in the code or tracking issue to make that clear.

**Review by kasperpeulen — COMMENTED** [review]
deleted from claude

**Review by kasperpeulen — COMMENTED** [review]
I absolutely agree that this PR improves our current setup. The features it adds are valuable - sandboxes running independently so one failure doesn't block others, the ability to filter jobs for debugging, and better visibility in the CircleCI graph.

That said, as you know, I still believe using a dedicated task runner is the right direction long-term. Here's why:

### 1. CI Config Generated from Task Graph
With NX Agents, this entire PR essentially becomes unnecessary - the CI configuration is automatically derived from the task graph. No custom code to generate YAML, no manual job dependencies to maintain. NX Agents dynamically distributes tasks across CI agents at runtime - it automatically determines which tasks can run concurrently and assigns them to available agents to minimize idle time.

(Turborepo doesn't have this level of automation yet - you'd still need to set things up manually.)

### 2. This is a Lot of Custom Code
This PR adds ~1500 lines of custom infrastructure that we need to maintain. With NX Agents, we get the same features (and more) out of the box.

### 3. Change Detection and Remote Caching
Both NX and Turborepo offer built-in change detection and remote caching. We're planning to implement change detection ourselves, but these tools already have it - they know which projects are impacted by a change and only run those tasks. Remote caching means tasks that haven't changed don't re-run, even across different PRs.

### 4. Breaking the Homebrew Pattern
Historically, the team has invested a lot of time in homebrew solutions - our custom `yarn task` command being a prime example. This PR continues that pattern. I would really like to discontinue this trend and instead normalize our repository as much as possible: using standard practices and the best tools available rather than building our own.

### 5. LLM Era Consideration
This is especially important in the age of LLMs. Using well-documented, widely-adopted tools means LLMs have extensive training data to help debug, optimize, and extend configurations. Custom infrastructure is harder for LLMs to assist with since it's unique to our codebase. Normalizing our setup makes it easier for both humans and AI to contribute.

---

This isn't blocking - the PR is a clear improvement and I'm happy to approve. 

However, I think we need a very strong case to continue the remaining milestones if we can get so much for free by using a dedicated tool instead.

**Review by kasperpeulen — APPROVED** [review]
