### PR TITLE
Actions: Fix HandlerFunction type to support async callback props

### LINKED ISSUE #23731: [Bug]: addon-actions action handler not assignable to async callback props
### Describe the bug

When the `action` function is used for an async callback property a type error occurs e.g.

 
image

### To Reproduce

Stackblitz reproduction: https://stackblitz.com/edit/github-u61rhv?file=stories%2FButton.stories.ts

### System

```shell
Environment Info:

  System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.2.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 115.0.5790.110
    Edge: Spartan (44.22621.1992.0), Chromium (115.0.1901.188)
  npmPackages:
    @storybook/addon-essentials: ^7.2.0 => 7.2.0 
    @storybook/addon-interactions: ^7.2.0 => 7.2.0 
    @storybook/addon-links: ^7.2.0 => 7.2.0
    @storybook/blocks: ^7.2.0 => 7.2.0
    @storybook/nextjs: ^7.2.0 => 7.2.0
    @storybook/react: ^7.2.0 => 7.2.0
    @storybook/testing-library: ^0.2.0 => 0.2.0
```

### Additional context

I think its a case of setting the return type for the HandlerFunction here https://github.com/storybookjs/storybook/blob/next/code/addons/actions/src/models/HandlerFunction.ts to `any` (`unknown` or 
`void|Promise<void>` doesnt work)

### PR DESCRIPTION
**Pull request by mixelburg**
Closes #23731

## What I did

Changed the return type of `HandlerFunction` from `void` to `any` so that action handlers can be assigned to async callback props (e.g. `onSubmit: () => Promise<void>`) without causing type errors.

The issue is that `(...args: any[]) => void` is not assignable to `(...args: any[]) => Promise<void>`, but `(...args: any[]) => any` is, since `any` is compatible with all return types.

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

This is a type-only change. Verified that the existing `HandlerFunction` usages in the codebase (e.g. `action()` return type, `ActionsMap`, test stories) remain compatible.

## Summary by CodeRabbit

* **Updates**
  * Handler functions may now return Promise<void> as well as void, enabling async handlers and broader compatibility in composed flows.

* **Tests**
  * Added type-level tests asserting both async and sync handler signatures to improve type safety and guard against regressions.

### CODE REVIEW

File: code/core/src/actions/models/HandlerFunction.ts [hunk 1]
```diff
@@ -1 +1 @@
-export type HandlerFunction = (...args: any[]) => void;
+export type HandlerFunction = (...args: any[]) => any;
```
Comment (Sidnioulz) [inline code/core/src/actions/models/HandlerFunction.ts]: q: Why not apply `void | Promise<void>` instead? This would enable using async functions whilst still communicating to users that no return value will be consumed.

Comment (Sidnioulz) [reply code/core/src/actions/models/HandlerFunction.ts]:
```suggestion
export type HandlerFunction = (...args: any[]) => void | Promise<void>;
```

I'll make the change and see how CI reacts.

**Review by Sidnioulz — APPROVED** [review]
