### PR TITLE
Vite: Add react docgen types

### LINKED ISSUE #20789: [Bug]: `reactDocgen` types missing from `@storybook/react-vite`
### Describe the bug

`@storybook/react-webpack5` has types for `typescript.reactDocgen` as can be seen [here](https://github.com/storybookjs/storybook/blob/next/code/presets/react-webpack/src/types.ts#L23). Similar types (though options should probably come from `@joshwooding/vite-plugin-react-docgen-typescript` and not `@storybook/react-docgen-typescript-plugin`) should be provided for vite as well.

### To Reproduce

This fails:

```js
import { StorybookConfig } from '@storybook/react-vite'

const config: StorybookConfig = {
  typescript: {
    reactDocgen: 'none',
  },
}

export default config;
```

### System

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by IanVS**
Closes #20789

## What I did

Adds types for react docgen options to the react-vite framework

## How to test

Generate a sandbox for react-vite/default-ts, add an option in the main.ts like:

```ts
typescript: {
	reactDocgen: false
}
```

it should not error.

## Checklist

- [x] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [x] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

File: code/frameworks/react-vite/src/types.ts [hunk 1]
```diff
@@ -25,6 +29,19 @@ type StorybookConfigFramework = {
...
+  /**
+   * Sets the type of Docgen when working with React and TypeScript
+   *
+   * @default `'react-docgen-typescript'`
+   */
+  reactDocgen: 'react-docgen-typescript' | 'react-docgen' | false;
+  /**
+   * Configures `@joshwooding/vite-plugin-react-docgen-typescript`
+   */
+  reactDocgenTypescriptOptions: Parameters<typeof docgenTypescript>;
```
Comment (shilman) [inline code/frameworks/react-vite/src/types.ts:42]: Should this be `Parameters<typeof docgenTypescript>[0]`? I think parameters returns an array

**Review by shilman — COMMENTED** [review]
Thanks @IanVS ! Was in the process of submitting my own PR for this but you beat me to it

**Review by shilman — APPROVED** [review]

**Comment by D1no** [comment]
@shilman Since you guys seem to work on this, updated the following ticket reproduction to `storybook@7.0.0-beta.62`

[#21399](https://github.com/storybookjs/storybook/issues/21399) [Bug]: No JSDoc generation when story outside root or symlinked (MonoRepo Blocker) `ts` + `vite` + `storybook@7.0.0-beta.62`

> https://github.com/D1no/reproduction-storybook-symlinks-pnpm
>
> The same component is included as (1) local copy inside `stories/`, (2) as reference in `.storybook/main.ts` and as a (3) symbolic link into `stories/`.
> 
> ✅ All three types render successfully in storybook.
> 
> ❌ Only variant (1) has JSDoc converted to story docs (!)
> 
> Exact same component and story, but as you see = different location = no JSDocGen.
> storybook_no_jsdocgen

**Comment by IanVS** [comment]
@D1no that seems unrelated to this PR.  Maybe you're thinking of something else?

**Comment by D1no** [comment]
@IanVS Maybe. The work on vite typescript docgen seems to be pretty fragmented. Have no insights 🤷🏻‍♂️ overview. If unrelated, ignore.
