### PR TITLE
Core: StorybookConfig `stories`-field support type async function

### LINKED ISSUE #21524: [Bug]: StoriesEntry type does not allow for custom implementation with async function
### Describe the bug

In the [storybook docs](https://storybook.js.org/docs/react/configure/overview#with-a-custom-implementation), there is an example where you can pass in an async function to `stories` to implement custom logic for loading stories. This works as expected, but if you are using typescript, it gives the error `Type '() => Promise<string[]>' is not assignable to type 'StoriesEntry[]'`.

### To Reproduce

This config will produce the typescript error, although it is a valid way to construct a `stories` configuration, according to the docs.

```ts
import type { StorybookConfig } from '@storybook/react-webpack5';

const stories = Promise.resolve(['../src/**/*.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'])
const config: StorybookConfig = {
  stories: async () => [...await stories],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
  ],
  framework: {
    name: '@storybook/react-webpack5',
    options: {},
  },
  docs: {
    autodocs: 'tag',
  },
};
export default config;
```

### System

```shell
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.2/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 109.0
    Safari: 16.3
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.64 => 7.0.0-rc.0
    @storybook/addon-interactions: ^7.0.0-beta.64 => 7.0.0-rc.0
    @storybook/addon-links: ^7.0.0-beta.64 => 7.0.0-rc.0
    @storybook/blocks: ^7.0.0-beta.64 => 7.0.0-rc.0
    @storybook/react: ^7.0.0-beta.64 => 7.0.0-rc.0
    @storybook/react-webpack5: ^7.0.0-beta.64 => 7.0.0-rc.0
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
```

### Additional context

I am willing to submit a fix to the `StoriesEntry` type for this.

### PR DESCRIPTION
**Pull request by imccausl**
Closes #21524 

## What I did

Modifies to the StorybookConfig['stories'] type to include a function that returns a Promise that resolves to `StoriesEntry[]`. This should cover the custom implementation case. Since this logic is already supported where presets are loaded/resolved and is already documented, I did not make changes to documentation or add tests. 

## How to test

1. modify `main.ts` in `ui/.storybook` so that the `stories` key in the config has an async function that resolves a promise like this: 

```
const asyncStories = Promise.resolve(allStories)
const config: StorybookConfig = {
     stories: async () => [... (await asyncStories)],
     // ...rest of the config
```

2. After this modification you should not see a typescript error on the stories key regardless of how you configure stories (async func or as a `StoriesEntry` array.
3. run yarn start to run the storybook dev server
4. all stories should load as expected.

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [x] Make sure to add/update documentation regarding your changes (updated docstring)
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

File: code/lib/types/src/modules/core-common.ts [hunk 1]
```diff
@@ -330,9 +330,9 @@ export interface StorybookConfig {
   /**
    * Tells Storybook where to find stories.
    *
-   * @example `['./src/*.stories.@(j|t)sx?']`
+   * @example `['./src/*.stories.@(j|t)sx?']` or `async () => [...(await myCustomStoriesEntryBuilderFunc())]`
    */
-  stories: StoriesEntry[];
+  stories: StoriesEntry[] | ((list?: StoriesEntry[]) => Promise<StoriesEntry[]>);
```
Comment (imccausl) [inline code/lib/types/src/modules/core-common.ts:335]: I honestly don't know how `list` works here. In my testing it comes back `undefined` but I added it because that is how it was documented. Also happy to remove it/update the docs if it is not a thing that works.

**Comment by ndelangen** [comment]
@shilman I think we need to discuss this...

Perhaps we decide after GA?

This PR seems correct to me..
- we have documentation saying it should be so
- we have implementation saying it should be so

Yet our types say not.

We kinda want to have this just be an array, because this value can be modified by codemods (maybe?), and for those to work, we want it to be a simple value.

But considering the above, I think we should merge this as-is, make the types match the documentation & implementation, then figure out how to do better config in the future.
I suspect we'll just have to make codemods smarter/better to cope with this.
