### PR TITLE
Ember: Fix @storybook/ember

### LINKED ISSUE #20653: [Bug]: Fresh install Storybook with Ember framework produces a ModuleNotFoundError
### Describe the bug

Hello 👋 

First of all, thank you for all the great work you do for the community 🙏 

Today, I tried a fresh install of storybook for ember framework using the following guide : https://storybook.js.org/docs/ember/get-started/install 

At the step `npm run storybook` it produces this error : 
```
ModuleNotFoundError: Module not found: Error: Can't resolve '@ember/component' in '/Users/myuser/Documents/workspace/ember-quickstart/node_modules/@storybook/ember/dist/esm/client/preview'
    at /Users/myuser/Documents/workspace/ember-quickstart/node_modules/webpack/lib/Compilation.js:2016:28
    at /Users/myuser/Documents/workspace/ember-quickstart/node_modules/webpack/lib/NormalModuleFactory.js:798:13
    at eval (eval at create (/Users/myuser/Documents/workspace/ember-quickstart/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/myuser/Documents/workspace/ember-quickstart/node_modules/webpack/lib/NormalModuleFactory.js:270:22
    at eval (eval at create (/Users/myuser/Documents/workspace/ember-quickstart/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/myuser/Documents/workspace/ember-quickstart/node_modules/webpack/lib/NormalModuleFactory.js:434:22
    at /Users/myuser/Documents/workspace/ember-quickstart/node_modules/webpack/lib/NormalModuleFactory.js:116:11
    at /Users/myuser/Documents/workspace/ember-quickstart/node_modules/webpack/lib/NormalModuleFactory.js:670:25
    at /Users/myuser/Documents/workspace/ember-quickstart/node_modules/webpack/lib/NormalModuleFactory.js:855:8
    at /Users/myuser/Documents/workspace/ember-quickstart/node_modules/webpack/lib/NormalModuleFactory.js:975:5
    at /Users/myuser/Documents/workspace/ember-quickstart/node_modules/neo-async/async.js:6883:13
    at /Users/myuser/Documents/workspace/ember-quickstart/node_modules/webpack/lib/NormalModuleFactory.js:958:45
    at finishWithoutResolve (/Users/myuser/Documents/workspace/ember-quickstart/node_modules/enhanced-resolve/lib/Resolver.js:312:11)
    at /Users/myuser/Documents/workspace/ember-quickstart/node_modules/enhanced-resolve/lib/Resolver.js:386:15
    at /Users/myuser/Documents/workspace/ember-quickstart/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/myuser/Documents/workspace/ember-quickstart/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/myuser/Documents/workspace/ember-quickstart/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/myuser/Documents/workspace/ember-quickstart/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/myuser/Documents/workspace/ember-quickstart/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:87:43
    at /Users/myuser/Documents/workspace/ember-quickstart/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/myuser/Documents/workspace/ember-quickstart/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/myuser/Documents/workspace/ember-quickstart/node_modules/enhanced-resolve/lib/forEachBail.js:16:12
    at /Users/myuser/Documents/workspace/ember-quickstart/node_modules/enhanced-resolve/lib/AliasPlugin.js:125:14
    at next (/Users/myuser/Documents/workspace/ember-quickstart/node_modules/enhanced-resolve/lib/forEachBail.js:14:3)
    at forEachBail (/Users/myuser/Documents/workspace/ember-quickstart/node_modules/enhanced-resolve/lib/forEachBail.js:24:9)
    at /Users/myuser/Documents/workspace/ember-quickstart/node_modules/enhanced-resolve/lib/AliasPlugin.js:51:5
    at _next0 (eval at create (/Users/myuser/Documents/workspace/ember-quickstart/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:1)
    at eval (eval at create (/Users/myuser/Documents/workspace/ember-quickstart/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
    at /Users/myuser/Documents/workspace/ember-quickstart/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/myuser/Documents/workspace/ember-quickstart/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/myuser/Documents/workspace/ember-quickstart/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/myuser/Documents/workspace/ember-quickstart/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/myuser/Documents/workspace/ember-quickstart/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/myuser/Documents/workspace/ember-quickstart/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/myuser/Documents/workspace/ember-quickstart/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:87:43
    at /Users/myuser/Documents/workspace/ember-quickstart/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/myuser/Documents/workspace/ember-quickstart/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/myuser/Documents/workspace/ember-quickstart/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/myuser/Documents/workspace/ember-quickstart/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/myuser/Documents/workspace/ember-quickstart/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:41:15
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
resolve '@ember/component' in '/Users/myuser/Documents/workspace/ember-quickstart/node_modules/@storybook/ember/dist/esm/client/preview'
  Parsed request is a module
  using description file: /Users/myuser/Documents/workspace/ember-quickstart/node_modules/@storybook/ember/package.json (relative path: ./dist/esm/client/preview)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/myuser/Documents/workspace/ember-quickstart/node_modules/@storybook/ember/dist/esm/client/preview/node_modules doesn't exist or is not a directory
      /Users/myuser/Documents/workspace/ember-quickstart/node_modules/@storybook/ember/dist/esm/client/node_modules doesn't exist or is not a directory
      /Users/myuser/Documents/workspace/ember-quickstart/node_modules/@storybook/ember/dist/esm/node_modules doesn't exist or is not a directory
      /Users/myuser/Documents/workspace/ember-quickstart/node_modules/@storybook/ember/dist/node_modules doesn't exist or is not a directory
      looking for modules in /Users/myuser/Documents/workspace/ember-quickstart/node_modules/@storybook/ember/node_modules
        single file module
          using description file: /Users/myuser/Documents/workspace/ember-quickstart/node_modules/@storybook/ember/package.json (relative path: ./node_modules/@ember/component)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/myuser/Documents/workspace/ember-quickstart/node_modules/@storybook/ember/node_modules/@ember/component doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /Users/myuser/Documents/workspace/ember-quickstart/node_modules/@storybook/ember/node_modules/@ember/component.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/myuser/Documents/workspace/ember-quickstart/node_modules/@storybook/ember/node_modules/@ember/component.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/myuser/Documents/workspace/ember-quickstart/node_modules/@storybook/ember/node_modules/@ember/component.jsx doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/myuser/Documents/workspace/ember-quickstart/node_modules/@storybook/ember/node_modules/@ember/component.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/myuser/Documents/workspace/ember-quickstart/node_modules/@storybook/ember/node_modules/@ember/component.tsx doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /Users/myuser/Documents/workspace/ember-quickstart/node_modules/@storybook/ember/node_modules/@ember/component.json doesn't exist
            .cjs
              Field 'browser' doesn't contain a valid alias configuration
              /Users/myuser/Documents/workspace/ember-quickstart/node_modules/@storybook/ember/node_modules/@ember/component.cjs doesn't exist
        /Users/myuser/Documents/workspace/ember-quickstart/node_modules/@storybook/ember/node_modules/@ember/component doesn't exist
      /Users/myuser/Documents/workspace/ember-quickstart/node_modules/@storybook/node_modules doesn't exist or is not a directory
      /Users/myuser/Documents/workspace/ember-quickstart/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /Users/myuser/Documents/workspace/ember-quickstart/node_modules
        single file module
          using description file: /Users/myuser/Documents/workspace/ember-quickstart/package.json (relative path: ./node_modules/@ember/component)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/myuser/Documents/workspace/ember-quickstart/node_modules/@ember/component doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /Users/myuser/Documents/workspace/ember-quickstart/node_modules/@ember/component.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/myuser/Documents/workspace/ember-quickstart/node_modules/@ember/component.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/myuser/Documents/workspace/ember-quickstart/node_modules/@ember/component.jsx doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/myuser/Documents/workspace/ember-quickstart/node_modules/@ember/component.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/myuser/Documents/workspace/ember-quickstart/node_modules/@ember/component.tsx doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /Users/myuser/Documents/workspace/ember-quickstart/node_modules/@ember/component.json doesn't exist
            .cjs
              Field 'browser' doesn't contain a valid alias configuration
              /Users/myuser/Documents/workspace/ember-quickstart/node_modules/@ember/component.cjs doesn't exist
        /Users/myuser/Documents/workspace/ember-quickstart/node_modules/@ember/component doesn't exist
      /Users/myuser/Documents/workspace/node_modules doesn't exist or is not a directory
      /Users/myuser/Documents/node_modules doesn't exist or is not a directory
      /Users/myuser/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
```

### To Reproduce

```shell
I can't create a "reproduction" using `npx sb@next sandbox` because my issue occurs during installation. Here is what I did:

- Use node 16 (which is still supported see [here](https://github.com/storybookjs/storybook/blob/next/code/frameworks/ember/package.json#L56))

nvm use 16
```
- Install latest version of Ember CLI (v4.9.2)
```
npm install -g ember-cli
```
- Create a fresh app Ember
```
ember new ember-quickstart --lang fr
```
- Check Ember app works fine
```
cd ember-quickstart
npm start
```
- Install storybook for Ember
```
npx storybook init
ember install @storybook/ember-cli-storybook
```
- Run storybook (it is when the error occurs)
```
npm run storybook
```
```


### System

```shell
Environment Info:

  System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.13.2 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
    Firefox: 108.0.2
    Safari: 15.2
  npmPackages:
    @storybook/addon-actions: ^6.5.15 => 6.5.15
    @storybook/addon-essentials: ^6.5.15 => 6.5.15
    @storybook/addon-links: ^6.5.15 => 6.5.15
    @storybook/builder-webpack5: ^6.5.15 => 6.5.15
    @storybook/ember: ^6.5.15 => 6.5.15
    @storybook/ember-cli-storybook: ^0.6.0 => 0.6.0
    @storybook/manager-webpack5: ^6.5.15 => 6.5.15
```

### Additional context

I also tried to bootstrap an Ember Addon rather than an Ember App. It produces the same error.

### PR DESCRIPTION
**Pull request by francois2metz**
Closes #20653

## What I did

This PR fixes the ember addon on the latest 7.0 release. It was also broken on the 6.0.0 release since https://github.com/storybookjs/storybook/pull/17843.
The code has been updated to install ember with the webpack builder and the patch #17843 has been reverted.
To make thinks easier to test, I added two sandbox templates for ember 3 and ember 4.

## How to test

Well, that's the fun part

### Ember 3

1. `yarn task --task dev --template ember/3-js --start-from=install`
1. Go to `sandbox/ember-3-js`
1. Edit the package.json to update `ember-auto-import` to `^2.0.0`.
1. Edit the package.json to update `ember-qunit` to `^6.0.0`.
1. Run `yarn`
1. Run `yarn add @storybook/ember-cli-storybook`
1. Run `yarn build && yarn storybook`
1. Access the stories and see that the preview is working \o/

### Ember 4

1. `yarn task --task dev --template ember/default-js --start-from=install`
1. Access the stories and see that the preview is working \o/

## Checklist

- [X] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [X] Make sure to add/update documentation regarding your changes
- [X] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### 🦋 Canary release

This pull request has been released as version [`0.0.0-pr-23435-sha-bd98198e`](https://npmjs.com/package/@storybook/cli/v/0.0.0-pr-23435-sha-bd98198e). Install it by pinning all your Storybook dependencies to that version.
<details>
<summary>More information</summary>

| | |
| --- | --- |
| **Published version** | [`0.0.0-pr-23435-sha-bd98198e`](https://npmjs.com/package/@storybook/cli/v/0.0.0-pr-23435-sha-bd98198e) |
| **Triggered by** | @shilman |
| **Repository** | [1024pix/storybook](https://github.com/1024pix/storybook) |
| **Branch** | [`fix-ember-3.28`](https://github.com/1024pix/storybook/tree/fix-ember-3.28) |
| **Commit** | [`bd98198e`](https://github.com/1024pix/storybook/commit/bd98198ef7f0c2addbca5ccb447027be6735338a) |
| **Datetime** | Sun Aug 20 15:21:51 UTC 2023 (`1692544911`) |
| **Workflow run** | [5918186521](https://github.com/storybookjs/storybook/actions/runs/5918186521) |

To request a new release of this pull request, mention the `@storybookjs/core` team.

_core team members can create a new canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=23435`_
</details>

### CODE REVIEW

**Comment by francois2metz** [comment]
With https://github.com/storybookjs/ember-cli-storybook/pull/183, I updated the sandbox template to ember 4.12 and it worked.

**Comment by esbanarango** [comment]
@francois2metz Thank you for putting the effort here 🙏 . Looking forward for this PR to be merged 👍

**Comment by sebasjimenez10** [comment]
Small bump to get this merged soon! 🙏 Thanks for contributing @francois2metz !

**Comment by francois2metz** [comment]
Hi @sebasjimenez10, @esbanarango and thanks! Could you test to see if it's working for you?

**Comment by yannbertrand** [comment]
I did try locally from a fresh storybook clone with Ember4.

I followed the steps described in the description. A few notes:
- I checkout this PR with GitHub's `gh`.
- When launching the first command `yarn task --task dev --template ember/default-js --start-from=install`, Storybook tries to launch itself in dev mode after the `sandbox` step (no error until `dev`). I just ignored the error and `ctrl+c`.

```ERR! Error: Failed to load static files, no such directory: /Users/yannbertrand/Developer/storybook/sandbox/ember-default-js/dist
ERR! Make sure this directory exists, or omit the -s (--static-dir) option.
ERR!     at parseStaticDir (/Users/yannbertrand/Developer/storybook/sandbox/ember-default-js/node_modules/@storybook/core-server/dist/presets/common-preset.js:6021:11)
```

- Then `yarn add @storybook/ember-cli-storybook` gives an error because I don't have the local npm registry. I ignore it as well and comment the `npmRegistryServer` config as explained above.

```
➤ YN0027: @storybook/ember-cli-storybook@unknown can't be resolved to a satisfying range
➤ YN0001: RequestError: connect ECONNREFUSED ::1:6001
    at ClientRequest.<anonymous> (/Users/yannbertrand/Developer/storybook/sandbox/ember-default-js/.yarn/releases/yarn-3.6.1.cjs:195:14340)
```

- I copy/paste the change in `node_modules/@storybook/ember-cli-storybook/lib/util.js`.
- `yarn build` works fine.
- Then `yarn storybook` gives these errors in the console.

```
ModuleNotFoundError: Module not found: Error: Can't resolve './stories/components' in '/Users/yannbertrand/Developer/storybook/sandbox/ember-default-js'
```

```
 using description file: /Users/yannbertrand/Developer/storybook/sandbox/ember-default-js/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /Users/yannbertrand/Developer/storybook/sandbox/ember-default-js/package.json (relative path: ./stories/components)
```

- Storybook launches on port 6006 as you can see on the following screenshots, but there is some errors. There is probably some deprecated stuff on Storybook's template config.

image
image
image

**Comment by yannbertrand** [comment]
I retried from a fresh clone, using Node16 and got the same results.

**Comment by ndelangen** [comment]
The code changes relating to the core & sandboxes all look 👍 to me. I can't really say anything meaningful about the ember changes.

**Comment by yannbertrand** [comment]
We actually got it working on ui.pix.fr using https://github.com/1024pix/pix-ui/blob/928360355e9b4a63a48a42606373af66d01208b8/package.json#L62 :)

File: code/lib/cli/src/sandbox-templates.ts [hunk 1]
```diff
@@ -432,6 +432,26 @@ const baseTemplates = {
...
+  'ember/default-js': {
+    name: 'Create Ember 4 app (Javascript)',
+    script: 'npx --package ember-cli@4.12.1 ember new {{beforeDir}}',
+    inDevelopment: true,
+    expected: {
+      framework: '@storybook/ember',
+      renderer: '@storybook/ember',
+      builder: '@storybook/builder-webpack5',
+    },
+  },
```
Comment (ndelangen) [inline code/lib/cli/src/sandbox-templates.ts:454]: We might need to change the CircleCI config because of the changed number of sandboxes.
And also create chromatic projects and add the project-tokens to the CI environment variables.

File: code/lib/core-common/src/index.ts [hunk 2]
```diff
@@ -5,7 +5,6 @@ export * from './presets';
 export * from './utils/cache';
 export * from './utils/check-addon-order';
 export * from './utils/envs';
-export * from './utils/findDistEsm';
```
Comment (ndelangen) [inline code/lib/core-common/src/index.ts:8]: If the file is no longer imported/exported, can it be removed?
Or is it used anywhere else?

Comment (francois2metz) [reply code/lib/core-common/src/index.ts:8]: I did not find any use in the repository, so it has been moved to `code/frameworks/ember/src/util.ts`

Comment (ndelangen) [reply code/lib/core-common/src/index.ts:8]: Ah, ok great, the file just moved. 👍

File: code/lib/cli/src/sandbox-templates.ts (hunk 1 above)
Comment (francois2metz) [reply code/lib/cli/src/sandbox-templates.ts:454]: Generating a working sandbox require manual intervention (to install ember-cli-storybook mainly). How can I do that?

Comment (ndelangen) [reply code/lib/cli/src/sandbox-templates.ts:454]: @yannbf Are these newly added templates not running yet due to the inDevelopment boolean?
I forgot how this works, can you help remind me.
At which point do we need to do the above? (upping the parallelism in CI and create the env-variables/projects to get chromatic on the templates working)

Comment (francois2metz) [reply code/lib/cli/src/sandbox-templates.ts:454]: They must be added in the exported `normal` const in `sandbox-templates.ts`: https://github.com/storybookjs/storybook/blob/e59d2c95ce8a96569e9bc2033e5e29f7e8c7fe2b/code/lib/cli/src/sandbox-templates.ts#L537

Comment (ndelangen) [reply code/lib/cli/src/sandbox-templates.ts:454]: > Generating a working sandbox require manual intervention (to install ember-cli-storybook mainly). How can I do that?

What sort of manual intervention is needed? 
Should it be scripted into the `init` command?
Should it be scripted in the `script` of the template?
https://github.com/storybookjs/storybook/blob/c1b4e2ef5d7662ec5abb08df316b45a4b0f416e0/code/lib/cli/src/sandbox-templates.ts#L99-L100

Comment (francois2metz) [reply code/lib/cli/src/sandbox-templates.ts:454]: `[ember-cli-storybook](https://github.com/storybookjs/ember-cli-storybook)` need to to installed and patched with https://github.com/storybookjs/ember-cli-storybook/pull/183.

**Comment by shilman** [comment]
@francois2metz Thanks for your patience on this -- I've been on vacation for the past ten days. @ndelangen thanks so much for jumping in here and helping move this forward.

Here's what I'm thinking needs to happen:
1. We merge and release https://github.com/storybookjs/ember-cli-storybook/pull/183 if @gossi @dbendaou are OK with it
2. We release a canary version of this PR and interested parties can test it out
3. We get the CI tests working, merge, and release this properly with the next release

WDYT?

**Comment by francois2metz** [comment]
@shilman Looks good

**Review by gossi — APPROVED** [review]
Fantastic work @francois2metz 👏 

I approved both PRs in terms of ember's related code. From my side, let's continue with @shilman's plan 👍

**Comment by shilman** [comment]
Sorry for the lag on this one. I've released https://github.com/storybookjs/ember-cli-storybook/releases/tag/0.6.1 and it looks like somebody else has published a canary here https://www.npmjs.com/package/@storybook/cli/v/0.0.0-pr-23435-sha-7496d4ba

@francois2metz @gossi @dbendaou and anybody else who's interested, can you please test out the new releases together and verify that they work in your projects as expected? Once I get some confirmation, I'll merge and release.

**Comment by francois2metz** [comment]
I'm going to test the new release and use in the template to have an e2e working test in the CI.

**Comment by shilman** [comment]
@francois2metz @gossi does the canary release work well in a standalone project?

**Comment by gossi** [comment]
Oups, I am no admin and cannot trigger this, which is fine, but I also saw the PR version on npm _was_ updated.

I did a testrun:

```
❯ ember -v
ember-cli: 5.2.0
node: 18.16.0
os: darwin x64
```

# Setup

```
> EMBER_CLI_PNPM=true ember new ember-sb7 -sg -sn --pnpm --typescript
> cd ember-sb7/
> pnpm add -D @storybook/ember-cli-storybook @storybook/cli@0.0.0-pr-23435-sha-7496d4ba
> pnpm exec sb init
[manually updated @storybook/* versions to PR version in package.json)
> pnpm i
```

# Fixes

When started, I faced some errors based on the auto-generated code, which I fixed as:

```diff
// .storybook/main.ts
- import type { StorybookConfig } from "@storybook/ember";

- const config: StorybookConfig = {
+ const config = {
```

```diff
// .storybook/preview.ts
- import type { Preview } from "@storybook/ember";

- const preview: Preview = {
+ const preview = {
```

and I updated `stories/Button.stories.js` to this, to update the stories with modern ember (it went a bit antiquated):

```js
import { hbs } from 'ember-cli-htmlbars';
import { action } from '@storybook/addon-actions';
import { linkTo } from '@storybook/addon-links';

// More on how to set up stories at: https://storybook.js.org/docs/ember/writing-stories/introduction
export default {
  title: 'Example/Button',
  render: (args) => ({
    template: hbs`<button {{on "click" this.onClick}}>{{this.label}}</button>`,
    context: args,
  }),
  argTypes: {
    label: { control: 'text' },
  },
  // This component will have an automatically generated Autodocs entry: https://storybook.js.org/docs/react/writing-docs/autodocs
  tags: ['autodocs'],
};

// More on writing stories with args: https://storybook.js.org/docs/ember/writing-stories/args
export const Text = {
  args: {
    label: 'Button',
    onClick: action('onClick'),
  },
};

export const Emoji = {
  args: {
    label: '😀 😎 👍 💯',
    onClick: action('onClick'),
  },
};

export const TextWithAction = {
  render: () => ({
    template: hbs`
    <button {{on "click" this.onClick}}>
      Trigger Action
    </button>
  `,
    context: {
      onClick: () => action('This was clicked')(),
    },
  }),
  name: 'With an action',
  parameters: {
    notes: 'My notes on a button with emojis',
  },
};

export const ButtonWithLinkToAnotherStory = {
  render: () => ({
    template: hbs`
    <button {{on "click" this.onClick}}>
      Go to Welcome Story
    </button>
  `,
    context: {
      onClick: linkTo('example-button--docs'),
    },
  }),
  name: 'button with link to another story',
};
```

# Testing

Starting the test run, I used two processes in parallel:

```
1) ember s
2) pnpm storybook
```

I tried it with both v4 (`4.12.3`) and v5 (`5.2.0`) major ember versions. Here are the results:

<table>
<tr>
 <th>Ember Versions
 <th>Stories
 <th>Docs
<tr>
 <td>v4
 <td>:white_check_mark:
 <td>:x:  
<tr>
 <td>v5
 <td>:white_check_mark:
 <td>:x:
</table>

As a bonus, I tried `emberoider` (ember's new build system), but that wasn't ready yet for it, but its ok.

# Result

First of all, fantastic work @francois2metz - it enables SB7 for ember. I think that is an improvment, from not working at all to make stories work vor v4 and v5 👍 

Making docs mode work should be a future PR.

The change I see would needed as part of this PR, that the auto-generated code from running `sb init` must lead to a working environment. As part of this:

- The updated `stories/Button.stories.js` (you can use mine directly from this PR)
- The generated `.storybook/main.ts` and `.storybook/preview.ts` importing non-existent types. I would prefer to have them and being exported from `@storybook/ember` 👍 

Thanks a lot for all your work 🥳

**Comment by shilman** [comment]
@francois2metz @gossi FWIW I've released an updated canary, linked in the PR description

**Comment by villander** [comment]
@gossi could you please merge and release it? My team is blocked to upgrade to latest embroider version because of it

**Comment by francois2metz** [comment]
> @francois2metz @gossi FWIW I've released an updated canary, linked in the PR description

i'll try to test it tomorrow.

**Comment by francois2metz** [comment]
@shilman I tried to run `npx storybook@0.0.0-pr-23435-sha-bd98198e init` on a fresh ember app. It fails as it tried to install `@storybook/ember@7.3.2`. How I'm supposed to test canary releases ?

**Comment by gossi** [comment]
Check `Setup` in my test log: https://github.com/storybookjs/storybook/pull/23435#issuecomment-1684932154

**Comment by shilman** [comment]
@francois2metz Yeah we plan to fix that in a future version of the CLI. For now as per @gossi 's comment you just need to update the versions by hand in your package.json. cc @JReinhold

**Comment by gossi** [comment]
I added a PR to your PR (PR-ception ?!): 1024pix/storybook#1

That should fix at least the story being generated + the config type. @francois2metz please check my PR, accept if you are happy. Make modifications if you feel needed, then folks can trigger another release and once this is good except the one problem. We can merge.




The remaining problem is:

```diff
// .storybook/preview.ts
- import type { Preview } from "@storybook/ember";

- const preview: Preview = {
+ const preview = {
```

that import is generated for all TS frameworks, but only Angular is providing that import, all other frameworks are broken here?

@shilman can you let us know what the plan is with the generated `import type { Preview } from "@storybook/ember";` ? How do we can solve this for ember in a follow-up PR?

**Comment by mattstrayer** [comment]
Any chance this will make it into the next minor version?

**Comment by ndelangen** [comment]
@shilman I think we can slot this into 7.5.0 WDYT?

**Comment by ndelangen** [comment]
@francois2metz I tried pushing to your fork's branch, but github won't let me.
Can you enable this on your side?

I opened this PR unto your branch, to not lose my work:
https://github.com/1024pix/storybook/pull/2

**Comment by francois2metz** [comment]
@ndelangen I can rebase myself if you want.

**Comment by ndelangen** [comment]
Sure, whatever works for you 👍

**Comment by mattstrayer** [comment]
Hello! Thank you all again for your hard work here. Is there anything I can do to help get this over the finish line and merged in for the next storybook release? 

Thanks!

**Comment by shilman** [comment]
@mattstrayer have you tried out the canary release above? does it work for you?

**Comment by mattstrayer** [comment]
@shilman Yeah we've been using it for weeks now, not issues from our side.

**Comment by shilman** [comment]
@mattstrayer that's great news! i guess we just need to figure out how to get this PR green so we can merge & release. @francois2metz is that something you need help with?

**Comment by gossi** [comment]
yeah, I'm approving all time but when I do, it is already red for some other unrelated reason. Not very helpful to continue playing this game.

@shilman any way we can continue this? PR is a massive improvement and enables sb7 for ember - is there a fastlane merge possible?

**Comment by kasperpeulen** [comment]
I reverted the `yarn.lock` changes that fixed it for my locally @gossi @drouhard

**Comment by kasperpeulen** [comment]
Oh I have no access to push the changes.

**Comment by shilman** [comment]
@francois2metz I got CI green in https://github.com/storybookjs/storybook/pull/25162. If you can update this PR with those changes, we should be able to get this one green

**Comment by francois2metz** [comment]
I fixed the template names and it worked. Nothing that I can understand.

**Comment by gossi** [comment]
It's greeeeeeeeeeeeeeeeeeeen 🥳 🎉

**Review by shilman — APPROVED** [review]
Great job @francois2metz !! Thanks so much for bearing with us on this one 😅

**Comment by chasegiunta** [comment]
@shilman is it not possible to get this backported to 7.x? I'm assuming a stable 8 release is still quite a while away.

**Comment by gossi** [comment]
Yeah, a backport to v7 sounds nice and we can have a _stable_ sb@v7 with an _stable_ ember version.

But also:

- This only affects ember people
- We can use this with an alpha of sb, as long as this works.
- We can even upgrade the alpha version of sb, as long as this works.
- If it stops working, we can lock the alpha version of sb@8 that was the last one working and try every now and then to upgrade
- sb@7 never worked for ember, so we can make skip this (like php6 😂)

I think it makes more sense to improve the DX for working with sb@8 at ember and aim at for a good experience once that hits a final release (given there is low capa from ember side, this might be converging on either schedules).

That is a very sober view on the practical side of things, which I see very realistic - I'm still with you on how that looks and rest assured my perfectionistic artistic sense is hammering this message into me, too 😬

**Comment by shilman** [comment]
@chasegiunta we typically only patch very small, non-disruptive changes and I would say this doesn't qualify. Fortunately, we're shooting for an 8.0 release at [end of Feb](https://github.com/storybookjs/storybook/discussions/25276), so it isn't too far out at this point.
