### PR TITLE
CLI: Add main.js `docs.autodocs` automigration

### LINKED ISSUE #27078: [Bug]: "The `docs.autodocs` setting in '.storybook/main.js' is deprecated." Appears even after migrating
### Describe the bug

The new autodocs tag mechanism introduced in https://github.com/storybookjs/storybook/pull/26634 includes a deprecation warning about the `docs.autodocs` option in `main.js` being deprecated. It suggests removing that option completely and set the tag in `preview.js` instead.

After doing that and restarting the server, the deprecation warning is still shown.

### To Reproduce

1. Start Storybook `next` with the autodocs option in main.js
2. See the warning in the console.
3. Stop the server
4. Remove the autodocs option from main.js
5. Start the server
6. See the warning in the console still

### System

```bash
8.1.0-beta.0
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by shilman**
Closes #27078

## What I did

Instead of checking the user's `main.js` file at runtime to log a deprecation message, just add an automigration that runs at upgrade time.

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [x] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

Run `storybook automigrate autodocs-tags` in a storybook with:
- `docs.autodocs = true`
- `docs.autodocs = true` and no `preview.js` file
- `docs.autodocs = false`
- `docs.autodocs = 'tag'`

Verify that the migration makes sense and that the messages are useful.

### Documentation

N/A

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Comment by yannbf** [comment]
Some cleanup is needed:

```
src/modules/store/csf/prepareStory.ts(2,1): error TS6133: 'dedent' is declared but its value is never read.
src/modules/store/csf/prepareStory.ts(26,1): error TS6133: 'once' is declared but its value is never read.
```

File: code/lib/cli/src/automigrate/fixes/autodocs-tags.ts [hunk 1]
```diff
@@ -0,0 +1,90 @@
...
+      trueMessage = ` and update ${chalk.cyan(previewConfigPath)}`;
+    }
+
+    return dedent`
+      The ${chalk.cyan('docs.autodocs')} setting in ${chalk.cyan(
+        '.storybook/main.js'
+      )} is deprecated.${falseMessage}
+        
+      Learn more: ${chalk.yellow(
+        'github.com/storybookjs/storybook/blob/next/MIGRATION.md#mainjs-docsautodocs-is-deprecated'
```
Comment (yannbf) [inline code/lib/cli/src/automigrate/fixes/autodocs-tags.ts:63]:
```suggestion
        'https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#mainjs-docsautodocs-is-deprecated'
```

File: code/lib/cli/src/automigrate/fixes/autodocs-tags.ts [hunk 2]
```diff
@@ -0,0 +1,90 @@
...
+        There is no ${chalk.cyan('docs.autodocs = false')} equivalent.
+        You'll need to check your stories to ensure none are tagged with ${chalk.cyan('autodocs')}.
+      `;
+    } else if (autodocs === true) {
+      trueMessage = ` and update ${chalk.cyan(previewConfigPath)}`;
+    }
+
+    return dedent`
+      The ${chalk.cyan('docs.autodocs')} setting in ${chalk.cyan(
+        '.storybook/main.js'
```
Comment (yannbf) [inline code/lib/cli/src/automigrate/fixes/autodocs-tags.ts:59]: can you use the mainConfigPath instead?

File: code/lib/cli/src/automigrate/fixes/autodocs-tags.ts [hunk 3]
```diff
@@ -0,0 +1,90 @@
...
+  id: 'autodocs-tags',
+  versionRange: ['*.*.*', '>=8.0.*'],
+  async check({ mainConfig, previewConfigPath }) {
+    const autodocs = mainConfig?.docs?.autodocs;
+    if (autodocs === undefined) return null;
+
+    if (autodocs === true && !previewConfigPath) {
+      throw Error(dedent`
+        ❌ Failed to remove the deprecated ${chalk.cyan('docs.autodocs')} setting from ${chalk.cyan(
+          '.storybook/main.js'
```
Comment (yannbf) [inline code/lib/cli/src/automigrate/fixes/autodocs-tags.ts:27]: Can you use the mainConfigPath instead?

File: code/lib/cli/src/automigrate/fixes/autodocs-tags.ts [hunk 4]
```diff
@@ -0,0 +1,90 @@
...
+        )}.
+        
+        There is no preview config file to add the ${chalk.cyan('autodocs')} tag to.
+
+        Please perform the migration by hand: ${chalk.yellow(
+          'github.com/storybookjs/storybook/blob/next/MIGRATION.md#mainjs-docsautodocs-is-deprecated'
```
Comment (yannbf) [inline code/lib/cli/src/automigrate/fixes/autodocs-tags.ts:33]:
```suggestion
          'https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#mainjs-docsautodocs-is-deprecated'
```

**Review by yannbf — APPROVED** [review]
Looks fine to me, did not test
