### PR TITLE
Core: Detect no matching export error in storybook start and build

### LINKED ISSUE #23992: [Bug]: No matching export in "global-externals:@storybook/channels" for import "createBrowserChannel"
### Describe the bug

I'm making the following dependency updates

```
-    "@storybook/addon-actions": "7.0.24",
+    "@storybook/addon-actions": "7.3.2",
-    "@storybook/addon-controls": "7.0.24",
+    "@storybook/addon-controls": "7.3.2",
-    "@storybook/addons": "7.0.24",
+    "@storybook/addons": "7.4.0",
-    "@storybook/theming": "7.0.24",
+    "@storybook/theming": "7.4.0",
```

and getting a failure on the `build-storybook` command:

```
Error: R] No matching export in "global-externals:@storybook/channels" for import "createBrowserChannel"
    ../../../../node_modules/@storybook/preview-api/dist/chunk-KAFJUYUA.mjs:5:9:
      5 │ import { createBrowserChannel } from '@storybook/channels';
        ╵          ~~~~~~~~~~~~~~~~~~~~
ERR! Error: Build failed with 1 error:
ERR! ../../../../node_modules/@storybook/preview-api/dist/chunk-KAFJUYUA.mjs:5:9: ERROR: No matching export in "global-externals:@storybook/channels" for import "createBrowserChannel"
```

Thanks for any help!

### To Reproduce

_No response_

### System

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yannbf**
Closes #23992 

## What I did

This PR adds a detection step when running `storybook dev` or `storybook build` for the infamous `No matching exports` error (refer to the issue), which is mostly caused by version inconsistencies in Storybook.

Hopefully this will aid users to fix the issues themselves, but ideally this error should give them a command to run, like `storybook doctor`, which could tell exactly what package to upgrade. For now, we do our best with an error message.

Before:
image

After:
image

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

This is tricky to test, I don't know if it's possible in the monorepo.

1. Create a sandbox
2. Change the version of `storybook` to something old, e.g. `7.0.3`
3. It's crucial that this results in duplicated versions of different Storybook packages, which is why this is tricky in the monorepo given the portaled resolutions which are used.
4. Run Storybook build

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Review by JReinhold — APPROVED** [review]
Haven't tried it out, but the code looks good!

File: code/lib/core-server/src/utils/build-or-throw.ts [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+
+export async function buildOrThrow<T>(callback: () => Promise<T>): Promise<T> {
+  try {
+    return await callback();
+  } catch (err: any) {
+    const builderErrors = err.errors as { text: string }[];
+    if (builderErrors) {
+      const inconsistentVersionsError = builderErrors.find((er) =>
+        er.text.includes('No matching export')
+      );
```
Comment (yannbf) [inline code/lib/core-server/src/utils/build-or-throw.ts:11]:
```suggestion
      const inconsistentVersionsError = builderErrors.find((er) =>
        er.text?.includes('No matching export')
      );
```

File: code/lib/core-events/src/errors/server-errors.ts [hunk 2]
```diff
@@ -368,3 +368,28 @@ export class GoogleFontsLoadingError extends StorybookError {
...
+      There was an exports mismatch error when trying to build Storybook.
+      Please check whether the versions of your Storybook packages match whenever possible, as this might be the cause.
+      
+      Problematic example:
+      { "@storybook/react": "7.5.3", "@storybook/react-vite": "7.4.5", "storybook": "7.3.0" }
+
+      Correct example:
+      { "@storybook/react": "7.5.3", "@storybook/react-vite": "7.5.3", "storybook": "7.5.3" }
+
+      Clearing your lock file and reinstalling your dependencies might help as well.
```
Comment (ndelangen) [inline code/lib/core-events/src/errors/server-errors.ts:392]: You might want to clarify, that their `package.json` file might all refer to the same version, but their lock-file isn't?

Comment (yannbf) [inline code/lib/core-events/src/errors/server-errors.ts:392]:
```suggestion
      Clearing your lock file and reinstalling your dependencies might help as well, as sometimes the version you see in your package.json might not be the one defined in your lock file, leading to version inconsistency issues.
```
