### PR TITLE
UI: Fix titles for addons/controls/panel tabs to support render fns and JSX elements

### LINKED ISSUE #19989: [Bug]: addon-interactions + disabled actions breaks storybook
### Describe the bug

Steps:
1. Generate nx/Angular/Storybook project.
2. Disable actions in `preview.js`
```
export const parameters = {
    actions: { disable: true },
    viewMode: 'docs'
};
```
3. Add interaction addon.
4. Try to build.

Just try to build storybook in repo with `nx run ui-kit:storybook`

Actual: 
`Error: Minified React error #311` and some other errors
Endless storybook app loading

Expected:
No errors, app is loaded

### To Reproduce

```shell
https://github.com/DzmVasileusky/storybook-bug-1
```

### System

```shell
System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    npm: 8.10.0 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Firefox: 106.0.5
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-a11y: ^6.5.13 => 6.5.13 
    @storybook/addon-essentials: ^6.5.13 => 6.5.13 
    @storybook/addon-interactions: ^6.5.13 => 6.5.13 
    @storybook/addon-jest: ^6.5.13 => 6.5.13 
    @storybook/addons: ^6.5.13 => 6.5.13 
    @storybook/angular: ^6.5.13 => 6.5.13 
    @storybook/builder-webpack5: ^6.5.13 => 6.5.13 
    @storybook/core-server: ^6.5.13 => 6.5.13 
    @storybook/jest: ^0.0.10 => 0.0.10 
    @storybook/manager-webpack5: ^6.5.13 => 6.5.13 
    @storybook/test-runner: ^0.9.1 => 0.9.1 
    @storybook/testing-library: ^0.0.13 => 0.0.13 
    @storybook/theming: ^6.5.13 => 6.5.13
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by valentinpalkovic**
Closes https://github.com/storybookjs/storybook/issues/19989

## What I did

The rules of hooks in React were not correctly applied. Hooks were used in a non-react way.

## How to test

1. Run a sandbox for template, e.g. `yarn task --task sandbox --start-from auto --template react-vite/default-ts`
2. Disable actions in preview.js

```jsx
const preview = {
  parameters: {
    actions: {disable: true },
  },
};
```

3. Open a Story. The Addon Tab Panel is visible and the app does not crash

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [x] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

File: code/addons/actions/src/manager.tsx [hunk 1]
```diff
@@ -1,27 +1,41 @@
...
+      setRerender((r) => !r);
+    },
+  });
+
+  const suffix = count.current === 0 ? '' : ` (${count.current})`;
+  return <>Actions{suffix}</>;
+}
+
+addons.register(ADDON_ID, (api) => {
+  const countRef = { current: 0 };
```
Comment (yannbf) [inline code/addons/actions/src/manager.tsx:26]: If this is not really a ref, can't it just be a counter variable instead?

**Review by yannbf — APPROVED** [review]
LGTM!

**Comment by yannbf** [comment]
Hey @valentinpalkovic I actually found an issue:

1. Open Storybook
2. Add `actions: { disable: true }` and see it update correctly
3. change to `actions: { disable: false }` or remove the line altogether, and see that the panel does not get updated:



Is this a memo issue?
