### PR TITLE
Builder-Vite: Centralize Vite plugins for builder-vite and addon-vitest

### LINKED ISSUE #33813: [Maintenance]: Modularize builder-vite into reusable plugins for addon-vitest parity
### Describe the bug

Refactor builder-vite from a monolithic implementation into a suite of self-contained Vite plugins. This allows us to share core Storybook logic (such as configuration injection, entry point handling, and asset management) between the primary Storybook builder and addon-vitest.

## Architectural Overview
Currently, logic is duplicated across builder-vite and addon-vitest. By modularizing this, we ensure that fixes in the builder automatically benefit the testing environment.

### Proposed Plugin Split
- `storybook-config-plugin`: Handles the merging of Storybook-specific Vite config with user-defined configs.
- `storybook-entry-plugin`: Manages the generation and injection of the virtual entry points for stories.
- `storybook-docgen-plugin`: Handles the extraction of component metadata (argTypes, descriptions).
- `storybook-runtime-plugin`: Injects necessary globals and environment variables.

### Reproduction link

-

### Reproduction steps

_No response_

### System

```bash
-
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by valentinpalkovic**
Closes https://github.com/storybookjs/storybook/issues/33813

## What I did

This PR refactors the @storybook/builder-vite plugin architecture to move core logic into a more modular, plugin-based structure.

### Key Changes
**1. Modularization of Vite Plugins**
Previously, much of the Vite configuration (resolve conditions, environment variables, fs-allow rules) was hardcoded within the builder's vite-config.ts. These have been extracted into self-contained plugins:

- `storybookConfigPlugin`: Handles resolve conditions (storybook, stories, test), envPrefix (VITE_, STORYBOOK_), and filesystem access.
- `storybookProjectAnnotationsPlugin`: Manages the virtual module for composed project annotations (getProjectAnnotations).
- `storybookRuntimePlugin`: Handles external globals and environment variable injection.

**2. Introduction of viteCorePlugins Preset**
A new `viteCorePlugins` preset has been added to builder-vite/src/preset.ts. (We don't want to use `viteFinal` to be able to clearly distinguish what is a shareable core plugin and what is config contributed by other addons/frameworks/user config - This was requested by Jeppe). This serves as the single source of truth for the Vite setup required to run Storybook code, and it can now be applied by both the standard builder and the addon-vitest.

**3. Refined Virtual Module Handling**
The project annotations logic has been moved out of the monolithic `codeGeneratorPlugin` into a dedicated virtual `module: virtual:/@storybook/builder-vite/project-annotations.js`. This allows tests and external tools to access composed annotations. The project annotations will be re-used in `@storybook/addon-vitest` in SB 11, since it is considered a breaking change because it might conflict with the user's existing `.storybook/vitest.setup.ts` file.

**4. Cleanups and Optimization**
- Removed sanitizeEnvVars in favor of the new storybookRuntimePlugin, which handles define injection via the standard Vite plugin config hook.
- Dependency Optimization: Simplified getOptimizeDeps logic and moved it into a plugin-driven approach.

**Impact on @storybook/addon-vitest**
By leveraging the new `viteCorePlugins` preset, addon-vitest can now automatically stay in sync with the builder's configuration for resolve conditions, globals, and docgen, reducing the maintenance burden and preventing configuration drift.

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

Manual testing should cover:
- HMR of preview files
- addon-vitest general functionality
- proper setting of optimize deps for both, Storybook and Story Tests powered by Vitest

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This pull request has been released as version `0.0.0-pr-33819-sha-40177d0f`. Try it out in a new sandbox by running `npx storybook@0.0.0-pr-33819-sha-40177d0f sandbox` or in an existing project with `npx storybook@0.0.0-pr-33819-sha-40177d0f upgrade`.
<details>
<summary>More information</summary>

| | |
| --- | --- |
| **Published version** | [`0.0.0-pr-33819-sha-40177d0f`](https://npmjs.com/package/storybook/v/0.0.0-pr-33819-sha-40177d0f) |
| **Triggered by** | @valentinpalkovic |
| **Repository** | [storybookjs/storybook](https://github.com/storybookjs/storybook) |
| **Branch** | [`valentin/encapsulate-vite-plugins`](https://github.com/storybookjs/storybook/tree/valentin/encapsulate-vite-plugins) |
| **Commit** | [`40177d0f`](https://github.com/storybookjs/storybook/commit/40177d0f5feaeb537f984145081ec2c9a3692ae2) |
| **Datetime** | Thu Feb 19 13:56:41 UTC 2026 (`1771509401`) |
| **Workflow run** | [22184698620](https://github.com/storybookjs/storybook/actions/runs/22184698620) |

To request a new release of this pull request, mention the `@storybookjs/core` team.

_core team members can create a new canary release [here](https://github.com/storybookjs/storybook/actions/workflows/publish.yml) or locally with `gh workflow run --repo storybookjs/storybook publish.yml --field pr=33819`_
</details>

## Summary by CodeRabbit

* **New Features**
  * Modular Vite plugins for Storybook (config, runtime, entry, optimize-deps, project annotations) and virtual module for project annotations.
  * Unified codegen for modern iframe to import project annotations.

* **Refactor**
  * Simplified Vite config assembly and optimize-deps flow; moved builder-specific settings into dedicated plugin.
  * Explicit plugin exports and tighter type assertions.

* **Chores**
  * Removed unused imports and cleaned up exports.

### CODE REVIEW

File: code/builders/builder-vite/src/plugins/storybook-runtime-plugin.ts [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+  }
+
+  const plugins: Plugin[] = [await externalGlobalsPlugin(externals)];
+  const envs = await options.presets.apply<Builder_EnvsRaw>('env');
+
+  if (envs && Object.keys(envs).length > 0) {
+    plugins.push({
+      name: 'storybook:env-plugin',
+      config(config) {
+        const envDefines = stringifyProcessEnvs(envs, config.envPrefix);
```
Comment (yannbf) [inline code/builders/builder-vite/src/plugins/storybook-runtime-plugin.ts:22]: take an extra look about this on vitest integration

File: code/addons/vitest/src/vitest-plugin/index.ts [hunk 2]
```diff
@@ -230,7 +229,10 @@ export const storybookTest = async (options?: UserOptions): Promise<Plugin[]> =>
   }
 
   // filter out plugins that we know are unnecesary for tests, eg. docgen plugins
-  const plugins = await withoutVitePlugins(viteConfigFromStorybook.plugins ?? [], pluginsToIgnore);
+  const plugins: Plugin[] = [
+    ...(corePlugins as Plugin[]),
```
Comment (yannbf) [inline code/addons/vitest/src/vitest-plugin/index.ts:233]: the env sanitization is missing

File: code/builders/builder-vite/src/codegen-project-annotations.ts [hunk 3]
```diff
@@ -0,0 +1,94 @@
...
+        return ${previewFileVariable}.default.composed;
+      }
+    `.trim();
+  }
+
+  const hmrCode = [
+    'if (import.meta.hot) {',
+    '  import.meta.hot.accept((newModule) => {',
+    '    window.__STORYBOOK_PREVIEW__?.onGetProjectAnnotationsChanged({',
+    '      getProjectAnnotations: newModule.getProjectAnnotations,',
```
Comment (yannbf) [inline code/builders/builder-vite/src/codegen-project-annotations.ts]: This has to be changed to account for the original use case:
```ts
 import.meta.hot.accept(${JSON.stringify(options.isCsf4 ? [previewFileURL] : previewAnnotationURLs)}, (previewAnnotationModules) => {
  // getProjectAnnotations has changed so we need to patch the new one in
  window.__STORYBOOK_PREVIEW__.onGetProjectAnnotationsChanged({ getProjectAnnotations: () => getProjectAnnotations(previewAnnotationModules) });
});
```

File: code/builders/builder-vite/src/codegen-modern-iframe-script.ts [hunk 4]
```diff
@@ -125,10 +60,8 @@ export async function generateModernIframeScriptCodeFromPreviews(options: {
   import { composeConfigs, PreviewWeb } from 'storybook/preview-api';
```
Comment (yannbf) [inline code/builders/builder-vite/src/codegen-modern-iframe-script.ts]: composeConfigs can be removed

File: code/builders/builder-vite/src/vite-config.ts [hunk 5]
```diff
@@ -86,33 +68,31 @@ export async function commonConfig(
...
-  }
+  const projectRoot = resolve(options.configDir, '..');
 
   const plugins = [
-    codeGeneratorPlugin(options),
+    // Shared core plugins (resolve conditions, envPrefix, fs.allow, docgen, externals, etc.)
+    ...(await corePlugins([], options)),
+    ...(await storybookRuntimePlugin(options)),
     await csfPlugin(options),
-    await injectExportOrderPlugin(),
```
Comment (yannbf) [inline code/builders/builder-vite/src/vite-config.ts:100]: does it matter that injectExportOrderPlugin will then be executed before csfPlugin?

**Review by yannbf — APPROVED** [review]
LGTM
