### PR TITLE
CLI: Automigration for upgrading storybook related dependencies

### LINKED ISSUE #25731: [Bug]: sb upgrade (prerelease) does not upgrade satellite packages
### Describe the bug

Back in Storybook 7.5.0, there was an indicator of every package and version that would be updated:
image

Whereas in Storybook 8, there is a banner that just states that Storybook will be upgraded from Y to X version (assuming that all storybook dependencies are using the same version)
image

However, apart from most of the `@storybook/*` dependencies which follow the same versioning, there are the so called "satellite packages" which are just storybook packages or addons (official or from the community) that follow a different versioning strategy. In Storybook 8, they are not taken into account when upgrading.

### To Reproduce

Using [MealDrop](https://github.com/yannbf/mealdrop) as a repro, after running `npx storybook@next upgrade`, this is what you get:
image

And this is what you were supposed to get (based on 7.5.0 functionality) - notice the test-runner and msw addon being updated to prerelease versions:
image

### Additional context

If the satellite packages are not upgraded, especially in the prerelease example, users will get a possibly broken Storybook because they will contain different major versions installed (and will get a warning via the upgrade command):

image

### PR DESCRIPTION
**Pull request by ndelangen**
Closes https://github.com/storybookjs/storybook/issues/25731

## What I did

This automigration will only run if one of the following is true:
- The user upgrades to the latest version of storybook
- The automigration script is called with this specific automigration targetted:
  `yarn sb automigrate upgradeStorybookRelatedDependencies`

The auto migration performs the following:
1. It looks for packages with `storybook` in their name. This matches packages such as:
   - `eslint-plugin-storybook`
   - `@storybook/addon-designs`
   - `@chromatic-com/storybook`
2. It looks for packages who have dependencies regarded as "storybook core packages".
3. It combines (and de-duplicate) both lists into 1 array
4. It fetches the `packageManager.latestVersion` for each entry
5. Now it checks if the package is upgradable
6. If there are package upgradable then we prompt to user
7. If the user answers yet, we continue
8. It will modify the `package.json` file and then run `packageManager.installDependencies`
9. It will run a `dedupe` command
10. And finally it will print a tiny report. (some of the report is going to be duplicated by the doctor, but it felt useful still.

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

I tested this by running it manually:
```
yarn sb automigrate upgradeStorybookRelatedDependencies
```

It's hard to simulate the code that triggers detecting if the user is updating to latest.

Here's what it looks like if it detects some packages being outdated:
Screenshot 2024-03-07 at 18 15 09

And here's the full output, with the mini report and then the doctor output as well:
Screenshot 2024-03-07 at 18 35 27

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

File: code/lib/cli/src/automigrate/index.ts [hunk 1]
```diff
@@ -94,7 +105,9 @@ export const doAutomigrate = async (options: AutofixOptionsFromCLI) => {
     isUpgrade: false,
   });
 
-  await doctor({ configDir, packageManager: options.packageManager });
+  if (outcome) {
```
Comment (yannbf) [inline code/lib/cli/src/automigrate/index.ts:108]: in what scenario would this not happen?

**Review by shilman — CHANGES_REQUESTED** [review]
Excellent! Left some comments. Also a test for the new automigration would be nice ❤️

**Comment by yannbf** [comment]
Found a bug while testing, it seems like the version detected for some packages is incorrect:
image

and pnpm mentions I only have 8 rc installed
image

This is what the deps looked like before running upgrade:

```
"devDependencies": {
    "@babel/core": "^7.14.6",
    "@ladle/react": "^2.4.5",
    "@storybook/addon-a11y": "^8.0.0-rc.2",
    "@storybook/addon-coverage": "^1.0.1",
    "@storybook/addon-designs": "v8.0.0-next.1",
    "@storybook/addon-essentials": "^8.0.0-rc.2",
    "@storybook/addon-interactions": "^8.0.0-rc.2",
    "@storybook/addon-themes": "^8.0.0-rc.2",
    "@storybook/blocks": "^8.0.0-rc.2",
    "@storybook/react": "^8.0.0-rc.2",
    "@storybook/react-vite": "^8.0.0-rc.2",
    "@storybook/test": "^8.0.0-rc.2",
    "@storybook/test-runner": "next",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^12.1.2",
    "@testing-library/user-event": "^13.5.0",
    "@types/node": "^15.12.3",
    "@types/react": "^17.0.2",
    "@types/react-dom": "^17.0.2",
    "@types/react-hooks-helper": "^1.6.3",
    "@types/react-redux": "^7.1.20",
    "@types/react-transition-group": "^4.4.4",
    "@types/styled-components": "^5.1.10",
    "@types/testing-library__jest-dom": "^5.14.5",
    "@typescript-eslint/eslint-plugin": "^5.10.0",
    "@typescript-eslint/parser": "^5.10.0",
    "@vitejs/plugin-react": "^2.2.0",
    "babel-loader": "8.1.0",
    "babel-plugin-istanbul": "^6.1.1",
    "babel-plugin-open-source": "^1.3.3",
    "c8": "^7.12.0",
    "chromatic": "^6.1.0",
    "concurrently": "^8.2.2",
    "eslint": "^8.27.0",
    "eslint-config-airbnb-typescript": "^16.0.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-import": "^2.25.3",
    "eslint-plugin-jsx-a11y": "^6.5.1",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-react": "^7.27.1",
    "eslint-plugin-react-hooks": "^4.3.0",
    "eslint-plugin-storybook": "^0.6.15",
    "husky": ">=6",
    "istanbul": "^0.4.5",
    "jest-junit": "^13.2.0",
    "jsdom": "^20.0.2",
    "lint-staged": ">=10",
    "msw": "^1.3.2",
    "msw-storybook-addon": "^1.10.0",
    "prettier": "^2.5.0",
    "react-is": "^17.0.2",
    "react-test-renderer": "^17.0.2",
    "storybook": "^8.0.0-rc.2",
    "vite": "^4.0.0",
    "vite-plugin-svgr": "^2.2.2",
    "vite-tsconfig-paths": "^3.5.2",
    "vitest": "^0.25.1",
    "vitest-axe": "^0.1.0",
    "vitest-canvas-mock": "^0.2.2",
    "wait-on": "^7.2.0"
  },
```

File: code/lib/cli/src/automigrate/fixes/upgrade-storybook-related-dependencies.ts [hunk 2]
```diff
@@ -0,0 +1,160 @@
...
+    }
+
+    return null;
+  },
+
+  prompt({ upgradable: list }) {
+    return dedent`
+      You're upgrading to the latest version of Storybook. We recommend upgrading the following packages:
+      ${list
+        .map(({ packageName, version }) => `- ${cyan(packageName)}@${cyan(version)}`)
```
Comment (yannbf) [inline code/lib/cli/src/automigrate/fixes/upgrade-storybook-related-dependencies.ts:85]: The output I got was:

```
│   You're upgrading to the latest version of Storybook. We       │
│   recommend upgrading the following packages:                   │
│   - eslint-plugin-storybook@0.8.0                               │
```

Can we make it so that it show something like:

```
│   You're upgrading to the latest version of Storybook. We       │
│   recommend upgrading the following packages:                   │
│   - eslint-plugin-storybook@0.6.0 (0.8.0 available)             │ 
```

Or

```
│   You're upgrading to the latest version of Storybook. We       │
│   recommend upgrading the following packages:                   │
│   - eslint-plugin-storybook: 0.6.0 => 0.8.0                     │ 
```

This way as a user I know the version I have installed vs the version which is available

**Comment by yannbf** [comment]
I ran the upgrade command on a Storybook 8 project, and it "downgraded" them to Storybook 7 (latest). Do we want to skip that in prereleases?

After "upgrading" to Storybook 7, I got a message which mentioned that it couldn't update these packages:
image

However msw-storybook-addon [doesn't have any Storybook dependencies](https://github.com/mswjs/msw-storybook-addon/blob/main/packages/msw-addon/package.json#L36), so it should not be in the list.

Also addon-coverage only has [core-common](https://github.com/storybookjs/addon-coverage/blob/main/package.json#L47) as a dev dependency because of its types. Even so, that dev dependency is Storybook 7, then I guess in theory it should not be seen as incompatible?

File: code/lib/cli/src/automigrate/fixes/upgrade-storybook-related-dependencies.ts [hunk 3]
```diff
@@ -0,0 +1,160 @@
...
+ * see: https://github.com/storybookjs/storybook/issues/25731#issuecomment-1977346398
+ */
+export const upgradeStorybookRelatedDependencies = {
+  id: 'upgradeStorybookRelatedDependencies',
+  versionRange: ['*.*.*', '*.*.*'],
+  promptType: 'auto',
+  promptDefaultValue: false,
+
+  async check({ packageManager, storybookVersion }) {
+    const packageJson = await packageManager.readPackageJson();
```
Comment (yannbf) [inline code/lib/cli/src/automigrate/fixes/upgrade-storybook-related-dependencies.ts:28]: If you're using this to check for deps + devDeps + peerDeps of the user's package.json (the cwd's package.json, as we don't read up), you don't need this at all, given that you already have them below in:
```ts
await packageManager.getAllDependencies();
```

File: code/lib/cli/src/automigrate/fixes/upgrade-storybook-related-dependencies.ts [hunk 4]
```diff
@@ -0,0 +1,160 @@
...
+
+    if (problematicPackages.length) {
+      console.log();
+      console.log(dedent`
+        The following packages, could not be upgraded,
+        likely because there's no update available compatible with the latest version of Storybook:
+        ${problematicPackages.map(({ packageName }) => `- ${cyan(packageName)}`).join('\n')}
+
+        We suggest your reach out to the authors of these packages to get them updated.
+        But before reporting, please check if there is already an open issue or PR for this.
```
Comment (yannbf) [inline code/lib/cli/src/automigrate/fixes/upgrade-storybook-related-dependencies.ts:155]: I think these messages could include the version you are upgrading to, to be more precise instead of `latest`. This could be useful if this command is supposed to do something in prereleases as well in the future

```suggestion
        likely because there's no stable update available which is compatible with the Storybook ${storybookVersion}:
        ${problematicPackages.map(({ packageName }) => `- ${cyan(packageName)}`).join('\n')}

        We suggest you to reach out to the maintainers of these packages to get them updated.
        But before reporting, please check if there is already an open issue or PR for this.
```

File: code/lib/cli/src/automigrate/fixes/upgrade-storybook-related-dependencies.ts [hunk 5]
```diff
@@ -0,0 +1,160 @@
...
+        if (packageJson.peerDependencies?.[packageName]) {
+          packageJson.peerDependencies[packageName] = prefixed;
+        }
+      });
+
+      await packageManager.writePackageJson(packageJson);
+      await packageManager.installDependencies();
+
+      await packageManager
+        .executeCommand({ command: 'dedupe', args: [], stdio: 'ignore' })
```
[the remark this answers is not in the document]
Comment (ndelangen) [reply code/lib/cli/src/automigrate/fixes/upgrade-storybook-related-dependencies.ts:135]: Not in yarn 1, hence the `.catch` and `sdio: 'ignore'`

File: code/lib/cli/src/automigrate/fixes/upgrade-storybook-related-dependencies.ts (hunk 2 above)
Comment (ndelangen) [reply code/lib/cli/src/automigrate/fixes/upgrade-storybook-related-dependencies.ts:85]: I can pull the version string from the `package.json`, but getting the exact installed version would add a lot of requests.

Why is it useful to know what your current version is?

File: code/lib/cli/src/automigrate/index.ts [hunk 6]
```diff
@@ -121,8 +134,21 @@ export const automigrate = async ({
     return null;
   }
 
-  const selectedFixes = inputFixes || allFixes;
-  const fixes = fixId ? selectedFixes.filter((f) => f.id === fixId) : selectedFixes;
+  const selectedFixes: Fix[] =
```
[the remark this answers is not in the document]
Comment (ndelangen) [reply code/lib/cli/src/automigrate/index.ts:137]: Though that does make sense, it means it's completely impossible to test the automigration in isolation.

Right now I can run `yarn sb automigrate upgradeStorybookRelatedDependencies` to manually force the automigration to run.

[the remark this answers is not in the document]
Comment (ndelangen) [reply code/lib/cli/src/automigrate/index.ts:137]: Do you have a suggestion for how to run it with that change?
see: [`909cb23` (#26377)](https://github.com/storybookjs/storybook/pull/26377/commits/909cb23f3876abc7f642c40f7f365fbee4745458)

**Review by yannbf — APPROVED** [review]

File: code/lib/cli/src/automigrate/index.ts (hunk 6 above)
[the remark this answers is not in the document]
Comment (shilman) [reply code/lib/cli/src/automigrate/index.ts:137]: Ok i don't love it but i don't have a better suggestion that satisfies your constraints

**Review by shilman — APPROVED** [review]
