### PR TITLE
Core: Support groups and info icon in highlight popover menu

### LINKED ISSUE #31414: [Bug]: Accessibility addon: Violation content is not correct
### Describe the bug

1. ~The violation description should match Chromatic's descriptions. They are not custom so it should be a matter of selecting the corresponding field.~
2. The violation link should say “Learn how to resolve this violation”
3. The violation listed in a popover should not be a menu item and should include a link to go to axe’s documentation. I will share screenshots of the specification below.
4. ~The violation listed in a popover should match the title, description, and link shown in the panel.~

Image

### Reproduction link

https://635781f3500dd2c49e189caf-xifgkzulyi.chromatic.com/?path=/story/button-component--variants

### Reproduction steps

1. Go to the above URL
2. Open the Accessibility panel
3. Open "Color contrast." The description says "The color contrast between text and its background meets WCAG AA contrast ratio." The description **should** say "Elements must meet minimum color contrast ratio thresholds"
4. Also check the issues listed above: Incorrect link text and popover menu item behavior

### System

```bash
No, ty.
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ghengeveld**
Closes #31414

## What I did

Split up the a11y popover menu to have a separate "Learn how to resolve this violation" button which links out to the Axe documentation. In order to support this I had to introduce the concept of groups to the menu structure, so it now expects an array of arrays of items rather than an array of items.

A handful of icons have been introduced in order to support the desired UX.

https://github.com/user-attachments/assets/ea811ff9-e886-42c0-8d74-0256606e1890

#### The changes in this PR are covered in the following automated tests:

- [x] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

## Greptile Summary

Enhanced the highlight popover menu functionality by adding support for grouped menu items and info icons, improving accessibility violation descriptions and links in the Storybook UI.

- Added `menuGroups` property in `code/core/src/highlight/types.ts` to support nested menu item grouping
- Updated `normalizeOptions` in `code/core/src/highlight/utils.ts` to handle both legacy and new highlight formats
- Added new MenuGroups story in `code/core/src/highlight/useHighlights.stories.tsx` demonstrating grouped items with info icons
- Fixed SVG attribute naming from camelCase to kebab-case in `code/core/src/highlight/useHighlights.ts`
- Added null check for removeHighlight function to prevent errors

### CODE REVIEW

File: code/addons/a11y/src/components/A11yContext.tsx [hunk 1]
```diff
@@ -215,16 +215,18 @@ export const A11yContextProvider: FC<PropsWithChildren> = (props) => {
...
-          ?.find((r) => r.id === id)
-          ?.nodes.findIndex((n) => details.selectors.some((s) => s === String(n.target))) ?? -1;
-      if (index !== -1) {
-        const key = `${type}.${id}.${index + 1}`;
-        setSelectedItems(new Map([[`${type}.${id}`, key]]));
-        setTimeout(() => {
-          document.getElementById(key)?.scrollIntoView({ behavior: 'smooth', block: 'center' });
-        }, 100);
+      const { helpUrl, nodes } = results?.[type as RuleType]?.find((r) => r.id === id) || {};
+      const openedWindow = helpUrl && window.open(helpUrl, '_blank', 'noopener,noreferrer');
```
Comment (yannbf) [inline code/addons/a11y/src/components/A11yContext.tsx:219]: isn't it bad for a11y if the link opens in a new tab?

**Review by yannbf — APPROVED** [review]

File: code/addons/a11y/src/components/A11yContext.tsx (hunk 1 above)
Comment (ghengeveld) [reply code/addons/a11y/src/components/A11yContext.tsx:219]: Maybe, I don't know. UX wise at least we have an icon to indicate this behavior. For screenreaders I have no idea whether this is okay or not. Either way I think as a general rule we should always be opening 3rd party links in a new tab.
