### PR TITLE
Webpack: Update StorybookConfig import in core-webpack types.ts

### LINKED ISSUE #22472: [Bug]: React.StrictMode is not working
### Describe the bug

`strictMode: true` option is ignored when using `@storybook/react-webpack5` in v. 7.0.*

### To Reproduce

The bug is reproducible in '[React v18 Webpack (TypeScript)](https://stackblitz.com/edit/github-jzuuqp?file=.storybook%2Fmain.ts)' on StackBlitz.

Or locally:

1. `npm init -y`
2. `npx storybook@latest init`
3. Choose `webpack_react` project type
4. Yes to `missing-babelrc` migration
5. Set `framework.options.strictMode` in `main.js` to `true`
6. `npm run storybook`

### System

```shell
Environment Info:

  System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  Binaries:
    Node: 16.19.0 - C:\Program Files\nodejs\node.EXE       
    Yarn: 3.4.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.35)
  npmPackages:
    @storybook/addon-essentials: ^7.0.9 => 7.0.9
    @storybook/addon-interactions: ^7.0.9 => 7.0.9
    @storybook/addon-links: ^7.0.9 => 7.0.9
    @storybook/blocks: ^7.0.9 => 7.0.9
    @storybook/react: ^7.0.9 => 7.0.9
    @storybook/react-webpack5: ^7.0.9 => 7.0.9
    @storybook/testing-library: ^0.0.14-next.2 => 0.0.14-next.2
```

### Additional context

_No response_

### LINKED ISSUE #25739: [Bug]: `env` type is wrong from `StorybookConfig` in `@storybook/your-framework`
### Describe the bug

The `env` property doesn't accept a function definition like this:

```ts
import { StorybookConfig } from "@storybook/angular";

const config: StorybookConfig = {
  stories: [...],
  framework: {
    name: "@storybook/angular"
    options: {},
  },
  env: (config) => ({
    ...config,
    FLAGS: JSON.stringify({
      flag1: true,
    }),
  }),
};

export default config;
```

Error:
image

The bug was introduced in 8.0.0-alpha.0 by https://github.com/storybookjs/storybook/pull/21555 here: https://github.com/storybookjs/storybook/pull/21555/files#diff-6ed749534ddc1242cc6f43a60dd370d916334533a03f2e0c36edb653e24eb74dR1

### To Reproduce

_No response_

### System

```bash
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 7 7800X3D 8-Core Processor
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 1.22.21 - /mnt/c/Program Files/nodejs/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm <----- active
    pnpm: 8.14.2 - /mnt/c/Program Files/nodejs/pnpm
  npmPackages:
    @storybook/addon-a11y: ^8.0.0-alpha.14 => 8.0.0-alpha.14 
    @storybook/addon-actions: ^8.0.0-alpha.14 => 8.0.0-alpha.14 
    @storybook/addon-designs: 7.0.7 => 7.0.7 
    @storybook/addon-essentials: ^8.0.0-alpha.14 => 8.0.0-alpha.14 
    @storybook/addon-interactions: ^8.0.0-alpha.14 => 8.0.0-alpha.14 
    @storybook/addon-links: ^8.0.0-alpha.14 => 8.0.0-alpha.14 
    @storybook/angular: ^8.0.0-alpha.14 => 8.0.0-alpha.14 
    @storybook/jest: 0.2.3 => 0.2.3 
    @storybook/testing-library: 0.2.2 => 0.2.2 
    chromatic: 10.0.0 => 10.0.0 
    eslint-plugin-storybook: 0.6.15 => 0.6.15 
    storybook: ^8.0.0-alpha.14 => 8.0.0-alpha.14
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by valentinpalkovic**
Closes https://github.com/storybookjs/storybook/issues/25739
Closes https://github.com/storybookjs/storybook/issues/22472

## What I did

Updated StorybookConfig import in core-webpack types.ts to use the proper StorybookConfig type and fix type bugs, which were introduced by this change.

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

1. Run a Webpack sandbox
2. Adjust your `.storybook/main.ts` to add the `env` property

```tsx
import { StorybookConfig } from "@storybook/angular";

const config: StorybookConfig = {
  stories: [...],
  framework: {
    name: "@storybook/angular"
    options: {},
  },
  env: (config) => ({
    ...config,
    FLAGS: JSON.stringify({
      flag1: true,
    }),
  }),
};

export default config;
```

3. TypeScript shouldn't complain about the type of `env`

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

File: code/frameworks/react-webpack5/src/preset.ts [hunk 1]
```diff
@@ -9,46 +9,14 @@ export const addons: PresetProperty<'addons'> = [
...
 export const core: PresetProperty<'core'> = async (config, options) => {
-  const framework = await options.presets.apply('framework');
+  const presetFramework = await options.presets.apply('framework');
 
   return {
     ...config,
     builder: {
       name: getAbsolutePath('@storybook/builder-webpack5'),
-      options: typeof framework === 'string' ? {} : framework.options.builder || {},
+      options: typeof presetFramework === 'string' ? {} : presetFramework.options.builder || {},
```
Comment (yannbf) [inline code/frameworks/react-webpack5/src/preset.ts:19]: If you completely removed the `framework` export above, then you don't need to rename this. It's good not to rename this because there are many other places that use this exact same code, and if we ever refactor them we probably would miss this. Or you could rename every place that has this, so they are "find-replaceable"

File: code/frameworks/react-webpack5/src/preset.ts [hunk 2]
```diff
@@ -9,46 +9,14 @@ export const addons: PresetProperty<'addons'> = [
   getAbsolutePath('@storybook/preset-react-webpack'),
 ];
 
-const defaultFrameworkOptions: FrameworkOptions = {
-  legacyRootApi: true,
-};
-
-export const frameworkOptions = async (
```
Comment (yannbf) [inline code/frameworks/react-webpack5/src/preset.ts:16]: Did you check whether this code never had any effect, or whether it was necessary at all? Also, this code change makes it so that the PR/release title is something else, and not just "update StorybookConfig import in core-webpack"

Comment (valentinpalkovic) [reply code/frameworks/react-webpack5/src/preset.ts:16]: Well, I rely on the sandboxes.

https://630511d655df72125520f051-pcarsnsigo.chromatic.com/?path=/docs/configure-your-project--docs
https://630511d655df72125520f051-tgkkntbsmv.chromatic.com/?path=/docs/configure-your-project--docs

One is from `next`, the other one from my branch. A warning from React that the legacyRootAPI is in use doesn't appear in either of the deployed Storybooks. So our assumption, that this code was never executed or taken into account is actually true.

**Review by yannbf — APPROVED** [review]
LGTM!
