### PR TITLE
ArgTypes: Always extract argTypes, even without `addon-docs`

### LINKED ISSUE #31453: [Bug]: Controls broken in minimal install
### Describe the bug

In a minimal install of Storybook (without addon-docs), the following code is not executed:

https://github.com/storybookjs/storybook/blob/9ae3155ebcb166bf46c4006a75baf22dd999f1b1/code/renderers/react/src/preset.ts#L15

This means that controls do not get auto-generated from the component's docgen info.

To fix this, we should remove this condition OR create a new preview entry that only contains this line:

https://github.com/storybookjs/storybook/blob/9ae3155ebcb166bf46c4006a75baf22dd999f1b1/code/renderers/react/src/entry-preview-docs.ts#L27

This needs to be done for all our renderers (React, Vue, etc.) since they all use the same pattern.

### Reproduction link

N/A

### Reproduction steps

1. Install Storybook for React/Vite using the "minimal" option
2. Toggle between the Button Primary and Secondary stories and observe the controls panel losing a row.

### System

```bash
any
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JReinhold**
Closes #31453

## What I did

1. Moved the logic required to extract arg types from docs-only preview entries to the main preview entries in React, Vue, Svelte, HTML Angular, Ember and Web Components.

_(I couldn't get the ember sandbox working to test it out, but I followed the exact same recipe as with the other frameworks, so I feel good about it)_

2. Always run React docgen in `react-webpack5`, instead of only running it when `addon-docs` or `addon-controls` were present. `react-vite` already behaved like this.

#### The changes in this PR are covered in the following automated tests:

- [x] stories
- [ ] unit tests
- [ ] integration tests
- [x] end-to-end tests

#### Manual testing

1. Create a sandbox for any of the given renderers listed above.
2. In the sandbox's main config, remove addon-docs and the `mdx` glob from `stories`
3. Start Storybook
4. Visit the Button > Secondary story, and see that it has _a boolean control_ for the `primary` prop. It wouldn't have without automatic argTypes extraction.

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

## Greptile Summary

This PR moves argTypes extraction logic from docs-only preview entries to main preview entries across multiple renderers (React, Vue, Svelte, HTML, Web Components), ensuring argTypes are always extracted even without addon-docs present.

- Moved `extractArgTypes` and `extractComponentDescription` from `entry-preview-docs.ts` to `entry-preview.ts` in all renderers
- Simplified `enhanceArgTypes` function in `code/core/src/docs-tools/argTypes/enhanceArgTypes.ts` for better readability
- Added proper type definitions and exports for parameters including docs configuration in main preview entries
- Consolidated argTypes extraction as a core feature rather than docs-specific functionality

### CODE REVIEW

**Review by valentinpalkovic — APPROVED** [review]

File: code/core/src/docs-tools/argTypes/enhanceArgTypes.ts [hunk 1]
```diff
@@ -12,10 +12,10 @@ export const enhanceArgTypes = <TRenderer extends Renderer>(
...
-  const withExtractedTypes = extractedArgTypes
-    ? (combineParameters(extractedArgTypes, userArgTypes) as typeof userArgTypes)
-    : userArgTypes;
+  if (!extractArgTypes || !component) {
+    return userArgTypes;
+  }
 
-  return withExtractedTypes;
+  const extractedArgTypes = extractArgTypes(component);
+  return extractedArgTypes ? combineParameters(extractedArgTypes, userArgTypes) : userArgTypes;
```
Comment (JReinhold) [inline code/core/src/docs-tools/argTypes/enhanceArgTypes.ts:20]: the outcome here is the same, I just refactored it slightly to make it more readable. Spent way too many brain cycles on figuring out what happened if `extractArgTypes` or `component` was `undefined`.

File: code/frameworks/angular/src/preset.ts [hunk 2]
```diff
@@ -10,16 +10,23 @@ const getAbsolutePath = <I extends string>(input: I): I =>
...
 
   if ((options as any as StandaloneOptions).enableProdMode) {
     annotations.unshift(require.resolve('./client/preview-prod'));
   }
 
+  const docsConfig = await options.presets.apply('docs', {}, options);
+  const docsEnabled = Object.keys(docsConfig).length > 0;
+  if (docsEnabled) {
+    annotations.push(require.resolve('./client/docs/config'));
+  }
```
Comment (JReinhold) [inline code/frameworks/angular/src/preset.ts:29]: this "copies" the logic that is used in the other frameworks for detecting docs. Strealining everything a little.

File: code/renderers/react/src/entry-preview-docs.ts [hunk 3]
```diff
@@ -1,29 +1,8 @@
...
-    extractArgTypes: ArgTypesExtractor;
-    extractComponentDescription: (component?: any) => string;
-  };
-} = {
-  docs: {
-    story: { inline: true },
-    extractArgTypes,
-    extractComponentDescription,
-  },
-};
```
Comment (JReinhold) [inline code/renderers/react/src/entry-preview-docs.ts:23]: I removed the types here during the migration. It was pretty confusing to read the same code twice, and I don't think it serves any purpose to type the object exactly like it's actual properties, it just means you have to change the code in two places whenever you make changes.
