### PR TITLE
Story Index: Fix storySort parsing for parameters variable

### LINKED ISSUE #21455: [Bug]: unexpected 'parameters'. Parameters 'options.storySort' should be defined inline e.g. ...
### Describe the bug

Since updating from V7 beta 57 to beta 62 I've run into this issue where no stories will load and throw the error 'options.storySort should be defined inline e.g. ...). Couldn't find any indications in the release notes as to what could cause this.

I've tried
- Defining the option in the parameters in preview.tsx
- Removing the parameters object altogether

### To Reproduce

https://github.com/developenguin/storybook-storysort-bug

To reproduce:
run `yarn install`
run `yarn storybook`
Observe that an error is shown

### System

```shell
Environment Info:

  System:
    OS: Linux 5.19 Linux Mint 21.1 (Vera)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
  Binaries:
    Node: 18.12.1 - ~/n/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.2 - ~/n/bin/npm
  Browsers:
    Firefox: 111.0b6
  npmPackages:
    @storybook/addon-actions: ^7.0.0-beta.62 => 7.0.0-beta.62 
    @storybook/addon-essentials: ^7.0.0-beta.62 => 7.0.0-beta.62 
    @storybook/addon-links: ^7.0.0-beta.62 => 7.0.0-beta.62 
    @storybook/mdx2-csf: ^1.0.0-next.5 => 1.0.0-next.5 
    @storybook/nextjs: ^7.0.0-beta.62 => 7.0.0-beta.62 
    @storybook/react: ^7.0.0-beta.62 => 7.0.0-beta.62
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by shilman**
Closes #21455 

## What I did

Fixed handling of parameters defined as a variable in the default export & added test cases

I also changed the behavior to be a little less strict about other cases & assume that some other part of Storybook will catch issues with, say, invalid parameters

Self-merging @tmeasday 

## How to test

- [ ] See attached unit tests

### CODE REVIEW

File: code/lib/csf-tools/src/getStorySortParameter.ts [hunk 1]
```diff
@@ -76,15 +76,18 @@ const parseParameters = (params: t.Expression): t.Expression | undefined => {
       unsupported('options', true);
     }
   } else {
-    unsupported('parameters', true);
+    console.log({ paramsObject });
```
Comment (tmeasday) [inline code/lib/csf-tools/src/getStorySortParameter.ts:79]: @shilman is this log intentional?
