### PR TITLE
Angular: Fix zone.js support for Angular libraries

### LINKED ISSUE #30691: [Bug]: Angular Library requires Zone.js
### Describe the bug

When creating an Angular library with Storybook, an error is thrown "NG0908: In this configuration Angular requires Zone.js". Zone is installed in the project.

I initially found this using NX to create a control component library. However, I was able to reproduce it without NX using just Angular libraries.

### Reproduction link

https://stackblitz.com/edit/stackblitz-starters-34gmr3qu?file=package.json

### Reproduction steps

1. Create a new Angular project
2. Add storybook
3. Create a button (for example) component
4. Add a story for the component
5. Run storybook
6. Observe that as long the component is in the "app," the story is displayed as expected.
7. Create a library for your control
8. Create a component (button, perhaps)
9. Create a story for said component
10. Wire up the angular.json to serve Storybook for the new library
11. Run Storybook for the library
12. Observe the story is not served. Instead, you are presented with an error reading "NG0908: In this configuration Angular requires Zone.js"

### System

```bash
Angular ^19.1.0
Storybook ^8.6.0
```

### Additional context

I have provided scripts in the package.json of this StackBlitz for an easy comparison. Please run `npm run control:storybook` to see the error

### PR DESCRIPTION
**Pull request by valentinpalkovic**
Closes https://github.com/storybookjs/storybook/issues/30691

## What I did

Add `zone.js` as a polyfill if it is missing in the polyfills section and `experimentalZoneless` isn't set to `true`

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

## Greptile Summary

Updates Angular framework configuration to properly include zone.js in polyfills when experimental zoneless mode is not enabled, ensuring proper support for Angular libraries.

- Modified `code/frameworks/angular/src/server/angular-cli-webpack.js` to conditionally include zone.js in polyfills array
- Added check to prevent duplicate zone.js inclusion in polyfills
- Maintains backward compatibility while supporting experimental zoneless mode

### CODE REVIEW

File: code/frameworks/angular/src/server/angular-cli-webpack.js [hunk 1]
```diff
@@ -85,6 +85,10 @@ exports.getWebpackConfig = async (baseConfig, { builderOptions, builderContext }
     ]
   );
 
+  if (!builderOptions.experimentalZoneless && !cliConfig.entry.polyfills.includes('zone.js')) {
```
Comment (kroeder) [inline code/frameworks/angular/src/server/angular-cli-webpack.js:88]: Is `polyfills` always part of the `cliConfig`?  

What if angular libraries don't define it (because they can't). Should it then be this?

```typescript
!cliConfig.entry.polyfills?.includes('zone.js')
```

**Review by kroeder — APPROVED** [review]
besides my comment, looks like a straight forward fix that would work in apps and libraries

**Comment by sk-pub** [comment]
@valentinpalkovic, there is a bug in this code:

```
if (!builderOptions.experimentalZoneless && !cliConfig.entry.polyfills?.includes('zone.js')) {
    cliConfig.entry.polyfills.push('zone.js');
}
```

When `cliConfig.entry.polyfills` is undefined, `.push('zone.js')` fails with "Cannot read properties of undefined (reading 'push')"

**Comment by valentinpalkovic** [comment]
@sk-pub Thanks for reporting. Would you mind open a PR to fix the issue?

**Comment by sk-pub** [comment]
@valentinpalkovic, I created https://github.com/storybookjs/storybook/pull/32230
