### PR TITLE
Babel: Update all @babel/* dependencies

### LINKED ISSUE #24607: [Bug]: Npm audit throws critical warning because of the peer dependency @babel/traverse version used in `@storybook/addon-docs`
### Describe the bug

Babel has suggested to use versions above 7.23.2 as the lower versions have security issues. But the peer dependency for `node_modules/@storybook/addon-docs/node_modules/@storybook/csf-tools` uses `@babel/traverse` lower than that. Can you please upgrade the peer deps for this package?

### To Reproduce

Use following versions -
"@storybook/addon-a11y": "^7.4.6",
  "@storybook/addon-actions": "^7.4.6",
  "@storybook/addon-docs": "^7.4.6",
  "@storybook/addon-essentials": "^7.4.6",
  "@storybook/addon-links": "^7.4.6",
  "@storybook/addon-storysource": "^7.4.6",
  "@storybook/addons": "^7.4.6",
  "@storybook/angular": "^7.4.6",

and check npm audit. It will give you critical warnings.

### System

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by valentinpalkovic**
Closes https://github.com/storybookjs/storybook/issues/24607

## What I did

- Update all @babel/* dependencies
- Removed unneeded ts-to-ts49 codemod

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Review by yannbf — APPROVED** [review]

File: scripts/ts-to-ts49.ts [hunk 1]
```diff
@@ -1,96 +0,0 @@
-/* eslint-disable @typescript-eslint/no-shadow,no-restricted-syntax */
```
Comment (ndelangen) [inline scripts/ts-to-ts49.ts:1]: I assume you're deleting this file because it's no longer used/ran?

Please add this to the PR description.

**Comment by ashwaryasharma741** [comment]
@valentinpalkovic When will this version be published?

**Comment by valentinpalkovic** [comment]
The 7.6.0-alpha.4 release might be published soon. But if you don't want to wait, just update your lock file. The `@babel/traverse` package is not pinned to an exact version. Updating your dependencies should lead to the latest version of this package.
