### PR TITLE
Preview: Enforce inert body if manager is focus-trapped

### LINKED ISSUE #32596: [Bug]: Focus trap war between preview and manager when both have an overlay open
### Describe the bug

This is a UI bug happening when our users' code in preview attempts to grab focus. Because preview code can come from a variety of frameworks, we'd want to handle this ourselves internally.

When we open a menu, popover, select in the UI, it implements a focus trap on the overlay content. That focus trap can cause preview components' own focus trap logic to enter into a battle for control of focus with our own react-aria components.

https://github.com/adobe/react-spectrum/issues/8952 reports the issue upstream as we see this with RAC in manager and RAC in preview, but we also want a general solution.

Through some testing, I noticed that manager managed (!) to keep control of focus if we add `inert` to the iframe. So, to solve this issue, we want to add logic in our codebase to detect when any of the following (but _not_ WithTooltip) is currently open:
* Modal
* Select
* WithPopover
* WithMenu (TBA)

And when they are open, we want to add `inert` to preview iframes to prevent focus wars.

### Reproduction link

https://a11y-consolidation--635781f3500dd2c49e189caf.chromatic.com/?path=/story/overlay-modal--base

### Reproduction steps

1. Go to https://a11y-consolidation--635781f3500dd2c49e189caf.chromatic.com/?path=/story/overlay-modal--base
2. Open the modal in the preview area
3. Click on the cog icon at the top-right of the sidebar, which opens a popover
4. Press Tab

### System

```bash
SB 10.0 beta, Linux, Chrome 140
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Sidnioulz**
Closes https://github.com/storybookjs/storybook/issues/32596

Caused by https://github.com/whatwg/html/issues/7605

## What I did

* Added an event so that manager can inform preview it is focus trapped
* Added focus trap detection logic to manager (reads `inert` attr set by RAC on `#root` when it traps focus)
* Added focus trap event handler to preview (enforces `inert` on preview body to prevent any programmatic focus from happening)

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

1. Run the code
2. Navigate to http://localhost:6006/?path=/story/overlay-modal--always-open
3. Open your favourite manager modal with the keyboard
4. Navigate within the modal with the keyboard and notice how focus isn't getting stolen any more

### Documentation

ø

## Checklist for Maintainers

- [x] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [x] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/publish.yml) or locally with `gh workflow run --repo storybookjs/storybook publish.yml --field pr=<PR_NUMBER>`_

## Summary by CodeRabbit

* **New Features**
  * New manager-preview event to notify inert attribute changes, enabling synchronized inert state between manager and preview.
  * Added inert synchronization so the preview mirrors manager inert state on load and when it changes.
  * Modals and popovers now hide outside content for improved accessibility when open.

* **Bug Fixes**
  * More reliable inert propagation to avoid stale focus or interaction issues.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: code/core/src/manager/App.tsx [hunk 1]
```diff
@@ -27,6 +27,29 @@ export const App = ({ managerLayoutState, setManagerLayoutState, pages, hasTab }
...
+      return;
+    }
+
+    const observer = new MutationObserver((mutations) => {
+      mutations.forEach((mutation) => {
+        if (mutation.type === 'attributes' && mutation.attributeName === 'inert') {
+          const hasInert = rootElement.hasAttribute('inert');
+          addons.getChannel().emit('managerFocusTrapChange', hasInert);
+        }
+      });
```
Comment (ghengeveld) [inline code/core/src/manager/App.tsx]: Technically this is the correct way do handle the callback value, but we don't really need the `forEach` nor the `if` check, since we're only observing a single element and we're using `attributeFilter`, so we know by definition that `mutations` will be a single item `{ type: 'attributes', attributeName: 'inert' }`.

File: code/core/src/manager/App.tsx [hunk 2]
```diff
@@ -27,6 +27,29 @@ export const App = ({ managerLayoutState, setManagerLayoutState, pages, hasTab }
     document.body.setAttribute('data-shortcuts-enabled', enableShortcuts ? 'true' : 'false');
   }, [enableShortcuts]);
 
+  useEffect(() => {
```
Comment (ghengeveld) [inline code/core/src/manager/App.tsx:43]: Please add a comment explaining why we need to track the `inert` attribute.

File: code/core/src/manager/App.tsx [hunk 3]
```diff
@@ -27,6 +27,29 @@ export const App = ({ managerLayoutState, setManagerLayoutState, pages, hasTab }
...
+    const rootElement = document.getElementById('root');
+    if (!rootElement) {
+      return;
+    }
+
+    const observer = new MutationObserver((mutations) => {
+      mutations.forEach((mutation) => {
+        if (mutation.type === 'attributes' && mutation.attributeName === 'inert') {
+          const hasInert = rootElement.hasAttribute('inert');
+          addons.getChannel().emit('managerFocusTrapChange', hasInert);
```
Comment (ghengeveld) [inline code/core/src/manager/App.tsx]: This should use the constant, not a magic string.

Also, the name and value of this constant does not reflect the actual event. I think it should be something like `INERT_ATTRIBUTE_CHANGED`.

File: code/core/src/preview/runtime.ts [hunk 4]
```diff
@@ -31,6 +31,17 @@ export function setup() {
     channel.emit(TELEMETRY_ERROR, prepareForTelemetry(error));
   };
 
+  document.addEventListener('DOMContentLoaded', () => {
```
Comment (ghengeveld) [inline code/core/src/preview/runtime.ts:41]: Add a comment explaining what this is for (synchronizing `inert` between manager and preview).

File: code/core/src/preview/runtime.ts [hunk 5]
```diff
@@ -31,6 +31,17 @@ export function setup() {
...
+    const channel = global.__STORYBOOK_ADDONS_CHANNEL__;
+    channel.on(MANAGER_FOCUS_TRAP_CHANGE, (isActive: boolean) => {
```
Comment (ghengeveld) [inline code/core/src/preview/runtime.ts]:
```suggestion
    channel.on(MANAGER_FOCUS_TRAP_CHANGE, (isInert: boolean) => {
```

**Review by ghengeveld — CHANGES_REQUESTED** [review]

File: code/core/src/manager/App.tsx (hunk 3 above)
Comment (Sidnioulz) [reply code/core/src/manager/App.tsx]: Good catch!

I initially named it `MANAGER_FOCUS_TRAP_CHANGE` because from framework/addon authors' perspective, I want the API to reflect the meaning or purpose of the event. I want third-parties to know they must stop all programmatic focus attempts. At the end of the day, I enforce a stop in the preview by also applying inert there, so it makes sense to name the event after what it actually does. I'll rename it!

File: code/core/src/manager/App.tsx (hunk 1 above)
Comment (Sidnioulz) [reply code/core/src/manager/App.tsx]: You're right, it's safe to process the event directly and it's safe to process it once.

**Comment by Sidnioulz** [comment]
Found two more holes in the emperor's armour:
* Select does not set inert
* Modal does not set inert

**Review by ghengeveld — APPROVED** [review]

**Review by ghengeveld — APPROVED** [review]
