### PR TITLE
CLI: Support addon-vitest setup when --skip-install is passed

### LINKED ISSUE #32377: [Bug]: `addon-vitest` and `addon-a11y` postinstall is not executed when running `create-storybook` with `--skip-install`
### Describe the bug

During the creation process, when the user selects the Recommended setup with testing, it adds `@storybook/addon-vitest` and `@storybook/addon-a11y`. Both have postinstall scripts that automatically modifies the Vite/Vitest configurations.

However when creating with the `--skip-install` flag - which skips dependency installations - these postinstall scripts are not executed and thus the setup is not complete.

### Reproduction link

x

### Reproduction steps

1. Run `npx create-storybook@latest --skip-install` and select "Recommended"
2. See that `.storybook/vitest.setup.ts` has _not_ been created, and the Vite config has not been modified.

### System

```bash
s
```

### Additional context

Related: https://github.com/sveltejs/svelte/pull/16701#issuecomment-3246467474

Short term I propose that we get the postinstall scripts of `addon-vitest` and `addon-a11y` into `create-stroybook` - as we know they are needed anyway - so they can be executed even with `--skip-install`. They could potentially just be relatively imported in the monorepo.

In the longer term we want to rethink the whole init flow, and only install dependencies at the end instead of multiple times.

### PR DESCRIPTION
**Pull request by valentinpalkovic**
Closes #32377

## What I did

Run @storybook/addon-vitest's and @storybook/addon-a11y's postinstall even with --skip-install during `init`. Bundle and call the addon's postinstall directly during init, avoiding runtime resolution failures when deps aren’t installed.

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

1. Run `npx storybook@latest --skip-install` and select "Recommended"
2. See that `.storybook/vitest.setup.ts` has been created, and the Vite config has been modified.

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This pull request has been released as version `0.0.0-pr-33718-sha-6755af19`. Try it out in a new sandbox by running `npx storybook@0.0.0-pr-33718-sha-6755af19 sandbox` or in an existing project with `npx storybook@0.0.0-pr-33718-sha-6755af19 upgrade`.
<details>
<summary>More information</summary>

| | |
| --- | --- |
| **Published version** | [`0.0.0-pr-33718-sha-6755af19`](https://npmjs.com/package/storybook/v/0.0.0-pr-33718-sha-6755af19) |
| **Triggered by** | @valentinpalkovic |
| **Repository** | [storybookjs/storybook](https://github.com/storybookjs/storybook) |
| **Branch** | [`valentin/bundle-addon-vitest-postinstall-into-storybook`](https://github.com/storybookjs/storybook/tree/valentin/bundle-addon-vitest-postinstall-into-storybook) |
| **Commit** | [`6755af19`](https://github.com/storybookjs/storybook/commit/6755af1976a28f3179f9206b3d2a20f63810b810) |
| **Datetime** | Tue Feb  3 09:11:12 UTC 2026 (`1770109872`) |
| **Workflow run** | [21624078404](https://github.com/storybookjs/storybook/actions/runs/21624078404) |

To request a new release of this pull request, mention the `@storybookjs/core` team.

_core team members can create a new canary release [here](https://github.com/storybookjs/storybook/actions/workflows/publish.yml) or locally with `gh workflow run --repo storybookjs/storybook publish.yml --field pr=33718`_
</details>

## Summary by CodeRabbit

* **Bug Fixes**
  * Automigration and addon installers now use a versioned Storybook CLI and fall back to a default when the installed version is unavailable.
  * Addon configuration no longer aborts early on install checks; partial addon failures are reported per-addon.

* **New Features**
  * Installer commands can run using a remote package mode when local install is skipped.

* **Chores / Refactor**
  * Template loading switched to dynamic module imports; postinstall routing standardized per addon.
  * Build tooling configured to include a raw-loader plugin dependency.

* **Types**
  * Added ambient typing for wildcard "*?raw" imports.

* **Tests**
  * Tests updated to use new template names and reflect updated addon configuration behavior.

### CODE REVIEW

File: code/addons/vitest/src/updateVitestFile.ts [hunk 1]
```diff
@@ -1,16 +1,26 @@
-import * as fs from 'node:fs/promises';
-
 import type { BabelFile, types as t } from 'storybook/internal/babel';
 
-import { join, normalize } from 'pathe';
+import { normalize } from 'pathe';
 
-import { resolvePackageDir } from '../../../core/src/shared/utils/module';
+async function getTemplatePath(name: string) {
+  switch (name) {
```
Comment (JReinhold) [inline code/addons/vitest/src/updateVitestFile.ts:10]: I think we should have a comment here, explaining why we need to do it this way.

**Review by JReinhold — APPROVED** [review]
