### PR TITLE
Fix usage of custom favicon

### LINKED ISSUE #581: Custom favicon (and customize layout in general)
My specific question: how can you add a custom favicon (like http://airbnb.io/react-dates). I'm using a webpack config if it makes any difference.

More general question: Is it possible to customize the CSS/layout at all? I'd like to add my company name/logo in place of the `REACT STORYBOOK` header in the top left. I could also see it being useful to customize the CSS of the "chrome" around the examples. Is this possible now or are there any plans to support this?

BTW I'm a huge fan of this project. We recently switched to it from a home-grown version which:
- was harder to maintain
- more inconsistent across example groups
- was shipped with our prod build which meant we needed to load dependencies like `faker` in prod.

### PR DESCRIPTION
**Pull request by jeffcarbs**
Fixes #581

This line (https://github.com/kadirahq/react-storybook/blob/master/src/server/index.js#L69) hard-codes the favicon to be pulled from `/node_modules/@kadira/storybook/dist/server/public/favicon.ico`.

This update first checks the specified static files for a `favicon.ico` and uses that if one is found. Otherwise, it falls back to using the default storybook favicon. The tricky part here is that it seems that the first call to `app.use(favicon)` wins, so we need to do the default last.

### CODE REVIEW

**Comment by mnmtanish** [comment]
Awesome! I'll just check it out locally in a few hours and merge

File: src/server/index.js [hunk 1]
```diff
@@ -78,9 +77,20 @@ if (program.staticDir) {
...
+
+    // If there's a favicon on the specified path, use it.
+    const faviconPath = path.resolve(staticPath, 'favicon.ico');
+    if (fs.existsSync(faviconPath)) {
+      app.use(favicon(faviconPath));
+    }
   });
 }
 
+// The first call to app.use(favicon) wins so we first check if there's a
```
Comment (arunoda) [inline src/server/index.js]: Is this something documented? 
I mean it's better to have a variable called `hasCustomFavicon` and act accordingly.

**Comment by arunoda** [comment]
@jcarbo I think we need to do the same in the `build.js` as well.
See: https://github.com/kadirahq/react-storybook/blob/8610bca7b0cbba93fa6c770dad4404325be6e549/src/server/build.js#L56

**Comment by jcarbo** [comment]
@arunoda - Looks like that line just copies the favicon from `/public/favicon.ico` into the main `outputDir` directory. If you define a static dir, all those assets will then be copied into that same directory afterward (https://github.com/kadirahq/react-storybook/blob/8610bca7b0cbba93fa6c770dad4404325be6e549/src/server/build.js#L65-L74) so if you've defined a `favicon.ico` it will override the default.

Given that, it looks like this is only an issue in development which is using express. When the build is compiled statically your custom `favicon.ico` will be the one that gets built.

File: src/server/index.js (hunk 1 above)
Comment (jcarbo) [inline src/server/index.js]: It's just something I noticed, but you're right that it's not super clear. I'll update this to use `hasCustomFavicon` based on your feedback.

**Comment by jcarbo** [comment]
Updated! I built and tested this in my app and it works as expected.

**Comment by arunoda** [comment]
@jcarbo yep. You've a solid point in that.
