### PR TITLE
Core: Switch from `mlly` to `exsolve`

### LINKED ISSUE #32364: [Bug]: SB 10.0.0-beta.0 not working on windows
### Describe the bug

```
SB_CORE-COMMON_0003 (CouldNotEvaluateFrameworkError): Could not evaluate the '.\node_modules\@storybook\react-vite' package from the 'framework' field of Storybook config.

Are you sure it's a valid package and is installed?

More info:

    at validateFrameworkName (file:///C:/dev/sb-10-pnp/node_modules/storybook/dist/_node-chunks/chunk-H5LTFJHQ.js:12649:11)
```

(ignore the pnp in the path - I thought it was a pnp error but it happens with node_modules linker too)

Looks like `mlly` isn't hadling windows paths?

### Reproduction link

https://github.com/mrginglymus/sb-10-pnp

### Reproduction steps

```bash
yarn
yarn storybook
```

### System

```bash
10.0.0-beta.0
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mrginglymus**
Closes #32364

## What I did

mlly resolve utils are deprecated
(https://github.com/unjs/mlly/pull/324#issuecomment-3248210965), and it is recommended to use exsolve instead.

The old strip-abs-node-modules-path utility is reintroduced as there is no equivalent in exsolve, and the mlly implementation was more or less the same anyway (except using regex instead of split)

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [x] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [x] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

## Greptile Summary

Updated On: 2025-09-03 09:05:50 UTC

This PR migrates Storybook from the deprecated `mlly` library to `exsolve` for module resolution utilities across the core package. The main changes include:

1. **Dependency Migration**: Removes `mlly` (^1.7.4) and adds `exsolve` (^1.0.7) in the core package.json
2. **API Updates**: Replaces `resolvePathSync` from mlly with `resolveModulePath` from exsolve in multiple files, with minor parameter changes (e.g., `url` becomes `from`)
3. **Utility Reintroduction**: Adds a new `stripAbsNodeModulesPath` utility function since exsolve doesn't provide an equivalent to mlly's `parseNodeModulePath`
4. **Cross-Platform Compatibility**: The new utility uses `posix.normalize` and `slash` for better Windows path handling

The changes affect module resolution in framework validation (`validate-config.ts`), manager building (`builder-manager/index.ts`), and preset loading (`presets.ts`). This migration addresses a critical Windows compatibility issue where mlly's path parsing was causing Storybook to fail on Windows systems. The exsolve library provides the same core functionality with better cross-platform support and is the officially recommended replacement by the mlly maintainers.

## Confidence score: 3/5

- This PR addresses a legitimate deprecation issue but has some implementation concerns that could cause problems
- Score reflects the presence of unused imports and incomplete migration patterns that suggest hasty implementation
- Pay close attention to `code/core/src/common/presets.ts` which contains unused imports and potential logic issues

### CODE REVIEW

File: code/core/src/builder-manager/index.ts [hunk 1]
```diff
@@ -42,8 +42,8 @@ export const getConfig: ManagerBuilder['getConfig'] = async (options) => {
   const tsconfigPath = getTemplatePath('addon.tsconfig.json');
   let configDirManagerEntry;
   try {
-    configDirManagerEntry = resolvePathSync('./manager', {
-      url: options.configDir,
+    configDirManagerEntry = resolveModulePath('./manager', {
+      from: options.configDir,
```
Comment (pi0) [inline code/core/src/builder-manager/index.ts:46]: Perf/Stability: Please make sure configDir ends with a trailing slash to indicate it is a dir otherwise resolution goes to a slow path to stat the path.

File: code/core/src/common/presets.ts [hunk 2]
```diff
@@ -12,12 +12,12 @@ import type {
   StorybookConfigRaw,
 } from 'storybook/internal/types';
 
-import { parseNodeModulePath } from 'mlly';
```
Comment (pi0) [inline code/core/src/common/presets.ts:15]: `mlly` is not deprecated. Only resolution util, you can keep using `mlly` for `parseNodeModulePath` :)

**Review by ndelangen — APPROVED** [review]

**Comment by pi0** [comment]
Please check comments above 😄

**Comment by ndelangen** [comment]
@JReinhold do you have a preference regarding the above?

File: code/core/src/common/presets.ts (hunk 2 above)
Comment (mrginglymus) [reply code/core/src/common/presets.ts:15]: I switched it on a one-in-one-out basis - doesn't make a huge difference to end users as its bundled, but given that all this is doing is splitting by `node_modules`, it doesn't seem worth the extra dep.

The function is also defined in the `resolve` file of mlly, so might presumably get swept up in a future clean out of the deprecated resolve utils.
