### PR TITLE
CLI: Fix vite config automigration to resolve from project root

### LINKED ISSUE #26260: [Bug]: v8 `automigrate` `viteConfigFile` failure
### Describe the bug

I ran `npx storybook@next upgrade --config-dir apps/my-app/.storybook` on a Nx monorepo. I got this error:

```
❌ error when running viteConfigFile migration
Error: Invariant failed: run method should be available in fix.
    at invariant (/Users/fileas/.npm/_npx/eb8bf615e50a412a/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:14:11)
    at runFixes (/Users/fileas/.npm/_npx/eb8bf615e50a412a/node_modules/@storybook/cli/dist/generate.js:569:1598)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async automigrate (/Users/fileas/.npm/_npx/eb8bf615e50a412a/node_modules/@storybook/cli/dist/generate.js:567:1525)
    at async doUpgrade (/Users/fileas/.npm/_npx/eb8bf615e50a412a/node_modules/@storybook/cli/dist/generate.js:583:1625)
    at async withTelemetry (/Users/fileas/.npm/_npx/eb8bf615e50a412a/node_modules/@storybook/core-server/dist/index.js:28:3579)
    at async upgrade (/Users/fileas/.npm/_npx/eb8bf615e50a412a/node_modules/@storybook/cli/dist/generate.js:583:2063)

Unable to find .eslintrc config file, skipping
```

Rest of the migrations worked successfully.

### To Reproduce

Here is my reproduction repository: https://github.com/mandarini/storybook-upgrade-latest-nx

I have detailed steps on the README.

Here is the [migration-storybook.log](https://github.com/mandarini/storybook-upgrade-latest-nx/blob/main/migration-storybook.log), where the error appears.

### System

```bash
npx storybook@next info

Storybook Environment Info:

  System:
    OS: macOS 13.5
    CPU: (12) arm64 Apple M2 Max
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm <----- active
    pnpm: 8.6.11 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 122.0.6261.69
    Safari: 16.6
  npmPackages:
    @storybook/addon-essentials: ^8.0.0-rc.0 => 8.0.0-rc.0
    @storybook/addon-interactions: ^8.0.0-rc.0 => 8.0.0-rc.0
    @storybook/core-server: ^8.0.0-rc.0 => 8.0.0-rc.0
    @storybook/react-vite: ^8.0.0-rc.0 => 8.0.0-rc.0
    @storybook/test: ^8.0.0-rc.0 => 8.0.0-rc.0
    @storybook/test-runner: ^0.13.0 => 0.13.0
    storybook: ^8.0.0-rc.0 => 8.0.0-rc.0

```
```


### Additional context

_No response_

### PR DESCRIPTION
**Pull request by valentinpalkovic**
Closes https://github.com/storybookjs/storybook/issues/26260

## What I did

I try to resolve and search for the vite.config.js starting from the project root instead of `cwd` during the `vite-config-file` automigration.

Additionally, the `vite-config-file` automigrations throws an error instead of showing a prompt. This was because the `promptType` wasn't defined and a `run` function was missing. I have improved the types for the `Fix` type.

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

1. Checkout https://github.com/mandarini/storybook-upgrade-latest-nx
2. Checkout the README.md for detailed reproduction steps

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This pull request has been released as version `0.0.0-pr-26262-sha-bb8590c9`. Try it out in a new sandbox by running `npx storybook@0.0.0-pr-26262-sha-bb8590c9 sandbox` or in an existing project with `npx storybook@0.0.0-pr-26262-sha-bb8590c9 upgrade`.
<details>
<summary>More information</summary>

| | |
| --- | --- |
| **Published version** | [`0.0.0-pr-26262-sha-bb8590c9`](https://npmjs.com/package/@storybook/cli/v/0.0.0-pr-26262-sha-bb8590c9) |
| **Triggered by** | @valentinpalkovic |
| **Repository** | [storybookjs/storybook](https://github.com/storybookjs/storybook) |
| **Branch** | [`valentin/fix-vite-config-automigration`](https://github.com/storybookjs/storybook/tree/valentin/fix-vite-config-automigration) |
| **Commit** | [`bb8590c9`](https://github.com/storybookjs/storybook/commit/bb8590c9b7d59cfd047be62632eb8e20ca299a9e) |
| **Datetime** | Mon Mar  4 07:30:07 UTC 2024 (`1709537407`) |
| **Workflow run** | [8136961530](https://github.com/storybookjs/storybook/actions/runs/8136961530) |

To request a new release of this pull request, mention the `@storybookjs/core` team.

_core team members can create a new canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=26262`_
</details>

### CODE REVIEW

**Comment by valentinpalkovic** [comment]
@mandarini Could you check out the canary release of this PR? `0.0.0-pr-26262-sha-4d24ee07`

File: code/lib/cli/src/automigrate/types.ts [hunk 1]
```diff
@@ -38,8 +37,23 @@ export interface Fix<ResultType = any> {
...
+  | {
+      promptType?: PromptType<ResultType, 'auto'>;
+      run: (options: RunOptions<ResultType>) => Promise<void>;
+    }
+  | {
+      promptType: PromptType<ResultType, 'manual' | 'notification'>;
+      run?: never;
+    }
+) &
+  BaseFix<ResultType>;
```
Comment (kasperpeulen) [inline code/lib/cli/src/automigrate/types.ts:56]: Nice!

**Review by kasperpeulen — APPROVED** [review]
