### PR TITLE
Maintenance: Drop tooling support

### LINKED ISSUE #30353: [Storybook 9]: Drop support for tooling/integrations/frameworks
### Describe the bug

The official support and maintenance of the following third-party toolings/integrations/frameworks will be removed in Storybook 9:

| Category | Tool | Versions |
|----------|------|----------|
| JavaScript Engine | Node.js | v18 |
| Package Manager | npm | v8, v9 |
| Package Manager | yarn | v3 |
| Package Manager | pnpm | v7, v8 |
| Renderer | Angular | v15, v16, v17 |
| Renderer | Lit | v1 |
| Builders | Vite | v4 |
| Language | Typescript | < v4.9 (4.9 introduces satisfies support) |
| Renderer | Svelte | < v5 |

### PR DESCRIPTION
**Pull request by valentinpalkovic**
Closes https://github.com/storybookjs/storybook/issues/30353

## What I did

This PR drops support for older tooling versions across Storybook packages:

- Drops Vite 4 support, requiring Vite 5+ across all Vite-based frameworks and builders
- Drops Angular <18 support
- Drops Node.js <20 support
- Drops Next.js <14.1.0 support
- Updates package manager requirements (npm v10+, yarn v4+, pnpm v9+)

Migration guide entries have been added to document these changes.

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

## Greptile Summary

This PR implements major breaking changes for Storybook 9.0, dropping support for older tooling versions and updating minimum requirements across the ecosystem.

- Raises minimum Node.js requirement to v20+ across all packages, dropping v18 support
- Removes Vite 4 support, requiring Vite 5+ for all Vite-based frameworks and builders
- Drops Angular <18 support and updates related dependencies
- Removes several deprecated APIs including `autodocs` config, `globals` in favor of `initialGlobals`, and legacy button props
- Updates package manager requirements to npm v10+, yarn v4+, and pnpm v9+

The changes are well documented in MIGRATION.md with clear upgrade paths provided.

### CODE REVIEW

File: code/.storybook/main.ts [hunk 1]
```diff
@@ -1,5 +1,7 @@
 import { join } from 'node:path';
 
+import react from '@vitejs/plugin-react';
```
Comment (ndelangen) [inline code/.storybook/main.ts:3]: We were missing this?!?! 😕

File: code/.storybook/preview.tsx [hunk 2]
```diff
@@ -280,7 +280,7 @@ const decorators = [
                 <div style={{ marginBottom: 20 }} />
               </>
             )}
-            <StoryFn />
```
Comment (ndelangen) [inline code/.storybook/preview.tsx:283]: Can you explain?

**Comment by ndelangen** [comment]
I think you may have missed a node version reference in the bin files:
https://github.com/storybookjs/storybook/blob/447caec091b077cd86a4d0c07fb9d68eec9219a3/code/core/bin/index.cjs#L3-L7

File: code/.storybook/main.ts (hunk 1 above)
Comment (valentinpalkovic) [reply code/.storybook/main.ts:3]: I have no clue how our Storybook was supposed to work without it. Maybe you have a good explanation!

File: code/lib/cli-storybook/src/autoblock/block-dependencies-versions.ts [hunk 3]
```diff
@@ -7,7 +7,7 @@ import { createBlocker } from './types';
 const minimalVersionsMap = {
   '@angular/core': '15.0.0',
   'react-scripts': '5.0.0',
-  next: '13.5.0',
+  next: '14.1.0',
   preact: '10.0.0',
   svelte: '4.0.0',
   vue: '3.0.0',
```
[the remark this answers is not in the document]
Comment (valentinpalkovic) [reply code/lib/cli-storybook/src/autoblock/block-dependencies-versions.ts:13]: Good point!

File: code/.storybook/preview.tsx (hunk 2 above)
Comment (valentinpalkovic) [reply code/.storybook/preview.tsx:283]: Sorry. This was just for testing purposes. I will revert. Good catch
