### PR TITLE
Manager: Ensure reset item only appears in globals toolbar when specified

### LINKED ISSUE #33271: [Bug]: Unwanted 'reset' option on globals
### Describe the bug

Since 10.1 (possibly 10.0?) my toolbar globals have had a new 'Reset selection` option.

Clicking this sets the global value to the string `_reset`, which is obviously undesirable. 

I would expect it to either

1. set it to defaultValue
2. set it to the initial value
3. set it to undefined
4. not be there

### Reproduction link

https://stackblitz.com/edit/github-w91nbsqm?file=.storybook%2Fpreview.ts,src%2Fstories%2FConfigure.mdx,.storybook%2Fmain.ts&preset=node

### Reproduction steps

_No response_

### System

```bash
-
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mrginglymus**
Closes #33271

## What I did

The `Select` component would add a 'reset' option if `onReset` was specified. The `ToolbarMenuSelect` component was unconditionally providing this callback.

The fix is to only pass in the `onReset` handler if a reset item has been specified by the user.

In addition, the reset handler is called with the reset value, instead of the static string `_reset`.

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

In the default storybook, note that the theme global no longer has a reset option:

image

but the locale one does

image

and clicking it now sets the locale to `undefined` instead of `'_reset'`

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/publish.yml) or locally with `gh workflow run --repo storybookjs/storybook publish.yml --field pr=<PR_NUMBER>`_

## Summary by CodeRabbit

* **Bug Fixes**
  * Toolbar reset functionality now applies conditionally based on reset item configuration instead of using a static value.

* **Refactor**
  * Improved reset item normalization handling in toolbar.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: code/core/src/toolbar/components/ToolbarMenuSelect.tsx [hunk 1]
```diff
@@ -98,7 +98,7 @@ export const ToolbarMenuSelect: FC<ToolbarMenuSelectProps> = withKeyboardCycle(
         ariaLabel={ariaLabel}
         tooltip={ariaLabel}
         resetLabel={resetLabel}
-        onReset={() => updateGlobals({ [id]: '_reset' })}
+        onReset={resetItem ? () => updateGlobals({ [id]: resetItem?.value }) : undefined}
```
Comment (Sidnioulz) [inline code/core/src/toolbar/components/ToolbarMenuSelect.tsx:101]: Thanks @mrginglymus! The conditional fix LGTM, I'll check the potential effects of setting undefined on URL query params and globals persistence as I suspect there was a reason why `_reset` was used.

Comment (Sidnioulz) [reply code/core/src/toolbar/components/ToolbarMenuSelect.tsx:101]: We do have a side effect that you can test on your monorepo.

If you reset the locale global, it lingers in the URL without a value: `http://localhost:6006/?path=/story/core-backgrounds-globals--set&globals=locale:`.

In contrast, the viewport global does not linger. That's because global toolbars' normalisation code forced the reset option to have a `''` value, which makes little sense. Global toolbar types do not allow for a default value, so we can safely set the reset item's value to `undefined`  for now (and change it to match any default value in the future).

I've pushed the relevant commit to your branch.

**Review by Sidnioulz — APPROVED** [review]

**Review by Sidnioulz — APPROVED** [review]
