### PR TITLE
Taking care of next/babel preset

### LINKED ISSUE #20087: [Bug]: Inconsistent propTypes handling between dev + build modes in NextJs
### Describe the bug

[JS arg types tests](https://www.chromatic.com/build?appId=634ff0454a50407deedde524&number=205) have changed the last 15 days on the `nextjs/default-js` sandbox, likely due to this PR: https://github.com/storybookjs/storybook/pull/19842

### To Reproduce

```shell
1. Checkout `next`
2. Run `yarn task --task dev --template nextjs/default-js`
3. Notice the story (http://localhost:6006/iframe.html?args=&id=renderers-react-js-argtypes--js-class-component) appears like the LHS of the Chromatic changes: https://www.chromatic.com/test?appId=634ff0454a50407deedde524&id=638be2c76de7967b8d2a22e6

4. Run `yarn task --task serve --template nextjs/default-js`
6. Notice the story (http://localhost:8001/iframe.html?args=&id=renderers-react-js-argtypes--js-class-component) appears like the RHS of the Chromatic changes: https://www.chromatic.com/test?appId=634ff0454a50407deedde524&id=638be2c76de7967b8d2a22e6
```

### Additional context

Debugging into the [`getPropDefs` function](https://github.com/storybookjs/storybook/blob/ee32804f5b69cc7a4f749c20a9403ee7f24aaf52/code/renderers/react/src/docs/extractProps.ts#L24) I'm pretty sure the difference is that the `component.propTypes` are stripped in build mode.

You can see this with (in the iframe console):

```js
c = __STORYBOOK_PREVIEW__.currentRender.storyContext()
c.parameters.component // <- no prop types in the build
```

It's clear they aren't there in the source code.

**dev**

image

**build**

image

### LINKED ISSUE #21027: [Bug]: @storybook/nextjs does not support satisfies
### Describe the bug

Yesterday I read about support for using `satisfies` in stories here: https://storybook.js.org/blog/improved-type-safety-in-storybook-7/

However, it does not work in the 7.0 beta 45 using `@storybook/nextjs` and generates a `babel` error:

```
File was processed with these loaders:
 * ./node_modules/.pnpm/@pmmmwh+react-refresh-webpack-plugin@0.5.10_ohj47mxwagpoxvu7nhhwxzphqm/node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
 * ./node_modules/.pnpm/babel-loader@9.1.2_la66t7xldg4uecmyawueag5wkm/node_modules/babel-loader/lib/index.js
 * ./node_modules/.pnpm/unplugin@0.10.2/node_modules/unplugin/dist/webpack/loaders/load.js
You may need an additional loader to handle the result of these loaders.
|   title: "Components/Alert",
|   component: Alert
> } satisfies Meta);
| export default meta;
| export var NoAction = {
```

I am using TS 4.9.5 and in my editor the code is not generating a TS error. In my demo the `components/Alert/Alert.stories.tsx` file looks like this:

```tsx
import { Meta, StoryObj } from "@storybook/react";
import { Alert } from ".";

const meta = {
  title: "Components/Alert",
  component: Alert,
} satisfies Meta<typeof Alert>;

export default meta;

type Story = StoryObj<typeof meta>;

export const NoAction: Story = {
  args: {
    label: "This is an alert without an action.",
  },
};
```

Note that `satisfies` works fine in the NextJS app itself.

### To Reproduce

```shell
git clone git@github.com:robcaldecott/next-tailwind.git -b storybook-7-beta-satisfies
cd next-tailwind
pnpm install
pnpm storybook
```

### System

```shell
System:
    OS: macOS 12.6.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Chrome: 110.0.5481.77
    Firefox: 109.0
    Safari: 16.1
  npmPackages:
    @storybook/addon-actions: ^7.0.0-beta.45 => 7.0.0-beta.45 
    @storybook/addon-essentials: ^7.0.0-beta.45 => 7.0.0-beta.45 
    @storybook/addon-interactions: ^7.0.0-beta.45 => 7.0.0-beta.45 
    @storybook/addon-links: ^7.0.0-beta.45 => 7.0.0-beta.45 
    @storybook/nextjs: 7.0.0-beta.45 => 7.0.0-beta.45 
    @storybook/react: ^7.0.0-beta.45 => 7.0.0-beta.45
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by valentinpalkovic**
Resolves https://github.com/storybookjs/storybook/issues/20087
Resolves https://github.com/storybookjs/storybook/issues/21027

## What I did:

Moved next/babel preset into codebase to be able to make changes, because it seems that `next/babel` will not be maintained anymore in favour of swc/Turbopack. Also:
- Fixed inconsistent propTypes handling between dev + build modes in NextJs.
- Removed precompiled `@babel/typescript-preset` package from next and use the latest one.

## Background:

The Next.js babel plugin `next/babel` behaves differently in `development` and `production` modes. It removes React propTypes in production, which is bad because Storybook relies on them to correctly infer the right argTypes. I opened a discussion [here](https://github.com/vercel/next.js/discussions/43757) at `@vercel/nextjs` to be able to conditionally still output the proptypes even for a production build. For almost two months nobody replied to this. I assume, that they will not work on any babel-related stuff, because the future at Next.js is Turbopack.

Essentially the `plugin-transform-react-remove-prop-types` plugin applied [here](https://github.com/vercel/next.js/blob/canary/packages/next/src/build/babel/preset.ts#L193) should not be applied on production. 

I tried different approaches: 

1. My first approach was flattening all plugins in `next/babel` preset and removing the superfluous `plugin-transform-react-remove-prop-types` plugin if it is present. The issue is that as soon as I want to look up the babel configuration, I cannot identify a plugin by a specific ID or name, because of how the plugins are set up in `next/babel` (direct require call).

2. The final approach I have decided on, and which was discussed with @shilman, was to actually copy `next/babel` and all of its dependencies to modify that one line and reference the modified `next/babel` preset instead. I really don't like this approach, but I can't think of another solution.

Therefore actually, only the changes in `code/frameworks/nextjs/src/preset.ts` matter. The other files are more or less copied over with some slight type adjustments.

## How to test

The chromatic changes introduced here
https://www.chromatic.com/build?appId=634ff0454a50407deedde524&number=205
should be reverted by
https://www.chromatic.com/build?appId=634ff0d0ec053b270775979d&number=2459

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [x] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [x] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by valentinpalkovic** [comment]
This PR would introduce a lot of maintenance overhead just to fix a small bug, which affects a very small group of users. Instead, we will mention a workaround in the FAQ section of Next.js docs

File: code/frameworks/nextjs/src/babel/plugins/commonjs.ts [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+  return {
+    visitor: {
+      Program: {
+        exit(path: NodePath<types.Program>, state) {
+          let foundModuleExports = false;
+          path.traverse({
+            MemberExpression(expressionPath: any) {
+              if (expressionPath.node.object.name !== 'module') return;
+              if (expressionPath.node.property.name !== 'exports') return;
+              foundModuleExports = true;
```
Comment (kasperpeulen) [inline code/frameworks/nextjs/src/babel/plugins/commonjs.ts:19]: Maybe add: `expressionPath.stop();`
for some small perf :)

File: code/frameworks/nextjs/src/babel/plugins/next-font-unsupported.ts [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+
+/**
+ * Source: https://github.com/vercel/next.js/blob/canary/packages/next/src/build/babel/plugins/next-font-unsupported.ts
+ */
+export default function NextPageDisallowReExportAllExports(): PluginObj<any> {
+  return {
+    visitor: {
+      ImportDeclaration(path: NodePath<types.ImportDeclaration>) {
+        if (['@next/font/local', '@next/font/google'].includes(path.node.source.value)) {
+          const err = new SyntaxError(
```
Comment (kasperpeulen) [inline code/frameworks/nextjs/src/babel/plugins/next-font-unsupported.ts:11]: throw path.buildCodeFrameError might be shorter to get an error message at the path

File: code/frameworks/nextjs/src/babel/plugins/next-page-config.ts [hunk 3]
```diff
@@ -0,0 +1,170 @@
...
+                          ? specifier.exported.name
+                          : specifier.exported.value) === CONFIG_KEY
+                      );
+                    }
+                  ) &&
+                  BabelTypes.isStringLiteral(
+                    (exportPath.node as BabelTypes.ExportNamedDeclaration).source
+                  )
+                ) {
+                  throw new Error(errorMessage(exportState, 'Expected object but got export from'));
```
Comment (kasperpeulen) [inline code/frameworks/nextjs/src/babel/plugins/next-page-config.ts:64]: path.buildCodeFrameError maybe again?

File: code/frameworks/nextjs/src/babel/plugins/next-font-unsupported.ts (hunk 2 above)
Comment (valentinpalkovic) [reply code/frameworks/nextjs/src/babel/plugins/next-font-unsupported.ts:11]: @kasperpeulen Do we want to change the code, which I copied from next in this PR, or should we do another one for performance improvements/cleanup?

**Review by kasperpeulen — APPROVED** [review]
Great!
