### PR TITLE
Test: Fix vitest patch to work with portable stories and upgrade testing-library/jest-dom

### LINKED ISSUE #25750: [Bug]: type imports in @storybook/test broken
### Describe the bug

With version > 6.2.0 of @testing-library/jest-dom the default exports for types have changed.

See https://github.com/testing-library/jest-dom/commit/5675b8668c09345e064001784338a85b7bf9f2af

This import https://github.com/storybookjs/storybook/blob/next/code/lib/test/src/expect.ts#L17 makes the type `Matchers<T>` resolve to `any`.

Pinning @testing-library/jest-dom in the project to `6.2.0` works.

### To Reproduce

_No response_

### System

```bash
Storybook Environment Info:

  System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12800H
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    pnpm: 8.12.1 - ~/.nvm/versions/node/v18.16.0/bin/pnpm <----- active
  npmPackages:
    @storybook/addon-essentials: 8.0.0-alpha.14 => 8.0.0-alpha.14
    @storybook/addon-interactions: 8.0.0-alpha.14 => 8.0.0-alpha.14
    @storybook/blocks: 8.0.0-alpha.14 => 8.0.0-alpha.14
    @storybook/jest: ^0.2.3 => 0.2.3
    @storybook/react: 8.0.0-alpha.14 => 8.0.0-alpha.14
    @storybook/react-vite: 8.0.0-alpha.14 => 8.0.0-alpha.14
    @storybook/test: 8.0.0-alpha.14 => 8.0.0-alpha.14
    @storybook/test-runner: 0.17.0-next.1 => 0.17.0-next.1
    @storybook/testing-library: ^0.2.2 => 0.2.2
    eslint-plugin-storybook: ^0.6.15 => 0.6.15
    storybook: 8.0.0-alpha.14 => 8.0.0-alpha.14
```

### Additional context

_No response_

### LINKED ISSUE #25794: [Bug]: Error when @storybook/test is used with portable stories
### Describe the bug

Filed in https://github.com/storybookjs/storybook/discussions/25690#discussioncomment-8234159

**Project:** MealDrop
**Version:** 8.0.0-alpha.10
**Bug/feedback:** 

When upgrading Storybook and running tests using portable stories (React), there's an error: `Object.defineProperty called on non-object`:

The issue seems to happen when `composeStories` is called on a story file that invokes anything from `@storybook/test`.
This issue was introduced in [alpha 10](https://github.com/storybookjs/storybook/releases/tag/v8.0.0-alpha.10), potentially from [this PR](https://github.com/storybookjs/storybook/pull/25576)

### To Reproduce

1. Access https://github.com/yannbf/mealdrop/tree/bug/portable-stories-expect
2. Run `yarn install` and `yarn test`

Here are the two places to focus on:
- [Test file](https://github.com/yannbf/mealdrop/blob/bug/portable-stories-expect/src/pages/RestaurantDetailPage/RestaurantDetailPage.test.tsx#L7)
- [Story file](https://github.com/yannbf/mealdrop/blob/bug/portable-stories-expect/src/pages/RestaurantDetailPage/RestaurantDetailPage.stories.tsx#L51)

### System

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kasperpeulen**
Fixes #25750
Fixes #25794
## What I did

Fix vitest patch to work with portable stories
And upgrade testing-library/jest-dom

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Review by yannbf — APPROVED** [review]
LGTM! How do we make sure issues with the patch won't happen again (so the patch needs to be revisited when vitest deps are upgraded)?

**Review by yannbf — APPROVED** [review]

**Comment by kasperpeulen** [comment]
@yannbf Added a test now for using storybook/test in vitest

File: code/lib/test/src/expect.ts [hunk 1]
```diff
@@ -16,9 +16,10 @@ import {
 } from '@vitest/expect';
 import * as matchers from '@testing-library/jest-dom/matchers';
 import type { PromisifyObject } from './utils';
+import type { TestingLibraryMatchers } from '@testing-library/jest-dom/types/matchers';
```
Comment (alitas) [inline code/lib/test/src/expect.ts:19]: This line seems to be translated as 
`import { TestingLibraryMatchers } from '@testing-library/jest-dom/types/matchers';` 
in `dist/index.d.ts`, which typescript can't parse right and causes it to be typed as `any`. 

Can you replace this with 
`import type { TestingLibraryMatchers } from '@testing-library/jest-dom/matchers'` 
by any chance?
