### PR TITLE
Preview: Treat canceled animations as finished

### LINKED ISSUE #32400: [Bug]: Animation `.cancel()` results in uncaught promise rejection of `AbortError: The user aborted a request.`
### Describe the bug

When upgrading from storybook@8.6.11 to storybook@9.1.0 (also tested with 9.1.4), we started to observe unhandled promise rejections with simply `AbortError: The user aborted a request.` and no stack trace to help pinpoint the problem. By adding some console logs I've narrowed it to the `animation.finished` promise here: https://github.com/storybookjs/storybook/blob/0db2a695a039d5b8725dfb8fb94b7be59258e151/code/core/src/preview-api/modules/preview-web/render/animation-utils.ts#L81

Seems like it stems from expected behavior of the `.cancel()` method per the docs on MDN: https://developer.mozilla.org/en-US/docs/Web/API/Animation/cancel

Seems like this `waitForAnimation` logic was added in #31287, fwiw.

Given the goal here is to wait for all animations to finish, it seems fine to treat canceled animations the same as successfully completed ones, i.e. rejected promises should be treated the same as resolved promises.

I don't have a minimal repro to hand, because it seems tricky to get the timing correct where we cancel an animation while we're waiting. But I can invest time into that if necessary.

### Reproduction link

example.com

### Reproduction steps

Per above there's no easy way to repro, but the issue itself seems clear enough.

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 15.6
    CPU: (10) arm64 Apple M1 Max
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 22.14.0 - ~/src/coda/build/node/bin/node
    npm: 10.9.2 - ~/src/coda/build/node/bin/npm
    pnpm: 10.12.4 - ~/src/coda/build/node/bin/pnpm <----- active
  Browsers:
    Chrome: 139.0.7258.157
    Safari: 18.6
  npmPackages:
    @storybook/addon-a11y: 9.1.0 => 9.1.0
    @storybook/react: 9.1.0 => 9.1.0
    @storybook/react-webpack5: 9.1.0 => 9.1.0
    chromatic: 13.1.4 => 13.1.4
    eslint-plugin-storybook: 9.1.0 => 9.1.0
    storybook: 9.1.0 => 9.1.0
```

### Additional context

I'm happy to put up a PR if this seems straightforward enough

### PR DESCRIPTION
**Pull request by bawjensen**
Closes #32400

## What I did

~Add a try/catch around `animation.finished` so we can treat canceled promises as finished, just the same as we'd treat successfully completed animations.~

Switch from `all` to `allSettled` so errored animations are treated as finished, just like successfully completed ones.

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

I believe this is simple enough to not warrant manual testing (also didn't do automated tests, above), given the trickiness of setting up a repro. But I'm certainly lacking context on storybook's testing setup, so I could easily be wrong.

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [x] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [x] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

## Summary by CodeRabbit

* **Bug Fixes**
  * Prevent animation cancellation errors from interrupting animation sequences — abort-related cancellations are treated as completed so they no longer surface as errors, while other errors still propagate.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Comment by Sidnioulz** [comment]
Thanks for your first PR, @bawjensen! Happy to see new faces!

You might be able to test this by adding an end-to-end test in `test-storybooks/portable-stories-kitchen-sink`, that runs tests on a story with a cancelled animation. You likely have a use case in your own code that prompted you to fix this. This use case could be transformed into the story for E2E testing.

Feel free to come find me on [Discord](https://discord.com/invite/storybook) if you want a showcase of how to run common commands, and how to set up those end-to-end tests. Any feedback you have on the documentation around contributing is also more than welcome.

**Comment by Sidnioulz** [comment]
@jonniebigodes I'm not super familiar with animations and interactions tests but I'm not finding relevant doc with naive searches. Should we have a brief mention of how animations are waited for in the interaction tests doc?

**Comment by jonniebigodes** [comment]
@Sidnioulz more than glad to get this documented as well, we can sync up on it and if @bawjensen has any questions, here to help him out and get him unblocked.

**Comment by Sidnioulz** [comment]
@bawjensen would you like to try and add an end-to-end test? The process to run E2E tests should look like that, roughly:

```sh
yarn task compile
cd test-storybooks/portable-stories-kitchen-sink/react/
yarn
# ensure localhost:6006 is up
yarn storybook
# in another tab
yarn playwright-e2e --headed
```

You can run Playwright in VSCode to record a new test, see https://playwright.dev/docs/codegen

**Comment by bryan-codaio** [comment]
@Sidnioulz yeah my intent is to try to create that test, just slow going as this hasn't been my main priority and then I went on vacation. Can't promise when I'll find time for it - but I appreciate the guidance!

**Comment by bawjensen** [comment]
@Sidnioulz yeah my intent is to try to create that test, just slow going as this hasn't been my main priority and then I went on vacation. Can't promise when I'll find time for it - but I appreciate the guidance!

**Comment by Sidnioulz** [comment]
> @Sidnioulz yeah my intent is to try to create that test, just slow going as this hasn't been my main priority and then I went on vacation. Can't promise when I'll find time for it - but I appreciate the guidance!

No worries! Contributions can spread over the course of a few months, we expect that and it's nothing to be ashamed of.

**Review by ghengeveld — COMMENTED** [review]
I think `Promise.all` should just be replaced with `Promise.allSettled`, as that is what we are trying to achieve here anyway (wait for _every_ animation to finish, not just the first one to throw). Alternatively, we could change `a.finished` to `a.finished.catch(() => {})`.

I don't think we need to re-throw in case of errors other than AbortError, it's fine to just catch any kind of error (realistically I don't expect anything other than AbortError).

**Comment by Sidnioulz** [comment]
> I think `Promise.all` should just be replaced with `Promise.allSettled`, as that is what we are trying to achieve here anyway (wait for _every_ animation to finish, not just the first one to throw). Alternatively, we could change `a.finished` to `a.finished.catch(() => {})`.
> 
> I don't think we need to re-throw in case of errors other than AbortError, it's fine to just catch any kind of error (realistically I don't expect anything other than AbortError).

I think it's ok as-is. Sure, the code would be simpler, but at the end of the day if there actually is another error, we'd be making it invisible by catching it and doing nothing with it. All we need is a test and we can merge this PR :)

**Comment by SimenB** [comment]
Any news on this one? Just stumbled across it, and it's quite annoying 😅

**Comment by Sidnioulz** [comment]
> Any news on this one? Just stumbled across it, and it's quite annoying 😅

We're waiting on an update to E2E tests from @bawjensen. Feel free to fork their PR and write the test though :) It'll speed things up!

File: code/core/src/preview-api/modules/preview-web/render/animation-utils.ts [hunk 1]
```diff
@@ -78,7 +78,18 @@ export async function waitForAnimations(signal?: AbortSignal) {
             .flatMap((el) => el?.getAnimations?.() || [])
             .filter((a) => a.playState === 'running' && !isInfiniteAnimation(a));
           if (runningAnimations.length > 0) {
-            await Promise.all(runningAnimations.map((a) => a.finished));
+            await Promise.all(
+              runningAnimations.map(async (a) => {
+                try {
+                  await a.finished;
+                } catch (err) {
+                  // Ignore AbortError from canceled animations, treat as "finished"
```
Comment (Sidnioulz) [inline code/core/src/preview-api/modules/preview-web/render/animation-utils.ts]:
```suggestion
                  // Ignore AbortError from canceled animations, treat as "finished"
                  // Those errors occur exclusively on CRA with React.StrictMode enabled.
```

**Review by Sidnioulz — APPROVED** [review]
I've spent a considerable amount of time reproducing this issue in our React sandboxes. It turns out it only occurs with CRA, and only when React.StrictMode wraps the code being run.

We don't currently have a CI pipeline for CRA, and our CRA sandbox is in a delicate state. Rebuilding CI for CRA is way out of scope for this PR and likely not something we want to consume CI credits for anyway.

In parallel, a user has independently confirmed the fix works, and so have I. So, I'm comfortable with not adding non-regression tests and merging as-is to unblock our CRA users.

@bawjensen thanks again for digging into this and finding a solution!

**Comment by bawjensen** [comment]
> I've spent a considerable amount of time reproducing this issue in our React sandboxes. It turns out it only occurs with CRA, and only when React.StrictMode wraps the code being run.
> 
> [...]

@Sidnioulz fwiw my original repro is a quite complex web app unrelated to CRA. Our setup does have `<StrictMode />` in storybook though

**Comment by Sidnioulz** [comment]
> > I've spent a considerable amount of time reproducing this issue in our React sandboxes. It turns out it only occurs with CRA, and only when React.StrictMode wraps the code being run.
> > [...]
> 
> @Sidnioulz fwiw my original repro is a quite complex web app unrelated to CRA. Our setup does have `<StrictMode />` in storybook though

Were you using Webpack as well?

I tried NextJS with Webpack and Vite and could only repro on CRA. I haven't tried rspack though.

**Comment by bawjensen** [comment]
> Were you using Webpack as well?
> 
> I tried NextJS with Webpack and Vite and could only repro on CRA. I haven't tried rspack though.

webpack, yeah. Not next.js, though

sadly I don't know that I can set up a minimal repro, it'd take a decent amount of effort to pare down our webpack setup to figure out what's causing it to happen when it didn't with your testing

**Comment by Sidnioulz** [comment]
> > Were you using Webpack as well?
> > I tried NextJS with Webpack and Vite and could only repro on CRA. I haven't tried rspack though.
> 
> webpack, yeah. Not next.js, though
> 
> sadly I don't know that I can set up a minimal repro, it'd take a decent amount of effort to pare down our webpack setup to figure out what's causing it to happen when it didn't with your testing

It's okay. The environment where we reliably see the bug is outside the scope of our CI anyway! Thanks again!

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
I agree that Promise.allSettled use would be a bit better, but I find the PR mergable as-is.

If @bawjensen (or someone else) wants to improve things further with the above suggestion, that would be very welcome.

**Comment by bawjensen** [comment]
> I agree that Promise.allSettled use would be a bit better, but I find the PR mergable as-is.
> 
> If @bawjensen (or someone else) wants to improve things further with the above suggestion, that would be very welcome.

@ndelangen done ✅
