### PR TITLE
UI: Fix Copy button overlapping code in portrait mode

### LINKED ISSUE #23642: Code and the Copy button under Common Navigation with custom bottom slot and Common Navigation with custom mid slot are getting slightly overlapped in orientation-portrait mode.
### Describe the bug

Code and the Copy button under Common Navigation with custom bottom slot and Common Navigation with custom mid slot are getting slightly overlapped in orientation-portrait mode.

Severity: Usable

### To Reproduce

**Pre- Requisites:** 
Settings-->Display-->Display orientation-->Portrait.

**Repro Steps:** 
Open URL: “[Overview - Docs ⋅ Storybook (windows.net)](https://vivacommonstorybooktest.blob.core.windows.net/$web/index.html?path=/docs/overview--docs)” and sign in with valid credentials. 
In left navigation select “components button for Common Navigation Drop Down select Common Navigation” and invoke it.  
Now Apply Orientation in portrait mode and observe the page.
Verify whether the code and copy button are overlapping slightly or not.

### System

```shell
Environmental details:  
Windows: Win11 Enterprise
OS: Version 22H2 (OS Build 22621.1992) 
Edge Version: Version 114.0.1823.51 (Official build) (64-bit) 
URL: Overview - Docs ⋅ Storybook (windows.net)
```

### Additional context

Expected Result:
Code and the Copy button under Common Navigation with custom bottom slot and Common Navigation with custom mid slot should not get overlapped in orientation-portrait mode.

Attachments are added
Normal mode:
Normal mode (1)

After applying orientation:
Orienation mode

### PR DESCRIPTION
**Pull request by Maelryn**
Closes #23642

## What I did

I increased the `paddingRight` in the `SyntaxHighlighter` component to `85px`.
This prevents the code text from running under the absolute positioned "Copy" button when viewing in mobile/portrait modes.

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

- [x] Manual testing

1. Open Storybook in a mobile viewport (Portrait mode).
2. Go to any story that displays a code snippet with the Copy button.
3. Verify that the long lines of code now wrap before hitting the Copy button.

## Summary by CodeRabbit

* **Style**
  * Improved code block layout and text wrapping with enhanced spacing
  * Refined copy button positioning for better accessibility
  * Optimized preview component sizing and content flow constraints

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Review by Sidnioulz — CHANGES_REQUESTED** [review]
Thanks for your PR @Maelryn!

I don't think the proposed fix is going in the right direction, because:
* A large padding removes useful space from the `pre` area, making it harder to read code snippets without scrolling, especially in portrait mode
* The value is arbitrary and will not account for future changes in copy or for font size zoom settings

Instead of reserving space horizontally, I'd like the ActionBar div to reserve space vertically whenever there isn't enough room for both the ActionBar and the content.

This can be done with a `flex` layout on the parent of the `pre` and `ActionBar`, flex wrapping, and `fit-content` width across all divs/pres in the `pre` block with the `ScrollArea`.

I've put together a diff to get you started:

```diff
diff --git a/code/core/src/components/components/ToggleButton/ToggleButton.stories.tsx b/code/core/src/components/components/ToggleButton/ToggleButton.stories.tsx
index c1245b23274..38d821df485 100644
--- a/code/core/src/components/components/ToggleButton/ToggleButton.stories.tsx
+++ b/code/core/src/components/components/ToggleButton/ToggleButton.stories.tsx
@@ -10,6 +10,7 @@ const meta = {
   title: 'ToggleButton',
   component: ToggleButton,
   tags: ['autodocs'],
+  parameters: { layout: 'fullscreen' },
   args: { ariaLabel: false, children: 'Click me' },
 } satisfies Meta<typeof ToggleButton>;
 
diff --git a/code/core/src/components/components/syntaxhighlighter/syntaxhighlighter.tsx b/code/core/src/components/components/syntaxhighlighter/syntaxhighlighter.tsx
index 58286cec773..2451eba1b3b 100644
--- a/code/core/src/components/components/syntaxhighlighter/syntaxhighlighter.tsx
+++ b/code/core/src/components/components/syntaxhighlighter/syntaxhighlighter.tsx
@@ -69,6 +69,9 @@ const Wrapper = styled.div<WrapperProps>(
   ({ theme }) => ({
     position: 'relative',
     overflow: 'hidden',
+    display: 'flex',
+    display: 'flex',
+    flexWrap: 'wrap',
+    gap: theme.layoutMargin,
     color: theme.color.defaultText,
   }),
   ({ theme, bordered }) =>
@@ -98,6 +101,13 @@ const UnstyledScroller = ({ children, className }: ScrollAreaProps) => (
 const Scroller = styled(UnstyledScroller)(
   {
     position: 'relative',
+    width: 'fit-content',
+    '> div': {
+      width: 'fit-content',
+      '> div > pre': {
+        width: 'fit-content',
+      },
+    },
   },
   ({ theme }) => themedSyntax(theme)
 );
@@ -125,6 +135,12 @@ const Code = styled.div(({ theme }) => ({
   fontFamily: theme.typography.fonts.mono,
 }));
 
+const RelativeActionBar = styled(ActionBar)({
+  position: 'relative',
+  marginLeft: 'auto',
+  alignSelf: 'flex-end',
+});
+
 const processLineNumber = (row: any) => {
   const children = [...row.children];
   const lineNumberNode = children[0];
@@ -247,7 +263,7 @@ export const SyntaxHighlighter = ({
       </Scroller>
 
       {copyable ? (
-        <ActionBar actionItems={[{ title: copied ? 'Copied' : 'Copy', onClick }]} />
+        <RelativeActionBar actionItems={[{ title: copied ? 'Copied' : 'Copy', onClick }]} />
       ) : null}
     </Wrapper>
```

Note that I forced one story to use a `fullscreen` layout as it helps spot the bug. The same logic would need to be applied to other code paths that use ActionBar, e.g.:
* `code/addons/docs/src/blocks/components/Preview.tsx` (for this issue, that should be the "Code" button)
* `addons/vitest/src/components/GlobalErrorModal.tsx` (bonus)
* `core/src/actions/components/ActionLogger/index.tsx` (bonus)

Ideally, I'd like `ActionBar` to _not_ have absolute positioning (cc @MichaelArestad in case you have planned a long-term replacement for that UI pattern). But if we want to change the positioning from absolute to relative, we'll also need to
* Wait for Storybook 11 to release the PR
* Add a note in the MIGRATION.md file
* Update addons that use ActionBar, such as the Jest addon

**Comment by Maelryn** [comment]
@Sidnioulz Thanks for the snippet!
I have applied the changes to syntaxhighlighter.tsx and ToggleButton.stories.tsx (and I restored the line-number logic that was accidentally removed in the previous commit).
Regarding applying this fix to Preview.tsx and the other files:
Currently, RelativeActionBar is defined locally inside syntaxhighlighter.tsx.
Question: To avoid code duplication, would you prefer I export RelativeActionBar from a shared location (like components/src/ActionBar), or should I just duplicate the styled component definition in the other files for now?

**Comment by Sidnioulz** [comment]
> Regarding applying this fix to Preview.tsx and the other files: Currently, RelativeActionBar is defined locally inside syntaxhighlighter.tsx. Question: To avoid code duplication, would you prefer I export RelativeActionBar from a shared location (like components/src/ActionBar), or should I just duplicate the styled component definition in the other files for now?

I prefer if you duplicate the fix for now. We know we'll review some of those patterns soon so any shared component would be short-lived. Besides, there are side effects when we moved components to different folders in `code/core/src`. Each of these sub-folders is its own package, so moving code into the `components` package makes it a public API that we then must maintain.

**Comment by Maelryn** [comment]
@Sidnioulz Thanks for the clarification!
I have duplicated the RelativeActionBar and flex-layout fix into Preview.tsx as requested.
regarding the "bonus" files (GlobalErrorModal and ActionLogger):
I investigated them, but since GlobalErrorModal uses a custom implementation and ActionLogger has strict fixed-height scrolling constraints, I decided to skip them for now to avoid accidental layout regressions in those complex components.
I believe the PR covers the main issue now, but let me know if you spot anything else!

**Comment by Sidnioulz** [comment]
I can't quite find what's missing compared to when I hacked something in my previous review and sent you a diff, but I still see the same overlap when checking out your branch. How does it look on your end?

**Comment by MichaelArestad** [comment]
This solution is looking good. Thanks for tackling it!

**Comment by Maelryn** [comment]
@Sidnioulz That's strange! It looks fixed on my end. I just updated the branch to make sure everything is fresh does it look any better for you now?

**Comment by Sidnioulz** [comment]
> @Sidnioulz That's strange! It looks fixed on my end. I just updated the branch to make sure everything is fresh does it look any better for you now?

It seems like it was a build cache issue, all good now! But we've broken the horizontal scroll area in the process of fixing the overlap. :(

File: code/core/src/components/components/syntaxhighlighter/syntaxhighlighter.tsx [hunk 1]
```diff
@@ -113,42 +122,36 @@ const Pre = styled.pre<PreProps>(({ theme, padded }) => ({
...
+  alignSelf: 'flex-end',
+});
+
 const processLineNumber = (row: any) => {
   const children = [...row.children];
   const lineNumberNode = children[0];
   const lineNumber = lineNumberNode.children[0].value;
   const processedLineNumberNode = {
     ...lineNumberNode,
-    // empty the line-number element
```
Comment (Sidnioulz) [inline code/core/src/components/components/syntaxhighlighter/syntaxhighlighter.tsx:134]: Could you please restore all those removed comments?

File: code/core/src/components/components/syntaxhighlighter/syntaxhighlighter.tsx [hunk 2]
```diff
@@ -98,6 +100,13 @@ const UnstyledScroller = ({ children, className }: ScrollAreaProps) => (
 const Scroller = styled(UnstyledScroller)(
   {
     position: 'relative',
+    width: 'fit-content',
+    '> div': {
+      width: 'fit-content',
+      '> div > pre': {
+        width: 'fit-content',
+      },
+    },
```
Comment (Sidnioulz) [inline code/core/src/components/components/syntaxhighlighter/syntaxhighlighter.tsx:113]:
```suggestion
    width: 'fit-content',
    maxWidth: '100%',
    '> div': {
      width: 'fit-content',
      maxWidth: '100%',
      '> div > pre': {
        width: 'fit-content',
        maxWidth: '100%',
      },
    },
```

This should take us closer to the finish line. The content of the scroll area needs to have a max width to ensure ScrollArea works.

By the way, we'll need to check for regressions everywhere else where syntaxhighlighter is used:
* code/addons/docs/src/blocks/blocks/SourceContainer.tsx
* code/addons/docs/src/blocks/components/Source.tsx
* code/addons/docs/src/blocks/components/ArgsTable/ArgValue.tsx
* code/addons/a11y/src/components/Report/Details.tsx
* code/addons/onboarding/src/Onboarding.tsx
* code/core/src/shared/checklist-store/checklistData.tsx

**Comment by Maelryn** [comment]
@Sidnioulz Thanks for catching that!

1. I've applied the maxWidth: '100%' fix to the Scroller and its children to ensure horizontal scrolling works correctly.
2. I've restored the missing comments in processLineNumber.

Since this fix is applied directly to the SyntaxHighlighter component, it should propagate to the other files you listed (like SourceContainer, ArgValue, etc.) automatically.

File: code/addons/docs/src/blocks/components/Preview.tsx [hunk 3]
```diff
@@ -172,15 +173,20 @@ const PositionedToolbar = styled(Toolbar)({
...
+  display: 'flex',
+  flexWrap: 'wrap',
+  gap: theme.layoutMargin,
+}));
+
+const RelativeActionBar = styled(ActionBar)({
+  position: 'relative',
+  marginLeft: 'auto',
+  alignSelf: 'flex-end',
 });
```
Comment (Sidnioulz) [inline code/addons/docs/src/blocks/components/Preview.tsx:189]:
```suggestion

/**
 * A preview component for showing one or more component `Story` items. The preview also shows the
 * source for the component as a drop-down.
 */
```

File: code/core/src/components/components/ToggleButton/ToggleButton.stories.tsx [hunk 4]
```diff
@@ -10,6 +10,7 @@ const meta = {
   title: 'ToggleButton',
   component: ToggleButton,
   tags: ['autodocs'],
+  parameters: { layout: 'fullscreen' },
```
Comment (Sidnioulz) [inline code/core/src/components/components/ToggleButton/ToggleButton.stories.tsx]:
```suggestion
```

File: code/core/src/components/components/syntaxhighlighter/syntaxhighlighter.tsx [hunk 5]
```diff
@@ -178,8 +186,6 @@ export interface SyntaxHighlighterState {
   copied: boolean;
 }
 
-// copied from @types/react-syntax-highlighter/index.d.ts
-
 export const SyntaxHighlighter = ({
```
Comment (Sidnioulz) [inline code/core/src/components/components/syntaxhighlighter/syntaxhighlighter.tsx:201]:
```suggestion
// copied from @types/react-syntax-highlighter/index.d.ts

export const SyntaxHighlighter = ({
```

File: code/core/src/components/components/syntaxhighlighter/syntaxhighlighter.tsx [hunk 6]
```diff
@@ -113,42 +125,38 @@ const Pre = styled.pre<PreProps>(({ theme, padded }) => ({
...
   };
   children[0] = processedLineNumberNode;
   return { ...row, children };
 };
 
-/**
- * A custom renderer for handling `span.linenumber` element in each line of code, which is enabled
- * by default if no renderer is passed in from the parent component
- */
 const defaultRenderer: SyntaxHighlighterRenderer = ({ rows, stylesheet, useInlineStyles }) => {
```
Comment (Sidnioulz) [inline code/core/src/components/components/syntaxhighlighter/syntaxhighlighter.tsx:170]:
```suggestion
/**
 * A custom renderer for handling `span.linenumber` element in each line of code, which is enabled
 * by default if no renderer is passed in from the parent component
 */
const defaultRenderer: SyntaxHighlighterRenderer = ({ rows, stylesheet, useInlineStyles }) => {
```

File: code/core/src/components/components/syntaxhighlighter/syntaxhighlighter.tsx [hunk 7]
```diff
@@ -113,42 +125,38 @@ const Pre = styled.pre<PreProps>(({ theme, padded }) => ({
...
   const lineNumber = lineNumberNode.children[0].value;
   const processedLineNumberNode = {
     ...lineNumberNode,
-    // empty the line-number element
     children: [],
+    // empty the line-number element
     properties: {
       ...lineNumberNode.properties,
-      // add a data-line-number attribute to line-number element, so we can access the line number with `content: attr(data-line-number)`
       'data-line-number': lineNumber,
```
Comment (Sidnioulz) [inline code/core/src/components/components/syntaxhighlighter/syntaxhighlighter.tsx:157]:
```suggestion
      // add a data-line-number attribute to line-number element, so we can access the line number with `content: attr(data-line-number)`
      'data-line-number': lineNumber,
```

File: code/core/src/components/components/syntaxhighlighter/syntaxhighlighter.tsx [hunk 8]
```diff
@@ -113,42 +125,38 @@ const Pre = styled.pre<PreProps>(({ theme, padded }) => ({
...
-      // remove the 'userSelect: none' style, which will produce extra empty lines when copy-pasting in firefox
+      // remove the userSelect: none style, which will produce extra empty lines when copy-pasting in firefox
```
Comment (Sidnioulz) [inline code/core/src/components/components/syntaxhighlighter/syntaxhighlighter.tsx]:
```suggestion
      // remove the 'userSelect: none' style, which will produce extra empty lines when copy-pasting in firefox
```

File: code/core/src/components/components/syntaxhighlighter/syntaxhighlighter.tsx [hunk 9]
```diff
@@ -113,42 +125,38 @@ const Pre = styled.pre<PreProps>(({ theme, padded }) => ({
...
+
 const processLineNumber = (row: any) => {
   const children = [...row.children];
   const lineNumberNode = children[0];
   const lineNumber = lineNumberNode.children[0].value;
   const processedLineNumberNode = {
     ...lineNumberNode,
-    // empty the line-number element
     children: [],
+    // empty the line-number element
```
Comment (Sidnioulz) [inline code/core/src/components/components/syntaxhighlighter/syntaxhighlighter.tsx:152]:
```suggestion
```

File: code/core/src/components/components/syntaxhighlighter/syntaxhighlighter.tsx [hunk 10]
```diff
@@ -113,42 +125,38 @@ const Pre = styled.pre<PreProps>(({ theme, padded }) => ({
...
+});
+
 const processLineNumber = (row: any) => {
   const children = [...row.children];
   const lineNumberNode = children[0];
   const lineNumber = lineNumberNode.children[0].value;
   const processedLineNumberNode = {
     ...lineNumberNode,
-    // empty the line-number element
     children: [],
```
Comment (Sidnioulz) [inline code/core/src/components/components/syntaxhighlighter/syntaxhighlighter.tsx]:
```suggestion
    // empty the line-number element
    children: [],
```

File: code/core/src/components/components/syntaxhighlighter/syntaxhighlighter.tsx [hunk 11]
```diff
@@ -113,42 +125,38 @@ const Pre = styled.pre<PreProps>(({ theme, padded }) => ({
   padding: padded ? theme.layoutMargin : 0,
 }));
 
-/*
-We can't use `code` since PrismJS races for it.
-See https://github.com/storybookjs/storybook/issues/18090
- */
 const Code = styled.div(({ theme }) => ({
```
Comment (Sidnioulz) [inline code/core/src/components/components/syntaxhighlighter/syntaxhighlighter.tsx:133]:
```suggestion
/*
We can't use `code` since PrismJS races for it.
See https://github.com/storybookjs/storybook/issues/18090
 */
const Code = styled.div(({ theme }) => ({
```

File: code/core/src/components/components/syntaxhighlighter/syntaxhighlighter.tsx [hunk 12]
```diff
@@ -113,42 +125,38 @@ const Pre = styled.pre<PreProps>(({ theme, padded }) => ({
...
   flex: 1,
-  paddingLeft: 2, // TODO: To match theming/global.ts for now
-  paddingRight: theme.layoutMargin,
+  paddingLeft: 2,
```
Comment (Sidnioulz) [inline code/core/src/components/components/syntaxhighlighter/syntaxhighlighter.tsx]:
```suggestion
  paddingLeft: 2, // TODO: To match theming/global.ts for now
```

File: code/core/src/components/components/syntaxhighlighter/syntaxhighlighter.tsx [hunk 13]
```diff
@@ -82,7 +85,6 @@ const Wrapper = styled.div<WrapperProps>(
   ({ showLineNumbers }) =>
     showLineNumbers
       ? {
-          // use the before pseudo element to display line numbers
           '.react-syntax-highlighter-line-number::before': {
```
Comment (Sidnioulz) [inline code/core/src/components/components/syntaxhighlighter/syntaxhighlighter.tsx:89]:
```suggestion
          // use the before pseudo element to display line numbers
          '.react-syntax-highlighter-line-number::before': {
```

File: code/addons/docs/src/blocks/components/Preview.tsx [hunk 14]
```diff
@@ -172,15 +173,20 @@ const PositionedToolbar = styled(Toolbar)({
...
 
-/**
- * A preview component for showing one or more component `Story` items. The preview also shows the
- * source for the component as a drop-down.
- */
 export const Preview: FC<PreviewProps> = ({
```
Comment (Sidnioulz) [inline code/addons/docs/src/blocks/components/Preview.tsx:194]:
```suggestion
/**
 * A preview component for showing one or more component `Story` items. The preview also shows the
 * source for the component as a drop-down.
 */
export const Preview: FC<PreviewProps> = ({
```

File: code/addons/docs/src/blocks/components/Preview.tsx [hunk 15]
```diff
@@ -172,11 +173,24 @@ const PositionedToolbar = styled(Toolbar)({
...
+const RelativeActionBar = styled(ActionBar)({
+  position: 'relative',
+  marginLeft: 'auto',
+  alignSelf: 'flex-end',
 });
 
+/**
+ * A preview component for showing one or more component `Story` items. The preview also shows the
+ * source for the component as a drop-down.
+ */
```
Comment (Sidnioulz) [inline code/addons/docs/src/blocks/components/Preview.tsx]:
```suggestion
```

File: code/core/src/components/components/syntaxhighlighter/syntaxhighlighter.tsx [hunk 16]
```diff
@@ -133,11 +151,13 @@ const processLineNumber = (row: any) => {
     ...lineNumberNode,
     // empty the line-number element
     children: [],
+    // empty the line-number element
     properties: {
       ...lineNumberNode.properties,
       // add a data-line-number attribute to line-number element, so we can access the line number with `content: attr(data-line-number)`
+      // add a data-line-number attribute to line-number element, so we can access the line number with `content: attr(data-line-number)`
```
Comment (Sidnioulz) [inline code/core/src/components/components/syntaxhighlighter/syntaxhighlighter.tsx]:
```suggestion
```

File: code/addons/docs/src/blocks/components/Preview.tsx (hunk 15 above)
Comment (Sidnioulz) [inline code/addons/docs/src/blocks/components/Preview.tsx]:
```suggestion
```

**Comment by Maelryn** [comment]
@Sidnioulz Hey! Just checking in on this since it's been a week.
I saw you applied the final cleanups and suggestions last week (thank you for doing that!) I've kept the branch updated to ensure no conflicts.
I noticed some checks are failing (like portable-react and vue-v3), but looking at the logs, they seem to be timeouts unrelated to the CSS changes here.
Is there anything else i need to do ?

**Review by Sidnioulz — APPROVED** [review]
@valentinpalkovic can I please let you take over? I think it'd be safe to do a runtime sanity check prior to merging. Thanks!
