### PR TITLE
Vue3: Fix source decorator to generate correct story code 

### LINKED ISSUE #21129: [Bug]: vue3 story sourcecode does not reflect the preview
### Describe the bug

In **vue3** + Storybook **7.0.0-beta.48** context (edit : same issue with beta 51)

When we declare a story with static properties, and without any args, the sourcecode is not rendering correctly (preview is fine though) : 

- static properties are not rendered
- slots are not rendered

Simple example with a Button component, having multiple variants that I need to display in one story : 

```
export const Variants = {
    render: (args) => ({
        components: { MyButton },
        setup() {
            return {
                args,
            }
        },
        template: `
            <MyButton variant="primary">Primary</MyButton>  
            <MyButton variant="secondary">Secondary</MyButton>  
        `,
    }),
}
```

Generated sourcecode : 
```
<MyButton />
<MyButton />  
```

I have a different behavior when I declare the slot like so : 

```
export const Variants = {
    render: (args) => ({
        components: { MyButton },
        setup() {
            return {
                args,
            }
        },
        template: `
            <MyButton variant="primary">{{args.defaultSlot}}</MyButton>  
            <MyButton variant="secondary">{{args.defaultSlot}}</MyButton>  
        `,
    }),
    args: {
        defaultSlot: 'Button',
    }
}
```

Generated sourcecode : 
```
<MyButton variant="primary" />
<MyButton variant="secondary" />  
```

This time the **variant** property is correctly displayed, but still not for the slot.

### To Reproduce

https://github.com/KevinCarnaille2/sb-vue3-sourcecode-issue

_No response_

### System

```shell
Environment Info:
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
  npmPackages:
    @storybook/addon-docs: 7.0.0-beta.48 => 7.0.0-beta.48 
    @storybook/addon-essentials: 7.0.0-beta.48 => 7.0.0-beta.48 
    @storybook/addon-interactions: 7.0.0-beta.48 => 7.0.0-beta.48 
    @storybook/addon-links: 7.0.0-beta.48 => 7.0.0-beta.48 
    @storybook/addons: 7.0.0-beta.48 => 7.0.0-beta.48 
    @storybook/channel-postmessage: 7.0.0-beta.48 => 7.0.0-beta.48 
    @storybook/channel-websocket: 7.0.0-beta.48 => 7.0.0-beta.48 
    @storybook/client-api: 7.0.0-beta.48 => 7.0.0-beta.48 
    @storybook/preview-web: 7.0.0-beta.48 => 7.0.0-beta.48 
    @storybook/testing-library: 0.0.13 => 0.0.13 
    @storybook/vue3: 7.0.0-beta.48 => 7.0.0-beta.48 
    @storybook/vue3-vite: 7.0.0-beta.48 => 7.0.0-beta.48
```

### Additional context

_No response_

### LINKED ISSUE #21424: [Bug]: Unexpected closing tag on story
### Describe the bug

The [Stack.Recursive](https://github.com/RCVarley/unexpected-closing-tag-error/blob/main/src/stories/ElStack.stories.ts story produces the error:

> SyntaxError: Unexpected closing tag "div". It may happen when the tag has already been closed by another tag.

```js
template: `
    <ElStack v-bind="args" style="min-height: 20rem">
        <div>This</div>
        <div>is</div>
        <div>
            <div>a</div>
            <div>recursive</div>
        </div>
        <div>stack</div>
    </ElStack>`
```

The issue is with the nested div.

### To Reproduce

Nest divs (or any other element) in a story template and view the story.

https://github.com/RCVarley/unexpected-closing-tag-error/blob/main/src/stories/ElStack.stories.ts

### System

```shell
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Safari: 16.3
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.61 => 7.0.0-beta.61 
    @storybook/addon-interactions: ^7.0.0-beta.61 => 7.0.0-beta.61 
    @storybook/addon-links: ^7.0.0-beta.61 => 7.0.0-beta.61 
    @storybook/blocks: ^7.0.0-beta.61 => 7.0.0-beta.61 
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1 
    @storybook/vue3: ^7.0.0-beta.61 => 7.0.0-beta.61 
    @storybook/vue3-vite: ^7.0.0-beta.61 => 7.0.0-beta.61
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by chakAs3**
Closes:  #21129
Closes:  #21424

## What I did

the source decorator snippet on the docs was not generating the complete and correct source code in a. complex  custom template.

i rewrote the code based on the vue-compiler to get better result.  now users can pick the snippet from docs block and use it in their project.  

image

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by aranoe** [comment]
This looks so much better than the current source code examples. I was really waiting for something like this! 

Allowing to show muiltiple components in one story is very important and a common practise.

**Comment by chakAs3** [comment]
> This looks so much better than the current source code examples. I was really waiting for something like this!
> 
> Allowing to show muiltiple components in one story is very important and a common practise.

I agree that is good practice to build components faster, in your Story with custom render , you really use Vue to build what you want not only the component that you want to document

**Comment by oemer-aran** [comment]
Is anything blocking the merge for this? Really looking forward to this change, as this is the only thing that is broken in the new storybook v7 for me 🙏

**Comment by chakAs3** [comment]
> Is anything blocking the merge for this? Really looking forward to this change, as this is the only thing that is broken in the new storybook v7 for me 🙏

@shilman  can someone review this PR to merge, it is an old one.

File: code/renderers/vue3/src/docs/sourceDecorator.ts [hunk 1]
```diff
@@ -176,141 +187,133 @@ function getTemplates(renderFn: any): [] {
...
+  watch(
+    () => context.args,
+    () => {
+      if (!skip) {
+        generateSource(context);
+      }
+    },
+    { immediate: true, deep: true }
+  );
+  return story;
```
Comment (kasperpeulen) [inline code/renderers/vue3/src/docs/sourceDecorator.ts:292]: Shouldn't we do something like:
```ts
() => {
  const story = storyFn();
  watch(
    () => context.args,
    () => {
      if (!skip) {
        generateSource(context);
      }
    },
    { immediate: true, deep: true }
  );
  return story;
};
```

I mean returning a functional component, instead of directly calling the storyFn?

**Review by kasperpeulen — APPROVED** [review]
LGTM and thanks 🚀

**Comment by ReactiveCoderHK** [comment]
finally it is merged !! i have been dying for this 💌  thanks @kasperpeulen and @chakAs3 for your great work 👍 👍

**Comment by fouss** [comment]
I just test it, but it replace all props by just an object as "v-bind", is it really wanted ? because I think no one write vue props like that

**Comment by chakAs3** [comment]
@fouss did you use the v-bind directive in your custom story?

**Comment by chakAs3** [comment]
we just transpile  what you write in your story template so if you use a v-bind directive it will be reflected the same in the source code, and this is a working code that you can copy and past into your app

**Comment by fouss** [comment]
@chakAs3 yes i made a script to automatically generate my props and values from my component props & default values, so my stories look like that : 
```
export const Playground: Story = {
  name: 'Default',
  render: args => ({
    components: { UIButton },
    setup() {
      return {
        args,
      }
    },
    template: '<UIButton v-bind="args" />',
  }),
}
setDefaultProps(Playground, UIButton)
```

**Comment by chakAs3** [comment]
Yes I got the idea, I know that v-bind used just as utility to bind all the props, and this is not the case in real App, you can open a request to spread the props in source, but it is not sure that will be the intent of everyone, there is use-case where you can use v-bind to spread all props and add specific prop to override its value, In both case the result is same. In my initial code I was spreading the props separately. Let me know if you really need this so I can address this in next PR, with any other feedback or bug that spotted.!

**Comment by kasperpeulen** [comment]
@fouss What if you use the implicit render function?


```ts
export default {
  component: UIButton,
}

export const Playground: Story = {
  name: 'Default'
}
```

**Comment by rstainsby** [comment]
Thank you for these changes, they fix a lot of the issues I was facing.

Unfortunately, they seem to have broken some of my code snippets (tested in 7.1.0-alpha.42). 

I have the following story:

```
export const IconOnly: Story = {
  ...Default,
  args: {
    icon: 'pi pi-check'
  }
}
```

which outputs this code snippet:
```
<template>
  <Button icon="()=>({})" />
</template>
```

where, in previous versions, it output:
```
<template>
  <Button icon="pi pi-check"/>
</template>
```

I am using Storybook with Vue 3 and PrimeVue component library.

This is happening with the use of the Button component which has an 'icon' prop and an 'icon' slot. If I were to take a guess I'd think that the slot and prop having the same name is causing the problem.

Here's the API for the component https://primevue.org/button/.

**Comment by chakAs3** [comment]
> I'd think that the slot and prop having the same name is causing the problem.

Yes, you are right I'm working on solving this issue, by separating props from slots, I will get back to you. you once I figured out some solution

**Comment by rstainsby** [comment]
Thanks @chakAs3, is there an open issue for this that I can follow?

**Comment by chakAs3** [comment]
> Thanks @chakAs3, is there an open issue for this that I can follow?

there is a long discussion about this internally with the team I may create an RFC for this in case we have to change our API.
If there is an issue addressing this I will tag your in both of them

**Comment by JReinhold** [comment]
@rstainsby can you file a bug report for this, with a reproduction? Makes it easier for us to track it and not forget about it.
