### PR TITLE
Vite: Don't prefix story import with `@fs`

### LINKED ISSUE #103: "Do not know how to load path" error in Storybook 8
Is this addon compatible with Storybook 8? I upgraded and am getting:

```
Failed to scan for dependencies from entries:
  [path]/src/stories/Demo.stories.vue

  ✘ [ERROR] Do not know how to load path: html:[path]/src/stories/Demo.stories.vue?vue&type=stories
```

### PR DESCRIPTION
**Pull request by tobiasdiez**
Closes https://github.com/tobiasdiez/storybook-vue-addon/issues/103

## What I did

Currently, the generated imports in `storybook-stories.js` use the prefix `@fs`. This prefix is generally used by vite to mark certain imports at the end of the resolution (eg files that outside of the root dir). Adding the prefix already at the beginning yields problems when plugins are modifying the story import resolution (which is the case for the vue plugin).

This is fixed by simplying using the full absolute path of the story (after normalizing Windows paths). 

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [x] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

| name | before | after | diff | z | % |
| ---- | ------ | ----- | ---- | - | - |
| createSize |  0 B | 0 B | 0 B | - | - |
| generateSize |  77.7 MB | 77.7 MB | -3 B | 1.21 | 0% |
| initSize |  130 MB | 130 MB | 10.5 kB | -0.41 | 0% |
| diffSize |  52.5 MB | 52.5 MB | 10.5 kB | -0.41 | 0% |
| buildSize |  6.83 MB | 6.83 MB | -14 B | 0.3 | 0% |
| buildSbAddonsSize |  1.51 MB | 1.51 MB | 0 B | -0.5 | 0% |
| buildSbCommonSize |  195 kB | 195 kB | 0 B | - | 0% |
| buildSbManagerSize |  1.86 MB | 1.86 MB | 0 B | 0.1 | 0% |
| buildSbPreviewSize |  271 kB | 271 kB | 0 B | -0.5 | 0% |
| buildStaticSize |  0 B | 0 B | 0 B | - | - |
| buildPrebuildSize |  3.84 MB | 3.84 MB | 0 B | 0.03 | 0% |
| buildPreviewSize |  3 MB | 3 MB | -14 B | 0.38 | 0% |
| testBuildSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbAddonsSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbCommonSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbManagerSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbPreviewSize |  0 B | 0 B | 0 B | - | - |
| testBuildStaticSize |  0 B | 0 B | 0 B | - | - |
| testBuildPrebuildSize |  0 B | 0 B | 0 B | - | - |
| testBuildPreviewSize |  0 B | 0 B | 0 B | - | - |

| name | before | after | diff | z | % |
| ---- | ------ | ----- | ---- | - | - |
| createTime |  24.3s | 24.2s | -97ms | **1.33** | -0.4% |
| generateTime |  19.4s | 21.9s | 2.5s | -0.08 | 11.7% |
| initTime |  12s | 14.9s | 2.9s | 0.11 | 19.5% |
| buildTime |  7.7s | 8.8s | 1s | -0.28 | 12% |
| testBuildTime |  0ms | 0ms | 0ms | - | - |
| devPreviewResponsive |  6.2s | 4.9s | -1s -300ms | -0.24 | -26.4% |
| devManagerResponsive |  4.3s | 3.5s | -821ms | -0.1 | -23% |
| devManagerHeaderVisible |  635ms | 544ms | -91ms | -0.42 | -16.7% |
| devManagerIndexVisible |  710ms | 607ms | -103ms | -0.36 | -17% |
| devStoryVisibleUncached |  1.2s | 1.8s | 553ms | 0.53 | 30.3% |
| devStoryVisible |  708ms | 576ms | -132ms | -0.63 | -22.9% |
| devAutodocsVisible |  545ms | 546ms | 1ms | 0.25 | 0.2% |
| devMDXVisible |  572ms | 496ms | -76ms | -0.32 | -15.3% |
| buildManagerHeaderVisible |  623ms | 559ms | -64ms | -0.15 | -11.4% |
| buildManagerIndexVisible |  632ms | 575ms | -57ms | -0.16 | -9.9% |
| buildStoryVisible |  621ms | 561ms | -60ms | -0.11 | -10.7% |
| buildAutodocsVisible |  465ms | 464ms | -1ms | -0.08 | -0.2% |
| buildMDXVisible |  455ms | 451ms | -4ms | -0.2 | -0.9% |

## Greptile Summary

This PR removes the '@fs' prefix from story imports in the Vite builder for Storybook, addressing issues with plugins modifying story import resolution.

- Refactored `toImportFn` in `codegen-importfn-script.ts` to use absolute paths and improve dynamic imports
- Updated `generateModernIframeScriptCode` in `codegen-modern-iframe-script.ts` for better preview annotation handling and HMR support
- Simplified `processPreviewAnnotation` in `process-preview-annotation.ts` to normalize paths using the 'pathe' library
- Added new test files `codegen-importfn-script.test.ts` and `codegen-modern-iframe-script.test.ts` to ensure correct functionality
- Updated dependencies in `package.json` to include 'knitwork', 'pathe', and 'slash' for improved path handling

### CODE REVIEW

**Comment by JReinhold** [comment]
Does these changes relate/interfere with the changes proposed in https://github.com/storybookjs/storybook/pull/26010 ?

**Comment by tobiasdiez** [comment]
> Do these changes relate/interfere with the changes proposed in #26010 ?

Apart from the obvious merge conflicts there is no interference. The changes in #26010 related to the story index involve virtual modules (prefixed with `virtual:`) while this PR here enables to use semi-virtual imports that use query selectors (e.g. `Button.stories.ts?story=abc`).

**Comment by tobiasdiez** [comment]
@JReinhold could we please get this in? It's blocking support for v8 in the vue plugin.

File: code/builders/builder-vite/src/codegen-importfn-script.ts [hunk 1]
```diff
@@ -21,34 +23,33 @@ function toImportPath(relativePath: string) {
...
-  return `
-    const importers = {
-      ${objectEntries.join(',\n')}
-    };
+  return dedent`
+    const importers = ${genObjectFromRawEntries(objectEntries)};
 
     export async function importFn(path) {
-        return importers[path]();
+      return await importers[path]();
```
Comment (JReinhold) [inline code/builders/builder-vite/src/codegen-importfn-script.ts:43]: AFAIK this would only make a difference if there was a try/catch-block, which there isn't here. Or maybe I'm missing something?

File: code/core/src/types/modules/core-common.ts [hunk 2]
```diff
@@ -194,6 +194,7 @@ export interface BuilderOptions {
   ignorePreview?: boolean;
   cache?: FileSystemCache;
   configDir: string;
+  projectRoot?: string;
```
Comment (JReinhold) [inline code/core/src/types/modules/core-common.ts:197]: can you elaborate on why this is needed now?

File: code/builders/builder-vite/src/codegen-importfn-script.ts [hunk 3]
```diff
@@ -1,7 +1,9 @@
-import { relative } from 'node:path';
-
 import type { Options } from 'storybook/internal/types';
 
+import { genDynamicImport, genImport, genObjectFromRawEntries } from 'knitwork';
```
Comment (JReinhold) [inline code/builders/builder-vite/src/codegen-importfn-script.ts:3]: I'm not a fan of using this package for multiple reasons:

1. With our recent focus on slimming down Storybook, we're trying to ensure that every KB counts, and to me it doesn't look like this improves the code in any way. The library covers a lot of edge cases/options which I don't think is relevant to us - but maybe I'm missing something?
2. I feel like the readability suffers here, because now to understand what the code does, you need to dig into what `knitwork` is and does. Before it was just simple string concatenations, which you could understand by understanding basic JS.

But again, maybe this adds compatibility for edge cases that users are experiencing which I don't know about?

File: code/builders/builder-vite/src/codegen-importfn-script.ts [hunk 4]
```diff
@@ -1,7 +1,9 @@
...
+import { normalize, relative } from 'pathe';
```
Comment (JReinhold) [inline code/builders/builder-vite/src/codegen-importfn-script.ts:4]: similar to above, how does this improve over the current combination of Node and Vite APIs, to justify the extra dependency?

File: code/builders/builder-vite/package.json [hunk 5]
```diff
@@ -50,14 +50,16 @@
     "express": "^4.19.2",
     "find-cache-dir": "^3.0.0",
     "fs-extra": "^11.1.0",
+    "knitwork": "^1.1.0",
     "magic-string": "^0.30.0",
+    "pathe": "^1.1.2",
+    "slash": "^5.0.0",
```
Comment (JReinhold) [inline code/builders/builder-vite/package.json:56]: why move `slash` to a `dependency`?

**Review by JReinhold — CHANGES_REQUESTED** [review]
I'm very sorry for taking so long to look at this, it slipped between the cracks! 🙇

I'm fine with the changes to remove `@fs`, but not a fan of the new dependencies as they seem unnecessary to me. But as I say, there might just be some context I'm missing.

File: code/builders/builder-vite/src/codegen-importfn-script.ts (hunk 1 above)
Comment (tobiasdiez) [reply code/builders/builder-vite/src/codegen-importfn-script.ts:43]: There is no noticeable difference (except that, in case of an exception, now the stacktrace also includes the importFn I believe). Personally, I prefer to always use "return await" because it's very easy to forget to add it once you add an exception handler. But I can revert this change if preferred.

File: code/core/src/types/modules/core-common.ts (hunk 2 above)
Comment (tobiasdiez) [reply code/core/src/types/modules/core-common.ts:197]: It's not strictly necessary, but before the paths were relative to `cwd` (which might not be the project root). I've actually extracted the root directory actually only to make testing of the `toImportFn` simpler - but then thought that I would make sense to propagate this upwards and add a proper handling of the project root.
https://github.com/storybookjs/storybook/pull/28941/files#diff-a4ade24974a8c7f082261c73f22be07ec54ad61a3f9683b20035955a50fa1a8bR54

File: code/builders/builder-vite/src/codegen-importfn-script.ts (hunk 1 above)
Comment (JReinhold) [reply code/builders/builder-vite/src/codegen-importfn-script.ts:43]: If this makes the stack trace better, I'm good with it! 👍

File: code/builders/builder-vite/src/codegen-importfn-script.ts (hunk 4 above)
Comment (tobiasdiez) [reply code/builders/builder-vite/src/codegen-importfn-script.ts:4]: As far as I know, there is no easy way to normalize windows paths in Node to always use forward-slash, which is what vite needs to handle the import correctly.

File: code/core/src/types/modules/core-common.ts (hunk 2 above)
Comment (JReinhold) [reply code/core/src/types/modules/core-common.ts:197]: I'm a little concerned that this doesn't actually solve the issue, but appears to. I wouldn't be surprised if there were hundreds of other places that assumed that `process.cwd() === projectRoot`, that would break if anyone attempted to use a project root different from the CWD. So then they'd set this explicitly, thinking that that would solve the issue, when it would just cause breakage somewhere else.

It's just my experience with the code base that makes me slightly defensive about this. We would need to set up an actual minimal reproduction with a case where CWD is not project root and see that it worked, before I'd feel confident in this.

I do like your thinking behind this though, on the surface it makes sense.

File: code/builders/builder-vite/package.json (hunk 5 above)
Comment (tobiasdiez) [reply code/builders/builder-vite/package.json:56]: It's actually used in a few instances in the builder, eg https://github.com/storybookjs/storybook/blob/66b439ef77082d1152f6330c3eb4f1814c80f9e2/code/builders/builder-vite/src/utils/process-preview-annotation.ts#L6 So I thought it would be better be listed as a proper dependency.

File: code/core/src/types/modules/core-common.ts (hunk 2 above)
Comment (tobiasdiez) [reply code/core/src/types/modules/core-common.ts:197]: Is this really a user-facing option? That was not my intention. I only set it once to be the parent of the config dir.
But sure, there might be other problems with not using the root as cwd.

File: code/builders/builder-vite/src/codegen-importfn-script.ts (hunk 4 above)
Comment (JReinhold) [reply code/builders/builder-vite/src/codegen-importfn-script.ts:4]: But isn't that what we did already with `normalizePath` from Vite at the old line 30-32 below?

https://github.com/storybookjs/storybook/pull/28941/files#diff-a4ade24974a8c7f082261c73f22be07ec54ad61a3f9683b20035955a50fa1a8bL30-L32

File: code/builders/builder-vite/package.json (hunk 5 above)
Comment (JReinhold) [reply code/builders/builder-vite/package.json:56]: The point of it being a `devDependency` is so that it gets bundled in (and minimized, optimized, tree-shaken) automatically when we build the package for publication.
Ideally we want to do this with all our dependencies, but some are incompatible with this and some pacakges we just haven't gotten around to test if they can be bundled in, which is why some are still regular `dependencies`. But `devDependencies` is the default unless it's not possible.

I understand how that is not obvious from your point of view, because that's usually not how projects use `dependencies` and `devDependencies`. We might someday move to a more explicit version of this pattern.

File: code/builders/builder-vite/src/codegen-importfn-script.ts (hunk 3 above)
Comment (JReinhold) [reply code/builders/builder-vite/src/codegen-importfn-script.ts:3]: > The package size of the builder should be the same (or actually slightly goes down since its shorter to write the code using knitwork over manual string concats).

From a bundled perspective yes, but not when you take into account that the extra dependencies need to be downloaded and installed.

> I also don't quite understand why the builder size would matter much, since it is never deployed to any server.

I'm sorry I didn't make this clear in the original comment, but for us it's not just about the size of the final bundle of a built Storybook, it's about the whole Storybook experience, which includes how fast it installs, how many dependencies it adds to your project, how many MBs it adds to your `node_modules`.
By far the biggest complaint about Storybook today is that it's "bloated" and people don't want to add the bloat to their projects.
You can very rightfully interpret that complaint however you like, but it doesn't change the fact that our users are loud and clear about caring about this, and so do we.

This is why dependencies need to be justified.

You can read more about the ethos at https://e18e.dev/guide/cleanup.html and our perspective on it in #29038.

> I would argue this is very subjective. Personally, I find `genDynamicImport(path)` more readable

Subjective yes. IMO `genDynamicImport` is only more readable if you understand what it does, which most don't.

> and it is less prone to make a small mistake

I can 100% agree with that.

It doesn't make sense to me to replace ``async () => import('${path}')` with a dependency.

File: code/core/src/types/modules/core-common.ts (hunk 2 above)
Comment (JReinhold) [reply code/core/src/types/modules/core-common.ts:197]: I'm unsure about it being user-facing, it's at least _readable_ by users, but I don't think it's writable.

Would still be great to confirm it works.

File: code/builders/builder-vite/src/codegen-importfn-script.ts (hunk 4 above)
Comment (tobiasdiez) [reply code/builders/builder-vite/src/codegen-importfn-script.ts:4]: Oh, I wasn't aware of the existence of that helper (at least not the active part of my brain). I still think it would make sense to just use pathe everywhere, because it makes you forget about the issue completely. Would also allow to get rid of the `slash` dependency, and the 2 or 3 independent implementations of path normalizing in storybook (https://github.com/search?q=repo%3Astorybookjs%2Fstorybook%20slash&type=code)

File: code/builders/builder-vite/src/codegen-importfn-script.ts (hunk 3 above)
Comment (tobiasdiez) [reply code/builders/builder-vite/src/codegen-importfn-script.ts:3]: If you really think that reducing 30kb in node_modules for developers (not production) is worth the danger of introducing bugs by manual string concatenation, may I ask you to migrate the code away from knitwork (here as well as in https://github.com/storybookjs/storybook/pull/28798)?

File: code/builders/builder-vite/package.json (hunk 5 above)
Comment (tobiasdiez) [reply code/builders/builder-vite/package.json:56]: Okay, I will move it back to dev dependency.

May I add that I'm not a big fan of this inline-practice (for the builder and framework - it makes completely sense for the cli and the react-based view). I don't see what dependencies you pull-in (along with their security concerns etc, I have to trust you), it makes package managers obsolete / helpless, it makes auditing & sponsoring of indirect dependencies impossible, and it might well increase the overall size of the node modules folder (definitely if everyone would follow such a practice) - and finally it artificially reduces download numbers for npm packages - and we all know that such numbers might be important to get funding for open source projects etc.

**Comment by tobiasdiez** [comment]
@JReinhold After rereading my messages from yesterday, I would like to say sorry for the tone. Had a bit of a rough day yesterday and then got a bit frustrated with what I perceived are minor points. But, of course, you and the team have more insights into the whole ecosystem than me, and I trust your judgments. So please don't take these comments personal. Sorry!

File: code/builders/builder-vite/package.json (hunk 5 above)
Comment (JReinhold) [reply code/builders/builder-vite/package.json:55]: That's fair, those are all valid considerations to include when weighing the trade offs.

**Comment by JReinhold** [comment]
No worries @tobiasdiez, we're all humans and I didn't put too much into it anyway. Thanks for being honest, makes everything easier.

File: code/builders/builder-vite/src/codegen-importfn-script.ts (hunk 4 above)
Comment (JReinhold) [reply code/builders/builder-vite/src/codegen-importfn-script.ts:4]: I see what you mean.
So what you're saying is that using `pathe` _everywhere_ is mentally easier/safer for us than using `node:path` + `slash` everywhere?

We've sort of been going in the opposite direction recetly, eg. replacing `fs-extra` with `node:fs` and a handful of manual logic, to slim down everything and make use of the modern APIs Node gives us today.

However when prebundled, `pathe` vs `slash` is 1.68 KB vs 98 B, which is an abysmal difference TBH.

**Comment by JReinhold** [comment]
I suggest you slim down this PR to the minimal changes required to get rid of the `@fs` prefix. The discussions about dependencies and code logic are becoming bigger than the main change itself, so they should be had in separate PRs that specifically introduces those changes.

File: code/builders/builder-vite/src/codegen-importfn-script.ts (hunk 4 above)
Comment (tobiasdiez) [reply code/builders/builder-vite/src/codegen-importfn-script.ts:4]: > I see what you mean. So what you're saying is that using `pathe` _everywhere_ is mentally easier/safer for us than using `node:path` + `slash` everywhere?

Yes. Additionally, pathe handles all kind of slashes also as input well (eg when calling `resolve` etc). So you don't need to worry about converting them to the correct format before calling the methods from `path`. `slash` is only this tiny bit of pathe: https://github.com/unjs/pathe/blob/main/src/_internal.ts

**Comment by tobiasdiez** [comment]
> I suggest you slim down this PR to the minimal changes required to get rid of the `@fs` prefix. The discussions about dependencies and code logic are becoming bigger than the main change itself, so they should be had in separate PRs that specifically introduces those changes.

I cannot really slim this down further without losing confidence that it still works. There are a lot of edge cases to consider (input as relative or absolute, in unix or windows style, with ending slash and without, etc). The solution using knitwork + pathe is taken from the nuxt project, that use them in exactly this way to generate dynamic imports for a very similar use case (dynamic imports of "modules"). So I regard this as well tested, also with strange inputs. 

If there were a lot of unit tests for this part of storybook, I would be more confident in eg. replacing pathe by the simple slash replacement.

File: code/builders/builder-vite/src/codegen-importfn-script.ts (hunk 4 above)
Comment (tobiasdiez) [reply code/builders/builder-vite/src/codegen-importfn-script.ts:4]: Just had a look at the vite implementation, and it looks like they also just replace the slash: https://github.com/vitejs/vite/blob/5cac0544dca2764f0114aac38e9922a0c13d7ef4/packages/vite/src/shared/utils.ts#L27-L29

**Comment by ms2d** [comment]
Is there any chance of this getting unblocked soon? If not, could someone suggest maximum version numbers and/or an install procedure for continuing to use this plugin with Storybook 7?

**Comment by charlieperrone** [comment]
> Is there any chance of this getting unblocked soon? If not, could someone suggest maximum version numbers and/or an install procedure for continuing to use the vue-addon with Storybook 7?

Seconding this, I've been spending a few hours trying to figure out how to get vue-addon working with storybook 7, but a guide would be helpful.

**Comment by tobiasdiez** [comment]
> > Is there any chance of this getting unblocked soon? If not, could someone suggest maximum version numbers and/or an install procedure for continuing to use the vue-addon with Storybook 7?
> 
> Seconding this, I've been spending a few hours trying to figure out how to get vue-addon working with storybook 7, but a guide would be helpful. @tobiasdiez

I'm using it at https://github.com/JabRef/JabRefOnline with storybook v7. But the setup is a bit non-standard, so I don't know if it works with the given dependency versions also on other systems.

**Review by kasperpeulen — APPROVED** [review]
Thanks!

**Review by JReinhold — APPROVED** [review]

**Comment by tobiasdiez** [comment]
@kasperpeulen and @JReinhold Thanks for the review!
