### PR TITLE
Core: Update error message from storiesOf usage.

### LINKED ISSUE #20146: Ensure error message you get when using storiesOf in ssv7 mode is very clear
Does it explain what's wrong? Does it link to the appropriate MIGRATION.md entry? Does the MIGRATION.md explain what to do to upgrade (or downgrade to ssv6)?

- [ ] Test in Vite project
- [ ] Test in Webpack project
- [ ] Do we want to add an automigration as well?

### PR DESCRIPTION
**Pull request by tmeasday**
Closes #20146

## What I did

- Made a more user-friendly message
- Link to the docs about change of default and how to opt-out

## Checklist

- [x] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [x] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

File: code/lib/csf-tools/src/CsfFile.ts [hunk 1]
```diff
@@ -414,9 +414,10 @@ export class CsfFile {
           const { callee } = node;
           if (t.isIdentifier(callee) && callee.name === 'storiesOf') {
             throw new Error(dedent`
-              CSF: unexpected storiesOf call ${formatLocation(node, self._fileName)}
+              Unexpected \`storiesOf\` usage: ${formatLocation(node, self._fileName)}.
 
-              More info: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#story-store-v7
+              In SB7, we use the \`storyStoreV7\` by default, which does not support \`storiesOf\`.
```
Comment (tmeasday) [inline code/lib/csf-tools/src/CsfFile.ts:419]:
```suggestion
              In SB7, we use \`storyStoreV7\` by default, which does not support \`storiesOf\`. 
```

**Review by yannbf — APPROVED** [review]
LGTM!
