### PR TITLE
UI: Fix keydown shortcut within shadow tree

### LINKED ISSUE #23790: [Bug]: Within shadow tree, shortcuts are not appropriately ignored
### Describe the bug

When a shadow dom is rendered within a story, keyboard actions are triggered even while a input, textarea, or contenteditable element is focused.

### To Reproduce

https://stackblitz.com/edit/stackblitz-starters-cxrkde?file=src%2Fstories%2Finput.shadow-dom.stories.tsx

### System

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
  npmPackages:
    @storybook/addon-essentials: ^7.2.2 => 7.2.2 
    @storybook/addon-links: ^7.2.2 => 7.2.2 
    @storybook/blocks: ^7.2.2 => 7.2.2 
    @storybook/react: ^7.2.2 => 7.2.2 
    @storybook/react-vite: ^7.2.2 => 7.2.2 
    @storybook/testing-library: ^0.2.0 => 0.2.0
```

### Additional context

I think the problem can be solved by using [`event.composedPath()`](https://developer.mozilla.org/en-US/docs/Web/API/Event/composedPath) instead of `event.target`.

https://github.com/storybookjs/storybook/blob/354d1baac8c10c9646b6dceff5dd93a52f06ec67/code/lib/preview-api/src/modules/preview-web/PreviewWithSelection.tsx#L47C1-L50

The reproduction shows the problem in an input, but same problem is expected on a textarea or `contenteditable` element.

### PR DESCRIPTION
**Pull request by stropitek**
Closes #23790

## What I did

I changed the part in the preview which checks if a keyboard event should be sent or not. Previously this was done using `event.target`, and I changed that to use `event.composedPath()[0]` instead, so that stories which render an input / textarea or contenteditable element within a shadow tree don't spuriously trigger storybook shortcuts.

The linked issue has a reproducible example of the bug.

### Testing

I made sure there are no regressions in the e2e tests and updated the unit tests. However I did not implement new tests for stories including a shadow tree. I wasn't sure how to go about this.

#### The changes in this PR are covered in the following automated tests:

- [x] stories
- [x] unit tests
- [ ] integration tests
- [x] end-to-end tests

#### Manual testing

I did not know how to manually test this in the storybook project directly. I use react and it would require to create a new react-only story and add the react-shadow dependency.

Instead, I checked my change manually within another project:

- Checkout https://github.com/zakodium-oss/react-science
- Run `npm ci`
- Run `npm run storybook`
- Run `npx serve storybook-static`
- Go to one of the "Input" stories
- Type "s" in the input => it toggles the sidebar
- Edit `./storybook-static/sb-preview/runtime.js`, replace `let target = event.target;` with `let target = event.composedPath()[0]`
- Reload the input story and check that when in the input, typing `s` does not toggle the sidebar as expected. When focused element is within the preview but not the input, type `s` does toggle the sidebar as expected.

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

File: code/lib/preview-api/src/modules/preview-web/PreviewWithSelection.tsx [hunk 1]
```diff
@@ -45,7 +45,7 @@ import type { StorySpecifier } from '../store/StoryIndexStore';
 const globalWindow = globalThis;
 
 function focusInInput(event: Event) {
-  const target = event.target as Element;
+  const target = event.composedPath()[0] as Element;
```
Comment (ndelangen) [inline code/lib/preview-api/src/modules/preview-web/PreviewWithSelection.tsx:48]: I figured I'd leave this here for future me:
https://developer.mozilla.org/en-US/docs/Web/API/Event/composedPath

**Review by ndelangen — APPROVED** [review]

File: code/lib/preview-api/src/modules/preview-web/PreviewWithSelection.tsx (hunk 1 above)
Comment (stropitek) [reply code/lib/preview-api/src/modules/preview-web/PreviewWithSelection.tsx:48]: FYI, I found this article to be really helpful on the topic of events and shadow dom
https://pm.dartus.fr/blog/a-complete-guide-on-shadow-dom-and-event-propagation/

Comment (yannbf) [inline code/lib/preview-api/src/modules/preview-web/PreviewWithSelection.tsx:48]: Hey @stropitek thank you so much for your contribution! I don't know if this would work in 100% of our use cases, so I wonder if we need to make this change safer?

I've seen this being handled other codebases like so:

```ts
const target = (event.composedPath && event.composedPath()[0]) || event.target
```

```ts
const target = (evnt.target.shadowRoot && evnt.composed) ? (evnt.composedPath()[0] || evnt.target) : evnt.target
```

```ts
const target = event.composedPath ? event.composedPath()[0] || event.target : event.target
```

Comment (stropitek) [reply code/lib/preview-api/src/modules/preview-web/PreviewWithSelection.tsx:48]: I made the assumption from https://developer.mozilla.org/en-US/docs/Web/API/Event/composedPath that there was enough browser support for this to be safe. It's also supposed to work both in closed and open modes, see https://mdn.github.io/web-components-examples/composed-composed-path/

But I agree that it does not "feel" safe because of the function call and the property access.

I'm happy to change it + add a test case for the `event.target` case.


> ```ts
> const target = (event.composedPath && event.composedPath()[0]) || event.target
> ```
> 

I'd go with this one since it is the least tied to any browser spec.

Comment (ndelangen) [reply code/lib/preview-api/src/modules/preview-web/PreviewWithSelection.tsx:48]: I think support is well within the range of what storybook supports, but considering it's a 1-liner to add the fallback I think we should go with the above suggestion @stropitek

**Comment by stropitek** [comment]
For the record, if the shadow root is `closed`, since we don't have access to the original dom node which dispatched the event, there is no way to know if we should or should not send the event through the channel.

With this implementation, the event will always be sent.

**Comment by ndelangen** [comment]
@stropitek The custom web-component should maybe be stop the propagation of the event in that case, shouldn't it?

**Comment by stropitek** [comment]
Yes, a custom web-component can stop the propagation of the event to the host (storybook) by calling `stopPropagation` on the `keydown` event (I tested it to be sure).

**Review by yannbf — APPROVED** [review]
