### PR TITLE
A11y: Make search clear button keyboard accessible

### LINKED ISSUE #32582: [Bug]:  Search clear button is not keyboard-reachable
### Describe the bug

Image

This probably happens because of the display logic in Search.tsx, which changes on blur.

Because the search button is not strictly necessary to use Search (users can also select all + delete), this issue is low priority.

### Reproduction link

yarn storybook:ui in the monorepo

### Reproduction steps

1. Launch Storybook in the monorepo
2. Go to the search feature and type something
3. Try to tab into the clear button

### System

```bash
N/A

Storybook 10.0 beta
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ritoban23**
Closes #32582

## What I did

Fixed the search clear button keyboard accessibility issue by changing the button's visibility condition from `isOpen` to `input`. This ensures the clear button remains visible and focusable even when the search input loses focus, allowing keyboard users to tab to and activate it. Also added proper `aria-label` for screen readers and improved the clear functionality.

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

1. Run Storybook UI: `cd code && yarn storybook:ui`
2. Open Storybook in your browser at http://localhost:6006/
3. Type something in the search field
4. Press Tab again - the clear button should now be focused
6. Press Enter on the clear button - it should clear the search input
7. Verify the button disappears when there's no input text

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - [x] `bug`: Internal changes that fixes incorrect behavior.
  - [ ] `maintenance`: User-facing maintenance tasks.
  - [ ] `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - [ ] `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - [ ] `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - [ ] `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - [ ] `feature request`: Introducing a new feature.
  - [ ] `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - [ ] `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

## Summary by CodeRabbit

* **Bug Fixes**
  * Sidebar search clear button shows only when text is entered, has an accessible label, clears the input, and closes suggestions.
  * Selecting a component now navigates to the first visible story when some children are filtered/hidden.

* **Documentation**
  * Updated migration guidance for ESM/config imports and added new changelog/release notes.

* **Breaking Change**
  * The Jest addon and its panel have been removed from this release.

### CODE REVIEW

File: code/core/src/manager/components/sidebar/Search.tsx [hunk 1]
```diff
@@ -409,8 +410,14 @@ export const Search = React.memo<SearchProps>(function Search({
...
                 )}
                 <Actions>
-                  {isOpen && (
-                    <IconButton onClick={() => clearSelection()}>
+                  {input && (
+                    <IconButton
+                      aria-label="Clear search"
+                      onClick={() => {
+                        reset({ inputValue: '' });
+                        closeMenu();
```
Comment (Sidnioulz) [inline code/core/src/manager/components/sidebar/Search.tsx:420]: Could you please explain in more detail why this is better than `clearSelection`? Could you please walk us through how you tested this change?

File: code/core/src/manager/components/sidebar/Search.tsx [hunk 2]
```diff
@@ -409,8 +410,14 @@ export const Search = React.memo<SearchProps>(function Search({
                   </FocusKey>
                 )}
                 <Actions>
-                  {isOpen && (
-                    <IconButton onClick={() => clearSelection()}>
+                  {input && (
+                    <IconButton
+                      aria-label="Clear search"
```
Comment (Sidnioulz) [inline code/core/src/manager/components/sidebar/Search.tsx]: This will be fixed upstream with changes to the button component, so it won't be necessary :)

File: code/core/src/manager/components/sidebar/Search.tsx [hunk 3]
```diff
@@ -409,8 +410,14 @@ export const Search = React.memo<SearchProps>(function Search({
                   </FocusKey>
                 )}
                 <Actions>
-                  {isOpen && (
-                    <IconButton onClick={() => clearSelection()}>
+                  {input && (
```
Comment (Sidnioulz) [inline code/core/src/manager/components/sidebar/Search.tsx:413]: Good job! This is indeed one of the things that weren't going so well with this component.

**Review by Sidnioulz — COMMENTED** [review]
Thanks for attempting a fix on this issue, @ritoban23!

Unfortunately, we've since noticed that the issue is a regression on a specific branch (`a11y-consolidation`) and we've found and fixed the root cause for this regression. So, I'll be closing the GitHub issue.

I want to discuss your changes to the event handler before closing the PR though. Could you please walk me through what it does?

File: code/core/src/manager/components/sidebar/Search.tsx (hunk 1 above)
Comment (ritoban23) [reply code/core/src/manager/components/sidebar/Search.tsx:420]: the `clearSelection()` function mainly clears the "selected item" from the dropdown, but it doesn't always clear the input text or close the menu properly...the new code explicitly clear the input text and closes dropdown to return to the tree view. This gives control over what happens matching the components behavior... also added `aria-label="Clear search"` for better accessibility ....it all basically ensures the search clears fully and the UI resets correctly, especially for keyboard users. clearSelection() was too vague and could leave things inconsistent.

I tested the change manually by verifying mouse and keyboard activation of the clear button (tab to button, Enter/Space to activate), confirming the input is emptied and the menu closes, and ensuring Escape still behaves as before.

**Comment by ritoban23** [comment]
@Sidnioulz hello , apologies for the late reply....I tried to explain my proposed changes to the best of my understanding hope it helps!

**Review by Sidnioulz — APPROVED** [review]

File: code/core/src/manager/components/sidebar/Search.tsx (hunk 1 above)
Comment (Sidnioulz) [reply code/core/src/manager/components/sidebar/Search.tsx:420]: Thanks for the clear explanation!

**Comment by Sidnioulz** [comment]
> @Sidnioulz hello , apologies for the late reply....I tried to explain my proposed changes to the best of my understanding hope it helps!

Absolutely, thank you for this contribution!

File: code/core/src/manager-api/tests/stories.test.ts [hunk 4]
```diff
@@ -1106,6 +1106,45 @@ describe('stories API', () => {
...
+        },
+        // Note: 'a--1' is missing from filtered index (hidden)
+      };
+
+      store.setState({ filteredIndex });
+
+      // When selecting the component, it should select the first visible child (a--2)
+      api.selectStory('a');
+      expect(navigate).toHaveBeenCalledWith('/story/a--2');
+    });
```
[the remark this answers is not in the document]
Comment (Sidnioulz) [reply code/core/src/manager-api/tests/stories.test.ts:1147]: @coderabbitai go home, you're drunk. This file was not touched at all by this PR.

**Review by Sidnioulz — APPROVED** [review]
