### PR TITLE
Core: Prevent stories lookup in node_modules

### LINKED ISSUE #25118: [Bug]: Storybook loads stories from node_modules with pnpm
### Describe the bug

When using pnpm, Stoybook seems to be loading stories from `node_modules` when the `stories` patterns could include `node_modules` of subdirectories. This seems to be the same issue as https://github.com/storybookjs/storybook/issues/18907 and https://github.com/storybookjs/storybook/issues/19446, but it does not seem to be fixed as of `7.6.3` and goes against the behavior described in https://github.com/storybookjs/storybook/pull/22873. In a large monorepo with lots of dependencies, this crashes the dev server and build with an out of memory error (but that's harder to reproduce):

```
<--- Last few GCs --->

[1987:0x67a8920]    61264 ms: Mark-Compact (reduce) 2033.9 (2082.7) -> 2033.1 (2082.7) MB, 2284.10 / 0.00 ms  (average mu = 0.104, current mu = 0.001) allocation failure; scavenge might not succeed
[1987:0x67a8920]    63550 ms: Mark-Compact (reduce) 2034.1 (2082.7) -> 2033.4 (2083.2) MB, 2284.16 / 0.00 ms  (average mu = 0.054, current mu = 0.001) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xc9e850 node::Abort() [node]
 2: 0xb720ff  [node]
 3: 0xec1a70 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [node]
 4: 0xec1d57 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [node]
 5: 0x10d3dc5  [node]
 6: 0x10ebc48 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 7: 0x10c1d61 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 8: 0x10c2ef5 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 9: 0x10a0466 v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
10: 0x14fb386 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
11: 0x7f7377e99ef6 
Aborted (core dumped)
 ELIFECYCLE  Command failed with exit code 134.
```

### To Reproduce

1. Clone https://github.com/Methuselah96/storybook-pnpm-issue
2. `pnpm install`
3. `pnpm storybook`
4. Observe errors that show it's trying to read stories from `node_modules`:

```
ERROR in ./node_modules/.pnpm/@storybook+react@7.6.3_react-dom@18.2.0_react@18.2.0_typescript@4.9.5/node_modules/@storybook/react/template/cli/ts-3-8/Button.stories.ts 1:12
Module parse failed: Unexpected token (1:12)
File was processed with these loaders:
 * ./node_modules/.pnpm/@storybook+builder-webpack5@7.6.3_esbuild@0.18.20_typescript@4.9.5_webpack-cli@5.1.4/node_modules/@storybook/builder-webpack5/dist/loaders/export-order-loader.js
 * ./node_modules/.pnpm/unplugin@1.5.1/node_modules/unplugin/dist/webpack/loaders/load.js
You may need an additional loader to handle the result of these loaders.
```

### System

```bash
Storybook Environment Info:

  System:
    OS: Windows 11 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD <----- active
    pnpm: 8.11.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (119.0.2151.97)
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by valentinpalkovic**
Closes https://github.com/storybookjs/storybook/issues/25118

## What I did

A glob pattern like
`"../packages/**/*.stories.@(js|jsx|mjs|ts|tsx)"` will look up stories even in submodule node_module folders like `../packages/a/node_modules/**/*.stories.*`

A couple of places were affected where we don't exclude node_modules

- export-order-loader hasn't excluded node_modules
- csf-plugin was running on all stories, even on stories in node_module folders
- the dynamic imports took node_module stories also into account. This only happens now, if `node_modules` is explicitly part of the stories glob pattern.

## Related PRs

- https://github.com/storybookjs/storybook/pull/22873

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

File: code/lib/core-webpack/src/to-importFn.ts [hunk 1]
```diff
@@ -4,6 +4,20 @@ import { globToRegexp } from '@storybook/core-common';
...
+  const excludeNodeModulesPattern = startsWithCaret ? '(?!.*node_modules)' : '^(?!.*node_modules)';
+
+  // Combine the new exclusion pattern with the original regex
+  const adjustedRegexString = startsWithCaret
+    ? `^${excludeNodeModulesPattern}${originalRegexString.substring(1)}`
+    : excludeNodeModulesPattern + originalRegexString;
+
+  // Create and return the new regex
+  return new RegExp(adjustedRegexString);
+}
```
Comment (tmeasday) [inline code/lib/core-webpack/src/to-importFn.ts:19]: Would it make sense to instead of doing this adjustment here to do it in `normalizeStoriesEntry`? 

https://github.com/storybookjs/storybook/blob/c98bddd2f2244a3a869c8e680e0e6734a03ebec3/code/lib/core-common/src/utils/normalize-stories.ts#L35

I guess I'm just wondering where else we use the stories entry to lookup or watch files? For instance, I think we do it here also:

https://github.com/storybookjs/storybook/blob/c98bddd2f2244a3a869c8e680e0e6734a03ebec3/code/lib/core-server/src/utils/watch-story-specifiers.ts#L26-L31

**Review by tmeasday — COMMENTED** [review]
I think this makes sense, and could be a big win. But what if someone does actually want to include stories from `node_modules`? Is that just not allowed?

**Comment by valentinpalkovic** [comment]
> I think this makes sense, and could be a big win. But what if someone does actually want to include stories from `node_modules`? Is that just not allowed?

@tmeasday  Currently, if someone wants to include stories from node_modules, they can, but no transformations would be applied to it. The babel-loader/swc-loaders currently ignore node_modules and the CSF-plugin or the export-order-loader plugin. I think it is okay if babel/swc doesn't touch the file since my assumption is that if something is provided via `node_modules`, it is already transformed and consumable. 

If the Stories are transformed into CJS, the `export-order-loader` plugin can't do much about it. So, I wouldn't configure it to transform node_modules as well. 

The CSF-plugin requires source files, for example, to extract JSDOC comments or the original source code. This also doesn't make much sense for precompiled code from node_modules.

File: code/lib/core-webpack/src/to-importFn.ts (hunk 1 above)
Comment (tmeasday) [reply code/lib/core-webpack/src/to-importFn.ts:19]: So given your comment below, we might not want to entirely disregard stories from `node_modules` for indexing / watching the index. Or at least if we did we'd want to commit to stories from the `node_modules` not being supported at all in SB.

I think we should definitely consider that (for perf reasons). I can imagine that setting up file watchers recursively in `node_modules` as `watch-story-specificers` may very well be doing could be *very* costly. At the least we could feature flag it so it's off by default.

I would say we do that work separate to this PR, but the thing is if we were to adjust the stories entry, we wouldn't need to make the other changes that are in this PR.

**Review by ndelangen — APPROVED** [review]

File: code/lib/core-webpack/src/to-importFn.ts (hunk 1 above)
Comment (valentinpalkovic) [reply code/lib/core-webpack/src/to-importFn.ts:19]: > Would it make sense to instead of doing this adjustment here to do it in `normalizeStoriesEntry`?
> 
> https://github.com/storybookjs/storybook/blob/c98bddd2f2244a3a869c8e680e0e6734a03ebec3/code/lib/core-common/src/utils/normalize-stories.ts#L35
> 
> I guess I'm just wondering where else we use the stories entry to lookup or watch files? For instance, I think we do it here also:
> 
> https://github.com/storybookjs/storybook/blob/c98bddd2f2244a3a869c8e680e0e6734a03ebec3/code/lib/core-server/src/utils/watch-story-specifiers.ts#L26-L31

@tmeasday If you don't mind, I would like to pair on this since I am not sure how easily achievable this is. `normalizeStoriesEntry` doesn't deal with regex, but with globs and having excluding patterns in a glob string is not that easy. We could change `normalizeStoriesEntry` completely to not return a glob string for `files`, but instead a e.g. picomatch `matcher`, which can be configured to ignore certain patterns: https://github.com/micromatch/picomatch. But this would require major refactorings.
