### PR TITLE
Autodocs: Fix docs pages ignoring `meta.id` when calculating their ID

### LINKED ISSUE #23394: [Bug]: Cannot manually set story id for the Docs pages
### Describe the bug

From Storybook [documentation](https://storybook.js.org/docs/vue/configure/sidebar-and-urls#permalink-to-stories), I read that we can set story id manually using 'id' and 'name' props. 

It works good for stories.ts files, but not for .mdx files, as well as autodocs. 

**Example**: 
A menucomponent has a title 'components/menu' and a story called basic. 
When I open the component. I get the following URL.
http://localhost:6006/?path=/story/components-menu--basic

When I add 'id: 'menu' in meta tag in stories.ts file, I get the following URL.
http://localhost:6006/?path=/story/menu--basic
'components-menu 'is replaced with 'menu' in the URL, which is expected.

However, when I open the Docs, I get the following URL.
http://localhost:6006/?path=/docs/components-menu--docs
The URL still uses 'components-menu', which I want to get replaced with 'menu'.

### To Reproduce

https://stackblitz.com/edit/github-ipnsdt?file=src%2Fstories%2FButton.stories.ts

### System

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.67)
  npmPackages:
    @storybook/addon-essentials: ^7.0.25 => 7.0.25
    @storybook/addon-interactions: ^7.0.25 => 7.0.25
    @storybook/addon-links: ^7.0.25 => 7.0.25
    @storybook/blocks: ^7.0.25 => 7.0.25
    @storybook/testing-library: ^0.2.0 => 0.2.0
    @storybook/vue3: ^7.0.25 => 7.0.25
    @storybook/vue3-vite: ^7.0.25 => 7.0.25
```

### Additional context

This used to work good in Storybook 6.5, where stories and docs are written in same stories.mdx files.  I understand in Storybook 7, we separated stories and documentation, but the Docs URL is not in sync with stories when we manually set it.

### PR DESCRIPTION
**Pull request by sookmax**
Closes #23394

## What I did

I made a little adjustment in `StoryIndexGenerator` so that the docs pages that are automatically generated would also prioritize `Meta.id` over `Meta.title` if `Meta.id` was provided.

I referenced code section below for the adjustment.

https://github.com/storybookjs/storybook/blob/c8e9caf9514cdb021834c0bbe6082faca733381a/code/lib/csf-tools/src/CsfFile.ts#L469-L493

## How to test

1. Run a sandbox for template, e.g. `yarn task --task sandbox --start-from auto --template react-vite/default-ts`
2. Add `id` to `meta` object in `Button.stories.ts` (e.g., `MyButton`)
3. Open Storybook in your browser
4. Go to `Button` docs page and confirm the url is something like: `http://localhost:6007/?path=/docs/mybutton--docs`

## Checklist

- [x] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "build", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by sookmax** [comment]
The second commit includes a fix for the case of MDX docs. It is slightly more involved than the case of autodocs since MDX docs, when being processed, don't have a direct access to `csf.meta.id`.

I decided to store the whole `csf.meta` object in `StoryIndexEntry` and pull the value (`meta.id`) from there, which inevitably resulted in generic index signature being added to `StoryIntexEntry` type, and the snapshots in `code/lib/core-server/src/utils/StoryIndexGenerator.test.ts` being updated.

I am not sure the decisions I made for the second commit are sound, so yes definitely need some reviews!

Thanks.

File: code/lib/core-server/src/utils/StoryIndexGenerator.ts [hunk 1]
```diff
@@ -260,7 +260,15 @@ export class StoryIndexGenerator {
...
         const tags = [...(storyTags || componentTags), 'story'];
-        entries.push({ id, title: csf.meta.title, name, importPath, tags, type: 'story' });
+        entries.push({
+          id,
+          title: csf.meta.title,
+          name,
+          importPath,
+          tags,
+          type: 'story',
+          meta: csf.meta,
```
Comment (tmeasday) [inline code/lib/core-server/src/utils/StoryIndexGenerator.ts:270]:
```suggestion
          // We need to keep track of the csf meta so we know the component id when referencing docs below
          meta: csf.meta,
```

**Review by tmeasday — CHANGES_REQUESTED** [review]
Let's drop the meta again in the `getIndex`, maybe something like:

```
          // Drop the meta as it isn't part of the index, we just used it for record keeping
          const { meta, ...existing } = indexEntries[entry.id];
```

Also, can we add a test case to `storyIndexGenerator.test.ts` that uses a component id?

**Comment by sookmax** [comment]
@tmeasday Hello, thanks for the review! I very much appreciate it.

I pushed additional commits reflecting what you suggested. I decided to filter out the meta before returning in `ensureExtracted`. I thought that way the consumers of `ensureExtracted` (e.g., `getIndex()`) that use its return value wouldn't see the meta. And as a result the updates to the snapshots weren't needed anymore so I reverted the snapshots.

I'm now going to work on the test cases and I'll let you know when I'm done!

Thanks.

**Comment by sookmax** [comment]
@tmeasday I added two test cases (for autodocs and mdx docs) under `describe('autodocs')` and `describe('docs specifier')` respectively. I chose to put relevant mock data in a new directory called `docs-id-generation` under `utils/__mockdata__` since I didn't want them to be grabbed by `./src/**/*.stories.(ts|js|mjs|jsx)`, which seemed to break a few other test cases if they were 😅.

Let me know if you prefer other directory/file structures for mock data.

Thanks!

**Review by tmeasday — APPROVED** [review]
Great job @sookmax!

File: code/lib/types/src/modules/storyIndex.ts [hunk 2]
```diff
@@ -56,6 +56,7 @@ export interface BaseIndexEntry {
 }
 export type StoryIndexEntry = BaseIndexEntry & {
   type: 'story';
+  [index: string]: any;
```
Comment (JReinhold) [inline code/lib/types/src/modules/storyIndex.ts:59]: This seems a bit too lax to me, is this so you can add the `meta` property, and then remove it later?

If so, I'd rather we remove this and do type casts instead where needed or if that's really complex at least only add the `meta.id` property here, optional.

**Review by JReinhold — CHANGES_REQUESTED** [review]
Looks good! Only a minor request regarding the types.

File: code/lib/types/src/modules/storyIndex.ts (hunk 2 above)
Comment (sookmax) [reply code/lib/types/src/modules/storyIndex.ts]: @JReinhold Thanks for the review! It's a bit much, isn't it? It also felt a little bit overkill to me as well.

I removed that generic index signature and add a type that extends `StoryIndexEntry` in `StoryIndexGenerator.ts` and added type castings at relevant lines.

Please check out the new commit below and give me additional feedbacks if necessary!

File: code/lib/core-server/src/utils/StoryIndexGenerator.ts [hunk 3]
```diff
@@ -44,6 +44,8 @@ type ErrorEntry = {
 };
 type CacheEntry = false | StoriesCacheEntry | DocsCacheEntry | ErrorEntry;
 type SpecifierStoriesCache = Record<Path, CacheEntry>;
+// Extended type to keep track of the csf meta so we know the component id when referencing docs in `extractDocs`
+type StoryIndexEntryWithMeta = StoryIndexEntry & { meta?: any };
```
Comment (tmeasday) [inline code/lib/core-server/src/utils/StoryIndexGenerator.ts:48]: Why not type `meta` also?

Comment (sookmax) [reply code/lib/core-server/src/utils/StoryIndexGenerator.ts:48]: Right! would `StoryIndexEntry & { meta?: { id?: string }}` be sufficient?

Comment (sookmax) [reply code/lib/core-server/src/utils/StoryIndexGenerator.ts:48]: Or how about `StoryIndexEntry & { meta?: IndexedCSFFile['meta'] };`?

Comment (tmeasday) [reply code/lib/core-server/src/utils/StoryIndexGenerator.ts:48]: That sounds good. Also should we change the type of `StoriesCacheEntry` to have `entries: [null | StoryIndexEntryWithMeta | DocsIndexEntry]` to avoid the typecasts?

Comment (sookmax) [reply code/lib/core-server/src/utils/StoryIndexGenerator.ts:48]: Um, I'm actually uncertain about the full implications of modifying `StoriesCacheEntry['entries']` to include `StoryIndexEntryWithMeta`. Since it would affect `CacheEntry` and `SpecifierStoriesCache` types and the consumers of them.

I'd appreciate If you could give me some guidance as to what you'd like to see!

Oh and by the way `StoriesCacheEntry['entries']` can be `null` as well?

Comment (tmeasday) [reply code/lib/core-server/src/utils/StoryIndexGenerator.ts:48]: No worries, thanks for being careful. I might be missing something but I believe the `SpecifierStoriesCache` is an internal type that's just used in this one file and not the return type of any public functions. So the implications should be confined to this type. Did I miss something?

> I'd appreciate If you could give me some guidance as to what you'd like to see!

As the type just represents the data we cache in this file to help with `ensureExtracted`, I think we can just add more fields to the type without problems.

> Oh and by the way StoriesCacheEntry['entries'] can be null as well?

Sorry I mean `CacheEntry`:

https://github.com/storybookjs/storybook/blob/29be84d00a4eae5597f8c71c074da32aa7cc7e42/code/lib/core-server/src/utils/StoryIndexGenerator.ts#L45

The cache entry is null when we haven't processed that particular file yet.

Comment (tmeasday) [reply code/lib/core-server/src/utils/StoryIndexGenerator.ts:48]: So, yes, I was probably quite confusing there, I was typing from my phone, always a mistake. What I meant was let's make it:

```ts
type StoriesCacheEntry = {
  entries: (StoryIndexEntryWithMeta | DocsIndexEntry)[];
  dependents: Path[];
  type: 'stories';
};
type CacheEntry = false | StoriesCacheEntry | DocsCacheEntry | ErrorEntry;
type SpecifierStoriesCache = Record<Path, CacheEntry>;

```

Comment (tmeasday) [reply code/lib/core-server/src/utils/StoryIndexGenerator.ts:48]: I think the `SpecifierStoriesCache` is only used by the `ensureExtracted` method and its submethods (`extractStories` and `extractDocs`) so if we want to add some more fields to help them communicate, that's fine with me!

Comment (sookmax) [reply code/lib/core-server/src/utils/StoryIndexGenerator.ts:48]: Okay great! I'll work on a commit that reflects what we've discussed in this thread. Thanks again for the detailed feedbacks 🙏.

I have one more question though. I've realized when I switch out `StoryIndexEntry` with `StoryIndexEntryWithMeta` in `StoriesCacheEntry['entries']` and remove the typecast in `extractStories` below (the last line):

```ts
 entries.push({
          id,
          title: csf.meta.title,
          name,
          importPath,
          tags,
          type: 'story',
          // We need to keep track of the csf meta so we know the component id when referencing docs below in `extractDocs`
          meta: csf.meta,
        } as StoryIndexEntryWithMeta);
```

Then I'll get a TypeScript error ('meta' does not exist in type 'StoryIndexEntry') because at the beginning of the body of `extractStories` we have `const entries = [] as IndexEntry[];`, and `IndexEntry` is `StoryIndexEntry | DocsIndexEntry`. 

This got me thinking whether if we should remove the entire usage of `IndexEntry` in `StoryIndexGenerator` for the sake of consistency? (so for example, should we create a similar internal type `type IndexEntryWithMeta = StoryIndexEntryWithMeta | DocsIndexEntry` and use that type instead throughout the file?)

Comment (tmeasday) [reply code/lib/core-server/src/utils/StoryIndexGenerator.ts:48]: Would the return type of `ensureExtracted()` not still need to reference `IndexEntry` @sookmax?

Comment (sookmax) [reply code/lib/core-server/src/utils/StoryIndexGenerator.ts:48]: Yes it does! thanks I apparently forgot about it 😅. 

Then, should I just change `const entries = [] as IndexEntry[];` to `const entries = [] as (StoryIndexEntryWithMeta | DocsIndexEntry)[];` in `extractStories()`?

Comment (sookmax) [reply code/lib/core-server/src/utils/StoryIndexGenerator.ts]: @tmeasday I've just pushed a93d7b4227441855d45a5e3e4d91a0f9406e233f. Could you look at it to see if everything's okay? Sorry I bombarded you with lots of minor questions!

**Review by tmeasday — APPROVED** [review]
Looks great!

**Comment by ndelangen** [comment]
@sookmax Looks like some merge-conflicts happened, do you think you'd be able to resolve those?

**Comment by sookmax** [comment]
@ndelangen Yes sure! It doesn't appear to be too complex so let me look into it, and I'll let you know when resolved!

**Comment by sookmax** [comment]
@ndelangen Merge is done!

**Comment by sookmax** [comment]
@ndelangen the previous merge seemed accidentally undo https://github.com/storybookjs/storybook/commit/1e90354a2ad9c92890d9081419ee4b5ef084b234 😅. So I re-merged and force-pushed the new merge.

**Review by JReinhold — APPROVED** [review]
Great work! 💪

I'm currently working on a big overhaul of `StoryIndexGenerator`, and I'll make sure to merge your changes into that.

**Comment by sookmax** [comment]
@JReinhold Ah, is that related to https://github.com/storybookjs/storybook/issues/23457?

Looking forward to learning the new architecture when it's done! 👍
