### PR TITLE
UI: Add bottom navigation on mobile

### LINKED ISSUE #23723: [Bug]: Storybook 7.2.1: When I click on the canvas navlink in mobile view the selected sidebar story is not shown
### Describe the bug

When I click on any story below the first/top one in the sidebar in mobile view (using Firefox v115.0.3) the story is at first correctly displayed to the right (scaled down but I can see that it's the selected story) but as soon as I click on the canvas navlink the story that is shown on the canvas is not the selected story but instead the first/top story in the sidebar.

I doesn't matter which story I choose/select, as soon as I click on the canvas navlink the story "resets" to the first/top one and that is what is displayed on the canvas.

I was previously using storybook 7.0.20 and everything was working fine.
I used "yarn dlx storybook@latest upgrade" to upgrade from 7.0.20 to 7.2.1 and I'm using a mono repo (lerna).

--------
Example/repro:

1. Select a story in Sidebar view (page is shown in mobile view)
bild

2. Click on Canvas navlink expecting to see the selected story but instead the story gets "reset" to the first/top one in the sidebar
bild

### To Reproduce

_No response_

### System

```shell
Environment Info:

  System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
  Binaries:
    Node: 16.20.0 - ~\AppData\Local\Volta\tools\image\node\16.20.0\node.EXE
    Yarn: 4.0.0-rc.42 - ~\AppData\Local\Volta\tools\image\yarn\4.0.0-rc.42\bin\yarn.CMD
    npm: 8.19.4 - ~\AppData\Local\Volta\tools\image\node\16.20.0\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1992.0), Chromium (114.0.1823.43)
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cdedreuille**
Closes https://github.com/storybookjs/storybook/issues/24221
Closes https://github.com/storybookjs/storybook/issues/24222
Closes https://github.com/storybookjs/storybook/issues/24216
Closes #23723

## What I did

This PR is adding all the new mobile navigation and updating a few patterns to make sure actions are working on mobile as expected. The mobile navigation is consisting of 2 main drawers, one on the left for the global navigation, and one on the right for addons.

#### The changes in this PR are covered in the following automated tests:
- [x] stories
- [x] unit tests
- [x] integration tests
- [x] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

- Run Storybook locally with `yarn storybook:ui`
- Reduce your window below 600px
- You should now see the mobile navigation

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

File: code/ui/manager/src/components/mobile/navigation/MobileMenuDrawer.tsx [hunk 1]
```diff
@@ -0,0 +1,130 @@
...
+        timeout={MOBILE_TRANSITION_DURATION}
+        mountOnEnter
+        unmountOnExit
+      >
+        {(state) => (
+          <Container ref={containerRef} state={state}>
+            <Transition nodeRef={sidebarRef} in={!isAboutOpen} timeout={MOBILE_TRANSITION_DURATION}>
+              {(sidebarState) => (
+                <SidebarContainer ref={sidebarRef} state={sidebarState}>
+                  <Sidebar setAboutOpen={setAboutOpen} />
```
Comment (JReinhold) [inline code/ui/manager/src/components/mobile/navigation/MobileMenuDrawer.tsx:41]: In the Sidebar components and all it's children, this should be called `onMenuClick`, so the Sidebar doesn't need to know anything about an about page that is open or closed. it just fires the onclick, and then the drawer here will know to use that to open/close the menu

File: code/ui/manager/src/components/mobile/navigation/MobileNavigation.tsx [hunk 2]
```diff
@@ -0,0 +1,82 @@
...
+import { IconButton, Icons } from '@storybook/components';
+import { MobileMenuDrawer } from './MobileMenuDrawer';
+import { MobileAddonsDrawer } from './MobileAddonsDrawer';
+import Panel from '../../../container/Panel';
+
+interface MobileNavigationProps {
+  storyTitle?: string | null | undefined;
+}
+
+export const MobileNavigation: FC<MobileNavigationProps> = ({ storyTitle }) => {
```
Comment (JReinhold) [inline code/ui/manager/src/components/mobile/navigation/MobileNavigation.tsx:13]: I suggest we just call `useStorybookApi` directly here instead of passing `storyTitle` down here.

It might make writing stories for this component slightly more complex, but let's try.

File: code/ui/manager/src/components/upgrade/UpgradeBlock.stories.tsx [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+              getCurrentVersion: () => ({
+                version: '7.2.2-alpha.0',
+              }),
+            },
+          } as any
+        }
+      >
+        {storyFn()}
+      </ManagerContext.Provider>
+    ),
```
Comment (JReinhold) [inline code/ui/manager/src/components/upgrade/UpgradeBlock.stories.tsx:24]: I think we need the same thing in the About stories.

File: code/ui/manager/src/components/upgrade/UpgradeBlock.stories.tsx [hunk 4]
```diff
@@ -0,0 +1,34 @@
...
+  ],
+} satisfies Meta<typeof UpgradeBlock>;
+
+export default meta;
+
+type Story = StoryObj<typeof meta>;
+
+export const Default: Story = {
+  args: {},
+};
```
Comment (JReinhold) [inline code/ui/manager/src/components/upgrade/UpgradeBlock.stories.tsx:34]:
```suggestion
export const Default: Story = {};
```

File: code/ui/manager/src/components/sidebar/Menu.tsx [hunk 5]
```diff
@@ -105,11 +107,30 @@ const SidebarMenuList: FC<{
...
+    return (
+      <SidebarIconButton
+        title="Shortcuts"
+        aria-label="Shortcuts"
+        highlighted={isHighlighted}
+        active={isTooltipVisible}
+        onClick={() => setAboutOpen(true)}
+      >
+        <Icons icon="cog" />
+      </SidebarIconButton>
```
Comment (JReinhold) [inline code/ui/manager/src/components/sidebar/Menu.tsx:130]:
```suggestion
      <SidebarIconButton
        title="About Storybook"
        aria-label="About Storybook"
        highlighted={isHighlighted}
        active={false}
        onClick={onClick}
      >
        <Icons icon="cog" />
      </SidebarIconButton>
```

File: code/ui/manager/src/components/mobile/navigation/MobileNavigation.tsx [hunk 6]
```diff
@@ -0,0 +1,82 @@
...
+  const [isMenuOpen, setMenuOpen] = useState(false);
+  const [isAddonsOpen, setAddonsOpen] = useState(false);
+  const [isAboutOpen, setAboutOpen] = useState(false);
+
+  const closeMenu = () => {
+    setMenuOpen(false);
+
+    setTimeout(() => {
+      setAboutOpen(false);
+    }, 300);
```
Comment (JReinhold) [inline code/ui/manager/src/components/mobile/navigation/MobileNavigation.tsx:23]: why does this need to be in a setTimeout? I think that can cause trouble.

Maybe we can use `onExited` on the drawer transition if it's to stagger the transitions.
https://reactcommunity.org/react-transition-group/transition#Transition-prop-onExited

File: code/ui/manager/src/components/mobile/navigation/MobileNavigation.tsx [hunk 7]
```diff
@@ -0,0 +1,82 @@
...
+      <MobileMenuDrawer
+        isMenuOpen={isMenuOpen}
+        isAboutOpen={isAboutOpen}
+        setAboutOpen={setAboutOpen}
+        closeMenu={closeMenu}
+      />
+      <MobileAddonsDrawer isAddonsOpen={isAddonsOpen}>
+        <Panel closeAddonsOnMobile={closeAddons} />
+      </MobileAddonsDrawer>
+      <Button onClick={() => setMenuOpen(!isMenuOpen)}>
```
Comment (JReinhold) [inline code/ui/manager/src/components/mobile/navigation/MobileNavigation.tsx:41]:
```suggestion
      <Button onClick={() => setMenuOpen((state) => !state)}>
```

File: code/ui/manager/src/components/mobile/about/MobileAbout.stories.tsx [hunk 8]
```diff
@@ -0,0 +1,36 @@
...
+
+export default meta;
+
+type Story = StoryObj<typeof meta>;
+
+export const Default: Story = {
+  args: {
+    isAboutOpen: true,
+  },
+};
```
Comment (JReinhold) [inline code/ui/manager/src/components/mobile/about/MobileAbout.stories.tsx:36]: some stories that tests/showcases the in/out transitions would be great.

**Review by JReinhold — CHANGES_REQUESTED** [review]
overall looks good, I've requested some changes and we want stories for all the new components if possible.

File: code/ui/manager/src/components/mobile/about/MobileAbout.tsx [hunk 9]
```diff
@@ -0,0 +1,138 @@
...
+};
+
+const Container = styled.div<{ state: TransitionStatus; transitionDuration: number }>(
+  ({ theme, state, transitionDuration }) => ({
+    position: 'absolute',
+    width: '100%',
+    height: '100%',
+    top: 0,
+    left: 0,
+    zIndex: 11,
```
Comment (JReinhold) [inline code/ui/manager/src/components/mobile/about/MobileAbout.tsx:73]: why do we need to position this absolute?

Comment (cdedreuille) [reply code/ui/manager/src/components/mobile/about/MobileAbout.tsx:72]: For transitions when the about section arrive on top of the sidebar

**Comment by JReinhold** [comment]
I've made some adjustments, mainly hiding the fullscreen tool when in mobile viewport (doesn't make sense), and hiding the "open addon panel" button when in docs mode, since docs don't have panels.

**Review by JReinhold — APPROVED** [review]
💪
