### PR TITLE
Interactions: Fix state reset bug when switching stories with date mocks

### LINKED ISSUE #32834: [Bug]: SB10 Play function error state persists for a bit after visiting new stories
### Describe the bug

I'm currently on a react-vite project with a CSF Next story file, the msw and mock date addons.

I have a story designed to fail its play function (`Late`). When I visit it in the UI, and then visit other stories (e.g. `OnTime`), the interactions panel continues to show the error:

Image

The interactions addon panel seems to not update when switching stories from a story in a failure state. Specifically, it continues to show the error until I visit a story **without** play function and then visit any other story.

If I visit stories with a play function (e.g. `OnTime` and `OnTimeToo`, the error state persists indefinitely).

### Reproduction link

https://github.com/Sidnioulz/storybook-play-function-error-state-persistence-repro

### Reproduction steps

1. Go to `http://localhost:6006/?path=/story/example-frog--late`
2. Click `OnTime`
3. Notice the error stays
4. Click `OnTime Too`
5. Notice the error stays
6. Repeat _ad nauseam_

1. Go to `http://localhost:6006/?path=/story/example-frog--late`
2. Click `Medium`
3. Notice the error stays
4. Click any other story (except `Late`)
5. The error is now gone

### System

```bash
10.0.0-rc.0 Linux
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Sidnioulz**
Closes #32834 

## What I did

Forced a reset of `lastRenderId` when switching stories, to ensure we account for the fact that `Date.now()` can be mocked in a story.

#### Manual testing

1. Build a canary for this PR
2. Install it on https://github.com/Sidnioulz/storybook-play-function-error-state-persistence-repro
3. Launch Storybook
4. Go to http://localhost:6006/?path=/story/example-frog--late which triggers a caught exception state
5. Navigate to http://localhost:6006/?path=/story/example-frog--on-time-too and see the state is cleared

Without the canary, the state will not be properly cleared.

### Documentation
ø

## Checklist for Maintainers

- [x] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [x] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/publish.yml) or locally with `gh workflow run --repo storybookjs/storybook publish.yml --field pr=<PR_NUMBER>`_

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved render tracking so component testing more reliably handles switching between stories, preventing stale or concurrent render updates.
  * Added per-story update logic and an early bailout to ensure only the relevant render advances, reducing incorrect state transitions during rapid story changes or mocked-time scenarios.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: code/core/src/component-testing/components/Panel.tsx [hunk 1]
```diff
@@ -273,8 +273,16 @@ export const Panel = memo<{ refId?: string; storyId: string; storyUrl: string }>
...
+          // Update lastRenderId. When we switch stories, this value might decrease if our
+          // users have mocked Date.now() via addons or manually in their code, so we must
+          // reset lastRenderId.
+          if (lastStoryId.current === event.storyId) {
+            lastRenderId.current = Math.max(lastRenderId.current, event.renderId || 0);
+          } else {
+            lastRenderId.current = event.renderId || 0;
+          }
+
           lastStoryId.current = event.storyId;
```
Comment (ghengeveld) [inline code/core/src/component-testing/components/Panel.tsx]: You could move this line inside the else block.

File: code/core/src/component-testing/components/Panel.tsx [hunk 2]
```diff
@@ -273,8 +273,16 @@ export const Panel = memo<{ refId?: string; storyId: string; storyUrl: string }>
             return;
           }
 
+          // Update lastRenderId. When we switch stories, this value might decrease if our
+          // users have mocked Date.now() via addons or manually in their code, so we must
+          // reset lastRenderId.
+          if (lastStoryId.current === event.storyId) {
+            lastRenderId.current = Math.max(lastRenderId.current, event.renderId || 0);
+          } else {
+            lastRenderId.current = event.renderId || 0;
```
Comment (ghengeveld) [inline code/core/src/component-testing/components/Panel.tsx]: Just wondering whether this should always be `0` rather than `event.renderId`, or would that break things? Not sure.

**Review by ghengeveld — APPROVED** [review]

**Comment by ghengeveld** [comment]
@Sidnioulz is this a sufficient fix or do we still need to revisit the use of dates for this?

**Comment by Sidnioulz** [comment]
> @Sidnioulz is this a sufficient fix or do we still need to revisit the use of dates for this?

It seems sufficient. I think we can leave it at that, and if we see more issues / next time we build an ID system, we can use a global sequential counter instead.

File: code/core/src/component-testing/components/Panel.tsx (hunk 2 above)
Comment (Sidnioulz) [reply code/core/src/component-testing/components/Panel.tsx]: If we don't initialise it to the id for the current event, then we'll hit the code below that bails out when multiple concurrent renders exist.

File: code/core/src/component-testing/components/Panel.tsx (hunk 1 above)
Comment (Sidnioulz) [reply code/core/src/component-testing/components/Panel.tsx]: Good point. I've also added a comment to explain why we care about lastRenderId, and renamed it latestRenderId to
* make it easier to distinguish from lastStoryId
* clarify that we pick the latest render when it comes into effect
