### PR TITLE
NextJS: Provide mocks for useRouter from next/router and next/navigation

### LINKED ISSUE #21654: [Bug]: next/router causing issues
### Describe the bug

Stack: 
```
next: v12.1
storybook: v7.0.0-rc.3
```

There is a Button with logic that breaks the Story:
```
import Router from 'next/router';

<Button disabled={!isSSR && Router.pathname === '/signup'}/>
```

The part that breaks  is the Router.pathname . Error message:
```
No router instance found.
You should only use "next/router" on the client side of your app.
```

I tried experimenting with nextjs object inside story, like so, but it didn't help:
```
  nextjs: {
    router: {
      basePath: '/',
      route: '/signup',
    },
  },
```

Any help with this?

### To Reproduce

[arianaamx-motorway/next-router-no-router-instance-found](https://github.com/arianaamx-motorway/next-router-no-router-instance-found)

Stackblitz DEMO: https://stackblitz.com/github/arianaamx-motorway/next-router-no-router-instance-found?file=stories/pages/HomePage/HomePage.tsx

### System

```shell
Environment Info:

  System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Firefox: 111.0
    Safari: 15.6.1
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-rc.3 => 7.0.0-rc.3 
    @storybook/addon-interactions: ^7.0.0-rc.3 => 7.0.0-rc.3 
    @storybook/addon-links: ^7.0.0-rc.3 => 7.0.0-rc.3 
    @storybook/blocks: ^7.0.0-rc.3 => 7.0.0-rc.3 
    @storybook/nextjs: ^7.0.0-rc.3 => 7.0.0-rc.3 
    @storybook/react: ^7.0.0-rc.3 => 7.0.0-rc.3 
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1 
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yannbf**
Closes # (I'm sure there is an issue or discussion about this, but I couldn't find)
Closes #21654 (extra fix)

## What I did

This PR introduces two new entrypoints: `@storybook/nextjs/router` and `@storybook/nextjs/navigation` which map to `next/router` and `next/navigation`. These entrypoints provide a `useRouter` export which gives users access to router mocks which are applied in Storybook for NextJS. This allows them to assert whether methods have been called, e.g. `router.push`. 

```tsx
// Component.tsx
import React from 'react';
import { useRouter } from 'next/navigation';

export default function Component() {
  const router = useRouter();
  return (
      <>
        <button type="button" onClick={() => router.forward()}>
           Forward
         </button>
        <button type="button" onClick={() => router.prefetch('/some-route')}>
           Prefetch
         </button>
      </>)
}
```

```tsx
// Component.stories.tsx
import Component from './Component';
import { useRouter } from '@storybook/nextjs/navigation';

export default {
  component: Component,
parameters: {
    nextjs: {
      router: {
        // custom prefetch hook, will still be turned into a spy
        prefetch: () => {
          console.log('custom prefetch');
        },
      },
    },
  },
};

export const Default = {
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step('Asserts whether forward hook is called', async () => {
      const forwardBtn = await canvas.findByText('Go forward');
      await userEvent.click(forwardBtn);
      await expect(useRouterMock().forward).toHaveBeenCalled();
    });

    await step('Asserts whether custom prefetch hook is called', async () => {
      const prefetchBtn = await canvas.findByText('Prefetch');
      await userEvent.click(prefetchBtn);
      await expect(useRouterMock().prefetch).toHaveBeenCalledWith('/prefetched-html');
    });
  },
};
```

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Review by JReinhold — APPROVED** [review]
✨

File: code/frameworks/nextjs/src/routing/navigation/index.ts [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+      });
+    }
+
+    navigationAPI = navigationActions;
+  }
+
+  return navigationAPI;
+};
+
+export const useRouter = () => {
```
Comment (kasperpeulen) [inline code/frameworks/nextjs/src/routing/navigation/index.ts:41]: I think we should call this `getRouter` as we will re-export `useRouter` once we fully mock next/navigation (including `redirect` etc.)

File: code/frameworks/nextjs/src/routing/router/index.ts [hunk 2]
```diff
@@ -0,0 +1,103 @@
...
+export const createRouter = (overrides: Partial<NextRouter>) => {
+  if (!routerAPI) {
+    const routerActions: Partial<NextRouter> = {
+      push: fn((..._args: any[]) => {
+        return Promise.resolve(true);
+      }).mockName('nextRouter.push'),
+      replace: fn((..._args: any[]) => {
+        return Promise.resolve(true);
+      }).mockName('nextRouter.replace'),
+      reload: fn((..._args: any[]) => {}).mockName('nextRouter.reload'),
```
Comment (kasperpeulen) [inline code/frameworks/nextjs/src/routing/router/index.ts:43]: Maybe `useRouter().reload` as name?

File: test-storybooks/portable-stories-kitchen-sink/nextjs/stories/Navigation.stories.tsx [hunk 3]
```diff
@@ -73,9 +75,29 @@ export default {
...
       },
     },
   },
 } as Meta<typeof Component>;
 
-export const Default: StoryObj<typeof Component> = {};
+export const Default: StoryObj<typeof Component> = {
+  play: async ({ canvasElement, step }) => {
+    const canvas = within(canvasElement);
+    const routerMock = useRouterMock();
```
Comment (kasperpeulen) [inline test-storybooks/portable-stories-kitchen-sink/nextjs/stories/Navigation.stories.tsx:89]: I think renaming this to `getRouter` is also better to avoid hook linter problems.

**Review by JReinhold — APPROVED** [review]
