### PR TITLE
React: Fix several CSF factory bugs 

### LINKED ISSUE #32620: [Bug]: SB10 - CSF Next issue with exported actions from `storybook/test`
### Describe the bug

When a user attempted to migrate from CSF to CSF Next by following the [documentation](https://storybook.js.org/docs/api/csf/csf-next), and attempting to export the `fn` function from `storybook/test` to use it in various stories, they will run cryptic errors in the Storybook UI that do not provide much context about the root cause of the issue, nor how to resolve it. This is a pattern that users may want to use to avoid duplicating the same action definitions across multiple stories/tests and instead have a single source of truth for them to use throughout their projects.

This can be observed in the following screenshot:

Image

### Reproduction link

N/A

### Reproduction steps

1. Create a small Storybook project using the latest Storybook stable version (e.g., 9.1.6)
2. Create a component with the following code:
```tsx
// src/components/Task.tsx
import type { TaskData } from "../types";

type TaskProps = {
  /** Composition of the task */
  task: TaskData;
  /** Event to change the task to archived */
  onArchiveTask: (id: string) => void;
  /** Event to change the task to pinned */
  onPinTask: (id: string) => void;
};

export default function Task({
  task: { id, title, state },
  onArchiveTask,
  onPinTask,
}: TaskProps) {
  return (
    <div className={`list-item ${state}`}>
      <label
        htmlFor={`archiveTask-${id}`}
        aria-label={`archiveTask-${id}`}
        className="checkbox"
      >
        <input
          type="checkbox"
          disabled={true}
          name="checked"
          id={`custom-archiveTask-${id}`}
          aria-label={`custom-archiveTask-${id}`}
          checked={state === "TASK_ARCHIVED"}
        />
        <span
          className="checkbox-custom"
          onClick={() => onArchiveTask(id)}
          aria-label={`custom-archiveTask-checkbox-${id}`}
        />
      </label>

      <label htmlFor={`title-${id}`} aria-label={title} className="title">
        <input
          type="text"
          value={title}
          readOnly={true}
          name="title"
          id={`title-${id}`}
          placeholder="Input title"
        />
      </label>
      {state !== "TASK_ARCHIVED" && (
        <button
          className="pin-button"
          onClick={() => onPinTask(id)}
          id={`pinTask-${id}`}
          aria-label={`pinTask-${id}`}
          key={`pinTask-${id}`}
        >
          <span className={`icon-star`} />
        </button>
      )}
    </div>
  );
}
```

3. Create the following story that exports the `fn` function from `storybook/test`:

```ts
// src/components/Task.stories.tsx

import type { Meta, StoryObj } from "@storybook/react-vite";

import { fn } from "storybook/test";

import Task from "./Task";

export const ActionsData = {
  onArchiveTask: fn(),
  onPinTask: fn(),
};

const meta = {
  component: Task,
  title: "Task",
  tags: ["autodocs"],
  //👇 Our exports that end in "Data" are not stories.
  excludeStories: /.*Data$/,
  args: {
    ...ActionsData,
  },
} satisfies Meta<typeof Task>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    task: {
      id: "1",
      title: "Test Task",
      state: "TASK_INBOX",
    },
  },
};

export const Pinned: Story = {
  args: {
    task: {
      ...Default.args.task,
      state: "TASK_PINNED",
    },
  },
};

export const Archived: Story = {
  args: {
    task: {
      ...Default.args.task,
      state: "TASK_ARCHIVED",
    },
  },
};
```
4. Upgrade to the latest beta (i.e., 10.0.0-beta.8)
5.  Follow the migration steps from CSF to CSF Next as outlined in the documentation and migrate the story to CSF Next using the command: `npx storybook automigrate csf-factories` to convert the story to CSF Next format using subpath imports that yield the following code:
```tsx
// src/components/Task.stories.tsx
import preview from "#.storybook/preview";

import { fn, expect } from "storybook/test";

import Task from "./Task";

export const ActionsData = {
  onArchiveTask: fn(),
  onPinTask: fn(),
};

const meta = preview.meta({
  component: Task,
  title: "Task",
  tags: ["autodocs"],
  //👇 Our exports that end in "Data" are not stories.
  excludeStories: /.*Data$/,
  args: {
    ...ActionsData,
  },
});

export const Default = meta.story({
  args: {
    task: {
      id: "1",
      title: "Test Task",
      state: "TASK_INBOX",
    },
  },
});

export const Pinned = meta.story({
  args: {
    task: {
      ...Default.input.args.task,
      state: "TASK_PINNED",
    },
  },
});

export const Archived = meta.story({
  args: {
    task: {
      ...Default.input.args.task,
      state: "TASK_ARCHIVED",
    },
  },
});
```

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 15.0.1
    CPU: (8) arm64 Apple M3
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.19.2 - ~/.nvm/versions/node/v20.19.2/bin/node
    Yarn: 4.9.2 - /usr/local/bin/yarn <----- active
    npm: 10.8.2 - ~/.nvm/versions/node/v20.19.2/bin/npm
  Browsers:
    Chrome: 140.0.7339.214
    Edge: 140.0.3485.94
    Safari: 18.0.1
  npmPackages:
    @storybook/addon-docs: ^10.0.0-beta.8 => 10.0.0-beta.8
    @storybook/addon-vitest: ^10.0.0-beta.8 => 10.0.0-beta.8
    @storybook/react-vite: ^10.0.0-beta.8 => 10.0.0-beta.8
    eslint-plugin-storybook: ^10.0.0-beta.8 => 10.0.0-beta.8
    msw-storybook-addon: ^2.0.5 => 2.0.5
    storybook: ^10.0.0-beta.8 => 10.0.0-beta.8
```

### Additional context

_No response_

### LINKED ISSUE #32831: [Bug]: CSF-factories: No type error without argument to meta.story()
### Describe the bug

I would expect to get an error when using meta.story() if there are required args, but I don't pass any object in.

### Reproduction link

https://github.com/IanVS/csf-factories-issues/commit/9c34239bb1c99b01235ea966d295453aeb86e8e5

### Reproduction steps

Clone and install the project, see _no_ typescript error in Button.stories.tsx, when there should be one, when using `meta.story()`.  

### System

```bash
System:
    OS: macOS 15.6.1
    CPU: (12) arm64 Apple M2 Max
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.13.1 - ~/.local/state/fnm_multishells/66831_1761232943323/bin/node
    npm: 11.6.0 - ~/.local/state/fnm_multishells/66831_1761232943323/bin/npm
    pnpm: 9.15.0 - ~/.local/state/fnm_multishells/66831_1761232943323/bin/pnpm <----- active
  Browsers:
    Edge: 141.0.3537.92
    Safari: 18.6
  npmPackages:
    @storybook/react-vite: 10.0.0-rc.0 => 10.0.0-rc.0
    eslint-plugin-storybook: 10.0.0-rc.0 => 10.0.0-rc.0
    storybook: 10.0.0-rc.0 => 10.0.0-rc.0
```

### Additional context

_No response_

### LINKED ISSUE #33024: [Bug]: CSF-Factories: Type errors with meta.input.play and meta.play is undefined
### Describe the bug

In Storybook 10 using the CSF Next factories you are unable to invoke a `play` function defined in the `meta`. This was previously possible in CSF 3.

Example setup:
```ts
const meta = preview.meta({
    /** title, component, etc... */
    play: async ({ canvas }) => {
        /** Do some common interactions */
    },
})

export const DefaultStory = meta.story()

export const ExtendedInteractionsStory = meta.story({
    play: async ({ canvas, ...rest }) => {
        await meta.play({ canvas, ...rest })

        /** Do some extra interactions */
    },
})
```

In the above example `meta.play` does not exist, and will fail at runtime.

You can make this work at runtime by using `meta.input.play`, but this causes a type error as it believes `args` is the only property that can exist on `meta.input`.

Running `npx storybook automigrate csf-factories` currently does not transform the `meta.play` invocations, causing the stories to fail.

Additionally, based on the above example, `DefaultStory.play` also works at runtime, but produces a similar type error. It does not work using `DefaultStory.composed.play`.

## Expected:
1. If `play` is defined in `meta`, you can invoke `meta.play` or `meta.input.play` without type errors.
2. If `play` is defined in `meta`, and not present on a story (e.g. "DefaultStory" above), another story can invoke `DefaultStory.play` and/or `DefaultStory.composed.play` without type errors.

### Reproduction link

https://github.com/AlexAtVista/storybook-csf-next-meta-play-types-error

### Reproduction steps

1. Clone the [replication repo](https://github.com/AlexAtVista/storybook-csf-next-meta-play-types-error) and run `npm install`
2. View the src/Page.stories.ts file
3. Run `npm run storybook`
4. View the interactions panel for each issue replication story

### System

```bash
System:
    OS: macOS 26.1
    CPU: (10) arm64 Apple M4
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.19.2 - ~/.nvm/versions/node/v20.19.2/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.19.2/bin/npm <----- active
  Browsers:
    Chrome: 142.0.7444.135
    Edge: 142.0.3595.65
    Safari: 26.1
  npmPackages:
    @storybook/addon-a11y: ^10.0.7 => 10.0.7 
    @storybook/addon-docs: ^10.0.7 => 10.0.7 
    @storybook/addon-onboarding: ^10.0.7 => 10.0.7 
    @storybook/addon-vitest: ^10.0.7 => 10.0.7 
    @storybook/react-vite: ^10.0.7 => 10.0.7 
    eslint-plugin-storybook: ^10.0.7 => 10.0.7 
    storybook: ^10.0.7 => 10.0.7
```

### Additional context

Originally raised on Discord:
https://discord.com/channels/486522875931656193/1438109436928593961

### PR DESCRIPTION
**Pull request by kasperpeulen**
Closes #32620, Closes #32831, Closes #33024

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/publish.yml) or locally with `gh workflow run --repo storybookjs/storybook publish.yml --field pr=<PR_NUMBER>`_

## Summary by CodeRabbit

* **New Features**
  * Play handlers can be composed via meta-level input, allowing story-level play to forward to meta.input.play.

* **Refactor**
  * More accurate story selection and richer metadata collection, including parameter checks and inclusion of child (test) stories with IDs.
  * Project-level composed preview source now follows the selected factory story.
  * Stricter React preview typings and new overloads for more precise args handling.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: code/renderers/react/src/preview.tsx [hunk 1]
```diff
@@ -76,7 +77,19 @@ export interface ReactPreview<T extends AddonTypes> extends Preview<ReactTypes &
           TArgs & Simplify<RemoveIndexSignature<DecoratorsArgs<ReactTypes & T, Decorators>>>
         >;
       },
-    { args: Partial<TArgs> extends TMetaArgs ? {} : TMetaArgs }
+    Omit<
```
Comment (yannbf) [inline code/renderers/react/src/preview.tsx:81]: Can you add a comment explaining what's going on?

File: code/renderers/react/src/preview.tsx [hunk 2]
```diff
@@ -108,9 +121,18 @@ export interface ReactMeta<T extends ReactTypes, MetaInput extends ComponentAnno
       >
     >,
   >(
-    story?: TInput
+    story: TInput
     /** @ts-expect-error hard */
   ): ReactStory<T, TInput>;
+
+  story(
```
Comment (yannbf) [inline code/renderers/react/src/preview.tsx:123]: Can you add a comment here to explain what's going on?

**Review by yannbf — APPROVED** [review]

**Review by jesn459 — COMMENTED** [review]
Graviss
