### PR TITLE
Angular: Remove cached NgModules and introduce a global queue during bootstrapping

### LINKED ISSUE #23875: [Bug]: Cannot Render Same Story Twice in Docs (Angular)
### Describe the bug

The error described at #15170 seems to be introduced again in Storybook 7 for Angular.
I cannot render a story twice in the docs; both story entries in HTML have the same id.

```
<Story of={ButtonStories.Primary}/>
<Story of={ButtonStories.Primary}/>
```

### To Reproduce

_No response_

### System

_No response_

### Additional context

_No response_

### LINKED ISSUE #24813: [Bug]: Missing ng* parameters for elements injected with ng-content (Angular)
### Describe the bug

I am overriding the template in the render method using Angular as follow:
```
render: (badge) => ({
        template: `
        <ds-badge variant="${badge.variant}" size="${badge.size}" label="${badge.label}">
            <ds-counter slot="start" type="${badge.icon}">10</ds-counter>
        </ds-badge>
        `
    })
```

where the ds-badge component contains following HTML
```
<ng-content select="[slot=start]"/>
<span class="badge-text">{{label}}</span>
<ng-content select="[slot=end]"/>
```

This results in docs being rendered as the following HTML:
```
<ds-badge variant="primary" size="medium" label="LABEL" _nghost-ng-c3862264782="" ng-reflect-variant="primary" ng-reflect-size="medium" ng-reflect-label="LABEL" class="medium primary shared">
  <ds-counter slot="start" type="primary">10</ds-counter>
  <span _ngcontent-ng-c3862264782="" class="badge-text">LABEL</span>
</ds-badge>
```

As soon as I change a property in the controls, it gets updated to (which is correct)
```
<ds-badge variant="primary" size="medium" label="LABE" _nghost-ng-c3862264782="" ng-reflect-variant="primary" ng-reflect-size="medium" ng-reflect-label="LABE" class="medium primary shared">
  <ds-counter slot="start" type="primary" _nghost-ng-c2123879280="" ng-reflect-type="primary" class="medium primary shared">10</ds-counter>
  <span _ngcontent-ng-c3862264782="" class="badge-text">LABE</span>
</ds-badge>
```
So, the initial rendering of the docs somehow does not initialize the elements injected with ngcontent as the _ng* parameters are missing on the ds-counter component.

### To Reproduce

https://stackblitz.com/~/github.com/markusnissl/storybook-demo

You see the background color of the number 10 is changing after the first interaction (Badge Component, With Counter).

### System

```bash
Storybook Environment Info:

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm <----- active
    pnpm: 8.9.2 - /usr/local/bin/pnpm
  npmPackages:
    @storybook/addon-essentials: ^7.5.3 => 7.5.3 
    @storybook/addon-interactions: ^7.5.3 => 7.5.3 
    @storybook/addon-links: ^7.5.3 => 7.5.3 
    @storybook/addon-styling: ^1.3.7 => 1.3.7 
    @storybook/angular: ^7.5.3 => 7.5.3 
    @storybook/blocks: ^7.5.3 => 7.5.3 
    @storybook/testing-library: ^0.2.2 => 0.2.2 
    storybook: ^7.5.3 => 7.5.3
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Marklb**
Closes #24813

## What I did

Problem: Caching the NgModule per component, causes the NgModule generated for the first story to get used for the following stories, but they may not have generated the same NgModule.

### Explanation:

Assume the following is the CSF file:
```ts
export default {
  component: FooComponent,
}

export const Primary = { }
export const Secondary = {
  moduleMetadata: {
    declarations: [ BarComponent ],
  },
}
```

In the renderer, the following is basically what the NgModule would be for each story:
```ts
// Primary
@NgModule({
  declarations: [ FooComponent ],
})
class StorybookModule {}

// Secondary
@NgModule({
  declarations: [ FooComponent, BarComponent ],
})
class StorybookModule {}
```

When using inline rendering to render both stories in a single document, Storybook attempts to render each story, without waiting on the previous to complete. The problem is that Angular only allows a component to be declared by a single NgModule, so we have to clear the compiled component cache after each story's app is initialized.

The solution being used currently, would cache the NgModule by the `component` defined in `Meta`. That avoids the error, but breaks the "Secondary" story, because `BarComponent` is not declared in the NgModule that was cached when the "Primary" story rendered (*Assuming the "Primary" story rendered first.*).

I don't know if the way inline stories render changed and used to wait for completion of each story or if it just wasn't fully implemented as expected. `AbstractRenderer` already has a method that calls `ɵresetCompiledComponents` and both `CanvasRenderer` and `DocsRenderer` call it after a full render. The problem is two render methods can be running in parallel, which makes the reset not work correctly.

To fix `ɵresetCompiledComponents` not getting called correctly, a queue is introduced to the `AbstractRenderer` that prevents calling `bootstrapApplication` in parallel. This may have an effect on performance, if a particular story is slow to initialize, but I don't know of another way to avoid conflicts between each Angular application's compiling.

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [x] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

To see the problem with caching the NgModule, 
1. Run a sandbox for template, e.g. `yarn task --task sandbox --start-from auto --template angular-cli/default-ts`
2. In the sandbox file `stories/core/decorators/componentWrapperDecorator/decorators.stories.ts`, add `tags: ['autodocs']` to the default export `Meta`.
3. Open Storybook in your browser
4. Access "frameworks > angular > core > decorators > componentWrapperDecorator > decorators > Docs" stories. Before this change, all the stories render something, but any of the stories declaring `ParentComponent` threw an error, because the first story did not declare `ParentComponent`. With this change all should render correctly.

To see the reason for adding the lock, instead of just removing the NgModule caching, you can do the same steps, but comment out `await acquireLock(selector);` in the the `bootstrapLock` function in `code/frameworks/angular/src/client/angular-beta/utils/BootstrapLock.ts`. Commenting that line would disable the lock and cause the *multiple modules declaring component* error that the caching was supposed to fix.

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Comment by valentinpalkovic** [comment]
@Marklb Thank you so much for figuring out the root cause of the issue. This was the missing peace. I am so grateful that you dived deep into it! 

I have thought about your solution, which works great. The only thing might be that renderings might happen in no particular order. I have pushed a different approach using queues. WDYT?

**Comment by valentinpalkovic** [comment]
No pressure! I will wait for your proper feedback. I also changed when the compiled modules got reset in the latest commit because otherwise, your newly written test case of mounting two angular components at once would fail.

File: code/frameworks/angular/src/client/angular-beta/utils/BootstrapLock.ts [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+};
+
+const processQueue = async () => {
+  isProcessing = true;
+
+  while (queue.length > 0) {
+    const bootstrappingFn = queue.shift();
+    if (bootstrappingFn) {
+      await bootstrappingFn();
+      await resetCompiledComponents();
```
Comment (Marklb) [inline code/frameworks/angular/src/client/angular-beta/utils/BootstrapLock.ts:45]: I haven't tested to see if it would work, but do you think it would make more sense to call this before bootstrapping or keep it after?

The following are my two thoughts:
1. By keeping it after, there may be more consistent usage.
2. If before, it should still prevent conflict with a previous render, but allow usage of not resetting. I don't know if `resetCompiledComponents` can have an effect on lazy loaded modules that aren't part of the initial render. I assume most situations that render multiple stories are dealing more with a documentation scenario, but if `resetCompiledComponents` is hiding an error that would typically happen, would it be better to not call it after? An isolated render in Canvas view could then expose that error, if possible. Of course, then we run into a situation of potential render inconsistency between Canvas and Docs.

**Comment by Marklb** [comment]
I updated a test to be more thorough, adjusted the names and wording from "lock" to "queue", and added back the comment explaining why the queue is necessary.

Other than getting your opinion on the questions I added about the `resetCompiledComponents` move, the changes look good to me.

File: code/frameworks/angular/src/client/angular-beta/utils/BootstrapLock.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (valentinpalkovic) [reply code/frameworks/angular/src/client/angular-beta/utils/BootstrapLock.ts]: > By moving this here, doesn't it prevent anyone from having the option of implementing a renderer that doesn't reset compiled components?

You're right. In `@storybookjs/testing-angular,` I haven't found where you are inheriting from `AbstractRenderer,` though. I guess you mentioned, in general, that people might use it to implement a custom renderer, which inherits from `AbstractRenderer`. I used the GitHub search, and I was not able to find any custom renderer inheriting `AbstractRenderer`. Could you find some to figure out whether this is a real problem? But I would guess we can avoid calling `resetCompiledComponents` in the lock function. Do you have an idea how we might avoid it?

Comment (valentinpalkovic) [reply code/frameworks/angular/src/client/angular-beta/utils/BootstrapLock.ts]: I agree with your thoughts. I guess we can try it out to place it before? Technically, this might be a breaking change in behavior, but since we have started to work on 8.0.0, we will not release another minor release of Storybook 7.x. I would vote to turn around the logic, as you mentioned.

[the remark this answers is not in the document]
Comment (Marklb) [reply code/frameworks/angular/src/client/angular-beta/utils/BootstrapLock.ts]: I am not sure how to best avoid it, at the moment. That can maybe wait for another PR, if necessary.

When I mentioned `@storybookjs/testing-angular`, I was just using it as an example, but forgot the renderer in that package isn't actually a render and doesn't extend `AbstractRenderer`. It is basically the renderer, without the bootstrapping part, because I create a component that can render the story and let the user's chosen test framework handle using it. So, this actually doesn't apply to it.

**Comment by valentinpalkovic** [comment]
Hi @Marklb 

Could you try to resolve the conflicts? Then, I will give CI another try. If it still fails, I will take a look!

**Comment by Marklb** [comment]
@valentinpalkovic The conflicts should be fixed now.

**Comment by valentinpalkovic** [comment]
Great! I will take a look tomorrow at why CI is failing

**Comment by Marklb** [comment]
I tried to update the tests for vitest, but I am not familiar with vitest, yet. The `BootstrapQueue` tests sometimes pass and sometimes fail. After debugging, it seems that the tests are running in parallel, without being isolated. I am not positive that is what happens, but stepping through breakpoints, once a test does something async the next test starts then the next sync action will go back to a breakpoint in the first test.

I am just assuming that is the problem and maybe I need to add something to stop that or that isn't even the problem, but I will look into it later, when I have more time to dig into it.

**Comment by valentinpalkovic** [comment]
Thanks for taking care of it! I try to support you as soon as I have some free resources. 

But maybe, first of all, it would make sense to understand why the UI Test in Chromatic fails.

Regarding the unit test: Can we run the whole test suite and its tasks sequentially? Maybe Vitest offers some options for doing so exclusively for a particular test suite.

File: code/frameworks/angular/src/client/angular-beta/utils/BootstrapLock.ts (hunk 1 above)
Comment (valentinpalkovic) [reply code/frameworks/angular/src/client/angular-beta/utils/BootstrapLock.ts]: @Marklb Keeping the reset before the actual rendering was [causing issues](https://www.chromatic.com/build?appId=6322ce6af69825592bbb28fc&number=8400). In particular, registered modules like the `CommonModule weren't available. This has lead to styles not being applies since the CommonModule is necessary for the `styles` attribute being applied.

**Review by valentinpalkovic — APPROVED** [review]
