### PR TITLE
Addon Test: Wrap sub-paths exported with `require.resolve`

### LINKED ISSUE #29785: [Bug]: `Error: Cannot find module '@storybook/experimental-addon-test/internal/coverage-reporter'` in monorepo setups
In certain monorepo scenarios, Vitest can fail to resolve `@storybook/experimental-addon-test/internal/coverage-reporter` if it has been hoisted or similar. We are not in control of this resolution, we simply pass in a string to a custom coverage reporter. See docs at:

https://vitest.dev/guide/coverage.html#custom-coverage-reporter

The problem is here on line 45:

https://github.com/storybookjs/storybook/blob/08dca94c3754e6eb8dcebed3d3ef30f384133964/code/addons/test/src/node/vitest-manager.ts#L44-L50

We could try to use `require.resolve` (or the ESM equivalent) to get an absolute path at runtime (relative to the current file) instead of referencing the export of our package.

## Reproduction

https://github.com/gawdfrey/storybook-experimental-monorepo

1. `npm install`
2. `npm run build`
3. `npm run dev`
4. Go to `localhost:6006` and try to run a test with coverage enabled, you should see error in console.

### PR DESCRIPTION
**Pull request by ndelangen**
Closes #29785

## What I did

- [x] wrap the sub exports with `require.resolve`

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

I manually verified this resolved the problem by copying and pasting `node_modules` `dist` files into the repro supplied in the issue.

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

| name | before | after | diff | z | % |
| ---- | ------ | ----- | ---- | - | - |
| createSize |  0 B | 0 B | 0 B | - | - |
| generateSize |  77.7 MB | 77.7 MB | 0 B | 0.91 | 0% |
| initSize |  133 MB | 133 MB | 0 B | **1.71** | 0% |
| diffSize |  55.2 MB | 55.2 MB | 0 B | **3.82** | 0% |
| buildSize |  6.87 MB | 6.87 MB | 0 B | -0.73 | 0% |
| buildSbAddonsSize |  1.51 MB | 1.51 MB | 0 B | **-4.22** | 0% |
| buildSbCommonSize |  195 kB | 195 kB | 0 B | - | 0% |
| buildSbManagerSize |  1.86 MB | 1.86 MB | 0 B | 0.23 | 0% |
| buildSbPreviewSize |  0 B | 0 B | 0 B | - | - |
| buildStaticSize |  0 B | 0 B | 0 B | - | - |
| buildPrebuildSize |  3.57 MB | 3.57 MB | 0 B | -1.18 | 0% |
| buildPreviewSize |  3.3 MB | 3.3 MB | 0 B | 0.23 | 0% |
| testBuildSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbAddonsSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbCommonSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbManagerSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbPreviewSize |  0 B | 0 B | 0 B | - | - |
| testBuildStaticSize |  0 B | 0 B | 0 B | - | - |
| testBuildPrebuildSize |  0 B | 0 B | 0 B | - | - |
| testBuildPreviewSize |  0 B | 0 B | 0 B | - | - |

| name | before | after | diff | z | % |
| ---- | ------ | ----- | ---- | - | - |
| createTime |  15s | 24.9s | 9.9s | **2.38** | 🔺39.9% |
| generateTime |  45.4s | 20.3s | -25s -60ms | -0.38 | -123.1% |
| initTime |  29.3s | 13.1s | -16s -168ms | -0.52 | -122.7% |
| buildTime |  8.7s | 8.5s | -262ms | **-1.25** | -3.1% |
| testBuildTime |  0ms | 0ms | 0ms | - | - |
| devPreviewResponsive |  4.2s | 4.9s | 730ms | -0.55 | 14.8% |
| devManagerResponsive |  3.1s | 3.7s | 616ms | -0.14 | 16.3% |
| devManagerHeaderVisible |  504ms | 574ms | 70ms | -0.1 | 12.2% |
| devManagerIndexVisible |  565ms | 590ms | 25ms | -0.52 | 4.2% |
| devStoryVisibleUncached |  1.7s | 1.7s | -19ms | -0.45 | -1.1% |
| devStoryVisible |  564ms | 656ms | 92ms | 0.36 | 14% |
| devAutodocsVisible |  425ms | 507ms | 82ms | -0.36 | 16.2% |
| devMDXVisible |  432ms | 352ms | -80ms | **-2.67** | 🔰-22.7% |
| buildManagerHeaderVisible |  500ms | 609ms | 109ms | 0.09 | 17.9% |
| buildManagerIndexVisible |  593ms | 694ms | 101ms | 0.02 | 14.6% |
| buildStoryVisible |  465ms | 559ms | 94ms | 0.27 | 16.8% |
| buildAutodocsVisible |  400ms | 481ms | 81ms | 0.41 | 16.8% |
| buildMDXVisible |  366ms | 474ms | 108ms | 0.42 | 22.8% |

## Greptile Summary

This PR fixes module resolution issues in monorepo setups by using `require.resolve` to get absolute paths for coverage reporter and setup files in the Storybook test addon.

- Added `packageDir` constant using `require.resolve` and `dirname` to get absolute package root path in `vitest-manager.ts`
- Updated coverage reporter path in `vitest-manager.ts` to use absolute path with `join(packageDir, 'dist/node/coverage-reporter.js')`
- Modified setup file paths in `vitest-plugin/index.ts` to use absolute paths with `packageDir` 
- Fixed issue where Vitest failed to resolve `@storybook/experimental-addon-test/internal/coverage-reporter` in monorepo environments

### CODE REVIEW

File: code/addons/test/src/node/vitest-manager.ts [hunk 1]
```diff
@@ -1,4 +1,5 @@
 import { existsSync } from 'node:fs';
+import { dirname, join } from 'node:path';
```
Comment (JReinhold) [inline code/addons/test/src/node/vitest-manager.ts:2]: We've agreed in the team to use `pathe` instead of `node:path` when we can.

(should have an eslint rule I guess. 🤷)

**Review by JReinhold — COMMENTED** [review]
The two other instances besides the coverage, did you find issues with those aswell or did you just think that it would be better overall with the `require.resolve` pattern? did you discover anything in the monorepo reproduction?

File: code/addons/test/src/node/vitest-manager.ts (hunk 1 above)
Comment (ndelangen) [reply code/addons/test/src/node/vitest-manager.ts:2]: I did not find other issues, but I figured I'd be consistent and figured it would fail sooner or later.

**Review by JReinhold — APPROVED** [review]
