### PR TITLE
Core: Fix conflicting staticDirs case when -s flag is used

### LINKED ISSUE #21564: [Bug]: Storybook build breaks with "Error: Conflict when trying to read staticDirs" when using -s flag
### Describe the bug

Due to a change in @storybook/manager, there are now default `staticDirs` which come from a preset:

```ts
staticDirs: [
    {
      from: '/Users/yannbraga/open-source/design-system/node_modules/@storybook/manager/static',
      to: '/sb-common-assets'
    }
  ],
```

Because of that, and an internal logic [here](https://github.com/storybookjs/storybook/blob/next/code/lib/core-server/src/build-static.ts#L117), Storybook's that just run with `-s` flag, now fail.

### To Reproduce

1. Create a Storybook 7 sandbox
2. Change script to use -s flag
3. Run storybook build
4. See failure

### System

_No response_

### Additional context

It seems like this issue happened in dev mode before, and was fixed [this way](https://github.com/storybookjs/storybook/blob/next/code/lib/core-server/src/utils/server-statics.ts#L18). Probably simple to fix in build mode as well

### PR DESCRIPTION
**Pull request by valentinpalkovic**
Closes https://github.com/storybookjs/storybook/issues/21564

## What I did

Fixed conflicting staticDirs case when -s flag is used

## How to test

1. Run a sandbox for template, e.g. `yarn task --task sandbox --start-from auto --template react-vite/default-ts`
2. Change build script to use -s flag
3. Run storybook build -> Does not fail anymore

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [x] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

File: code/lib/core-server/src/build-static.ts [hunk 1]
```diff
@@ -114,7 +116,7 @@ export async function buildStaticStandalone(options: BuildStaticStandaloneOption
     features,
   };
 
-  if (staticDirs && options.staticDir) {
+  if (options.staticDir && !isEqual(staticDirs, defaultStaticDirs)) {
```
Comment (yannbf) [inline code/lib/core-server/src/build-static.ts:119]: If we could do this without lodash I guess it'd be nicer, but if we can't that's fine too!

**Review by yannbf — APPROVED** [review]
