### PR TITLE
Addon Docs: Fix [Object object] displayName in some JSX components

### LINKED ISSUE #20920: [Bug]: Show code displays `<[object Object]...` instead of component name
### Describe the bug

Components that are wrapped with `forwardRef` in react are not displaying the proper name in built Storybook, whole working as expected in development mode. Example of what I mean in the image below.

image

Tried to debug by modifying and logging what is passed here: https://github.com/storybookjs/storybook/blob/next/code/renderers/react/src/docs/jsxDecorator.tsx#L108

image

and indeed the element is different in dev vs prod.

After digging with the help of @IanVS and @JReinhold found out that this might be an issue with `react-docgen-typescript` and `tsconfig.json` of the project.

### To Reproduce

```shell
Visit this link: https://github.com/konsalex/design-system-newline-course/tree/storybook-v7-issue
Clone then:


// Install packages
yarn
yarn workspace @newline-ds/foundation build
yarn workspace @newline-ds/react build

// Build and run
yarn workspace @newline-ds/storybook build-storybook && live-server packages/storybook/storybook-public
```
```


### System

```shell
Environment Info:

  System:
    OS: macOS 13.0
    CPU: (10) x64 Apple M1 Max
  Binaries:
    Node: 16.19.0 - ~/Library/Caches/fnm_multishells/44085_1675428690209/bin/node
    Yarn: 3.2.1 - /usr/local/bin/yarn
    npm: 8.19.3 - ~/Library/Caches/fnm_multishells/44085_1675428690209/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 109.0
    Safari: 16.1
```

### Additional context

_No response_

### LINKED ISSUE #26503: [Bug]: Story source is showing `[object Object]` instead of the component name
### Describe the bug

In Storybook v8, when creating a story in CSF format, the source code shown does not include the name of the component, but rather `[object Object]`.

### To Reproduce

```
export const MaxLines: Story = {
  args: {
    children: `This is some content to render.`,
    variant: 'body1',
  },
  name: 'Basic typography',
  parameters: {
    docs: {
      canvas: {
        sourceState: 'shown',
      },
    },
  },
};
```

Outputs:

```
<[object Object]
  variant="body1"
>
  This is some content to render.
</[object Object]>
```

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.3
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    npm: 10.2.5 - ~/.nvm/versions/node/v18.19.0/bin/npm <----- active
  Browsers:
    Chrome: 122.0.6261.128
    Edge: 122.0.2365.80
    Safari: 17.3
  npmPackages:
    @storybook/addon-a11y: ^8.0.0 => 8.0.0 
    @storybook/addon-coverage: ~1.0.1 => 1.0.1 
    @storybook/addon-designs: ~8.0.0 => 8.0.0 
    @storybook/addon-essentials: ^8.0.0 => 8.0.0 
    @storybook/addon-interactions: ^8.0.0 => 8.0.0 
    @storybook/addon-links: ^8.0.0 => 8.0.0 
    @storybook/addon-themes: ~8.0.0 => 8.0.0 
    @storybook/blocks: ^8.0.0 => 8.0.0 
    @storybook/manager-api: ^8.0.0 => 8.0.0 
    @storybook/nextjs: ^8.0.0 => 8.0.0 
    @storybook/react: ^8.0.0 => 8.0.0 
    @storybook/test: ^8.0.0 => 8.0.0 
    @storybook/test-runner: ^0.17.0 => 0.17.0 
    @storybook/theming: ^8.0.0 => 8.0.0 
    chromatic: ~11.0.8 => 11.0.8 
    eslint-plugin-storybook: ~0.8.0 => 0.8.0 
    storybook: ^8.0.0 => 8.0.0
```

### Additional context

Was working before the upgrade to v8.

### PR DESCRIPTION
**Pull request by yannbf**
Closes #20920, Closes #26503

## What I did

This PR reworks the logic in the JSX decorator to account for more use cases, fixing the [Object object] displayName issue.

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [x] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

There are unit tests for this. You can also test it manually if you'd like:

1. Run a sandbox for template, e.g. `yarn task --task sandbox --start-from auto --template react-vite/default-ts`
2. Change its main.ts to use react-typescript-docgen
3. Look at the autodocs page for the Button component
4. Change the Button component to use different formats:
- Nothing, just as is in the boilerplate
- override Button.displayName
- forwardRef()
- memo()

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

File: code/renderers/react/src/docs/jsxDecorator.tsx [hunk 1]
```diff
@@ -124,16 +125,28 @@ export const renderJsx = (code: React.ReactElement, options?: JSXOptions) => {
...
-            getDocgenSection(el.type, 'displayName') ||
-            (el.type.name !== '_default' ? el.type.name : null) ||
-            (typeof el.type === 'function' ? 'No Display Name' : null) ||
-            (isForwardRef(el.type) ? el.type.render.name : null) ||
-            (isMemo(el.type) ? el.type.type.name : null) ||
-            el.type,
+      displayName: (el: any): string => {
+        if (el.type.displayName) {
+          return el.type.displayName;
+        } else if (getDocgenSection(el.type, 'displayName')) {
```
Comment (yannbf) [inline code/renderers/react/src/docs/jsxDecorator.tsx:131]: I moved this up because I am assuming that docgenInfo should take precedence over an element's symbol name. 

Before, if you had a forwardRef element AND docgenInfo with a displayName of "Button", it would say <React.ForwardRef> instead of <Button>.

Now it will say <Button>.

**Review by kasperpeulen — APPROVED** [review]
LGTM
