### PR TITLE
UI: Fix TreeNode alignment when using a different font

### LINKED ISSUE #18607: Alignment of text and icon on sidebar is changed when font of storybook is changed
Have changed the font to open sans in `theme.js` and when doing so, the alignment of the text to the icons on the sidebar gets affected as shown in the image

alignment_off_center

### PR DESCRIPTION
**Pull request by bdriguesdev**
Closes #18607

## What I did
The spacing to align the icons of **TreeNode** with the first line of text is hard coded, so when we change the theme's font it will not line up correctly with the text. 
In order to be able to adjust this to work with every custom font that the user can specify, we did a trick: we added a blank character to an element that receives the icons to set the min-height to exactly one line of text, so the icons are aligned with  **TreeNode** text.

Before:

Screenshot_8

After:

Screenshot_9

## How to test

You can reproduce in two ways:
1. https://stackblitz.com/edit/github-zf44nu?file=README.md
2. Run a sandbox for any template, you just need to change the Storybook theme font (can be **Arial**)

## Checklist

- [x] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [x] Make sure to add/update documentation regarding your changes
- [x] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [x] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [x] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by valentinpalkovic** [comment]
@cdedreuille I would like to assign this to you if you don't mind.

File: code/ui/manager/src/components/sidebar/TreeNode.tsx [hunk 1]
```diff
@@ -145,6 +142,26 @@ export const RootNode = styled.div(({ theme }) => ({
...
+const InvisibleText = styled.p({
+  margin: 0,
+  width: 0,
+});
+
+// Make the content have a min-height equal to one line of text
+export const IconsWrapper: FunctionComponent<{ children?: React.ReactNode }> = ({ children }) => {
+  return (
+    <Wrapper>
+      <InvisibleText>&nbsp;</InvisibleText>
```
Comment (cdedreuille) [inline code/ui/manager/src/components/sidebar/TreeNode.tsx:159]: Why do you need this InvisibleText? It should automatically center it in the middle without this line, no?

File: code/ui/manager/src/components/sidebar/TreeNode.tsx [hunk 2]
```diff
@@ -145,6 +142,26 @@ export const RootNode = styled.div(({ theme }) => ({
...
+  alignItems: 'center',
+});
+
+const InvisibleText = styled.p({
+  margin: 0,
+  width: 0,
+});
+
+// Make the content have a min-height equal to one line of text
+export const IconsWrapper: FunctionComponent<{ children?: React.ReactNode }> = ({ children }) => {
```
Comment (cdedreuille) [inline code/ui/manager/src/components/sidebar/TreeNode.tsx:156]: You can use `FC` instead of `FunctionComponent`

**Review by cdedreuille — CHANGES_REQUESTED** [review]

File: code/ui/manager/src/components/sidebar/TreeNode.tsx (hunk 1 above)
Comment (bdriguesdev) [reply code/ui/manager/src/components/sidebar/TreeNode.tsx:159]: The reason is that when the text for the TreeNode breaks in multiple lines the icon needs to be centered with the first line of text on the right side not with the whole container, like the first example here:
image
To achieve this the only way I found is to wrap the Icon within an element that has a height of just one line of text and align the icon vertically inside it, so it will be aligned with the first line of text of the TreeNode. We can't use a fixed value that represents the height of one line of text because each font can have a different height, to deal with it I used this trick of placing an invisible character to set a height for the container of the icon to be exactly the same as one line of a text.
Makes sense?
Also, we could align the icon in the center of the TreeNode not with the first line of text, that will be way easier and we can remove the InvisibleText
---
Just for visualization
Aligning with the first line of text:
Screenshot_10

Aligning with the TreeNode:
Screenshot_11

File: code/ui/manager/src/components/sidebar/TreeNode.tsx (hunk 2 above)
Comment (bdriguesdev) [reply code/ui/manager/src/components/sidebar/TreeNode.tsx]: Good to know, this is better 😄 
I changed it here: https://github.com/storybookjs/storybook/pull/22221/commits/f5621205dc714499563f9cb9061f421756a1d632

**Review by cdedreuille — APPROVED** [review]

**Comment by cdedreuille** [comment]
What's the status on this one @ndelangen?

**Comment by ndelangen** [comment]
I haven't worked on it @cdedreuille

**Comment by cdedreuille** [comment]
The change seems good to me @ndelangen. I'll approve it but perhaps someone else in the team can review it as well.

**Comment by ndelangen** [comment]
@cdedreuille does this look good to you:
https://www.chromatic.com/build?appId=635781f3500dd2c49e189caf&number=7513
?

**Comment by cdedreuille** [comment]
Yes I checked everything on Chromatic. All good for me @ndelangen
