### PR TITLE
React: Support v19 betas in peer dependencies

### LINKED ISSUE #27027: [Bug]: defaultProps Warnings
### Describe the bug

Not strictly a bug, but React versions >= 18.3.0 report console warnings of unsupported features in React 19.

```
react-dom.development.js:86 Warning: WithTooltipPure: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
```

In my particular case it was from the tooltip component used by the docs addon: https://github.com/storybookjs/storybook/blob/1e0e8220bcdc8d0988732d2f8889cdc42284d48b/code/ui/components/src/components/tooltip/WithTooltip.tsx#L123

Any particular plans to remove these warnings in version 8 of storybook, or are you going to push a new major version that supports React 19?

### To Reproduce

Use `@storybook/react` with `@storybook/addon-docs`.

### System

```bash
morgan@machine:~/code/tts-react (develop)$ ./node_modules/.bin/storybook info

Storybook Environment Info:
(node:18511) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

  System:
    OS: Linux 6.8 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (12) x64 13th Gen Intel(R) Core(TM) i5-1335U
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 22.1.0 - ~/n/bin/node
    npm: 10.7.0 - ~/n/bin/npm <----- active
  Browsers:
    Chrome: 124.0.6367.118
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JReinhold**
Closes https://github.com/storybookjs/storybook/issues/27027

## What I did

- Added sandboxes for React prereleases, Vite and Webpack. Generation triggered at https://github.com/storybookjs/storybook/actions/runs/8845643521/job/24289949895
- Expanded React peer deps version ranges to match. Isn't 100% perfect though since we still have transitive dependencies that doesn't specify v19, automatically narrowing it down to 18 still.
- Converted defaultProps to default assignments in functional components where it was easy. React 19 ignores defaultProps, and we had a story that broke because of our usage of it .

#### The changes in this PR are covered in the following automated tests:
- [x] stories
- [ ] unit tests
- [x] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

File: scripts/utils/yarn.ts [hunk 1]
```diff
@@ -97,7 +98,7 @@ export const configureYarn2ForVerdaccio = async ({
     `yarn config set enableImmutableInstalls false`,
   ];
 
-  if (key.includes('svelte-kit')) {
+  if (key.includes('svelte-kit') || key.includes('prerelease')) {
```
Comment (JReinhold) [inline scripts/utils/yarn.ts:101]: only cover react prereleases

**Review by ndelangen — APPROVED** [review]
