### PR TITLE
Blocks: IconGallery improvement

### LINKED ISSUE #24764: [Bug]: Unable to style the IconItem component
### Describe the bug

I am unable to style the IconItem component which is causing issues with long icon names that my team insist on using such as StarfighterTwinIonEngineAdvanced 

which results in 
Screenshot 2023-11-08 at 14 36 45

### To Reproduce

https://stackblitz.com/edit/github-mtjcjc?file=src%2Fstories%2FIconography.mdx

### System

```bash
Environment Info:

  System:
    OS: macOS 14.1
    CPU: (12) arm64 Apple M2 Pro
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
  Browsers:
    Edge: 119.0.2151.46
    Safari: 17.1
  npmPackages:
    @storybook/addon-a11y: ^7.0.10 => 7.3.1 
    @storybook/addon-console: ^1.2.3 => 1.2.3 
    @storybook/addon-essentials: ^7.0.8 => 7.3.1 
    @storybook/addon-interactions: ^7.0.8 => 7.3.1 
    @storybook/addon-jest: ^7.0.10 => 7.3.1 
    @storybook/addon-links: ^7.0.8 => 7.3.1 
    @storybook/addon-storysource: ^7.0.11 => 7.3.1 
    @storybook/addons: ^7.0.8 => 7.3.1 
    @storybook/blocks: ^7.0.8 => 7.3.1 
    @storybook/react: ^7.0.8 => 7.3.1 
    @storybook/react-webpack5: ^7.0.8 => 7.3.1 
    @storybook/theming: ^7.0.8 => 7.3.1
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by leeovictor**
Closes #24764 

## What I did

I tried to improve the IconGallery using an approach that tries to balance between displaying the content of the icon label as much as possible and keeping the gallery layout consistent with long labels. This means that if the label is long it will be displayed on up to 2 lines, but if it is so long that it does not fit on 2 lines the content will be truncated, prioritizing the visual consistency of the gallery layout.

In addition, I changed the gallery layout implementation using CSS grid and reduced the font size of the label so that more cases where the label content is too long will not be truncated.

I added two cases in the block stories for example. Here are some screenshots:
image
image

#### The changes in this PR are covered in the following automated tests:

- [x] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

1. Run the storybook on the 'code' directory: `yarn storybook:ui`
2. Open Storybook in your browser
3. Access the  'http://localhost:6006/?path=/story/blocks-components-icongallery--default-style' story (IconGallery story)

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

| name | before | after | diff | z | % |
| ---- | ------ | ----- | ---- | - | - |
| createSize |  0 B | 0 B | 0 B | - | - |
| generateSize |  79.9 MB | 80 MB | 69.4 kB | **16.44** | 0.1% |
| initSize |  79.9 MB | 80 MB | 69.4 kB | **16.44** | 0.1% |
| diffSize |  97 B | 97 B | 0 B | - | 0% |
| buildSize |  7.47 MB | 7.45 MB | -25.4 kB | -1.03 | -0.3% |
| buildSbAddonsSize |  1.98 MB | 1.9 MB | -80.7 kB | -1.1 | -4.3% |
| buildSbCommonSize |  195 kB | 195 kB | 0 B | - | 0% |
| buildSbManagerSize |  1.88 MB | 1.88 MB | -3 B | **-Infinity** | 0% |
| buildSbPreviewSize |  0 B | 0 B | 0 B | - | - |
| buildStaticSize |  0 B | 0 B | 0 B | - | - |
| buildPrebuildSize |  4.06 MB | 3.97 MB | -80.7 kB | -1.1 | -2% |
| buildPreviewSize |  3.42 MB | 3.47 MB | 55.3 kB | -0.65 | 1.6% |
| testBuildSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbAddonsSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbCommonSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbManagerSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbPreviewSize |  0 B | 0 B | 0 B | - | - |
| testBuildStaticSize |  0 B | 0 B | 0 B | - | - |
| testBuildPrebuildSize |  0 B | 0 B | 0 B | - | - |
| testBuildPreviewSize |  0 B | 0 B | 0 B | - | - |

| name | before | after | diff | z | % |
| ---- | ------ | ----- | ---- | - | - |
| createTime |  11.5s | 10.3s | -1s -198ms | -0.9 | -11.5% |
| generateTime |  20.2s | 19s | -1s -239ms | -0.38 | -6.5% |
| initTime |  4.9s | 4.5s | -412ms | -0.45 | -9% |
| buildTime |  9.1s | 8.3s | -851ms | -1.23 | -10.2% |
| testBuildTime |  0ms | 0ms | 0ms | - | - |
| devPreviewResponsive |  4.6s | 5.6s | 983ms | 0.65 | 17.5% |
| devManagerResponsive |  4.4s | 5.3s | 872ms | 0.6 | 16.4% |
| devManagerHeaderVisible |  782ms | 801ms | 19ms | -0.13 | 2.4% |
| devManagerIndexVisible |  793ms | 886ms | 93ms | 0.19 | 10.5% |
| devStoryVisibleUncached |  2.7s | 1.8s | -862ms | **-2.6** | 🔰-46.2% |
| devStoryVisible |  1.2s | 1.2s | 56ms | -0.09 | 4.4% |
| devAutodocsVisible |  1.1s | 1.2s | 159ms | 0.8 | 12.4% |
| devMDXVisible |  1.1s | 1.2s | 79ms | 0.1 | 6.5% |
| buildManagerHeaderVisible |  880ms | 1s | 139ms | **1.31** | 🔺13.6% |
| buildManagerIndexVisible |  885ms | 1s | 162ms | **1.37** | 🔺15.5% |
| buildStoryVisible |  869ms | 1s | 141ms | **1.33** | 🔺14% |
| buildAutodocsVisible |  618ms | 1.1s | 559ms | **2.6** | 🔺47.5% |
| buildMDXVisible |  666ms | 925ms | 259ms | **1.4** | 🔺28% |

## Greptile Summary

Improved IconGallery component to handle long icon labels by implementing CSS grid layout and text truncation after two lines, ensuring consistent visual presentation.

- Switched from flexbox to CSS grid in `code/lib/blocks/src/components/IconGallery.tsx` for better layout control
- Added text truncation with `-webkit-line-clamp: 2` for `ItemLabel` styled component
- Set fixed grid template columns with `minmax(140px, 1fr)` for uniform sizing
- Added test cases in `IconGallery.stories.tsx` with long icon names to demonstrate truncation behavior
- Reduced font size to theme.typography.size.s1 for better label fitting

<sub>💡 (1/5) You can manually trigger the bot by mentioning @greptileai in a comment!</sub>

### CODE REVIEW

**Comment by leeovictor** [comment]
eu estava pensando em talvez adicionar uma opção de customização do layout geral da galeria, com uma opção de setar o layout dos itens verticalmente. aqui um screenshot com um exemplo rapido que prototipei (poderia fazer isso em outra CL)
maybe something like that:
```js
<IconGalery itemOrientation="vertical">
```
image

File: code/lib/blocks/src/components/IconGallery.tsx [hunk 1]
```diff
@@ -34,15 +41,16 @@ const Item = styled.div({
   display: 'inline-flex',
   flexDirection: 'row',
   alignItems: 'center',
-  flex: '0 1 calc(20% - 10px)',
-  minWidth: 120,
-
-  margin: '0px 10px 30px 0',
+  width: '100%',
+  padding: '0 8px',
```
Comment (ghengeveld) [inline code/lib/blocks/src/components/IconGallery.tsx:45]:
```suggestion
```
I think this padding is duplicative, since there's also a `gridGap`. The extra padding just makes the text truncate sooner than strictly necessary.

@MichaelArestad WDYT?

**Review by ghengeveld — APPROVED** [review]
Nice work. @MichaelArestad should make the call on the padding/gap sizing. Once he does I think this is good to go.

Nice to see line-clamp being put to good use 👍

File: code/lib/blocks/src/components/IconGallery.tsx (hunk 1 above)
Comment (MichaelArestad) [reply code/lib/blocks/src/components/IconGallery.tsx:45]: Good catch. I would prefer we remove the padding, but add spacing to the `gap`. To me `gap: 8px 16px` looks good.

Comment (ghengeveld) [reply code/lib/blocks/src/components/IconGallery.tsx:45]: That wouldn't actually change anything except for the outermost paddings. So not much extra space for the text.

Comment (leeovictor) [reply code/lib/blocks/src/components/IconGallery.tsx]: Hi! Good catch. I added a commit changing this, please take a look. Thanks for the suggestion 😄

**Review by ghengeveld — APPROVED** [review]

File: code/lib/blocks/src/components/IconGallery.tsx (hunk 1 above)
Comment (ghengeveld) [reply code/lib/blocks/src/components/IconGallery.tsx]: Works for me.
