### PR TITLE
Autodocs: Hide Stories block when only primary story exists

### LINKED ISSUE #20969: [Bug]: autodocs pages that only contain a single story show the same story twice
### Describe the bug

image

### To Reproduce

Access a Storybook 7 project with autodocs, and create a single story for a component. Look at the docs entry and you will see two component, which seems redundant.

One would assume that there should be no need to display the same component twice, while others might argue the top one is a playground, and the bottom one is the fixed story (with original looks). Providing the story at the bottom when there are multiple stories does seem to make more sense, it just feels weird when there is a single story.

### PR DESCRIPTION
**Pull request by JReinhold**
Closes #20969

## What I did

This PR adds a special case to the default `DocsPage` block for single story autodocs:

- Hide the "Stories" section below, to not show the primary story twice
- Move the primary story's description from the now hidden stories section to between the component description and the canvas.

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Review by shilman — APPROVED** [review]
LGTM!

**Comment by MichaelArestad** [comment]
@JReinhold Is there somewhere I can see an example of this in one of the test Storybooks?

**Comment by JReinhold** [comment]
After discussing this with @MichaelArestad we decided that the primary story's description should be featured below the component description in the case of single stories. See screenshots below.

The only downside here is the fact that we now loose the narrative that "The `DocsPage` is super simple, you can copy it from here" because now it contains actual logic: https://github.com/storybookjs/storybook/pull/21178/files#diff-c940951c2adc4415d2b5dd98d12260a366f44fcd5ae7d4a3e92744ef780df9e8R11-R27
Any thoughts about that @shilman?

## Single story

image

## Multiple stories

image

**Review by shilman — APPROVED** [review]
I'm ok with this too, tho it lacks the simplicity of before. Please update the PR description before merging 🙏

File: code/ui/blocks/src/blocks/DocsPage.tsx [hunk 1]
```diff
@@ -6,14 +6,22 @@ import { Description } from './Description';
...
-    <Subtitle />
-    <Description />
-    <Primary />
-    <Controls />
-    <Stories />
-  </>
-);
+export const DocsPage: FC = () => {
+  const resolvedOf = useOf('meta', ['meta']);
+  const { stories } = resolvedOf.csfFile;
```
Comment (tmeasday) [inline code/ui/blocks/src/blocks/DocsPage.tsx:13]: Maybe this should be `docsContext.componentStories()`, rather than digging into the `csfFile`?

Comment (JReinhold) [reply code/ui/blocks/src/blocks/DocsPage.tsx:13]: Yes I thought about that too, because that's how we do it elsewhere. But since we often share how the default DocsPage is implemented, I wanted to use the more official approach with `useOf`, instead of something that is semi-internal.
