### PR TITLE
Viewport: Fix editing when default viewport is set

### LINKED ISSUE #26334: [Bug]: Viewport cannot be changed
### Describe the bug

@storybook/addon-viewport is broken.
If default viewport is set, you cannot change to a viewport other than defaultViewport on the ui.
Even if you change the viewport, it will return to the defaultviewport with a redirect-like behavior.
This doesn't happen on the latest 7.6.17, it happens on versions 8 and later (confirmed on 8.0.0-rc.2).

```preview.ts
import type { Preview } from "@storybook/react"
import { INITIAL_VIEWPORTS, MINIMAL_VIEWPORTS } from "@storybook/addon-viewport"

const preview: Preview = {
  parameters: {
    actions: { argTypesRegex: "^on[A-Z].*" }, // Delete this line after ver 8
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },
    viewport: {
      defaultViewport: "iphone5",
      viewports: {
        ...INITIAL_VIEWPORTS,
        ...MINIMAL_VIEWPORTS,
      },
    },
  },
}

export default preview
```

### To Reproduce

_No response_

### System

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by shilman**
Closes #26334 

## What I did

Fixed a reactivity bug that caused the viewport to snap back to the default viewport when the user tries to edit.

### Testing

1. Added a test for this case 
2. Checked that it fails with the old code
3. Checked that it passes with the new 

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [x] end-to-end tests

#### Manual testing

See E2E test

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

File: code/addons/viewport/src/Tool.tsx [hunk 1]
```diff
@@ -150,7 +150,15 @@ export const ViewportTool: FC = memo(
...
       }
-    }, [defaultOrientation, defaultViewport, globals, updateGlobals]);
+      // NOTE: we don't want to re-run this effect when `globals` changes
+      // due to https://github.com/storybookjs/storybook/issues/26334
+      //
+      // Ultimately this process of "locking in" a parameter value should be
+      // replaced by https://github.com/storybookjs/storybook/discussions/23347
+      // or something similar.
+      //
+      // eslint-disable-next-line react-hooks/exhaustive-deps
```
Comment (tmeasday) [inline code/addons/viewport/src/Tool.tsx:160]:
```suggestion
      // NOTE: we don't want to re-run this effect when `globals` changes
      // due to https://github.com/storybookjs/storybook/issues/26334
      //
      // Also, this *will* rerun every time you change story as the parameter is briefly `undefined`.
      // This behaviour is intentional, if a bit of a happy accident in implementation.
      //
      // Ultimately this process of "locking in" a parameter value should be
      // replaced by https://github.com/storybookjs/storybook/discussions/23347
      // or something similar.
      //
      // eslint-disable-next-line react-hooks/exhaustive-deps
```

Comment (tmeasday) [reply code/addons/viewport/src/Tool.tsx:160]: It bothers me a bit that if we say changed things so `useParameters` didn't flash through `undefined`, this behaviour would change.

**Review by tmeasday — APPROVED** [review]
