### PR TITLE
Telemetry: Fix `project.json` for getAbsolutePath

### LINKED ISSUE #29664: [Bug]: getAbsolutePath results in broken `project.json`
### Describe the bug

Currently Storybook's `project.json` reports the addons that are listed in `.storybook/main.ts`. It does this by calling `getActualPacakgeVersion` on each of the addons:

https://github.com/storybookjs/storybook/blob/next/code/core/src/telemetry/package-json.ts

However, in monorepos we recommend using absolute paths with the following pattern:

```ts
import { dirname, join } from 'node:path';

const getAbsolutePath = <I extends string>(input: I): I =>
  dirname(require.resolve(join(input, 'package.json'))) as any;

const config: StorybookConfig = {
  stories: ['../stories/**/*.mdx', '../stories/**/*.stories.@(js|jsx|mjs|ts|tsx)'],
  addons: [
    getAbsolutePath('@storybook/addon-onboarding'),
    getAbsolutePath('@storybook/addon-essentials'),
    getAbsolutePath('@chromatic-com/storybook'),
  ]
},
```

This generates addon entries like the following:

```
info     "addons": {
info       "$SNIP/node_modules/.pnpm/@storybook+addon-onboarding@8.5.0-alpha.8_react@18.3.1_storybook@8.5.0-alpha.8/node_modules/@storybook/addon-onboarding": {
info         "version": null
info       },
info       "$SNIP/node_modules/.pnpm/@storybook+addon-essentials@8.5.0-alpha.8_@types+react@18.3.12_storybook@8.5.0-alpha.8/node_modules/@storybook/addon-essentials": {
info         "version": null
info       },
info       "$SNIP/node_modules/.pnpm/@chromatic-com+storybook@3.2.2_react@18.3.1_storybook@8.5.0-alpha.8/node_modules/@chromatic-com/storybook": {
info         "version": null
info       },
```

Instead, it should produce:

```
info     "addons": {
info       "@storybook/addon-onboarding": {
info         "version": "8.5.0-alpha.8"
info       },
info       "@storybook/addon-essentials": {
info         "version": "8.5.0-alpha.8"
info       },
info       "@chromatic-com/storybook": {
info         "version": "3.2.2"
info       },
```

### Reproduction link

N/A

### Reproduction steps

See above

### System

```bash
Any
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ndelangen**
Closes #29664

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This pull request has been released as version `0.0.0-pr-31510-sha-3664c943`. Try it out in a new sandbox by running `npx storybook@0.0.0-pr-31510-sha-3664c943 sandbox` or in an existing project with `npx storybook@0.0.0-pr-31510-sha-3664c943 upgrade`.
<details>
<summary>More information</summary>

| | |
| --- | --- |
| **Published version** | [`0.0.0-pr-31510-sha-3664c943`](https://npmjs.com/package/storybook/v/0.0.0-pr-31510-sha-3664c943) |
| **Triggered by** | @ndelangen |
| **Repository** | [storybookjs/storybook](https://github.com/storybookjs/storybook) |
| **Branch** | [`norbert/fix-telemetry-projectjson-generation`](https://github.com/storybookjs/storybook/tree/norbert/fix-telemetry-projectjson-generation) |
| **Commit** | [`3664c943`](https://github.com/storybookjs/storybook/commit/3664c94334e316a5cb4fcd1fb2dc0bfa27031064) |
| **Datetime** | Mon May 19 14:35:22 UTC 2025 (`1747665322`) |
| **Workflow run** | [15115847466](https://github.com/storybookjs/storybook/actions/runs/15115847466) |

To request a new release of this pull request, mention the `@storybookjs/core` team.

_core team members can create a new canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=31510`_
</details>

## Greptile Summary

This PR fixes telemetry data collection in monorepo setups by improving package version resolution and addon handling in project.json generation.

- Enhanced package.json resolution in `code/core/src/telemetry/package-json.ts` using findUp for absolute paths in monorepos
- Added proper fallback handling for version information in `code/core/src/telemetry/storybook-metadata.ts` using `version || undefined`
- Improved error handling for package manager detection and metaFramework version fallback to 'unknown'
- Fixed addon version reporting to use actual package names instead of absolute paths

### CODE REVIEW

File: code/core/src/telemetry/package-json.ts [hunk 1]
```diff
@@ -12,18 +15,29 @@ export const getActualPackageVersion = async (packageName: string) => {
...
 };
 
-export const getActualPackageJson = async (packageName: string) => {
-  const resolvedPackageJson = require.resolve(join(packageName, 'package.json'), {
-    paths: [process.cwd()],
-  });
+export const getActualPackageJson = async (
+  packageName: string
+): Promise<PackageJson | undefined> => {
+  let resolvedPackageJson = await findUp('package.json', { cwd: require.resolve(packageName) });
```
Comment (shilman) [inline code/core/src/telemetry/package-json.ts:32]: Do we know the perf implications of this?

File: code/core/src/telemetry/storybook-metadata.ts [hunk 2]
```diff
@@ -77,7 +77,7 @@ export const computeStorybookMetadata = async ({
     metadata.metaFramework = {
       name: metaFrameworks[metaFramework],
       packageName: metaFramework,
-      version,
+      version: version || 'unknown',
```
Comment (shilman) [inline code/core/src/telemetry/storybook-metadata.ts:80]: why `undefined` elsewhere and `'unknown'` here?

**Review by shilman — COMMENTED** [review]
Is there any way to unit/integration test any of this?

File: code/core/src/telemetry/package-json.ts (hunk 1 above)
Comment (ndelangen) [reply code/core/src/telemetry/package-json.ts:32]: not noticeable I think. the function was already async.

File: code/core/src/telemetry/storybook-metadata.ts (hunk 2 above)
Comment (ndelangen) [reply code/core/src/telemetry/storybook-metadata.ts:80]: The type used to be `any`.

I made it more strict, but that didn't match up with the expected type here.
I just made it work without too much consideration.

I can also type-cast it back to `any` if you feel that's better.
I didn't want to keep pulling the thread and potentially run out of time.
