### PR TITLE
Core: Fix null version check bug

### LINKED ISSUE #8706: TypeError: Cannot read property 'latest' of undefined
After upgrade storybook to alpha.38

```
    "@storybook/addon-actions": "^5.3.0-alpha.38",
    "@storybook/addon-info": "^5.3.0-alpha.38",
    "@storybook/addon-links": "^5.3.0-alpha.38",
    "@storybook/addon-storysource": "^5.3.0-alpha.38",
    "@storybook/addons": "^5.3.0-alpha.38",
    "@storybook/react": "^5.3.0-alpha.38",
```

Babel version:
```
"babel-cli": "^6.26.0",
    "babel-core": "^6.26.3",
    "babel-eslint": "^10.0.2",
    "babel-jest": "^23.6.0",
    "babel-loader": "^7.1.4",
    "babel-plugin-styled-components": "^1.10.6",
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "babel-plugin-transform-object-assign": "^6.22.0",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-es2017": "^6.24.1",
    "babel-preset-react": "^6.24.1",
```

Getting TypeError: Cannot read property 'latest' of undefined

```
Uncaught (in promise) TypeError: Cannot read property 'latest' of undefined
    at _callee$ (vendors~main.9d27a94eeb00f3ca0217.bundle.js:9217)
    at tryCatch (vendors~main.9d27a94eeb00f3ca0217.bundle.js:173386)
    at Generator.invoke [as _invoke] (vendors~main.9d27a94eeb00f3ca0217.bundle.js:173612)
    at Generator.prototype.<computed> [as next] (vendors~main.9d27a94eeb00f3ca0217.bundle.js:173438)
    at asyncGeneratorStep (vendors~main.9d27a94eeb00f3ca0217.bundle.js:9129)
    at _next (vendors~main.9d27a94eeb00f3ca0217.bundle.js:9131)
    at vendors~main.9d27a94eeb00f3ca0217.bundle.js:9131
    at new Promise (<anonymous>)
    at vendors~main.9d27a94eeb00f3ca0217.bundle.js:9131
    at _init (vendors~main.9d27a94eeb00f3ca0217.bundle.js:9254)
```

Webpack
```
"webpack": "4.8.3",
    "webpack-cli": "2.1.3",
    "webpack-dev-server": "3.1.4",
    "webpack-merge": "4.1.0"
```

React
```
 "react": "16.3.0",
    "react-dom": "16.3.0",
```

image

### PR DESCRIPTION
**Pull request by ndelangen**
Issue: #8706

## What I did
I made sure the return value is always an object

### CODE REVIEW

**Comment by ndelangen** [comment]
@brendonco WDYT?

File: lib/api/src/modules/versions.ts [hunk 1]
```diff
@@ -33,7 +33,7 @@ export interface SubState {
 const getVersionCheckData = memoize(1)(
   (): Versions => {
     try {
-      return JSON.parse(VERSIONCHECK).data as Versions;
+      return { ...(JSON.parse(VERSIONCHECK).data || {}) };
```
Comment (shilman) [inline lib/api/src/modules/versions.ts]: @ndelangen why s the `{ ... }` needed?

Comment (ndelangen) [reply lib/api/src/modules/versions.ts]: to ensure the returned value is an object.

I'm unsure how it happened but in #8706 if window.VERSION is parsable, and accessing data didn't throw an error, it would be returned. (it could be undefined)

Now I made sure data is defined, and is an object.

If something is attempted to be spread, that cannot be spread, it will throw, and the catch-clause will return an empty object.
