### PR TITLE
Next.js: Support rename font import

### LINKED ISSUE #23592: [Bug]: Cannot rename import
### Describe the bug

I use Next.js 13 Font Module in following code `lib/fonts.ts`

```ts
import { Inter as FontSans } from 'next/font/google'

export const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans'
})
```

It works normally with `next start` but failed in storybook. Workaround is to remove the renaming:

```ts
import { Inter } from 'next/font/google'

export const fontSans = Inter({
  subsets: ['latin'],
  variable: '--font-sans'
})
```

### To Reproduce

_No response_

### System

```shell
Environment Info:

  System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.0/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.248
    Safari: 16.5.2
  npmPackages:
    @storybook/addon-essentials: ^7.1.1 => 7.1.1 
    @storybook/addon-interactions: ^7.1.1 => 7.1.1 
    @storybook/addon-links: ^7.1.1 => 7.1.1 
    @storybook/addon-styling: ^1.3.4 => 1.3.4 
    @storybook/blocks: ^7.1.1 => 7.1.1 
    @storybook/nextjs: ^7.1.1 => 7.1.1 
    @storybook/react: ^7.1.1 => 7.1.1 
    @storybook/testing-library: ^0.2.0 => 0.2.0
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yoshi2no**
Closes #23592

## What I did

- ensured that renaming using as doesn't cause errors
- updated unit tests for `TransformFontImports`

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [x] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

1. Run a sandbox for `nextjs/default-ts` template
2. Open Storybook in your browser
3. edit `sandbox/nextjs-default-ts/app/layout.tsx` like this
```js
import './globals.css'
import type { Metadata } from 'next'
import { Lora as FontLora } from 'next/font/google' // rename

const lora = FontLora({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={lora.className}>
        <div>{children}</div>
      </body>
    </html>
  )
}
```
4. add `RootLayout` to Page `sandbox/nextjs-default-ts/stories/Page.tsx`
5. go to `http://localhost:6006/?path=/story/example-page--logged-out`
6. check that no errors are displayed and the font-family is applied correctly

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

File: code/frameworks/nextjs/src/font/babel/helpers.ts [hunk 1]
```diff
@@ -311,8 +314,15 @@ export function getVariableMetasBySpecifier(
...
-      const functionName = declaration.init.callee.name;
-
+      let functionName = declaration.init.callee.name;
+      if (
+        specifier.type === 'ImportSpecifier' &&
+        specifier.imported &&
+        specifier.imported.type === 'Identifier' &&
+        declaration.init.callee.name !== specifier.imported.name
+      ) {
+        functionName = specifier.imported.name;
```
Comment (yoshi2no) [inline code/frameworks/nextjs/src/font/babel/helpers.ts:324]: font-data could need to be looked for using imported.name

sandbox/nextjs-default-ts/node_modules/next/dist/compiled/@next/font/dist/google/font-data.json

**Review by valentinpalkovic — APPROVED** [review]

**Comment by valentinpalkovic** [comment]
Hi @yoshi2no 

Thanks for your contribution.

LGTM!
