### PR TITLE
Manager API: Fix `api.getAddonState`default value

### LINKED ISSUE #23741: [Bug]: Since v7.2.0: Actions tab doesn't show count anymore + console error
### Describe the bug

After updating to v7.2 the number of actions is not shown in the tab anymore (top: v7.1, bottom: v7.2):

Bildschirmfoto 2023-08-07 um 10 27 29

Also, the console is flooded with errors (1 per event/action):

Bildschirmfoto 2023-08-07 um 11 35 24

The error is happening in this Storybook component:
```jsx
function Title() {
  let[{count},setCount] = useAddonState(ADDON_ID, {
    count: 0
  });
  return useChannel({
    [EVENT_ID]: ()=>{
      setCount(c=>({
        ...c,
        count: c.count + 1          // ← c is undefined
      }));
    }
    ,
    [STORY_CHANGED]: ()=>{
      setCount(c=>({
        ...c,
        count: 0
      }));
    }
    ,
    [CLEAR_ID]: ()=>{
      setCount(c=>({
        ...c,
        count: 0
      }));
    }
  }),
  React.createElement("div", null, React.createElement(Spaced, {
    col: 1
  }, React.createElement("span", {
    style: {
      display: "inline-block",
      verticalAlign: "middle"
    }
  }, "Actions"), count === 0 ? "" : React.createElement(Badge, {
    status: "neutral"
  }, count)))
}
```

### To Reproduce

Unfortunately, I can't reproduce the problem in the provided stackblitz. But since it works in v7.1 without having changed anything and it is related to a component of Storybook, I hope you can fix it.

### System

```shell
Environment Info:

  System:
    OS: macOS 13.5
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.20.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.4 - /usr/local/bin/npm
  Browsers:
    Google Chrome: 115.0.5790.170
    Safari: 16.6
  npmPackages:
    @storybook/addon-docs: 7.2.1 => 7.2.1 
    @storybook/addon-essentials: 7.2.1 => 7.2.1 
    @storybook/addon-links: 7.2.1 => 7.2.1 
    @storybook/addons: 7.2.1 => 7.2.1 
    @storybook/components: 7.2.1 => 7.2.1 
    @storybook/manager-api: 7.2.1 => 7.2.1 
    @storybook/preset-create-react-app: 7.2.1 => 7.2.1 
    @storybook/react: 7.2.1 => 7.2.1 
    @storybook/react-webpack5: 7.2.1 => 7.2.1 
    @storybook/testing-library: ^0.2.0 => 0.2.0 
    @storybook/theming: 7.2.1 => 7.2.1
```

### Additional context

_No response_

### LINKED ISSUE #23787: [Bug]:  TypeError: Cannot read properties of undefined (reading 'count') with onClick action
### Describe the bug

image

image

### To Reproduce

just setup a react app with webpack or vite, then install storybook and create a story for a single button component

### System

```shell
Environment Info:

  System:
    OS: macOS 13.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 18.13.0 - ~/.nodenv/versions/18.13.0/bin/node
    Yarn: 1.22.19 - ~/.nodenv/versions/18.13.0/bin/yarn
    npm: 9.6.7 - ~/.nodenv/versions/18.13.0/bin/npm
  Browsers:
    Chrome: 115.0.5790.170
    Safari: 16.6
  npmPackages:
    @storybook/addon-essentials: ^7.2.1 => 7.2.1
    @storybook/addon-interactions: ^7.2.1 => 7.2.1
    @storybook/addon-links: ^7.2.1 => 7.2.1
    @storybook/addon-onboarding: ^1.0.8 => 1.0.8
    @storybook/blocks: ^7.2.1 => 7.2.1
    @storybook/react: ^7.2.1 => 7.2.1
    @storybook/react-webpack5: ^7.2.1 => 7.2.1
    @storybook/testing-library: ^0.2.0 => 0.2.0
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sookmax**
Closes #23741 #23787

## What I did
I've noticed `api.getAddonState()` sometimes (not sure the exact condition) returns `undefined`, which affects consumers of `api.setAddonState()`. 

More specifically, #23787 occurs when the state updater function `setCount()` in `code/addon/actions/src/manager.tsx` attempts to access `c.count` assuming the state `{ count: number; }` is available all the time (i.e., `setCount((c) => ({ ...c, count: c.count + 1 }));`). Unfortunately as I mentioned above, sometimes `api.getAddonState()`, which is the value of the parameter `c` of the callback in `setCount()`, results in `undefined`.

This PR fixes the issue by providing `defaultState` when `c` is undefined in `useSharedState()`.

## Checklist

- [x] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "build", "documentation", "maintenance", "dependencies", "other"]`

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

File: code/lib/manager-api/src/index.tsx [hunk 1]
```diff
@@ -416,7 +416,7 @@ const addonStateCache: {
 } = {};
 
 // shared state
-export function useSharedState<S>(stateId: string, defaultState?: S) {
+export function useSharedState<S extends object>(stateId: string, defaultState?: S) {
```
Comment (ndelangen) [inline code/lib/manager-api/src/index.tsx:419]: `S extends object`

- doesn't everything extend object in JS land?
- AFAIK `S` could also be a `string`, `number`, etc.

Comment (sookmax) [reply code/lib/manager-api/src/index.tsx:419]: Oh I didn't know it could be primitives like `string` or `number`.

I was merely trying to filter out `API_StateMerger<S>` from `S | API_StateMerger<S>` so I can call it, but TypeScript produces:
```
This expression is not callable.
  Not all constituents of type 'API_StateMerger<S> | (S & Function)' are callable.
    Type 'S & Function' has no call signatures.
```

So I added that to work around the typescript error.

What would be a better idea? should I exhaustively include all possible type for `S`?

**Comment by ndelangen** [comment]
The confusion comes from a race condition:

When using `useAddonState()` in 2 places in the react tree, or even across manager & preview... then if both do not have the exact same default config there's the possibility of creating an infinite loop.

So it's recommended to only have the default state value defined in 1 place. everywhere else you might get an `undefined` initially, but it will get called again.

File: code/lib/manager-api/src/index.tsx (hunk 1 above)
Comment (sookmax) [reply code/lib/manager-api/src/index.tsx]: @ndelangen Maybe this is better? https://github.com/storybookjs/storybook/pull/23804/commits/63f2dbef61ad47161d053617a0087cd05deb4766

**Comment by sookmax** [comment]
Oh I see.. so it's more involved than I originally thought.

But my fix merely uses the default state provided to `useSharedState`, which was already there before the fix, and even the initial `undefined` passed here: `setCount((c) => ({ ...c, count: c.count + 1 }))` will produce a runtime error and the counter becomes out of sync with the number of items shown in the action panel.

File: code/lib/manager-api/src/index.tsx [hunk 2]
```diff
@@ -431,7 +431,13 @@ export function useSharedState<S>(stateId: string, defaultState?: S) {
   }
 
   const setState = (s: S | API_StateMerger<S>, options?: Options) => {
-    const result = api.setAddonState<S>(stateId, s, options);
+    let sFinal = s;
+    if (typeof s === 'function') {
+      sFinal = (_state) => {
+        return (s as API_StateMerger<S>)(_state || defaultState);
+      };
```
[the remark this answers is not in the document]
Comment (sookmax) [reply code/lib/manager-api/src/index.tsx:438]: By adding `defaultState` to the list of parameters of `setAddonState`? I mean yeah sure if it's not a breaking change to every consumer of `api.setAddonState` (by a quick inspection, it seems `useSharedState` is the sole user of `api.setAddonState` for now).

I didn't know maintaining the referential identity of the passed `API_StateMerger<S>` was important. If you think handling this in `api.setAddoinState` is safer, than by all means let's do it that way.

**Review by kasperpeulen — COMMENTED** [review]
Comitted on this one, so I can not approve anymore 😅

**Review by ndelangen — APPROVED** [review]
