### PR TITLE
A11y: Improved toolbar a11y by fixing semantics

### LINKED ISSUE #25918: [Bug]: Top toolbar lacking semantics
### Describe the bug

The HTML markup for the top toolbar needs semantics. The buttons should be marked up as an unordered list to indicate the number of items clearly, and ideally, this would be grouped into a labeled `<section>`. 
bug1

### To Reproduce

Inspect top toolbar elements.

### System

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mehm8128**
Closes #25918

## What I did

Grouped toolbar with labelled section.

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

1. Run a sandbox for template, e.g. `yarn task --task sandbox --start-from auto --template react-vite/default-ts`
2. Open Storybook in your browser
3. Access http://localhost:6006/?path=/story/example-button--primary
4. Check that toolbar is correctly rendered and readed by screen reader as unordered list and the section named as 'Toolbar'.

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

| name | before | after | diff | z | % |
| ---- | ------ | ----- | ---- | - | - |
| createSize |  0 B | 0 B | 0 B | - | - |
| generateSize |  0 B | 77.8 MB | 77.8 MB | - | 100% |
| initSize |  0 B | 143 MB | 143 MB | - | 100% |
| diffSize |  0 B | 65.6 MB | 65.6 MB | - | 100% |
| buildSize |  0 B | 7.19 MB | 7.19 MB | - | 100% |
| buildSbAddonsSize |  0 B | 1.85 MB | 1.85 MB | - | 100% |
| buildSbCommonSize |  0 B | 195 kB | 195 kB | - | 100% |
| buildSbManagerSize |  0 B | 1.87 MB | 1.87 MB | - | 100% |
| buildSbPreviewSize |  0 B | 0 B | 0 B | - | - |
| buildStaticSize |  0 B | 0 B | 0 B | - | - |
| buildPrebuildSize |  0 B | 3.92 MB | 3.92 MB | - | 100% |
| buildPreviewSize |  0 B | 3.28 MB | 3.28 MB | - | 100% |
| testBuildSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbAddonsSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbCommonSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbManagerSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbPreviewSize |  0 B | 0 B | 0 B | - | - |
| testBuildStaticSize |  0 B | 0 B | 0 B | - | - |
| testBuildPrebuildSize |  0 B | 0 B | 0 B | - | - |
| testBuildPreviewSize |  0 B | 0 B | 0 B | - | - |

| name | before | after | diff | z | % |
| ---- | ------ | ----- | ---- | - | - |
| createTime |  0ms | 8.4s | 8.4s | - | 100% |
| generateTime |  0ms | 25.3s | 25.3s | - | 100% |
| initTime |  0ms | 20s | 20s | - | 100% |
| buildTime |  0ms | 9.1s | 9.1s | - | 100% |
| testBuildTime |  0ms | 0ms | 0ms | - | - |
| devPreviewResponsive |  0ms | 6s | 6s | - | 100% |
| devManagerResponsive |  0ms | 4.3s | 4.3s | - | 100% |
| devManagerHeaderVisible |  0ms | 761ms | 761ms | - | 100% |
| devManagerIndexVisible |  0ms | 790ms | 790ms | - | 100% |
| devStoryVisibleUncached |  0ms | 2s | 2s | - | 100% |
| devStoryVisible |  0ms | 788ms | 788ms | - | 100% |
| devAutodocsVisible |  0ms | 636ms | 636ms | - | 100% |
| devMDXVisible |  0ms | 702ms | 702ms | - | 100% |
| buildManagerHeaderVisible |  0ms | 744ms | 744ms | - | 100% |
| buildManagerIndexVisible |  0ms | 881ms | 881ms | - | 100% |
| buildStoryVisible |  0ms | 717ms | 717ms | - | 100% |
| buildAutodocsVisible |  0ms | 478ms | 478ms | - | 100% |
| buildMDXVisible |  0ms | 584ms | 584ms | - | 100% |

### CODE REVIEW

File: code/core/src/manager/components/preview/tools/zoom.tsx [hunk 1]
```diff
@@ -40,20 +41,26 @@ const Zoom = memo<{
...
+          <ZoomOutIcon />
+        </IconButton>
+      </li>
+      <li>
+        {/* @ts-expect-error (non strict) */}
+        <IconButton key="zoomreset" onClick={reset} title="Reset zoom">
+          <ZoomResetIcon />
+        </IconButton>
+      </li>
+    </ToolList>
```
Comment (kasperpeulen) [inline code/core/src/manager/components/preview/tools/zoom.tsx:63]: Didn't you already wrap those over here already?
https://github.com/storybookjs/storybook/blob/65a6d76bd7cd7adf3bde10a85af5d664afad785e/code/core/src/manager/components/preview/Toolbar.tsx#L185-L190

File: code/core/src/manager/components/preview/Toolbar.tsx [hunk 2]
```diff
@@ -172,12 +181,14 @@ export const ToolbarComp = React.memo<ToolData>(function ToolbarComp({
...
 export const Tools = React.memo<{ list: Addon_BaseType[] }>(function Tools({ list }) {
   return (
-    <>
+    <ToolList>
       {list.filter(Boolean).map(({ render: Render, id, ...t }, index) => (
         // @ts-expect-error (Converted from ts-ignore)
-        <Render key={id || t.key || `f-${index}`} />
+        <ToolListItem key={id || t.key || `f-${index}`}>
+          <Render />
+        </ToolListItem>
```
Comment (kasperpeulen) [inline code/core/src/manager/components/preview/Toolbar.tsx:189]: Did you check if everything looks after the change? Do we have chromatic visuals for those components?

**Review by kasperpeulen — COMMENTED** [review]
Looks great, couple of suggestions

File: code/core/src/manager/components/preview/tools/zoom.tsx (hunk 1 above)
Comment (mehm8128) [reply code/core/src/manager/components/preview/tools/zoom.tsx:63]: For this issue, I think that each button should be wappred with `<li>`, but `Zoom` component includes multiple buttons and so three buttons are grouped by only one `<li>` tag. So I nested unordered list.

Comment (mehm8128) [reply code/core/src/manager/components/preview/tools/zoom.tsx:63]: For this issue, I think that each button should be wappred with `<li>`, but `Zoom` component includes multiple buttons and so three buttons are grouped by only one `<li>` tag. So I nested unordered list(`manager.tsx` is the same).

File: code/core/src/manager/components/preview/Toolbar.tsx (hunk 2 above)
Comment (mehm8128) [reply code/core/src/manager/components/preview/Toolbar.tsx:189]: How much does mean 'everything'? As far as I checked, generally no problem was found in the view.
It looks like there is no story with Toolbar.

**Review by kasperpeulen — APPROVED** [review]

**Comment by kasperpeulen** [comment]
Sorry, for getting back so late, could you fix the merge conflicts?

**Comment by mehm8128** [comment]
@kasperpeulen I resolved the merge conflict. Could you review this again?

**Review by valentinpalkovic — APPROVED** [review]

File: code/core/src/manager/components/preview/Toolbar.tsx [hunk 3]
```diff
@@ -136,8 +136,17 @@ export const ToolbarComp = React.memo<ToolData>(function ToolbarComp({
...
   return tabs || tools || toolsExtra ? (
-    <Toolbar className="sb-bar" key="toolbar" shown={isShown} data-test-id="sb-preview-toolbar">
+    <Toolbar
+      className="sb-bar"
+      aria-labelledby={id}
+      key="toolbar"
+      shown={isShown}
+      data-test-id="sb-preview-toolbar"
+    >
+      <ScreenReaderLabel id={id}>Toolbar</ScreenReaderLabel>
```
Comment (Sidnioulz) [inline code/core/src/manager/components/preview/Toolbar.tsx:149]: @valentinpalkovic FYI I've recently added a CSS util for visually hidden content which could simplify this ScreenReaderLabel code.

Comment (Sidnioulz) [reply code/core/src/manager/components/preview/Toolbar.tsx:149]: See `code/core/src/theming/global.ts`

**Comment by valentinpalkovic** [comment]
Hi @mehm8128 

Thank you so much for your contribution so far.

We have left some comments and the PR got a bit stale. Would you be interested in continuing, resolve the merge conflicts and address the comments? Let us know whether your time allows it. Thanks!

**Comment by mehm8128** [comment]
@valentinpalkovic 
Thank you for contacting, the structure of toolbar seems to be more complex than what I have worked on before, so I'm not motivated to work on this task. So I rebased next branch and only changed toolbar HTML tag name and set visually hidden accessible name without changing toolbar items to listitem.
If it's ok to only change that, please merge this PR as is (or some fix related to the change), or can you close this PR without merging.
