### PR TITLE
Toolbar: Remove extra toolbar divider when zoom controls not shown

### LINKED ISSUE #21429: [Bug]: Extra divider shown in toolbar when zoom controls are not shown
### Describe the bug

image

### To Reproduce

Create a storybook with a toolbar button & view in docs mode

### System

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jonathan-fulton**
## Description

Fixes #21429

In docs mode, an extra divider/separator was appearing in the toolbar even though no tools followed it.

## Problem

The `menuTool` component renders a `<Separator />` after the menu button. This separator is intended to visually separate the menu button from subsequent tools (like `remountTool`). 

However, in docs mode:
- `remountTool` has `match: ({ viewMode }) => viewMode === 'story'` 
- So it gets filtered out in docs mode
- But the `menuTool` still renders its separator
- Result: orphaned separator with nothing to separate

## Solution

Made the `<Separator />` conditional on `viewMode === 'story'`, since that's when the other left-side tools are actually visible.

## Before/After

**Before (docs mode):**
```
[Menu Button] | (empty space - other tools filtered out)
              ^
              orphaned separator
```

**After (docs mode):**
```
[Menu Button] (clean, no orphaned separator)
```

**Story mode (unchanged):**
```
[Menu Button] | [Remount Button] ...
              ^
              separator still appears correctly
```

## Summary by CodeRabbit

* **Bug Fixes**
  * Fixed conditional rendering of menu separators to display correctly based on the current view mode.

### CODE REVIEW

File: code/core/src/manager/components/preview/tools/menu.tsx [hunk 1]
```diff
@@ -35,7 +36,9 @@ export const menuTool: Addon_BaseType = {
             >
               <MenuIcon />
             </Button>
-            <Separator />
+            {/* Only show separator in story mode where other tools (like remount) are visible.
+                In docs mode, most left-side tools are filtered out, leaving an orphaned separator (fixes #21429) */}
+            {viewMode === 'story' && <Separator />}
```
Comment (valentinpalkovic) [inline code/core/src/manager/components/preview/tools/menu.tsx]:
```suggestion
            {viewMode === 'story' && <Separator />}
```

**Review by valentinpalkovic — APPROVED** [review]

**Review by valentinpalkovic — APPROVED** [review]
