### PR TITLE
Core: Fix using dates in expect statements

### LINKED ISSUE #24465: [Bug]: Using dates in expect statements with the interactions add-on causes Storybook to crash
### Describe the bug

Using _dates_ in `expect` statements (from @storybook/jest) within interaction tests (@storybook/addon-interactions) causes storybook to crash when running in the browser, resulting in a blank screen and the following error in the console:

> Uncaught TypeError: e.split is not a function or its return value is not iterable

image

The expect in the following play function causes the error for example:
```
  play: () => {
    const date1 = new Date(Date.UTC(2020, 8, 9));
    const date2 = new Date(Date.UTC(2020, 8, 9));
    expect(date1).toEqual(date2);
  }.
```

The tests pass when running in test-runner.

The error looks to originate from this line in @storybook/addon-interactions where the dates are being rendered for display in the addon-interactions panel (the split string function is being called on the date object): https://github.com/storybookjs/storybook/blob/e9f2e1f7112fc5e391b82ff2d871d3656f5cdfee/code/addons/interactions/src/components/MethodCall.tsx#L345

The error occurs in v7.4.6 and the latest, as in the reproduction linked to below. The error did not occur in v6.5.16 which we were previously on.

### To Reproduce

This error occurs in v7.4.6 of Storybook, also in the latest as in the reproduction link below. The error did not occur in v6.5.16.

Line #35 of Button.stories.js in the reproduction results in the error (i.e. white screen and error in console):

https://stackblitz.com/edit/github-pjbwb9?file=stories%2FButton.stories.js

### System

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yann-combarnous**
Closes #24465

#### The changes in this PR are covered in the following automated tests:
- [x] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

File: code/addons/interactions/src/components/MethodCall.tsx [hunk 1]
```diff
@@ -341,7 +341,7 @@ export const ElementNode = ({
 };
 
 export const DateNode = ({ value }: { value: string | Date }) => {
-  const [date, time, ms] = (value instanceof Date ? value.toISOString() : value).split(/[T.Z]/);
+  const [date, time, ms] = new Date(value).toISOString().split(/[T.Z]/);
```
Comment (jadehamel) [inline code/addons/interactions/src/components/MethodCall.tsx:344]: This change assumes value can always be converted to a valid Date. However, if value is an invalid date string, new Date(value) will result in an invalid Date object (Invalid Date).

It can lead to runtime errors if value is not a valid date string. Consider adding error handling for invalid dates.

Suggestion: To handle potential invalid date values, add error handling and validate the date conversion.

Something like this:

```
export const DateNode = ({ value }: { value: string | Date }) => {
  let dateStr, time, ms;

  try {
    const dateObj = new Date(value);
    if (isNaN(dateObj.getTime())) {
      throw new Error('Invalid date');
    }
    [dateStr, time, ms] = dateObj.toISOString().split(/[T.Z]/);
  } catch (error) {
    console.error('Invalid date value provided to DateNode:', value);
    [dateStr, time, ms] = ['Invalid date', '', ''];
  }

  const colors = useThemeColors();
  return (
    <span style={{ whiteSpace: 'nowrap', color: colors.date }}>
      {dateStr} {time} {ms}
    </span>
  );
}
```

Comment (yann-combarnous) [reply code/addons/interactions/src/components/MethodCall.tsx:344]: My previous version was a bit simpler and I could revert to it:

`const [date, time, ms] = (value instanceof Date ? value.toISOString() : value).split(/[T.Z]/); `

would this work?

Comment (yann-combarnous) [reply code/addons/interactions/src/components/MethodCall.tsx]: Thx @jadehamel , updated PR with catch for invalid date.

File: code/addons/interactions/src/components/MethodCall.tsx [hunk 2]
```diff
@@ -340,16 +340,32 @@ export const ElementNode = ({
...
+      { date !== 'Invalid date' && (
+        <>
+          <span style={{ opacity: 0.7 }}>T</span>
+          {time === '00:00:00' ? <span style={{ opacity: 0.7 }}>{time}</span> : time}
+          {ms === '000' ? <span style={{ opacity: 0.7 }}>.{ms}</span> : `.${ms}`}
+          <span style={{ opacity: 0.7 }}>Z</span>
+        </>
+      )}
     </span>
   );
```
Comment (ghengeveld) [inline code/addons/interactions/src/components/MethodCall.tsx:370]:
```jsx
  const colors = useThemeColors();
  if (!parsed) {
    return <span style={{ whiteSpace: 'nowrap', color: colors.date }}>Invalid date</span>;
  }

  const [date, time, ms] = parsed.toISOString().split(/[T.Z]/);
  return (
    <span style={{ whiteSpace: 'nowrap', color: colors.date }}>
      {date}
      <span style={{ opacity: 0.7 }}>T</span>
      {time === '00:00:00' ? <span style={{ opacity: 0.7 }}>{time}</span> : time}
      {ms === '000' ? <span style={{ opacity: 0.7 }}>.{ms}</span> : `.${ms}`}
      <span style={{ opacity: 0.7 }}>Z</span>
    </span>
  );
```

This is what I would do to decouple the date parsing from the render logic (splitting for purpose of displaying) and avoid the conditional in the template.

**Review by ghengeveld — COMMENTED** [review]
Thanks for picking this up. Date parsing and rendering is always a pain. I think it can be done a little cleaner so I made some suggestions.

File: code/addons/interactions/src/components/MethodCall.tsx (hunk 1 above)
Comment (ghengeveld) [reply code/addons/interactions/src/components/MethodCall.tsx]: This is a good suggestion. I think we can even make do without the try/catch by omitting the `getTime` call.

File: code/addons/interactions/src/components/MethodCall.tsx [hunk 3]
```diff
@@ -340,16 +340,32 @@ export const ElementNode = ({
...
+  if (value instanceof Date) {
+    try {
+      dateSplit = value.toISOString().split(/[T.Z]/);
+    } catch (error) {
+      console.error('Invalid date value provided to DateNode:', value);
+      dateSplit = ['Invalid date', '', ''];
+    }
+  } else {
+    dateSplit = value.split(/[T.Z]/);
+  }
```
[the remark this answers is not in the document]
Comment (yann-combarnous) [reply code/addons/interactions/src/components/MethodCall.tsx]: Done, just added one small change using cast on parsed `if (isNaN(+parsed))` for Typescript to be happy.

**Comment by yann-combarnous** [comment]
> Thanks for picking this up. Date parsing and rendering is always a pain. I think it can be done a little cleaner so I made some suggestions.

Thx, PR updated

**Review by ghengeveld — APPROVED** [review]

**Comment by bodograumann** [comment]
Is that failing test due to this PR or can we merge?

**Comment by kurellajunior** [comment]
Bug’s still around, can we help merging it?
