### PR TITLE
Addon-vitest: Fix coverage being disabled with Run All button

### LINKED ISSUE #30960: [Bug]: Storybook 9 - Status store things that "Run all" is equivalent to focused test run resulting in no code coverage
### Describe the bug

**Repo:** MealDrop
**Branch:** `sbtest-qa`, commit `db25fba146e`

**Steps:**
- Toggle code coverage on
- Run all tests via the main run tests button
- Notice that there is no coverage

Image

### Reproduction link

-

### Reproduction steps

_No response_

### System

```bash
-
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JReinhold**
Closes #30960

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

## Greptile Summary

This PR fixes a bug in the vitest addon by updating the trigger logic in `code/addons/vitest/src/components/TestProviderRender.tsx` so the coverage feature remains enabled when using the "Run All" button.

- Updated trigger logic in `TestProviderRender.tsx` to accept both `'global'` and `'run-all'`.
- Added a type import for `RunTrigger` to support the new trigger.
- Addresses Issue #30960 by ensuring consistent coverage handling during test runs.

### CODE REVIEW

File: code/addons/vitest/src/components/TestProviderRender.tsx [hunk 1]
```diff
@@ -325,7 +325,8 @@ export const TestProviderRender: FC<TestProviderRenderProps> = ({
                   note={
                     watching
                       ? 'Unavailable in watch mode'
-                      : currentRun.triggeredBy && currentRun.triggeredBy !== 'global'
+                      : currentRun.triggeredBy &&
+                          !(['global', 'run-all'] as RunTrigger[]).includes(currentRun.triggeredBy)
```
Comment (ghengeveld) [inline code/addons/vitest/src/components/TestProviderRender.tsx:329]: Maybe extract this to a variable because it doesn't read very well.

**Review by ghengeveld — APPROVED** [review]
