### PR TITLE
Addon-Vitest: Skip postinstall setup when configured

### LINKED ISSUE #33695: [Bug]: Addon-Vitest: Add support for existing `.storybook/vitest.setup.ts` files during postinstall step
### Describe the bug

The current `addon-vitest` postinstall/init script is too sensitive to existing files. If it detects an existing `.storybook/vitest.setup.ts`, the process aborts with an error rather than verifying the configuration and proceeding or skipping gracefully. This creates a friction point for users who are incrementally upgrading or who have manually scaffolded their testing environment.

**Proposed Solution: "Smart Skip" Logic**
Instead of aborting, the postinstall script should be refactored to be idempotent. It should validate the existing environment and only take action if pieces are missing.

**Logic Workflow:**
1. Detect: Check for the existence of .storybook/vitest.setup.ts.
2. Verify Config: Check if vitest.config.ts (or vite.config.ts) already includes:
  - The storybookTest plugin from @storybook/experimental-addon-test.
  - The reference to the setupFiles array pointing to .storybook/vitest.setup.ts.
3. Evaluate:
  - If fully configured: Log a success message (e.g., "Vitest for Storybook is already properly configured. Skipping setup.") and exit gracefully.
  - If partially configured: Only apply the missing pieces (e.g., if the setup file exists but the config doesn't point to it, update the config).

### Reproduction link

-

### Reproduction steps

_No response_

### System

```bash
-
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by valentinpalkovic**
Closes #33695

## What I did

This PR refactors the `@storybook/addon-vitest` postinstall script to be more idempotent and user-friendly. Instead of failing when it encounters existing configurations or setup files, the script now intelligently detects existing setups and avoids redundant modifications.

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [x] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

> [!CAUTION]
> This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This pull request has been released as version `0.0.0-pr-33712-sha-bdf0cf9e`. Try it out in a new sandbox by running `npx storybook@0.0.0-pr-33712-sha-bdf0cf9e sandbox` or in an existing project with `npx storybook@0.0.0-pr-33712-sha-bdf0cf9e upgrade`.
<details>
<summary>More information</summary>

| | |
| --- | --- |
| **Published version** | [`0.0.0-pr-33712-sha-bdf0cf9e`](https://npmjs.com/package/storybook/v/0.0.0-pr-33712-sha-bdf0cf9e) |
| **Triggered by** | @valentinpalkovic |
| **Repository** | [storybookjs/storybook](https://github.com/storybookjs/storybook) |
| **Branch** | [`valentin/addon-vitest-skip-existing-configs`](https://github.com/storybookjs/storybook/tree/valentin/addon-vitest-skip-existing-configs) |
| **Commit** | [`bdf0cf9e`](https://github.com/storybookjs/storybook/commit/bdf0cf9ef7e99f4230898948966a16ac2ad39494) |
| **Datetime** | Fri Jan 30 07:06:56 UTC 2026 (`1769756816`) |
| **Workflow run** | [21507518897](https://github.com/storybookjs/storybook/actions/runs/21507518897) |

To request a new release of this pull request, mention the `@storybookjs/core` team.

_core team members can create a new canary release [here](https://github.com/storybookjs/storybook/actions/workflows/publish.yml) or locally with `gh workflow run --repo storybookjs/storybook publish.yml --field pr=33712`_
</details>

## Summary by CodeRabbit

* **New Features**
  * Postinstall now detects existing Vitest+Storybook setup and reuses existing setup files or skips redundant config updates instead of failing.

* **Tests**
  * Added unit tests covering detection of Vitest/Storybook configuration.

* **Chores**
  * Removed an internal exported error type related to the postinstall flow (internal cleanup).

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: code/addons/vitest/src/postinstall.ts [hunk 1]
```diff
@@ -412,3 +423,52 @@ export default async function postInstall(options: PostinstallOptions) {
     throw new AddonVitestPostinstallError({ errors });
   }
 }
+
+function isStorybookTestPluginSource(value: string) {
+  return value === STORYBOOK_TEST_PLUGIN_SOURCE;
+}
```
Comment (ghengeveld) [inline code/addons/vitest/src/postinstall.ts:429]: Seems a bit unnecessary to have a function for such a trivial thing?

File: code/addons/vitest/src/postinstall.ts [hunk 2]
```diff
@@ -290,18 +295,24 @@ export default async function postInstall(options: PostinstallOptions) {
...
       const source = babelParse(configTemplate);
       target = babelParse(configFile);
       updated = updateConfigFile(source, target);
     }
 
-    if (target && updated) {
+    if (alreadyConfigured) {
+      logger.step(
+        CLI_COLORS.success('Vitest for Storybook is already properly configured. Skipping setup.')
+      );
```
Comment (ghengeveld) [inline code/addons/vitest/src/postinstall.ts:314]: Could reuse the message above.

**Review by ghengeveld — APPROVED** [review]
Nice improvement. Only some minor remarks (feel free to ignore).
