### PR TITLE
Core: Use `exsolve` `resolveModulePath` for `safeResolveModule`

### LINKED ISSUE #32476: [Bug]: 10.0.0-beta.3 continued windows issues
### Describe the bug

On a similar line but unrelated in code to #32364

https://github.com/storybookjs/storybook/blob/ac47ec9a0373842bcdd936f78f50c5b79a3a10b7/code/core/src/shared/utils/module.ts#L117

This line is failing to resolve on windows, because `import-meta-resolve` is returning a value that when passed to fileURLToPath throws a `ERR_INVALID_URL_SCHEME`

Investigations continue...

### Reproduction link

-

### Reproduction steps

_No response_

### System

```bash
windows
yarn pnp
sb@10.0.0-beta.3
```

### Additional context

_No response_

### LINKED ISSUE #32485: [Bug]: `getAbsolutePath` wrapper incorrect on windows
### Describe the bug

To support yarn pnp, frameworks and addons are resolved in the `main.ts` file before being passed to storybook.

This is done with a utility injected by an automigration that adds the following snippet:

```
import { dirname, join } from "node:path";

function getAbsolutePath(value: string): string {
  return dirname(fileURLToPath(require.resolve(join(value, "package.json"))));
}
```

However, on windows this means you would be attempting to resolve, for example, `@storybook/addon-docs\package.json`, which, from my testing at least, results in occasional explosions.

A number of alternatives exist - e.g. importing `join` from `node:path/posix` - but given the triviality of what's going on here, and the likelihood of the module path separator changing any time soon (ie, zero), a simple `\`${value}/package.json\`` is probably sufficient.

### Reproduction link

-

### Reproduction steps

_No response_

### System

```bash
-
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mrginglymus**
- Closes #32476
- Closes #32485

## What I did

Use exsolve for `safeResolveModule`, as this can handle absolute paths on windows (which `fileURLToPath(import.meta.resolve(...))` cannot).

This does mean we bypass the `importMetaResolve` check for vitest...I'm _hoping_ that for this specific use case its ok. 

The linked issue in that code (https://github.com/vitest-dev/vitest/issues/6953) is now closed for vite 7

I've also updated the yarn pnp sandbox to wrap frameworks and addons in `getAbsolutePath`.

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

Just running a sandbox on windows should be enough to demonstrate this.

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

## Greptile Summary

Updated On: 2025-09-16 12:22:17 UTC

This PR addresses a Windows compatibility issue in Storybook 10.0.0-beta.3 by replacing the module resolution implementation in the `safeResolveModule` function. The change switches from using Node.js's native `import.meta.resolve()` combined with `fileURLToPath()` to the `exsolve` library's `resolveModulePath` function.

The core problem was that the previous implementation would throw `ERR_INVALID_URL_SCHEME` errors when handling absolute paths on Windows systems. The `exsolve` library provides better cross-platform compatibility and can properly resolve absolute paths on Windows where the native Node.js resolution methods fail.

The implementation maintains the same API and functionality while simplifying the code structure. Instead of manually looping through file extensions and using multiple try-catch blocks, the new approach uses `exsolve`'s built-in extension handling and only re-throws errors that are not `ERR_MODULE_NOT_FOUND`. This change is part of Storybook's module resolution utilities that are used throughout the codebase for finding and loading various components and configuration files.

## Confidence score: 4/5

- This is a targeted bug fix that addresses a specific Windows compatibility issue with a well-tested third-party library
- The change maintains the same API contract and error handling patterns as the previous implementation  
- Focus attention on the `code/core/src/shared/utils/module.ts` file to ensure the exsolve integration works correctly across different environments

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved reliability of module resolution across ESM, PNPM, and Yarn PnP environments.
  * Angular preset now resolves paths as file URLs to prevent resolution errors.
  * Stabilized CLI automigrations and telemetry path lookups.

* **Refactor**
  * Simplified path construction by replacing join-based logic with template literals.

* **Documentation**
  * Updated migration guide and configuration snippets to the new getAbsolutePath pattern; removed builder example.

* **Breaking Change**
  * Angular preset no longer re-exports from its distribution bundle; update imports to use the official entry points.

### CODE REVIEW

File: code/core/src/shared/utils/module.ts [hunk 1]
```diff
@@ -112,13 +113,17 @@ export const safeResolveModule = ({
...
+      from: parent,
+      extensions: [''].concat(extensions),
+    });
+    if (statSync(resolvedPath).isFile()) {
+      return resolvedPath;
+    }
+  } catch (e: any) {
+    if (e.code !== 'ERR_MODULE_NOT_FOUND') {
+      throw e;
+    }
```
Comment (ndelangen) [inline code/core/src/shared/utils/module.ts]: This is the cause of the error @mrginglymus 

Can you explain why you added this?

**Review by ndelangen — CHANGES_REQUESTED** [review]

File: code/core/src/shared/utils/module.ts (hunk 1 above)
Comment (ndelangen) [reply code/core/src/shared/utils/module.ts]: I've removed the code, for now.

**Review by jonniebigodes — APPROVED** [review]
@mrginglymus thanks for taking the time to update the documentation. Appreciate it 🙏 ! I've checked and all is good on my end. I'll defer to @ndelangen on this, as he left some items for you to check when you're able.

Have a great day.

Stay safe

File: code/core/src/shared/utils/module.ts (hunk 1 above)
Comment (mrginglymus) [reply code/core/src/shared/utils/module.ts]: Because the old logic would iterate through extensions it was expected that at least some of them would throw, but that's ok because the throw just said 'move on to the next extension'- they are recoverable exceptions.

However, this was _also_ catching and thus masking the critical error from `fileURLToPath` (or whichever function was choking on windows absolute paths).

I'd hoped that being a bit more selective in error codes would allow to differentiate between 'the module isn't there, let's just carry on' (ie, the existing behaviour) and 'there's a critical configuration error or bug in storybook that needs fixing'.

Obviously I've missed the target there and we're getting more than just `ERR_MODULE_NOT_FOUND` on the happy path.

**Review by ndelangen — APPROVED** [review]
