### PR TITLE
ESLint: Only apply csf-strict rules on stories files

### LINKED ISSUE #155: csf-strict is applied on all files
**Describe the bug**
The csf-strict preset isn't restricted to stories, unlike the csf and recommended presets. This causes the following two rules to be disabled everywhere:
```
'react-hooks/rules-of-hooks': 'off',
'import/no-anonymous-default-export': 'off',
```

**To Reproduce**
https://github.com/storybookjs/eslint-plugin-storybook/blob/main/lib/configs/csf-strict.ts

**Expected behavior**
csf-strict preset to be applied only to stories.

### PR DESCRIPTION
**Pull request by cylewaitforit**
Closes https://github.com/storybookjs/eslint-plugin-storybook/issues/155

## What I did

Updated csf-strict rules to apply on stories files. This is to fix csf-strict from disabling 'react-hooks/rules-of-hooks' and 'import/no-anonymous-default-export' for an entire project.

This updates and moves a PR the was previously opened in the eslint-plugin-storybook repo.

https://github.com/storybookjs/eslint-plugin-storybook/pull/201

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

## Greptile Summary

Updates the ESLint csf-strict configuration to properly scope rules to story files only, fixing incorrect project-wide rule application.

- Modified `code/lib/eslint-plugin/src/configs/csf-strict.ts` to target only `*.stories.*` and `*.story.*` files using overrides
- Fixed unintended disabling of `react-hooks/rules-of-hooks` and `import/no-anonymous-default-export` rules across entire projects
- Updated both traditional and flat config generation scripts to respect story file patterns
- Scoped rules to supported file extensions (ts, tsx, js, jsx, mjs, cjs) for better specificity

## Summary by CodeRabbit

- Bug Fixes
  - CSF Strict rules now apply only to Storybook story files, reducing false positives in non-story code.
  - Flat config explicitly targets story files via file globs for consistent behavior across config formats.
- Refactor
  - Migrated from global rules to per-file overrides for clearer, more precise linting scope.
- Chores
  - Updated config generation to include file-based targeting when categories extend others, aligning legacy and flat configs.

### CODE REVIEW

**Comment by cylewaitforit** [comment]
Hey @valentinpalkovic I saw you had assigned this out, but I see last week it has been marked stale. Is there anything you need from me to address this?

**Comment by valentinpalkovic** [comment]
No. I think we're good, but just busy with the 9.1 release. I am sure that after releasing 9.1, @yannbf will take a look!

File: code/lib/eslint-plugin/src/configs/csf-strict.ts [hunk 1]
```diff
@@ -7,10 +7,15 @@ export = {
...
   extends: './configs/csf',
-  rules: {
-    'react-hooks/rules-of-hooks': 'off',
-    'import/no-anonymous-default-export': 'off',
-    'storybook/no-stories-of': 'error',
-    'storybook/no-title-property-in-meta': 'error',
-  } as const,
+  overrides: [
+    {
+      files: ['**/*.stories.@(ts|tsx|js|jsx|mjs|cjs)', '**/*.story.@(ts|tsx|js|jsx|mjs|cjs)'],
```
Comment (yannbf) [inline code/lib/eslint-plugin/src/configs/csf-strict.ts:12]: Hey there @cylewaitforit, thanks for your contribution!
Won't this block users from specifying their own files to apply these rules? As it now has hardcode file paths? Perhaps we can do differently and leave things as they were, and only move these general, conflicting rules to a new entry that's always added, and has the hardcoded paths:

```
        'react-hooks/rules-of-hooks': 'off',
        'import/no-anonymous-default-export': 'off',
```

What do you think?

Comment (cylewaitforit) [reply code/lib/eslint-plugin/src/configs/csf-strict.ts:12]: Hey @yannbf, thanks for reviewing. This updates csf-strict to follow the same pattern used by the other configs (see https://github.com/storybookjs/storybook/blob/next/code/lib/eslint-plugin/src/configs/recommended.ts and https://github.com/storybookjs/storybook/blob/next/code/lib/eslint-plugin/src/configs/csf.ts). Users should still have the ability to make any overrides in their own config after extending.

Comment (cylewaitforit) [reply code/lib/eslint-plugin/src/configs/csf-strict.ts:12]: @yannbf Another option, if you’re concerned about this legacy config, might be to only leave the fix for the Flat Config and instead mark the legacy config options as deprecated for removal in V10 of this storybook eslint plugin.

Overriding files types for a config on the user side is very straight forward in the flat config and can be easily verified with the [eslint config inspector.](https://github.com/eslint/config-inspector)

Comment (cylewaitforit) [reply code/lib/eslint-plugin/src/configs/csf-strict.ts:12]: @yannbf Are the legacy configs staying in eslint for Storybook 10 or will they be removed?

Comment (yannbf) [reply code/lib/eslint-plugin/src/configs/csf-strict.ts:12]: Hey there, I'm so sorry this has become stale for so long.
We don't have plans to drop ESLint v8 support as there are still tons of users on that version.
Additionally, I spent some time today on this PR and made changes to address my concern, by separating the normal rules (without any overrides) to the extra overrides (which would use the overrides), so that users can define any file name for stories.. but to be honest, this plugin's purpose is to help users follow standards, and the story file name is a standard 😅 so I'll just go on and accept your PR as is! Thank you so much for your contribution 🙏 

If users report this as a breaking change I'll revisit this.

**Review by yannbf — APPROVED** [review]

File: code/lib/eslint-plugin/src/configs/csf-strict.ts (hunk 1 above)
Comment (cylewaitforit) [reply code/lib/eslint-plugin/src/configs/csf-strict.ts:12]: Thanks @yannbf! Appreciate the time and thoughtfulness you gave to the review.
