### PR TITLE
SvelteKit: Only disable SSR when building, not serving

### LINKED ISSUE #21053: [Bug]: HMR not working on SvelteKit and Storybook
### Describe the bug

Hot module reload is not working with a fresh install of sveltekit and storybook.

### To Reproduce

```shell
npm create svelte@latest .
npx sb@next init
npm run storybook

Make a change in src/stories/Button.svelte
Does not automatically update on localhost:6006
Remount component button also does not update it. Only page reload
```

### System

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
  Binaries:
    Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (109.0.1518.78)
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.46 => 7.0.0-beta.46
    @storybook/addon-interactions: ^7.0.0-beta.46 => 7.0.0-beta.46
    @storybook/addon-links: ^7.0.0-beta.46 => 7.0.0-beta.46
    @storybook/blocks: ^7.0.0-beta.46 => 7.0.0-beta.46
    @storybook/svelte: ^7.0.0-beta.46 => 7.0.0-beta.46
    @storybook/sveltekit: ^7.0.0-beta.46 => 7.0.0-beta.46
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JReinhold**
Closes #21053

## What I did

In #20804 we disabled SSR because Storybook can't be built with SSR enabled.

That broke HMR, so now we're only disabling SSR at build time, not when serving.

I'm unsure why it broke HMR, but it's not SvelteKit related, as it also breaks HMR to add that disable-SSR plugin to a plain Svelte-Vite project.

It looks like the Svelte Vite plugin is using the SSR setting to handle HMR differently, so maybe that's the culprit. 

https://github.com/sveltejs/vite-plugin-svelte/blob/main/packages/vite-plugin-svelte/src/handle-hot-update.ts#L61-L65

## How to test

1. Create a SvelteKit sandbox with `yarn task --task sandbox --start-from auto --template svelte-kit/skeleton-ts`
2. Start it and open a story.
3. Make changes to the story, and see that they are reflected in the UI.
3. Make changes to the component, and see that they are reflected in the UI.
4. Build the Storybook to ensure it can still be built.

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

File: code/frameworks/sveltekit/src/plugins/config-overrides.ts [hunk 1]
```diff
@@ -2,14 +2,11 @@ import type { Plugin } from 'vite';
...
+    // SvelteKit sets SSR, we need it to be false when building
     name: 'storybook:sveltekit-overrides',
-    config: (conf) => {
-      // Some versions of sveltekit set ssr, we need it to be false
-      if (conf.build?.ssr) {
-        // eslint-disable-next-line no-param-reassign
-        conf.build.ssr = false;
-      }
-      return conf;
+    apply: (_, { command }) => command === 'build',
```
Comment (IanVS) [inline code/frameworks/sveltekit/src/plugins/config-overrides.ts:7]: This can be simplified to `apply: 'build'`

**Review by IanVS — APPROVED** [review]
This is so bizzare, but good find.  I'd lean towards considering it a vite or plugin-svelte issue, but this seems like a good workaround.

**Comment by JReinhold** [comment]
> This is so bizzare, but good find. I'd lean towards considering it a vite or plugin-svelte issue, but this seems like a good workaround.

I agree, I'll see if I can build a non-Storybook repro and file an issue over there.
