### PR TITLE
Webpack: Improve performance of module-mocking plugins

### LINKED ISSUE #33778: [Bug]: WebpackMockPlugin and resolveWithExtensions (Storybook mocks) slow down story loading by 5-10x (3-5s on medium-sized codebase)
## Investigation

After upgrading to Storybook 10, we noticed that the speed was much slower than Storybook 6. To investigate this, I profiled the performance and compare Storybook 6 and Storybook 10. 

## Summary

The Webpack configuration from Builder Webpack 5 for mocks was causing Storybook to be extremely slow. After profiling, we found that `resolveWithExtensions` from the Storybook mocking utils was taking approximately 7-8 seconds of total render time, accounting for most of the performance bottleneck.

## Profiling process

1. Removed `node_modules/.cache` to ensure a clean state
2. Killed Storybook
3. Launched Storybook
4. Found processes that used Storybook
5. Used Node.js debugging to open a Chrome inspector port: `kill -USR1 $PID`
6. Went to `chrome://inspect` to access the performance profiler
7. Pressed record
8. On Storybook, switched from one standard story (the default one) to another story (AddAttachmentModal in our codebase)
9. Stopped recording

## Findings

Through profiling, we discovered:

- In v10: **fileExistsWithCase took 5729ms**, of which resolveWithExtensions and an (anonymous) function from `node_modules/@storybook/builder-webpack5/dist/presets/custom-webpack-preset.js` took most of it

Image

- In v6: **fileExistsWithCase took 160.8ms**

Image

More details

- The stack trace showed a ton of work being done in `custom-webpack-preset.js`
- An anonymous function in `custom-webpack-preset.js` was calling `resolveWithExtensions`, which is a function within the Storybook mocking utils
- `resolveWithExtensions` accounted for a huge amount of the total time
- In the call tree, searching for `resolveWithExtensions` showed it took almost 7 seconds of the total time, which is approximately 7/8 of basically all the time that any function took

## Solution

After commenting out the plugin (node_modules/@storybook/builder-webpack5/dist/presets/custom-webpack-preset.js):

```ts
async function webpackFinal(config, options) {
  // Delete everything in here and replace with a no-op
  return config;
}
```

**fileExistsWithCase only took 278ms after the fix**

Image

### Realistic solution

Here are a few options

1. Offer an option to disable mocks for a performance benefit
2. Optimize resolveWithExtensions to use a cache or generally just be much faster

### Reproduction link

https://github.com/hsource/storybook-example

### Reproduction steps

Check out the repository, which has lazyLoading enabled. **Note:** With the tiny test repository, the difference is tens of milliseconds rather than the seconds in the larger real repo I tested on. The difference is still measurable in the stacktrace.

1. Removed `node_modules/.cache` to ensure a clean state
2. Killed Storybook
3. Launched Storybook
4. Found processes that used Storybook
5. Used Node.js debugging to open a Chrome inspector port: `kill -USR1 $PID`
6. Went to `chrome://inspect` to access the performance profiler
7. Pressed record
8. On Storybook, switched from one standard story (the default one) to another story (AddAttachmentModal in our codebase)
9. Stopped recording

### System

```bash
│  Storybook Environment Info:
│

│  System:
│  OS: macOS 26.2
│  CPU: (10) arm64 Apple M1 Pro
│  Shell: 5.9 - /bin/zsh
│  Binaries:
│  Node: 22.14.0 - /Users/harry/.nvm/versions/node/v22.14.0/bin/node
│  Yarn: 1.22.22 - /Users/harry/.nvm/versions/node/v22.14.0/bin/yarn <----- active
│  npm: 10.9.2 - /Users/harry/.nvm/versions/node/v22.14.0/bin/npm
│  pnpm: 9.1.0 - /Users/harry/.nvm/versions/node/v22.14.0/bin/pnpm
│  Browsers:
│  Chrome: 144.0.7559.132
│  Firefox: 146.0.1
│  Safari: 26.2
│  npmPackages:
│  @storybook/addon-styling-webpack: ^3.0.0 => 3.0.0
│  @storybook/addon-webpack5-compiler-babel: ^4.0.0 => 4.0.0
│  @storybook/react: ^10.2.3 => 10.2.3
│  @storybook/react-webpack5: ^10.2.1 => 10.2.1
│  @storybook/test-runner: ^0.24.2 => 0.24.2
│  eslint-plugin-storybook: ^0.6.8 => 0.6.8
│  storybook: ^10.2.1 => 10.2.1
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by valentinpalkovic**
Closes https://github.com/storybookjs/storybook/issues/33778

## What I did

During Hot Module Replacement (HMR) in development mode, the Webpack builder was performing unnecessary work on every compilation, leading to slower rebuild times. E.g.: The mocker runtime script was being regenerated and re-emitted on every compilation, even though it never changes and the mock map was being rebuilt on every watch run, even when the preview config file hadn't changed

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This pull request has been released as version `0.0.0-pr-33169-sha-8cabf98d`. Try it out in a new sandbox by running `npx storybook@0.0.0-pr-33169-sha-8cabf98d sandbox` or in an existing project with `npx storybook@0.0.0-pr-33169-sha-8cabf98d upgrade`.
<details>
<summary>More information</summary>

| | |
| --- | --- |
| **Published version** | [`0.0.0-pr-33169-sha-8cabf98d`](https://npmjs.com/package/storybook/v/0.0.0-pr-33169-sha-8cabf98d) |
| **Triggered by** | @valentinpalkovic |
| **Repository** | [storybookjs/storybook](https://github.com/storybookjs/storybook) |
| **Branch** | [`valentin/fix-hmr-for-webpack-users`](https://github.com/storybookjs/storybook/tree/valentin/fix-hmr-for-webpack-users) |
| **Commit** | [`8cabf98d`](https://github.com/storybookjs/storybook/commit/8cabf98da93e7f6fbcd64cc5f601695fdc3aaf5e) |
| **Datetime** | Wed Jan 21 12:02:37 UTC 2026 (`1768996957`) |
| **Workflow run** | [21208826124](https://github.com/storybookjs/storybook/actions/runs/21208826124) |

To request a new release of this pull request, mention the `@storybookjs/core` team.

_core team members can create a new canary release [here](https://github.com/storybookjs/storybook/actions/workflows/publish.yml) or locally with `gh workflow run --repo storybookjs/storybook publish.yml --field pr=33169`_
</details>

## Summary by CodeRabbit

* **Bug Fixes**
  * Prevents duplicate mock asset emission during builds and improves error handling during asset generation.

* **Performance**
  * Caches runtime generation and skips unnecessary mock re-extraction when preview config is unchanged to speed rebuilds.

* **Reliability**
  * Skips processing when no mocks are present and more robustly detects preview-config changes to reduce spurious work.

### CODE REVIEW

File: code/builders/builder-webpack5/src/plugins/webpack-mock-plugin.ts [hunk 1]
```diff
@@ -67,16 +69,24 @@ export class WebpackMockPlugin {
...
           [mock.absolutePath, mock],
-          // second one, without the extension
           [mock.absolutePath.replace(/\.[^.]+$/, ''), mock],
         ])
       );
-      // divide by 2 because we add both the full path and the path without the extension
-      logger.info(`Mock map updated with ${this.mockMap.size / 2} mocks.`);
+      this.candidateSpecifiers = new Set(resolved.map((m) => m.path));
+      this.lastPreviewMtime = mTimePreviewConfig;
+      logger.info(`Mock map updated with ${resolved.length} mocks.`);
```
Comment (yannbf) [inline code/builders/builder-webpack5/src/plugins/webpack-mock-plugin.ts]: little reminder, now that you're touching this file, to either:
- not show the log when the count is 0
- only show the log if the current count is 0 and previous count wasn't 0 (so you don't keep showing "updated 0 mocks" every time)
