### PR TITLE
Core: Fix URL load failure due to missing base

### LINKED ISSUE #10227: Failed to construct 'URL': Invalid URL [6.0.0-alpha.29]
**Describe the bug**
After updating from`6.0.0-alpha.6` to `6.0.0-alpha.29` Storybook freezes with spinning loader and shows an error message.

```
TypeError: Failed to construct 'URL': Invalid URL
    at getEventSourceUrl (vendors~main.cb19d1134e7321a2d4ff.bundle.js:9519)
    at PostmsgTransport.handleEvent (vendors~main.cb19d1134e7321a2d4ff.bundle.js:9467)
```

**Expected behavior**
Storybook should load stories as usual.

**Screenshots**
Screen Shot 2020-03-27 at 08 47 43

**System:**
Browsers: 
- Chrome 80.0.3987.149 (Official Build) (64-bit)
- Firefox 74.0 (64-bit)

```
Environment Info:

  System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 74.0
    Safari: 13.0.5
  npmPackages:
    @storybook/addon-actions: 6.0.0-alpha.29 => 6.0.0-alpha.29 
    @storybook/addon-docs: 6.0.0-alpha.29 => 6.0.0-alpha.29 
    @storybook/addon-knobs: 6.0.0-alpha.29 => 6.0.0-alpha.29 
    @storybook/addon-links: 6.0.0-alpha.29 => 6.0.0-alpha.29 
    @storybook/addon-storysource: v6.0.0-alpha.29 => 6.0.0-alpha.29 
    @storybook/addon-viewport: v6.0.0-alpha.29 => 6.0.0-alpha.29 
    @storybook/addons: v6.0.0-alpha.29 => 6.0.0-alpha.29 
    @storybook/react: v6.0.0-alpha.29 => 6.0.0-alpha.29 
    @storybook/source-loader: v6.0.0-alpha.29 => 6.0.0-alpha.29 
```

### PR DESCRIPTION
**Pull request by ndelangen**
Issue: #10227 

## What I did

- ADD a try-catch around the `new URL` call, and attempt again with base parameter

### CODE REVIEW

File: lib/channel-postmessage/src/index.ts [hunk 1]
```diff
@@ -205,11 +205,18 @@ const getEventSourceUrl = (event: MessageEvent) => {
     try {
       return element.contentWindow === event.source;
     } catch (err) {
-      const src = element.getAttribute('src');
-      const { origin } = new URL(src);
+      //
```
Comment (shilman) [inline lib/channel-postmessage/src/index.ts]: comment here?

File: lib/channel-postmessage/src/index.ts [hunk 2]
```diff
@@ -205,11 +205,18 @@ const getEventSourceUrl = (event: MessageEvent) => {
...
+    }
+
+    const src = element.getAttribute('src');
+    let origin;
 
-      return origin === event.origin;
+    try {
+      ({ origin } = new URL(src));
+    } catch (err) {
+      ({ origin } = new URL(src, document.location));
```
Comment (idbartosz) [inline lib/channel-postmessage/src/index.ts]: Since the second argument will be called implicitly with `document.location.toString()` so wouldn't `new URL(document.location)` be sufficient in this case?

Comment (ndelangen) [reply lib/channel-postmessage/src/index.ts]: Yeah I guess..

Comment (idbartosz) [reply lib/channel-postmessage/src/index.ts]: I'm posting my proposal here but I leave it up to you folks 👍 

```js
  try {
    ({ origin } = new URL(src, document.location));
  } catch (err) {
    // throws when src contains invalid absolute URL
    console.error(`Failed to obtain iframe origin from src: ${src}`);
    throw err;
  }
```

Comment (ndelangen) [reply lib/channel-postmessage/src/index.ts]: Does adding the document.location do nothing when the passed src is already a full url?

Comment (idbartosz) [reply lib/channel-postmessage/src/index.ts]: @ndelangen yes, you can find a note about the behavior in [docs](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL)

> If url is a relative URL, base is required, and will be used as the base URL. If url is an absolute URL, a given base will be ignored.

Comment (ndelangen) [reply lib/channel-postmessage/src/index.ts]: TIL, thanks!

**Review by shilman — APPROVED** [review]
LGTM

**Comment by shilman** [comment]
@ndelangen any idea what's going on with the CI?

**Comment by idbartosz** [comment]
Looks good, what about those lines?

https://github.com/storybookjs/storybook/blob/35abb7a1c8af9a673783ed931e3c7d75bdcf9214/lib/channel-postmessage/src/index.ts#L228-L230

**Comment by idbartosz** [comment]
Nice, thank you @ndelangen 👍 

BTW I've noticed that Storybook now uses Prettier 2.0 maybe it's worth to run it across the whole codebase to not pollute new PRs with unrelated changes 😉

**Comment by ndelangen** [comment]
https://github.com/storybookjs/storybook/pull/10236
