### PR TITLE
Next.js: Fix Link component override in appDirectory configuration

### LINKED ISSUE #30390: [Bug]: Next.js Link component causes navigation to a non-existent page in stories
### Describe the bug

When using the `Link` component from Next.js 15 within an `appDirectory` configuration, the component behavior is not properly overridden. This leads to navigating directly to nonexistent pages after clicking the link. 

This behavior does not occur with Next.js 14.

### Reproduction link

https://stackblitz.com/edit/github-6hzs76ok?file=src%2Fstories%2FHeader.tsx

### Reproduction steps

1. Go to the above link
2. Go to a story of the Header component
3. Click the link on the header, and the preview will crush

### System

```bash
Storybook Environment Info:

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm <----- active
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @storybook/addon-essentials: ^8.6.0-alpha.2 => 8.6.0-alpha.2 
    @storybook/addon-interactions: ^8.6.0-alpha.2 => 8.6.0-alpha.2 
    @storybook/addon-onboarding: ^8.6.0-alpha.2 => 8.6.0-alpha.2 
    @storybook/blocks: ^8.6.0-alpha.2 => 8.6.0-alpha.2 
    @storybook/nextjs: ^8.6.0-alpha.2 => 8.6.0-alpha.2 
    @storybook/react: ^8.6.0-alpha.2 => 8.6.0-alpha.2 
    @storybook/test: ^8.6.0-alpha.2 => 8.6.0-alpha.2 
    storybook: ^8.6.0-alpha.2 => 8.6.0-alpha.2
```

### Additional context

[Proper behavior with Next.js 14](https://stackblitz.com/edit/github-scn3vgkf?file=src%2Fstories%2FHeader.tsx,src%2Fstories%2FHeader.stories.ts&preset=node)

### PR DESCRIPTION
**Pull request by yatishgoel**
Closes #30390

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

## Greptile Summary

Added mock implementation and webpack alias mappings for Next.js Link component to fix navigation issues in Next.js 15 with appDirectory configuration.

- Added `code/frameworks/nextjs/src/export-mocks/link/index.tsx` with mock Link component implementation
- Added Link component mappings in `code/frameworks/nextjs/src/export-mocks/webpack.ts` for proper aliasing
- Updated `code/frameworks/nextjs/package.json` exports to include new Link mock component
- Added support for Next.js 15.0.0 as peer dependency

The changes ensure proper Link component behavior in stories by preventing navigation to non-existent pages when using Next.js 15 in appDirectory mode.

## Summary by CodeRabbit

* **New Features**
  * Added a mock for the Next.js Link component, enabling improved Storybook testing support for Next.js projects.
  * Introduced new compatibility utilities for segment and redirect status code handling.
  * Extended public API exports for easier access to mocking and compatibility modules.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Review by valentinpalkovic — APPROVED** [review]

**Comment by valentinpalkovic** [comment]
Hi @yatishgoel,

Thank you for opening the PR!

Could you take a look at the build pipeline? Unfortunately, it is failing.

**Comment by valentinpalkovic** [comment]
Superseded by https://github.com/storybookjs/storybook/pull/32131

**Comment by ryami333** [comment]
@valentinpalkovic – seeing as https://github.com/storybookjs/storybook/pull/32131 did not actually address the issue, should this PR be re-evaluated?

**Comment by valentinpalkovic** [comment]
@yatishgoel Could you merge `next` into your PR and resolve the merge conflicts?

**Comment by yatishgoel** [comment]
Thanks for prioritizing this! Let me know if anything else is needed.

**Comment by valentinpalkovic** [comment]
Hi @yatishgoel 

Thank you for resolving the merge conflicts. Could you please take a look into the build errors for `next-js-latest--webpack---typescript---build`?

**Comment by valentinpalkovic** [comment]
Hi @yatishgoel 

the nextjs Link story is broken. Empty links are rendered. 

[
IMG_1205
](url)

**Comment by yatishgoel** [comment]
Hi @valentinpalkovic,                                                                                                                                           
                                                                                                                                                                    
The empty links are happening because the mock uses `fn()` as the default export. `fn()` without an implementation returns `undefined` when React calls it as a component, so nothing renders.                                                                                                                                    
                                                                                                                                                                    
I'm planning to replace it with a `React.forwardRef` component that renders a plain `<a>` tag, stripping Next.js-specific props like `replace, scroll, prefetch`. This is similar to how the image mock works, real DOM rendering without the Next.js navigation layer.

One tradeoff is that the mock would no longer use `fn()`, so users won't be able to track or assert Link interactions in their tests. Would this approach work, or would you prefer a different direction?

**Comment by valentinpalkovic** [comment]
Can't we just create an `a` element with an `onClick` handler, which suppresses the navigation (e.preventDefault) and also calls `fn() inside the ' onClick ' handler so that link clicks are logged to the action panel?

**Review by valentinpalkovic — APPROVED** [review]

**Comment by lencioni** [comment]
I believe this may not work correctly for Next.js links with `legacyBehavior`. I opened an issue https://github.com/storybookjs/storybook/issues/33861

File: code/frameworks/nextjs/src/export-mocks/link/index.tsx [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+    e.preventDefault();
+    onClick?.(e);
+    linkAction(hrefString, { replace, scroll, shallow, prefetch, locale });
+  };
+
+  return (
+    <a ref={ref} href={hrefString} onClick={handleClick} {...rest}>
+      {children}
+    </a>
+  );
```
Comment (lencioni) [inline code/frameworks/nextjs/src/export-mocks/link/index.tsx:39]: I think if `legacyBehavior` is true, this should pass the props onto the child instead of rendering an `<a>` itself. https://github.com/storybookjs/storybook/issues/33861

See here: https://github.com/vercel/next.js/blob/b0595b17ae331a2e1cccff35da8d093f0636c8e1/packages/next/src/client/link.tsx#L680-L690
