### PR TITLE
Core: Fix internal yarn build command

### LINKED ISSUE #33432: [Bug]: yarn build fails with Commander error: "option creation failed due to no flags found in 'addon-a11y'"
### Describe the bug

Running `yarn build `for the Storybook fails with a commander error:
```log
/storybook/code$ yarn build
storybook/node_modules/commander/lib/option.js:372
    throw new Error(
          ^

Error: option creation failed due to no flags found in 'addon-a11y'.
    at splitOptionFlags (storybook/node_modules/commander/lib/option.js:372:11)
    at new Option (storybook/node_modules/commander/lib/option.js:20:25)
    at Command.createOption (storybook/node_modules/commander/lib/command.js:586:12)
    at Command._optionEx (storybook/node_modules/commander/lib/command.js:747:25)
    at Command.option (storybook/node_modules/commander/lib/command.js:789:17)
    at storybook/scripts/build-package.ts:84:28
    at Array.reduce (<anonymous>)
    at run (storybook/scripts/build-package.ts:84:3)

Node.js v22.21.1
```

### Reproduction link

...

### Reproduction steps

1. Clone the repository and install dependencies
2. cd code
3. yarn build

### System

```bash
OS: Linux (WSL)
Node.js: v22.21.1
Yarn: v4.10.3 (via corepack)
corepack: enabled and active
yarn binary: ~/.nvm/versions/node/v22.21.1/bin/yarn
```

### Additional context

This change resolves the build issue, but the exact root cause of the original `commander` error (“no flags found in 'addon-a11y'”) has not been fully investigated.

Modified Code Example:
storybook/scripts/build-package.ts
```ts
const packages = (await getCodeWorkspaces()).filter(({ name }) => name !== '@storybook/code');
const packageTasks = packages.map((pkg) => {
  let name = pkg.name.replace('@storybook/', '');

  if (pkg.name === '@storybook/cli') {
    name = 'sb-cli';
  }

  // Construct a flag that commander can recognize
  const suffix = `--${name}`;

  // Create a command-line option for each package
  return program.option(suffix, `Build ${name} package`);
});
```

### PR DESCRIPTION
**Pull request by Sidnioulz**
Closes #33432 

## What I did

* Fixed regression caused by an upgrade to the commander dependency (thanks @ia319 for diagnosing it)
* Repaired `yarn build --all` which incorrectly caused the script to exit
* Fixed bug when passing `--all storybook` which incorrectly assumed `storybook` is an invalid package name due to incorrect package name filtering
* Restored old package order with the main `storybook` package appearing first, as it's the most useful
* Made `--watch` and `--prod` flags skip relevant prompts when passed without package name
* Added `--no-watch` and `--no-prod` counterparts with the same effect
* Documented `yarn build` flags

### Testing
ø

#### Manual testing

Run commands:

* `yarn build`, you will get fully prompted (watch + prod + packages, `storybook appears first)
* `yarn build --all`, build will start
* `yarn build --all storybook`, build will start
* `yarn build --all addon-a11y`, build will start
* `yarn build storybook addon-a11y`, build will start with only 2 packages
* `yarn build --all --watch`, build will start in watch mode
* `yarn build --watch --no-prod`, you will be prompted only package names, and build will start in watch mode and development mode

### Documentation

- [x] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [x] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [x] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/publish.yml) or locally with `gh workflow run --repo storybookjs/storybook publish.yml --field pr=<PR_NUMBER>`_

## Summary by CodeRabbit

* **Documentation**
  * Added documentation for the yarn build command, covering --all, --watch, --prod (and examples for building specific packages).

* **Chores**
  * Improved the build CLI: clearer package selection ordering, explicit disable options, better validation and error messages, conditional prompts, and clearer build/output messaging.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Review by ndelangen — APPROVED** [review]

File: scripts/build-package.ts [hunk 1]
```diff
@@ -5,12 +5,14 @@
...
- * You can also pass the `--watch` flag to build in watch mode.
+ * Pass the `--watch` flag to build in watch mode or `--no-watch` to skip the watch mode prompt.
  *
- * You can also pass the `--prod` flag to build in production mode.
+ * Pass the `--prod` flag to build in production mode or `--no-prod` to skip the production prompt.
  *
  * When you pass no package names, you will be prompted to select which packages to build.
  */
+// FIXME --all not working
+// FIXME --no-watch and --no-prod needed
```
Comment (Sidnioulz) [inline scripts/build-package.ts]:
```suggestion
```

File: scripts/build-package.ts [hunk 2]
```diff
@@ -36,102 +48,74 @@ async function run() {
...
+          `${picocolors.red('Error')}: ${picocolors.cyan(
+            arg
+          )} is not a valid package name, Did you mean ${picocolors.cyan(matchText)}?\n`
+        );
       }
     }
+  }
 
+  if (hasInvalidName) {
     process.exit(0);
```
Comment (Sidnioulz) [inline scripts/build-package.ts]:
```suggestion
    process.exit(1);
```
