### PR TITLE
Manager: Do not display non-existing shortcuts in the settings page

### LINKED ISSUE #32464: [Bug]: Keyboard shortcuts are missing labels on page refresh
### Describe the bug

This is what I see:

Image

### Reproduction link

Storybook UI

### Reproduction steps

1. Open keyboard shortcuts
2. Refresh the page
3. Scroll down

### System

```bash
MacOS: 15.6.1
Firefox Dev Edition: 143.0b9 (aarch64)
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by DKER2**
Closes https://github.com/storybookjs/storybook/issues/32464

addonsShortcutLabels and addonsShortcut is initilized as empty dict on start of programs, but because of localstorage from previous session, it retrieve the list of shortcuts with previously initialized addon shortcut. This PR will hide any addon-shortcut if it have not been initiliazed in new start

Thank you for contributing to Storybook! Please submit all PRs to the `next` branch unless they are specific to the current release. Storybook maintainers cherry-pick bug and documentation fixes into the `main` branch as part of the release process, so you shouldn't need to worry about this. For additional guidance: https://storybook.js.org/docs/contribute

-->

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/publish.yml) or locally with `gh workflow run --repo storybookjs/storybook publish.yml --field pr=<PR_NUMBER>`_

## Summary by CodeRabbit

* **Bug Fixes**
  * Shortcut settings now hide entries without visible labels, cleaning up the shortcuts list.

* **Refactor**
  * Shortcut rendering simplified to only show available labeled shortcuts.

* **Removed**
  * Built-in Jest addon and its Test panel have been removed.

* **Documentation**
  * Migration guidance updated for ESM and explicit file extensions; changelogs and snippets updated (Next.js Vite plugin, a11y export rename to initialGlobals).

* **Behavior**
  * Story navigation now prefers visible children when an index is filtered, improving navigation with active filters.

### CODE REVIEW

File: code/core/src/manager/settings/shortcuts.tsx [hunk 1]
```diff
@@ -287,8 +287,13 @@ class ShortcutsScreen extends Component<ShortcutsScreenProps, ShortcutsScreenSta
 
   renderKeyInput = () => {
     const { shortcutKeys, addonsShortcutLabels } = this.state;
-    // @ts-expect-error (non strict)
-    const arr = Object.entries(shortcutKeys).map(([feature, { shortcut }]: [Feature, any]) => (
+    const availableShortcuts = (Object.entries(shortcutKeys) as [Feature, any][]).filter(
```
Comment (Sidnioulz) [inline code/core/src/manager/settings/shortcuts.tsx:291]:
```suggestion
    // Filter out keyboard shortcuts from localStorage that no longer exist in code
    const availableShortcuts = (Object.entries(shortcutKeys) as [Feature, any][]).filter(
```

Comment (Sidnioulz) [reply code/core/src/manager/settings/shortcuts.tsx:291]: It would help us in the future if you could comment why this filtering is necessary :)

**Review by Sidnioulz — CHANGES_REQUESTED** [review]
Thanks for your contribution @DKER2!

I think something is wrong with the applied logic unfortunately. I am consistently missing Toggle Outline on both my existing sets of browsers with expired shortcuts and on a fresh port with the default shortcuts.

I think it would be wiser to figure out what is defined in the code, and filter out the settings in local storage that don't match the list in the code. It might also be useful to enforce the sorting present in the code rather than in local storage, as that can result in a messy ordering.

File: code/core/src/manager/settings/shortcuts.tsx (hunk 1 above)
Comment (DKER2) [reply code/core/src/manager/settings/shortcuts.tsx:291]: Hi @Sidnioulz, thanks for feedback, it make sense

**Comment by DKER2** [comment]
> Thanks for your contribution @DKER2!
> 
> I think something is wrong with the applied logic unfortunately. I am consistently missing Toggle Outline on both my existing sets of browsers with expired shortcuts and on a fresh port with the default shortcuts.
> 
> I think it would be wiser to figure out what is defined in the code, and filter out the settings in local storage that don't match the list in the code. It might also be useful to enforce the sorting present in the code rather than in local storage, as that can result in a messy ordering.

Hi @Sidnioulz, based on  this code https://github.com/storybookjs/storybook/blob/4a0464b20fb5496d776b237f2646aeef20a00c6e/code/core/src/outline/OutlineSelector.tsx#L25-L33, it is seem that the Toggle Outline is initilized after the webapp start, so when you directly reload on shortcuts page, and this addonShortcut have not been initiliazed yet. So this action is not initiliazed yet for that shortcut

https://github.com/storybookjs/storybook/blob/4a0464b20fb5496d776b237f2646aeef20a00c6e/code/core/src/manager-api/modules/shortcuts.ts#L412-L414

**Review by Sidnioulz — APPROVED** [review]

**Comment by Sidnioulz** [comment]
> , it is seem that the Toggle Outline is initilized after the webapp start, so when you directly reload on shortcuts page, and this addonShortcut have not been initiliazed yet. So this action is not initiliazed yet for that shortcut

Oh wow, good catch. I definitely didn't expect that.

**Review by ghengeveld — APPROVED** [review]
