### PR TITLE
UI: Fix custom tabs not showing in the manager

### LINKED ISSUE #25322: [Bug]: Main section disappears when navigating to addon tab
### Describe the bug

While upgrading from Storybook 7.0 to 7.6, I noticed that the main section gets hidden when navigating to an addon tab. ([Playroom](https://github.com/rbardini/storybook-addon-playroom) in this case)

Manually removing the `hidden` attribute from the wrapping `<div>` in browser devtools fixes the issue, i.e. the addon matches the route and renders correctly, but Storybook hides it.

Interestingly, it doesn't seem to affect docs pages. Possibly related to #23292.

### To Reproduce

Open the following deploy preview from https://github.com/rbardini/storybook-addon-playroom/pull/54, navigate to stories and click the _Playroom_ tab:

> https://deploy-preview-54--storybook-addon-playroom.netlify.app/

---

I've also reproduced it in [storybookjs/addon-kit](https://github.com/storybookjs/addon-kit) after bumping Storybook dependencies to their latest versions:

```sh
git clone git@github.com:storybookjs/addon-kit.git && cd addon-kit
npx storybook@latest upgrade
npm start
```

Demo

### System

```bash
System:
  OS: macOS 14.2.1
  CPU: (10) arm64 Apple M1 Pro
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 21.5.0 - /opt/homebrew/bin/node
  npm: 10.2.5 - /opt/homebrew/bin/npm <----- active
Browsers:
  Chrome: 120.0.6099.129
  Safari: 17.2.1
npmPackages:
  @storybook/react: ^7.0.0 => 7.6.6 
  @storybook/react-vite: ^7.0.0 => 7.6.6 
  storybook: ^7.0.0 => 7.6.6
```

### Additional context

_No response_

### LINKED ISSUE #25758: [Bug]: Custom tabs not shown in tool bar
### Describe the bug

Any custom tabs added via the register-addon API are not shown in the toolbar as they used to be.

See this screenshot from 7.6:
image

Compare with 8.0:
image

It's also possible that this is not a layout issue but the API to register addon tabs have a change or bug.

### To Reproduce

Here's an 8.0 sandbox demonstrating the issue:
https://stackblitz.com/edit/github-t8esdj?file=.storybook%2Fmanager.jsx

And the exact same code in a 7.6 sandbox showing the tab:
https://stackblitz.com/edit/github-sibamb?file=.storybook%2Fmanager.jsx

### System

```bash
**Version**: `8.0.0-alpha.12`
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ndelangen**
Closes https://github.com/storybookjs/storybook/issues/25322
Closes: https://github.com/storybookjs/storybook/issues/25758

## What I did

- change Tabs type addon to always render via a query parameter `&tab={tabId}`
- Fix memoization of multiple layers

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

- Open storybook
- expect to see no tabs
- Add a custom tab type addon in `.storybook/manager.ts`
- Restart + open storybook
- expect the "canvas"-tab + any tabs manually configured to show up
- Clicking between both tabs show should you the content of canvas / tabs
- The URL should not contain a `tab=...` when the "Canvas" tab is active
- The active tan should be highlighted with a bar
- Tools should only be shown on the "Canvas" tab

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

File: code/ui/manager/src/components/preview/Preview.tsx [hunk 1]
```diff
@@ -107,22 +94,18 @@ const Preview = React.memo<PreviewProps>(function Preview(props) {
...
-              // @ts-expect-error (Converted from ts-ignore)
-              const key = t.id || t.key || i;
-              return (
-                <Fragment key={key}>
-                  <Location>{(lp) => <Render active={match(lp)} />}</Location>
-                </Fragment>
-              );
-            })}
+            {tabContent && <S.IframeWrapper>{tabContent({ active: true })}</S.IframeWrapper>}
+            <S.CanvasWrap style={!!tabId ? { display: 'none' } : {}}>
```
Comment (JReinhold) [inline code/ui/manager/src/components/preview/Preview.tsx:106]: given this is now an actual Emotion component it would be cleaner to pass a `tabId` prop instead of using `style`

File: code/ui/manager/src/components/preview/Toolbar.tsx [hunk 2]
```diff
@@ -119,73 +117,57 @@ export const defaultToolsExtra: Addon_BaseType[] = [
...
-  );
+export const ToolbarComp = React.memo<ToolData>(function ToolbarComp({
+  isShown,
+  tools,
+  toolsExtra,
+  tabs,
+  tabId,
+  api,
+}) {
+  console.log({ tabs, tools, toolsExtra });
```
Comment (JReinhold) [inline code/ui/manager/src/components/preview/Toolbar.tsx:137]:
```suggestion
```

**Review by JReinhold — APPROVED** [review]
Looks good to me, only a few minor comments. Also needs a migration note mentioning the URL for tabs have now changed, and that `tabId` is now passed into `match` and how to use it.

Will you do a Documentation Request too?

**Comment by ndelangen** [comment]
@JReinhold I added the migration notes, and submitted a documentation update request 👍 Thank you for the reminder!

File: MIGRATION.md [hunk 3]
```diff
@@ -386,6 +387,46 @@
 
 ## From version 7.x to 8.0.0
 
+### Tab addons are now routed to a query parameter
```
Comment (shilman) [inline MIGRATION.md:390]: This migration note should describe the URL structure before the change and after. The current content should be moved down to "Addon author changes" since it's really not end user facing.

**Review by shilman — CHANGES_REQUESTED** [review]

File: MIGRATION.md (hunk 3 above)
Comment (shilman) [reply MIGRATION.md:390]: Also we can merge this PR as is and fix it in a follow-on PR, since time is tight

**Review by shilman — APPROVED** [review]
LGTM if you split up that migration note after merge :D
