### PR TITLE
UI: Fix code/copy buttons overlap with content

### LINKED ISSUE #23642: Code and the Copy button under Common Navigation with custom bottom slot and Common Navigation with custom mid slot are getting slightly overlapped in orientation-portrait mode.
### Describe the bug

Code and the Copy button under Common Navigation with custom bottom slot and Common Navigation with custom mid slot are getting slightly overlapped in orientation-portrait mode.

Severity: Usable

### To Reproduce

**Pre- Requisites:** 
Settings-->Display-->Display orientation-->Portrait.

**Repro Steps:** 
Open URL: “[Overview - Docs ⋅ Storybook (windows.net)](https://vivacommonstorybooktest.blob.core.windows.net/$web/index.html?path=/docs/overview--docs)” and sign in with valid credentials. 
In left navigation select “components button for Common Navigation Drop Down select Common Navigation” and invoke it.  
Now Apply Orientation in portrait mode and observe the page.
Verify whether the code and copy button are overlapping slightly or not.

### System

```shell
Environmental details:  
Windows: Win11 Enterprise
OS: Version 22H2 (OS Build 22621.1992) 
Edge Version: Version 114.0.1823.51 (Official build) (64-bit) 
URL: Overview - Docs ⋅ Storybook (windows.net)
```

### Additional context

Expected Result:
Code and the Copy button under Common Navigation with custom bottom slot and Common Navigation with custom mid slot should not get overlapped in orientation-portrait mode.

Attachments are added
Normal mode:
Normal mode (1)

After applying orientation:
Orienation mode

### PR DESCRIPTION
**Pull request by Sidnioulz**
Closes #23642

This is the proper fix for the PR I had to revert earlier today (https://github.com/storybookjs/storybook/pull/33877).

## What I did

Implemented the [following design changes](https://www.figma.com/design/7M5y4W56hqBJBrowKqgZSN/Move-the-%22Code%22-button-2026?node-id=0-1&p=f&t=AujbCtkFOGvZGZcz-0):
* Reworked the styling and position of Preview actions
* Moved the code copy button up into Preview actions
* Fixed up other use cases of SyntaxHighlighter to have a flex-wrap layout where the copy button is guaranteed not to overlap with content

### Testing

A story was added to showcase the wrapping in preview.

#### The changes in this PR are covered in the following automated tests:

- [x] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

1. Open Storybook, go to preview stories
2. Play around with container width

### Documentation
ø

## Checklist for Maintainers

- [x] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [x] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/publish.yml) or locally with `gh workflow run --repo storybookjs/storybook publish.yml --field pr=<PR_NUMBER>`_

## Summary by CodeRabbit

* **New Features**
  * New mobile preview example showcasing long-button wrapping
  * Added opt-in copyable control for source blocks
  * Action bar flexible layout mode for alternative positioning

* **Bug Fixes**
  * Copy-to-clipboard shows "Copied!" confirmation
  * Disabled copy UI when no code is available

* **Improvements**
  * Simplified source rendering and expanded/error handling
  * Improved accessibility attributes and toolbar behavior

### CODE REVIEW

File: code/addons/docs/src/blocks/components/Preview.tsx [hunk 1]
```diff
@@ -172,9 +176,10 @@ const PositionedToolbar = styled(Toolbar)({
   height: 40,
 });
 
-const Relative = styled.div({
+const ActionBarContainer = styled.div({
   overflow: 'hidden',
-  position: 'relative',
+  display: 'flex',
+  flexWrap: 'wrap',
```
Comment (Sidnioulz) [inline code/addons/docs/src/blocks/components/Preview.tsx]: Causes content to no longer be centered. Wrong approach.

**Comment by Sidnioulz** [comment]
@ghengeveld FYI I've sneaked in a commit that fixes CSS decorators used to apply background/grid for primary stories. We had a recent regression there and I needed to use the same story file to test both bug fixes so they got batched in :p

**Review by valentinpalkovic — APPROVED** [review]
