### PR TITLE
Addon Vitest: Support init in Vitest >= 3.2

### LINKED ISSUE #31689: [Bug]: Vitest Addon using Deprecated Workspace File
### Describe the bug

The current automated installation of `@storybook/addon-vitest` results in the creation of a vitest.workspace.js file. These configurations work as expected, however when I run tests, the following warning is provided:

_DEPRECATED  The workspace file is deprecated and will be removed in the next major. Please, use the `projects` field in /Users/jbouder/repos/comet/vite.config.js instead._

My long-term plan is to move from traditional vitest unit tests to using storybook vitest using stories with interactions for coverage. In the short-term however, I will need to be able to run both.

I've been trying to get my existing vitest configs to work with both, by using different vite/vitest configurations, none of them are working 100%.

A couple of questions:
1. Is there a plan to replace the workspace file with something else?
2. Does anyone have a configuration they can share to replace the workspace with a supported configuration, to support both of my test projects?

### Reproduction link

https://github.com/MetroStar/comet/compare/main...storybook-vitest

### Reproduction steps

1. Clone Repo
2. `npm install`
3. `npm run test`

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 15.5
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.14.0 - ~/.nvm/versions/node/v22.14.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 10.9.2 - ~/.nvm/versions/node/v22.14.0/bin/npm <----- active
    pnpm: 9.14.2 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 137.0.7151.69
    Safari: 18.5
  npmPackages:
    @storybook/addon-a11y: ^9.0.5 => 9.0.5 
    @storybook/addon-docs: ^9.0.5 => 9.0.5 
    @storybook/addon-links: ^9.0.5 => 9.0.5 
    @storybook/addon-vitest: ^9.0.5 => 9.0.5 
    @storybook/react-vite: ^9.0.5 => 9.0.5 
    eslint-plugin-storybook: ^9.0.5 => 9.0.5 
    storybook: ^9.0.5 => 9.0.5
```

### Additional context

The following branch has my current configurations: https://github.com/MetroStar/comet/tree/storybook-vitest

### PR DESCRIPTION
**Pull request by valentinpalkovic**
Closes https://github.com/storybookjs/storybook/issues/31689

## What I did

- Use the `projects` field when initializing Addon Vitest for Vitest 3.2 users
- Added `optimizeDeps` to `@storybook/addon-vitest`
- Fixed a bug where some preview annotations weren't added for Next.js
- Refactored the vitest config override for our sandboxes so that we only apply small changes instead of overriding the whole config

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This pull request has been released as version `0.0.0-pr-31715-sha-b9a0ceb9`. Try it out in a new sandbox by running `npx storybook@0.0.0-pr-31715-sha-b9a0ceb9 sandbox` or in an existing project with `npx storybook@0.0.0-pr-31715-sha-b9a0ceb9 upgrade`.
<details>
<summary>More information</summary>

| | |
| --- | --- |
| **Published version** | [`0.0.0-pr-31715-sha-b9a0ceb9`](https://npmjs.com/package/storybook/v/0.0.0-pr-31715-sha-b9a0ceb9) |
| **Triggered by** | @valentinpalkovic |
| **Repository** | [storybookjs/storybook](https://github.com/storybookjs/storybook) |
| **Branch** | [`valentin/support-vitest-3-2`](https://github.com/storybookjs/storybook/tree/valentin/support-vitest-3-2) |
| **Commit** | [`b9a0ceb9`](https://github.com/storybookjs/storybook/commit/b9a0ceb9b39134922aabbbce5bc8df4c0c750a15) |
| **Datetime** | Fri Jun 13 14:07:41 UTC 2025 (`1749823661`) |
| **Workflow run** | [15636541237](https://github.com/storybookjs/storybook/actions/runs/15636541237) |

To request a new release of this pull request, mention the `@storybookjs/core` team.

_core team members can create a new canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=31715`_
</details>

## Greptile Summary

Updates the Vitest addon to support Vitest >= 3.2 by using the `projects` field instead of the deprecated workspace file configuration.
- Added new template `vitest.config.3.2.template.ts` utilizing the `projects` array instead of workspace config
- Updated postinstall script to detect Vitest version and apply appropriate configuration template
- Modified config file updater to handle both legacy workspace and new projects field formats
- Updated dependencies to support Vitest ^3.2.0 while maintaining backward compatibility
- Added comprehensive documentation explaining configuration differences between Vitest versions

### CODE REVIEW

File: code/builders/builder-vite/src/constants.ts [hunk 1]
```diff
@@ -0,0 +1,172 @@
...
+  'telejson',
+  'ts-dedent',
+  'unfetch',
+  'util-deprecate',
+  'vue',
+  'warning',
+];
+
+/**
+ * Returns only those INCLUDE_CANDIDATES that can be resolved by Vite's resolver.
```
Comment (valentinpalkovic) [inline code/builders/builder-vite/src/constants.ts]:
```suggestion
 * Returns only those candidates that can be resolved
```

File: code/addons/vitest/src/postinstall.ts [hunk 2]
```diff
@@ -421,58 +436,42 @@ export default async function postInstall(options: PostinstallOptions) {
...
-          ${picocolors.cyan(`https://vitest.dev/guide/workspace.html`)}
-        `
+        Please refer to the documentation to complete the setup manually:
+        https://storybook.js.org/docs/writing-tests/integrations/vitest-addon#manual-setup
+      `
       );
-
-      const extension = extname(rootConfig).includes('ts') ? '.ts' : '.js';
-      const newWorkspaceFile = resolve(dirname(rootConfig), `vitest.workspace${extension}`);
-      const workspaceTemplate = await loadTemplate('vitest.workspace.template.ts', {
```
Comment (JReinhold) [inline code/addons/vitest/src/postinstall.ts:446]: should the `vitest.workspace.template.ts` file be deleted then, or is it still being used somewhere?

File: docs/writing-tests/integrations/vitest-addon.mdx [hunk 3]
```diff
@@ -97,7 +97,7 @@ When the addon is set up automatically, it will create or adjust your Vitest con
 </details>
 
 <details id="example-vitest-workspace">
-  <summary>Example Vitest workspace file</summary>
+  <summary>Example Vitest workspace file (Vitest < 3.2)</summary>
```
Comment (JReinhold) [inline docs/writing-tests/integrations/vitest-addon.mdx:100]: I'd think it makes more sense to remove this section altogether, now that the example config file already has everything, including pre and post Vitest 3.2?

And also adjust https://github.com/storybookjs/storybook/pull/31715/files#diff-64c8d1c5581a216a909dc8ece0c8611404e6add0ec5d6f9faecdec6ae300dbbeR66 to not mention a separate worksapce file.

cc @kylegach

**Review by JReinhold — APPROVED** [review]

File: docs/writing-tests/integrations/vitest-addon.mdx (hunk 3 above)
Comment (valentinpalkovic) [reply docs/writing-tests/integrations/vitest-addon.mdx:100]: That's what I wanted to do initially, but @yannbf vetoed and wanted to keep the documentation for people who already have a workspace configuration in place.

File: code/addons/vitest/src/postinstall.ts (hunk 2 above)
Comment (valentinpalkovic) [reply code/addons/vitest/src/postinstall.ts:446]: It is still used in the case the user has an existing workspace file.
