### PR TITLE
A11y: Persist tab/highlight across docs navigation

### LINKED ISSUE #32634: [Bug]: SB10 - A11y addon loses state when navigating to docs page
### Describe the bug

Not sure if it's intended but doesn't seem like it,

When defining a specific type of report (passes, violations, etc) and whether highlights are enabled, navigating between stories keeps that preference saved.. until you navigate to a docs page. Then it's lost:
Image

This seems like a flow break on a user perspective

### Reproduction link

MealDrop, any story

### Reproduction steps

1. Access MealDrop or any other Storybook
2. Turn on a11y highlights
3. Visit a docs page
4. Go back to the story
5. See the issue

### PR DESCRIPTION
**Pull request by 404Dealer**
Problem:
The A11y panel UI state (selected tab and highlight toggle) is lost when navigating Stories → Docs → Stories. See #32634.

Solution:
Persist the A11y panel UI state with useAddonState so preferences survive navigation between Stories and Docs.
- Persisted UI state: selected tab and highlighted are stored under a dedicated key across view-mode changes.
- State initialization: on initial mount, the a11ySelection query param overrides any persisted state for deep-linking. The param is cleared after it’s read.
- Minimal impact: only UI state handling changed; no changes to A11y checks or core logic.

Implementation details:
- New key:
  - UI_STATE_ID = `${ADDON_ID}/ui`
- State management:
  ```ts
  const [uiState, setUiState] = useAddonState(UI_STATE_ID, {
    highlighted: false,
    tab: RuleType.VIOLATION,
  });

  const [tab, setTabState] = useState<RuleType>(() => {
    const [type] = a11ySelection?.split('.') ?? [];
    return type && Object.values(RuleType).includes(type as RuleType)
      ? (type as RuleType)
      : uiState.tab;
  });

  const [highlighted, setHighlighted] = useState<boolean>(() =>
    a11ySelection ? true : uiState.highlighted
  );
  // a11ySelection precedence is applied once on mount; effect depends only on a11ySelection
  ```

Files touched:
- code/addons/a11y/src/constants.ts
- code/addons/a11y/src/components/A11yContext.tsx
- code/addons/a11y/src/components/A11yContext.test.tsx

Test coverage:
- Unit tests:
  - Highlight toggle persists over re-mount
  - Tab persists over re-mount
  - a11ySelection overrides persisted state on initial mount

Manual testing:
- yarn start → http://localhost:6006
- Enable highlights, switch tabs, go to Docs, return — state persists

Risks/considerations:
- Unique useAddonState key avoids collisions
- a11ySelection takes precedence once and is cleared
- Only small UI booleans/enums are persisted

Fixes:
- Fixes #32634

## Summary by CodeRabbit

* **New Features**
  * Persisted UI state now stored under a dedicated UI namespace; new Status type added to the public API for addon lifecycle.
* **Refactor**
  * Internal state consolidated into a single composite addon state (ui, results, error, status); tab and highlights driven from ui and exposed via wrapper APIs.
* **Tests**
  * Tests updated to reflect the composite state shape and adjusted persistence/remount behavior.

### CODE REVIEW

**Comment by 404Dealer** [comment]
After merging the latest 'next', I noticed ci/circleci: e2e-ui and normal checks are failing, though my previous commit passed. I'm happy to debug and resolve this if these failures relate to my code—just let me know if you'd like me to proceed, or if the main branch is in flux and I should wait. If needed, I'm also happy to post more details on the errors to help clarify whether it's my changes or the branch state.

**Comment by 404Dealer** [comment]
Hey @yannbf! Friendly ping here. This fixes #32634, the A11y panel now keeps its selected tab and highlight across Stories/Docs.

Added tests and kept it scoped to UI state. First time contributing to open source, so happy to tweak anything and I welcome any feedback. Thanks!

File: code/addons/a11y/src/components/A11yContext.tsx [hunk 1]
```diff
@@ -135,9 +150,19 @@ export const A11yContextProvider: FC<PropsWithChildren> = (props) => {
...
+      return next;
+    });
+  }, [setUiState]);
+  const setTab = useCallback(
+    (type: RuleType) => {
+      setTabState(type);
+      setUiState((prev) => ({ ...prev, tab: type }));
+    },
+    [setUiState]
   );
```
Comment (ndelangen) [inline code/addons/a11y/src/components/A11yContext.tsx]: I think we can simplify this a lot, by not having the local state anymore, but just the upstream uiState.

File: code/addons/a11y/src/components/A11yContext.tsx [hunk 2]
```diff
@@ -107,15 +113,24 @@ export const A11yContextProvider: FC<PropsWithChildren> = (props) => {
   }, [api]);
 
   const [results, setResults] = useAddonState<EnhancedResults | undefined>(ADDON_ID);
-  const [tab, setTab] = useState(() => {
+  const [uiState, setUiState] = useAddonState<{ highlighted: boolean; tab: RuleType }>(
```
Comment (ndelangen) [inline code/addons/a11y/src/components/A11yContext.tsx]: these could be combined, for simplicity.

**Review by ndelangen — APPROVED** [review]

**Comment by 404Dealer** [comment]
Thanks for merging this, @ndelangen! Really appreciate the feedback and tweaks. My first opensource merged PR got me jumping out my seat hahaha :)
