### PR TITLE
CLI: Automigrate improve upgrade storybook related packages

### LINKED ISSUE #26451: [Bug]: `@storybook/addon-styling-webpack` is downgraded when upgrading from beta 8 to stable 8 release
### Describe the bug

I'm currently using Storybook 8.0.0-beta.3. When I tried upgrading to the stable v8 release (using the `npx storybook@latest upgrade` command), I got the following message:

Screenshot 2024-03-12 at 22 18 26

With `@storybook/addon-styling-webpack` being downgraded from 1.0.0 to 0.0.6.

Once the migration was completed, I started Storybook and got the following warning (which was expected):

Screenshot 2024-03-12 at 22 36 41

---

I was able to start Storybook successfully and things seem to work as expected with `@storybook/addon-styling-webpack` 0.0.6, but I'm wondering if the downgrade is expected.

### To Reproduce

_No response_

### System

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ndelangen**
Closes https://github.com/storybookjs/storybook/issues/26451

## What I did

Instead of coercing the version from the `package.json`, actually retreive the version that's installed.

This allows us to properly compare with semver if the package that's latest on npm is newer.

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

File: code/lib/core-common/src/js-package-manager/JsPackageManager.ts [hunk 1]
```diff
@@ -535,6 +535,23 @@ export abstract class JsPackageManager {
...
+  public async getInstalledVersion(packageName: string): Promise<string | null> {
+    const installations = await this.findInstallations([packageName]);
+    if (!installations) {
+      return null;
+    }
+
+    console.log({
+      installations,
+      version: Object.entries(installations.dependencies)[0]?.[1]?.[0].version,
+    });
```
Comment (yannbf) [inline code/lib/core-common/src/js-package-manager/JsPackageManager.ts:550]:
```suggestion
```

**Review by yannbf — APPROVED** [review]
