### PR TITLE
Core: Enhance warning for Testing Library's `screen` usage in docs mode

### LINKED ISSUE #31598: [Bug]: React Native Storybook warning about testing library screen object (interactions is not used)
### Describe the bug

In v9 for a while I've been seeing this warning even though there is no use of testing library or interactions on the react native side since its not implemented I also set interactions as disabled in gobals.

```
WARN  You are using Testing Library's `screen` object. Use `within(canvasElement)` instead.
More info: https://storybook.js.org/docs/essentials/interactions
```

### Reproduction link

https://github.com/dannyhw/expo-storybook-starter

### Reproduction steps

1. yarn 
2. yarn storybook:ios

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 15.5
    CPU: (10) arm64 Apple M1 Max
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.14.0 - /usr/local/bin/node
    Yarn: 4.7.0 - ~/Library/pnpm/yarn <----- active
    npm: 10.9.2 - /usr/local/bin/npm
  npmPackages:
    @storybook/addon-docs: ^9 => 9.0.0 
    @storybook/addon-ondevice-actions: 9.0.0-rc.5 => 9.0.0-rc.5 
    @storybook/addon-ondevice-backgrounds: 9.0.0-rc.5 => 9.0.0-rc.5 
    @storybook/addon-ondevice-controls: 9.0.0-rc.5 => 9.0.0-rc.5 
    @storybook/addon-ondevice-notes: 9.0.0-rc.5 => 9.0.0-rc.5 
    @storybook/react: ^9 => 9.0.0 
    @storybook/react-native: 9.0.0-rc.5 => 9.0.0-rc.5 
    @storybook/react-native-web-vite: ^9 => 9.0.0 
    storybook: ^9 => 9.0.0
```

### Additional context

this has been happening since the addons were merged in the storybook package I guess

### PR DESCRIPTION
**Pull request by yannbf**
Closes #31598

## What I did

This PR scopes the TL `screen` warning so it only really warns when a story which uses the screen utility is rendered in docs mode

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/publish.yml) or locally with `gh workflow run --repo storybookjs/storybook publish.yml --field pr=<PR_NUMBER>`_

## Summary by CodeRabbit

* **Bug Fixes**
  * Refined Testing Library warning behavior so alerts only appear in Storybook docs view, providing contextual guidance there and remaining silent during normal development. The change also improves robustness against cross-origin environments to avoid spurious warnings.

### CODE REVIEW

File: code/core/src/test/testing-library.ts [hunk 1]
```diff
@@ -25,10 +25,24 @@ const testingLibrary = instrument(
...
-          You are using Testing Library's \`screen\` object. Use \`within(canvasElement)\` instead.
-          More info: https://storybook.js.org/docs/writing-tests/interaction-testing?ref=error
-        `);
+    if (typeof window !== 'undefined') {
+      let isInDocsViewMode = false;
+
+      try {
+        isInDocsViewMode =
+          globalThis.location?.href?.includes('viewMode=docs') ||
+          globalThis.parent?.location?.href?.includes('/docs/');
```
Comment (ndelangen) [inline code/core/src/test/testing-library.ts]: AFAIK this pattern only happens in the manager, where this warning/code should never appear.

**Review by ndelangen — APPROVED** [review]
