### PR TITLE
Automigrations: Add migration note about new react-docgen default

### LINKED ISSUE #26555: [Bug]: Expand react-docgen automigration
### Describe the bug

In Storybook v8 we switched to using `react-docgen` by default. There is an existing automigration called `react-docgen` that helps users choose what to do in the case that they have `reactDocgenTypescriptOptions` set in their projects. https://github.com/storybookjs/storybook/blob/next/code/lib/cli/src/automigrate/fixes/react-docgen.ts

However, this is too aggressive. We should notify users that the default has changed and give them a choice for whether or not to upgrade. Without this, users see the different results & don't know why they are happening or what to do about it.

If the user does not have a `reactDocgen` specified, we should give them a choice:

```
Starting in Storybook 8, Storybook uses a library called `react-docgen`  to automatically generate controls for your components. In earlier versions of Storybook, it used `react-docgen-typescript` which is way slower, but also way more accurate if your components use complex TypeScript types.

[Link to more info]

Would you like us to upgrade your project to use to the new default `react-docgen` (recommended)?
```

### To Reproduce

N/A

### System

```bash
N/A
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by valentinpalkovic**
Closes https://github.com/storybookjs/storybook/issues/26555

## What I did

I have enhanced the existing `react-docgen` automigration to give users the possibility to migrate back to the previous `typescript.reactDocgen` default `react-docgen-typescript`.

Bildschirmfoto 2024-03-22 um 15 18 30

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [x] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

1. Migrate a react-based project from Storybook 7 to 8.
2. If you don't have `typescript.reactDocgen` and `typescript.reactDocgenTypescriptOptions` set, the automigration should pop up.
3. For projects which are not react-based, the automigration shouldn't pop up

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

File: code/lib/cli/src/automigrate/fixes/react-docgen.ts [hunk 1]
```diff
@@ -37,15 +44,34 @@ export const reactDocgen: Fix<Options> = {
...
+      
+      For more on this change, check the migration guide: 
+      ${chalk.yellow(
+        'https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#react-docgen-component-analysis-by-default'
+      )}
+      
+      For known "react-docgen" limitations, see: 
+      ${chalk.yellow('https://github.com/storybookjs/storybook/issues/26606')}
+      
+      Would you like to switch back to ${chalk.cyan('react-docgen-typescript')} in your Storybook?
```
Comment (yannbf) [inline code/lib/cli/src/automigrate/fixes/react-docgen.ts:65]: I think it would be nice to say something like "Your project currently uses react-docgen. Would you like to switch back to react-docgen-typescript?

File: code/lib/cli/src/automigrate/fixes/react-docgen.ts [hunk 2]
```diff
@@ -37,15 +44,34 @@ export const reactDocgen: Fix<Options> = {
 
       https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#react-docgen-component-analysis-by-default
     `;
+    } else {
+      return dedent`
+      Since Storybook 8, ${chalk.cyan(
+        'react-docgen'
```
Comment (yannbf) [inline code/lib/cli/src/automigrate/fixes/react-docgen.ts:50]: Can you maybe make both messages (the if and else statements) consistent?

**Review by yannbf — APPROVED** [review]
