### PR TITLE
Angular: Allow usage of all component valid selectors

### LINKED ISSUE #14079: 6.2.0-beta.4 - Issue when using angular attribute selectors or multiple selectors
### Bug

When using attribute selectors or multiple selectors, running the project either does not show the button on the canvas or throws an error

### Steps to reproduce

1. Init storybook with 6.2.0 beta 4 in a clean angular cli project (Angular v.11.0.9) - `npx sb@next init`
2. Use these selectors below in the button.component.ts file
3. `npm run storybook`

This selector will show no button
`selector: 'storybook-button[foo]',`

This selector will cause an error
`selector: 'storybook-button, storybook-button[foo]',`

These work fine in 6.1 which adds the attribute to the button tag automatically

### PR DESCRIPTION
**Pull request by dexster**
Issue: #14079

## What I did

Added checks for all valid angular directive/component selectors to allow templates to be generated correctly.  

## How to test

- Is this testable with Jest or Chromatic screenshots? Yes
Tests added

- Does this need a new example in the kitchen sink apps?
Possibly. Examples added but they don't show much. Could be removed?

- Does this need an update to the documentation?
No

### CODE REVIEW

**Comment by dexster** [comment]
Could I have some feedback on the unsuccessful checks please so I can ensure future PR's are successful. Thanks

**Comment by shilman** [comment]
@dexster don't worry about the unsuccessful checks 👍

File: app/angular/src/client/preview/angular-beta/ComputesTemplateFromComponent.ts [hunk 1]
```diff
@@ -127,5 +128,55 @@ export const computesTemplateSourceFromComponent = (
...
 
-  return `<${ngComponentMetadata.selector}${templateInputs}${templateOutputs}></${ngComponentMetadata.selector}>`;
+  const template = buildTemplate(ngComponentMetadata.selector);
+  return `<${template.openTag}${templateInputs}${templateOutputs}></${template.closeTag}>`;
+};
+
+const buildTemplate = (
+  selector: string
+): {
+  openTag?: string;
```
Comment (ThibaudAV) [inline app/angular/src/client/preview/angular-beta/ComputesTemplateFromComponent.ts:138]: Do you think it would be possible to have `openTag` and `closeTag` not optional

File: app/angular/src/client/preview/angular-beta/ComputesTemplateFromComponent.ts [hunk 2]
```diff
@@ -127,5 +128,55 @@ export const computesTemplateSourceFromComponent = (
...
+  return templates.reduce((acc, template) => {
+    const matched = selector.match(template.re);
+    if (matched) {
+      return {
+        openTag: template.openTag(matched).trim(),
+        closeTag: template.closeTag(matched),
+      };
+    }
+    return acc;
+  }, {});
```
Comment (ThibaudAV) [inline app/angular/src/client/preview/angular-beta/ComputesTemplateFromComponent.ts:181]: what do you think about starting with a default value? 
like `storybook-default-selector` ? (or something like that)
In case of an error it could be a workaround? 

or we could display a clearer error if the open/close tag is not found ?

File: app/angular/src/client/preview/angular-beta/ComputesTemplateFromComponent.ts [hunk 3]
```diff
@@ -127,5 +128,55 @@ export const computesTemplateSourceFromComponent = (
...
+const buildTemplate = (
+  selector: string
+): {
+  openTag?: string;
+  closeTag?: string;
+} => {
+  const templates = [
+    {
+      // Match element selectors with optional chained attributes or classes
+      re: /^([\w\d-_]+)(?:(?:\[([\w\d-_]+)(?:=(.+))?\])|\.([\w\d-_]+))?/,
```
Comment (ThibaudAV) [inline app/angular/src/client/preview/angular-beta/ComputesTemplateFromComponent.ts:144]: a long time ago when I was doing Jquery I used this solution (regex) : https://codegolf.stackexchange.com/a/123281
I don't know if you made them yourself but maybe this could improve or simplify 🤷‍♂️

File: examples/angular-cli/src/stories/basics/component-with-complex-selectors/attribute-selector.component.ts [hunk 4]
```diff
@@ -0,0 +1,7 @@
+import { Component } from '@angular/core';
+
+@Component({
+  selector: 'storybook-attribute-selector[foo]',
+  template: '<p>Attribute selector</p>',
```
Comment (ThibaudAV) [inline examples/angular-cli/src/stories/basics/component-with-complex-selectors/attribute-selector.component.ts:5]: I find these examples very interesting. 

We could display the html output expected in template 🤔 like :
```ts
template: `
<h3>Attribute selector</h3>
Selector: "storybook-attribute-selector[foo]" <br>
Generated tempalte: "<storybook-attribute-selector foo></storybook-attribute-selector>"
`,
```

but maybe it's too much 🤷‍♂️

**Review by ThibaudAV — COMMENTED** [review]
Very nice work :) with tests and examples ❤️ I added some remarks but nothing blocking. just questions and suggestions

**Comment by manuelmeister** [comment]
In angular it is valid to have multiple selectors for the same directive/component. How do we handle that? In that case we probably want to be able to choose which selector we want to use.

**Comment by dexster** [comment]
For the purposes of Storybook auto-generated templates I simply use the first selector. If someone wanted to use one of the  other selectors from their component I would expect them to use the template property and specify the required selector.

**Comment by dexster** [comment]
Changes made as per feedback

File: app/angular/src/client/preview/angular-beta/ComputesTemplateFromComponent.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (dexster) [reply app/angular/src/client/preview/angular-beta/ComputesTemplateFromComponent.ts:138]: N/A with new commit using the regex you mentioned

File: app/angular/src/client/preview/angular-beta/ComputesTemplateFromComponent.ts (hunk 2 above)
Comment (dexster) [reply app/angular/src/client/preview/angular-beta/ComputesTemplateFromComponent.ts:181]: N/A with new commit using the regex you mentioned which should always return a selector.

File: app/angular/src/client/preview/angular-beta/ComputesTemplateFromComponent.ts (hunk 3 above)
Comment (dexster) [reply app/angular/src/client/preview/angular-beta/ComputesTemplateFromComponent.ts:144]: Done with modifications

File: examples/angular-cli/src/stories/basics/component-with-complex-selectors/attribute-selector.component.ts (hunk 4 above)
Comment (dexster) [reply examples/angular-cli/src/stories/basics/component-with-complex-selectors/attribute-selector.component.ts]: Done

**Comment by shilman** [comment]
@dexster @ThibaudAV is this good to merge? if we're going to include it in 6.2 we should probably merge it today. (doesn't mean we can't get it in later, or as a patch, but ideally we'd wrap everything ASAP). thanks!

**Comment by dexster** [comment]
I've made all the updates as per @ThibaudAV recommendations so happy from my side.

**Comment by shilman** [comment]
Thanks @dexster 🙏  merging and will release later today!

**Comment by ThibaudAV** [comment]
Coool thanks @dexster 🙂
