### PR TITLE
Save from Controls: Replace rendererPackage with frameworkPackage

### LINKED ISSUE #31112: [Bug]: Storybook 9 - Create new story from component writes file with renderer imports, not framework imports
### Describe the bug

**Repro:** MealDrop
**Branch:** `storybook/9.0.0`

**Steps:** 
- Delete the `Badge.stories.tsx` file
- Run Storybook
- Click on the `+` to create story from component
- Notice the file containing wrong imports:
Image

### Reproduction link

-

### Reproduction steps

_No response_

### System

```bash
-
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by valentinpalkovic**
Closes https://github.com/storybookjs/storybook/issues/31112

## What I did

Adjusted the creation of a new story by changing the import of TypeScript types to not use the renderer package, but rather the framework package instead.

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

## Greptile Summary

This PR replaces `rendererPackage` with `frameworkPackage` in the story file generation utilities to standardize terminology across the codebase.

- Changed parameter name from `rendererPackage` to `frameworkPackage` in `code/core/src/core-server/utils/new-story-templates/typescript.ts` interface and function
- Updated import logic in `code/core/src/core-server/utils/get-new-story-file.ts` to use `extractProperFrameworkName` instead of renderer extraction
- Updated tests in `code/core/src/core-server/utils/get-new-story-file.test.ts` to reflect framework package imports
- Modified test snapshots in `code/core/src/core-server/utils/new-story-templates/typescript.test.ts` to use framework references

### CODE REVIEW

File: code/core/src/core-server/utils/new-story-templates/typescript.ts [hunk 1]
```diff
@@ -22,7 +22,7 @@ export async function getTypeScriptTemplateForNewStoryFile(data: TypeScriptTempl
     : `import { ${importName} } from './${data.basenameWithoutExtension}'`;
 
   return dedent`
-  import type { Meta, StoryObj } from '${data.rendererPackage}';
+  import type { Meta, StoryObj } from '${data.frameworkPackage}';
```
Comment (yannbf) [inline code/core/src/core-server/utils/new-story-templates/typescript.ts:25]: Will this work with community frameworks? 🤔

Comment (valentinpalkovic) [reply code/core/src/core-server/utils/new-story-templates/typescript.ts:25]: Which react-based community frameworks do you have in mind? Do any exist?

Comment (valentinpalkovic) [reply code/core/src/core-server/utils/new-story-templates/typescript.ts:25]: I think in Storybook 9, it is a requirement that community frameworks, which use one of our renderers as basis, have to re-export them. That's what we are doing, and that's what addon/framework authors should do as well.

Comment (yannbf) [reply code/core/src/core-server/utils/new-story-templates/typescript.ts:25]: I'm thinking of rspack, but I guess it will work as well
