### PR TITLE
Backgrounds/Viewport: Fix resetting

### LINKED ISSUE #31381: [Bug]: Backgrounds doesn't reset to initialGlobals
### Describe the bug

Once set, when resetting the backgrounds by clicking on "Reset background" in the toolbar, the backgrounds resets, but the url is malformed.

### PR DESCRIPTION
**Pull request by valentinpalkovic**
Closes https://github.com/storybookjs/storybook/issues/31381

## What I did

Fixing an issue to properly reset values for backgrounds and viewports in the toolbar.

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

## Greptile Summary

This PR implements fixes for resetting functionality in Storybook's backgrounds and viewport toolbar controls. Here's a concise summary of the key changes:

- Modified `GlobalsStore.update()` to properly reset values to their initial state when undefined is passed
- Simplified reset handling in `backgrounds/Tool.tsx` and `viewport/Tool.tsx` by allowing direct undefined values
- Updated type signatures in both tools to explicitly accept undefined as valid input for the update functions
- Streamlined reset logic by removing unnecessary object wrappers when clearing values

The changes improve the reliability of the reset functionality while maintaining type safety. The implementation looks solid but could benefit from additional test coverage to verify the reset behavior works as expected across different scenarios.

### CODE REVIEW

File: code/core/src/preview-api/modules/store/GlobalsStore.ts [hunk 1]
```diff
@@ -62,5 +62,11 @@ export class GlobalsStore {
 
   update(newGlobals: Globals) {
     this.globals = { ...this.globals, ...this.filterAllowedGlobals(newGlobals) };
+
+    for (const key in newGlobals) {
+      if (newGlobals[key] === undefined) {
+        this.globals[key] = this.initialGlobals[key];
```
Comment (valentinpalkovic) [inline code/core/src/preview-api/modules/store/GlobalsStore.ts:68]: Deleting wasn't doing the trick. We have to reset it to the initial "initialGlobals" value instead. That's what the comparing logic later requires.
