### PR TITLE
CLI: Fix copyTemplate failures on `init`

### LINKED ISSUE #22348: storybook init: Couldn't find template dir
Error locations:

- [angular generator](https://github.com/storybookjs/storybook/blob/next/code/lib/cli/src/generators/ANGULAR/index.ts#L83)
- [server generator](https://github.com/storybookjs/storybook/blob/next/code/lib/cli/src/generators/SERVER/index.ts#L13)
- [aurelia generator](https://github.com/storybookjs/storybook/blob/next/code/lib/cli/src/generators/AURELIA/index.ts#L29)

Suggested work:

This seems like a bug that should be investigated and fixed. In the scenario where the issue makes sense, the error message should be improved with a suggestion where the user can act upon.

### PR DESCRIPTION
**Pull request by ndelangen**
Closes #22348 

## What I did

Add guards against projectType being an unknown value
Add guards against templateDir being a location that doesn't exist

## How to test

I'm not exactly sure how to reproduce the error, but 1 way that would work for sure would be to set a `projectType` to a odd value in an angular project. I don't think there are any other proper values other then `application` and `library` but if there are, then that would have caused issues in the past. After this PR that should default back to `application`. I assume this is the correct default.

If the templateDir cannot be found at all, we'll just skip it, this MIGHT cause those storybook to fail to start or build, but that's hard to tell without a full reproduction I can follow.
...either way that would become a follow-up issue then.

### CODE REVIEW

File: code/lib/cli/src/generators/SERVER/index.ts [hunk 1]
```diff
@@ -10,7 +10,9 @@ const generator: Generator = async (packageManager, npmOptions, options) => {
   });
 
   const templateDir = join(getCliDir(), 'templates', 'server');
```
Comment (shilman) [inline code/lib/cli/src/generators/SERVER/index.ts:12]: We can just get rid of this block of code entirely. I just tested it out on a sample project and will be adding a telescoping PR to do it.

**Review by shilman — APPROVED** [review]
LGTM. I'll let @yannbf follow up as needed but merging now since I want to get the server changes released.
