### PR TITLE
React-Docgen: Add tsconfig fallback chain and warning for monorepos

### LINKED ISSUE #24585: [Bug]: Typescript auto-generated controls behaves weird
### Describe the bug

Auto generating controls only works if there is a tsconfig.json in the root directory.
I started fresh with storybook 7.5 and have a very small monorepo with only one component.

In my root directory I have a tsconfig.base.json and in my components tsconfig.json I extend that via 
```json
{
  "extends": ["../../../tsconfig.base.json"]
}
```

Storybook doesn't seem to pick it up tough and it's not even logging or erroring in any way that something is missing.
The controls just stay empty.

My main.ts:
```ts
import { StorybookConfig } from "@storybook/react-vite";

const config: StorybookConfig = {
  stories: ["../src/**/*.mdx", "../src/**/*.stories.@(js|jsx|mjs|ts|tsx)"],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-onboarding",
    "@storybook/addon-interactions",
  ],
  framework: {
    name: "@storybook/react-vite",
    options: {},
  },
  docs: {
    autodocs: "tag",
  },
  typescript: {
    reactDocgen: "react-docgen-typescript",
    reactDocgenTypescriptOptions: {},
  },
};

export default config;
```

Initially I had reactDocgenTypescriptOptions filled with the example from https://storybook.js.org/docs/react/configure/typescript but that didn't do anything. The propFilter callback wasn't even called.

By mere chance I realized having a tsconfig.json in my root directory triggered a reload and my props were shown in the Controls panel.

I think Storybook should warn the user that no tsconfig file was found/used when the typescript option is added in the config like above. 

**The typescript config example also includes "compilerOptions" so at first I assumed a tsconfig.json file is not needed.** But those didn't work either and had no effect.

### To Reproduce

https://stackblitz.com/edit/github-b3yb1v?file=.storybook%2Fmain.ts

### System

```bash
Storybook Environment Info:

  System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - ~/.local/share/pnpm/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
    pnpm: 8.7.6 - ~/.local/share/pnpm/pnpm <----- active
  npmPackages:
    @storybook/addon-essentials: ^7.5.1 => 7.5.1
    @storybook/addon-interactions: ^7.5.1 => 7.5.1
    @storybook/addon-links: ^7.5.1 => 7.5.1
    @storybook/addon-onboarding: ^1.0.8 => 1.0.8
    @storybook/blocks: ^7.5.1 => 7.5.1
    @storybook/react: ^7.5.1 => 7.5.1
    @storybook/react-vite: ^7.5.1 => 7.5.1
    @storybook/testing-library: ^0.2.2 => 0.2.2
    eslint-plugin-storybook: ^0.6.15 => 0.6.15
    storybook: ^7.5.1 => 7.5.1
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by viditkbhatnagar**
## What this PR does

Fixes #24585

In monorepo setups (e.g., Nx, Turborepo), the root directory often has 
`tsconfig.base.json` instead of `tsconfig.json`. Storybook's tsconfig 
resolution silently failed, causing react-docgen-typescript to produce 
no controls with zero warnings.

## Changes

- **`utils.ts`** — `findTsconfigPath()` now tries `tsconfig.json` → 
  `tsconfig.base.json` → `tsconfig.app.json` in order, with a warning 
  log when using a fallback
- **`reactDocgenTypescript.ts`** — Warns when no tsconfig variant is 
  found, telling the user TypeScript controls won't work
- **`react-docgen.ts` / `react-docgen-loader.ts`** — Consistent 
  fallback chain for path alias resolution in Vite and Webpack
- **`utils.test.ts`** — 5 new tests covering all scenarios

## How to test

1. Create a monorepo with `tsconfig.base.json` in root (no `tsconfig.json`)
2. Set up a Storybook with `react-docgen-typescript`
3. Verify controls are now generated correctly
4. Verify a warning is logged when falling back to `tsconfig.base.json`
5. Remove all tsconfig variants and verify a clear warning is shown

## Checklist

- [x] Bug fix
- [x] Tests added
- [x] No breaking changes

## Summary by CodeRabbit

* **Bug Fixes & Improvements**
  * Broadened TypeScript config discovery to try common alternative filenames for better multi-package/monorepo support.
  * Added a runtime warning when no TypeScript config is found (affects prop documentation behavior).

* **Tests**
  * Added tests for config discovery priority and warning behavior.

### CODE REVIEW

File: code/renderers/react/src/componentManifest/utils.ts [hunk 1]
```diff
@@ -169,9 +169,31 @@ export const cachedResolveImport: typeof resolveImport = cached(resolveImport, {
...
+
+    for (const candidate of TSCONFIG_CANDIDATES) {
+      const found = find.up(candidate, { cwd, last: projectRoot });
+      if (found) {
+        if (candidate !== 'tsconfig.json') {
+          logger.warn(
+            `No tsconfig.json found. Using "${candidate}" instead. ` +
+              `To silence this warning, create a tsconfig.json that extends "${candidate}".`
+          );
+        }
```
Comment (valentinpalkovic) [inline code/renderers/react/src/componentManifest/utils.ts]: I don't think we need a warning. We can safely drop it.

**Review by valentinpalkovic — APPROVED** [review]
