### PR TITLE
fix: conflicts static dirs.

### LINKED ISSUE #21063: [Bug]: Cannot use `-s` flag to set static dir
### Describe the bug

If you have a (upgraded) project that sets the static dir via `-s` rather than the `main.js:staticDir` flag, SB errors on startup with:

```
info => Starting manager..
Error: Conflict when trying to read staticDirs:
* Storybook's configuration option: 'staticDirs'
* Storybook's CLI flag: '--staticDir' or '-s'

Choose one of them, but not both.
    at useStatics (/Users/tom/GitHub/tmeasday/repro-static-dir/node_modules/@storybook/core-server/dist/index.js:1:3510)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### To Reproduce

```shell
# This is a simple `npx sb@repro` with the `-s` option set (and `staticDirs` removed from `main.js).
git clone https://github.com/tmeasday/repro-static-dir
cd repro-static-dir
yarn
yarn storybook
```

### System

_No response_

### Additional context

My guess is an addon is setting the `staticDirs` preset field. We should make sure the above error/warning only happens for `staticDirs` set directly.

### PR DESCRIPTION
**Pull request by zhyd1997**
Fixes #21063 

## How to test

it should work with sandboxes.
enable `-p` option or add `staticDirs` or nothing.

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

File: code/lib/core-server/src/build-static.ts [hunk 1]
```diff
@@ -114,7 +117,7 @@ export async function buildStaticStandalone(options: BuildStaticStandaloneOption
     features,
   };
 
-  if (staticDirs && options.staticDir) {
+  if (staticDirs && options.staticDir && !isEqual(options.staticDir, defaultStaticDirs)) {
```
Comment (zhyd1997) [inline code/lib/core-server/src/build-static.ts:120]: core change

**Review by ndelangen — APPROVED** [review]
makes sense
