### PR TITLE
fix: Storybook 7 viewport menu not working

### LINKED ISSUE #22718: [Bug]: Storybook 7 viewport menu not working
### Describe the bug

The viewport button in the top buttons bar does not update the screen size anymore.

- Storybook 7
- Vite 
- TS 
  

### To Reproduce

https://stackblitz.com/github/storybookjs/sandboxes/tree/next/vue3-vite/default-ts/after-storybook?file=README.md&preset=node

### System

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sookmax**
Closes #22718

## What I did

Modified `getStyles` function in `code/addons/viewport/src/Tool.tsx` so that it works correctly even when `prevStyles` is `undefined`.

I did a little bit of digging, and it seems like the bug was introduced by https://github.com/storybookjs/storybook/commit/fe02579b4ca5f162044ab5ca28293228458fc28f. The main problem introduced by this commit is that `getStyles` now always returns `undefined` if `prevStyles` is `undefined` which is initialized as such and never gets updated, so subsequent calls to `getStyles` in `ViewportTool` component's body always yield `undefined`, resulting in no style being applied to the iframe.

## How to test

1. Run a sandbox for template, e.g. `yarn task --task sandbox --start-from auto --template react-vite/default-ts`
2. Open Storybook in your browser
3. Access any story, click the viewport resize button in the preview toolbar, and choose any viewport item in the popover menu, and check if the iframe is resized accordingly.

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

File: code/addons/viewport/src/Tool.tsx [hunk 1]
```diff
@@ -106,11 +106,25 @@ const getStyles = (
...
+
+  let result: ViewportStyles | undefined;
+
+  if (typeof styles === 'function') {
+    if (prevStyles) {
+      result = styles(prevStyles);
+    }
+  } else {
+    result = styles;
+  }
```
Comment (kasperpeulen) [inline code/addons/viewport/src/Tool.tsx:121]: But what now if styles is a function and prevStyles is not yet defined. Then `result` will also be always undefined right? I think that maybe the right fix would be to rollback what we had before, and change the type to be:

```ts
export type Styles = ViewportStyles | ((previous: ViewportStyles | null) => ViewportStyles) | null;
```
So that the user has to explicitly handle previous being still `null`.

**Review by kasperpeulen — CHANGES_REQUESTED** [review]

File: code/addons/viewport/src/Tool.tsx (hunk 1 above)
Comment (sookmax) [reply code/addons/viewport/src/Tool.tsx:121]: > to rollback what we had before

You mean reverting back to before fe02579, right?

And yes you're right the nested if `if (prevStyles)` was only there because of the type `Styles`.

And what about the type for `prevStyles`? The actual value for `prevStyles` argument comes from `const ref = useRef<ViewportStyles>();` which allows it to be `undefined`, so you either have to give it the initial value or accept `undefined` for `prevStyles` arg of `getStyles`.

Comment (kasperpeulen) [reply code/addons/viewport/src/Tool.tsx:121]: > You mean reverting back to before https://github.com/storybookjs/storybook/commit/fe02579b4ca5f162044ab5ca28293228458fc28f, right?

Yes!

Oh wait, widening `previous` in the type of `Styles` to `undefined` instead of `null` sounds also good to me indeed!

**Review by kasperpeulen — APPROVED** [review]
LGTM!
