### PR TITLE
Addon Vitest: Use its own cache directory

### LINKED ISSUE #31431: [Bug]: Storybook 9 - Tests hang or fail when running Vitest and multiple browser mode workspaces + Storybook
### Describe the bug

Repro steps:
- Access the [reproduction link](https://github.com/yannbf/vitest-browser-repro)
- Run `npm run test`
- Notice that Storybook tests will run and then the other Vitest projects will either hang or fail:

Image

- Disable the storybook 
- Run `npm run tests`
- Notice that all tests ran perfectly

Image

### PR DESCRIPTION
**Pull request by yannbf**
Closes https://github.com/storybookjs/storybook/issues/31431

## What I did

When using Storybook with other browser mode projects, the cache was getting corrupted as each Vitest instance needs its own cache, and dependency optimization from Storybook was affecting other project's cache. This PR makes it so that each Storybook vitest workspace has its own unique cache directory.

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

## Greptile Summary

Modified the Vitest plugin to ensure each Storybook workspace uses a unique cache directory based on the config directory path hash, preventing cache corruption when running multiple Vitest instances simultaneously.

- Added cache directory configuration in `code/addons/vitest/src/vitest-plugin/index.ts` using config path hash
- Fixed issue where multiple Vitest instances were sharing and corrupting each other's cache
- Resolved test hanging/failing issues when running Vitest with multiple browser mode workspaces

### CODE REVIEW

**Review by ndelangen — APPROVED** [review]

File: code/addons/vitest/src/vitest-plugin/index.ts [hunk 1]
```diff
@@ -17,14 +18,14 @@ import type {
 } from 'storybook/internal/core-server';
 import { readConfig, vitestTransform } from 'storybook/internal/csf-tools';
 import { MainFileMissingError } from 'storybook/internal/server-errors';
+import { oneWayHash } from 'storybook/internal/telemetry';
```
Comment (ndelangen) [inline code/addons/vitest/src/vitest-plugin/index.ts:21]: I'm wondering if importing the relative src file would be better?

Comment (yannbf) [reply code/addons/vitest/src/vitest-plugin/index.ts:21]: Can you elaborate?

Comment (ndelangen) [reply code/addons/vitest/src/vitest-plugin/index.ts:21]: Never mind, it's likely nothing.
