### PR TITLE
Addon-vitest: Fix coverage when restarting Vitest due to config change

### LINKED ISSUE #30900: [Bug]: Storybook 9 - When running tests after updating vite config, coverage is not calculated anymore
### Describe the bug

**Repo:** MealDrop
**Branch:** `sbtest-qa` commit `ab0db5aa80c`

**Steps:**
- Turn code coverage on
- Run all tests
- Notice that code coverage is available

Image

- Modify the vite.config.ts file (uncomment the code coverage lines 9-13)
- Notice the `Restarting Vitest due to config change` message in the CLI
- Rerun all tests
- Notice that code coverage, while still enabled, does not provide results anymore

Image

It seems that once Vitest is restarted, it does not take into account the settings that users have chosen. Perhaps the bug is that once restarting Vitest, it doesn't keep the previously selected config.

### Reproduction link

-

### Reproduction steps

_No response_

### System

```bash
-
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JReinhold**
Closes https://github.com/storybookjs/storybook/issues/30900

## What I did

The issue was technically already fixed in #30875, where coverage mode became more resilient and always restarted Vitest when a run was triggered with coverage mode that didn't match the currently running mode: 

https://github.com/storybookjs/storybook/blob/71a080ba529e0bb4277d5ae3d68187d28d3a928b/code/addons/vitest/src/node/vitest-manager.ts#L201-L213

However restarting Vitest due to config change didn't correctly set coverage mode, so it could result in:

1. Enable coverage
2. Run all tests
3. (This restarts Vitest with coverage enabled)
4. Change Vitest config
5. (This restarts Vitest with coverage _disabled_)
6. Run all tests
7. (This restarts Vitest _again_ to enable coverage)

This PR eliminates step 7, because step 5 will have the correct coverage mode.

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

## Greptile Summary

Updated the VitestManager in `/code/addons/vitest/src/node/vitest-manager.ts` to correctly apply the coverage mode when restarting Vitest after configuration changes.

- Modified `startVitest` to require an explicit `coverage` boolean.
- Removed redundant waiting on the prior restart promise in `restartVitest`.
- Updated the config change listener to fetch the current coverage state from the test manager store.
- Ensured the correct coverage mode is maintained post-config change, preventing unnecessary restarts.

### CODE REVIEW

File: code/addons/vitest/src/node/vitest-manager.ts [hunk 1]
```diff
@@ -206,7 +206,6 @@ export class VitestManager {
     if (!this.vitest) {
       await this.startVitest({ coverage: coverageShouldBeEnabled });
     } else if (currentCoverage !== coverageShouldBeEnabled) {
-      await this.vitestRestartPromise;
```
Comment (JReinhold) [inline code/addons/vitest/src/node/vitest-manager.ts:209]: this was already called within `this.restartVitest`

**Review by yannbf — APPROVED** [review]
