### PR TITLE
CLI: Fix "Invalid version null" issues by improved version detection

### LINKED ISSUE #22345: storybook init: Invalid Version: `null`
Error locations: 

- [automigration duplicated dependencies summary](https://github.com/storybookjs/storybook/blob/next/code/lib/cli/src/automigrate/helpers/hasMultipleVersions.ts#L5)
- [init → detect language](https://github.com/storybookjs/storybook/blob/next/code/lib/cli/src/detect.ts#L174)

Suggested work: 

The issue occurs as a result of calling `semver.coerce(version)` to get the version of a package which looks like one of the following scenarios:

```json
{
  "typescript": "*", // wildcard, common in peerDependency field
  "typescript": "workspace:*", // common in monorepos
  "typescript": "latest", // or any other npm tag
}
```

This issue relates to the fact that we get package versions by reading a package.json file, which might not be a robust solution. Possible solutions to work on would be:

- Change the way we read package versions by parsing the lock file instead. We could use tools such as [nodejs-lockfile-parser](https://github.com/snyk/nodejs-lockfile-parser) for instance.
- Change the way we read package versions by using package managers commands e.g. `yarn why <dep>`.
- Create a wrapper of `semver` that deals with the scenario of “invalid” versions and falls back to another mechanism to retrieve the package version, or at least provide a better error message.
- Add error handling around the places where we calculate versions, and gracefully handle the errors if needed (e.g. skip duplicated dependency check rather than crash)

### PR DESCRIPTION
**Pull request by valentinpalkovic**
Closes https://github.com/storybookjs/storybook/issues/22345

## What I did

- Removed bower support
- Implemented methods to read the version of an installed package
- Fixed some places, which weren't pnpm sensitive
- Removed Angular 12 automigrations
- Fixed `upgrade` and `automigrate` commands in nx projects
- Fixed setting eslint-plugin in eslintPlugin automigrate
- Fixed Storybook `upgrade/init` commands in `yarn workspace` environments
- Fixed a bug where `nextjs` wasn't working properly in `pnp` environments
- Fixed detection of pnp in workspaces when Storybook init was called in a subdirectory
- Fixed `@storybook/addon-docs` not automatically installed when compodoc was in use

## Checklist

- [x] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [x] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

File: code/lib/cli/src/detect.ts [hunk 1]
```diff
@@ -158,71 +158,61 @@ export function detectPnp() {
...
   let language = SupportedLanguage.JAVASCRIPT;
 
-  // TODO: we may need to also detect whether a jsconfig.json file is present
-  // in a monorepo root directory
-  if (!packageJson || fs.existsSync('jsconfig.json')) {
+  if (fs.existsSync('jsconfig.json')) {
     return language;
   }
 
+  const typescriptVersion = await packageManager.getPackageVersion('typescript');
```
Comment (valentinpalkovic) [inline code/lib/cli/src/detect.ts:168]: I am not sure about this change. If the mono repository has Typescript installed, it does not mean, that the user would also like to use Typescript in Storybook

File: code/lib/cli/src/automigrate/helpers/mainConfigFile.ts [hunk 2]
```diff
@@ -9,6 +15,60 @@ import type { JsPackageManager } from '../../js-package-manager';
...
+ * Given a Storybook configuration object, retrieves the package name or file path of the framework.
+ * @param mainConfig - The main Storybook configuration object to lookup.
+ * @returns - The package name of the framework. If not found, returns null.
+ */
+export const getFrameworkPackageName = (mainConfig?: StorybookConfig) => {
+  const packageNameOrPath =
+    typeof mainConfig?.framework === 'string' ? mainConfig.framework : mainConfig?.framework?.name;
+
+  return packageNameOrPath
+    ? Object.keys(frameworkPackages).find((pkg) => packageNameOrPath.endsWith(pkg)) ??
```
Comment (valentinpalkovic) [inline code/lib/cli/src/automigrate/helpers/mainConfigFile.ts:28]: Fix this logic for windows (\)

File: code/lib/cli/src/automigrate/helpers/mainConfigFile.ts [hunk 3]
```diff
@@ -9,6 +15,60 @@ import type { JsPackageManager } from '../../js-package-manager';
...
+ * @returns - The package name of the builder. If not found, returns null.
+ */
+export const getBuilderPackageName = (mainConfig?: StorybookConfig) => {
+  const packageNameOrPath =
+    typeof mainConfig?.core?.builder === 'string'
+      ? mainConfig.core.builder
+      : mainConfig?.core?.builder?.name;
+
+  return packageNameOrPath
+    ? builderPackages.find((pkg) => packageNameOrPath.endsWith(pkg)) ?? packageNameOrPath
```
Comment (valentinpalkovic) [inline code/lib/cli/src/automigrate/helpers/mainConfigFile.ts:45]: Fix this logic for windows (\)

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
Can this be merged @valentinpalkovic

**Comment by yannbf** [comment]
> Can this be merged @valentinpalkovic ?

No, I'm working on it!

**Review by yannbf — CHANGES_REQUESTED** [review]
Let me start by saying that this is super awesome ❤️ 

Unfortunately it seems like the pnp solutions do not work?

### Yarn2
```
• Detecting project typeError while fetching package version in Yarn PnP mode: Error: Your application tried to access nx, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: nx
Required by: /Users/yannbraga/experiments/delete/react-ts

    at makeError (/Users/yannbraga/experiments/delete/react-ts/.pnp.cjs:21064:34)
    at resolveToUnqualified (/Users/yannbraga/experiments/delete/react-ts/.pnp.cjs:22781:21)
    at Object.resolveToUnqualified (/Users/yannbraga/experiments/delete/react-ts/.pnp.cjs:22973:26)
    at Yarn2Proxy.getPackageVersion (/Users/yannbraga/open-source/storybook/code/lib/cli/dist/generate.js:1751:43)
    at isNxProject (/Users/yannbraga/open-source/storybook/code/lib/cli/dist/generate.js:535:42)
```

And similar errors happen when trying to resolve `prettier`, `@babel/plugin-transform-typescript`, `eslint-plugin-storybook` in the same execution

### PNPM

```
Detecting project typeError while fetching package version in Yarn PnP mode: Error: Your application tried to access nx, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: nx (via "nx")
Required by: /Users/yannbraga/experiments/delete/react-ts

    at internalTools_makeError (/Users/yannbraga/experiments/delete/react-ts/.pnp.cjs:13925:34)
    at resolveToUnqualified (/Users/yannbraga/experiments/delete/react-ts/.pnp.cjs:14884:23)
    at Object.resolveToUnqualified (/Users/yannbraga/experiments/delete/react-ts/.pnp.cjs:15051:26)
    at PNPMProxy.getPackageVersion (/Users/yannbraga/open-source/storybook/code/lib/cli/dist/generate.js:1492:43)
    at isNxProject (/Users/yannbraga/open-source/storybook/code/lib/cli/dist/generate.js:535:42)
    at detect (/Users/yannbraga/open-source/storybook/code/lib/cli/dist/generate.js:673:13)
```


It also feels a little weird having tons of errors but the storybook init command continues “normally” as these errors are console.error messages

Can you take a look at that?

File: code/lib/cli/src/js-package-manager/PNPMProxy.ts [hunk 4]
```diff
@@ -107,6 +111,50 @@ export class PNPMProxy extends JsPackageManager {
...
+        const pkg = pnpApi.getPackageInformation(pkgLocator);
+
+        const packageJSON = fs.readFileSync(
+          path.join(pkg.packageLocation, 'package.json'),
+          'utf-8'
+        );
+
+        return semver.coerce(JSON.parse(packageJSON).version)?.version ?? null;
+      } catch (error) {
+        console.error('Error while fetching package version in Yarn PnP mode:', error);
```
Comment (yannbf) [inline code/lib/cli/src/js-package-manager/PNPMProxy.ts:136]:
```suggestion
        console.error('Error while fetching package version in PNPM with PnP mode:', error);
```

**Comment by valentinpalkovic** [comment]
> Let me start by saying that this is super awesome ❤️
> 
> Unfortunately it seems like the pnp solutions do not work?
> 
> ### Yarn2
> ```
> • Detecting project typeError while fetching package version in Yarn PnP mode: Error: Your application tried to access nx, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.
> 
> Required package: nx
> Required by: /Users/yannbraga/experiments/delete/react-ts
> 
>     at makeError (/Users/yannbraga/experiments/delete/react-ts/.pnp.cjs:21064:34)
>     at resolveToUnqualified (/Users/yannbraga/experiments/delete/react-ts/.pnp.cjs:22781:21)
>     at Object.resolveToUnqualified (/Users/yannbraga/experiments/delete/react-ts/.pnp.cjs:22973:26)
>     at Yarn2Proxy.getPackageVersion (/Users/yannbraga/open-source/storybook/code/lib/cli/dist/generate.js:1751:43)
>     at isNxProject (/Users/yannbraga/open-source/storybook/code/lib/cli/dist/generate.js:535:42)
> ```
> 
> And similar errors happen when trying to resolve `prettier`, `@babel/plugin-transform-typescript`, `eslint-plugin-storybook` in the same execution
> 
> ### PNPM
> ```
> Detecting project typeError while fetching package version in Yarn PnP mode: Error: Your application tried to access nx, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.
> 
> Required package: nx (via "nx")
> Required by: /Users/yannbraga/experiments/delete/react-ts
> 
>     at internalTools_makeError (/Users/yannbraga/experiments/delete/react-ts/.pnp.cjs:13925:34)
>     at resolveToUnqualified (/Users/yannbraga/experiments/delete/react-ts/.pnp.cjs:14884:23)
>     at Object.resolveToUnqualified (/Users/yannbraga/experiments/delete/react-ts/.pnp.cjs:15051:26)
>     at PNPMProxy.getPackageVersion (/Users/yannbraga/open-source/storybook/code/lib/cli/dist/generate.js:1492:43)
>     at isNxProject (/Users/yannbraga/open-source/storybook/code/lib/cli/dist/generate.js:535:42)
>     at detect (/Users/yannbraga/open-source/storybook/code/lib/cli/dist/generate.js:673:13)
> ```
> 
> It also feels a little weird having tons of errors but the storybook init command continues “normally” as these errors are console.error messages
> 
> Can you take a look at that?

Can you provide the repo, where it fails?

File: code/lib/cli/src/automigrate/index.ts [hunk 5]
```diff
@@ -211,10 +212,19 @@ export async function runFixes({
...
+        configDir,
+        packageManager,
+      });
+
       result = await f.check({
         packageManager,
         configDir,
         rendererPackage,
+        mainConfig,
+        storybookVersion,
```
Comment (yannbf) [inline code/lib/cli/src/automigrate/index.ts:225]: given that this is not a coerced version, it will break in places that use it with `semver.gte` etc
```suggestion
        storybookVersion: sbVersionCoerced,
```

Comment (valentinpalkovic) [reply code/lib/cli/src/automigrate/index.ts:225]: @yannbf Can you show me some examples where you think this change breaks the current behaviour?

File: code/frameworks/nextjs/src/utils.ts [hunk 6]
```diff
@@ -94,7 +94,15 @@ export const addScopedAlias = (baseConfig: WebpackConfig, name: string, alias?:
...
 export const scopedResolve = (id: string): string => {
-  const scopedModulePath = require.resolve(id, { paths: [path.resolve()] });
+  // id = css-loader/package.json
+  let scopedModulePath;
+
+  try {
+    scopedModulePath = require.resolve(id, { paths: [path.resolve()] });
+  } catch (e) {
+    scopedModulePath = require.resolve(id);
+  }
```
Comment (ndelangen) [inline code/frameworks/nextjs/src/utils.ts:103]: So that was to fix for pnp right, we just left the top statement for backwards compat.
We should likely add a todo here, for ourselves, to just have the bottom statement in 8.0?

**Comment by yannbf** [comment]
Unfortunately there is something going on where the output of automigration affects the other and the user gets stuck (does not happen in `next`). I have to investigate what's causing it.

image

**Review by yannbf — APPROVED** [review]

File: code/lib/cli/src/js-package-manager/JsPackageManager.ts [hunk 7]
```diff
@@ -264,15 +264,15 @@ export abstract class JsPackageManager {
...
-      } catch (e) {
-        logger.error('An error occurred while removing dependencies.');
-        logger.log(e.message);
-        throw new HandledError(e);
-      }
+      return this.writePackageJson(packageJson);
+    }
+
+    try {
+      return this.runRemoveDeps(dependencies);
```
Comment (valentinpalkovic) [inline code/lib/cli/src/js-package-manager/JsPackageManager.ts:271]: Since this statement is not awaited, the surrounding catch block doesn’t have any effect.

```javascript
function getPromise() {
  // This promise rejects immediately
  return new Promise((resolve, reject) => reject(new Error("An error occurred")));
}

try {
  return getPromise(); // This won't be caught by the catch block below
} catch (err) {
  console.log("Caught an error:", err);
}
```

Comment (yannbf) [reply code/lib/cli/src/js-package-manager/JsPackageManager.ts:271]: Great catch!

**Comment by yannbf** [comment]
Time to merge this!!
