### PR TITLE
UI: Overhaul layout engine

### LINKED ISSUE #14916: Addons panel does not appear
**Describe the bug**

This is duplicating #11670 which was closed for inactivity, as this is still a problem on 6.1.14. Opening storybook for a project, viewport changes from opening DevTools or sometimes no user action at all, the actions addon panel is not visible. Using the "D" shortcut is a known workaround. However this shortcut may not be obvious to non-devs/casual users using the tool as a documentation source. Currently trying to validate if this is only an issue in local environments or if it also affects the static build (a prior bug report indicated it does not affect the static build).

**To Reproduce**

Same as #11670 

1. Open storybook
2. Observe that Addons panel may not be visible (trying to get a more concrete repro than, "this randomly happens")

**System**

```
Environment Info:

  System:
    OS: macOS 11.3.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 15.12.0 - ~/.nvm/versions/node/v15.12.0/bin/node
    Yarn: 2.4.1 - /opt/homebrew/bin/yarn
    npm: 7.6.3 - ~/.nvm/versions/node/v15.12.0/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 87.0
    Safari: 14.1
```

**Additional context**

### PR DESCRIPTION
**Pull request by ndelangen**
Resolves https://github.com/storybookjs/storybook/issues/14916
Closes https://github.com/storybookjs/storybook/issues/24215
Closes https://github.com/storybookjs/storybook/issues/24252
Closes https://github.com/storybookjs/storybook/issues/24253

Works on #24124 

https://github.com/storybookjs/storybook/assets/5678122/90bd8d73-2241-4eaf-9e78-d22c4c608a85

## What we did

This PR completely overhauls the layout engine, and how sidebar/panels are sized and positioned. Mobile/responsive UI does **not** work here, that's being worked on in follow-up PRs: https://github.com/storybookjs/storybook/issues/24124

- Switch from using absolute positioning of all panels to using CSS grid.
- Don't re-render Canvas when resizing to a mobile viewport
- ... In fact don't use resize observers at all, but rely on [matching media queries](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia) instead, which is more performant and less error prone.
- Enable users to drag panels to the edge to toggle them off completely, which is easier than using the menu or remembering keyboard shortcuts - both of which still works. The sidebar and right panel still have a minimum width though.
- Change the layout state to not have booleans for the panels but instead actual sizes, to ensure you can't get into "impossible states" like `{ isFullscreen: true, showNav: true }`. The new size state properties are accompanies by `recentVisisbleSizes` properties that are used when restoring panels back from a non-shown state
- Changed how layout state is synced, so the Layout component has an internal state of the size that is synced to the manager API when dragging stops. There's also a sync the other way, when sizes are changed via the manager API.

**This PR was first done by @ndelangen but then finished 6 months later by @JReinhold and @cdedreuille, so not all changes might make sense together anymore.**

#### The changes in this PR are covered in the following automated tests:
- [x] stories
- [x] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

1. Compile and run any sandbox
2. Resize panels with dragging
3. Toggle panels with the menu and with keyboard shortcuts (A, S, D and F)
4. Use query params to set initial layout state [as per documentation](https://storybook.js.org/docs/react/configure/features-and-behavior#configuring-through-url-parameters).

### Documentation

- [x] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Comment by ndelangen** [comment]
A bit of a Christmas present 🎁

**Comment by ghengeveld** [comment]
> A bit of a Christmas present 🎁

What are you doing working on Christmas?!

File: code/ui/manager/src/components/layout/Layout.tsx [hunk 1]
```diff
@@ -0,0 +1,144 @@
+import { useImmerReducer } from 'use-immer';
+import type { Dispatch, MutableRefObject } from 'react';
+import React, { useEffect, useRef } from 'react';
+import { DESKTOP, getGridTemplate, MOBILE, SHARED } from './Layout.styles';
+import type { Props, LayoutState, ExposedLayoutState } from './Layout.types';
+import { MobileControls } from './Layout.MobileControls';
+import { DesktopControls } from './Layout.DesktopControls';
+
+export const Layout = ({ state: incomingState, persistence, setState, ...slots }: Props) => {
+  const [state, updateState] = useImmerReducer<LayoutState, Partial<LayoutState>>(
```
Comment (IanVS) [inline code/ui/manager/src/components/layout/Layout.tsx:10]: It feels like a little bit of a bummer to add a nearly-one-megabyte dependency just for this one use.  Can you talk a little about why you chose to use it here?  Aside from the added filesize, it's also one extra tool that contributors may need to learn.  I am not familiar with it myself, and while I'm happy to learn it if it adds a ton of value, if there's a way we could avoid it, I'd prefer to, personally.

File: code/ui/manager/src/container/Panel.tsx [hunk 2]
```diff
@@ -3,7 +3,7 @@ import React from 'react';
 import memoize from 'memoizerific';
 import { Consumer, type Combo } from '@storybook/manager-api';
 
-import AddonPanel from '../components/panel/panel';
+import AddonPanel from '../components/panel/Panel';
```
Comment (IanVS) [inline code/ui/manager/src/container/Panel.tsx:6]: Might as well make this a named export as well?

File: code/ui/manager/src/settings/index.tsx [hunk 3]
```diff
@@ -6,9 +6,9 @@ import { global } from '@storybook/global';
 import type { FC, SyntheticEvent } from 'react';
 import React, { Fragment } from 'react';
 
-import { AboutPage } from './about_page';
-import { ReleaseNotesPage } from './release_notes_page';
-import { ShortcutsPage } from './shortcuts_page';
+import { AboutPage } from './About.page';
+import { ReleaseNotesPage } from './ReleaseNotes.page';
+import { ShortcutsPage } from './Shortcuts.page';
```
Comment (IanVS) [inline code/ui/manager/src/settings/index.tsx:11]: Is this a Storybook convention, to name page files with `.page`?  Any reason not to just call these `AboutPage`, etc?

File: code/ui/manager/src/components/layout/Layout.types.ts [hunk 4]
```diff
@@ -0,0 +1,30 @@
+import type { API_PanelPositions, ViewMode } from '@storybook/types';
+import type React from 'react';
+import type { usePersistence } from './Layout.persistence';
+
+export interface ExposedLayoutState {
+  panelPosition: API_PanelPositions;
+  panel: boolean;
+  sidebar: boolean;
```
Comment (IanVS) [inline code/ui/manager/src/components/layout/Layout.types.ts:8]: Personal preference: I like to follow a convention of booleans starting with `is` or `has` or `show` or something like that, rather than just a noun.  I had to dig and find these types to convince myself they were indeed boolean.  I think it would be more clear if these were `showPanel` and `showSidebar`, or similar.

**Review by IanVS — COMMENTED** [review]
I'm not too familiar with the manager UI, so I don't feel qualified to give this a ✅, but it's definitely pretty exciting looking!  I left a few niggly comments and questions, from a brief skim-through.

File: code/ui/manager/src/components/layout/Layout.tsx (hunk 1 above)
Comment (shilman) [reply code/ui/manager/src/components/layout/Layout.tsx:10]: Agree with @IanVS on this one! 👍

**Comment by shilman** [comment]
Nice suggestions across the board @IanVS! Merry christmas!!! 🎄

File: code/ui/manager/src/components/layout/Layout.types.ts (hunk 4 above)
Comment (ghengeveld) [reply code/ui/manager/src/components/layout/Layout.types.ts:8]: `showPanel` suggests a function to me. I prefer `is` or `has` for booleans.

File: code/ui/manager/src/components/layout/Layout.tsx (hunk 1 above)
Comment (ndelangen) [reply code/ui/manager/src/components/layout/Layout.tsx]: I love immer, and think we should use it everywhere, but I was able to downgrade the vanilla useReducer.
Where did you get the 1MB number from?

**Comment by ndelangen** [comment]
This is ready for re-review IMHO

@IanVS or @shilman want to give this another pass?

**Review by IanVS — COMMENTED** [review]
The code looks good to me.  Here are a few notes from an experience perspective:

1) Changing the size of the panels is jerky, whereas it was smooth before.  Is that intentional?
2) The hover shadow could maybe use some love from @MichaelArestad, it feels a bit … stark maybe?
3) I'm a bit sad that we lose the animated expand/collapse when using the keyboard shortcuts now.
4) The only real "bug": moving the addon panel from bottom to side with the button works, but it does not return to the bottom when clicking the button again, without hiding/showing the panel.
5) The panels return to a preset width after hiding/showing, rather than returning to their previously-set size.

Overall I think this is a win, and it will be great to fix the bug where the panel doesn't open at all.  Feel free to take or leave this feedback, just wanted to share what I noticed.

**Comment by ndelangen** [comment]
Thanks for taking a look, I'll investigate these findings and see if I can improve it.

UI wise, I'll experiment with changing the shadow with a tiny handle instead, @ghengeveld suggested this.

**Comment by MichaelArestad** [comment]
This one slipped by me. Thank you fore the reminder @IanVS! Here are some notes from my tests in Safari:

### 1. The border is missing
image

### 2. The drop shadow is significantly darker than on `next`.
image

The border and drop shadow should look like this:
image

### 3. I can no longer toggle addon orientation reliably
Trying via keyboard shortcut or using the menu usually results in it being stuck in side-by-side orientation.



### 4. When I drag the panel wider than it allows, the shadow disappears



This is how it should work:



### 5. The panel probably shouldn't get smaller than 250px

Any smaller, and it's pretty much unusable. I would rather the panel be closed if they need the space.

### 6. The panel and sidebar should not be percentage widths

Often, when I am resizing the window, I only want the canvas to change sizes, not the sidebars. If I wanted the canvas to be really wide, I would need to resize the window and then resize both sidebars.

**Comment by ndelangen** [comment]
I made it percentage based, to avoid the bug where absolute pixel sizes could cause the sizes to become impossible to be applied, causing the panel to be renderer out of bounds.

**Comment by MichaelArestad** [comment]
@ndelangen Gotcha. Is there another way around this?

**Comment by jd-oconnor** [comment]
@ndelangen @MichaelArestad @shilman @IanVS I've made some updates from your feedback and I think it's ready for another pass. 

- The shadow I changed to a soft blue from our theme. I can always use a basic shadow like we had previously if it's a no-go. 
- For the addon panel, the orientation bug is fixed so you should be able to switch it back and forth from right to bottom and not lose the drag capability, and I added the border too.
- The drag is nice and smooth again. I removed the `Math.round` that was being applied, causing it to jump between whole percentages making it feel jerky.
- I kept percentages after talking with Norbert and I like the responsiveness and flexibility percentages provide for nearly any use case.
- I also didn't add a drag icon but if that's something we for sure want, I don't mind spending some time adding it.

**Comment by IanVS** [comment]
What's the current status here?  I see that it's still marked as a draft, and there are some conflicts, but it sounds like you might be looking for a review, @jd-oconnor?

**Comment by jd-oconnor** [comment]
> What's the current status here? I see that it's still marked as a draft, and there are some conflicts, but it sounds like you might be looking for a review, @jd-oconnor?

Sorry about that -- I marked it as ready for review and I can work on resolving those conflicts. If I get stuck on any I'll put a message in contributing on discord. Looking forward to your feedback. Thanks, @IanVS!

**Comment by MichaelArestad** [comment]
I'm having trouble testing this with the published Storybooks. For example, the `storybook-ui` Storybook shows the white screen: https://635781f3500dd2c49e189caf-jynsnpfncy.chromatic.com

The corresponding console error: 
image

**Comment by MichaelArestad** [comment]
> I kept percentages after talking with Norbert and I like the responsiveness and flexibility percentages provide for nearly any use case.

@jd-oconnor @ndelangen The sidebar and addons panel really should be fixed width for the best user experience. Many folks resize the browser regularly to get a feel for how the component works at various sizes or just to make space for other windows. Having the sidebar and addons panel also resize because of percentage-based widths is not ideal as the center content resizes at 1/3 the rate of the browser. Not only is it unexpected, but it doesn't look the best either. Is there a way to fix these panel layout issues without making the addon panel and the sidebar percentage-based?

**Comment by cdedreuille** [comment]
As we are working on improving the mobile discussion, we had a conversation with @JReinhold and @shilman to include this work as. base for the layout experience. We are going to reopen this branch. @JReinhold and I will work on it going forward.

**Comment by JReinhold** [comment]
I've managed to merge in `next`, but it's most likely incomplete, so we need to meticulously go through the changes.

Bugs I've noticed so far:

- [ ] toggling full screen when the user has already manually resized a panel to 0 size does nothing
- [ ] the addon panel is visible in docs mode

**Review by cdedreuille — APPROVED** [review]

File: code/lib/manager-api/src/modules/layout.ts [hunk 5]
```diff
@@ -219,61 +312,73 @@ export const init: ModuleFn = ({ store, provider, singleStory, fullAPI }) => {
...
+      return getIsFullscreen(store.getState());
+    },
+    getIsPanelShown() {
+      return getIsPanelShown(store.getState());
+    },
+    getIsNavShown() {
+      return getIsNavShown(store.getState());
+    },
+
     setOptions: (options: any) => {
```
Comment (JReinhold) [inline code/lib/manager-api/src/modules/layout.ts:340]: the changes below just reverses the condition for readability, nothing else.

File: code/lib/manager-api/src/modules/layout.ts [hunk 6]
```diff
@@ -284,7 +389,6 @@ export const init: ModuleFn = ({ store, provider, singleStory, fullAPI }) => {
     api,
     state: merge(api.getInitialOptions(), persisted),
     init: () => {
-      api.setOptions(merge(api.getInitialOptions(), persisted));
```
Comment (JReinhold) [inline code/lib/manager-api/src/modules/layout.ts:287]: this makes setting layout from URL work again, similar to https://github.com/storybookjs/storybook/pull/23750

File: code/ui/manager/src/app.stories.tsx
Comment (JReinhold) [inline code/ui/manager/src/app.stories.tsx:1]: I need to re-add this back.

**Review by JReinhold — APPROVED** [review]

**Review by cdedreuille — APPROVED** [review]

**Comment by ndelangen** [comment]
@JReinhold I assume you're taking this PR to it's conclusion? Do you need anything from me?
