### PR TITLE
Adjust child process I/O for compodoc command

### LINKED ISSUE #22400: [Bug]: Storybook fails to build on large Angular projects due to excessive Compodoc output
### Describe the bug

The `start-storybook` and `build-storybook` builders fail with exit code 127 on large Angular projects.

There is no output over stdout or stderr. There are no files produced. There is only a non-zero exit code.

This is what I see when I attempt to run the `start-storybook` builder:

```command
$ ng run myproject:storybook
$ echo $?
127
```

Please see Additional Context for an explanation of what I believe is causing this failure as well as some possible solutions.

### To Reproduce

_No response_

### System

```shell
Environment Info:

  System:
    OS: Linux 6.2 Pop!_OS 22.04 LTS
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    npm: 9.6.3 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.165
    Firefox: 112.0.1
  npmPackages:
    @storybook/addon-actions: ^7.0.8 => 7.0.8 
    @storybook/addon-essentials: ^7.0.8 => 7.0.8 
    @storybook/addon-links: ^7.0.8 => 7.0.8 
    @storybook/angular: ^7.0.8 => 7.0.8
```

### Additional context

The problem appears to be due to the fact that...

1. Compodoc is VERY chatty
   - On my project, compodoc produces 1,347,625 bytes of output
2. [Storybook attempts to buffer the output from compodoc](https://github.com/storybookjs/storybook/blob/7e573248c43ade20431b79e2da59c93f1cd8ca82/code/lib/cli/src/js-package-manager/JsPackageManager.ts#L424)
3. The default [`maxBuffer` on `spawnSync`](https://nodejs.org/api/child_process.html#child_processspawnsynccommand-args-options) is `1024*1024 = 1,048,576 bytes`
4. Node will terminate child processes [if output exceeds the maxBuffer](https://nodejs.org/api/child_process.html#maxbuffer-and-unicode)

In my case, the 1,347,625 bytes of output exceeds the default maximum of 1,048,576 bytes, causing compodoc to be terminated.

I've done some investigating and found three bits of evidence that support this idea:

1. If I **suppress compodoc's output** with...

    ```
    npx ng run myproject:storybook --compodoc-args='--silent --exportFormat=json'
    ```

    ... then storybook builds/starts just fine.
2. If I modify [`JSPackageManager#executeCommand`](https://github.com/storybookjs/storybook/blob/7e573248c43ade20431b79e2da59c93f1cd8ca82/code/lib/cli/src/js-package-manager/JsPackageManager.ts#L424), so that it defaults to "inherit" instead of "pipe", then all of compodoc's output is shown on my console instead of being buffered. This allows me to build/start storybook successfully.
3. If I modify [`JSPackageManager#executeCommand`](https://github.com/storybookjs/storybook/blob/7e573248c43ade20431b79e2da59c93f1cd8ca82/code/lib/cli/src/js-package-manager/JsPackageManager.ts#L424), so that its `maxBuffer` is arbitrarily huge (e.g. `3000000`), then the output is buffered successfully and is output when the spawned compodoc finishes. Storybook then proceeds successfully.

Possible solutions:

- For those encountering this problem today, passing `--silent` to `--compodoc-args` is a fine workaround.
- As a more permanent solution, I think it may be a good idea to change `runCompodoc` to use `inherit` for stdio. Setting the `maxBuffer` arbitrarily high doesn't sound as sustainable, as some folks may require an even higher buffer.

### PR DESCRIPTION
**Pull request by valentinpalkovic**
Closes https://github.com/storybookjs/storybook/issues/22400

## What I did

Refactor package manager's runPackageCommand method to include an optional stdio parameter for better control over child process I/O

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

File: code/lib/cli/src/js-package-manager/Yarn1Proxy.ts [hunk 1]
```diff
@@ -42,8 +42,13 @@ export class Yarn1Proxy extends JsPackageManager {
...
 
-  runPackageCommand(command: string, args: string[], cwd?: string): string {
-    return this.executeCommand(`yarn`, [command, ...args], undefined, cwd);
+  runPackageCommand(
+    command: string,
+    args: string[],
+    cwd?: string,
+    stdio?: 'pipe' | 'inherit'
+  ): string {
+    return this.executeCommand(`yarn`, [command, ...args], stdio, cwd);
```
Comment (yannbf) [inline code/lib/cli/src/js-package-manager/Yarn1Proxy.ts:51]: The implementation of runPackageCommand changed to be async and the implementation of executeCommand was split into executeCommand(async) and executeCommandSync. Could you merge the latest next and resolve the conflicts?

**Review by yannbf — CHANGES_REQUESTED** [review]

File: code/lib/cli/src/js-package-manager/Yarn1Proxy.ts (hunk 1 above)
Comment (valentinpalkovic) [reply code/lib/cli/src/js-package-manager/Yarn1Proxy.ts]: Done

**Review by yannbf — APPROVED** [review]
LGTM! Do you plan on patching this?
