### PR TITLE
Fix Source View in Nextjs projects

### LINKED ISSUE #20356: [Bug]: Show Code in Sample Components is not showing the component code (7.0.0-beta13 nextjs)
### Describe the bug

This bug is for 7.0.0-beta13 with nextjs and was confirmed by shilman (see below).

1. Run npx storybook@next init into a nextjs (13) project.  
2. Start the dev server with npm run storybook
3. Navigate to sample component docs
4. All of the "show code" views in the sample components don't seem to be showing the component code.  I did a bunch of searching but can't find anyone else that has run into this.   Every sample component (EG: the default Button) shows the attached code when you click on "Show code".

Screenshot 2022-12-20 at 3 07 16 PM

Feedback from shilman
Ok i'm able to reproduce the issue. Can you please file a github issue about this?  Looks like a bug in @storybook/nextjs

I think there are a couple problems:
1. it doesn't show the component name
2. it doesn't show the props passed to the component
5. the PageRouterProvider is getting automatically injected by the nextjs frameowork, but i believe shouldn't show up in the source snippet because it's an implementation detail

### To Reproduce

```shell
This command seems to be hanging for me but the bug is reproducible by installing the latest storybook@next beta and initiating a new instance in a nextjs 13 project (confirmed by other parties including shilman)
```

### System

```shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 18.10.0 - /opt/homebrew/bin/node
    npm: 8.19.2 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 16.2
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by valentinpalkovic**
Resolves https://github.com/storybookjs/storybook/issues/20356

## What I did

I have set the `parameters.docs.source.excludeDecorators` to true per default.

## How to test

1. Run a sandbox for template, e.g. `yarn task --task sandbox --start-from auto --template nextjs/default-ts`
2. Open Storybook in your browser
3. Access Button Docs
4. Click on "Show Code" and it should show the component code properly

## Checklist

- [x] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

File: code/renderers/react/src/docs/config.ts [hunk 1]
```diff
@@ -8,6 +8,9 @@ export const parameters = {
     story: { inline: true },
     extractArgTypes,
     extractComponentDescription,
+    source: {
+      excludeDecorators: true,
+    },
```
Comment (valentinpalkovic) [inline code/renderers/react/src/docs/config.ts:13]: @tmeasday Should I set it to true for the other renderers as well? Because in the code we assume that it is set per default to true. E.g. here: https://github.com/storybookjs/storybook/blob/valentin/fix-source-code-view-for-nextjs/code/renderers/react/src/docs/jsxDecorator.tsx#L210

**Comment by JReinhold** [comment]
Was it default true in 6.5 as well and we just lost it at some point, or is this new?
If this is new I would consider this a breaking change that we need to mention in migration notes - and I think we should do it for all renderers if we want to do this.

Alternatively you could set this in the NextJS framework instead of the renderer, if it's only there it is causing trouble.

**Comment by valentinpalkovic** [comment]
I have to use the react renderer. Next.js does not have its own renderer.

**Comment by JReinhold** [comment]
> I have to use the react renderer. Next.js does not have its own renderer.

I'm pretty sure you can set parameters in frameworks the same way you'd do it in renderes, via the `preset.ts`. In https://github.com/storybookjs/storybook/blob/next/code/frameworks/nextjs/src/preset.ts :

```ts
...

export const parameters = {
  docs: {
    source: {
      excludeDecorators: true,
    }
  } 
};
```

**Comment by valentinpalkovic** [comment]
@JReinhold Changed!

**Comment by JReinhold** [comment]
I'm still seeing weird sources in the published NextJS Storybook:

https://634ff0d0ec053b270775979d-zjgrspsocr.chromatic.com/?path=/docs/example-button--docs

image


Was this PR supposed to fix this, or am I missing something? Or maybe this only fixes it in dev mode?

File: code/renderers/react/src/docs/config.ts (hunk 1 above)
Comment (tmeasday) [reply code/renderers/react/src/docs/config.ts]: I think this is a question that @shilman might need to answer.

**Comment by shilman** [comment]
@valentinpalkovic @JReinhold
- Setting the parameters should happen in `preview.tsx` not `preset.ts`
- We've never set `excludeDecorators` to `true` by default, but there's no reason we can't

**Comment by valentinpalkovic** [comment]
@shilman or @tmeasday May I get final approval? :)

**Review by tmeasday — APPROVED** [review]
Fine by me! But I think I am missing why we need to drop the decorators in next exactly? Perhaps a comment explaining why there's problematic decorators would help?

**Comment by tmeasday** [comment]
@valentinpalkovic I re-enabled the test https://github.com/storybookjs/storybook/pull/21029/commits/f5d598916ce74b5b0b91456a3e1ad309343d0cdb and it worked great!
