### PR TITLE
Telemetry: Always send error events if init doesn't succeed

### LINKED ISSUE #21878: CLI: Fix init failure telemetry
### Describe the bug

There are numerous early exit cases in the `sb init` command which are not properly reported by telemetry. These should all be reported as `error` events, and the end-user behavior of the CLI should retain the current behavior.

### To Reproduce

_No response_

### System

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tmeasday**
Closes #21878

## What I did

We should never exit early from init via `process.exit()` or a return inside the `doInitiate()` function

## How to test

The only one I was able to reproduce was an incorrect project type:

```
STORYBOOK_TELEMETRY_DEBUG=1 ~/GitHub/storybookjs/storybook/code/lib/cli/bin/index.js init  -t madeup
```

I think the other changes only happen if you somehow crash yarn etc.

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

File: code/lib/cli/src/js-package-manager/JsPackageManager.ts [hunk 1]
```diff
@@ -79,7 +80,7 @@ export abstract class JsPackageManager {
       this.runInstall();
     } catch (e) {
       done('An error occurred while installing dependencies.');
-      process.exit(1);
+      throw new HandledError(e);
```
Comment (tmeasday) [inline code/lib/cli/src/js-package-manager/JsPackageManager.ts:83]: I'm not sure if there are implications for the migration scripts in throwing rather than exiting inside these functions. @yannbf do you?

It seems weird to call `process.exit()` however.

File: code/lib/cli/src/initiate.ts [hunk 2]
```diff
@@ -290,23 +293,23 @@ async function doInitiate(options: CommandOptions, pkg: PackageJson): Promise<vo
...
+      logger.log();
+      throw new HandledError(`Unknown project type supplied: ${projectTypeProvided}`);
+    }
+  } else {
+    try {
       projectType = detect(packageJson, options);
+    } catch (err) {
+      done(err.message);
+      throw new HandledError(err);
     }
```
Comment (tmeasday) [inline code/lib/cli/src/initiate.ts:312]: I moved the try inside but I'm pretty sure it wasn't possible to throw outside.

File: code/lib/cli/src/initiate.ts [hunk 3]
```diff
@@ -320,16 +323,10 @@ async function doInitiate(options: CommandOptions, pkg: PackageJson): Promise<vo
...
+    throw new HandledError(`Angular project already installed`);
   }
 
-  const installResult = await installStorybook(
-    projectType as ProjectType,
-    packageManager,
-    options
-  ).catch((e) => {
-    process.exit();
-  });
```
Comment (tmeasday) [inline code/lib/cli/src/initiate.ts:332]: I'm not sure why this was here, given the outer catch does the same thing with `exit(1)`. Did we want this to exit 0? I doubt it.

File: code/lib/cli/src/initiate.ts [hunk 4]
```diff
@@ -320,16 +323,10 @@ async function doInitiate(options: CommandOptions, pkg: PackageJson): Promise<vo
...
+  const installResult = await installStorybook(projectType as ProjectType, packageManager, options);
```
Comment (shilman) [inline code/lib/cli/src/initiate.ts:329]: @tmeasday This is new behavior right? Since it's not throwing a handled error. But this seems like a good change

File: code/lib/cli/src/js-package-manager/JsPackageManager.ts (hunk 1 above)
Comment (yannbf) [reply code/lib/cli/src/js-package-manager/JsPackageManager.ts:83]: I believe that's fine! The error will be surfaced in the automigrations like:
`❌ error when running XXX migration`

**Review by JReinhold — APPROVED** [review]
LGTM 💪
