### PR TITLE
CLI: Fix init help for `storybook` command

### LINKED ISSUE #29276: [Bug]: common CLI commands are missing from --help output
### Describe the bug

The `dev`, `build` and `init` commands (at least) are missing from `--help` output.

```
> ./node_modules/.bin/storybook -V
8.3.3
```

```
> ./node_modules/.bin/storybook --help
Usage: cli <command> [options]

Options:
  -V, --version                           output the version number
  -h, --help                              display help for command

Commands:
  add [options] <addon>                   Add an addon to your Storybook
  remove [options] <addon>                Remove an addon from your Storybook
  upgrade [options]                       Upgrade your Storybook packages to v8.3.3
  info [options]                          Prints debugging information about the local environment
  migrate [options] [migration]           Run a Storybook codemod migration on your source files
  sandbox|repro [options] [filterValue]   Create a sandbox from a set of possible templates
  link [options] <repo-url-or-directory>  Pull down a repro from a URL (or a local directory), link it, and run storybook
  automigrate [options] [fixId]           Check storybook for incompatibilities or migrations and apply fixes
  doctor [options]                        Check Storybook for known problems and provide suggestions or fixes
  help [command]                          display help for command
```

### Reproduction link

storybook --help

### Reproduction steps

1. Run `storybook --help`

### System

```
> npx storybook info

Storybook Environment Info:

  System:
    OS: macOS 14.6.1
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Shell: 5.1.8 - /usr/local/bin/bash
  Binaries:
    Node: 20.11.1 - ~/.asdf/installs/nodejs/20.11.1/bin/node
    npm: 10.2.4 - ~/.asdf/plugins/nodejs/shims/npm <----- active
  Browsers:
    Chrome: 129.0.6668.90
    Edge: 129.0.2792.79
    Safari: 17.6
  npmPackages:
    @storybook/addon-actions: ^8.3.3 => 8.3.3
    @storybook/addon-controls: ^8.3.3 => 8.3.3
    @storybook/addon-docs: ^8.3.3 => 8.3.3
    @storybook/addon-essentials: ^8.3.3 => 8.3.3
    @storybook/addon-interactions: ^8.3.3 => 8.3.3
    @storybook/addon-links: ^8.3.3 => 8.3.3
    @storybook/addon-onboarding: ^8.3.3 => 8.3.3
    @storybook/addon-webpack5-compiler-swc: ^1.0.5 => 1.0.5
    @storybook/blocks: ^8.3.3 => 8.3.3
    @storybook/preview-api: ^8.3.3 => 8.3.3
    @storybook/react: ^8.3.3 => 8.3.3
    @storybook/react-webpack5: ^8.3.3 => 8.3.3
    @storybook/test: ^8.3.3 => 8.3.3
    @storybook/test-runner: ^0.19.1 => 0.19.1
    chromatic: ^11.0.0 => 11.10.4
    eslint-plugin-storybook: ^0.8.0 => 0.8.0
    storybook: ^8.3.3 => 8.3.3
    storybook-addon-apollo-client: ^7.3.0 => 7.3.0
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by toothlessdev**
Fixes part of #29276 

## What I did

- Add test code for common CLI commands `help`
- Add `init` command to common CLI commands `help`

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

| name | before | after | diff | z | % |
| ---- | ------ | ----- | ---- | - | - |
| createSize |  0 B | 0 B | 0 B | - | - |
| generateSize |  78.2 MB | 78.2 MB | 0 B | 0.98 | 0% |
| initSize |  143 MB | 143 MB | 0 B | 1.06 | 0% |
| diffSize |  65.2 MB | 65.2 MB | 0 B | 0.61 | 0% |
| buildSize |  6.88 MB | 6.88 MB | 0 B | 1.22 | 0% |
| buildSbAddonsSize |  1.51 MB | 1.51 MB | 0 B | 0.58 | 0% |
| buildSbCommonSize |  195 kB | 195 kB | 0 B | - | 0% |
| buildSbManagerSize |  1.9 MB | 1.9 MB | 0 B | 1.22 | 0% |
| buildSbPreviewSize |  271 kB | 271 kB | 0 B | - | 0% |
| buildStaticSize |  0 B | 0 B | 0 B | - | - |
| buildPrebuildSize |  3.88 MB | 3.88 MB | 0 B | 1.22 | 0% |
| buildPreviewSize |  3 MB | 3 MB | 0 B | - | 0% |
| testBuildSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbAddonsSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbCommonSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbManagerSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbPreviewSize |  0 B | 0 B | 0 B | - | - |
| testBuildStaticSize |  0 B | 0 B | 0 B | - | - |
| testBuildPrebuildSize |  0 B | 0 B | 0 B | - | - |
| testBuildPreviewSize |  0 B | 0 B | 0 B | - | - |

| name | before | after | diff | z | % |
| ---- | ------ | ----- | ---- | - | - |
| createTime |  7.6s | 22.6s | 15s | 1.22 | 66.4% |
| generateTime |  23.4s | 19.3s | -4s -167ms | -0.73 | -21.6% |
| initTime |  16.9s | 14.2s | -2s -714ms | -0.85 | -19% |
| buildTime |  11s | 7.9s | -3s -76ms | -0.91 | -38.6% |
| testBuildTime |  0ms | 0ms | 0ms | - | - |
| devPreviewResponsive |  5.3s | 6.4s | 1.1s | 0.92 | 17.6% |
| devManagerResponsive |  3.3s | 4s | 796ms | **1.3** | 🔺19.4% |
| devManagerHeaderVisible |  560ms | 602ms | 42ms | 0.55 | 7% |
| devManagerIndexVisible |  633ms | 694ms | 61ms | 0.84 | 8.8% |
| devStoryVisibleUncached |  945ms | 1.3s | 395ms | **1.35** | 🔺29.5% |
| devStoryVisible |  627ms | 689ms | 62ms | 1.03 | 9% |
| devAutodocsVisible |  519ms | 504ms | -15ms | -0.28 | -3% |
| devMDXVisible |  482ms | 610ms | 128ms | 1.08 | 21% |
| buildManagerHeaderVisible |  703ms | 704ms | 1ms | **1.74** | 0.1% |
| buildManagerIndexVisible |  725ms | 714ms | -11ms | **1.56** | -1.5% |
| buildStoryVisible |  704ms | 702ms | -2ms | **1.74** | -0.3% |
| buildAutodocsVisible |  566ms | 507ms | -59ms | 0.66 | -11.6% |
| buildMDXVisible |  596ms | 589ms | -7ms | **2.07** | -1.2% |

## Greptile Summary

Added the 'init' command and related tests to the Storybook CLI help output, ensuring users can see initialization options when running `storybook --help`.

- Added `init` command to `code/lib/cli-storybook/src/bin/index.ts` with options for package manager, builder, and initialization preferences
- Added test coverage in `code/lib/cli-storybook/test/default/cli.test.cjs` to verify `init` command appears in help output
- Fixed missing documentation for core CLI commands (`init`, `dev`, `build`) in help text
- Integrated with existing telemetry and error handling patterns

### CODE REVIEW

File: code/lib/cli-storybook/src/bin/index.ts [hunk 1]
```diff
@@ -40,6 +41,38 @@ const command = (name: string) =>
...
+      await initiate(options);
+      if (!options.disableTelemetry) {
+        await telemetry('init', { source: 'cli' });
+      }
+    }).catch((e) => {
+      logger.error(e);
+      process.exit(1);
+    })
+  );
+
```
Comment (kasperpeulen) [inline code/lib/cli-storybook/src/bin/index.ts:75]: It would be great if you could re-use this code somehow:

https://github.com/storybookjs/storybook/blob/aec16d5b490d238050b6bdec3d169c77ed70498d/code/lib/create-storybook/src/bin/index.ts#L16-L50

**Review by kasperpeulen — CHANGES_REQUESTED** [review]

File: code/lib/cli-storybook/src/bin/index.ts (hunk 1 above)
Comment (kasperpeulen) [reply code/lib/cli-storybook/src/bin/index.ts:75]: This code will only be used for the help command `storybook --help`, because otherwise it gets forwarded to the right file using this proxy:

https://github.com/storybookjs/storybook/blob/3416d197992e46fb05f8fcc16767253f2e34572e/code/lib/cli/src/proxy.ts#L1-L22

Comment (toothlessdev) [reply code/lib/cli-storybook/src/bin/index.ts:75]: > It would be great if you could re-use this code somehow:
> 
> https://github.com/storybookjs/storybook/blob/aec16d5b490d238050b6bdec3d169c77ed70498d/code/lib/create-storybook/src/bin/index.ts#L16-L50

I tried to reuse the code, but the applied options such as addToGlobalContext are different, so it will be difficult to reuse.

Comment (kasperpeulen) [reply code/lib/cli-storybook/src/bin/index.ts]: That is correct.

Comment (toothlessdev) [reply code/lib/cli-storybook/src/bin/index.ts]: Thank you!

Comment (toothlessdev) [reply code/lib/cli-storybook/src/bin/index.ts]: > That is correct.

Thank you for review! I've applied the requirements that you mentioned! 🙂

**Review by kasperpeulen — APPROVED** [review]
