### PR TITLE
CSF: Use `__namedExportsOrder` array in loader if provided

### LINKED ISSUE #9136: CSF story order depends on webpack and breaks with vanilla es module imports
**Describe the bug**
The order of stories within the code of an `index.stories.js` file (in CSF format) determines the order of the storybook menu.

Consider the following example
```js
// orderedNamedExports.js
export const b = 'BB';
export const a = 'AA';
export const c = 'CC';

// start.js
import('./orderedNamedExports.js').then(module => {
  console.log(Object.keys(module));
});
```

When loading this file by going through webpack it will result in
```js
// (3) ["b", "a", "c"]
```

However, when using a browser native es module import the modules will be sorted.
```js
// (3) ["a", "b", "c"]
```

It is specified in the es module spec https://tc39.es/ecma262/#sec-modulenamespacecreate

> 7. Let sortedExports be a new List containing the same values as the list exports where the values are ordered as if an Array of the same values had been sorted using Array.prototype.sort using undefined as comparefn.

There are also part of the official platform tests https://github.com/tc39/test262/blob/master/test/language/module-code/namespace/internals/own-property-keys-sort.js

it sort of all started with this tweet so if you are interested there are more details
https://twitter.com/daKmoR/status/1204877164233015297?s=20

As this order determines the menu order it will result in "wrong menus" if you are not using webpack[1] - (and possible also when doing production builds with the upcoming es module flag in webpack v5)

**To Reproduce**
1. have a story file like
```js
import { html } from '../../index.js';

export default {
  title: 'Has order Paragraph-Heading',
};

export const paragraph = () =>
  html`
    <p>First Story</p>
  `;

export const heading = () =>
  html`
    <h1>Second Story</h1>
  `;
```
2. using webpack results in the following menu
  - Paragraph
  - Heading
3. using vanilla es module imports results in the following menu
  - Heading
  - Paragraph

**Expected behavior**
Have storybook have the same story order when using webpack and when using es modules.

**strawman proposal**
We could export a special `__exportOrder` array from within story files. This could be automatically done by a loader.

possible addition for the example above
```js
// 1.
export __exportOrder = ['paragraph', 'heading'];

// 2.
export __orderedExports = [paragraph, heading];
```

with 1. you would sort the * imports via this array and with 2. you would ignore all other imports and just use this ordered array contain all exports.

Personally I think 2. sounds better

What do you all think?

---
[1]: > A quick check shows the problem is not limited to webpack; Babel & TypeScript also make no attempt to sort exports. [tweet](https://twitter.com/robpalmer2/status/1205066610769354752?s=20)

### PR DESCRIPTION
**Pull request by daKmoR**
closes #9136
follow up of https://github.com/storybookjs/storybook/pull/9181

## What I did

As discussed in https://github.com/storybookjs/storybook/pull/9181 there have been 2 solutions to guarantee a story order if loaded via es modules. I went for the object. However, I have been missing the use case of rexports

```js
const myStory = () => html`Foo`;
export { myStory as notMyStory };
```

which currently produces the following `export const __orderedExports = { notMyStory };` which fails as `notMyStory` is not a local variable.

Therefore we should go with the previously discussed array of strings.

This Pull Request changes how loaders can guarantee the order of stories

Before:
```js
export const __orderedExports = { notMyStory };
```

After:
```js
export const __namedExportsOrder = ['notMyStory'];
```

## How to test

- use storybook without webpack and provide this export

## Notes

Related PR where we found the issue
https://github.com/open-wc/open-wc/pull/1171

### CODE REVIEW

File: lib/core/src/client/preview/start.js [hunk 1]
```diff
@@ -379,10 +379,20 @@ export default function start(render, { decorateStory } = {}) {
         );
       }
 
-      const { default: meta, __orderedExports, ...namedExports } = fileExports;
+      const { default: meta, __namedExportsOrder, ...namedExports } = fileExports;
+      let exports = namedExports;
+
       // prefer a user/loader provided `__orderedExports` object if supplied as es module exports
```
Comment (LarsDenBakker) [inline lib/core/src/client/preview/start.js]:
```suggestion
      // prefer a user/loader provided `__namedExportsOrder ` object if supplied as es module exports
```

**Review by LarsDenBakker — CHANGES_REQUESTED** [review]

File: lib/core/src/client/preview/start.js (hunk 1 above)
Comment (daKmoR) [reply lib/core/src/client/preview/start.js]: good catch - rephrased 👍

**Review by shilman — APPROVED** [review]
LGTM
